### ISSUE TITLE
LUCID orm lack of relationships

### ISSUE THREAD

**Issue by vieks** [adonisjs/adonis-framework#1]
When did you plan to implement model relationships ?
Meantime only the querybuilder is efficient to handle relations so the ORM is not very useful with this lack.

Do you have a release date ?
I want to use your framework for my next project.
Thanks.

**Comment by thetutlage** [comment]
I am actively working on it , and let me share the release cycle. Before that models have other benefits for example.

## Models can have

1. soft deletes.
2. Getter and setter for each field. 
3. Query scopes ( for readability )
4. Visible and hidden fields from query results.

But obviously , relationships are way more important.

## Release Cycle

Visit https://trello.com/b/ENQW36UC/version-1-1 , to see what is coming in next release cycle.

I follow SEMVER 

- so patches will go under version 1.0.x .
- 1.1.x will include relationships and database hooks ( before and after )

**Comment by vieks** [comment]
Awesome ! Good support.
I am very excited to see the evolution of your work.
I will stay tuned.

**Comment by thetutlage** [comment]
Now Lucid has support of relationships check out http://adonisjs.com/docs/1.0/lucid-relations

Upgrade lucid to `v1.0.3` or create a new app using `adonis-cli`. In a working on update docs that will make it easier to update modules in your existing application.

Have fun :)
