### ISSUE TITLE
soft deletes not working out of box

### ISSUE THREAD

**Issue by jacksonGross** [adonisjs/adonis-framework#10]
I am creating a Users schema via migrations, and noticed that it wasn't creating a 'deleted_at' timestamp when using table.timestamps(), so I added the column myself.
```javascript
exports.up = function(knex, Promise) {
    return Promise.all([
        knex.schema.createTable('users', function(table) {
            table.increments('id')
            table.string('username')
            table.string('firstname')
            table.string('lastname')
            table.string('email')
            table.string('password')
            table.boolean('isadmin').defaultTo('0')
            table.timestamps()
            table.timestamp('deleted_at').nullable().defaultTo(null)
        })
    ])
};
```
Perhaps this is something that could be added, considering that there are static methods to enable/disable these fields in the framework.

Also, a couple things I noticed about the documentation (not sure if this is the right place to raise these):
 - The documentation for the resourceful controller says that the destroy function is actually named delete http://adonisjs.com/docs/1.0/controllers#resourceful-controllers, while the ace command generates controllers with the function named 'destroy'.

 - Using a query on my Users model to retrieve all users does not ignore those that have a deleted_at timestamp on them and instead have to call fetch() to ignore these rows. Perhaps this is ok but I assumed that because Lucid supports soft deletes out of the box that it would default to use this on a retrieve all query. 

- The documentation surrounding the soft deletes is missing the yield keyword in almost every place it is referenced.

**Comment by thetutlage** [comment]
@jacksonGross Thanks for pointing out all the issues :+1: 

## Migrations

fields like `created_at` and `updated_at` are often used by everyone but soft deletes is not something everyone needs. It's you can switch it on or off from your models but people prefer keeping their tables clean by not adding unnecessary fields.

 ## Using Fetch

`fetch` is indeed required and here's why

All methods on query chain are chainable which means you can add as many `where` clauses or `orderBy` etc, so Lucid needs to know when you want to end that query chain. This is where `fetch` comes into the picture. It does everything required to make sure `soft_deletes`, `mutators` etc are called and makes final result out of it.

## Documentation

I am going to update docs and will improve them to have better documentation for every skill level. As i have a huge task list for `v2` you may not see much improvement in docs as of now. But i will fix these typos.

**Comment by thetutlage** [comment]
Fixed docs , let me know if you find any other issues :+1:
