### ISSUE TITLE
adonis -h too slow

### ISSUE THREAD

**Issue by vinnie0921** [adonisjs/adonis-framework#1000]
It's too slow to display the result everytime
I waited 5sec above for every command

## Package version
adonis 4.1.0

## Node.js and npm version
Node.js v10.8.0
npm 6.4.1

## Sample Code (to reproduce the issue)
just type: adonis -h
adonis
adonis route:list

## BONUS (a sample repo to reproduce the issue)
MAC air 13-inch 2015 early
RAM: 4GB
SSD: 128G

**Comment by ShadowPaz** [comment]
it would be nice if you add more context, because I had reproduce those three commands and I only wait 2 secs for each one 

So if you have a group of routes or anything else please add them

**Comment by viniciusgati** [comment]
1 sec on windows 10 and newest hardware (i5 8250U | 16gm ram)

**Comment by RomainLanz** [comment]
Hey guys 👋 

I'm currently working on the CLI and Ace to make it faster. 🚀

**Comment by ShadowPaz** [comment]
excuse me @RomainLanz do you need help? how I can contribute?

**Comment by RomainLanz** [comment]
There's no need for help for the moment. Thanks for asking 👍

**Comment by ujjwal-kr** [comment]
someone look at #1058
