### ISSUE TITLE
Heroku Error R10 - Adonis v4.1

### ISSUE THREAD

**Issue by kp222x** [adonisjs/adonis-framework#1001]
## Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
 
I know this is duplicate but other solutions are not working. I am not using .env file. This is adonis api only. Heroku is not able to bind the port.

**Comment by thetutlage** [comment]
What is the value of `PORT` inside environment variables set with in heroku console?

**Comment by kp222x** [comment]
Than you for the quick response. I figured it out. But to answer to your question, I have not set the `PORT` env variable at all. The problem was I wasn't ignoring `.env` file from .gitignore. I thought using `ENV_SILENT` is enough.


p.s. Awesome job with Adonis mate. Honestly never thought of Indian making an excellent Node Framework. single-handedly.

**Comment by thetutlage** [comment]
Closing since issue has been resolved 😄
