### ISSUE TITLE
Multiple validator on single route

### ISSUE THREAD

**Issue by egodasa** [adonisjs/adonis-framework#1002]
I'm trying to assign 2 validator to single route like this
```
Route.get('jenis-pengguna', 'JenisPenggunaController.show').validator(['SortJenisPengguna','Pagination']);
Route.get('jenis-pengguna', 'JenisPenggunaController.show').validator('SortJenisPengguna','Pagination');
```
And both are not working. Only first validator working. Is AdonisJS support multiple validator on single route? I'm not creating a resource controller. Just trying to validate query string for paginate and sort my API.
Thanks.

**Comment by thetutlage** [comment]
@egodasa Currently multiple validators are not supported. However, you can keep your rules seperate Javascript files and use require them inside your Validators.

Regarding, **sort my API**
I am not sure why you are using validators for sorting data
