### ISSUE TITLE
Append data to model JSON

### ISSUE THREAD

**Issue by behnamazimi** [adonisjs/adonis-framework#1003]
I'm looking for the Laravel append functionality in lucid. I mean I want to add a parameter to fetched JSON like what append did in the Laravel.

I tried the Mutators but there was not the solution! 
Another way is loops, like "for" or "map" on the fetched data but it's not best practice! Also, the result is different when I work with ORM and when fetch data by Query Builder. 

The Query Builder return a valid array of data but ORM return rows! what is that "rows" ?! Does it mean the rows of my model in DB? If so, how should I loop on it?!

**Comment by thetutlage** [comment]
@behnamazimi 

Please don't expect me to read the Laravel docs and understand what `append` does and then code the solution for you.

I understand that AdonisJs is inspired by Laravel, but you guys have to also do some hard work and create actionable issues.

It will be nice, if you can share the current shape of your object and what is the desired shape.

**Comment by thetutlage** [comment]
I believe, you can get it working (unless is value is computed asynchronously) using `computed properties`.

```js
class User extends Model {
  static get computed () {
     return ['fake_param']
  }

  getFakeParam () {
     return 'whatever'
  }
}
```

and then fetching users will append this property.

```js
const users = await User.all()
users.toJSON()
```

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by farzanehp** [comment]
@thetutlage Hi, Can I use get computed conditionally? (For example, append `isOwner` property if request's userId is equal to object's userId?
