### ISSUE TITLE
Transaction query already complete, run with DEBUG=knex:tx for more info

### ISSUE THREAD

**Issue by LordZombi** [adonisjs/adonis-framework#1004]
Using:
`await Database.beginGlobalTransaction();` etc.

after calling BE (in Controller) multiple times I got an error:
`Transaction query already complete, run with DEBUG=knex:tx for more info`

Is this the right way to do DB transactions?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
