### ISSUE TITLE
Integrate passportjs with adonis

### ISSUE THREAD

**Issue by Nisthar** [adonisjs/adonis-framework#1006]
I am trying to integrate steam login with passportjs.

How can i use passportjs inside adonis? Should i simply do `auth.attempt` inside passportjs callback?

**Comment by thetutlage** [comment]
For what purpose are you using Passport js?

**Comment by Nisthar** [comment]
@thetutlage I am using pasportjs for steam login.

**Comment by Nisthar** [comment]
I have checked adonis-ally. It looks like passportjs. But It lacks documentation on how to create custom drivers.

**Comment by thetutlage** [comment]
What driver you looking for?

**Comment by Nisthar** [comment]
@thetutlage Thanks. I'll give this a try.

Anyway, If i have to authenticate without using ally. How would i do that? 
Does simply doing `auth.attempt` keep track of the auth session?

**Comment by thetutlage** [comment]
Yes. I suggest reading the docs thoroughly and also feel free to join our [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)

**Comment by Nisthar** [comment]
@thetutlage Thanks.

**Comment by Nisthar** [comment]
@thetutlage Just a correction in your code. It should be `before.providersRegistered` instead of `before.providersBooted`

**Comment by Nisthar** [comment]
Ok, I have tried this:

```javascript
const Config = require("@adonisjs/framework/src/Config");

hooks.before.providersRegistered(function() {
  ioc.extend("Adonis/Addons/Ally", "opskins", function() {
    console.log(new Config(`${__dirname}./../config/`));

    return new Opskins(new Config(`${__dirname}./../config/`));
  });
});
```

**Comment by annymosse** [comment]
@thetutlage i need passport for Oauth2 service and apps even for graphQL user auth, is there any plan to integrate passport or a similar lib?
