### ISSUE TITLE
Question about how to convert Database.raw() query result to JSON

### ISSUE THREAD

**Issue by kooyear** [adonisjs/adonis-framework#1007]
Question about how to convert Database.raw() query result to JSON, I use 
Database.raw('SELECT *, ( 3959 * acos( cos( radians(?) ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians(?) ) + sin( radians(?) ) * sin( radians( latitude ) ) ) ) AS distance FROM g_merchants ORDER BY distance LIMIT ?, ?;',[latitude,longitude,latitude,offset,count])

But I don't know how to convert the result to the JSON, what should I do?

**Comment by ShadowPaz** [comment]
Maybe you need to do this

`const data = Database.raw('SELECT *, ( 3959 * acos( cos( radians(?) ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians(?) ) + sin( radians(?) ) * sin( radians( latitude ) ) ) ) AS distance FROM g_merchants ORDER BY distance LIMIT ?, ?;',[latitude,longitude,latitude,offset,count])`

And after that use the `response.send()` according to docs data will be sent as JSON 

`return response.send(data)`


[Reference](https://adonisjs.com/docs/4.0/response#_basic_example)

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
