### ISSUE TITLE
Return Promise in Server handle function

### ISSUE THREAD

**Issue by adrian-gallardo-wizeline** [adonisjs/adonis-framework#1008]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

## Consider an RFC

Please create an [RFC](https://github.com/adonisjs/rfcs) instead, if

- Feature introduces a breaking change
- Demands lots of time and changes in the current code base.

*Delete the above section and the instructions in the sections below before submitting*

## Why this feature is required (specific use-cases will be appreciated)?

I'm trying to integrate fastify with Adonis, and I managed to get it working but with a small change on `Server.handle` function by exposing the Promise it generates.

Here is my working example of `server.js`:

```
function createFastifyServerHandler(fastify) {
  return serverHandler => {
    fastify.addHook('preHandler', async (request, reply) => {
      // Here is where I need to access the Promise created inside Server.handle function
      return serverHandler(request.req, reply.res)
    })
    return fastify
  }
}

const Fastify = require('fastify')
const fastify = Fastify()

new Ignitor(require('@adonisjs/fold'))
  .appRoot(__dirname)
  .fireHttpServer(createFastifyServerHandler(fastify))
  .catch(console.error)
```

The promise I'm willing to return is the one created in `Server.handle` in the following line: `this._executeServerMiddleware(ctx)`

The main reason I'm trying to make adonis work with fastify is because the latter has an easy way to integrate with `http2`

## Have you tried any other work arounds?

I've tried other workarounds and looking at the source code this was the way I got this working

## Are you willing to work on it with little guidance?

I could contribute with this change, but wanted to now first if this change will be allowed or if any could suggest a better way to achieve the same

**Comment by thetutlage** [comment]
Why would you use fastify with Adonis? They both are two different frameworks

**Comment by adrian-gallardo-wizeline** [comment]
Thanks for answering quickly @thetutlage, I appreciate your point of view.

The main reason I'm looking at fastify is because of easier `http2` integration.. it allows me to receive the `stream` within a controller action, so I can respond with additional resources using `http2 push` functionality.
Also, there are some other http2-related related fastify-plugins I'm willing to use, like `node-fastify-auto-push`

But, I still see in Adonis a more robust framework to develop and handle the model/data layer, that is why I was trying to get the best of both worlds..

I know this might be some very specific use case, that's why I've decided to create this issue before sending any PR, but I think the proposed change is kind of `harmless` so I wanted to discuss it.

If not possible, probably I will try to provide my own modified `Server` class to Adonis `Ignitor` instance (not sure how yet, but I suppose using `IoC` should be possible)
