### ISSUE TITLE
Adonisjs has something to do with binary file uploads?

### ISSUE THREAD

**Issue by plfqz** [adonisjs/adonis-framework#1009]
I'm doing file uploading, but our front-end standard is uploading binary pictures. I haven't found a way to handle this part of the document. Do you have a solution now?

**Comment by plfqz** [comment]
I'm doing file uploading, but our front-end's standards is uploading binary pictures. I haven't found a way to handle this part of the document. Do you have a solution now?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
