### ISSUE TITLE
I am trying to make a project in Adonis, and i am getting this error message. Please help, I am a beginner.

### ISSUE THREAD

**Issue by RadiGade** [adonisjs/adonis-framework#1014]
C:\Users\Rishi>adonis new ^C
    _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

  [1/6] 🔬  Requirements matched [node & npm]
  [2/6] 🔦  Ensuring project directory is clean [C]
  [3/6] ❌  Unable to clone repo [adonisjs/adonis-fullstack-app]

   ERROR  Command failed: git clone --depth=1 https://github.com/adonisjs/adonis-fullstack-app.git "C:\Users\Rishi\C"
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by RomainLanz** [comment]
Hey @RadiGade! 👋 

You need to have git installed in your system which seems to not be the case.

**Comment by RadiGade** [comment]
okay i downloaded git now what should i do next
#

**Comment by RadiGade** [comment]
nvm i had to use git cmd to get it to work thanks btw.

**Comment by RomainLanz** [comment]
Cool, closing this issue then.

Happy coding with Adonis!
