### ISSUE TITLE
Redirect unauthenticated user in 'Auth'

### ISSUE THREAD

**Issue by deromanenko** [adonisjs/adonis-framework#1015]
Shoudn't we add the abillty to redirect unauthenticated user right in the 'auth' somehow?
Like in Laravel:
https://github.com/laravel/docs/blob/5.7/authentication.md#redirecting-unauthenticated-users

Because it very often situation, when you just need to redirect user who try to get some routes in 'admin' group, but with default 'auth' behavior you can only get session error and need to create another middleware.

Sorry if I get something wrong about 'auth' and there is a better solution.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
