### ISSUE TITLE
Can not upload an image using axios 

### ISSUE THREAD

**Issue by begueradj** [adonisjs/adonis-framework#1020]
#### Summary

I want to upload an image to my AdonisJS REST API using axios from a Nuxt.js client application.
I noticed that data is always transferred successfully **as long as** it is not an image or any other file.

#### Client code:

```
async submit() {
  console.log(this.photo) // this is fine
  let data = new FormData()
  data.append('file', this.photo)
  let url = 'http://127.0.0.1:3333/upload'
  let options = {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  }
  await this.$axios.$post(url, data, options)
}
```
#### Server code:
This is the corresponding function on my controller:
```
async upload( {request, response} ) {                                                                                             
  console.log(request.all())    
}
```

#### Server output
I always get this in case of a file: `{}`

#### Context

- AdonisJs version 4.1
- Environment.: node v10.13.0 chrome 71, Ubuntu 18.04*

Thank you for any suggestions, 
Billal BEGUERADJ

#### Updated on 01/01/2019:
I tested my Nuxt.js client code as it is (without modifications) with a different RESTful API that I set using Flask (a Python framework), and this server clearly processes the request successfully.

**Comment by RomainLanz** [comment]
Hey @begueradj! 👋 

This is clearly more a question about how to use Adonis than a bug of the framework itself.

Please, [take a look at the documentation about how to upload a file with Adonis](https://adonisjs.com/docs/4.1/file-uploads) and [open a thread in the forum](https://forum.adonisjs.com/) if it didn't help.

**Comment by begueradj** [comment]
Hello,
Yes, I succeeded to upload images as described in the documentation. I just wanted to try with axios as a step before introducing Graphql into my application.
I asked this same question on the forum as well as on StackOverflow
Thank you.
