### ISSUE TITLE
E_INVALID_HASHER_DRIVER running on docker container

### ISSUE THREAD

**Issue by asantamarian** [adonisjs/adonis-framework#1024]
Im running a API project inside a docker container but when I login to the API I get this error:

"E_INVALID_HASHER_DRIVER: Hash driver bcryptmysql does not exists.\n> More details: https://err.sh/adonisjs/errors/E_INVALID_HASHER_DRIVER"

Im trying to find out what I am missing inside the container.

I added bcrypt but still no luck.

thanks in advance

**Comment by RomainLanz** [comment]
Hey @asantamarian! 👋 

You missed configured your application, it seems that Adonis is looking for a `bcryptmysql` driver but it doesn't exist.

It should be `bcrypt` or `argon2`

**Comment by asantamarian** [comment]
I found the problem @RomainLanz I was really stupid thing, .env was not updated inside the container.

Thanks
