### ISSUE TITLE
websocket broadcast anywhere getChannel undefined

### ISSUE THREAD

**Issue by toknT** [adonisjs/adonis-framework#1028]
since https://adonisjs.com/docs/4.1/websocket-server#_broadcast_from_anywhere
```js
    const channel = Ws.getChannel('chat')
    console.log(channel);//output undefined
```

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by toknT** [comment]
@thetutlage  sorry I wrote a bad issue,  and I tink i found the same issue https://github.com/adonisjs/adonis-websocket/issues/55#issuecomment-399845174 

and I found *The topic method returns null when no one has subscribed* but the topic still null 

my client code it successed subscriped and send message 

```js
            ws.getSubscription('chat').emit('message', {
                body: message
            })
```
