### ISSUE TITLE
websocket broadcast from ace command

### ISSUE THREAD

**Issue by toknT** [adonisjs/adonis-framework#1029]
Does websocket can broadcast in ace command(it work well in http controller)? 

it's a nice framework and given me a nice way to deal ws, but I can't broadcast it from ace command .

same question found in here https://forum.adonisjs.com/t/websocket-broadcast-from-ace-command/1734

**Comment by m1ng-s** [comment]
[copied from my answer on the forum]

From my understanding, the ace command (so as cronjob if you are going to implement) will start and execute in a new node process when you run the command which not in your application process. There are two processes and memory are not shared.
So the socket remain in your application process and your command will not reach them.

My suggestion is, you write a listener in your application for the command to trigger the broadcast and your ace command act as the client to connect to the application process like end user and trigger the event.

hope its help 😀 
If this solved your problem, please mark the thread solved as well, thanks

**Comment by toknT** [comment]
@m1ng-s  thanks your ansower make me understand why it now work . And I broadcasted it like end user to solve my problem.
