### ISSUE TITLE
Can we have mongoDB support too?

### ISSUE THREAD

**Issue by sabbirrahman** [adonisjs/adonis-framework#103]
Since it's a node.js framework it will be great to have mongoDB support. Developers then will be able to develop full stack JavaScript application.

**Comment by thetutlage** [comment]
I believe mongoosejs has a pretty solid implementation of MongoDB, and you can easily use it like you would do in any other node application.

Ideally you can wrap it inside a service provider but that would need some understanding of how adonis IOC container works.

**Comment by sudeepdk** [comment]
so adonisjs  team is planning to add mongodb/mongoose support to adonisjs... ?

**Comment by allanfreitas** [comment]
@sabbirrahman @sudeepdk @flashvnn 

Hi, 
I've just published a npm package that integrates
**Mongorito**(mongodb package that use ES6 generators) with **AdonisJS** :)

I hope it helps someone.

https://www.npmjs.com/package/adonis-mongorito
https://github.com/allanfreitas/adonis-mongorito

**Comment by kristianmandrup** [comment]
The community provided mongodb adapters should at least be mentioned in the docs under DB support. I almost moved on since I refuse to be stuck with the limitations of SQL DBs. 
Thanks for adding these adapters!!!

**Comment by RomainLanz** [comment]
Hey @kristianmandrup !

Only official adapter/driver will be on the documentation. There's an [awesome-adonisjs](https://github.com/zgabievi/awesome-adonisjs) repository if you want third party module.

**Comment by kristianmandrup** [comment]
I understand that. How about a community section in the docs or Faq with Mongo as one frequent question?

**Comment by thetutlage** [comment]
I see a lot of people making recommendations on do X or do Y, whereas no one even has time to submit a PR 

I am not going to write docs on others modules/providers, so that when they don't work people create another issue, saying it doesn't work and then saying Adonisjs should be careful on adding things to documentation.

As Romain said, there is an awesome-adonis repo. If you find something useful, create a PR their and tweet about it

**Comment by jay-jlm** [comment]
2018 update: a quick google/npm search revealed quite a few community projects related to this subject.
Here's a couple of them:
https://github.com/duyluonglc/lucid-mongo
https://medium.com/@juampi92/mongoose-models-with-the-mighty-adonis-js-715cd83b923f
