### ISSUE TITLE
loading uploaded files via  browser url

### ISSUE THREAD

**Issue by Geowan** [adonisjs/adonis-framework#1033]
I have already uploaded my files successifully and i can see the file in the tmp uploads folder

What i would like to do is to access the same uploaded picture from the browser url. I have tried

       localhost://3033/uploads/mypic.jpg

But the above fails.
I have also tried manually moving the file to the storage directory the accessing it via
      localhost://3033/storage/mypic.jpg

  But also this fails
 How do i access the uploaded files via a browser url or what am i missing out.

I have also checked on the documentation and this is not pointed out of files uploads or even storage

**Comment by RomainLanz** [comment]
Hey @Geowan! 👋 

You need to use the `move()` method as state [in the documentation](https://adonisjs.com/docs/4.1/file-uploads).

Also, this is not an issue with Adonis but more a question about how to make some code. Please, use the [forum](https://forum.adonisjs.com/) or the [Discord server](https://discord.gg/vDcEjq6) for this kind of question.

**Comment by Geowan** [comment]
I think you misunderstood my question. Am not asking about moving the file, its about accessing the already moved or existing file via the browser url. 

Example suppose i have uploaded an image and i want to access the same image from a frontend framework like vuejs ill need the full path of the image on a url eg: https://localhost:3033/path_to_my_image which is not clear on the documentation on how to achieve this

Thats what am looking to achieve not moving a specific file.

**Comment by RomainLanz** [comment]
Then use the `public` directory and ensure that the [`StaticMiddleware`](https://github.com/adonisjs/adonis-api-app/blob/master/start/kernel.js#L53) is activated.

**Comment by Geowan** [comment]
Thanks this works. Maybe you may need to add this on the documentation to make it abit clearer

**Comment by annymosse** [comment]
you can use Helpers.publicPath() & drive.move
to like that
```js
const Helpers = use('Helpers')

Route.post('upload', async ({ request }) => {
  const profilePic = request.file('profile_pic', {
    types: ['image'],
    size: '2mb'
  })

  await profilePic.move(Helpers.publicPath(), {// => /public/custom-name.jpg
    name: 'custom-name.jpg',
    overwrite: true
  })

  if (!profilePic.moved()) {
    return profilePic.error()
  }
  return 'File moved'
})
```
or if you want to serve your file from other path as temp folder
```js
/**
 * return user files
 * @param {email,file}
 * @returs {file}
 */
Route.get('/file/:uid/:file', async({response,params})=>{// where :file is file name
    return response.download(Helpers.tmpPath(`uploads/${params.uid}/${params.file}`))
})
```

**Comment by hiukky** [comment]
@Geowan 

I've broken the head a little .. the documentation is not helping much in this upload issue .. but I can get it that way

```js
    const image = request.file('image', {
      types: ['image'],
      size: '2mb'
    })

    await image.move(Helpers.tmpPath('uploads'), {
      name: `${Date.now()}-${image.clientName}`,
      overwrite: true
    })

    console.log(image.fileName)

    if (!image.moved()) {
      return image.error()
    }
    
    return 'File moved'
```
