### ISSUE TITLE
Disable mysql query log in production

### ISSUE THREAD

**Issue by Arunkumarcs** [adonisjs/adonis-framework#1035]
## Disable mysql query log in production

I disabled the debug false in my databae,js file for mysql but still when every a query executes it outputs that on the console how do i stop it doing that.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

**Issue lags code samples or enough information to debug and help**

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
