### ISSUE TITLE
Is Adonis name associated with Illuminate? What is the meaning of Adonis

### ISSUE THREAD

**Issue by Cholowao** [adonisjs/adonis-framework#1036]
## Package version
4.1

## Node.js and npm version
6.2

**Comment by ShadowPaz** [comment]
This is not an issue, so I guess you could use the official forum right here ->https://forum.adonisjs.com/ to ask your question @Cholowao

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
