### ISSUE TITLE
Special characters and quotation

### ISSUE THREAD

**Issue by mfauzaan** [adonisjs/adonis-framework#1037]
I cannot use Variable Substitution in adonisjs Env. 

If a value contains a $ and it is not intended to be a variable, it breaks.
for Example: 'pas$word'

**Comment by thetutlage** [comment]
Upgrade to `@adonisjs/framework@5.0.13` and make sure to escape the `$` sign.

```
pas\$word
```

**Comment by mfauzaan** [comment]
Would appreciate if this could be included in the documentation 👏🏻
