### ISSUE TITLE
API Request Validation

### ISSUE THREAD

**Issue by kevin1193** [adonisjs/adonis-framework#1038]
## Why this feature is required (specific use-cases will be appreciated)?
Same like what Laravel have done. I think it will be good for us to have a request validation for Adonis
## Have you tried any other work arounds?
I have tried to make a work around but it became messy on my end

## Are you willing to work on it with little guidance?
Yes I am

**Comment by thetutlage** [comment]
What is `API Request Validation`?

**Comment by kevin1193** [comment]
Same like what we have here https://laravel.com/docs/5.7/requests

**Comment by thetutlage** [comment]
I cannot see any validation related docs on that page. Also, if you are expecting me to read the entire documentation and then decide, then it's not called help :)

If you want to contribute, bare minimum you have to do following:

1. Research on topic regardless of a specific framework or implementation.
2. Explain us properly why the feature is required with proper description and some code samples.
3. Explain what else you have tried, again proper description and some code samples.

**Comment by kevin1193** [comment]
Oh Sorry. I'll try to make it clearer. This is the correct link https://laravel.com/docs/5.7/validation

In Laravel we can extend an object Request where it has a custom validation rules. So before we pass the values to Controller it is validated already in the Request object.  Something like this 

`public function rules()
{
    return [
        'title' => 'required|unique:posts|max:255',
        'body' => 'required',
    ];
}`

**Comment by jsdecena** [comment]
@kevin1193 

You can already do this:

```
    async store({ request, response }) {

        const validation = await validate(request.all(), Address.rules)

        if (validation.fails()) {
            return response.status(422).json(validation.messages())
        }

        try {

            const address = await AddressRepository.create(request.only(Address.requests))

            return AddressTransformer.transform(address.toJSON())

        } catch (e) {
            return response.status(400).json({
                message: 'The address is unable to create.',
                status_code: 400
            })
        }
    }
```

My Rules:

```
    static get rules() {
        return {
            user_id: 'required',
            receiver_first_name: 'required',
            receiver_last_name: 'required',
            province: 'required',
            city: 'required',
            barangay: 'required',
            street: 'required'
        }
    }
```

**Comment by kevin1193** [comment]
@jsdecena  wow cool. Thanks a lot.
