### ISSUE TITLE
Descriptive Methods on Response missing on docs v4.0+

### ISSUE THREAD

**Issue by savioserra** [adonisjs/adonis-framework#1039]
The [Descriptive Methods](https://adonisjs.com/docs/3.2/response#_descriptive_methods) session is missing on the documentation, but it is still an available feature. Is it being deprecated any time soon?

Thank you for any help you can offer...

**Comment by RomainLanz** [comment]
Hey @savioserra! 👋 

PRs are welcomed 😄
