### ISSUE TITLE
Passing data to views from controller doesn't work

### ISSUE THREAD

**Issue by tremendus** [adonisjs/adonis-framework#104]
I'm new to this framework, but I love where it's going. light, lean, ES6 modules ... nice :) :+1: 

But I'm having an issue passing data to a view template from a controller, following the example in the docs. 

controller action: 
```
    * demo (request, response) {
      const view = yield response.view('demo')
      const data = { message : 'hello world' }
      response.send(view, data)
    }
```

view file: (jade, which compiles to html)
```
extends layouts/main

block body
  section
    .__wrapper
      //- img.__logo(src='/logo_white.svg')
      p  say: {{ message }}
```

html compiled from jade:
```
// only body shown for concise
<body>
  <section>
    <div class="__wrapper">
      <p> say: {{ message }}</p>
    </div>
  </section>
</body>
```

rendering in the browser: `say: < nothing >` : no message

This is following the docs exactly. What am I missing?

**Comment by thetutlage** [comment]
There is little typo with your code, it has to be

```javascript
* demo (request, response) {
   const data = { message : 'hello world' }
   const view = yield response.view('demo', data)
   response.send(view)
}
```

you always send data to the `view` method, not to the `send` method.Here are the docs http://adonisjs.com/docs/2.0/response#making-views.

You can also do call `sendView` as a one liner.

```javascript
* demo (request, response) {
   const data = { message : 'hello world' }
   yield response.sendView('demo', data)
}
```

**Comment by tremendus** [comment]
Ok, I understood. Thanks for pointing that out. Again, its a great tool!
