### ISSUE TITLE
Migration not working while creating relationships.

### ISSUE THREAD

**Issue by bhavikji** [adonisjs/adonis-framework#1040]
Hi, I am trying to create a relationship between user and token following the doc, but when I am running the migration I am getting this error

`TypeError: table.integer(...).unsigned(...).references(...).inTable is not a function `

After doing a little bit of googling I even tried 

`table.integer('user_id').index().references('id').inTable('users');`

but I am getting the following error
`TypeError: CE.InvalidArgumentException is not a constructor`

if none of the above following ways are right then what is the right way to create a relationship in migration?

This is my users table

```
class UserSchema extends Schema {
  up () {
    this.create('users', (table) => {
      table.increments()
      table.string('first_name', 80)
      table.string('last_name', 80)
      table.string('email', 254)
      table.string('password', 60)
      table.string('phone_no', 80)
      table.string('profile_pic')
      table.integer('status')
      table.timestamps()
    })
  }

```
  down () {
    this.drop('users')
  }
}

And this is my token migration file

```
class TokensSchema extends Schema {
  up () {
    this.create('tokens', (table) => {
      table.increments();
      table.integer('user_id').index().references('id').inTable('users');
      table.string('token', 255).notNullable().unique().index();
      table.string('type', 80).notNullable();
      table.boolean('is_revoked').defaultTo(false);
      table.timestamps()
    })
  }

  down () {
    this.drop('tokens')
  }
}
```

**Comment by RomainLanz** [comment]
Hey @bhavikji! 👋 

This is the code you should use:
```js
table.integer('user_id').unsigned().references('id').inTable('users')
```

If you cannot get it working, could you please create a repository with the minimum amount of code to reproduce the issue?

**Comment by jsdecena** [comment]
@bhavikji 

Maybe this would help?

```
      table.integer('user_id').unsigned()
      table.foreign('user_id').references('users.id')
```

**Comment by bhavikji** [comment]
@jsdecena  @RomainLanz  hey, tried both things but none of the thing is working even I am getting error   table.text is not a function
when I trying to add a text field
 table.text('message','text');

**Comment by jsdecena** [comment]
@bhavikji This is a different issue already. I suggest you try to do the first thing before you add the 
```
table.text('message','text');
```

If it is still not working, follow @RomainLanz suggestion to create a repository to reproduce your issue.

**Comment by bhavikji** [comment]
this one worked for me.

`table.integer('user_id').unsigned().references('users.id');`

another issue was because I am using MongoDB in the backend and mongo doesn't support text type so for that I need to keep it string with a length specified.

**Comment by RomainLanz** [comment]
@bhavikji MongoDB doesn't even support relation since it's a non-relational database system.

I'd recommend to stay away from MongoDB for any long-live storage.
