### ISSUE TITLE
Column name model

### ISSUE THREAD

**Issue by victorgois07** [adonisjs/adonis-framework#1043]
Please, I need help to change the name of the columns in the model, so that the user does not know the name of the columns of the database

**Comment by ShadowPaz** [comment]
first point: This is not an issue, so it would be better to ask this on: **https://forum.adonisjs.com/**

second point: under which scenario a user would know the column names? for this scenario why not only write an alias for every column inside your query to rename every one of them

**Comment by jsdecena** [comment]
I agree with @ShadowPaz with posting this in the forum. Also, if you do not want your users to know the real name of your columns, you could use a transformer / serializer. [Here you go](https://github.com/SeyZ/jsonapi-serializer)

**Comment by victorgois07** [comment]
Yes, I understand!! Sorry for the inconvenience

**Comment by RomainLanz** [comment]
This is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

**Comment by jonaselan** [comment]
Renames a column from one name to another.

```
this.table('user', table => {
      table.renameColumn('old_name', 'new_name')
})
```
