### ISSUE TITLE
Improved query/SQL Builder

### ISSUE THREAD

**Issue by eldinphp** [adonisjs/adonis-framework#1044]
Hello guys

in the first place, thanks for such a  cool, neat Node Framework, I really like it. <3

However, I must admit I am a bit lost building complex queries.

I am trying to make a complex search on my website, where users can select multiple different values, for example, in simple words it would be like : Find me a **new** phone with brand **Samsung** from **location Amsterdam** which costs **between 400 and 600 $.**

Now, I can use where() function , but it's kinda hard to make exact search with all these values at the same time

It would  be a great idea if we could manually build queries, like in PHP, where you concatenate a query, for example

if(something == true)
query + = "WHERE id = 1"

if(somethingElse = true)
query + = "WHERE location = Amsterdam

if(thisIsTrue = true)
query + = "WHERE item = 'new'

etc etc.. it's just a basic example.

Or maybe I just need to improve my knowledge about queries in general  ?

Thanks..

**Comment by jsdecena** [comment]
Maybe you want to use a Full-Text Search package? https://www.npmjs.com/package/full-text-search OR use Elastic Search?

**Comment by ShadowPaz** [comment]
in fact this is not a complex query, you only need to know more about the query builder and the LUCID ORM, here you have a resource to start 

https://github.com/ShadowPaz/adonis-tips/blob/master/Adonis%20Framework%204%20%20Cheat%20sheet%20Part%208.md

**Comment by eldinphp** [comment]
Hello okay, thanks for the idea, I heard before about Elastic Search, but never really considered it.. good idea, good luck guys :)
