### ISSUE TITLE
Computed property crush app only on Linux

### ISSUE THREAD

**Issue by basilhskk** [adonisjs/adonis-framework#1046]
🐛 This bug happens only in linux (both arm and x86). Works well on windows 10 and mac OS mojave.
🐛 
## Package version
4.1.0
## Node.js and npm version

node : v8.12.0
npm : 6.8.0

## Sample Code (to reproduce the issue)

  static get computed () {
    return ['fullname','test']
  }

  getFullname ({ firstname, lastname }) {
    return `${firstname} ${lastname}`
  }

   getTest({
     firstname, lastname
   }) {

     try {
      return firstname + " " + lastname.substring(0, 1)
     } catch {
       return "anonymous"
     }
   }

## Error Message 
SyntaxError: Unexpected token {
SyntaxError: Unexpected token { 
 at /var/www/vhosts/example.com/app/Models/User.js(/var/www/vhosts/example.com/app/Models/User.js:1:1)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
