### ISSUE TITLE
Regular expression issue in validator

### ISSUE THREAD

**Issue by mritgupta** [adonisjs/adonis-framework#1049]
When using regular expression in a validator

## Package version
4.1.0

## Node.js and npm version
node 11.8.0
npm 6.5.0

## Sample Code (to reproduce the issue)
```js 
 get rules() {
    return {
      password:
        'required|regex: /^(?=.*[A-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$@])(?!.*[iIoO])S{6,12}$/'
    }
  }
```

Getting Error:
Invalid flags supplied to RegExp constructor '12}$/'

**Comment by RomainLanz** [comment]
Hey @mritgupta! 👋 

From your code sample, it seems that you have a syntax error with the quotes.

**Comment by thetutlage** [comment]
I suggest just through the docs of Indicative, it's documented https://indicative.adonisjs.com/docs/syntax-guide#_limitations

**Comment by mritgupta** [comment]
Yes, I got what is the issue.

Thanks a lot, Harminder
