### ISSUE TITLE
Stream Pipe Response Does Not Work 

### ISSUE THREAD

**Issue by christiancheng0731** [adonisjs/adonis-framework#1052]
Hello I tried returning an image through stream pipe using raw node response and I'm not getting any response. until I changed my env to SESSION_DRIVER=file and this only works in adonis-app boilerplate not in slim boilerplate since session is not included there.

This is weird because in simple express app it works.  

## Package version
4.1

## Node.js and npm version
latest

## Sample Code (to reproduce the issue)
```
Route.get('/file', async ({ response }) => {
  const qwe = fs.createReadStream(`./22.jpeg`)
  response.response.setHeader('Content-type', 'image/jpeg')
  response.response.setHeader('Content-disposition', `inline; filename="22.jpeg"`)
  qwe.pipe(response.response)
})
```

**Comment by thetutlage** [comment]
Set `response.implicitEnd = false`. More on same in the documentation https://adonisjs.com/docs/4.1/response#_making_response

**Comment by christiancheng0731** [comment]
Thanks
