### ISSUE TITLE
Subdomain can access main domain routes

### ISSUE THREAD

**Issue by mathieuh** [adonisjs/adonis-framework#1053]
@thetutlage the issue we talked about on AdonisJs discord.

## Package version
"adonis-version": "4.1.0",
"@adonisjs/framework": "^5.0.13",

## Node.js and npm version
v9.11.2
6.9.0

## Sample Code (to reproduce the issue)
Add this line to your /etc/hosts file ``127.0.0.1	test.localhost``
Create a simple repo with ``adonis new yardstick``, remove ``Route.on('/').render('welcome')`` from the ``routes.js`` file and add the following code:
```
Route.get('/', () => 'You\'re on the subdomain').domain('test.localhost')
Route.get('/', () => 'You\'re on the maindomain')
Route.get('/contact', () => 'You\'re on the maindomain')
```

Here is the behaviour:
When I go on ``test.localhost:3333`` it shows "You're on the subdomain".
When I go on ``localhost:3333`` it shows "You're on the main domain".
When I go on ``test.localhost:3333/contact`` it shows "You're on the main domain".
Apparently it's not the expected behaviour and you shouldn't have to add ``.domain('localhost')`` to your main domain routes to prevent your subdomain from accessing them.

## BONUS
Repo to reproduce the issue -> https://github.com/mathieuh/domain-bug

An issue about it was opened here -> https://github.com/adonisjs/adonis-framework/issues/971

@RomainLanz kind of answered here -> https://forum.adonisjs.com/t/routing-domains-doesnt-care-for-domain-while-routes-are-same/2178

**Comment by mathieuh** [comment]
@annymosse thank you, actually I know how to solve it, its just that I have a lot of routes and I didn't want to put ``.domain`` on all my ``www`` routes plus I talked to @thetutlage who told me it might be a bug.
I just want to be sure of the behaviour of Adonis on this.

**Comment by annymosse** [comment]
@mathieuh you've a right ,for me i prefer the current methods coz i can handle each route by myself that making me review and organize my routes for each development to improve and scale my projects slow and fast at same time because i'm sure i didn't miss any router and his controller,i think my idea little buggy :man_facepalming: but who know maybe this my secret that making me grow up and faster as a coder .

**Comment by ujjwal-kr** [comment]
someone look at #1058

**Comment by RomainLanz** [comment]
Closing since not actionable.
