### ISSUE TITLE
create items unique to the foreign key

### ISSUE THREAD

**Issue by neydoo** [adonisjs/adonis-framework#1056]
How do I create a constraint such that if a value already exists with the same foreign key, it won't save, but will save if the value exist but with a different foreign key?
e.g phone -> windows OS saves
laptop -> windows OS saves
but if you enter either of them again it won't save

**Comment by RomainLanz** [comment]
Hey @neydoo! 👋 

This is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
