### ISSUE TITLE
Changing structure of result on model's paginate method?

### ISSUE THREAD

**Issue by BatuhanK** [adonisjs/adonis-framework#1057]
Is there a way to change returning data structure `.paginate()` method? (without ugly hacks after result came in)

For example, this is default result:

```
    "total": "414",
    "perPage": 12,
    "page": 1,
    "lastPage": 35,
    "data": [//items here]
```

And this is what I want (when I use on Article model)

```
    "total": "414",
    "perPage": 12,
    "page": 1,
    "lastPage": 35,
    "articles": [//items here]
```

**Comment by thetutlage** [comment]
I don't think this output even makes sense. If you are writing an API server, then you would want to return consistent output and not different output based upon the underlying model.

I will never use an API which returns the main data in different keys for every endpoint. For example:

1. Use `response.articles` when making request to `/articles`.
2. Use `response.comments` when making request to `/comments`.

**Comment by BatuhanK** [comment]
I agree but this is a legacy project and clients are already in market so I have to adopt :/

@thetutlage

**Comment by thetutlage** [comment]
Assuming the values are saved to variable `result`, you can do following.

```js
result.articles = result.data
delete result.data
```

**Comment by BatuhanK** [comment]
> Assuming the values are saved to variable `result`, you can do following.
> 
> ```js
> result.articles = result.data
> delete result.data
> ```

```js
result.article_count = result.total
result.last_page = result.lastPage
result.articles = result.data
delete result.total
delete result.lastPage
delete result.perPage
delete result.page
delete result.data
```

This is ugly :( I have too many legacy endpoints and this code should repeat itself. Do you have any suggestion?

**Comment by jsdecena** [comment]
@BatuhanK Why don't you use a transformer instead? https://github.com/rhwilr/adonis-bumblebee

**Comment by thetutlage** [comment]
Avoid repetition in any sort of application is more of a programming question and not really related to AdonisJs.

I will close this issue, and you can discuss about it on discord or forum
