### ISSUE TITLE
Bad requests and 404 errors returns HTML when working with api

### ISSUE THREAD

**Issue by ujjwal-kr** [adonisjs/adonis-framework#1058]
Well,  400 bad requests and unexpected type errors are good in HTML format when working with fullstack apps but, in --api-only, is should just return an error JSON object

` <section class="error-page">
            <section class="error-stack">
                <h3 class="error-status">400</h3>
                <div class="error-title">
                    <h4 class="error-name"> SyntaxError </h4>
                    <h2 class="error-message"> Unexpected token t in JSON at position 2 </h2>
                    <p class="error-links">
                        <a href="https://forum.adonisjs.com/search?q=Unexpected token t in JSON at position 2" target="_blank" title="Search on the official forum">
                            <i class="fab fa-discourse"></i>
                        </a>`

I always have to scroll down into POSTMAN and look in the HTML.
Hope you will fix this soon..

**Comment by thetutlage** [comment]
May I why you have to spam all other issues?

**Comment by ujjwal-kr** [comment]
sorry :(
for fast response..

**Comment by thetutlage** [comment]
The error handler works on the principles of **Content negotiation**. If you will define `Accept: application/json` in the request header, then the error message will be returned in JSON, rather than HTML.

**Comment by ujjwal-kr** [comment]
Thanks a lot !
