### ISSUE TITLE
Running node ace commands when firing the http server fails

### ISSUE THREAD

**Issue by Geowan** [adonisjs/adonis-framework#1062]
Am trying to run a node ace commands when firing the httpserver during npm run dev but the commands are not executed.

I have adonis scheduler commands run via node ace run:scheduler. When i manually run the command manually it works. So i have decided to add it in the loadcommands that is

on the server.js

       const { Ignitor } = require('@adonisjs/ignitor')
             new Ignitor(require('@adonisjs/fold'))
            .appRoot(__dirname)
          .loadCommands('node ace run:scheduler') //added this
          .fireHttpServer()

## Package version
      3.2

## Node.js and npm version
      npm version 6.5.0
      node version v11.9.0

## Sample Code (to reproduce the issue)
       const { Ignitor } = require('@adonisjs/ignitor')
             new Ignitor(require('@adonisjs/fold'))
            .appRoot(__dirname)
          .loadCommands('node ace run:scheduler') //added this
          .fireHttpServer()

You can also retry running this with the default command like migration and it doesnt work. Like

        const { Ignitor } = require('@adonisjs/ignitor')
             new Ignitor(require('@adonisjs/fold'))
            .appRoot(__dirname)
          .loadCommands('node ace migration:runr') //run migrations
          .fireHttpServer()

Why does this fail?

**Comment by thetutlage** [comment]
I am not sure from where inside the docs or code you found that passing `node ace run:scheduler` to `loadCommands` method will run it.

Also, the scheduler must run inside it's own process.

**Comment by Geowan** [comment]
@thetutlage am running this on the server.js file which is the file that is run initially to start the application.

You can see the file server.js even on the default adonis blog demo on github on the link https://github.com/adonisjs/adonis-blog-demo.

Open the file and youll see the comments on  loadCommands
