### ISSUE TITLE
Writing data to .env fails

### ISSUE THREAD

**Issue by Geowan** [adonisjs/adonis-framework#1064]
Am trying to write to .env files as per the documentation on
[Documentation on writing to .env](https://adonisjs.com/docs/3.2/env#_readingwriting_values)

So i have added

        const Env = use('Env')
        Env.set('API_URL', 'https://test.dev')

I fetch the value via
  
          Env.get('API_URL', 'test') //this works

Fetching during runtime works but the value is not written to the .env file so when i restart the server the value doesnt exists.

## Package version
       6.4.1

## Node.js and npm version
     npm version 6.5.0
     node version v11.9.0

Why does the Env.set fail to write to the actual .env file

**Comment by vyobukhov** [comment]
`Env.set` was always used only for in-memory changes in both 3.0 and 4.0 branches. Here is a note from the official 4.0 docs:
> Config.set will only change the value in-memory. It will not write the new value to your config file.

See more: https://adonisjs.com/docs/4.1/configuration-and-env#_config_provider

**Comment by Geowan** [comment]
Thanks i see,
