### ISSUE TITLE
Controller Middleware

### ISSUE THREAD

**Issue by leandromatos** [adonisjs/adonis-framework#1065]
Is it possible to add a middleware in the controller like Laravel?

https://laravel.com/docs/5.8/controllers#controller-middleware

**Comment by jayrchamp** [comment]
@leandromatos I don’t think that is possible with Adonis. As Virk said [here](https://forum.adonisjs.com/t/can-middlleware-be-used-inside-controller-instead-in-routes-file/205/3),  routes should be considered as a single source of truth to find what all will be executed when a route get’s hit.

Cheers 🥂

**Comment by thetutlage** [comment]
More than that, I don’t think it as a great option, since you have look at all controller files to see the middleware they use. Also, Adonis cannot precompile middleware unless it scans all the controller files, which will slow down the boot cycle

**Comment by leandromatos** [comment]
Hum... It's true. I not thought about that.

Thanks for reply guys.
