### ISSUE TITLE
Latest type-is release breaks body-parser

### ISSUE THREAD

**Issue by SAGV** [adonisjs/adonis-framework#1067]
So the latest release of `type-is` package which is used in `node-req` has a new [check](https://github.com/jshttp/type-is/blob/master/index.js#L257) in `tryNormalizeType` function:

```
if (typeof value !== 'string') {
    return null
}
```

The release was made today. 

Unfortunately, it brakes adonis body parser since body type check stops working and returns false on all types (aka `this._isType(request, this.jsonTypes)`). 

By default `node-req` tries to get the latest `type-is` version and hence all the users who made a fresh adonis install in the last few hours wouldn't be able to get a request body.

I'm not sure whether this issue should be in `node-req` (by the way. [npm page](https://www.npmjs.com/package/node-req/v/1.0.3) has a wrong github repo link) or in body-parser repo. So I'll post it here since it is the main adonis repo.

## Package version
"@adonisjs/framework": "^5.0.13",
"@adonisjs/bodyparser": "^2.0.9",

## Node.js and npm version
10.15.3

## Sample Code (to reproduce the issue)
request.all() or any other request
To reproduce, make a fresh adonis install and do a POST with any body (I tested on `application/json`.

**Comment by SAGV** [comment]
@thetutlage @RomainLanz might worth taking a look ASAP… The quick fix would be to set a `node-req#type-is` dependency on stictly to `1.6.16` version. 

However, as I mentioned above the link to the `node-req` repo @ npm is broken so I'm not sure which `node-req` repo is the proper one…

**Comment by Lewis2608** [comment]
I've been trying for 6 hours to see what the problem was. I thought it was the only 😢  Thank you @SAGV

**Comment by jericopulvera** [comment]
I'm having the same problem. 

>The quick fix would be to set a node-req#type-is dependency on stictly to 1.6.16 version.

where do I set this?

**Comment by jericopulvera** [comment]
@SAGV okay I understand it now. I though that I could set node-req#type-is: '1.6.16' in package.json 

it should be

```
"type-is": "^1.6.16",
```

**Comment by thetutlage** [comment]
It's weird that they released a breaking change in a patch version. Looking into it

**Comment by devanandb** [comment]
Thanks @thetutlage ! Really stuck and we have to go love today :(, if you can even give me a quick fix, I will use that to at-least get through today and tomorrow!

**Comment by thetutlage** [comment]
Remove `node_modules` and `package-lock.json` file and run `npm i` again. Should be good to go after that.

**Comment by thetutlage** [comment]
Thanks @SAGV for bringing it to the notice. If you guys can confirm the fix, I will close this issue

**Comment by kooyear** [comment]
So strange, all my post body is empty, why

**Comment by devanandb** [comment]
> Thanks @SAGV for bringing it to the notice. If you guys can confirm the fix, I will close this issue

Awesome @thetutlage it works now!

**Comment by thetutlage** [comment]
Thanks 😄

**Comment by SAGV** [comment]
Thanks, @thetutlage !



> where do I set this?

@jericopulvera well, this bug was already fixed while I was sleeping. However, if you face similar issues with a different package, you can force-set sub-dependency version either with [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) or with [npm force resolutions](https://github.com/rogeriochaves/npm-force-resolutions) like this in `package.json`:

```
"resolutions": {
    "@adonisjs/framework/node-req/type-is": "1.6.16"
  },
```

**Comment by dougwilson** [comment]
> It's weird that they released a breaking change in a patch version. Looking into it

@thetutlage it was unintentional; no one reported it to the `type-is` repo until a few hours ago, and so I pushed 1.6.18 with it fixed. Sorry for the trouble, though I didn't realize until just recently that it was a breaking change. I added a test suite to the repo as well for this case to prevent it from regressing again.

**Comment by mritgupta** [comment]
json type check in request return false, I am confiuse its related to type-is or any other package.

```js
const isJson = request.is(['json']);
```

**Comment by thetutlage** [comment]
Are you setting the `Content-type` as `application/json` for the request?

**Comment by mritgupta** [comment]
thanks @thetutlage 

Yes, I am setting.

It is previously working. today, I did NPM install and its break.

**Comment by mritgupta** [comment]
Now it starts working, I run again ```npm install```

I don't have an idea about what happened.

thanks @thetutlage
