### ISSUE TITLE
request.body is returning empty for all POST requests

### ISSUE THREAD

**Issue by devanandb** [adonisjs/adonis-framework#1068]
## Package version
^5.0.9

## Node.js and npm version
9.11.2 and 5.6.0

## Sample Code (to reproduce the issue)
Any Post request, has a request.body as empty object

**Comment by jericopulvera** [comment]
quick fix is located at  #1067

**Comment by thetutlage** [comment]
Closing in favor of https://github.com/adonisjs/adonis-framework/issues/1067
