### ISSUE TITLE
Payloads and files aren't processed because a update of dep type-is

### ISSUE THREAD

**Issue by wiliame** [adonisjs/adonis-framework#1069]
## Package version
^5.0.9

## Node.js and npm version
node 10.15.3
npm 6.4.0

## Sample Code (to reproduce the issue)
Any json payload, so request.file() and request.post() are empty always.

## BONUS (a sample repo to reproduce the issue)
No repo

----

The issue is described here:
https://forum.adonisjs.com/t/empty-request-all/3461

I have found the error, is described here:
https://forum.adonisjs.com/t/empty-request-all/3461/6

The issue appears at `request.is` which stopped working after type-is last commit, the library that uses `node-req` to determine the request type.

https://github.com/jshttp/type-is/issues/41

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonis-framework/issues/1067
