### ISSUE TITLE
TypeError: this.RelatedModel.query is not a function

### ISSUE THREAD

**Issue by wmtamit** [adonisjs/adonis-framework#1071]
in my project three model country, nationality and countrynationality.in this countrynationality model store nationality_id and country_id  then i give hasMany to nationality and hasOne to country.
when i access both at a time that time gives me error **TypeError: this.RelatedModel.query is not a function**.
i put code here 
=> CountryNationality model 
`  static get table(){
        return 'country_nationality'
    }
    static get hidden () {
        return ['created_at', 'updated_at']
      }
   country(){
      return this.hasOne(Country,'country_id','id')
     }
     nationality(){
       return this.hasMany(Nationality,'id','nationality_id')
     }

      `
=> country model

`static get table () {
    return 'country'
  }
  static get hidden () {
    return ['created_at', 'updated_at']
  }`

=> nationality model 
`static get table() {
    return "nationality";
  }
  static get hidden() {
    return ["created_at", "updated_at"];
  }`

-> i access country and nationality model like this 

`const relationcountry = await CountryNationality.query()
        .with("country")
        .with("nationality")
        .where("id", countrynationality.id)
        .fetch();`

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
