### ISSUE TITLE
Response time varying on localhost with much of a difference

### ISSUE THREAD

**Issue by mapsgeek** [adonisjs/adonis-framework#1072]
## Package version
"version": "4.1.0"

## Node.js and npm version
v8.12.0 and 6.4.1

## Sample Code (to reproduce the issue)
i have the following code in a controller to send back a file, the issue is that when you hit the end point for the first time response time takes 400-300 ms on localhost, requests after that first one takes only 4-5 ms, wait for a few seconds and hit the end point again, it will take the longer time and so on ... any explanation ??

--- edit -----
this happens with any kind of `request.send` not just the await for `drive.get`

![image](https://user-images.githubusercontent.com/10188264/57085601-d3a6e780-6cfc-11e9-83c2-b765b1515d31.png)

```
async getFile({ request, response }) {
    let file = await Drive.get("./store/HelaBoundary_2.json")

    response.send(file)
  };
```

**Comment by RomainLanz** [comment]
Hey @mapsgeek! 👋 

Could you please create a repository to reproduce the issue?

**Comment by guiquintelas** [comment]
Having the same problem with the --api-only boilerplate

Env:
Win 10
Node: 8.11.1
Npm: 5.6.0

**Comment by mapsgeek** [comment]
same as  the comment above nothing more than the boilerplate.

**Comment by RomainLanz** [comment]
Hey @mapsgeek, @guiquintelas! :waves:

After some debugging (thanks to @targos) it appears to be the `nslookup` of your browser that takes some time and not Adonis.

You could maybe avoid this by prefetching the DNS upfront using the `link` tag with `rel="dns-prefetch"`. More on this in **Addy Osmany** article about [Preload, Prefetch And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf).

**Comment by mapsgeek** [comment]
@RomainLanz  how does this relates to a get request sent by angular or any other framework ?
