### ISSUE TITLE
youtube tutorials

### ISSUE THREAD

**Issue by Samaras2018** [adonisjs/adonis-framework#1073]
## Hi there, 
i'd like to say why you guys don't make a YouTube channel for basic to advanced tutorials🤔
Adonis is very Js friendly and has potentials to be a " first choice " to develop node apps💯
I hope to see official YT channel about adonis soon👏👏

**Comment by RomainLanz** [comment]
Hey @Samaras2018! 👋 

Thanks for your question.
We planned to create more learning content after 5.0.

I'm closing this since it's a question and not an issue with the framework itself.
