### ISSUE TITLE
Can not update Lucid model primary key

### ISSUE THREAD

**Issue by begueradj** [adonisjs/adonis-framework#1074]
I asked this as a question in the forum but it is clearly a bug (AdonisJs 4.1).

According to the [documentation](https://adonisjs.com/docs/4.1/lucid#_inserts_updates), calling `save()` on a model instance, AdonisJs is smart enough to guess whether it should perform an update or create a new database entry. I found out this is true only when the custom primary key is not involved by the update operation.

## Code snippet
Try this:
```javascript
const oldUserName = params.id
const user = await User.find(oldUserName) 
console.log(user.toJSON()) // Right record
const newUserName = 'begueradj'
user.username = newUserName
// This should perform an update
await user.save() // Actually console.log(await user.save()) returns false

```

Actually no update is performed (and no instance is created)

## Important notes:
-  **`username`** is the primary key here (but I think this  [should not be an issue](https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/Model/index.js#L84))
- `save()` performs the update when the primary key is not involved
- This has other pesky implications such as hooks, setters and validators not taking effect when the custom primary key is concerned

## Bug origin
This bug is an issue related to the [_update()](https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/Model/index.js#L649) function:

```javascript
affected = await query
  .where(this.constructor.primaryKey, this.primaryKeyValue)
  .ignoreScopes()
.update(this)
```

The culprit line is this one:
```javascript
 .where(this.constructor.primaryKey, this.primaryKeyValue)
```
because this function searches for the record to update based on the primary key value whereas the new `primaryKeyValue` does not exist yet.

**Comment by mritgupta** [comment]
I think it may be an issue of a primary key, 

It cannot violate the rule:

The value is unique
No existing foreign keys are violated

Please check StackOverflow discussion [here](https://stackoverflow.com/questions/3838414/can-we-update-primary-key-values-of-a-table)

**Comment by begueradj** [comment]
Thank you for the feedback.
I do not agree with that post on StackOverflow. Suppose you have to manage product categories, what would be the good primary key ? I think it will be the name of the product category.
If we agree on this, then maybe you wrote 'Appels' instead of 'Apples', so you need to update the primary key in this context. @mritgupta

**Comment by andu99** [comment]
I use 5.0.9 and it's work.

`const user = await User.find(1)
  console.log(user.toJSON()) 
  const newUserName = '1'
  user.username = newUserName
  await user.save() `

// return
`{"id":1,"username":"1","password":"$2a$10$R/WlXsLFdOX6i2QncG/RC./UG1CxZUdN2cqqfrtyq0BJpZAsFb2pq","created_at":"2019-05-06 14:19:53","updated_at":"2019-05-07 09:22:35"}`

**Comment by begueradj** [comment]
I know it works that way, but try to set `username` as your primary key. @andu99

**Comment by RomainLanz** [comment]
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.
