### ISSUE TITLE
Boot function won't  override if using 'use'

### ISSUE THREAD

**Issue by guiquintelas** [adonisjs/adonis-framework#1075]
I'm new to Adonis so not 100% sure if I'm doing something wrong but I stumble upon this problem.

I've written a custom model class, to introduce new functions shared beetwen my models, but doing so the boot function within my models stopped been called. After some debugging I tried changing `use` for `require` solving the problem.

If this isn't a bug how do I know when to use `use` and `require`

## Package version
4.1.0

## Node.js and npm version
8.11.1 and 5.6.0

## Sample Code (to reproduce the issue)
````
//right output
//const Model = require('../Core/Model')

// wrong output
const Model = use('App/Core/Model')
````

1. Run `adonis serve --dev`, it should log `custom model call` then `user call`
2. Comment the `use` statementin App/Models/User
3. Uncomment the `require` statementin App/Models/User
4. Save. Logs correctly.

## Demo Repo
https://github.com/guiquintelas/adonis-bug

**Comment by gabrielperales** [comment]
I'm also new to adonis, so I'm not sure if I'm also doing it wrong, but I'm having an issue similar to this one. This is the code I have:

```javascript
'use strict'

const User = use('App/Models/User')
const Role = use('Role')

class Admin extends User {
  static boot () {
    super.boot()

    this.addHook('beforeCreate', async (instance) => {
      try {
        console.log('beforeCreate')
        const admin = await Role.pair('slug', 'administrator')
        instance.roles().attach([admin.id])
      } catch (e) {}
    })
  }

  static get table () {
    return 'users'
  }
}

module.exports = Admin
```

And the `console.log('beforeCreate')` is not being called, but the static method boot from `App/Models/User` is being called.

**Comment by gabrielperales** [comment]
Ok, @guiquintelas I found this issue wich is also related to this one https://github.com/adonisjs/adonis-lucid/issues/274 and seems like `boot` doesn't work on nested inherance.

**Comment by guiquintelas** [comment]
@gabrielperales using `require` works fine, but i'm not sure if it's the best practice

**Comment by thetutlage** [comment]
Closing since not actionable
