### ISSUE TITLE
Command to create database

### ISSUE THREAD

**Issue by dfmoreto** [adonisjs/adonis-framework#1076]
Required feature to avoid manually creating database.

NA

Yes! I want to help on it with little guidance =D

**Comment by guiquintelas** [comment]
I think you're describing migrations https://adonisjs.com/docs/4.1/migrations

**Comment by dfmoreto** [comment]
No, I mean to really run a command to create the database itself as we do with `create database xpto`. I don't know if I looked right, but I didn't see it on migrations.
I think it could have commands as `adonis database:create` and `adonis database:drop` that would run these creation and dropping database commands.

**Comment by RomainLanz** [comment]
Hey @dfmoreto! 👋 

That would be a great addition to the current CLI!
Looking forward to add it after 5.0 release.

**Comment by thetutlage** [comment]
Not something that needs to live on this repo and please follow the RFC process, if you want to propose features
