### ISSUE TITLE
Facebook Connect

### ISSUE THREAD

**Issue by koraysels** [adonisjs/adonis-framework#108]
How would you go about integrating facebook into adonis ?
We would like to use passportjs for facebook login but are unsure how we could implement this with adonis...

**Comment by thetutlage** [comment]
There is no official module to do this with Adonis. Passport is very tightly written for express. 

So i personally feel you will have a hard time integrating it. The best way to do is use the official Facebook api and use that.

**Comment by thetutlage** [comment]
Rest you can follow the framework development lifecycle here. https://trello.com/c/wns5DzT3/28-authentication-provider

Authentication provider will have a sibling module to support the social authentication.
