### ISSUE TITLE
npm ERR! Linux 4.18.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "i" "--global" "@adonisjs/cli"

### ISSUE THREAD

**Issue by nguyennamkkb** [adonisjs/adonis-framework#1081]
npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "i" "--global" "@adonisjs/cli"
help me. please

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue do not follow our guidelines.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
