### ISSUE TITLE
How to set up Passport in an Adonis project?

### ISSUE THREAD

**Issue by constantinpopa11** [adonisjs/adonis-framework#1084]
I'm working on an Adonis project and I'm trying to implement authentication using Passport. There are many examples on how to use it with express, but I can't configure it for Adonis.

I mostly understand what the code does, but the Adonis project is structured a bit differently. I don't understand where I need to pass the passport object, the return of passport.session() and so on, because there is no app object in my code. Is there a way to retrieve this object or where should I place my code?

```
app.use(session({ secret: 'anything' })); // session secret
app.use(passport.initialize());
app.use(passport.session()); // persistent login sessions
app.use(flash()); // use connect-flash for flash messages stored in session

// routes ======================================================================
require('./app/routes.js')(app, passport); // load our routes and pass in our app and fully configured passport
```

**Comment by mrdionjr** [comment]
Hi, if what you want is a simple authentication system then you should check the docs. Adonis has in-built authentication support as stated in this thread: https://forum.adonisjs.com/t/passport-js-integration/543/5

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
