### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Birblover** [adonisjs/adonis-framework#1087]
I was trying to install adonisjs on my recently-factory reset laptop, I have a brand new installation of node.js and I'm getting EACCES errors. I've attached the error log.
Thank you!
[2019-06-08T17_18_42_805Z-debug copy.log](https://github.com/adonisjs/adonis-framework/files/3268776/2019-06-08T17_18_42_805Z-debug.copy.log)

**Comment by rafaellaurindo** [comment]
This is because your current user, has not permission to write in global `node_modules` folder.

Line 514 from log:
`514: verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules'`

Try install using `sudo`, to grant all permissions:

```bash
sudo npm i -g @adonisjs/cli
```

Hope this helps!

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
