### ISSUE TITLE
.env.test file creation can cause issues with existing databases.

### ISSUE THREAD

**Issue by webdeveloperpr** [adonisjs/adonis-framework#1089]
Installing the` vowProvider` creates a `.env.testing` file. This file gets merged with the main `.env` file. If the user does not change the database name before running HTTP tests. It will overwrite the existing data.

## Why this feature is required (specific use-cases will be appreciated)?
It would  remove the possibility of overwriting an existing database.

## Have you tried any other work arounds?
Changing the database name on the .env.test file but it was already too late.

## Are you willing to work on it with little guidance?
Maybe

**Comment by thetutlage** [comment]
What alternative are you propsing?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
