### ISSUE TITLE
How to use local variable or function for all view templates

### ISSUE THREAD

**Issue by freehosting2016** [adonisjs/adonis-framework#109]
Hi,
i want to create a dynamic menu so there is any way to pass data for all view or for master template , In Laravel that is possible by using Service Provider

**Comment by thetutlage** [comment]
Same can be done by adding globals http://adonisjs.com/docs/2.0/views#extending-views

**Comment by freehosting2016** [comment]
thanks

**Comment by michaeljcalkins** [comment]
@thetutlage I'm running a ReactJS SPA is there similar functionality in v3?

Right now I'm just doing:

```
'use strict'

class HomeController {

    * index (request, response) {
        yield response.sendView('home', {
            isProduction: process.env.NODE_ENV === 'production'
        })
    }

}

module.exports = HomeController
```

But I was looking at this guy: http://adonisjs.com/docs/3.0/response#extending-response
