### ISSUE TITLE
camelCase table columns name

### ISSUE THREAD

**Issue by prakashbharti786** [adonisjs/adonis-framework#1090]
There should be a way to create camelCase columns name instead of sank_case. 
I try to find the solutions to create camelCase columns name of table auto-created by migration e.g.  "table.timestamp()"

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
