### ISSUE TITLE
How to get request values with processManually

### ISSUE THREAD

**Issue by vikrampunchh** [adonisjs/adonis-framework#1092]
```
  var folderName ='';
  request.multipart.field(async (name, value) => {
      console.log(name, value);
      folderName = value;
  });

  request.multipart.file('image', {}, async file => {
     // want to use folderName here
      url = await Drive.disk('s3').put( folderName + file.clientName, file.stream);
  });

  await request.multipart.process()
```

`request.multipart.file` exicutes before `request.multipart.field` so folderName i am getting `''` always.

**Comment by thetutlage** [comment]
When processing manually, you are reading the bytes from a stream. The stream output bytes as they are added to the stream and their order cannot be guaranteed.

## Alternatives?
1. Send folder name as a query string and not request body.
2. If you are not dealing with GB's of size, then simply process the uploads manually.
3. Use s3 direct upload from client side code (You have to read AWS docs for that)

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
