### ISSUE TITLE
Question - Extending Authentication Provider

### ISSUE THREAD

**Issue by lcsdms** [adonisjs/adonis-framework#1093]
Hi, how are you ? I have a external api for authentication, and would like to extend the authentication to use this api for getting the users information and validating the token , like in the "api" scheme, to use in the auth middleware, for websocket connections.

I've found on the version 3.2 how to on the docs https://adonisjs.com/docs/3.2/authentication#_extending_auth_provider, but  is there any way or instructions for the 4.1 version?

I've thought of creating a simple custom middleware for this, but I would like to be able to use the existing auth structure so I can make use of additional helpers and the auth middleware.

**Comment by RomainLanz** [comment]
Hey @lcsdms! 👋 

The documentation for extending the core can be find here https://adonisjs.com/docs/4.1/extending-adonisjs#_extending_providers.

Also, this is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
