### ISSUE TITLE
New project  pausing error

### ISSUE THREAD

**Issue by yasinakca** [adonisjs/adonis-framework#1097]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

**Comment by yasinakca** [comment]
When I create a new Adonis project it's always pausing. My os is Ubuntu 18.04. Can anyone have ideas for my problem?
![2019-07-02 17-03-37 ekran görüntüsü](https://user-images.githubusercontent.com/15368330/60519035-5d6a3580-9ceb-11e9-963e-eae80e073e30.png)

**Comment by mritgupta** [comment]
Can you explain more detail about the error,

Please check nodejs and npm veriosn 

Node.js >= 8.0.0
npm >= 3.0.0

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
