### ISSUE TITLE
error npm start

### ISSUE THREAD

**Issue by Mostafa-akbarzadeh** [adonisjs/adonis-framework#11]
hi. i when start projcet with npm start , display this error
...
> adonis-app@1.0.0 start /home/mostafa/Desktop/test/proje
> node --harmony_proxies server.js

Error: Cannot find module './parser'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mostafa/Desktop/test/proje/node_modules/adonis-validation-provider/node_modules/indicative/lib/validator.js:19:12)
    at Object.<anonymous> (/home/mostafa/Desktop/test/proje/node_modules/adonis-validation-provider/node_modules/indicative/lib/validator.js:174:4)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
...

**Comment by thetutlage** [comment]
quite weird , can you remove and re-install all dependencies using 

```
npm install
```

**Comment by Mostafa-akbarzadeh** [comment]
thank you .. but show this message

...
npm WARN package.json adonis-app@1.0.0 No repository field.
npm WARN package.json adonis-ace@1.0.3 No repository field.
npm WARN package.json adonis-commands@1.0.4 No repository field.
npm WARN package.json adonis-config-provider@1.0.3 No repository field.
npm WARN package.json adonis-fold@1.0.6 No repository field.
npm WARN package.json adonis-framework@1.1.2 No repository field.
npm WARN package.json adonis-lucid@1.0.3 No repository field.
npm WARN package.json adonis-validation-provider@1.0.1 No repository field.
...

**Comment by thetutlage** [comment]
It's fine these are warnings , does `npm start` works after this or not ?

**Comment by Mostafa-akbarzadeh** [comment]
no .. show error message 

Error: Cannot find module './parser'

**Comment by thetutlage** [comment]
Okay can you tell me the OS you are using and also paste `package.json` file of your project

**Comment by Mostafa-akbarzadeh** [comment]
OS : ubuntu 15.04  
package.jason:


{
  "name": "adonis-app",
  "version": "1.0.0",
  "description": "Folder structure for adonis application",
  "main": "server.js",
  "scripts": {
    "start": "node --harmony_proxies server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "adonis-ace": "^1.0.3",
    "adonis-commands": "^1.0.4",
    "adonis-config-provider": "^1.0.3",
    "adonis-fold": "^1.0.6",
    "adonis-framework": "^1.1.2",
    "adonis-lucid": "^1.0.3",
    "adonis-validation-provider": "^1.0.1",
    "formidable": "^1.0.17",
    "ouch": "^0.2.0-beta",
    "raw-body": "^2.1.2"
  },
  "autoload": {
    "App": "./app"
  },
  "devDependencies": {
    "sqlite3": "^3.1.0"
  }
}

**Comment by Mostafa-akbarzadeh** [comment]
thank you .. solved
sudo npm update
