### ISSUE TITLE
Reuse a query with some conditions

### ISSUE THREAD

**Issue by pichlou** [adonisjs/adonis-framework#1104]
Hi 
I want to reuse a query with some conditions
This is the query :
` var query = Trade.query().where('amount','>',amount);`
I want to get two copy without reference to query and run 'await' on them;
`var Ids = await query.pluck('id');`
`var result = await query.with('hasCurrency').paginate(page, limit);`

I used the clone() but it didn't work, What do I do?

**Comment by thetutlage** [comment]
Why not simply create a static on the model?

```js
class Trade extends Model {
  static amountQuery (amount) {
    return this.query().where('amount', '>', amount)
  }
}
```

and use it as follows:

```js
Trade.amountQuery(amount).fetch()

Trade.amountQuery(amount).with('hasCurrency').paginate()
```
