### ISSUE TITLE
edge template engine low speed when data changes  ❕

### ISSUE THREAD

**Issue by id1385** [adonisjs/adonis-framework#1105]
hi
when i tested adonis i was delighted with the high speed of  adonis than laravel
i tested speed for reponse of hello world and api with database query response , adonis  return response in avg 10 - 30 ms in my system , it is good because laravel take avg 80 - 180 ms for this test 

But when i tested [views](https://adonisjs.com/docs/4.1/views) I got sad 😥
because when i return view without data its take 10 - 30 ms and it is good
code : 
`Route.get('/index', ({ view }) => {
    let data = {
        username: 'it is test'
    };
    return view.render('index',data);
});`
**but when i change data (username ) that passed to view it is take +200 ms For First Time**
**why ?** 
Do i make a mistake?

if i want make an site like news that only return view (not api) with this result of time response its not good idea to use adonisjs !

**Comment by thetutlage** [comment]
I am not even sure, how exactly you are benchmarking the code and there can be many factors for things being slow or fast.

The `view.render` compiles the template for the first time and then caches the compiled template to subsequent requests are generally fast. I won't mind the request being a bit slower and then it being fast from there on.

Please share the source of your benchmarks, otherwise it is hard to comment on anything.

**Comment by id1385** [comment]
First tnx for replay.
- Sorry for bad English typing -
i dont  benchmarking .
now i have 2 question 

1 - when i run adonis serve --dev and start changing index.edge  template its not effected 
i must exit serve and reserve again !
why ?

**Comment by id1385** [comment]
2 - i serve in --dev mode 
i write below code in controller function and save and refresh page

    let data = [{
        "aa" : 1
    }];
    return view.render('index',data);

first time page time loading take 198 ms ! and next time take -20 ms
i back to code and change code to below and refresh page again


  let data = [{
        "aa" : 2
    }];
    return view.render('index',data);

first time loading page again take 198 ms ! why ? i only change 1 to 2

**Comment by PurwadiPw** [comment]
> First tnx for replay.
> 
> * Sorry for bad English typing -
>   i dont  benchmarking .
>   now i have 2 question
> 
> 1 - when i run adonis serve --dev and start changing index.edge template its not effected
> i must exit serve and reserve again !
> why ?

@id1385 

you sould read more about documentation or check the `adonis` cli. there is already about `serve` command
```
Usage:
  serve [options]

Options:
  --dev                Start development server
  -w, --watch <value>  A custom set of only files to watch
  -e, --ext <value>    A custom set of extensions to watch. In development, they will be merged with the default .js and .json
  -i, --ignore <value> A custom set of folders to ignore watching
  -p, --polling        Use polling to find file changes. Also required when using Docker
  --debug [value]      Start server in debug mode

About:
  Start Http server
```
use `adonis serve --dev -p` command to find file changes

*sorry for my bad english
