### ISSUE TITLE
DD function in adonisjs

### ISSUE THREAD

**Issue by id1385** [adonisjs/adonis-framework#1106]
is any function like dd function in laravel ? 

![image](https://user-images.githubusercontent.com/28746285/61235182-20219100-a74a-11e9-8e4b-8a91da9c25e1.png)

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by annymosse** [comment]
hi @id1385 i don't think you need `dd()` coz javascript(node) have a powerfull than php when we're trying to make a debug just checkout the `console` functions like `console.table();console.log();console.debug()...`
[mozillaSource](https://developer.mozilla.org/en-US/docs/Web/API/Console)
