### ISSUE TITLE
 Infinite pole classification problem

### ISSUE THREAD

**Issue by livissnack** [adonisjs/adonis-framework#1110]
mysql table comments

> id int auto increment,
> parent_id int,
> user_id int,
> content varchar

Model

children() {
        return this.hasMany("App/Models/Comment", "id", "parent_id");
}

allChildren() {
       return this.children().with('allChildren');
}

person code use

try {
            const data = await Comment.query()
                .where({})
                .with("user")
                .with("allChildren")
                .paginate(page, pageSize);
            return response.json({
                status: "success",
                msg: "Successful data acquisition",
                data: data
            });
        } catch (error) {
            return response.json({
                status: "failure",
                msg: "Data acquisition failed",
                data: error.toString()
            });
 }

Calling an infinite loop, asking for a solution！

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
