### ISSUE TITLE
Method spoofing inside request body should work

### ISSUE THREAD

**Issue by erisrayanesh** [adonisjs/adonis-framework#1116]
## The problem
I'd like to know why adonis router recognizes the method spoofing inside the form body but doesn't call the right handler? Consider this:

```html
<form method="post" action="/users/1">
    <input type="hidden" name="name" value="myname" />
    <input type="hidden" name="_method" value="put" />
</form>
``` 
When I submit the above form, unfortunately  adonis doesn't call `UsersController.update` and unexpectedly throws a 403 error. Using method spoofing in query string works like a charm.
According to the source code of `request.method()` and it's return value (which is truly PUT) in my test, it uses `request.all()` which contains both query string and body. Then, why the router behaves like so?

**Comment by thetutlage** [comment]
It's because the request body is parsed by the body parser middleware and the decision to load the route is made before that.

Simply pass the `_method` as a query string and it will work fine.

```html
<form method="post" action="/users/1?_method=put">
    <input type="hidden" name="name" value="myname" />
</form>
```

**Comment by erisrayanesh** [comment]
@thetutlage Thanks. Yes. Using method spoofing in query string works. Do you think is there a plan for improving it to work even inside the body?

**Comment by thetutlage** [comment]
Not really. I don't see any downsides in using a query string
