### ISSUE TITLE
style not being applied to emails in --api-only mode

### ISSUE THREAD

**Issue by yungsilva** [adonisjs/adonis-framework#1117]
I am using `--api-only` mode and trying to send emails, but no style is being applied to the email...

I'm doing the same in [view documetation](https://adonisjs.com/docs/4.1/views#_style)

on my controller
```
await Mail.send('emails.welcome', { name: user.name }, message => {
  message
    .to(user.email)
    .from('contact@company.com', 'Yung Silva')
    .subject('Welcome to Station')
})
```
`resources/views/emails/welcome.edge`
```
{{ style('style') }}

<h1>Hello {{ name }}</h1>

<p>just a test</p>
```

`public/style.css`
```
h1 {
  background: #000;
  color: #fff;
}

p {
  color: green;
}
```

The email is sent but no style is applied.

already made sure middleware `'Adonis/Middleware/Static'` is registered in `start/kernel.js`

## Package version
Version 4.1
`"@adonisjs/framework": "^5.0.9"`

## Node.js and npm version
v10.15.0

**Comment by thetutlage** [comment]
Closing in favor of forum thread https://forum.adonisjs.com/t/style-not-being-applied-to-emails-in-api-only-mode/4143
