### ISSUE TITLE
Getting error as "TypeError: Class extends value undefined is not a constructor or null" while running "adonis serve --dev"

### ISSUE THREAD

**Issue by zeeshanyshaikh** [adonisjs/adonis-framework#1118]
## Package version
Global : 5.0.8
Local : 6.1.1

## Node.js and npm version
Node.js version : 10.16.0
npm version : 6.9.0

## Sample Code (to reproduce the issue)
Initiating command : `adonis serve --dev`

Getting error :
```
D:\code\zeeapi>adonis serve --dev
C:\Users\zee\AppData\Roaming\npm\node_modules\@adonisjs\cli\src\Commands\Base\index.js:17
class BaseCommand extends ace.Command {
                              ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\zee\AppData\Roaming\npm\node_modules\@adonisjs\cli\src\Commands\Base\index.js:17:31)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\zee\AppData\Roaming\npm\node_modules\@adonisjs\cli\src\Commands\New\index.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

I reinstalled nodejs and adonisjs but still getting same error.

## BONUS (a sample repo to reproduce the issue)
NONE

**Comment by thetutlage** [comment]
It will be nice, if you can share just the package version `@adonisjs/ace` in your `package.json` vs bombarding us with a dump of tree view.

Also, please visit the forum or discord and only open Github issues, when you are have confirmation that it is a real issue

**Comment by zeeshanyshaikh** [comment]
Thanks....Added the query to discord.

**Comment by zeeshanyshaikh** [comment]
Was working on wrong package version. Hence closing this issue.

Thanks @thetutlage for the quick response and help.

**Comment by jenisse** [comment]
Guys, i got the same error while using the cli. 

node version:  v10.16.0

package.json:

`{
  "name": "adonis-api-app",
  "version": "4.1.0",
  "adonis-version": "4.1.0",
  "description": "Adonisjs boilerplate for API server with pre-configured JWT",
  "main": "index.js",
  "scripts": {
    "start": "node server.js",
    "test": "node ace test"
  },
  "keywords": [
    "adonisjs",
    "adonis-app"
  ],
  "author": "",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@adonisjs/ace": "^6.1.1",
    "@adonisjs/auth": "^3.0.7",
    "@adonisjs/bodyparser": "^2.0.5",
    "@adonisjs/cors": "^1.0.7",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.9",
    "@adonisjs/ignitor": "^2.0.8",
    "@adonisjs/lucid": "^6.1.3",
    "@adonisjs/mail": "^3.0.9",
    "firebase": "^6.2.4",
    "firebase-admin": "^8.2.0",
    "speakeasy": "^2.0.0"
  },
  "devDependencies": {},
  "autoload": {
    "App": "./app"
  }
}
`

I reinstall adoniscli and still getting the same error. P @zeeshanyshaikh Have you found the cause of trouble?

**Comment by zeeshanyshaikh** [comment]
@jenisse run this command
npm i @adonisjs/ace@5.0.8

**Comment by wimurk** [comment]
I got the same error with the @adonisjs/ace verison. Change it to `5.0.8` and don't run `npm audit fix` it will update to the broken version

**Comment by wimurk** [comment]
@cleyton1986 in your package.json change the `@adonisjs/ace version` to `5.0.8`. Delete your `node_modules` folder and then run `npm i`.

**Comment by LOGIC254** [comment]
> ng.cmd run app:ionic-cordova-serve --host=0.0.0.0 --port=8100 --cordova-mock --consolelogs --consolelogs-port=53703
[ng] Class extends value undefined is not a constructor or null
[ng] TypeError: Class extends value undefined is not a constructor or null
[ng]     at Object.<anonymous> (C:\Users\PC\rba-app\node_modules\@ionic\angular-toolkit\builders\cordova-serve\index.js:31:52)
[ng]     at Module._compile (internal/modules/cjs/loader.js:956:30)
[ng]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[ng]     at Module.load (internal/modules/cjs/loader.js:812:32)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[ng]     at Module.require (internal/modules/cjs/loader.js:849:19)
[ng]     at require (internal/modules/cjs/helpers.js:74:18)
[ng]     at Architect.getBuilder (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect-legacy.js:210:35)
[ng]     at MapSubscriber.project (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect-legacy.js:142:332)
[ng]     at MapSubscriber._next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\map.js:49:35)
[ng]     at MapSubscriber.Subscriber.next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
[ng]     at TapSubscriber._next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:65:26)
[ng]     at TapSubscriber.Subscriber.next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
[ng]     at MergeMapSubscriber.notifyNext (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
[ng]     at InnerSubscriber._next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
[ng]     at InnerSubscriber.Subscriber.next (C:\Users\PC\rba-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.

**Comment by LOGIC254** [comment]
I am having the above error, I have tried deleting the node modules and reinstalling new ones and it has still failed to work. Someone help me, please.

**Comment by RomainLanz** [comment]
You are using a version of Adonis Ace which is not compatible with your version of Adonis.

**Comment by LOGIC254** [comment]
How do I get to update it, or get through it and the application to work??
