### ISSUE TITLE
Nothing Is Validating Multipart File While Streaming Files

### ISSUE THREAD

**Issue by yungsilva** [adonisjs/adonis-framework#1119]
Already tried

```
request.multipart.file('avatar', {
  types: ['jpeg', 'jpg', 'png'], // I already tried -> type: ['image'] types: ['image'],
  size: "4mb"
  }, async file => {
    await Drive.put(key, file.stream)
})
```

`.../Validators/changeAvatar.js`
```
'use strict'

class UserChangeAvatar {
  get rules() {
    return {
      avatar: 'required|file|file_ext:png,jpg,jpeg,svg'
    }
  }
}

module.exports = UserChangeAvatar
```

Nothing works, the code lets you upload any type of file, like `.pdf` or `.mp4`

There's nothing in the Adonis.js documentation talking about it either.

## Package version
Version 4.1
`"@adonisjs/framework": "^5.0.9"`

## Node.js and npm version
NODE - v10.15.0
NPM - 6.10.1

**Comment by thetutlage** [comment]
You need to learn how streams work and please use the forum for such questions. GitHub issues are to report verified issues
