### ISSUE TITLE
Additional template engine support

### ISSUE THREAD

**Issue by gokaygurcan** [adonisjs/adonis-framework#112]
Hello everyone,
I don't know if there's a specific reason to choose [nunjucks](https://mozilla.github.io/nunjucks/) over other template engines, but wouldn't it be nice to give users a chance to choose their favourite template engine?

There're nice alternatives to nunjucks, here you can find the list of most commonly used/followed* ones:
- [Pug.js/Jade](https://github.com/pugjs/jade) (10,244 stars)
- [handlebars](http://handlebarsjs.com/) (9,891 stars)
- [mustache.js](https://github.com/janl/mustache.js) (8,988 stars)
- [Hogan.js](https://github.com/twitter/hogan.js/) (4,378 stars)
- [doT.js](http://olado.github.io/doT/index.html) (2,613 stars)
- [Swig](http://paularmstrong.github.io/swig/) (2,401 stars)
- [EJS](https://github.com/tj/ejs) (2,656 stars)
- [dust.js](http://akdubya.github.io/dustjs/) (1,471 stars)
- [twig.js](https://github.com/justjohn/twig.js) (801 stars)

I hope you can at least consider this request. Many others who uses _Express_ or _Koa_ for some time are not familiar with nunjucks unless they didn't integrate it themselves. And this makes things a bit harder than they should for beginners. For example _recursive includes_ and _layouts_ and _partials_ are not that much easy to manage as _pug_ or _handlebars_ in _nunjucks_. 

*: number of stars as of 2016-03-06

**Comment by thetutlage** [comment]
@gokaygurcan Nunjucks has support for almost everything you would ever need and if something is missing, i would love to consider that.

Now couple of reasons why not the option of multiple templating engines

1. Koa/Express are simple ( nice ) libraries and have very different nature from Adonis, so i will not make any comparisons here.

2. Adonis is tightly coupled, let's take the example of CSRF protection http://adonisjs.com/docs/2.0/security#csrf-protection. Now Adonis gives you a pre-built helper to put CSRF tokens right into your views, without any extra effort. Giving the choice of 100 different template engines will remove this flexibility.

At the end, my goal is not take the functionality away, but to spend my hardwork on build stable solutions, which should save everyone's time. And keeping everything open will add a lot of unnecessary boilerplate and you have configure everything to get started

**Comment by gokaygurcan** [comment]
Thanks for your reply.
I'm not saying that nunjucks doesn't have any of these features. I'm just saying that it's hard to use than the rest of them. If, for instance, CSRF protection is the reason to use nunjucks, I'd rather implement it in a custom way and go with handlebars. It's probably not the whole reason though, so, anyways. 

Maybe this is my lack of knowledge but this is really hard to do in nunjucks when compare it with handlebars for example:
https://gist.github.com/gokaygurcan/96d2253058bfafe43319
(it doesn't allow me to create sub-directories, so all `-` characters are actually `/`characters)

Again, I don't want to have 100 different options. But it would be nice to have at least one or two more. I just listed the most common ones so maybe people can say their opinion or something. Sticking with one option, which is not that much common and widely used, is not a good thing for this kind of project imho.

**Comment by thetutlage** [comment]
Sorry i don't see any point in including multiple templating engines.

**Comment by gokaygurcan** [comment]
Okay, good luck.

**Comment by webdevian** [comment]
@gokaygurcan Pug was a must-have for me (lots of mixins I use across projects/platforms), so I've written a simple pug provider for adonis https://www.npmjs.com/package/adonis-pug

It should be straight forward to write your own for other engines

**Comment by gokaygurcan** [comment]
Hey @webdevian,
Thanks for letting me know. I'm more into Sinatra-like frameworks. That and the authors response made me decide to move away from Adonis.

**Comment by RomainLanz** [comment]
Nunjucks takes approximately 5 minutes to learn, if you cannot spend this time to use a new framework that not the author problem. 😄

**Comment by gokaygurcan** [comment]
I don't agree but also don't want to make this become a pissing contest. As you said earlier,
> Pug was a must-have for me
Handlebars is the same to me. Since the author had no plans for it, I didn't spent my precious time on it. 

Yes, I spent some time on Nunjucks, also created a PR to make it supported in express-generator package too. But Adonis is not a long term solution for me. And here we are now. 

Thank again for unofficial Pug support. And I believe the keyword is unofficial in this context ;)
