### ISSUE TITLE
Can i use transaction in multiple connection?

### ISSUE THREAD

**Issue by PurwadiPw** [adonisjs/adonis-framework#1122]
## Package version

 "@adonisjs/framework": "^5.0.9",
 "@adonisjs/lucid": "^6.1.3",

## Node.js and npm version

Node.js v10.16.0
npm version 6.9.0

## Sample Code (to reproduce the issue)

In my case i use multiple connection to insert data

```
await Database.connection('db01').table('agent').insert({})

await Database.connection('db02').table('agent').insert({})

await Database.connection('db03').table('agent').insert({})
```

How to use transaction in the example code above at the same time ?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
