### ISSUE TITLE
Wrong documented error handling in Authentication

### ISSUE THREAD

**Issue by marcosguerrini** [adonisjs/adonis-framework#1123]
Hello! (sorry for my bad english)

Well I'm Working with AdonisJs API-Only, and i'm having a trouble handling errors of authentication.

I'm using JWT, and all Works fine but the problem is that I can't send a JSON response when the Token is invalid or not in the header. Adonis always send a HTML/TEXT response. all perfct with the 401 status but not in JSON.

In the Docs you use Try Catch, well the problem here is that if the token is invalid or not exists in the header you never enter to the Catch block.

This is my code and like i say before adonis never execute the catch block of the code, when the authentication is OK all goes perfect but the problem is when the token is invalid or not exists

```js
try {
  await auth.check()
  const projects= await Project.all();
  return response.json({ projects });
} catch (error) {
  console.log(error)
  return response.json({
    ok: false,
    message: "Usuario no autenticado"
  });
}
```

This is shown in the guides

```js
try {
  await auth.check()
} catch (error) {
  response.send('Missing or invalid jwt token')
}
```

I ask in the forums before came here but, i not recevie right answers there, then i think is a bad documented error handling in the official guides, because i think you add the catch block to make the user able to handling the error response.

Thanks!

**Comment by rusya1313** [comment]
@marcosguerrini try to use Accept: application/json header in your request. Should be fine.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
