### ISSUE TITLE
Unique validator not working in string mode

### ISSUE THREAD

**Issue by erisrayanesh** [adonisjs/adonis-framework#1124]
First, these are the available formats that unique validator offers for rule definition
```js
   * email: 'unique:users' // define table
   * email: 'unique:users,user_email' // define table + field
   * email: 'unique:users,user_email,id:1' // where id !== 1
   *
   * // Via new rule method
   * email: [rule('unique', ['users', 'user_email', 'id', 1])]
```
Second, I'd like to know what's wrong with my code? in my test, this rules must throw a validation exception due to duplication of username in the users table.
```js
// UsersController.update

const id = params.id;
const rules = {
    username: 'required|unique:users,username,id:' + id
}
```
But this works
```js
// UsersController.update

const id = params.id;
const rules = {
    rule('required'),
    rule('unique', ['users', 'username', 'id', id])
}
```

Third, How Indiactive library finds out the ignoreKey and ignoreValue and sends it as arguments to unique validator? Answer to this question gives me the idea for creating my new custom validator

**Comment by thetutlage** [comment]
Coz you are using a `colon` vs using a `comma`. This is how it should be

```
const rules = {
    username: 'required|unique:users,username,id,' + id
}
```
