### ISSUE TITLE
Can't make Adonis global on Windows

### ISSUE THREAD

**Issue by anaalicefig** [adonisjs/adonis-framework#1125]
I followed all the documentation instructions to install adonis but i have that error message when i try to run any adonis commands

Adonis is not recognized like a cmdlet, function, script file or operation program. Verify if the spelling of the name or if the path was included, look if the path is correct and try again.
Line: 1 character: 1

Node: 12.4
NPM: 6.9
Windows 10

![image](https://user-images.githubusercontent.com/29892114/62151577-fbdfbb80-b2d6-11e9-8fb1-dcc0bcdfd64d.png)

**Comment by viniciusgati** [comment]
have you installed any other package like angular and it works as global?
I ask this because my first clue is that node is installed incorrectly

**Comment by drmnk** [comment]
I can recommend you to install Windows Subsystem for Linux (WSL) and install Node inside it - it will save you from OS inconsistensy frustration in future.

**Comment by anaalicefig** [comment]
@drmnk thank you
