### ISSUE TITLE
Adonis Mail Can't send mail connect ETIMEDOUT 64.233.189.109:25

### ISSUE THREAD

**Issue by rosnaib11** [adonisjs/adonis-framework#1127]
I can't send email using adonis/mail

I'm using smtp.

What happen is it just loading for 10 seconds and throwing an error connect ETIMEDOUT 64.233.189.109:25. Couldn't find simillar issue with this please help.

```
SMTP_HOST=smtp.gmail.com
MAIL_USERNAME=<myemail>
MAIL_PASSWORD=<mypassword>



smtp: {
    driver: "smtp",
    pool: true,
    port: 25, //2525 //465
    host: Env.get("SMTP_HOST"),
    secure: false,
    auth: {
      user: Env.get("MAIL_USERNAME"),
      pass: Env.get("MAIL_PASSWORD")
    },
    maxConnections: 50,
    maxMessages: 1000,
    rateLimit: 100
  },
```

**Comment by thetutlage** [comment]
How do you confirm that the issue is with AdonisJs and not the email server?

**Comment by rosnaib11** [comment]
@thetutlage it was on my xampp sendmail settings. What did I missed? 

```
SMTP_HOST=smtp.gmail.com
port=465 // doesn't work too
MAIL_USERNAME=<myemail>
MAIL_PASSWORD=<mypassword>
```

**Comment by thetutlage** [comment]
Yeah but how do you confirm that issue is with AdonisJs? Have you tried connecting to the email server separately?

Please remember to only open issues related to the confirmed bugs, and use forum or discord for discussions

**Comment by rosnaib11** [comment]
It worked now, just changed some settings, my badd.

  smtp: {
    driver: "smtp",
    pool: false,
    port:  465, //2525 //465
    host: "smtp.gmail.com", //Env.get("SMTP_HOST"),
    secure: true,
    auth: {
      user: "user", //Env.get("MAIL_USERNAME"),
      pass: "pass" //Env.get("MAIL_PASSWORD")
    },
    maxConnections: 50,
    maxMessages: 1000,
    rateLimit: 100
  },
