### ISSUE TITLE
How to deploy AdonisJS to IIS server?

### ISSUE THREAD

**Issue by rosnaib11** [adonisjs/adonis-framework#1130]
The only thing I know to run adonisJS is by 'adonis serve' and it serve on port 3333 or any specific port. We need to deploy it on IIS server so I installed iisnode, etc. and the express server works on IIS. But when I add adonis project to IIS node its not working, I'm thinking how could I add this since I have to run 'adonis serve' to make it working. Or else I have to modified or tweak something to make it work?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
