### ISSUE TITLE
Version 4.1 always outputs {} on the screen no matter what we do

### ISSUE THREAD

**Issue by harshdoshi999** [adonisjs/adonis-framework#1131]
Version 4.1 always outputs {} on the screen no matter what we do

Output I'm getting -- http://prntscr.com/os3b6a

Route -- http://prntscr.com/os3blc

Controller -- http://prntscr.com/os3bv0

Model -- http://prntscr.com/os3c89

Please I need help on this.

Thanks in Advance.

**Comment by thetutlage** [comment]
Can you share, where exactly in the docs you show an example using generators? You should be using `async/await`.

**Comment by harshdoshi999** [comment]
Can you point out which file is wrong? I haven't used generators.

**Comment by harshdoshi999** [comment]
While using await, I'm getting this error -- http://prntscr.com/os3izz

SyntaxError
Unexpected token await user.save()

**Comment by thetutlage** [comment]
Please go through the documentation first and use the forum or the discord server to discuss more

**Comment by harshdoshi999** [comment]
I am following the documentation now and still getting the above error. 

SyntaxError
Unexpected token await user.save()

**Comment by thetutlage** [comment]
First of all, you cannot even take the pain to write the code and expecting others to read code from your screenshots. 

2nd, can you tell me where in the documentation you found this syntax?

![download](https://user-images.githubusercontent.com/1706381/62943955-498d1580-bdf9-11e9-9546-78b9870333b5.png)
