### ISSUE TITLE
'Unknown cipher' error when using adonisjs in electron

### ISSUE THREAD

**Issue by luukhoeben** [adonisjs/adonis-framework#1132]
## Package version
AdonisJS: 4.1
Electron: 6.0.2
adonisjs/framework: 5.0.9
node-cookie: 2.1.1
simple-encryptor: 1.4.0

## Node.js and npm version
NodeJS: 12.4.0
NPM: 6.9.0

## Sample Code (to reproduce the issue)
```
const { fork } = require('child_process');

this.serverInstance = fork('./server.js', [], {
  cwd: __dirname,
  env: {
    PORT: this.port
  },
});
```

Because Electron is using a custom version of node, the `aes-256` encryption used in the simple-encryptor package doesn't work, now this is fixed in version 3.0.0 by using the `aes-256-cbc` cipher. The simple encryptor package is used in the node-cookie package that is included in adonis.

Now I thought I could just include the higher version of this package myself but the node-cookie package looks specifically in the node_modules of the package itself. So now I don't know what to do.. 

Thanks in advance :D

**Comment by RomainLanz** [comment]
Hey @luukhoeben! 👋 

We are happy to accept a PR to update `simple-encryptor` to the version `3.0.0`.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by whiteyhat** [comment]
I also got this isse

**Comment by wemersonjanuario** [comment]
same problem here. How to fix?

**Comment by luukhoeben** [comment]
Hey sorry for answering so late. I see you ugraded the simple-encryptor to version 3 in the framework, but the problem still exists. Here is an image of the error:
![image](https://user-images.githubusercontent.com/9342486/68027869-c4a4f000-fcb3-11e9-9b9b-cd9853724424.png)

It looks like the `node-cookie` package get's the simple encryptor from its own node_modules folder, so upgrading the simple encryptor package in the framework won't help.

**Comment by luukhoeben** [comment]
@RomainLanz Made a PR on the `node-cookie` repo.

**Comment by wemersonjanuario** [comment]
@luukhoeben any update or workaround ? how to use your fork on my project?
