### ISSUE TITLE
Handling errors not coming from an HTTP request

### ISSUE THREAD

**Issue by lpeppe** [adonisjs/adonis-framework#1133]
Hi everyone.
I'm developing a system that apart from providing APIs to external services also has a separate core that makes computations independently from the http calls the server receives. 
I need some way to handle the exceptions risen from this part of the system but, as far as I understood, the exception handling provided by Adonis only works with HTTP requests.
How should I handle them?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
