### ISSUE TITLE
after run npm @adonisjs/ace@6.1.4 adonis crash

### ISSUE THREAD

**Issue by alvarolordelo** [adonisjs/adonis-framework#1135]
*Delete the above section and the instructions in the sections below before submitting*

## Package version

Adonis api-only
 
## Node.js and npm version

npm 6.4.0
node 10.16.3

## Sample Code (to reproduce the issue)

I've just asked to install mysql from NPM, and as it accused package that need fix
I ran npm install @adonisjs/ace@6.1.4
after that the server crashed and couldn't start

![image](https://user-images.githubusercontent.com/1663952/63829320-9c111a80-c93f-11e9-9103-7c99cbbd03e2.png)

![image](https://user-images.githubusercontent.com/1663952/63829350-ac28fa00-c93f-11e9-81ec-86aacdf15c66.png)

## BONUS (a sample repo to reproduce the issue)

install adonis NPM will acuse a vulnerability and ask you to run npm audit fix
after fix it won't start

**Comment by thetutlage** [comment]
Saying this quite a few times. Please do not upgrade the `ace` version to `6.x.x`, since it has breaking changes for v5.

**Comment by alvarolordelo** [comment]
@thetutlage  so what is the main action to peform to solve the issue, since after install it starts to show a security warning ?
