### ISSUE TITLE
Question: where can I find out the possible ctx methods?

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#1138]
When generating controllers automatically by creating migrations, the methods have comment blocks for the documentation like this:

```
/**
 * Show a list of all projects.
 * GET projects
 *
 * @param {object} ctx
 * @param {Request} ctx.request
 */
```

I often change the methods' signature by adding `auth` or `params`, and I want to modify the comments as well, but I am not sure if something like this would be correct:

```
/**
 * Create/save a new team.
 * POST teams
 *
 * @param {object} ctx
 * @param {Request} ctx.request
 * @param {Auth} ctx.auth
 */
```

I just want a list of methods to see what I can use or not.

Thank you, and I love Adonis.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
