### ISSUE TITLE
What About Installtion Issue ??

### ISSUE THREAD

**Issue by Darshan197** [adonisjs/adonis-framework#1139]
I Am Getting This Warning While Installing Or Clone Repository 

npm i -g @adonisjs/cli                                                        
 npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-c olors' if you prefer the old syntax. Visit  ases/tag/v3.0.0\> for migration path(s).                                         npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrad e to the latest version.

After Upgrading this packages Still It's Not Working...

**Comment by thetutlage** [comment]
The issue is reported in the wrong repo and must be reported in `@adonisjs/cli`. Also please note that any depreciations are not deal breakers with the CLI tools.
