### ISSUE TITLE
¿This is bug? Controller and database

### ISSUE THREAD

**Issue by gario300** [adonisjs/adonis-framework#1140]
First of all I want to apologize for my bad English

Recently I have been working with Adonis Js and I really had only but problems related to the little understanding of my English and the framework, however yesterday I noticed something quite strange, I was having problems with a query and then rummage and dig in the code I came to the conclusion that the code was fine ... Which led me to wonder what was going on? I activated the developer mode in the adonis settings to be able to see the complete query to the database and what was my surprise to see that adonis was actually executing the query but IN ANOTHER TABLE, that is, I was telling Adonis to search in the "Conversations" table but Adonis was looking in the user table, something similar is happening to me today, I'm telling Adonis to execute a specific controller method and is executing another one (I know why the answer that is returning to me is that of the method that I should not be executing)

I would try to specify the code fragment that I want to execute but this error is happening with everything I am trying to put 
Could this be a mistake? I have the project on github should I put it here?

Thanks in advance this is the code in the controller

Update:
I moved the route outside the group I was in and the code is working wtf? :o

[controller1.txt](https://github.com/adonisjs/adonis-framework/files/3597668/controller1.txt)

[controller2.txt](https://github.com/adonisjs/adonis-framework/files/3597667/controller2.txt)

**Comment by RomainLanz** [comment]
Hey @gario300! 👋 

Instead of sending your code in a txt file. Could you please create a repository or upload them on https://gist.github.com/ instead?

Also, this is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

**Comment by thetutlage** [comment]
Closing as issue is half baked and must be discussed on the Forum or Discord. Please issue the Github issues for confirmed bugs
