### ISSUE TITLE
deployment error/ npm install gives error

### ISSUE THREAD

**Issue by Nainabbas** [adonisjs/adonis-framework#1142]
`remote:        found 2 high severity vulnerabilities
remote:          run 'npm audit fix' to fix them, or 'npm audit' for details
`

when i deploy my app to the server its shows this error when deploying and the app does not work.
this is the same error when you run `npm install`

**Comment by tlgreg** [comment]
Both vulnerabilities are because of `set-value`, right?
If so, this is because of `@adonisjs/ace`, the related issue there:
https://github.com/adonisjs/ace/issues/102
In the next major version, this is fixed, but it might worth to patch this in `5.x` IMO.

**Comment by McSneaky** [comment]
https://github.com/adonisjs/ace/issues/102#issuecomment-526023904

**Comment by Nainabbas** [comment]
ok got it
