### ISSUE TITLE
auth generate user

### ISSUE THREAD

**Issue by elviskudo** [adonisjs/adonis-framework#1143]
hi, this is awesome product, thanks for that

i implement this product, but i found error when i create code like this
````const token = await auth.generate(user)````
the result is:
````primary key is missing for user````
what is this?
and how can i solve that?
thanks a lot

**Comment by RomainLanz** [comment]
Hey! @elviskudo 👋 

We would need more code to help you.
It seems that the `user` doesn't have any primary key assign to it. This can happen when you create the record just before and you don't reload the model (`user.reload()`).

Also, this is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
