### ISSUE TITLE
Oracle db library cant install

### ISSUE THREAD

**Issue by nikklass** [adonisjs/adonis-framework#1144]
Hi. Am having issues using oracle with Adonis.
Running either:
```
npm i oracledb --save
or 
npm i strong-oracle --save
```
to install oracle db libraries doesnt seem to work.
Do they exist?
NPM keeps complaining it cant find the file...

**Comment by thetutlage** [comment]
This must be an issue created on @adonisjs/lucid repo and also please share the errors you are receiving. A half baked issue is of no help

**Comment by nikklass** [comment]
What happened to due diligence? This @thetutlage  guy doesnt even ask me anything. Just goes ahead and closes the issue I opened without bothering to understand what the issue is about!!! Phew!!! Seems like a hostile place for me. Lemme go back to my hallowed expressjs... Good riddance.

**Comment by jsdecena** [comment]
> What happened to due diligence? This @thetutlage guy doesnt even ask me anything. Just goes ahead and closes the issue I opened without bothering to understand what the issue is about!!! Phew!!! Seems like a hostile place for me. Lemme go back to my hallowed expressjs... Good riddance.

I think @thetutlage is correct. As a good member of the community, you must provide details of your error and might be good also to share what steps have you made in trying to resolve your issue and not just throw your problem without proper context.

**Comment by nikklass** [comment]
Noted. But my problem is about installing the library itself! what other steps could I have tried out? Am not programming anything yet!!! I am at the npm install phase. I simply repeated the steps you provided in your docs which dont work for me....

**Comment by nikklass** [comment]
Seems like the issue was corrected. Just tried the same command now and its installing!!! Strange...

**Comment by nikklass** [comment]
@thetutlage  Be considerate next time. Thanks.
