### ISSUE TITLE
call function from other function

### ISSUE THREAD

**Issue by elviskudo** [adonisjs/adonis-framework#1145]
Hi,
I got problem here,
i try to call another function from function like this
```
this.loopScan(what)

async loopScan(what) {
  const result = await axios.get(url)
  return result.toJSON()
}
```
output is:
```
Unexpected token await axios.get(url)
```
why?
thanks

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
