### ISSUE TITLE
Adonis mysql invalid connection type

### ISSUE THREAD

**Issue by elviskudo** [adonisjs/adonis-framework#1146]
I have lucid monggo installed, but i have to connect with my MySQL server
so i have to connect multiple databases
primary connection is mongodb
secondary connection is mysql

but i have a problem here, i already added code in my model like this
```
class Order extends Model {
    static get connection () {
        return 'mysql'
    }
}
```
but when i try, result like this:
```
RuntimeException
invalid connection type
```
how can i fix this?
thanks a lot, youre framework very awesome and helped me

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
