### ISSUE TITLE
Adonis new won't clone repo

### ISSUE THREAD

**Issue by Kawacrepe** [adonisjs/adonis-framework#1147]
Hello,

I'm trying to use
`adonis new yardstick`
I get :

ERROR  Command failed: git clone --depth=1 https://github.com/adonisjs/adonis-api-app.git "C:\Users\XXX\Documents\Dev\Project\yardstick"
Cloning into 'C:\Users\XXX\Documents\Dev\Project\yardstick'...
BUG: refs/files-backend.c:2956: initial ref transaction called with existing refs

Git: git version 2.23.0.windows.1

**Comment by Kawacrepe** [comment]
Update: I fix the problem by using `git init` inside the folder but I'm not sure that the good way to resolve this ?

**Comment by thetutlage** [comment]
Wrong repo. Please post in the CLI Repo
