### ISSUE TITLE
Adonis WebSocket Client Example

### ISSUE THREAD

**Issue by mpena2099** [adonisjs/adonis-framework#1149]
Hi!

I'm new on NodeJS and AdonisJS but I really need an example of how to make a client (backend, not frontend) to connect to my AdonisJS websocket server. The AdonisJS + websocket server is OK.

Thanks!

**Comment by thetutlage** [comment]
Don't have much bandwidth to work on same and also the repo is wrong, so closing the issue. Feel free to ping me on Discord for same
