### ISSUE TITLE
Static provider as middleware.

### ISSUE THREAD

**Issue by seth2810** [adonisjs/adonis-framework#115]
As I understand, currently Static provider is tightly coupled into framework and there is no way to pass control to my custom middleware before static provider process request? I ask because i want to serve some of files through webpack-dev-middleware (that uses memory file system to prevent unecessary io) and if it can't respond pass control to serve provider.

**Comment by thetutlage** [comment]
I do not have much experience with webpack, but i was reading this [thread](https://github.com/webpack/webpack-dev-middleware), it says do not use it in production.

The reason i pointed that out is i am trying to understand whether this is something you would like to use in production also or not?

For now static resources are served without touching the application core layer, but i won't mind adding the middleware support for them. But i would need some real use cases before i really dig into changing the code.

**Comment by seth2810** [comment]
You correctly right, webpack-dev-middleware is used only in development environment, but i want to enable it through my custom middleware only for development needs. 

I read the code and saw this https://github.com/adonisjs/adonis-framework/blob/develop/src/Server/index.js#L116. Currently this code blocks all registred middlewares until staticHandler doesn't find file.

I'm talking about that someone may need to implement his own static handler implementation and it was be great if he can do this through middleware that replace default static middleware.

**Comment by thetutlage** [comment]
Great, i won't mind adding a traditional `use` method to this class https://github.com/adonisjs/adonis-framework/blob/develop/src/Static/index.js. 

And it will run the middleware before the final `serve` method.

I am not sure about other use cases one can have while serving static resources. So for now i will keep it like a hidden gem and if i find that static resources has plenty of resource, then i will improve upon it.

For now i will add the functionality to do something like this

```javascript
const Static = use('Static')
Static.use(function * (req, res, next) {
   // do your work
   // yield next
})
```

**Why i am not keeping it part of actual middleware ?**

I do not want static resources to go through all the middleware as i personally do not any use. I am implement the above, and will see if community comes up with more cases.

**Comment by seth2810** [comment]
Currently. It's not important for me. I solve my case use other static server, that use proxy over adonis application. I think that this functionality may be required by the community, so would be reasonable to vote before you implement it?

**Comment by nallown** [comment]
Would be great if you could add this since I'm planning on serving static files through nginx rather then the application it self since the load balancers hosts them and not the application servers.

**Comment by thetutlage** [comment]
@nallown You can do that even without a middleware. You just need to configure nginx to point to the right directory to serve static resource for you

**Comment by nallown** [comment]
Oh yea that's true. Nginx can serve those static files anyway even if the application serves them, it'll just get a response from nginx instead of the application.

**Comment by Atinux** [comment]
@seth2810, I found a way to use the webpack middlewares with Adonis, you can take a look at it here: https://github.com/Atinux/vue-adonis (take a look at the WebAppController.js).

@thetutlage 
When I was working on this boilerplate, I add some difficulties to find a way to add a middleware to be called before the static file, even with vue-adonis, I am cleaning the public/dist/ everytime so the webpack middleware get called instead of the static file.

I think it would be nice to be able to add a middleware which goes before the static handler and the routes. I am thinking of the [compression](https://github.com/expressjs/compression) middleware, mostly used in production.

**Comment by Atinux** [comment]
But actually, your solution will do the job perfectly @thetutlage 👍 

If I do:
```
const Static = use('Static')
const compression = require('compression')
const promisify = require('es6-promisify')

Static.use(function * (req, res, next) {
   yield promisify(compression())(req, res)
   yield next
})
```

Because the staticHandler is called before every route, it will be applied for every routes in the app.

From my point of view, it's a great feature 🔥

**Comment by thetutlage** [comment]
Great, I will start working on it. It will require some transparent changes to the middleware store itself. Since right now middleware are stored as `global` and `named` and now another segmentation is required for `static`. 

So better I will abstract this to a middleware store with **tags** for example:- Add global middleware with `global` tag and so on. This will make it more generic than hardcoding types of middleware.

Since, I am travelling will start working on it in early November.

**Comment by dennschu** [comment]
@thetutlage 

> I do not want static resources to go through all the middleware as i personally do not see any use case. 

protect static files with authentication e.g. static prototype demos where the client (human) needs to authenticate before he gets access to the prototype

**Comment by RomainLanz** [comment]
@dennschu 

You can do that by just setting up a routes and controller and put your resource into the `storage` folder.

Then you send a respond after authentication with the file bring from`storage` folder. I have done that for the [media part of my website](https://www.qualitas-helvetica.ch/media) to count how many times the file is downloaded.

**Comment by dennschu** [comment]
@RomainLanz I know that this is possible through controller and a "File" Response but my sugguested use case offers the same feature with less code...

**Comment by muxahuk** [comment]
Hey, idk if these is the right place, or i should create new issue, but I can't figure out what should i do to performe some changes on static files. For ex. i have less or sass or postcss files and i'm serving them directly, but when it comes to serving the file i need to compile it and give user an css file compiled from these compilers.. I know how to read/compile file, but i don't know when to trigger it.. any help ?

**Comment by thetutlage** [comment]
You can keep your `less/sass` files inside the `resources` directory and compile the css file inside `public` directory.

As far as compiling is concerned, Adonis does not impose anything regarding the frontend toolchain, feel free to use gulp/grunt etc

**Comment by muxahuk** [comment]
@thetutlage Yeah, i know that there are no ristrictions in what to use on frontend, but my question is litle different.. May be "Can i use middlewere on static files" will be more clear ?..
There can be many ( ? ) usecases of using it.. for ex. allow only logged in users to view sertain fails.. or ( as i mentioned before ) compile ( bubelify/minify/compress images atc. ) files before outputing to user. ( with gulp/grunt atc. tasks.. )
Back to you'r comment - on production i would never touch less files and there might be better to use already compiled file, but on dev., i think, it would be better to compile on the fly. At least i could deside what to use, if i would have these feature, but currently i'm restricted to use gulp/grunt...

**Comment by thetutlage** [comment]
Finally it's a middleware https://github.com/adonisjs/adonis-framework/blob/develop/src/Static/index.js
