### ISSUE TITLE
Control when session cookies get set

### ISSUE THREAD

**Issue by AbinashMaharaj** [adonisjs/adonis-framework#1151]
When using the SessionMiddleware, any user gets a session cookie as soon as he visits the page. 
In order for any AdonisJS app to be GDPR-complient, this cookie can only get set after the user gave their consent or when the cookie is strictly required for the website to work. In this case, the cookie is not required yet (only when the user is trying to sign in) but with AdonisJS I can't find a way to block setting the session cookie before consent is given.

**Comment by RomainLanz** [comment]
Hey @AbinashMaharaj! 👋 

I may be wrong, but I believe the current behaviour is GDPR-compliant.
It wouldn't be if you directly use this cookie to track the user and save information about him.

If you have more information, could you please link any source saying that GDPR remove the usage of Cookie by default?

**Comment by RomainLanz** [comment]
Closing since not actionable.
