### ISSUE TITLE
Route.get not working in Route.group

### ISSUE THREAD

**Issue by Kriegsmarine13** [adonisjs/adonis-framework#1155]
Hello, can't figure out why adonis is not seeing my route.

I have 63 methods (get, post and patch) in my group, all of them working. But when I try to add one more GET method, it simply doesnt work.

`Route.group(() => {
`
`
    Route.get('/getTest', 'QuestionController.getTest');
`
`
    Route.post('postTest', 'QuestionController.postTest');
`
`
}).prefix('api/questionnaire')`

Related methods: 
`
    async getTest({request, response}) {
        console.log("QuestionController: getTest");
    }
`
`
    async postTest({request, response}) {
        console.log("QuestionController: postTest");
    }
`

postTest func works fine, and logging result as expected, but getTest logs nothing
However, if I take getTest outside of group - I get expected console.log output. All other GET methods, that were written previously - work (although looks like now I'm having troubles with getting data from `request.get()`).
Is this a bug or I'm missing something?

**Comment by mritgupta** [comment]
@Kriegsmarine13 

Get added prefix as `/`

It should be like
```js
Route.get('getTest', 'QuestionController.getTest');
```

**Comment by Kriegsmarine13** [comment]
@mritgupta 
Thanks a lot, that made it work! But...
This works only in a separate group. If I put these two routes to my main 'api/questionnaire' group it still won't work. But when I take them out in another 'api/questionnaire' group, as mentioned before, still nothing happens. I wonder, if there's a limit on a number of routes in a group?

**Comment by mritgupta** [comment]
@Kriegsmarine13 

There no limit for routes in the group

I Tried to like this, and its working

```js
Route.group(() => {
  Route.get('getTest', () => {
    return {
      status: 200,
      data: {
        message: 'Get test',
      },
    };
  });
  Route.post('postTest', () => {
    return {
      status: 200,
      data: {
        message: 'Post test',
      },
    };
  });
}).prefix('api/questionnaire');
```

**Comment by Kriegsmarine13** [comment]
@mritgupta Well, at least it is working now and I can continue my work. Thank you so much!
