### ISSUE TITLE
Migration: be able to run a specific migration

### ISSUE THREAD

**Issue by marceloagil** [adonisjs/adonis-framework#1156]
Hi there. 

I'm reading docs and googling but can't find a way to run a specific migration instead of all migrations.

Sorry if this is the wrong place to ask.

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
