### ISSUE TITLE
Write unit test files using typescript

### ISSUE THREAD

**Issue by belal-mazlom** [adonisjs/adonis-framework#1157]
## Prerequisites

I used this repo to create adonisjs project using typescript

https://github.com/tiansin/adonis-quick-start-typescript

## Why this feature is required?
We can build project using typescript, it would be great if we can write unit test using typescript also.

## Have you tried any other work arounds?
I tried example using mocha library but want a way to do that using `Japa` and `adonis test` command

## Are you willing to work on it with little guidance?
Yes

**Comment by thetutlage** [comment]
Can you share, what exact issue you are facing while running the tests? I believe, you can run them using `ts-node`. Example:

```ts
ts-node ace test
```

**Comment by belal-mazlom** [comment]
Hi @thetutlage 

The command above will produce this error:
```bash
/Users/fn/Documents/adonistest/node_modules/typescript/lib/typescript.js:125680
var error = new Error("Could not find source file: '" + fileName + "'.");
```

Anyway I moved test directory inside **src** and convert all files to TS extension.
I run this command to make it work
```bash
tsc && adonis test
```
It will generate test on root directory then run `adonis test`

All is went good, but I forced to add these things inside each test file:
```js
const Test = use('Test/Suite') as Function;
const { test, trait } = Test('Testing example');
import { assert as Assert } from 'chai';
....

test('Test required data', async ({ assert }: { assert: typeof Assert }) => {
....
});

```

I think it's will be helpful if adonis-cli support generating project with TS support and also for testing directory, and add required types for it.

**Comment by thetutlage** [comment]
The official support for Typescript is coming. I will close the issue, since the existing version of framework wasn't written for Typescript support in mind and giving support around that is isn't possible for me now.
