### ISSUE TITLE
Alias field name

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [adonisjs/adonis-framework#1158]
## Why this feature is required (specific use-cases will be appreciated)?

this feature will make it easier to write code by taking an example of the documentation

https://adonisjs.com/docs/4.1/lucid#_setvisiblesethidden

we could alias to a field name

```js
User.query ().setVisible ({ firstname: name }).fetch ()
```

with that we would have `user.name` instead of `user.firstname`

## Have you tried any other work arounds?

I found nothing about it in the documentation

## Are you willing to work on it with little guidance?

Yes!

**Comment by carvalhoviniciusluiz** [comment]
you refer to do that?

`User.query ().select('firstname AS name').setVisible (['name']).fetch ()`

understand!

**Comment by thetutlage** [comment]
Will close it for now, since it's not a feature that stops someone from using the package. Maybe I can improve it once I have less workload.
