### ISSUE TITLE
Validator - Async rules

### ISSUE THREAD

**Issue by hiukky** [adonisjs/adonis-framework#1159]
Is there any way to return my rules based on a promise? To be more specific I'm trying to return them based on the auth.getUser() result.

if i fix this with Promise.resolve() i get the result and when i return the rules in the then block the same doesn't apply.. and the get method inside clsase also doesn't accept async in the declaration.

```js
  get rules () {
    return Promise.resolve(this.ctx.auth.getUser())
      .then(user => {
        return {
          email: `required|email|unique:clients,email,id,${user.id}`,
        }
      })
  }
```

**Comment by thetutlage** [comment]
If you place your validator after the Auth middleware, then you can access the user as `auth.user`, there is no need to call `auth.getUser()`

```js
  get rules () {
    return {
      email: `required|email|unique:clients,email,id,${this.ctx.auth.user.id}`,
    }
  }
```

**Comment by hiukky** [comment]
> If you place your validator after the Auth middleware, then you can access the user as `auth.user`, there is no need to call `auth.getUser()`
> 
> ```js
>   get rules () {
>     return {
>       email: `required|email|unique:clients,email,id,${this.ctx.auth.user.id}`,
>     }
>   }
> ```

Thank @thetutlage  you...it really works.
