### ISSUE TITLE
Environment from different location

### ISSUE THREAD

**Issue by kbucksch** [adonisjs/adonis-framework#116]
Hey, 

actually the environment is loaded by .env file on system in folder. This is a nice solution but I would prefere having the possibility to point to a different location of .env file like /etc/myApp/.env

**Comment by thetutlage** [comment]
Is there any specific reason for that?

**Comment by kbucksch** [comment]
Yes, when using for production or staging I would love having files in different location. Especially since server will be setted up by server infrastructure/management tools.

**Comment by thetutlage** [comment]
How about doing a symlink ? `ln -s /etc/myApp/.env .env`

**Comment by kbucksch** [comment]
It's of course a solution but it would be need to be executed after deployment. When doing deployment with Capistrano for example it is another step we would need to implement. Better would be like known from other languages/frameworks that default location will be './.env' otherwise /etc/something/.env will be checked.
That would help to make Adonis more useful for production use cases

**Comment by thetutlage** [comment]
I won't mind implementing it, but trying to understand a solid use case. Most probably there can be a `paths.js` file inside the root of every project and that file can define path to `.env`

But in that scenario, may be you want a different `.env` path for development and different for production, so having `paths.js` file will not help much.

Any suggestion?

**Comment by kbucksch** [comment]
I would suggest that your core will look up "/etc/adonis_env", "~/.adonis_env" and "./.env" for environment settings in this order and this priority. If it will find a file in the first place it will ignore the other places. If it will find a file not in first but in second place it will ignore the last place, etc.

In this way developers can use during development ".env" file when not having placed one of the other on their local system. And Admins can deal with the other locations. This will help keeping development stage and the others seperatly.

**Comment by thetutlage** [comment]
Have to think about it and see what are common ways to look for `.env` file. How about adding `ENV_PATH=/etc/.env` to node server start command ?

So it will something like this

```
ENV_PATH=/etc/.env npm start
// or
ENV_PATH=/etc/.env pm2 start server.js
```

**Comment by RomainLanz** [comment]
I like the idea to have a node variable (`ENV_PATH`) to define where it need to check for the .env file. Instead, it use the default `./.env` path.

**Comment by thetutlage** [comment]
yes otherwise i have to get into making it cross platform, looking into different paths for windows, linux and mac

Will implement the node flag

**Comment by kbucksch** [comment]
+1 great idea

Harminder Virk <notifications@github.com> schrieb am Do., 10. März 2016,
10:16:

**Comment by thetutlage** [comment]
Will be part of next release

**Comment by kbucksch** [comment]
:+1:
