### ISSUE TITLE
return a value from an event listener

### ISSUE THREAD

**Issue by metronetwork** [adonisjs/adonis-framework#1163]
is there any way i can return a value from the listener?

My listener:
Listener.method = async () => {  // code return true }

let e = Event.emit('new::listener')
console.log(e) // undefined

**Comment by RomainLanz** [comment]
Hey @metronetwork! 👋 

This is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
