### ISSUE TITLE
Super Admin

### ISSUE THREAD

**Issue by nice9uy** [adonisjs/adonis-framework#1169]
Hi, adonis framework is indeed very impressive and very easy to use for website development. 

What I want to ask is, can this adonis create a super admin page like django? 

Hopefully with a super admin like Django in Adonis, website developers can manage websites very easily in building sophisticated websites with Adonis. 

thank you

**Comment by MarcusPianco** [comment]
I know django and I've used it, and in adonisJS the same environment(admin panel) not exist or I don't know yet   :)

**Comment by RomainLanz** [comment]
Hey @nice9uy! 👋 

There's not a super admin provided by Adonis and I don't know any from the community. Feel free to build one if you believe it's useful.
