### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by Matthijn** [adonisjs/adonis-framework#117]
First off, coming from Laravel, this looks rather lovely. In the [documentation](http://adonisjs.com/docs/2.0/connection) is says there is PostgreSQL support.

Now in the `database.js` there is an example for `MySQL` which I presume looks similar to the `PostgreSQL` one. However there is also a command to install the `MySQL driver`. Through: `npm install --save mysql`

Which `driver` should I have if I want to use `PostgreSQL` instead? 

Thanks.

**Comment by thetutlage** [comment]
This is how it will look for PostgreSQL.

```javascript
pg: {
    client: 'pg',
    connection: {
        host: '127.0.0.1',
        port: 5432,
        user: '',
        password: '',
        database: 'adonis',
        ssl: false
    }
}
```

and install pg with npm `npm i --save pg`

**Comment by Matthijn** [comment]
Ah thanks, I did find `pg` on npmjs, however I was not sure if that was the correct one.
