### ISSUE TITLE
bug when  serve

### ISSUE THREAD

**Issue by m-mgahed** [adonisjs/adonis-framework#1171]
## Package version
4.1.0

## Node.js and npm version
node v 10.17.0
npm 6.11.3

this error  show  when serve although it worked before 
TypeError: this.app.with is not a function

1 BodyParserProvider._registerValidatorBindings
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/@adonisjs/bodyparser/providers/BodyParserProvider.js:86

2 BodyParserProvider.boot
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/@adonisjs/bodyparser/providers/BodyParserProvider.js:101

3 _.filter.map
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/@adonisjs/fold/src/Registrar/index.js:147

4 arrayMap
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:639

5 Function.map
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:9554

6 interceptor
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:16997

7 thru
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:8795

8 anonymous
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:4368

9 arrayReduce
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:683

10 baseWrapperValue
  /home/mostafa/projects/hive-back/hive-logic-api/node_modules/lodash/lodash.js:4367

Application crashed, make sure to kill all related running process, fix the issue and re-run the app

**Comment by RomainLanz** [comment]
Hey @m-mgahed!

Could you share the version of all Adonis package? Seems that you are using an old version of Adonis with the new packages.

**Comment by m-mgahed** [comment]
hey @RomainLanz !
sorry for late !
yes,u r right it seems that i use an old version of adonis 
Thank you for your interest .
