### ISSUE TITLE
AdonisJS  how to use both request.file & request.multipart.file in a function

### ISSUE THREAD

**Issue by minhtranin** [adonisjs/adonis-framework#1174]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

## Consider an RFC

Please create an [RFC](https://github.com/adonisjs/rfcs) instead, if

- Feature introduces a breaking change
- Demands lots of time and changes in the current code base.

*Delete the above section and the instructions in the sections below before submitting*

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
