### ISSUE TITLE
Adonis can't handle more than 9 request per sec

### ISSUE THREAD

**Issue by TheYkk** [adonisjs/adonis-framework#1178]
I use https://github.com/Utwo/adonis-realworld-example-app
## Package version
"@adonisjs/framework": "^5.0.13"
## Node.js and npm version
node v12.13.1
npm 6.12

## Issue
Adonis can't handle login request
I tested with hey load generator
```
hey -z 30s -c 5 -m POST  -d '{"user":{"email":"ykk@theykk.net", "password":"ykkqwe"}}' -H "Content-Type: application/json" http://SERVER:8080/users/login
```
![image](https://user-images.githubusercontent.com/21688838/71006532-7e3a1200-20f6-11ea-88b4-52399a604391.png)

When I test the CPU, it's 100 %

**Comment by TheYkk** [comment]
Local test
![image](https://user-images.githubusercontent.com/21688838/71007402-01a83300-20f8-11ea-8c25-a9dab99feedf.png)

**Comment by thetutlage** [comment]
No idea what exactly you are testing. Try it on a fresh app with hello world to see if it's really related to AdonisJS or your own code

**Comment by thetutlage** [comment]
Also, since you are saving a new user in `POST /users/login`, the password hashing takes place and Bcrypt is intentionally a slow algorithm. 

Read this https://stackoverflow.com/questions/15763086/bcrypt-for-password-hashing-because-it-is-slow and https://auth0.com/blog/hashing-in-action-understanding-bcrypt/

**Comment by TheYkk** [comment]
https://github.com/Utwo/adonis-realworld-example-app/blob/master/app/Controllers/Http/AuthController.js 

i try only login

**Comment by thetutlage** [comment]
Already shared the reason. Please read how Bcrypt works

**Comment by TheYkk** [comment]
Is it normal only 10 logins per second?

**Comment by thetutlage** [comment]
Read the links. Don't expect me to read them out for you and share the summary with you.
