### ISSUE TITLE
Getting error as "TypeError: Class extends value undefined is not a constructor or null" while add LucidProvider

### ISSUE THREAD

**Issue by tridungle** [adonisjs/adonis-framework#1179]
## Package version

@adonisjs/core v2.6.2
## Node.js and npm version

Node v10.16.0 and npm 6.13.4
## Sample Code (to reproduce the issue)

`{
  "typescript": true,
  "commands": ["./commands"],
  "exceptionHandlerNamespace": "App/Exceptions/Handler",
  "autoloads": {
    "App": "app",
    "Contracts": "contracts"
  },
  "preloads": ["./start/routes", "./start/kernel"],
  "metaFiles": [".env", ".adonisrc.json", ".gitignore"],
  "providers": [
    "@adonisjs/core",
    "@adonisjs/bodyparser",
    "@adonisjs/lucid/providers/LucidProvider"
  ],
  "aceProviders": ["@adonisjs/lucid/providers/MigrationsProvider"]
}`
## BONUS (a sample repo to reproduce the issue)

`TypeError: Class extends value undefined is not a constructor or null

1 anonymous
  /node_modules/@adonisjs/lucid/providers/LucidProvider.js:14

2 Object.esmRequire
 /node_modules/@poppinss/utils/build/src/esmRequire.js:5

3 Registrar._loadProvider
  /node_modules/@adonisjs/fold/build/src/Registrar/index.js:13

⚠  warn      Underlying HTTP server died with "0 code"
`

**Comment by thetutlage** [comment]
Can you please share how you created the app? Because you are using a mix of v4 and un-released v5

**Comment by tridungle** [comment]
> Can you please share how you created the app? Because you are using a mix of v4 and un-released v5

I use this https://github.com/AdonisCommunity/create-adonis-ts-app to generate adonis app.

**Comment by thetutlage** [comment]
Please don't use it for now. The package is meant for v5 and is not released yet. You need to wait for a while 😄

**Comment by tridungle** [comment]
> Please don't use it for now. The package is meant for v5 and is not released yet. You need to wait for a while smile

thank you! till waiting :dancer:

**Comment by thetutlage** [comment]
😄
