### ISSUE TITLE
Difference between /provider services and app/services

### ISSUE THREAD

**Issue by tremendus** [adonisjs/adonis-framework#118]
So I understand the Provider pattern and the purpose of pulling dependencies .... but for what purpose would services be placed in the app/services folder? I don't see it referenced in the docs. 

Thanks

**Comment by thetutlage** [comment]
`app/services` does not have any logical entity in the framework itself.

It is just a folder to keep any services that you think can decouple your code. Taking an example blog i will keep a file called Categories inside the folder, which will have methods like `getAll()`, `getForPost()` etc.
