### ISSUE TITLE
How to add React.js to edge template for Frontend ?

### ISSUE THREAD

**Issue by premier213** [adonisjs/adonis-framework#1183]
i need to use edge Template for backend and Reactjs for Frontend but no integrated this!
please help me . tnx

**Comment by MarcusPianco** [comment]
Hi @premier213 in this channel you will have response ore fast: https://discordapp.com/invite/vDcEjq6.
But, if you need to use the edge template to send emails or something like that, in your back-end , you only to see this tutorial(adapted to your case): https://adonisjs.com/docs/4.1/mail, and use react in your front with an external  client. But, if you need to mix edge template(sintaxe, semantic) with ractJS, I think that is not possible in the same file/module.

**Comment by RomainLanz** [comment]
Hey @premier213! 👋 

This is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
