### ISSUE TITLE
Error installing npm dependencies

### ISSUE THREAD

**Issue by deep80** [adonisjs/adonis-framework#1186]
I am not able to install any other libraries like jquery, bootstrap css or even mysql using npm.

Error is as follows:

PS D:\Important\others\fresher> npm i mysql       
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'D:\Important\others\fresher\node_modules\.staging\fsevents-be04ebf9\node_modules\concat-map' -> 'D:\Important\others\fresher\node_modules\.staging\concat-map-280e0319'        

npm ERR! path D:\Important\others\fresher\node_modules\mysql\node_modules\string_decoder
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Important\others\fresher\node_modules\mysql\node_modules\string_decoder' 
-> 'D:\Important\others\fresher\node_modules\mysql\node_modules\.string_decoder.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deepk\AppData\Roaming\npm-cache\_logs\2020-01-05T04_07_28_365Z-debug.log

Please Help :-(

**Comment by thetutlage** [comment]
How is it related to AdonisJS?

**Comment by deep80** [comment]
I do feel the same. If I work on regular express app, i am not getting the
same error. Every thing works fine.

Do you think that it is related to operating system? Mine is windows 10 64
bit.

Please advise.

**Comment by thetutlage** [comment]
AdonisJS literally has nothing to do with what lives inside your node modules and what you install with npm. 

All I can suggest is, remove the `node_modules` completely and then do `npm install`

**Comment by deep80** [comment]
Everything went smoothly on Ubuntu 18 machine but in windows it's the same
old story.

This is really wiered.

**Comment by deep80** [comment]
Everything now went fine even on windows. It's still a mystery what caused
the error earlier.

Can you suggest some packages for generating tree structure on Adonis?
Laravel has a package called nested set

https://github.com/lazychaser/laravel-nestedset

Much like this

**Comment by RomainLanz** [comment]
Hi @deep80! 👋 

I believe we can close the issue since it's not related to Adonis and seems to be resolved now.

Concerning your latest message, this is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
