### ISSUE TITLE
How to customize JSON error response from my API?

### ISSUE THREAD

**Issue by viniciussvl** [adonisjs/adonis-framework#1189]
Hello everyone, how can I make it clear to the front end that the requested request has failed? For example, in this validation comes no parameter with status or error, how can I add this parameter globally to my JSON responses?

`[
  {
    "message": "min validation failed on password",
    "field": "password",
    "validation": "min"
  }
]`

Would using middleware to handle all JSON responses be a bad practice?

**Comment by RomainLanz** [comment]
Hey @viniciussvl!

This is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
