### ISSUE TITLE
Template Render Problems

### ISSUE THREAD

**Issue by darmie** [adonisjs/adonis-framework#119]
Hi, I am trying to use a filter and I am getting this error

`(C:\Users\Damilare\freelance\kangpe\resources\views\read-tip.html) RangeError: Maximum call stack size exceeded`

This is my filter 

```javascript
View.filter('nl2br', function nl2br (value) {
    return nl2br(value)
  })
```

**Comment by thetutlage** [comment]
Ofcourse, you are setting `nl2br` as the closure name and calling the same function inside the closure, it ends up in circular calls.

Do this instead

```javascript
View.filter('nl2br', function (value) {
    return nl2br(value)
})
```

**Comment by darmie** [comment]
Oh... Thank you!

**Comment by darmie** [comment]
Sorry to reopen this issue... is there a way I could use my `nl2br` filter that I would get this result

![2016-03-17 1](https://cloud.githubusercontent.com/assets/848002/13840438/dcd1c1c6-ec22-11e5-9d99-3d752f331bdb.png)

instead of this result => 
![2016-03-17](https://cloud.githubusercontent.com/assets/848002/13840385/8f091002-ec22-11e5-915a-eed578460cec.png)

**Comment by darmie** [comment]
It appears to return as a string, instead of a valid html

**Comment by thetutlage** [comment]
Make use of `safe` filter http://adonisjs.com/docs/2.0/views#auto-escaping.

```twig
{{ value | nl2br | safe }}
```

**Comment by darmie** [comment]
Thanks
