### ISSUE TITLE
How do I handle 404s?

### ISSUE THREAD

**Issue by seanc** [adonisjs/adonis-framework#120]
Hi, I'm pretty new to Adonis and I am having some issues regarding 404 errors in production. Unfortunately, when you visit a **non existent** route Adonis exhibits weird (?) behavior and crashes immediately.

I am wondering how I can handle this error.

Thanks.

**Comment by thetutlage** [comment]
Inside `bootstrap/start.js` there is a block to listen to `error` event and same is used to handle error. https://github.com/adonisjs/adonis-app/blob/develop/bootstrap/start.js#L51.

If you have better suggestions, i am all open to improve http error handling

**Comment by seanc** [comment]
I think if we could have some sort of error handling within the routes file that would be great. Something along the lines of how ExpressJS does it with Middleware perhaps?

**Comment by thetutlage** [comment]
I have added the Event provider to the core of the framework, it will make it possible to handle Http errors , in a better way.

## Teaser

```javascript
const Event = use('Event')
Event.on('Http.404', 'Http.handle404')
```

Here `Http.handle404` comes from `app/Listeners/Http.js` file. 

```app/Listeners/Http.js
Http.handle404 = function * (error, request, response) {
 yield response.sendView('errors/404')
}
```

**Comment by iyobo** [comment]
Hi Aman, thanks.
Also For now, line 55 of `bootstrap/start.js` should be removed in any serious app.

`process.exit(1)`
In the current state of this project, 404s cause the entire server to crash. Calling that an over-sight is a massive over-simplification.

Being a singular thread, The node process should never be ended trivially. 
Nothing should kill it of it's own volition.
That design pattern of ending process on a simple sneeze only makes sense if you are writing PHP, not server-side Javascript.

**Comment by thetutlage** [comment]
Nope, you should always let your application crash and get re-started by deamons like `forever` or `pm2`. http://shapeshed.com/uncaught-exceptions-in-node/

For http 404 error, you can manually add a check on `status` to see if it's 404 or not. For any other errors you should make the process die, failing fast and first is always a good practice

**Comment by iyobo** [comment]
That depends on the type of the exception, i.e. an uncaught exception and not every exception. 
404's and infact **all HTTP errors, should never qualify as uncaught exceptions **on a **framework** level, not an app level, and especially not a framework that prides itself on convention-over-config). 
UncaughtExceptions, by their very nature of being uncaught, kill the app on their own, in which case yes the best thing to do is to restart it.

Theory context mismatch aside, rebooting an app takes time.
The realities of running a server mean you have to account for attacks.
If it becomes clear that a certain url on your app makes your entire server-side app reboot, what black-hat won't have a field day messing up your system with a loop attack. That would be the easiest site to bring down and KEEP down.

**Comment by seanc** [comment]
Awesome stuff here, I forward to 3.0/

**Comment by DBadalyan** [comment]
Hello Everyone!!!
The fact that Adonisjs handle various errors is great, but it is always a good practice to make an app prepared for all errors and not let a framework to show an error itself, that errors are actually for developers, and it fill be embarrassing to have a live web application which is accidentally can show an system error.
So, even that from `bootstrap/events.js` this `Event.when('Http.error.*', 'Http.handleError')` navigates to `/app/Listeners/Http.js` it is not a event solution, but it is awesome cause by 2 lines of simple code we can handle an important case of 404's simply adding
```
if (status === 404 )
    yield response.sendView('front')
```

**Comment by RomainLanz** [comment]
Hey @DBadalyan! 👋 

The error you are currently seeing is only for development purpose, on production, these will not be displayed.

**Comment by DBadalyan** [comment]
@RomainLanz I'm new to adonisjs, and would like to know what would be then on production, I started looking and playing Adonis from yesterday. Thank you!

**Comment by DBadalyan** [comment]
@RomainLanz Oh, I'm new to Adonis, playing with it from yesterday, now I see it acts wonderful. Happy to learn that. Actually, I really appreciate the great job of Adonis developers.

**Comment by RomainLanz** [comment]
Yes!
