### ISSUE TITLE
[feature] auto register service providers

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-framework#1200]
## Why this feature is required (specific use-cases will be appreciated)?

atm on each package setup we have to manually register the sp, but with [npm scripts](https://docs.npmjs.com/misc/scripts) i think we can automate that,
basically what we need is `postinstall` & `preuninstall` to add/remove the service provider from the registry pool.

both scripts will need to be added to each package used by adonis, however i think we will need some type of an internal command or something to install/remove them instead of relying on the user script to avoid any mis-use or any bad behavior that might harm the user. 

## Have you tried any other work arounds?

 not yet

## Are you willing to work on it with little guidance?

yeah sure

**Comment by RomainLanz** [comment]
Hey @ctf0! 👋 

We have an RFC for this feature and it's planned to be added soon.
➡️ https://github.com/adonisjs/rfcs/issues/21
