### ISSUE TITLE
`make:test` is not a registered command

### ISSUE THREAD

**Issue by VictorLessa** [adonisjs/adonis-framework#1206]
the adonis make:test command is not working
## Package version
4.1.0

## Node.js and npm version
Node: 13.3.0
npm: 6.13.1

**Comment by RomainLanz** [comment]
Hey @VictorLessa! 👋 

Have you installed and configured the required package?

**Comment by VictorLessa** [comment]
@RomainLanz 
Yes, even when I run adonis -h this command "make: test" does not appear.
But this same command is described in the documentation

**Comment by jualahmed** [comment]
if you you Have installed and configured the required dependency successfully. the make:test commend should be appear. you can read the documentation to install https://adonisjs.com/docs/4.1/testing#_setup

**Comment by VictorLessa** [comment]
Solved to me, thank you very much
