### ISSUE TITLE
I am creating a typescript project based on adonisjs

### ISSUE THREAD

**Issue by nguyenpl117** [adonisjs/adonis-framework#1208]
I am creating a typescript project based on adonisjs. But I have a problem with require-stack. I don't know how to fix it, or I have to fix @ adonisjs / fold. I wonder if you can help me?
Line:
return require (requirePath);
I want to turn it into.
const m = require (requirePath);
if (m.default) {
   return m.default;
} else if (m [path.basename (requirePath)]) {
   return m [path.basename (requirePath)];
}
return m;

**Comment by GENL** [comment]
How did you create this typescript based project?,

**Comment by RomainLanz** [comment]
Hey @nguyenpl117! 👋 

The next release of Adonis will be Typescript based.
No need for you to work on this. 🤗

**Comment by nguyenpl117** [comment]
> Hey @nguyenpl117! 👋
> 
> The next release of Adonis will be Typescript based.
> No need for you to work on this. 🤗

When do you plan to publish it?

**Comment by nguyenpl117** [comment]
> How did you create this typescript based project?,

Does the typescript still run javascript normally?
