### ISSUE TITLE
belongsTo relation won't accept key other than 'id'

### ISSUE THREAD

**Issue by dakkafex** [adonisjs/adonis-framework#1211]
## Package version
4.1.0

## Node.js and npm version
12.16.1  6.13.1

## Sample Code (to reproduce the issue)
```
const y = await User.find(7)
const z = await y.signUps().with('session').fetch()
```
   ```
    session()   {
        return this.belongsTo('App/Models/Session', 'session', 'id')
    }
```

this results in a `` this.belongsTo is not a function`` error 

the column ``session`` exists in the table  ``signups`` so there should be no reason it is not reading it out, the only thing that will work is using ``id`` as FK and PK, but then its trying to apply the signup.id to find the session which obviously is not what I want.

- yes i have checked spelling
- turning around the FK and PK in the ``session()`` function yields the same result

**Comment by thetutlage** [comment]
You have defined the relationship in plural form `sessions` but trying to use it in singular form inside the `with` method

**Comment by dakkafex** [comment]
huh? when did I define it in plural?

On another note I have changed the column ``session`` to ``session_id`` and now it does work.

**Comment by thetutlage** [comment]
Closing, since it's working now.

**Comment by dakkafex** [comment]
but can you explain what you mean with plural? i have not defined ``sessions`` anywhere
