### ISSUE TITLE
How to start a Typescript based adonisjs project.

### ISSUE THREAD

**Issue by GENL** [adonisjs/adonis-framework#1212]
Hi! I want to know how to use the last release of AdonisJs(chore(release): 2.10.3) using typescript.

I really need this because I am migrating from typeorm project that I wrote entirely with typescript.

**Comment by RomainLanz** [comment]
Hey @GENL,

The preview of the next version be release in a short amount of time.

**Comment by GENL** [comment]
Great! I am impatient for it to come. Thanks for your hard work!
