### ISSUE TITLE
How to get Client's IP

### ISSUE THREAD

**Issue by darmie** [adonisjs/adonis-framework#122]
I know there's a method to get the ip which is `request.ip()` but it returns `127.0.0.1` which is localhost.

I want it to get the actual client's IP so that I can detect what country the client is browsing from.

**Comment by thetutlage** [comment]
You get `127.0.0.1` because you are reaching to your own local server from your machine. Host the application on a real server, then it will show the internet ip address

**Comment by darmie** [comment]
Ok. Thanks. I want to be sure it would show the user's IP address and not
the server's IP address

**Comment by parkerproject** [comment]
@thetutlage that's not the case because I am using DigitalOcean and still does that

**Comment by parkerproject** [comment]
still getting 127.0.0.1

**Comment by julioaze** [comment]
@parkerproject i have the same problem.
