### ISSUE TITLE
Queue System

### ISSUE THREAD

**Issue by seanc** [adonisjs/adonis-framework#123]
I think it would be neat to implement a Queue system, something along the lines of Laravel's queue system.

**Comment by thetutlage** [comment]
Part of roadmap https://trello.com/c/TKJmernd/20-queues

**Comment by nicklaw5** [comment]
Is the Queue system being worked on at the moment? I feel this is significant missing piece of Adonis.

**Comment by allanfreitas** [comment]
@nicklaw5 Yes, it's a important piece. 
But for now I think until it's released,
If you really need Queue, you can try to use some of these libs 
with adonisjs (I think it's not hard to put then to work with it):
https://github.com/LewisJEllis/bee-queue
https://github.com/Automattic/kue
https://github.com/OptimalBits/bull

**Comment by RomainLanz** [comment]
To complete @allanfreitas answer there's already a wrapper for [kue](https://github.com/Automattic/kue) - [adonis-kue](https://github.com/nrempel/adonis-kue).

**Comment by nicklaw5** [comment]
Thanks guys! I didn't really want to create my own if there was an official on the way.
