### ISSUE TITLE
javascript audio.pause() crashing app

### ISSUE THREAD

**Issue by ithrasil** [adonisjs/adonis-framework#124]
When i'm trying to pause audio in javascript, my app crashes. Error looks like this:

> _http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.writeHead (_http_server.js:180:21)
    at Server.finish (E:\adonis-framework\yardstick\node_modules\node-static\lib
\node-static.js:125:17)

It's strange, because when i'm loading music from cloud, everything works fine. Bug appears only, when audio is loading from 'public' directory.

**Comment by thetutlage** [comment]
Can u please share the code?

**Comment by ithrasil** [comment]
Thanks for answer!
So, it is my client side javascript: https://github.com/ithrasil/RainBeat/blob/master/public/scripts/functions.min.js, all repo code is here: https://github.com/ithrasil/RainBeat. 

My audio object is in 'piece' variable, and for know default sound is loaded from dropbox(16 line)
So interesting part are in: 30(invocation stopPlayback function) and 59 line(definition of stopPlayback function).

**Comment by thetutlage** [comment]
Pure problem with `node-static`, i switched to `serve-static` and all works fine. Will publish a hotfix, but trying to figure out the real issue with node-static.

**Comment by thetutlage** [comment]
Release `2.0.10` has the fix

**Comment by ithrasil** [comment]
When release 2.0.10 will be available?

**Comment by thetutlage** [comment]
Its release, you need to update the `adonis-framework` version in your package file

**Comment by ithrasil** [comment]
Thanks a lot, everything works :D
