### ISSUE TITLE
Running Adonis with Forever or PM2 is causing a problem

### ISSUE THREAD

**Issue by darmie** [adonisjs/adonis-framework#126]
I tried using `forever` or `pm2` to keep my app running , but it shows this error 

```
proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag
```

**Comment by thetutlage** [comment]
You need to pass `--harmony_proxies` flag while starting the server. This may work 

`pm2 -- --harmony_proxies start server.js`

**Comment by darmie** [comment]
I actually did it this way according to their docs `pm2 start server.js -- --harmony_proxies` , now I just used yours `pm2 -- --harmony_proxies start server.js` and none of them worked.

**Comment by thetutlage** [comment]
Try `pm2 start server.js --node-args="--harmony_proxies"`

**Comment by darmie** [comment]
The same problem. How do you keep your app running?

**Comment by thetutlage** [comment]
I make use of `--node-args`, you may have to raise this issue with pm2. It is all about passing the harmony flags

**Comment by darmie** [comment]
I fixed the problem using JSON configuration file instead

```json
  "apps" : [{
    "name"        : "Kangpe-fb",
    "script"      : "server.js",
    "watch"       : true,
    "instances"   : 4,
    "node_args"   : "--harmony_proxies",
    "env": {
      "NODE_ENV": "development",
    },
    "env_production" : {
       "NODE_ENV": "production"
    }
  }]
}
```
