### ISSUE TITLE
Session lost on Ajax request

### ISSUE THREAD

**Issue by imperez** [adonisjs/adonis-framework#127]
I'm not sure if I'm doing something wrong but figured to put in an issue just in case it's a bug. I am trying to post a new ajax request with the "_csrf" field set as documented. When this happens the SessionManager.sessionCookiePayload is null on the new request despite it already being set as a cookie beforehand. 

This results in my csrf token not found and after doing some debugging it turns out the keygrip module is throwing an error when trying to decrypt the adonis-session cookie. It catches the error and then returns false which results in no session data returned.

I do have an APP_KEY set but that doesn't seem to make a difference since we have a default value if it's not set. Is there anything I could be missing?

Here's the code that makes the ajax call. For this method I would make a call such as `call('post', '/api/company', {name: 'test'})`.

```
call (method, url, data) {
        let headers = {}
        // add in csrftoken on all api calls
        if (['post', 'put', 'delete'].indexOf(method) !== -1) {
            headers['csrf-token'] = $('[name="csrftoken"]').val()
        }
        let promise = $.ajax(
            url,
            {
                type: method,
                headers: headers,
                dataType: 'json',
                data: data
            })
            .done(function (response) {
                // if there are errors prompt the user
                if (response.errors && response.errors.length > 0) {
                    showError(response.errors)
                }
            })
            .fail(function (jqXHR, textStatus, error) {
                showError([error])
            })

        return promise
    }
```

I've also included a screenshot of the headers sent in the request for reference.

![screen shot 2016-03-30 at 7 00 28 am](https://cloud.githubusercontent.com/assets/481144/14140257/f16403f6-f645-11e5-8653-e64bb67c0348.png)

**Comment by thetutlage** [comment]
Can u please share some code to debug?

**Comment by imperez** [comment]
Sure just updated my original comment. The basic idea is I call the method I pasted and it sends the following headers I immediately get the CSRF missing error.

Let me know if you need anything else!

**Comment by thetutlage** [comment]
So basically this is what happening.

1. You make a ajax call and send the `csrf-token` inside the headers
2. And in response you are receiving the CSRF token missing error.

Is that the only issue? i believe you were also talking about something related to the sessions.

Also it will be great if you can share the error you are receiving from the server.

**Comment by thetutlage** [comment]
I tried and unable to reproduce it, sharing the repo with the sample code.
https://github.com/thetutlage/issue-127

**Comment by imperez** [comment]
That's basically what I'm doing. I make the Ajax call and then see the "csrf secret missing" error. 

As for the other information I mentioned, when I debugged the codebase to see what I could be missing I noticed in Shield's handle() method the `request.session.get(this.sessionKey)` call always returning empty. I checked SessionManager's `_getSessionCookie()` code and `sessionCookiePayload` was always set to null. That's what made me think the session kept getting lost.

After more debugging that's when I looked into node-cookie's parse method and eventually saw that in the keygrip module the error "error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt" was thrown when trying to decrypt the adonis-session cookie. That's what resulted in a null session being returned and the final csrf token error being thrown.

As you can see I really did fall down the debug rabbit hole! I'll clone the repo tonight to see if I can reproduce the issue in your repo. Thanks for all your help so far and the awesome framework!

**Comment by imperez** [comment]
I got a chance to try your repo and I also can't reproduce my error. So I'm sure theres an issue on my end. Feel free to close this issue and if I find anything relevant I will post a reply.

**Comment by imperez** [comment]
Ok I was finally able to reproduce it in the repo you created. I forgot to mention in my use case I was hitting a Controller in a subdirectory. I didn't think it makes a difference but it's the only thing that's difference from what you were doing in your original repo. Can that actually make a difference? 

Anyways if you take a look at my fork of issue-127 you can see the EBADCSRFTOKEN when it tries to hit the url `/api/ajax`.

https://github.com/imperez/issue-127

**Comment by thetutlage** [comment]
What's the concern here? It goes all good for me

First the route you registered here https://github.com/imperez/issue-127/blob/master/app/Http/routes.js#L16 is for a get request ideally you are making a POST request from ajax

**Comment by thetutlage** [comment]
Also can you share your .env file too?

**Comment by imperez** [comment]
ok turns out safari was caching the bad response. Once I tried it in another browser or incognito all is good. Sorry for the false alarm!
