### ISSUE TITLE
v2.0.10 broken on POST request

### ISSUE THREAD

**Issue by kbucksch** [adonisjs/adonis-framework#128]
Hey,

took me some time to recognize on server that there is a new version in npmjs.com called 2.0.10. This one seems to have problems when dealing with POST request. Getting everytime a 405 error response without any logging ;-)

Setted version in my package.json back to 2.0.9 solved the issue.

**Comment by thetutlage** [comment]
`2.0.10` has nothing to do with parsing the POST body, there seems to be some other issue.

Can u share a sample repo reproducing the issue

**Comment by thetutlage** [comment]
Fixed, it was my mistake that i removed a check :(

**Comment by kbucksch** [comment]
Great! And plaease forget the harsh words. I love the framework just would love to have it even more stable.

**Comment by thetutlage** [comment]
Sure, all bugs are welcome :smile:

**Comment by samundrak** [comment]
I am not getting data of post body ?
neither req.all() gets nor req.post() ?
`    'adonis-middleware/providers/AppMiddlewareProvider',`
is in providers
also enabled as global middleware ..
i have disabled shield middleware do this will impact?

**Comment by thetutlage** [comment]
Please create a separate issue and do share some code to understand what's going on
