### ISSUE TITLE
Change default timezone?

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#13]
timezone is 0 by default,how can I change it?

**Comment by thetutlage** [comment]
timezone in what ? you mean database entries ?

**Comment by wtser** [comment]
system time

**Comment by wtser** [comment]
![image](https://cloud.githubusercontent.com/assets/2093743/10869161/c9c629bc-80e0-11e5-9dd3-cded245670b5.png)

local server in China

![image](https://cloud.githubusercontent.com/assets/2093743/10869163/e3bfc0ee-80e0-11e5-8bd4-c705e3dfe59d.png)
server in Los Angeles

**Comment by thetutlage** [comment]
You need to change system time in NodeJs, try [node-time](https://github.com/TooTallNate/node-time) to have custom datetime zone
