### ISSUE TITLE
Correct way to pass Model Collection instance to a view

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#130]
Initially i was trying:

```js
  * index(request, response) {
    const articles = yield Article.all()

    yield response.sendView('articles', {articles: articles})
  }
```

```html
      {% for article in articles %}
        {{ article.title }}
        {{ article.slug }}
      {% endfor %}
```

But this didn't return anything, if i tried:

```js
  * index(request, response) {
    const articles = yield Article.all()

    yield response.sendView('articles', {articles: articles.__wrapped__})
  }
```

Then the template iteration worked correctly, is there a better way other than using `__wrapped__`?

**Comment by thetutlage** [comment]
use `articles.toJSON`. It is a standard lodash chain, so anytime u want to check certain implementation, jist refer lodash docs

**Comment by dan-gamble** [comment]
Ah thanks, i'm not very familiar with lodash so i'll look into that too, congrats on 500 stars too :)
