### ISSUE TITLE
Injecting the request instance into the templates.

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#131]
I was looking through the issues specifically at #109 which helped a bit but you don't have access to `request` and `response` on `App.start` (obviously). Is there a way to inject it into every template by default instead of passing it in every controller method?

**Comment by thetutlage** [comment]
Why do you want to inject request and response instance to the view?

**Comment by dan-gamble** [comment]
Not the response, just the request. No particular reason at the moment, i just use Django normally and that's one of the normal things i've got used to from Django so was seeing if it was possible with this.

**Comment by thetutlage** [comment]
It is possible, but i will recommend it much.

Create a global middleware and write following to it's `handle` method

```
* handle (request, response, next) {
  View.global('request', request)
}
```

**Comment by dan-gamble** [comment]
Thanks, helpful to know. Will not use it for now and inject the request if i need it. Adonis is very different to Django so it might not be needed at all.
