### ISSUE TITLE
Allow template extension customization

### ISSUE THREAD

**Issue by gabe-alex** [adonisjs/adonis-framework#133]
It would be nice if we could change the file extension used for templates.
Even better if Adonis used something specific instead of html by default.

Having them as HTML messes with the formatting in some editors, like WebStorm.
With a custom extension, we could at least fix this ourselves and not affect the settings for real html.

**Comment by thetutlage** [comment]
Will add support for `.nunjucks`.

**Comment by dan-gamble** [comment]
Is there a way to allow the use of `.html` still? My editor provides a lot of help if it uses the `.html` extension :)

I tried: `extensions: ['html']` in `config/app.js` but they didn't seem to help.

**Comment by gabe-alex** [comment]
This is why I said a customizable extension would be better...

**Comment by dan-gamble** [comment]
I did just have a look in the source based on the commits above. Not quite sure how to get the `Config` in the `View/loader.js`. Was thinking of being able to specify the view extension in the `config/app.js`. On `adonis new` it would default to `extension: 'nunjucks'` but you can change this to whatever you want.
