### ISSUE TITLE
Lucid within Ace command

### ISSUE THREAD

**Issue by Matthijn** [adonisjs/adonis-framework#135]
Currently I'm writing a very simple command to run some seeds. And writing the command itself goes wel (e.g it searches the seed directory for seed files, and calls a run method on those).

However, as soon as I add a use('App/Model/User') (or any Lucid model) it will hang on that point. It's like it is trying to connect to the database, but it never actually does that (and might be waiting for a timeout of some sort). There is no error, it just hangs. 

The database (and same model) is approachable within the same Adonis application from a GET request to a route. So, I'm wondering, is the database connection not loaded? 

I took a peek at how it was done in de migration command. But honestly, that did not make me much wiser.

**Comment by thetutlage** [comment]
Are you able to seed your database? Means are you able to save records in your database ?

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-lucid #26](https://github.com/adonisjs/adonis-lucid/issues/26) via [**ZenHub.io**](https://www.zenhub.io/)
