### ISSUE TITLE
adonis-cli installing a last version 3, but have erros.

### ISSUE THREAD

**Issue by dielduarte** [adonisjs/adonis-framework#137]
I Want using adonis in version 2, but i upgrade my adonis-cli and when I run this, he installing a new version 3.  how I can install version 2?

**Comment by thetutlage** [comment]
What command you are using? just checked. `adonis new test-app` works as expected

**Comment by dielduarte** [comment]
So, in my first test adonis new create app with version 3. but now, i run adonis new and this create app with version 2. 

thanks.
