### ISSUE TITLE
pg-native error

### ISSUE THREAD

**Issue by dielduarte** [adonisjs/adonis-framework#138]
for example, in this function bellow:
    
 * show (request, response) {
      let id = request.params().id;
      let user = yield User.find(id);

      response.json(user);
    }

I get error:

{ [Error: Cannot find module 'pg-native'] code: 'MODULE_NOT_FOUND' }

but in others functions this error don`t exist.

**Comment by thetutlage** [comment]
You need to install `pg-native`.
