### ISSUE TITLE
any plan to add typescript and es7(async/await) ?

### ISSUE THREAD

**Issue by coolicer** [adonisjs/adonis-framework#140]

**Comment by thetutlage** [comment]
@coolicer No, i am not in favor of adding any transpilers or build steps.

**Comment by alexjoverm** [comment]
What about now @thetutlage ? It is already supported in Node 7 natively

**Comment by RomainLanz** [comment]
`async/await` is planned for Adonis 4.0! 🎉

**Comment by alixaxel** [comment]
@RomainLanz what is the timeline for that? I'm starting a new project and it would be useful to know if I should wait.

**Comment by RomainLanz** [comment]
There's no release date at the moment. You can follow [the roadmap for 4.0 in the adonis/discussion repository](https://github.com/adonisjs/discussion/issues/19).
