### ISSUE TITLE
./ace - No such file or directory

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#141]
I created a fresh droplet on Digital Ocean (The Node one click app) and followed the starting piece in the documentation to create `yardstick`.

When i try and use Ace i get:

```bash
adonis@adonis:~/yardstick$ ./ace
/usr/bin/env: node --harmony_proxies: No such file or directory
```

`which node` gives me `/usr/bin/node`

**Comment by dan-gamble** [comment]
Node version `4.4.3` btw

**Comment by keeross** [comment]
Are you using nvm or just clean node install from apt?

**Comment by thetutlage** [comment]
@dan-gamble Make use of `node --harmony_proxies ace` and your command. 

It is a combination of several issues, i will be writing a blog post + a command to fix `ace` file.

**Comment by dan-gamble** [comment]
I tried both global node & `nvm`.

That worked @thetutlage! I'll just set up an alias to use in the interim :)

**Comment by thetutlage** [comment]
Sure, the problem is `--harmony` flag does not work when using `/usr/bin/env node`. It needs to be `/usr/bin/node`. 

Since the installation of NodeJs is different from every OS and also depends upon the way you have installed NodeJs.

I will add a command to `adonis-cli` to fix the ace file with the correct location of node on the current OS.

**Comment by dan-gamble** [comment]
Awesome, thanks for the help :)

**Comment by glexposito** [comment]
Hi Guys, I ran adonis fix and the issue was not fixed for me. I am using antergos. Any idea?

**Comment by vizo** [comment]
Maybe this will help for Linux systems ...

http://stackoverflow.com/questions/8108917/why-does-passing-arguments-to-the-command-in-an-env-invocation-not-work

**Comment by vizo** [comment]
Ok i found hack for Linux... http://sambal.org/2014/02/passing-options-node-shebang-line/
It should be:
```
#!/bin/sh 
":" //# comment; exec /usr/bin/env node --harmony_proxies "$0" "$@"

'use strict'
/*
|--------------------------------------------------------------------------
|   Running Console Commands
|--------------------------------------------------------------------------
|
|  Here we invoke console commands registered under Ace store.
|
*/
const kernel = require('./bootstrap/kernel')
kernel()
```
It works for me, can anyone test it on OSX?

**Comment by thetutlage** [comment]
@vizo Kind of works great, have to test it on Windows too

**Comment by juan55860** [comment]
Great!! @vizo it works :+1:

**Comment by Artemidas** [comment]
Hey guys, you also may use `node ace make:[command] <params> ...` from the Adonis project folder, and it does'n matter what OS you are using, just need NodeJS to run.

**Comment by rindia** [comment]
C:\Users\Admin\demowork>./ace                                                                                                     
'.' is not recognized as an internal or external command,                                                                         
operable program or batch file.

**Comment by rindia** [comment]
C:\Users\ROHIT SAINI\ya>./ace                                                                                                     
'.' is not recognized as an internal or external command,                                                                         
operable program or batch file.  

how to fix this problem ?

**Comment by navdeepsingh** [comment]
In windows env use
node --harmony-proxies ace migration:run

Like above

**Comment by iben12** [comment]
added an alias like `alias ace="node --harmony-proxies ./ace"`, so I just go `ace make:model Cool` in the app root and it works.

**Comment by raulvillca** [comment]
i have an issue when i tried to create a new project:

✔ Your current Node.js & npm version match the AdonisJs requirements!
✖ An error occured while trying to access "/Documents/WKS_SERVER/my_chat" directory
Cannot read property 'F_OK' of undefined

**Comment by RomainLanz** [comment]
May you create a new issue and specify which OS you use (it looks like Windows) and which command do you run @raulvillca ?

**Comment by thetutlage** [comment]
@RomainLanz Fixed. Node.js v6.2 has `fs.constants` as undefined whereas v6.3 and later have `fs.constants` as defined. The weird part is versions earlier than v6.2 also has `fs.constants` defined.

**Comment by RomainLanz** [comment]
Good to know! Thanks.

**Comment by pushkertiwari** [comment]
.ace is not working , please suggest me how to get rid of this issue

**Comment by RomainLanz** [comment]
Dear @pushkertiwari !

What's your problem?

**Comment by pushkertiwari** [comment]
.ace make:controller home is  not working , i have tried all the ways , but cli of adnois is not working in the terminal , always giving the isssue in the .ace is not found. @RomainLanz

**Comment by RomainLanz** [comment]
You need to use `./ace` and not `.ace` to use it inside your terminal.
You can also directly use it with node via `node ace`.

```bash
$ node ace make:controller XXX
```

**Comment by pushkertiwari** [comment]
thanks @RomainLanz  , you have solved my problem.

**Comment by pushkertiwari** [comment]
@RomainLanz  could you please help me in the autenication process of adnois js

**Comment by RomainLanz** [comment]
@pushkertiwari Please join the gitter for those kind of questions

**Comment by DLUK44** [comment]
To run ace on Windows, create a file called ace.cmd in the root of your project with the following content
```
cd %~dp0
node ace %*
```
Now you can run `ace make:view home` (but NOT `./ace make:view home`, so careful when following tutorials etc.)

**Comment by horiyomi** [comment]
There seem to be an issue when running during development. The server throw an event.js error while still serving, however the client is still connected to but the server still shows the error.  I'm on a windows 10 machine.
________________________________

**Comment by RomainLanz** [comment]
Hey @DLUK44, @horiyomi !

First of all, thanks for the tips @DLUK44, we'll add that to the documentation for 4.0 if it's not already inside.

@horiyomi, may you create a new issue with the error you get?

**Comment by thetutlage** [comment]
@RomainLanz 

In 4.0 `adonis` proxy all the project specific commands. So instead of running `ace <cmd>`, you can do `adonis <cmd>`, which fixes all cross platform issues

**Comment by salvadorzepeda** [comment]
you should create a file named ace.js in the root with this code inside:
```

#!/usr/bin/env node

'use strict'
const kernel = require('./bootstrap/kernel')
kernel()
```
