### ISSUE TITLE
[TypeError: Route.resource(...).middlewares is not a function]

### ISSUE THREAD

**Issue by dielduarte** [adonisjs/adonis-framework#142]
How to use middlewares using route.resource ??

**Comment by dielduarte** [comment]
I have 3 routes : 

`const Route = use('Route');

Route.get('/', 'HomeController.index');

Route.post('api/auth', 'AuthController.auth');

Route.resource('users', 'UsersController');`

and one middleware called a auth. I do not declared middleware on any route, but when I called any route the middleware is called. How I can resolve this?

**Comment by thetutlage** [comment]
Wrap it inside a group.

```javascript
Route.group('web', function () {
   Route.resource('')
}).middlewares('')
```

**Comment by dielduarte** [comment]
that works, thanks!
