### ISSUE TITLE
./ace no output on current v3 dev

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#143]
I've tried running:

`./ace`, `node --harmony_proxies ace`, `node --harmony_proxies ace migration:make create_articles_table`

And every time there is no output and no table gets created.

Using OSX with Node `5.9.0`.

This was after a clean install using `adonis new yardstick --dev` `cd yardstick` `./ace`

**Comment by thetutlage** [comment]
Do `ace --help` since the command has changed. All file generation commands have been moved into `make:` namespace. So try `ace make:migration create_articles_table --create=articles`. Do check `help` everytime

**Comment by dan-gamble** [comment]
Hmm, i have no idea what happened here..

I just started a new test project and tried `./ace` again and it was fine. On my other project that i have i tried it again:

```
~/Workspace/adonis/dangamble
❯ ./ace migration:make create_articles_table

~/Workspace/adonis/dangamble
❯ ./ace migration:make create_articles_table

~/Workspace/adonis/dangamble
❯ ./ace

~/Workspace/adonis/dangamble
❯ cat ace
#!/usr/bin/env node --harmony_proxies
'use strict'

const kernel = require('./bootstrap/kernel')
kernel()
```

Nothing seems to be output. Luckily it's right at the start so i'll just remake it, thanks :)
