### ISSUE TITLE
Cannot flash an empty object

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#144]
Sorry, me again!

I was following: http://adonisjs.com/docs/2.0/validation#basic-usage and trying to combine it with: http://adonisjs.com/docs/2.0/request#flash-messages.

I ended up with this code:
```js
  * store (request, response) {
    const rules = {
      title: 'required',
      body: 'required'
    }

    const data = request.all()
    const validation = yield Validator.validate(rules, data)

    if (validation.fails()) {
      yield request.flashAll()

      return response.redirect('back')
    }
  }
```

When i submit my form i get the error: `Cannot flash an empty object`

My `request.all()` looks like: `{ _csrf: 'iLQJHmq3-8jiB2v0yOqPOdRZ0qu1UQ64SUHo', title: 'Test' }`

Am i doing something stupid / missing something? :)

This on on `--dev` (v3) btw

**Comment by thetutlage** [comment]
You are using docs from `2.0`, `flash` has breaking changes. This may help https://github.com/adonisjs/adonis-middleware/blob/develop/src/Flash/methods.js

Also i believe the syntax will be

```javascript
yield request.withAll().flash()
yield request.withAll().andWith('some custom object to merge').flash()
```

**Comment by dan-gamble** [comment]
Thank you :) Are the 3.0 dev docs live anywhere yet?

**Comment by thetutlage** [comment]
Nope, i am almost done with the [Auth provider](https://github.com/adonisjs/adonis-auth). So next part is to write docs.

**Comment by dan-gamble** [comment]
Awesome, looking forward to it :)
