### ISSUE TITLE
Receiving an empty array on Model.all()

### ISSUE THREAD

**Issue by seanc** [adonisjs/adonis-framework#148]
Hello, I'm experiencing some odd behavior when calling the `.all()` method on my model. It is currently returning an empty array, when I chain `.withTrashed()` I can then get all of my database data, how can I fix this?

**Comment by thetutlage** [comment]
Do you have soft deletes on?

**Comment by seanc** [comment]
Yeah.

**Comment by thetutlage** [comment]
If all of the entries inside the database have `deleted_at` timestamp set to a date. `all` will not pick them as they are considered deleted.

**Comment by seanc** [comment]
So I will need to disable soft deletes?

**Comment by thetutlage** [comment]
That's your decision. You may read more about soft deletes here http://www.pcmag.com/encyclopedia/term/57355/soft-delete

**Comment by seanc** [comment]
Alright thanks, I just went ahead and disabled soft deletes, however I will look into a more suitable solution for me at a later time.
