### ISSUE TITLE
How do you get following login functionality to work properly?

### ISSUE THREAD

**Issue by woss** [adonisjs/adonis-framework#15]
I've been having some issues with understanding Lucid, and overall api. Documentation is kinda ok but i couldn't find descriptions on api, so i started checking the code. 
Can you help me with this. How would you write this? Check for user, session login. Thanks
```
class AccessController {
  * login(request, response) {
    const rules = {
      username: 'required|email',
      password: 'required|min:6'
    }
    let data = request.post()

    yield Validator.validate(rules, data)

    // checking if validation has failed
    if (Validator.fails()) {
      return Validator.messages()
    }

    let currentUser = yield User.where('username', '=', data.username).fetch();
    currentUser = currentUser.toJSON()[0];
    if (!currentUser.id) {
      response.send(404).json({
        message: 'User not found'
      });
    } else {
      let currentSession = yield Session.where('user_id', '=', currentUser.id).fetch();
      currentSession = currentSession.toJSON();
      console.log(currentSession);
    }
}
```

**Comment by thetutlage** [comment]
do u have session model or u planning to manage sessions of your own ?

adonis has support for cookie n file based sessions

**Comment by woss** [comment]
I couldn't find place where you explain usage of session, i didn't even know of it before i checked the code :)

full file 

```
'use strict'

const User = use('App/Model/User');
const Session = use('App/Model/Session');
const Validator = use('Validator');
const SessionProvider = use('Session');

class AccessController {

  * login(request, response) {
    const rules = {
      username: 'required|email',
      password: 'required|min:6'
    }
    let data = request.post()

    yield Validator.validate(rules, data)

    // checking if validation has failed
    if (Validator.fails()) {
      return Validator.messages()
    }

    let currentUser = yield User.where('username', '=', data.username).fetch();
    currentUser = currentUser.toJSON()[0];
    if (!currentUser.id) {
      response.send(404).json({
        message: 'User not found'
      });
    } else {
      let currentSession = yield Session.where('user_id', '=', currentUser.id).fetch();
      currentSession = currentSession.toJSON();
      console.log(currentSession, SessionProvider);
    }


  }
  * validate(request, response) {}
  * refresh(request, response) {}
  * revoke(request, response) {}
  * logout(request, response) {}
}

module.exports = AccessController

```

**Comment by thetutlage** [comment]
yeah it seems to be missing in the documentation, give me an hour i will sum it up for everyone.

Also v2 of adonis is 80% ready and it covers all use cases to write end-2-end apps

**Comment by woss** [comment]
oh cool. can i start using it already? is it develop branch?

**Comment by thetutlage** [comment]
ahhh no, lot of core components have been re-written and adonis itself is a combition of several internal modules. 

So hve to wait for sometime to get access to a stable release and list of breaking changes

**Comment by woss** [comment]
ah. so if i continue my project with v1 it's a rewrite for v2. 
for now i would like to know more in details about session, controller and Lucid.

**Comment by thetutlage** [comment]
It is going to be a re-write for you , there will be breaking changes, the overall api will remain same

**Comment by thetutlage** [comment]
Here you go with docs http://adonisjs.com/docs/1.0/request#session-management

Let me know if you can face any issues, which are likely to be solved itself in `v2`

**Comment by woss** [comment]
thanks.
