### ISSUE TITLE
repo for version 3.0 and document

### ISSUE THREAD

**Issue by ajayphp** [adonisjs/adonis-framework#154]
Hi,

I am php developer and new to nodejs and looking for framework for web app and api for mobile
end to use. 

while googling i found you and as i bit experienced of laravel and really happy to saw Adonis
but i want to start with new , so interested with latest version 3.0 how to install 3.0 
and where i read document for v3.0 

could you guide me ... .,

as you inspired by Laravel , also see yii2 that is brilliant even from laravel to create fast , best , secure 
php .... you can also have look once that. 

please advice how to create separate api as module v1 and v2 etc. to make SOA
and how to use with Angular 2 in frontend. 

if you could write blog etc. on above topics

+like , hope 3.0 would be LTS stable version.

Regards,

**Comment by thetutlage** [comment]
Docs will be coming with the final release of 3.0, other requests noted.

**Comment by ajayphp** [comment]
Hi, 

I am to start with adonis as  so you suggested for new better to start with 3.0,
when could i expected 3.0 release and getting started doc etc.

i am ready to help, asap i understand this flow.
