### ISSUE TITLE
For ace there is another working way

### ISSUE THREAD

**Issue by samundrak** [adonisjs/adonis-framework#158]
If there is error when trying ace command
and error output is
 `/usr/bin/env: node --harmony_proxies: No such file or directory`
Then on root of adonisjs app at ace file at top
replace 
`#!/usr/bin/env node --harmony_proxies`
with
`#! node --harmony_proxies`

**Comment by thetutlage** [comment]
Adonis new includes a command to fix the ace file for the OS you are on. `adonis fix`. Make sure to update the `adonis-cli`.

```bash
npm i -g adonis-cli
```

**Comment by lordpixel** [comment]
Not working for me, I think it's because I'm using NVM to admin my node versions, any idea how can I fix this?

**Comment by salvadorzepeda** [comment]
you must create a file named ace.js in the root with this code inside:

#!/usr/bin/env node

'use strict'
const kernel = require('./bootstrap/kernel')
kernel()
