### ISSUE TITLE
POST body are empty

### ISSUE THREAD

**Issue by samundrak** [adonisjs/adonis-framework#159]
I am not getting data of post body ?

neither `req.all()` gets nor `req.post()`.

`adonis-middleware/providers/AppMiddlewareProvider` is in providers.

Also body parser is enabled as global middleware ..
i have disabled shield middleware do this will impact?

**Comment by thetutlage** [comment]
What is `adonis-middleware/providers/AppMiddlewareProvider` ?

and can you share the code of controller, where you are using `req.all()` ?

**Comment by samundrak** [comment]
```
This is my routing file
'use strict';
module.exports = function(api) {
    api.group('apis', () => {
        api.post('/register', 'UserController.register');
        api.post('/login', 'UserController.login');
    }).prefix('/api');
}
```

And its my register method of UserController
```
*register (req,res){
    	const rules =  {
    		email : 'required|email',
    		password : 'required|min:6'
    	}

    	console.log(req.hasBody())
    	console.log(req.all())
    	const validation = yield Validator.validate(rules,req.post());
    	if(validation.fails()){
    		return req.error(req.formatedValidation(validation.messages()));
    	}
    	//if success
    }

```

**Comment by thetutlage** [comment]
It looks fine to me. May i know how you are sending the post data? If it is using postman, then a screenshot will be great. 

And please do share the output of `req.hasBody()` and `req.all()`.
