### ISSUE TITLE
how to render a JSON object in the Dom?

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#16]
obj={title:"aaa",content:"bbb"}

in the view I use {{obj}} ,but it rendered as "object"

i want it rendered as JSON.stringify(obj)

how can I do it ?

**Comment by thetutlage** [comment]
you mean from your views?

**Comment by thetutlage** [comment]
Use the json filter inside your views 

```twig
{{ obj | json }}
```

**Comment by wtser** [comment]
yes,in the views.

I try it brefore, but it render nothing

![image](https://cloud.githubusercontent.com/assets/2093743/11012927/441b61be-8537-11e5-8abe-228023a21c6b.png)

![image](https://cloud.githubusercontent.com/assets/2093743/11012929/50a1a20e-8537-11e5-8113-c285f4d9139f.png)

**Comment by thetutlage** [comment]
There was a minor bug , resolved as of `1.1.3`. Update `adonis-framework`
