### ISSUE TITLE
Ability to increase request size limit?

### ISSUE THREAD

**Issue by ChezFre** [adonisjs/adonis-framework#163]
I'm trying to save a png I pulled from a canvas, but whenever I perform the request I get `Error 413: request entity too large`. I've found a bunch of related articles, but they all show how to change this using Express [[1]](http://stackoverflow.com/questions/25332561/node-js-express-large-body-for-bodyparser) (although it seems to be based on body-parser, which adonis relies on as well).

EDIT: The actual error is thrown in `9. makeError <#anonymous> node_modules/raw-body/index.js 198`, which is where the limit is enforced.

Could you perhaps point me in the right direction?

**Comment by thetutlage** [comment]
@ChezFre It will be configurable in the new release or if you have just started the project, i would recommend switching to dev release. Here is blog post on dev release https://adonisjs.svbtle.com/adonis-30-dev-release

**Comment by ChezFre** [comment]
Thanks for your reply. I've temporarily enforced the limit in the `raw-body` module since it's a project that will only run locally, but I might look into the 3.0-dev release later.

**Comment by thetutlage** [comment]
Closed issue, as it has already been done just not released
