### ISSUE TITLE
authUser variable seems to be buggy in condition in view

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-framework#166]
Hi there !

I have a weird problem with a condition in my view to display different content when I user is logged in or not.

So I'm using the `authUser` variable which is send by default to any views.
I have got in my `navbar` partials a condition to display the `Login / Register` button or user information.

```twig
<div id="nav-bar-right">
  {% if authUser %}
    <div class="nav-bar-user">
      <!-- ... -->
    </div>

    <div class="nav-bar-separator"></div>

    <div class="nav-bar-actions">
      <!-- -->
    </div>
  {% else %}
    <div class="nav-bar-login">
      <p><a href="#" @click.prevent="showLoginModal">Connexion</a> / <a href="#" @click.prevent="showRegisterModal">Inscription</a></p>
    </div>
  {% endif %}
</div>
```

This is working perfectly (I have only tested it when I'm not logged in).<br>
I also have a condition to display modal when you're not logged in. You can find the code below.

```twig
{% if not authUser %}
  {% include 'frontend.modals.login' %}
  {% include 'frontend.modals.register' %}
{% endif %}
```

This doesn't work. I have also try some "hacks" to make it works but nothing happens.

```twig
{% if authUser %}
  {% include 'frontend.modals.login' %}
  {% include 'frontend.modals.register' %}
{% endif %}

{% if not authUser %}
  {% include 'frontend.modals.login' %}
  {% include 'frontend.modals.register' %}
{% else %}
  {% include 'frontend.modals.login' %}
  {% include 'frontend.modals.register' %}
{% endif %}
```

Both example under display nothing. I have tried to display the variable `authUser` in my view to see his content. So I have put `{{ authUser | json }}` before the two conditions. Nothing is display.

**Comment by RomainLanz** [comment]
I come back to give you update.

So I have finish my login/register function and the `if/else` in the navbar doesn't work either. `authUser` seems always `empty` (not `null`).

**Comment by thetutlage** [comment]
@RomainLanz `authUser` is only to the views by the named `auth` middleware.

```javascript
Route.get('/profile', 'UserController.profile').middleware('auth')
```

Also make sure to update the `adonis-auth` package from github, coz I added this global around a week ago and may be your app has the old version

**Comment by thetutlage** [comment]
> Reference from the conversation on Gitter

Stateless and stateful authentication will have a little difference in how you access the user from your controllers and views.

Stateful Authentication will have the access to a variable called `currentUser` on each request and view after the user has loggedIn

Whereas Stateless authentication like `JWT` and `API` will have access to the variable called `auth` on the request object. There will be no view's global for stateless auth, since creating a view with JWT in place is not expected.

**Comment by niallobrien** [comment]
When can we expect this to be implemented? Thanks.

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-auth #6](https://github.com/adonisjs/adonis-auth/issues/6) via [**ZenHub.io**](https://www.zenhub.io/)
