### ISSUE TITLE
Hi i dont know if this is a issure or not

### ISSUE THREAD

**Issue by Jamesoncy** [adonisjs/adonis-framework#168]
i just want to ask if how to do knex.js in models, ive try to create my own but it fails, it doesnt recognized by the controller, can you give samples on how to do it, also how classes to be extend from another model or controller, thanks

**Comment by thetutlage** [comment]
@Jamesoncy Can you be more specific with the issue. Share some code of what exactly you are trying to achieve

**Comment by Jamesoncy** [comment]
thanks for the reply 

HomeController

'use strict'

const User = use('App/Model/User')

class HomeController {

  * index (request, response) {
    response.json(User.getUsers())
  }

}

module.exports = HomeController

Model

'use strict';

let Lucid = use('Lucid'),
   Database = use('Database');

class User extends Lucid {

  getUsers(){
    let query = yield Database.table('users').select('*');
    return query;
  }

}

module.exports = User

i just wanna run some knex.js queries in the model but seeems i cannot retrieve it, asking if im doing it right or wrong, thansk for the feedback

**Comment by thetutlage** [comment]
Okay you are following the wrong approach here. Models can run queries on themselves, so there is no need to import `Database` into a model.

**Model**

```javascript
const Lucid = use('Lucid')

class User extends Lucid {

}

module.exports = User
```

Now inside your controller you need to do

```javascript
const User = use('App/Model/User')

class HomeController {

  * index (request, response) {
      const users = yield User.all()
      response.json(users.toJSON())
  }

}
module.exports = HomeController
```

Also I would suggest you to read more about ES2015 Generators https://medium.com/javascript-scene/the-hidden-power-of-es6-generators-observable-async-flow-control-cfa4c7f31435.

And read some docs on Lucid http://dev.adonisjs.com/docs/3.0/lucid

**Comment by Jamesoncy** [comment]
ah ... ok ahhahahaha im just trying if that can be happened, ok thanks
ahhahah so i just nid to stick with the lucid, also with the join queries ?

**Comment by thetutlage** [comment]
Yes
