### ISSUE TITLE
Adonis Route OPTIONS request

### ISSUE THREAD

**Issue by vlasov2312** [adonisjs/adonis-framework#17]
I use Adonis Framework as backend and angularjs for frontend.
My routes: 
```
Route.post('/user/registration', 'UserController.registration');
```
If i use Adonis on another domain how to resolve OPTIONS request for cross domain ajax?

it request return this headers for me:
```
Access-Control-Allow-Headers:Content-Type, Authorization
Access-Control-Allow-Methods:GET,PUT,POST,DELETE
Access-Control-Allow-Origin:*
```

```
Remote Address:127.0.0.1:8080
Request URL:http://localhost:8080/user/registration
Request Method:OPTIONS
Status Code:200 OK
```

Route.any()  is ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] only.
Where is OPTIONS?

**Comment by vlasov2312** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by thetutlage** [comment]
i realized this issue and planning to fix it in upcoming version transparently. For now you can do following

### routes.js
```javascript
Route.match(['options'],'*',function * () {
  return 'allowed'
})
```

and then add a middleware to allow CORS for all requests.

### app/Http/Middleware/Cors.js
```javascript
'use strict'

class Cors{

  *handle (request, response , next) {

    response.header("Access-Control-Allow-Origin", "*");
    response.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Distinct-Id, Customer-Id, Distinct-Email");
    yield next
  }
}
module.exports = Cors
```

finally add it as a global middleware inside `app/Http/kernel.js`

```javascript
const globalMiddlewares = [
  'App/Http/Middleware/BodyParser',
  'App/Http/Middleware/Cors'
]
```

**Comment by mehsan1** [comment]
Hey, as the documentation mentions that other than POST & GET, all can be used but you need to send this value in _method parameter. this is called method / function spoofing. for spoofing , you should a POST request.
