### ISSUE TITLE
adonis question ? 

### ISSUE THREAD

**Issue by flessard** [adonisjs/adonis-framework#170]
In adonis there is a way to create a module ? If i want to have a module blog in my app, how i can create a folder contain the same structure of folder app and i can load outside the app folder ? 
```

Projects/
    |-- Modules/
        |-- Blog/
            |-- Http/
                |-- Controllers/
            |-- Model/
            |-- Providers/
            |-- Resources/
                |-- Lang/
                |-- Views/
```

**Comment by thetutlage** [comment]
Very broad question. Out of the box there is no support for this kind of layout. But you can explore the IoC container more to see what best you can get out of it.
