### ISSUE TITLE
is it possible to runknex,js queries in models?

### ISSUE THREAD

**Issue by Jamesoncy** [adonisjs/adonis-framework#172]
hai im planning to run knes.js queries in model? is that possible?

**Comment by thetutlage** [comment]
Yes

```javascript
User.query().where('').fetch()
```

Just make sure to call `fetch` at the end

**Comment by Jamesoncy** [comment]
So ill instantiate a const Database = use (''Database")

and the class model will be extended in Lucid, then query like that?

**Comment by RomainLanz** [comment]
No, you can use the `QueryBuilder` by using the `Database` class but you can also directly use your model.

You only need to call the `query()` method to have back the `QueryBuilder` without doing something special.

Not that Lucid wrap the `QueryBuilder` to have a pretty API. :)

**Comment by WesleyRibs** [comment]
Hi, I am a beginer with AdonisJs. How Can I to do this with my Model ?
```javascript
const query = Database.table('users')

if (username) {
  query.where('username', username)
}
```
I am trying something like this:

```javascript
'use strict'
const User = use('App/Model/User')

class UsersController {

  * index(request, response) {
    const Users = yield User.where('active', true)

    if (username) {
      Users.where('username', username)
    }
 }
}
```
but I recive this messagem: **users.where is not a function**
thanks
