### ISSUE TITLE
hi i want to write queries in model like this, is it possible?

### ISSUE THREAD

**Issue by Jamesoncy** [adonisjs/adonis-framework#176]
class Log extends Model {
  /**
   * Log Model Constructor
   */
  constructor () {
    super();
  }

  /**
   * Adds a new log of the given transaction.
   * @access public
   * @param transactionId .. Id that identifies a unique transaction (generated by providers)
   * @param body .. body of the transaction
   * @param type .. this can be incoming or outgoing
   * @returns {*}
   */
  *addLog (transactionId, body, type) {
    return yield this.query(
      'INSERT INTO logs(transaction_id, body, type) VALUES (?,?,?)',
      [transactionId, body, type]
    );
  }

}

**Comment by thetutlage** [comment]
Cannot understand anything, can you please format the issue?

**Comment by Jamesoncy** [comment]
im trying to write my queries in this way, but it seems not working... do you have a good way of doing it, but not using lucid stuff
![adonis](https://cloud.githubusercontent.com/assets/12342949/15779304/2115ffbc-29ce-11e6-820a-718d110479a5.png)

**Comment by thetutlage** [comment]
`getUsers` needs to be a generator method.

```javascript
* getUsers() {
    // your code
}
```

It is better to use existing methods, for this situation it will be.

```javascript
const users = yield User.all()
response.json(users)
```

**Comment by Jamesoncy** [comment]
any advice on this? new to node here :)
![desktop](https://cloud.githubusercontent.com/assets/12342949/15779670/336fd622-29d0-11e6-8bc6-e7f641630774.png)

**Comment by RomainLanz** [comment]
@Jamesoncy You should first take a look at the Active Record pattern.

* [Active Record](http://guides.rubyonrails.org/active_record_basics.html)
* [AdonisJs Lucid](http://dev.adonisjs.com/docs/3.0/lucid)

--

For your problem, you need to return the `response`.

**Comment by Jamesoncy** [comment]
yah it can be really simplified in that way, but what im trying to learn really is to make inner joins hahahahahah so thats why im asking my way is right or it can be done in that way

**Comment by Jamesoncy** [comment]
what im trying to implement is this kind of code behavior in the model,
*addLog (transactionId, body, type) { return yield this.query( 'INSERT INTO logs(transaction_id, body, type) VALUES (?,?,?)', [transactionId, body, type] ); }

sorry ahahha im really new to node and so happen that i like your framework :)

**Comment by RomainLanz** [comment]
So you want to learn SQL, Adonis Query Builder or something else?

**Comment by Jamesoncy** [comment]
yah, i like to implement it in a model, can you give me some samples on how
to do it :)

**Comment by RomainLanz** [comment]
Sorry I didn't get it.

You should come speak into AdoniJs Gitter channel. It would be simplier. :)

https://gitter.im/adonisjs/adonis-framework

**Comment by thetutlage** [comment]
Closing as it seems to be more of a conversation than an issue. @Jamesoncy As @RomainLanz said, please feel free to join us on [gitter](https://gitter.im/adonisjs/adonis-framework).
