### ISSUE TITLE
Installing adonis-mail-provider in v3 dev?

### ISSUE THREAD

**Issue by froamer** [adonisjs/adonis-framework#178]
Hi, when I try to install adonis-mail-provider in an Adonis v3 dev app, I get this error:

UNMET PEER DEPENDENCY adonis-fold@3.0.1

Is it possible to install Mail yet or should I wait until version  3's stable release?

Thanks for any help (great framework)

**Comment by thetutlage** [comment]
Yeah, Mail provider is dependent on `fold2.x`. I am yet to add new drivers to it, like Mailgun.

I will release the new version with correct dependency on `fold` soon.

**Comment by froamer** [comment]
Many thanks!!!! Loving Adonis.

**Comment by gabe-alex** [comment]
As a note, Validator also has a peer dependency on fold 2, but it seems to work regardless...

**Comment by thetutlage** [comment]
The peer dependency has been fixed inside the new release.
