### ISSUE TITLE
Make use of .njk extension for views instead of .nunjucks

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-framework#180]
Nunjucks recently decided to stick to `.njk` extension officially, which means with time more editors and 3rd party tools with follow this convention. 

Since, AdonisJs major release is on the way, we should include this breaking change of making use of `.njk` extensions.

https://mozilla.github.io/nunjucks/templating.html

**Comment by keeross** [comment]
+1

**Comment by gabe-alex** [comment]
It would be much better if Adonis just had a config value for view extension...
