### ISSUE TITLE
How can I implement a RESTful API?

### ISSUE THREAD

**Issue by lordpixel** [adonisjs/adonis-framework#181]
Thank you for creating and sharing Adonis!

I would really like to try this framework as it seems so **beautifully crafted**, I'd like to build a _RESTful API_ but I don't know where/how to start.

I would really appreciate some guidance on this matter as I did some research and wasn't able to find any documentation on it.

Thanks.

**Comment by RomainLanz** [comment]
Hi @lordpixel 

I think this would help you http://dev.adonisjs.com/docs/3.0/controllers#toc-resourceful-routes.

**Comment by thetutlage** [comment]
Seems to be more of a discussion than the issue. Please join us on Gitter to talk about it https://gitter.im/adonisjs/adonis-framework

**Comment by lordpixel** [comment]
Thank you both, I'm eagerly expecting 3.0!

**Comment by manishmaharjan69051** [comment]
i have a api ...hhow to call in adonis js with token ...

**Comment by RomainLanz** [comment]
Hey @manishmaharjan69051! 👋 

Please, [use the forum](https://forum.adonisjs.com/) instead of writing in a closed issue.
Also note that this isn't related to Adonis, you need to know how to use your frontend framework.

**Comment by manishmaharjan69051** [comment]
But how to use external api with token in adonis.plz help me.
