### ISSUE TITLE
Stream response

### ISSUE THREAD

**Issue by froamer** [adonisjs/adonis-framework#183]
Hi, how can I stream data to the response?

I am trying to use [archiver](http://archiverjs.com/docs/) to send zip data (from code, not a file) and it expects this kind of code:

```
const archiver = require('archiver')
var archive = archiver('zip')
response.attachment('archive-name.zip')
archive.pipe(response)
archive.append(svg, {name: 'test.svg'})
archive.finalize()
```
An Adonis response doesn't seem to be geared up for this, or am I missing something?
Thanks for any help.

**Comment by thetutlage** [comment]
You can do `archive.pipe(response.response)`

**Comment by froamer** [comment]
Perfect!!! Many thanks.

**Comment by thetutlage** [comment]
Closing!

**Comment by tomvrho** [comment]
I also try to use archiver with archive.pipe(response.response), but I'am getting error: Error: Can't remove headers after they are sent

      var archive = archiver('zip')
      response.attachment('test.zip')
      archive.pipe(response.response)
      archive.append(csvFile, { name: ('osebe.csv') })
      archive.finalize()  

Any suggestion please? Thank you!

**Comment by thetutlage** [comment]
`response.attachment` streams the file and then you are piping the response again to `archive.pipe`. So basically, you are making 2 response in one request
