### ISSUE TITLE
JsonResponseHandler

### ISSUE THREAD

**Issue by belozyorcev** [adonisjs/adonis-framework#186]
how to configure `Http/Listeners/Http.js` by this example https://github.com/thetutlage/Ouch/blob/master/examples/example-jsonAndPretty.js ?

I tried
```
  if (Env.get('NODE_ENV') === 'development') {
    const ouch = new Ouch();
    ouch.pushHandler(
      (new Ouch.handlers.JsonResponseHandler(true,true))
    )
    ouch.pushHandler(
      new Ouch.handlers.PrettyPageHandler('blue', null, 'sublime')
    )
    ouch.handleException(error, request.request, response.response, (output) => {
      console.log('Handled error gracefully')
    })
    return
  }
```
but not working...

**Comment by thetutlage** [comment]
Checkout what's written here https://github.com/thetutlage/Ouch/blob/master/examples/example-jsonAndPretty.js#L35

**Comment by belozyorcev** [comment]
@thetutlage I tried request with headers: `X-Requested-With: xmlhttprequest` and `'Content-Type: application/json`

**Comment by belozyorcev** [comment]
system freeze....

**Comment by belozyorcev** [comment]
Without this headers returning ```PrettyPageHandler```

**Comment by belozyorcev** [comment]
@thetutlage I found problem and send PR to your repository

**Comment by thetutlage** [comment]
Sure will check it out, closing this issue, as related to a different repo
