### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-framework#19]
Hi all, I'd be very interested to see how we could tackle websocket support as there are many possible options.
For example, we could recommend that such functionality should be offloaded to Pusher or we could document how to use a socket.io cluster. If you're to use Websocks, once your app gets big you'll want to account for a solid scaling setup (Redis etc.). Also, see Sailsjs for example who make it very easy to utilise Websocks on the client. Happy to discuss & assist wherever I can, thanks.

**Comment by keeross** [comment]
+1

**Comment by tinkone** [comment]
+1

**Comment by dennisver** [comment]
+1

**Comment by jbruni** [comment]
What about [SocketCluster](http://socketcluster.io)?

**Comment by thetutlage** [comment]
@jbruni worth checking, i will look into it, once i will start with the Socket provider

**Comment by thetutlage** [comment]
Closing and added it to the Roadmap on trello https://trello.com/b/yzpqCgdl/adonis-for-humans

**Comment by mubbashar** [comment]
is it already added  ?

**Comment by ntvsx193** [comment]
When is the implementation planned?

**Comment by keeross** [comment]
@ntvsx193 @mubbashar it is already implemented
http://adonisjs.com/docs/3.2/websocket
