### ISSUE TITLE
Session ID could be guessable

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-framework#191]
I notice here: https://github.com/adonisjs/adonis-framework/blob/c523b591bacb578057506214afdf4e4bdcd3f4ab/src/Session/SessionManager/index.js#L278 you are using uuid.v1 which is unique but could be guessable.

Would it make more sense to use v4 which is more randomized and thus unguessable? It may have a slightly higher chance of collision, but will still never happen.

https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_.28date-time_.26_MAC_address.29

**Comment by thetutlage** [comment]
@nrempel Are there are any downsides on a guessable session id?

**Comment by nrempel** [comment]
If an attacker creates a a cookie with a guessed session id, could that give the attacker access to a user's account (the owner of the session)?

**Comment by thetutlage** [comment]
No the value of the cookie matters, which is encrypted and signed with a SALT.. so getting the value right is difficult.

When cookie's values are tampered, they return `null`

**Comment by nrempel** [comment]
That is the case with the cookie driver (where information is stored _in_ the cookie).

But in the case of the `File` driver (or a Redis driver in the future), it simply uses the sessionId to lookup the data from the stored session.

For example: https://github.com/adonisjs/adonis-framework/blob/c523b591bacb578057506214afdf4e4bdcd3f4ab/src/Session/Drivers/File/index.js#L102

Unless I'm missing something. Thanks for taking the time to look at this!

**Comment by thetutlage** [comment]
Yeah in that case the session id itself get's signed and encrypted before it is sent to the browser.

**Comment by nrempel** [comment]
Ok, I see now that the sessionId is signed just the same.

https://github.com/adonisjs/adonis-framework/blob/c523b591bacb578057506214afdf4e4bdcd3f4ab/src/Session/SessionManager/index.js#L43

Thanks again.
