### ISSUE TITLE
Inconsistency between views and code, when accessing relation data 

### ISSUE THREAD

**Issue by gabe-alex** [adonisjs/adonis-framework#195]
If you want to get data from a relation in a view, you can do:
`{{ row1.relation1.related_data }}`
But this doesn't seem to work from JS code, you need to do:
`row1.relations.relation1.related_data`
I think one of them should be made like the other, to avoid confusion.

Also, slightly off-topic, but `row1.relations.relation1` is `null` if no related rows are found.
I think it would be better if it were an empty collection (for multi-row relations), in order to avoid extra checks, and to be consistent with main queries returning no rows.

Using Adonis 3.

**Comment by thetutlage** [comment]
Now you share some code on how you are making use of the data?

**Comment by gabe-alex** [comment]
Nevermind, I found out the problem: I was using .toJSON() to add a collection to a view. (By the way, why aren't they supported directly?)

Changing it to .value() made it work as expected...

**Comment by thetutlage** [comment]
Views has nothing to do with collections. They render what you give them.

**Comment by gabe-alex** [comment]
Maybe, but for example being able to iterate a collection directly from a view, without converting it into a list, would be handy, especially when collections are used so often...
