### ISSUE TITLE
Page loads correctly only when refreshed after a redirect

### ISSUE THREAD

**Issue by raen79** [adonisjs/adonis-framework#198]
Hello,

I have used a very simple redirect (using response.route) towards a certain page and it appears totally blank. After refreshing the page, the text that is supposed to be genrated by adonis appears. I noticed that one of the variables that is supposed to be re-created in the method remains the same as the one in the previous method (before the redirect), so I assume the controller is simply loading the second view without generating any new variables. Here is the relevant code in my controller:
```
 * read (request, response) {
  	const id = request.params().id
  	const post = yield Post.where('id', id).fetch()
  	const view = yield response.view('read', {post: post.first()})
  	response.send(view)
}

* create (request, response) {
   		const newPost = request.except('_csrf')
  		yield Post.create(newPost)
  		const post = yield Post.max('id').first()
  		response.route('read', {id: post.max})
}
```

And the view for read:
```
<h1>{{ post.title }}</h1>
<br>
{{ post.body }}
```

**Comment by thetutlage** [comment]
@raen79 Can u share the version you are on and do share your routes file too.

**Comment by raen79** [comment]
I am on version 2.00, and my route file looks like this:

```
'use strict'

/*
|--------------------------------------------------------------------------
| Routes
|--------------------------------------------------------------------------
|
| Routes helps you in defining http endpoints/urls which will be used
| by outside world to interact with your application. Adonis has a
| lean and rich router to support various options out of the box.
|
*/
const Route = use('Route')

Route.get('/', 'HomeController.index').as('index')
Route.get('/post/:id', 'HomeController.read').as('read')
Route.get('/new', 'HomeController.new').as('new')

Route.post('/create', 'HomeController.create').as('create')
```

**Comment by raen79** [comment]
I found the solution to my problem by changing the way I created a new post. The new code for the create method is below:
```
* create (request, response) {
	const params = request.except('_csrf')
	const post = new Post

	post.title = params.title
	post.body = params.body

	yield post.create()
	response.route('read', {id: post.id})
}

**Comment by thetutlage** [comment]
@raen79 I would recommend to make use of version `3.0`. It has lot of improvements and is quite stable. Closing this issue for now
