### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-framework#20]
Hi, just thought I'd point out that the documentation differs a little from an actual installation.
![image](https://cloud.githubusercontent.com/assets/1525669/11334883/e41eb31a-91cf-11e5-8fc2-bdab9c453810.png)
I instead ran `node ace server:start` - might also be worth pointing out that to kill the process, users should run `node ace server:stop`.

Thanks in advance.

**Comment by RomainLanz** [comment]
It would be great if you can put the documentation on Github to make some changes.

**Comment by thetutlage** [comment]
Going to do it soon

**Comment by niallobrien** [comment]
@thetutlage A general contribution document or contribution guidelines would be great. Also, I'm certain many people would like to know how committed you are to this project before they adopt it, thanks in advance.

**Comment by thetutlage** [comment]
@niallobrien I agree, there are ton of things pending which needs to be done. Here is the list of priorities i have as of now in sequential order

1. Complete v2 development.
2. Improve documentation, including contribution guide.
3. Write articles, blog posts educating on how to get best out of adonis.

I am fully committed to the project and has plans to stay with it. As alone i have to manage everything, things are expected to get delayed.

Also i am open to any kind of contribution, which may be hard as there is contribution guidelines, but this is how all projects get started.

**Comment by niallobrien** [comment]
@thetutlage That's fantastic news, thank you for clarifying. I'd be happy to contribute towards blog posts, tutorials etc. and any code contributions where possible. Would you rather see an asset pipeline proposal before or after v2?

**Comment by thetutlage** [comment]
@niallobrien Replied on https://github.com/adonisjs/adonis-framework/issues/18

**Comment by niallobrien** [comment]
Thanks @thetutlage

**Comment by RomainLanz** [comment]
@thetutlage In which branch should we commit new functionalities?

**Comment by thetutlage** [comment]
make brances as `feature/<feature-name>` for example for sessions go with `feature/session`

**Comment by RomainLanz** [comment]
But in which branch should we propose a PR?

Also, have you the code of the V2 somewhere? That we don't add some features that is already in it.

**Comment by thetutlage** [comment]
Check trello https://trello.com/b/DKLuWLda/version-2-0, consider using development branch for `PR`

**Comment by RomainLanz** [comment]
`development` branch is 20 commits behind, can you rebase?

**Comment by thetutlage** [comment]
Did

**Comment by RomainLanz** [comment]
Thanks @thetutlage 

Would it be not better to use master for development purpose and 1.0 for the 1.0 release, etc.?

**Comment by thetutlage** [comment]
@RomainLanz So far, i have been into the development process, and being lenient with the process. Still i would like to keep master branch clean and later i am planning to implement `git-flow` which makes more sense as it is used globally

**Comment by RomainLanz** [comment]
It would be soooo great to implement `git-flow`.

You have make (and you still make) an awesome job. Keep it up!

**Comment by RomainLanz** [comment]
@thetutlage What do you think of creating a new branch (`v2.0`) to put all of your code that we can already develop application with this new version, implements features and correct bugs?

**Comment by thetutlage** [comment]
@RomainLanz This issue seems to be talking about everything, closing it for now. Let's talk about these things on https://gitter.im/adonisjs/adonis-framework
