### ISSUE TITLE
Nodemon errors while installing any npm package

### ISSUE THREAD

**Issue by lordpixel** [adonisjs/adonis-framework#202]
I keep getting **nodemon** related errors when installing any additional package, I checked the contents of the generated _npm-debug.log_  and found this:

`2718 verbose stack TypeError: Cannot read property 'nodemon' of undefined`

It looks like npm expects to find nodemon in dependencies (not devDependencies but regular dependencies) so I installed nodemon using

`npm install nodemon --save`

Problem solved, but I feel like this is not a good solution as nodemon should be only required as a dev dependency.

I will keep troubleshooting this, if I find a good solution I will file a PR.

**Comment by RomainLanz** [comment]
This is not a problem in Adonis.

I have installed a new project with Adonis right now and I have no problem of running `npm run dev`.

* How have you installed Adonis?
* How do you launch `nodemon`?

**Comment by thetutlage** [comment]
mpm has weird issues with npmshrink.json file, delete and re-create this file

**Comment by lordpixel** [comment]
You guys are right, it must be an issue with NPM, nothing related to Adonis, will keep on testing this wonderful framework.

Thank you!

**Comment by CWolfs** [comment]
I'm getting this problem too on a fresh install.
