### ISSUE TITLE
How do you configure Nunjucks not to conflict with Angular

### ISSUE THREAD

**Issue by rkrishnamoorthy** [adonisjs/adonis-framework#203]
Hi,
I would like to understand where one configures Nunjucks tokens - especially for {{ variable }} patterns. This conflicts with Angular

appreciate the help

thanks
RK

**Comment by thetutlage** [comment]
http://adonisjs.com/docs/3.0/templating#raw. Closing, please feel free to open if you have any specific questions.

**Comment by rkrishnamoorthy** [comment]
thank you but in the interest of knowledge, I would love to know how to configure nunjucks behaviour for my needs. 

is there some thing i can do to configure nunjucks env as in the nunjucks documentation.
