### ISSUE TITLE
All input fields prefilled even when pass null to form builder

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-framework#205]
Using the form builder, all form fields are pre-filled from flash data if it exists - even if you pass null.

For example:

`{{ form.password('password', null, { class: 'auth-form-input', placeholder: 'password' }) }}`

generates:

`<input type="password" name="password" value="123123123" class="auth-form-input" placeholder="password" id="password">`

But, 

`{{ form.password('password', 'notpassword', { class: 'auth-form-input', placeholder: 'password' }) }}`

Generates:

`<input type="password" name="password" value="notpassword" class="auth-form-input" placeholder="password" id="password">`

In the controller: 

```javascript
      yield request
        .withAll()
        .andWith({errors: ['Invalid username or password']})
        .flash()
```

I fix this by not sending back the password in flash.

**Comment by thetutlage** [comment]
You can make use of `avoidOld` So it will be.

```
{{ form.password('password', null, { class: 'auth-form-input', placeholder: 'password', avoidOld:true }) }}
```

**Comment by thetutlage** [comment]
Closing, please feel free to open in case of any issues.

**Comment by nrempel** [comment]
Ok, that works. Thanks.

I do think that in this case it might be easier for a developer to do the wrong thing than the right thing by accident. This is a design decision that is up to you, but I do think that the design philosophy of "make it easy to do the right thing" is good.

👍
