### ISSUE TITLE
Policy based authorization

### ISSUE THREAD

**Issue by erkan1991** [adonisjs/adonis-framework#209]
I'm going to be starting on a project in 3 weeks, hopeing to use adonisjs. I was wondering if it is achievable to have policy based authorization on routes, controllers etc similar to Laravel. 
https://laravel.com/docs/5.2/authorization

From looking at the docs I haven't seen anything to do with authorization. Im also new to node, so maybe if you could please point me to the right direction so I can try to implement it :) 

Btw I love the  framework!!

**Comment by thetutlage** [comment]
@erkan1991 No there is no official support for ACL. Ofcourse you can manage access control of your own by writing re-usable services, and may be share with everyone in the community.

Also I am going to close this issue, as I have no plans on working on this right now.

**Comment by obstschale** [comment]
@erkan1991 Did you find a solution to your problem? Have you created a module you can share because I also need a  feature to handle ACL.

**Comment by RomainLanz** [comment]
Hey @erkan1991, @obstschale.

I have created a framework-agnostic package to manage ACL in Node.js.

I let you give it a try!

* https://github.com/RomainLanz/node-fence

**Comment by obstschale** [comment]
Thx @RomainLanz. I will give it a try within the next weeks.
