### ISSUE TITLE
can i use adoinsjs now？

### ISSUE THREAD

**Issue by colinshen** [adonisjs/adonis-framework#21]
First.this is a awesome framework. I really like it. After looking the documentation, I think this framework like Larael in some ways. Because it's a brand new framewor, I am not sure I can use it in production now! Can I?

**Comment by thetutlage** [comment]
I depends upon your requirements, shipped features are well tested and documented and are intended to be used for production. 

But still there are missing features like `Websockets, mail, redis` etc, which will be coming out in version 2

**Comment by colinshen** [comment]
cool,thanks. Hope won't wait for long time
