### ISSUE TITLE
Bulk Loading Master data with seeds and lucid

### ISSUE THREAD

**Issue by rkrishnamoorthy** [adonisjs/adonis-framework#211]
Hi
how do we bulk load master data (eg a list of states into the states table) using seeds. I only see documentation about dummy data and factories

thanks
Rk

**Comment by thetutlage** [comment]
Do you mean u already have list of states?

**Comment by rkrishnamoorthy** [comment]
Yes  in a json array

**Comment by thetutlage** [comment]
You can skip factories in that case, and make use of model directly inside your Seed class.

```
const State = use('App/Model/State')
class StateSeeder {

  * run () {
    yield State.createMany(statesArray)
  }

```

**Comment by rkrishnamoorthy** [comment]
thanks a ton

**Comment by Utwo** [comment]
Do you know how you can run seeds in a specific order? For example, I have Seed1.js, Seed2.js and Seed3.js. How can i run these seeds in this order: Seed2.hs, Seed3.js and Seed1.js?

**Comment by thetutlage** [comment]
Simply prepend a number in front of the file names.

```
01-Seed2.js
02-Seed3.js
03-Seed1.js
```

**Comment by jessicamrbr** [comment]
Each seed runs asynchronously, even though the execution of the files is in order by name.
