### ISSUE TITLE
How to Integrate With MongoDB?

### ISSUE THREAD

**Issue by devcaststudio** [adonisjs/adonis-framework#213]
How to use adonis with **MongoDB**?

**Comment by thetutlage** [comment]
@devcaststudio The same way you will do it with any other Node.js framework.

Closing, please re-open or create a new issue, if there is any specific issue.

**Comment by allanfreitas** [comment]
@devcaststudio 

Hi, 
I've just published a npm package that integrates
**Mongorito**(mongodb package that use ES6 generators) with **AdonisJS** :)

I hope it helps someone.

https://www.npmjs.com/package/adonis-mongorito
https://github.com/allanfreitas/adonis-mongorito
