### ISSUE TITLE
node --harmony_proxies: No such file or directory

### ISSUE THREAD

**Issue by LeventeNagy** [adonisjs/adonis-framework#214]
Hi, I am experiencing the following issue, when I run ace command

`./ace make:controller Post`

I get the following message 

`/usr/bin/env: node --harmony_proxies: No such file or directory`

I was searching a lot to fix this issue but nothing really worked

PS: I am running elementray os 64bit Built on Ubuntu 14.04

**Comment by thetutlage** [comment]
Would u mind running `adonis ace fix` in the root of your project and then make use of `ace` again?

**Comment by LeventeNagy** [comment]
Okay

Ran in the terminal: `adonis ace fix`

Returned

> Commands
------------
adonis new
adonis fix

Than ran `adonis fix`

Returned

> Fixing ace file

Than ran `./ace make:controller Post`

Returned
`/usr/bin/env: node --harmony_proxies: No such file or directory`

Than ran `ace make:controller Post`

Returned
`sudo apt-get install libace-perl`

**Comment by thetutlage** [comment]
What is the output of `which node`

**Comment by LeventeNagy** [comment]
Output: `/usr/bin/node`

**Comment by thetutlage** [comment]
So it has been already reported as there is some issue the way Linux picks the node path. 

Ideally you will have to replace first line of the `ace` file with `#!/usr/bin/node --harmony_proxies`. Also checkout this issue https://github.com/adonisjs/adonis-framework/issues/141

**Comment by LeventeNagy** [comment]
Oh so sorry for not digging in deeper, the linked issue solved the problem, thank you very much
