### ISSUE TITLE
please recommendation of some packages

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#218]
@thetutlage can you recommend which one will work best with adonis-framework:

1) Frontend: reactjs vs vuejs? 
2) Can we use passport for authentication as it supports Social Authentication?

**Comment by connor11528** [comment]
React vs Vue is personal preference and not an issue with this repo.

Please check out adonis-auth for authentication: https://github.com/adonisjs/adonis-auth. If you have issues building authentication with that system please redirect issues to that repo

Thank you!

**Comment by thetutlage** [comment]
It has less to do with AdonisJs. I would suggest to discuss ideas and recommendations on the [Gitter channel](https://gitter.im/adonisjs/adonis-framework)
