### ISSUE TITLE
Configuration on webstorm

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#219]
![webstorm](https://cloud.githubusercontent.com/assets/3604392/17078452/0e3507b6-5111-11e6-9dbd-5c594566ee22.png)
Please check attachment and can you suggest files to select, in case of sails sails.js needs to be selected from node_modules folder

**Comment by thetutlage** [comment]
@webreinvent I don't use webstorm, so you will have to tell me the purpose of that Javascript file.

**Comment by RomainLanz** [comment]
Hi @webreinvent!

If I correctly understand the [documentation about Webstorm](https://www.jetbrains.com/help/webstorm/2016.2/running-and-debugging-node-js.html) you should select the `server.js`. You can find this file at the root of your project.

Let us know if it's working! 😃

**Comment by webreinvent** [comment]
@RomainLanz of course I tried couple settings, including selecting server.js and "npm start node --harmony_proxies" in application parameter. When I run the application it start fine but when I visit localhost:3333 is show 500 error check attachment. 
![error](https://cloud.githubusercontent.com/assets/3604392/17114064/f9d04ff4-52ca-11e6-9517-bec472ae5e7f.png)

**Comment by franzsilva** [comment]
Hi @webreinvent, what version of node are you using?, I can help you setup adonis with webstorm.

**Comment by webreinvent** [comment]
@franzsilva thanks, node is v4.4.4 and npm is 3.10.5

**Comment by RomainLanz** [comment]
Thanks @franzsilva. Maybe you could send a PR to the documentation. :smiley:

**Comment by franzsilva** [comment]
This is the configuration i have and it works fine

![image](https://cloud.githubusercontent.com/assets/5158380/17119282/f4faefee-5292-11e6-8af9-3a009c7a411a.png)

I will submit the configuration for the the docs.

**Comment by thetutlage** [comment]
`npm start node --harmony_proxies` is the wrong command.. It needs to be `node --harmony_proxies server.js` or `npm start`

@webreinvent Rest you can check the proposed settings of @franzsilva

**Comment by webreinvent** [comment]
Thanks @franzsilva and @thetutlage , it worked!

**Comment by ncacace** [comment]
Does this mean anything to anyone?
- Thanks if you can help

<img width="1061" alt="screen shot 2017-06-05 at 02 54 56" src="https://cloud.githubusercontent.com/assets/1590147/26766935/b9c9178e-499a-11e7-8603-37255f702fcc.png">

<img width="875" alt="screen shot 2017-06-05 at 02 55 22" src="https://cloud.githubusercontent.com/assets/1590147/26766938/beb38978-499a-11e7-9f8e-36d218cab5d5.png">

**Comment by ncacace** [comment]
I removed the --harmony_proxies parameter as it's apparently no longer required for versions of Node above 6.5
but I still get the same error:

<img width="1048" alt="screen shot 2017-06-05 at 03 16 41" src="https://cloud.githubusercontent.com/assets/1590147/26767164/8b17d5c6-499d-11e7-8d7d-f6938a73cf93.png">

<img width="829" alt="screen shot 2017-06-05 at 03 17 02" src="https://cloud.githubusercontent.com/assets/1590147/26767168/8f12c2da-499d-11e7-84bf-122e1367b167.png">
