### ISSUE TITLE
documentation: how to access route state in view template?

### ISSUE THREAD

**Issue by connor11528** [adonisjs/adonis-framework#220]
Is there a way to make a PR or issue for the documentation?

I am following the [Getting Started guide](http://adonisjs.com/docs/3.0/adonis-blog-part1) and in **master.njk** we create a navbar like so:

```
<nav>
        <ul class="nav nav-pills pull-xs-right">
          <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
          <li class="nav-item"><a href="/contact" class="nav-link">Contact</a></li>
        </ul>
        <h3 class="text-muted"> Adonis Blog </h3>
      </nav>
```

Now for above navbar I would like to highlight where the user is by adding `class="active"` when the user is on a particular page.  So if we're on the "Home" page the home li gets the "active" class, when on About page, "About" get the active class?

How do I access the url state with Adonis and Nunjucks like this? Thank you so much!

**Comment by thetutlage** [comment]
@connor11528 If you are using `Route.on('/about').render('someview')` then it passes the current request object to the view and you can access the request `url`.

```twig
          <li class="nav-item"><a href="/" class="nav-link {{ 'active 'if request.url() == '/' }}">Home</a></li>
          <li class="nav-item"><a href="/about" class="nav-link {{ 'active 'if request.url() == '/about' }}">About</a></li>
          <li class="nav-item"><a href="/contact" class="nav-link {{ 'active 'if request.url() == '/contact' }}">Contact</a></li>
```

If you are creating views via controller, then you will have to pass the `request.url()` to your views manually.

**Comment by connor11528** [comment]
oh cool! I like that `request` object. Thank you much

**Comment by MiRush94** [comment]
how do you pass the request.url() to the view?

**Comment by RomainLanz** [comment]
Dear @MiRush94 !

You should create a [globalMiddleware](http://adonisjs.com/docs/3.1/middleware#_global_middleware) which will register a [view global](http://adonisjs.com/docs/3.1/views#_working_with_globals) with the url.

Here's an example of mine:

```javascript
'use strict'

class CurrentUrl {

  * handle(request, response, next) {
    const View = use('View')

    View.global('currentUrl', request.url())

    yield next
  }

}

module.exports = CurrentUrl
```

**Comment by connor11528** [comment]
Thank you @RomainLanz

**Comment by MiRush94** [comment]
Ohh wow great thank you :)

2016. okt. 24. de. 9:46 ezt írta ("Connor Leech" <notifications@github.com

**Comment by zgabievi** [comment]
Found nice solution for this one:

1. Create global middleware. Ex: `TemplateHelpers`

```js
'use strict'

class TemplateHelpers {

  * handle (request, response, next) {
    const View = use('View')

    View.global('activeRoute', function(url) {
      url = '/' + url.replace('*', '(.*)')

      return request.match(url) ? 'is-active' : ''
    })

    yield next
  }

}

module.exports = TemplateHelpers
```

2. in your `app/Http/kernel.js`:

```js
const globalMiddleware = [
  ...
  'App/Http/Middleware/TemplateHelpers'
]
```

3. use this new helper in your template:

```njk
<li class="{{ activeRoute('users*') }}">{{ linkTo('users.index', 'Users') }}</li>
```

**Comment by MiRush94** [comment]
This is good one, thanks!! :)

**Comment by samuelcesc** [comment]
Thank you @RomainLanz and @zgabievi . Thinking of publishing a post to help other devs. Cheers!

**Comment by RomainLanz** [comment]
Hey @samuelcesc !

Note that the API has been changed about that :)

**Comment by samuelcesc** [comment]
@RomainLanz Any updates to the API I should take note of? Creating a middleware so that the currently loggedIn user can be identified in all views allowed on the auth middleware

**Comment by domzgarcia** [comment]
This works but changes of request.url  was late. For example, you have navigation a,b,c  and you print {{currentUrl}} on your view,  when you click "a" nothing printed out then when you click "b" that's the time navigation "a" printed its path to the view. How to fix this?

**Comment by jaypozo** [comment]
Yeah, weird I get the same problem as @domzgarcia. It seems like the previously clicked url is passed through when using middleware that uses request.url().

**Comment by jaypozo** [comment]
The answer to my recent problem can be fixed as mentioned here:
https://github.com/adonisjs/adonis-framework/issues/580

**Comment by thetutlage** [comment]
You are using version 3.2 with config file for new version? If it’s a new project I suggest using the dev release. Docs here http://dev.adonisjs.com
