### ISSUE TITLE
Problem revoking all api tokens

### ISSUE THREAD

**Issue by franzsilva** [adonisjs/adonis-framework#223]
Hi all, im having problems trying to revoke all api tokens on adonis. im using the method exactly like in the documentation but im getting the following error. 

**user.apiTokens(...).query is not a function**

Anything i might be doing wrong?

Thanks

**Comment by thetutlage** [comment]
Can u share the `User Model`

**Comment by franzsilva** [comment]
```javascript

'use strict'

const Lucid = use('Lucid')

class User extends Lucid {

  apiTokens () {
    return this.hasMany('App/Model/Token')
  }

}

module.exports = User
```

**Comment by thetutlage** [comment]
@franzsilva This looks good.

Can u share some more code on how you are revoking the tokens + what is the output of the `user` instance when you `console.log` it.

**Comment by franzsilva** [comment]
Hi @thetutlage, later today ill send you the snippet of code. Its on my home computer. 

I have an extra question, are there any plans for i18n for adonis?, i think its the only thing missing, and redis session replication. 

Thank you

**Comment by thetutlage** [comment]
@franzsilva Closing! Please feel free to open this issue if the problem persists 😄

**Comment by cachilders** [comment]
Was this issue resolved? I'm running into it as well, and though I see an update to the dev branch of adonis-auth that seems to address it, it hasn't been merged to master.

**Comment by tranlamnhatnam** [comment]
Same here, will there release for fix this issues soon?

**Comment by thetutlage** [comment]
Fixed in this commit https://github.com/adonisjs/adonis-auth/commit/c012936799bea9206f1b8fedb04d8f24e39b59fd

You can install the `develop` branch, until I release it to npm
