### ISSUE TITLE
Adonis not Receiving Ajax Post Parameters

### ISSUE THREAD

**Issue by raen79** [adonisjs/adonis-framework#224]
Hello,

I have been making ajax post requests with parameters from javascript to adonis successfully, (meaning that adonis receives the post parameters correctly) using jQuery. However a similar request being made using a JS software called Stimulsoft Report.JS is being sent, but it's post parameters are totally ignored by Adonis. I have attached pictures of the console logs (console.log(request.all())) and the requests that were made to adonis.

Unsuccessful request:
![image](https://cloud.githubusercontent.com/assets/5307107/17095385/7444df42-5254-11e6-830b-044b4d67dc4d.png)
![image](https://cloud.githubusercontent.com/assets/5307107/17095448/c2b54da6-5254-11e6-9942-4cd18d756333.png)

Successful request (using jquery ajax):
![image](https://cloud.githubusercontent.com/assets/5307107/17095510/08e60806-5255-11e6-893e-63c55561a279.png)
![image](https://cloud.githubusercontent.com/assets/5307107/17095539/3ad307b0-5255-11e6-8a18-18a78842296f.png)

Do you know what the issue might be?

**Comment by RomainLanz** [comment]
Hi @raen79!

As you can see it's not the same request. You are sending **form data** with jQuery, which is how it's working, instead, you are sending a **payload** with your software `Stimulsoft Report.JS`. It should be handled differently.

**Comment by raen79** [comment]
Hi!

I assumed it was because stimulsoft was sending a payload, but adonis doesn't seem to have a specific way to handle it (at least I can't find it in the documentation).

**Comment by thetutlage** [comment]
Ideally `Request Payload` is used by browser when you send `raw` data. I can see the `Content-type` of the request is set to `text/plain` which needs to be `application/json` to make Adonis parse the JSON body as a object.

**Comment by raen79** [comment]
And is there no way of receiving a request made with text/plain in adonis and converting it to json?

**Comment by thetutlage** [comment]
@raen79 Why would you do that?

**Comment by raen79** [comment]
When I wrote this I thought I wouldn't be able to change Stimulsoft's ajax request's content-type but I was able to so I solved the issue.

Thank you very much!

**Comment by thetutlage** [comment]
Closing the issue
