### ISSUE TITLE
Possibility of HMVC structure

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#225]
Guys,

I am working on an ACL (access control list) application with a module/extension manager. You can compare this with Wordpress or Joomla where we have some default functionalities when you install the application like ACL, user management, theme management etc but you can extend those functionalities by installing other module, extensions or plugins.

I need help in achieving following folder structure:
![hmvc](https://cloud.githubusercontent.com/assets/3604392/17152383/23a5d0fe-5395-11e6-862e-083f373ae08d.png)

**Comment by thetutlage** [comment]
@webreinvent This is not a issue related to AdonisJs. You are free to modify the application structure as per your needs but you will have dig deeper into the code and understand how and why pieces are joined together.
