### ISSUE TITLE
Prerender.js not work 

### ISSUE THREAD

**Issue by ayontulip** [adonisjs/adonis-framework#226]
I'm using adonisjs 3.0 with angular js so i need  Prerender.js for seo. I try to use Prerender.js that's not work. please tell me how to  use prerender-node with adonisjs 30.

https://www.npmjs.com/package/prerender-node

**Comment by thetutlage** [comment]
The package you are using is written for Express. You will have to directly make use of the Prerender.io service and hook up a middleware to AdonisJs.

There is no official support for prerender, but if you feel comfortable you are most welcome to create and share the middleware with rest of the community.
