### ISSUE TITLE
Middleware parameters

### ISSUE THREAD

**Issue by arma-gast** [adonisjs/adonis-framework#230]
Noticed that there is a way to pass parameters to middleware: `...middlewares(['middleware:param1:param2']` that is not documented. I don't link undocumented features but this is the only way I found to pass middleware params. 

Am I wrong? Is there other way?

**Comment by thetutlage** [comment]
Yes my bad, that I never documented it. The syntax is slightly different `middleware:param1,param2`. 

Check authentication docs for reference http://adonisjs.com/docs/3.0/authentication#multiple-authenticators

**Comment by arma-gast** [comment]
Ouch! My mistake.

What do you think about another form of defining middleware in the list? Something like

```
...middlewares([
  'auth',
  { middleware : 'ACL', rules : [
    { matcher : '$everyone', rule : ACL.DENY },
    { matcher : '$isAdministrator', rule : ACL.ALLOW }
  ]}
])
```

ACL will receive whole configuration item as third argument and deal with it.

**Comment by arma-gast** [comment]
Another example:

```
...middlewares([
  'auth',
  { middleware : 'ACL', rules : [
    { matcher : '$everyone', rule : ACL.DENY },
    { matcher : '$postOwner', rule : ACL.ALLOW },
    { matcher : '$hasRole', role : 'Editor', rule : ACL.ALLOW },
    { matcher : '$hasRole', role : 'Administrator', rule : ACL.ALLOW }
  ]}
])
```

I understand, that creating static middlewares is better for performance reasons, but parameters will help keep code DRY.

**Comment by thetutlage** [comment]
Nope, this is too verbose. It is better to pass a config key to the middleware as a parameter and read your ACL rules from the config file.

### example config file - config/acl.js

```javascript
admin: {
 { matcher : '$everyone', rule : ACL.DENY },
 { matcher : '$postOwner', rule : ACL.ALLOW },
 { matcher : '$hasRole', role : 'Editor', rule : ACL.ALLOW },
 { matcher : '$hasRole', role : 'Administrator', rule : ACL.ALLOW }
}
```

and on middleware you can say.

```
.middleware('acl:admin')
```

and within the ACL middleware you can grab the configuration for the `admin` key.

### middleware

```javascript
* handle (request, response, next, rule) {
   const ruleConfig = Config.get(`acl.${rule}`)
}
```

**Comment by arma-gast** [comment]
Oh! Thanks for an idea!

**Comment by thetutlage** [comment]
Closing! Please feel free to open new issues if required

**Comment by onewiseburdman** [comment]
Can you please help out a little bit more and go into detail?  I decided to write some apps for our bank using your platform.  I would like to have a better understanding of the acl config portion:  according to you you create a file call config/acl.js then you somehow get the user roles out of the config.  I tried his and it seems to fail immediately.  Perhaps I am not understanding what you are doing or how its getting done.  Please help as I am under a deadline.  Thanks...

**Comment by corysimmons** [comment]
@thetutlage I agree. I'd like to see some docs on the Adonis way to handle permissions and/or roles.
