### ISSUE TITLE
how to run migrations from a controller

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#232]
Guys,

Can you please tell me how to run the migration and seeds in a controller method? I am building a setup wizard just like wordpress installation.

**Comment by thetutlage** [comment]
@webreinvent There is no direct or single way of doing this. If you want more control over the response, then try using the `Migrations` class directly. You will have to dig into the code of `adonis-lucid` for that.

Quickly you can also use `Ace` directly to issue commands. 

```javascript
const Ace = use('adonis-ace')

Route.get('/', function * (request, response) {
  const startTime = new Date().getTime()
  response.response.write('running migrations \n')
  try {
    yield Ace.call('migration:run', {}, {help: true})
  } catch (errors) {
    console.log(errors)
  }
  const endTime = new Date().getTime()
  response.response.write('database migrated \n')
  response.response.write(`time taken ${endTime - startTime}ms \n`)
  response.end()
})
```

and make use to register `aceProviders` and register `aceCommands` inside `bootstrap/http.js` file. You can take the reference from `bootstrap/kernel.js` file, on how to concatenate providers and register ace commands

**Comment by webreinvent** [comment]
it generate following error:
==================================
{ [CommandNotFound: migration:reset is not registered with ace]
  name: 'CommandNotFound',
  message: 'migration:reset is not registered with ace',
  status: 500 }

**Comment by webreinvent** [comment]
For those who might need it:

In file bootstrap/http.js
Step 1) Add const Ace = require('adonis-ace') after const fold = require('adonis-fold')
Step 2) Replace .register(app.providers) with .register(app.providers.concat(app.aceProviders))
Step 3) Add Ace.register(app.commands) after const Server = use('Adonis/Src/Server')

Then the following code will work:
const Ace = use('adonis-ace')

Route.get('/', function * (request, response) {
  const startTime = new Date().getTime()
  response.response.write('running migrations \n')
  try {
    yield Ace.call('migration:run', {}, {help: true})
  } catch (errors) {
    console.log(errors)
  }
  const endTime = new Date().getTime()
  response.response.write('database migrated \n')
  response.response.write(`time taken ${endTime - startTime}ms \n`)
  response.end()
})
