### ISSUE TITLE
how to check database connection in middleware

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#233]
Is there any method available in Database class or in Lucid to check the connectivity of the database? 

Like

```javascript
const Database = use('Database')
if(Database.connection('mysql').isConnected()) {
}
```

**Comment by thetutlage** [comment]
If there will be any error in connecting the database, Database provider will throw an error. So if there are no errors, means it is connected.

**Comment by webreinvent** [comment]
already tried try catch 
 try {
    Database.connection('mysql');
console.log("connected")
  } catch (errors) {
    console.log(errors)
  }

but no error with wrong database credentials.

**Comment by thetutlage** [comment]
You have to execute a query `yield Database.connection('mysql').table('...')`

**Comment by webreinvent** [comment]
Still, it's getting connected while I am using wrong database credentials
http://i.imgur.com/lqNVyuy.png

![connected](https://cloud.githubusercontent.com/assets/3604392/17401528/c8bef2fa-5a6b-11e6-8a74-fda044e8900f.png)

**Comment by thetutlage** [comment]
What's the value of `DB_DATABASE` in `.env` file.

**Comment by webreinvent** [comment]
my bad

**Comment by webreinvent** [comment]
@thetutlage what if there is no database table but still I want to know database connection status.

**Comment by RomainLanz** [comment]
Dear @webreinvent !

If you call `getConnectionPools` on `Database` you'll get back a list of connection pools.

--

* [Code Source](https://github.com/adonisjs/adonis-lucid/blob/develop/src/Database/index.js#L170)

**Comment by thetutlage** [comment]
@webreinvent The problem lies within the way knex throws errors. If you will look into issues https://github.com/tgriesser/knex/issues/1542 and https://github.com/tgriesser/knex/issues/522 there is no easy way to handle connection level errors.

Knex uses a logger library to log errors, which makes it almost impossible to catch errors until you read the output of `stdout` and process errors manually.

By looking into the knex source code, I found the following way to get access to the connection pool error, I am not sure how frequently this error event will be fired, so to be on the safer side, bind via `once` instead of `on`.

```javascript
  Database.client.pool.once('error', function (error) {
    console.log(error.message)
  })
```

**Comment by thetutlage** [comment]
Closing the issue as not directly related to adonis

**Comment by webreinvent** [comment]
@thetutlage it's okay but I believe we should either extend or build such functionality in the adonis framework. It's very useful and laravel does have such functionality.

```
if(DB::connection()->getDatabaseName())
   {
     echo "conncted sucessfully to database ".DB::connection()->getDatabaseName();
   }
```

**Comment by Geowan** [comment]
I was able to solve this by the following

       const mysql = require('mysql')
        const Config = use('Config')
        try {
  
          const con = mysql.createConnection(Config.get('database.mysql.connection'))
          con.connect((err) => {
            if (err) {
             console.log('Error connecting to Db', err)
              return //handle connection failed here 
              }
           })
          con.end()

        } catch (errors) {
            console.log('connection failed', errors) //here handle more connection failure
          }

Using Database in checking always failed. This is for mysql but can be adapted for the others like pgsql and sqlite as well.
