### ISSUE TITLE
check if table exist in database (hasTable function)

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#234]
Function like knex.schema.hasTable('my_users'), still exist? how to verify if table exist in database.
try catch of Database.connection("mysql").table("tableName"); does not generate excepted result.

**Comment by RomainLanz** [comment]
Dear @webreinvent !

Does `Database.connection('mysql').hasTable('tableName')` work?

--

* [Knex.js hasTable()](http://knexjs.org/#Schema-hasTable)

**Comment by thetutlage** [comment]
Closing since the answer my @RomainLanz is supposed to work fine. Feel free to open issues for specific questions.
