### ISSUE TITLE
ES6 modules support?

### ISSUE THREAD

**Issue by shnhrrsn** [adonisjs/adonis-framework#235]
Are there any plans to support ES6 modules?

Being able to do the following would be far more concise:

```js
export class SomeController {
  // etc
}
```

**Comment by RomainLanz** [comment]
AdonisJs is build without any transpiling system. We use directly functionalities provided by Node.js.

Here's a list of Node.js compatibility with ES2015 specs: http://node.green

**Comment by thetutlage** [comment]
@shnhrrsn Closing, please feel free to open new issues if applicable.

**Comment by shirshak786** [comment]
It is now experimental with stability 1. I think we can support it using webpack module bundling  and it will make code consistent :)
