### ISSUE TITLE
Error: Unexpected strict mode reserved word - service provider

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#237]
I have created a service provider and the following class:
```javascript
'use strict';

const Role = use('App/Model/Core/Role');

class CoreUser {
  createNewAdmin() {
    const role = new Role();
    role.name = "test";
    var newRole = yield role.save();
    console.log(newRole);
    return newRole;
  }
}
module.exports = CoreUser;
```
Called this method in a Controller which generate "Unexpected strict mode reserved word" error. Can you guide me?

**Comment by thetutlage** [comment]
`createNewAdmin` should be generator method `* createNewAdmin()`

**Comment by webreinvent** [comment]
@thetutlage I have tried to make it a generator as well, but then I don't get any response at all. Even tried just  ```console.log("this should be logged")``` and get nothing in console.

**Comment by thetutlage** [comment]
Can u share the complete code? How you define it and how you call it?

**Comment by webreinvent** [comment]
Sure, here's the code of service provider:

```javascript
'use strict';
const Role = use('App/Model/Core/Role');
class CoreUser {
  *createNewAdmin() {
    const role = new Role();
    role.name = "test 2";
    console.log("service provider");
    var result = yield role.save();
    return result;
  }
}
module.exports = CoreUser;
```
Code in controller (I have  include all necessary paths):
```javascript
*createAdminFirst(request, response) {
    var admin = Core.CoreUser.createNewAdmin();
    console.log("first response", admin.next());
    console.log("second response", admin.next());
    return response.json(admin);
  }
```
Console response is following:
```
service provider
first response { value: {}, done: false }
second response { value: undefined, done: true }
```

**Comment by RomainLanz** [comment]
How do you import `Core.CoreUser`?

You should first instantiate the class then used it.
Also, you should use `yield` because you are calling a generator.

**Comment by webreinvent** [comment]
thanks

**Comment by RomainLanz** [comment]
Is it working? 😄

**Comment by webreinvent** [comment]
@RomainLanz  yeah, I forgot to use yield in ```var admin =  Core.CoreUser.createNewAdmin();``` line that was the only problem. Thanks, I am really liking the framework and the community support.
