### ISSUE TITLE
How to run migrations using Docker?

### ISSUE THREAD

**Issue by jetoneza** [adonisjs/adonis-framework#238]
Found an error when docker runs `./ace migration:run`.

```
Step 10 : RUN ./ace migration:run --force
 ---> Running in 1955bc7328f4
/usr/bin/env: node --harmony_proxies: No such file or directory
The command '/bin/sh -c ./ace migration:run --force' returned a non-zero code: 127
```

Do you have a solution for this? Thanks!

**Comment by thetutlage** [comment]
This is a issue with Ubuntu/Linux distributions that they don't recognize node on `/usr/bin/env: node` location.

You can run ace commands are `node -harmony_proxies ace <command>`

**Comment by jetoneza** [comment]
Thanks, it worked! I have another problem using docker. The app isn't loading when I run docker. I set the port in my .env to 3000.

This is my Dockerfile:

```
# Define the image
FROM node:6.3

ENV NODE_ENV development
ENV APP_PATH /usr/src/app

# Replace this with the RDS url.
ENV DB_URL postgres://postgres:password@localhost:5432/load

# Create the app directory
RUN mkdir -p $APP_PATH

# Bundle app source
COPY . $APP_PATH
COPY .env $APP_PATH
WORKDIR $APP_PATH

# Install
RUN npm install

# MIGRATE
RUN node --harmony_proxies ace migration:run --force

# Run it in port 3000
EXPOSE 3000

# Start it
CMD [ "npm", "start" ]
```

I run docker using the command `docker run -p 3000:3000 -d load .`


Docker logs says that the app is running but when I access `localhost:3000`, all i see is a page saying `The localhost page isnt't working`, `localhost didn't send any data.`, `ERR_EMPTY_RESPONSE`.

Docker logs:

```
jeetkunedo » docker logs 95451148183c
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
npm info lifecycle adonis-app@3.0.0~prestart: adonis-app@3.0.0
npm info lifecycle adonis-app@3.0.0~start: adonis-app@3.0.0

> adonis-app@3.0.0 start /usr/src/app
> node --harmony_proxies server.js

info adonis:framework [Mon Aug 08 2016 10:41:45 GMT+0000 (UTC)] serving app on localhost:3000
```

Thanks for answering!

**Comment by thetutlage** [comment]
Seems to be issue with docker not binding to the localhost properly. I am not a docker guy, so can't comment much on the same. But you can try running a basic Html page on localhost:3000 to see if that works.

**Comment by jetoneza** [comment]
Thanks for helping!

It was just a misconfiguration of the server to listen to localhost only. I used `127.0.0.1` instead of `localhost` in `.env` for the host.

**Comment by victoralvesf** [comment]
> Thanks for helping!
> 
> It was just a misconfiguration of the server to listen to localhost only. I used `0.0.0.0` instead of `localhost` in `.env` for the host.

Thanks, i was having the same issue.
