### ISSUE TITLE
How to add support for ssl?

### ISSUE THREAD

**Issue by jetoneza** [adonisjs/adonis-framework#240]
I have set SSL to true.

```
pg: {
    client: 'pg',
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      user: Env.get('DB_USER', 'root'),
      password: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis'),
      ssl: true
    }
  }
```

But an error occured.

```
Knex:Error Pool2 - Error: The server does not support SSL connections
```

Hope anyone can help. Thanks!

**Comment by thetutlage** [comment]
@jetoneza It says `The server does not support SSL connections` which means the postgres server does not support SSL.

**Comment by jetoneza** [comment]
Ah okay thanks! I thought it was the node server.

**Comment by thetutlage** [comment]
@jetoneza Closing. Feel free to create new issues if required
