### ISSUE TITLE
Last inserted ID or record

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#241]
In Laravel when saving any record via elaquent, it also return save data. How to achieve this in adonis?

**Comment by iamdual** [comment]
Is there any solution? Thanks.

**Comment by webreinvent** [comment]
It's actually pretty simple:
```
role = new Role();
role.name = "New Role";
yield role.save();
console.log(role);
return role;
```
Variable ```role``` after ```yield role.save()``` will contain the last inserted id and other associated properties.

**Comment by eldinphp** [comment]
> It's actually pretty simple:
> 
> ```js
> * createRole () {
>   role = new Role();
>   role.name = "New Role";
>   yield role.save();
>   console.log(role);
>   return role;
> }
> ```
> 
> Variable `role` after `yield role.save()` will contain the last inserted id and other associated properties.

I am getting an error saying yield keyword reserved..
