### ISSUE TITLE
Custom table  name for pivot table

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#243]
I have following models (just for example, it's not the complete code):
```javascript
'use strict'
const Lucid = use('Lucid');
const Role = use('App/Model/Role');
class User extends Lucid {
  static get table() {
    return "core_users";
  }
  roles() {
    return this.belongsToMany('App/Model/Role')
  }
static attachRole(){
var user = User.find(1);
yield user.roles().attach([1]);
return user;
}

}
```
And
I have following models:
```javascript
'use strict'
const Lucid = use('Lucid');
const User= use('App/Model/User');
class User extends Lucid {
  static get table() {
    return "core_roles";
  }
}
```
My pivot table name is `core_user_core_role`. When I call `attachRole()` function in controller it display following error:
```insert into `role_user` (`role_id`, `user_id`) values ('undefined', 2) - ER_NO_SUCH_TABLE: Table 'acl.role_user' doesn't exist```

**Comment by RomainLanz** [comment]
Dear @webreinvent !

You can change the pivot table name by sending a second argument to your definition.

```js
roles () {
  return this.belongsToMany('App/Model/Role', 'pivotTableName')
}
```

* [Documentation](http://adonisjs.com/docs/3.0/relationships#belongstomany-relationship)
* [Code](https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/Model/index.js#L820)

**Comment by webreinvent** [comment]
@RomainLanz thanks. It worked!
