### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by Immortalin** [adonisjs/adonis-framework#245]
How should you set up live code reloading?

**Comment by RomainLanz** [comment]
Hi @Immortalin !

What do you mean? You can run `npm run dev` which use [nodemon](http://nodemon.io) to reload the server whenever you made a modification.

If you though about frontend reload you should use something like [Browersync](https://www.browsersync.io) but this isn't in the scope of Adonis.

**Comment by Immortalin** [comment]
@romainsync it would be great if client side reload can be integrated into Adonis. Frameworks such as phoenix already do this

**Comment by RomainLanz** [comment]
What do you mean by client side reload? Forcing the client (browser) to reload when you modify your code?

**Comment by thetutlage** [comment]
Closing as not directly related to AdonisJs. Frontend code reloading is outside the scope.
