### ISSUE TITLE
Installation Error - ubuntu 

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#247]
I have followed all the instruction as per docs and verified node & npm version. Still when i run `npm run dev` I am getting following error.
![error](https://cloud.githubusercontent.com/assets/3604392/17697175/d4eb33b8-63d0-11e6-8e20-2b07cb887f62.png)

**Comment by thetutlage** [comment]
Can u clear the node_modules and re-install

```
rm -rf node_modules && npm i
```

**Comment by webreinvent** [comment]
now getting following error:
```
> adonis-app@3.0.0 dev /root/adonisSpeedo
> nodemon --watch app --watch bootstrap --watch config --watch .env -x "node --harmony_proxies" server.js

sh: 1: nodemon: not found
```

**Comment by RomainLanz** [comment]
Which version of Node.js and npm are you using?

**Comment by webreinvent** [comment]
Node:  v4.4.5 & NPM: v3.10.6

**Comment by thetutlage** [comment]
@webreinvent It has to do with the way your dependencies are installed. Make sure all dev{dependencies} are installed correctly inside node_modules.

**Comment by webreinvent** [comment]
I have followed the method written in the docs. I have separately installed nodemon too but then it displays the error I mentioned in first post

**Comment by thetutlage** [comment]
And do you have `adonis-fold` folder inside the `node_modules` folder?

**Comment by webreinvent** [comment]
Fresh install result following:
```
root@node-india:~# adonis new adonisSpeedo
Cloning into 'adonisSpeedo'...
cleaning project
setting up app key
Fixing ace file
installing dependencies may take a while
installing dependencies... /Killed
undefined
```
Create following file & folders:
```
root@node-india:~/adonisSpeedo# ls
ace        CHANGELOG.md  npm-shrinkwrap.json  public     server.js
app        config        package.json         README.md  storage
bootstrap  database      providers            resources
```
I am surprised there is no node_module folder in this installation but can you guess the cause because node & npm version is proper.

**Comment by thetutlage** [comment]
I can see the install task has been killed `installing dependencies... /Killed \n undefined`

**Comment by webreinvent** [comment]
I tried ```npm install``` in the folder which produces following result:
```
root@node-india:~/adonisSpeedo# npm install
Killed.............] \ cloneCurrentTree: verb correctMkdir /root/.npm correctMk
```

**Comment by thetutlage** [comment]
Seems to be some issue with `npm` you have to debug it further or submit an issue with Npm

**Comment by RomainLanz** [comment]
That's definitively an issue with `npm`.

Is this on your server?

**Comment by webreinvent** [comment]
@RomainLanz  yeah it's on digital ocean server. I don't mind to share credential if you're interested in taking a look.

**Comment by RomainLanz** [comment]
Did you got the cheapest one? When I was using Digital Ocean I cannot run any `npm` command cause of the available RAM.

**Comment by webreinvent** [comment]
it has the following configuration: 512 MB Memory / 20 GB Disk / BLR1 - Ubuntu Node 4.4.5 on 14.04 and I am using Sails on the same server. I don't know if Adonis consume more resources compared to Sails

**Comment by RomainLanz** [comment]
Yeah, 512Mb of memory is not sufficient to run `npm install` command (nor `gulp`, etc.)

**Comment by RomainLanz** [comment]
You should use a swap file if you want to keep this server.

**Comment by webreinvent** [comment]
@RomainLanz Swap file worked. It was a insufficient RAM issue. Below is reference like to setup Swap File: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
