### ISSUE TITLE
Form open enctype duplicate

### ISSUE THREAD

**Issue by uno-de-piera** [adonisjs/adonis-framework#248]
Hi guys,

I try to upload files with form helper without lucky.

I open tag with the next code:

`{{ form.open({action: 'UserController.upload', enctype: 'multipart/form-data'}) }}`

And I have the next response in html code:

`<form method="POST" action="/upload" enctype="application/x-www-form-urlencoded" enctype="multipart/form-data">`

I can see that enctype tag it's duplicated.

I opened the Form class and I can see the next code into open method.

`formAttributes.push(`enctype="${enctype}"`)`

I understand that this is the problem, the code it's pushing a new enctype without check if exists.

Great job with this framework.
Best regards.
Israel Parra.

**Comment by thetutlage** [comment]
Use `{{ form.open({action: 'UserController.upload', files: true) }}`

**Comment by uno-de-piera** [comment]
Great, ¡¡thanks!!
