### ISSUE TITLE
How to change 'localhost:3333' to actual domain name or IP

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#249]
I was not able to find it anywhere in documentation

**Comment by RomainLanz** [comment]
You should use a process manager like [pm2](http://pm2.keymetrics.io/).

This is not related to AdoniJs, this is more deployment of Node.js application specific. Please, use Gitter for these type of question.

**Comment by webreinvent** [comment]
sure

**Comment by samarhaider** [comment]
set following .env file

`HOST=0.0.0.0`
