### ISSUE TITLE
EnvProvider should only run dotenv.load() in NODE_ENV=development

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-framework#252]
In a production environment, there is no file named `.env` so `dotenv.load()` fails with an error:

```
Error: ENOENT: no such file or directory, open '.env' 
```

**Comment by thetutlage** [comment]
How will you get Environment variables with the `.env` file?

**Comment by RomainLanz** [comment]
Hi @nrempel !

You should set `ENV_SILENT` to `true`.

```bash
$ ENV_SILENT npm run dev
```


I will document it.

--

* [Source Code](https://github.com/adonisjs/adonis-framework/blob/develop/src/Env/index.js#L27)
* [Documentation](https://github.com/motdotla/dotenv#silent)

**Comment by nrempel** [comment]
Thank you!
