### ISSUE TITLE
Request.originalUrl() not returning hash

### ISSUE THREAD

**Issue by andreechristian** [adonisjs/adonis-framework#253]
Is there any way to get current request hash in adonis?

**Comment by thetutlage** [comment]
@andreechristian What is the `hash` and can u share the  complete url too

**Comment by andreechristian** [comment]
@thetutlage i tried with localhost:3333/vendorPage?page=2#projects and when i tried Request.originalUrl() it returns localhost:3333/vendorPage?page=2. I need the hash to figure out next url (for SEO purpose)

**Comment by thetutlage** [comment]
@andreechristian Server never receives the `#` fragments. Here is a wikipedia article on same.
https://en.wikipedia.org/wiki/Fragment_identifier

> Clients are not supposed to send URI-fragments to servers when they retrieve a document, and without help from a local application (see below) fragments do not participate in HTTP redirections

**Comment by andreechristian** [comment]
@thetutlage yeah :( thanks for the article. Btw, for me (noob's perspective), Adonis documentations which says

"url : Returns request current URL. It will trim query string and hashes of the URL."

while

"originalUrl() returns the untouched version of current URL."

get me sooo wrong. I assume that the docs is talking about different "hashes", right?

**Comment by thetutlage** [comment]
Nope there is nothing wrong with the docs.

> `originalUrl()` returns the untouched version of current URL.

It does return the untouched version, but the clients are not supposed to send the `#` fragments. Even a raw Node.js server will not have the `#` fragments. So for adonis the untouched version is what comes to the server, not what is on the browser.

**Comment by RomainLanz** [comment]
Yes, but it's wrong to say that `request.url()` trim hashes because the server never receive hashes.

**Comment by thetutlage** [comment]
Yes, that needs to be fixed! Closing the issue, feel free to create new issues if required
