### ISSUE TITLE
Adonis Redis Implementation

### ISSUE THREAD

**Issue by Nigeltiany** [adonisjs/adonis-framework#255]
```error
Error (500) select * from "users" - SQLITE_ERROR: no such table: users
```
When trying to set key values to Redis.
First error was because it needed sqlite3 dependencies. Why does redis need sqlite3?
After installing sqlite3 with npm, it throws a query error (???). 
Followed the simple example available in the [documentation](http://www.adonisjs.com/docs/3.0/redis)

**Comment by thetutlage** [comment]
Code?

**Comment by Nigeltiany** [comment]
@thetutlage just following the docs on a completely new project.
Basic Controller
```javascript
'use strict'

const Redis = use('Redis')
const User = use('App/Model/User')

class UserController {
  * index (request, response) {
    //const cachedUsers = yield Redis.get('users')
    // if (cachedUsers) {
    //   response.json(JSON.parse(cachedUsers))
    //   return
    // }

    const users = yield User.all()
    yield Redis.set('users', 'hello world')
    response.json(users)
  }
}

module.exports = UserController
```

**Comment by thetutlage** [comment]
There is a query made by User model, which is supposed to hit the active SQL table

**Comment by Nigeltiany** [comment]
Ahh yes. I need to focus.
```javascript
yield Redis.set('users', 'hello world2')
    response.send('done');
```
