### ISSUE TITLE
Configure HoundCI

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-framework#26]
HoundCI don't very like ES6 for the moment.

Is it possible to configure it or remove it?

--

**Examples**

 - https://github.com/adonisjs/adonis-framework/pull/25
 - https://github.com/adonisjs/adonis-framework/pull/22

**Comment by thetutlage** [comment]
True, i will working on `git-flow` and code quality management tool soon, will keep it mind

**Comment by thetutlage** [comment]
Also , they have added basic es6 support as of this tweet 
https://twitter.com/dancarlito/status/568252008307818496

**Comment by RomainLanz** [comment]
> Also , they have added basic es6 support as of this tweet 

We should add a `.jshint` file to the repository to use ES6 with HoundCI.

**Comment by thetutlage** [comment]
Yes, i will find the best config to make HoundCI work by keeping coding style consistent.

**Comment by thetutlage** [comment]
Removed hound completely and using http://standardjs.com/ , it will not detect errors on automatically but so far the nicest tool.

**Comment by RomainLanz** [comment]
:+1:
