### ISSUE TITLE
./ace and nvm: No such file or directory

### ISSUE THREAD

**Issue by indr** [adonisjs/adonis-framework#262]
I use node v6.3.1 and the node version manager nvm on Fedora 24. When I run `./ace` I get:
```bash
$ ./ace
/usr/bin/env: ‘node --harmony_proxies’: No such file or directory
```

I only quickly tried to find the cause and/or a solution. Some hints can be found in creationix/nvm#828 (and creationix/nvm#786 but this went on root privileges).

My workaround is this:

 * Remove the shebang (first line) in the `ace` file
 * Invoke with `node ace`, i.e. `node ace make:controller Foos`

Does the job for me. Maybe this should be mentioned in the docs.

---

Btw. AdonisJs is amazing. Thank you!

I just started and read the guides. I tried to fix some typos and inconsistencies in the docs while reading it but couldn't figure out which branch in the [adonisjs/docs](https://github.com/adonisjs/docs) repo I should update.

**Comment by indr** [comment]
Ah stupid me, searched in the wrong repo for an already reported issue. Voilà #141.

**Comment by thetutlage** [comment]
Closing as duplicate
