### ISSUE TITLE
angular 2

### ISSUE THREAD

**Issue by amrayoub** [adonisjs/adonis-framework#265]
Does it work with angular 2 , and if so .
can you provide any tutorial on that ?

Thanks

**Comment by RomainLanz** [comment]
Hi @amrayoub !

It works on any frontend framework you wanna use (Angular, Angular 2, Ember, React, VueJS, Aurelia, Elm, ...).

If you want to have your application and your endpoint on the same domain you need to configure Nginx to serve every requests to your `index.html` and whitelist `/api/` (or whatever url you have for your endpoint) to go to your Adonis application.

It's better in my opinion to separate by a domain your api and your application (`api.example.com`, `example.com`). If you do that you will only need to configure Nginx to redirect every request going to `example.com` to your `index.html` file.

**Comment by allanfreitas** [comment]
@amrayoub This question is like you to ask if CakePHP/Zend/Symfony/Laravel/Silex works with angular2. Right @RomainLanz ?

**Comment by RomainLanz** [comment]
Yes.

Frontend stuff do not depend on the backend technologies/frameworks.
