### ISSUE TITLE
request.session.forget('build_id') not clearing the session id on production server

### ISSUE THREAD

**Issue by michaeljcalkins** [adonisjs/adonis-framework#266]
`yield request.session.forget('build_id')`  
Is not working on my production server but appears to be working locally.
Am I missing an environment variable or something?

```javascript
'use strict'

const Database = use('Database')
const BuildModel = use('App/Model/Build')

class ApiBuildController {

    * store(request, response) {
        // Create a new build and set that build's id as a cookie
        yield request.session.forget('build_id') // THIS IS WHERE THE ISSUE IS
        response.ok()
    }

    * showCurrentBuild(request, response) {
        let buildId = yield request.session.get('build_id')

        console.log(buildId) // has same value as before

        if (buildId === null) {
            // Create a new build and set that build's id as a cookie
            let buildResult = yield Database
                .insert({ user_id: 0 })
                .into('builds')

            buildId = buildResult[0]
            yield request.session.put('build_id', buildId)
        }

        const build = yield BuildModel
            .findBy('id', buildId)

        const products = yield build
            .products()
            .fetch()

        response.json({
            build: build,
            products: products
        })
    }

}

module.exports = ApiBuildController
```

![cursor_and_airsoft_kit_builder_-_eaglefreak](https://cloud.githubusercontent.com/assets/8272012/18189353/f9478234-706e-11e6-9fd6-ed824ebe2650.png)

**Comment by michaeljcalkins** [comment]
<img width="837" alt="cursor_and_eaglefreak_ _settings___heroku" src="https://cloud.githubusercontent.com/assets/8272012/18189369/233ba430-706f-11e6-974a-509250c33191.png">

**Comment by thetutlage** [comment]
Seems to be weird, since no changes have been published related to sessions lately.

Also are you having issues, when running the code under tests? Or is it manual?

**Comment by thetutlage** [comment]
Also it is `NODE_ENV` not `APP_ENV`.

**Comment by michaeljcalkins** [comment]
All manual at the moment.

**Comment by michaeljcalkins** [comment]
Ok get this I changed `SESSION_DRIVER` to `file` and it's working now. :shrugs:

**Comment by thetutlage** [comment]
Yeah but it should work with `cookie` driver too. I will setup a sample project to reproduce the issue

**Comment by michaeljcalkins** [comment]
Sorry I don't have anymore details but if I get any clues I'll post.

**Comment by scrombie** [comment]
I faced a similar issue a while back as well. Sessions were working accurately on local and I could forget stuff easily. But it didn't work so well on production. I was receiving requests from a proxy server so I assumed that was the issue. I had to switch to file storage, reduce session storage time, and clear both session and cookies when I needed to, before i could get it to work properly.

**Comment by thetutlage** [comment]
@scrombie Just checked it on production by running it behind `nginx`. `cookie` driver works great for me. 

Also make sure `http.trustProxy` is set to `true` inside `config/app.js` file.  I will document it too.

**Comment by scrombie** [comment]
`trust proxy` is set to true. Yesterday the hack i did earlier, for some reason just stopped working. Well, it works, but only on certain browsers. Works on Safari, firefox and Opera, but doesn't seem to work on Chrome. I'm currently using `file` storage for my sessions. I'm going to try switching back to `cookies` to see if it'll work well again, but any idea why this could happen?

**Comment by scrombie** [comment]
A little bit of clarification. All the browsers mentioned in my previous comment were mobile browsers. It seems to work on desktop browsers as well, but doesn't work on chrome for Android and the phone's native browser. I don't know if its an android webkit issue, but right now i'm just confused. `cookies` didn't solve the issue as well though.

**Comment by thetutlage** [comment]
@scrombie thanks for the insights lemme play with an android phone

**Comment by michaeljcalkins** [comment]
@thetutlage 

```javascript
'use strict'

const Database = use('Database')
const BuildModel = use('App/Model/Build')

class ApiBuildController {

    * store(request, response) {
        // Create a new build and set that build's id as a cookie
        response.cookie('build_id', 0)
        response.ok()
    }

    * show(request, response) {
        // Show one build
        const buildId = request.param('id')

        const build = yield BuildModel
            .findBy('id', buildId)

        if (! build) return response.status(404).send()

        const products = yield build
            .products()
            .fetch()

        response.json({
            build: build,
            products: products
        })
    }

    * showCurrentBuild(request, response) {
        let buildId = request.cookie('build_id', null)
        console.log(buildId)

        if (buildId === null) {
            // Create a new build and set that build's id as a cookie
            let buildResult = yield Database
                .insert({ user_id: 0 })
                .into('builds')

            buildId = buildResult[0]
            response.cookie('build_id', buildId)
        }

        const build = yield BuildModel
            .findBy('id', buildId)

        const products = yield build
            .products()
            .fetch()

        response.json({
            build: build,
            products: products
        })
    }

    * addProduct(request, response) {
        // Create new build if none found as a cookie
        let buildId = request.cookie('build_id')
        const productId = request.input('product_id')

        if (buildId === null) {
            // Create a new build and set that build's id as a cookie
            let buildResult = yield Database
                .insert({ user_id: 0 })
                .into('builds')

            buildId = buildResult[0]
            yield response.cookie('build_id', buildId)
        }

        const result = yield Database
            .insert({
                build_id: buildId,
                product_id: productId
            })
            .into('build_product')

        response.json({
            success: true
        })
    }

}

module.exports = ApiBuildController
```

**Comment by michaeljcalkins** [comment]
Not related to Adonis this is an XHR issue I'm having with `axios`.
