### ISSUE TITLE
How to execute Seeds to perform two insertions for one User

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#267]
Our database is divided into `users` and `users_properties`, where the second table is used for hashed password and salt storage.

My `factory.js` contains this code for storing a new user and his properties.

```
Factory.blueprint('App/Model/User', () => {
  return {
    name: 'John Doe',
    username: 'johndoe',
    email: 'johndoe@gmail.com',
    firstName: 'John',
    lastName: 'Doe',
  }
})

Factory.blueprint('App/Model/UserProperties', () => {
  return {
    userId: 1,
    key: 'passwordHash',
    value: Hash.make('mypassword' + salt, 10)
  }
})

Factory.blueprint('App/Model/UserProperties', () => {
  return {
    userId: 1,
    key: 'passwordSalt',
    value: salt
  }
})
```

The seeder files just then `create()`. The issue is that only the last `UserProperties` factory is executed, and if I use `.each()`, the second is executed twice, and adds a different foreign key. Is there a way to execute each Factory for `UserProperties`?

**Comment by thetutlage** [comment]
@mfgabriel92 You should never create multiple factories for a single Model. Think of factories as a reusable blueprint.

How what you are trying to do is, create properties for a single user and here is what you should do.

```javascript
const user = yield Factory.model('App/Model/User').create()
const userProperties = Factory.model('App/Model/UserProperties').make()

userProperties.userId = user.id
yield userProperties.save()
```

Notice the difference between `make` and `create`. Also if you want to save multiple properties for a single user, you have to do it inside a asynchronous loop.

### Multiple Properties
```javascript
const cf = use('co-functional') // npm module

const user = yield Factory.model('App/Model/User').create()
const userProperties = Factory.model('App/Model/UserProperties').make(5)

yield cf.forEach(function * (properties) {
  properties.userId = user.id
  yield properties.save()
}, userProperties)

```

**Comment by mfgabriel92** [comment]
Hi @thetutlage, it worked, although I had to make some changes to adapt. :)

**Comment by thetutlage** [comment]
Great @mfgabriel92. Closing the issue 😄
