### ISSUE TITLE
How to auto load all or selective models

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#268]
I want to auto load certain models so that I can use them in any of my controller without manually defining it within the controller?

**Comment by RomainLanz** [comment]
Dear @webreinvent,

Could we have more information about your use case?

You should be able to achieve this using [Global Middleware](http://adonisjs.com/docs/3.0/middleware#global-middleware).

**Comment by webreinvent** [comment]
@RomainLanz consider that I need a Setting model and methods in almost every controller and other models and I don't want to load every time in all controller and models.

**Comment by allanfreitas** [comment]
Why cannot load it on a Base Controller? (I've search the docs and not found, but I will try create a BaseController Later.

**Comment by allanfreitas** [comment]
@webreinvent , I've created a BaseController to try out and it worked as you wanted to.
I hope it helps you or someone else :)

Changes I've made for my example:
```javascript
//created a base controller on App/Http/Controllers/BaseController
'use strict'

const Post = use('App/Model/Post')

class BaseController{

	constructor(){
	 	this.post = Post
	}
}

module.exports = BaseController
```
```javascript
'use strict'
//my Alias"ed" BaseController
const Controller = use('BaseController')

class PostController extends Controller{

  constructor(){
    super()
  }
  ...other CRUD functions...

  * show (request, response) {
    //before
    //const post = yield Post.find(request.param('id'))
   //after
    const post = yield this.post.find(request.param('id'))
    yield response.sendView('showPost', { post: post.toJSON() })
  }
}
module.exports = PostController
```

```javascript
//register my BaseController on the Aliases object to easily import on my controllers
const aliases = {
  Command: 'Adonis/Src/Command',
  ...
  BaseController: 'App/Http/Controllers/BaseController'
}
```

@RomainLanz @thetutlage

**Comment by thetutlage** [comment]
Closing the issue since not directly related to AdonisJs. Feel free to discuss on Gitter
