### ISSUE TITLE
Adonis fail to start server

### ISSUE THREAD

**Issue by tanimkg** [adonisjs/adonis-framework#270]
The `npm start` command gives following output:

> adonis-app@3.0.0 start /home/touhid/Node/adonis-test
> node --harmony_proxies server.js
node: bad option: --harmony_proxies
npm ERR! Linux 4.7.2-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the adonis-app@3.0.0 start script 'node --harmony_proxies server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_proxies server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/touhid/Node/adonis-test/npm-debug.log

Tried by installing adonis-cli (as per official documentation) and by coning git repo. Also issued `npm update --save` command to update dependencies (if any), but the problem still occurs.

**Comment by allanfreitas** [comment]
@tanimkg,
It's a bug with the 6.5.0 version of Nodejs, I couldn't find it right now to attach the link here.
I had this trouble too, I've downgraded to 4 lts and just worked :)

**Comment by thetutlage** [comment]
Remove `--harmony_proxies` from the start script.

**Comment by xoxefdp** [comment]
> adonis-app@3.0.0 start /home/neoj/Escritorio/testing/adonisjs/helloWorld
> node --harmony_proxies server.js

node: bad option: --harmony_proxies

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/home/neoj/.npm-global/bin/npm" "run" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the adonis-app@3.0.0 start script 'node --harmony_proxies server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_proxies server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/neoj/Escritorio/testing/adonisjs/helloWorld/npm-debug.log

Same proble here!

**Comment by thetutlage** [comment]
@xoxefdp The solution has been posted above. It is more of a issue with Node.js itself, follow the thread here https://github.com/nodejs/node/issues/8388#issuecomment-244978559

**Comment by thetutlage** [comment]
Closing since, the fix has been posted in Node.js and it will be released soon.

**Comment by FrancisVarga** [comment]
I have the same problem the another thing would be when will be the next node version released? Wanted to check it out.

**Comment by thetutlage** [comment]
@FrancisVarga All you really need to do is, remove the `--harmony_proxies` flag from the dev script.

**Comment by blogui91** [comment]
@thetutlage yes, it works but, how should i use ace if it presents the same issue?

**Comment by blogui91** [comment]
Well, i could **fix the problem,**
Considering that i I have 
```npm 3.10.3```
```node 6.5.0```

Just replace ```--harmony_proxies``` to ```--harmony ``` in scripts (located in ```package.json```)

To use ace generetors you need to enter into ```ace``` file located in root project,  then change the first line  to ``` #!/usr/bin/env node --harmony ```


That's it :) 
Reference: ``` https://nodejs.org/es/docs/es6/ ```

**Comment by rtablada** [comment]
@thetutlage I would recommend looking at making a version cut soon and replacing `harmony__proxies` with `--harmony`.

With 6.1 and on, `--harmony__proxies` does nothing as proxies were no longer `experimental` in the version of v8, and in 7.x the flag is completely removed and causes an error.

In terms of semantic versioning, if the switch to `--harmony` still works on 4.x LTS (that would be great since 4.x is still in the active LTS stage), then I would recommend a minor version bump since it still affects documentation and available commands, but with a drop in replacement without removing functionality.
If simply changing to `harmony` does not work on 4.x then I would consider this a major version change since the installation requirements and support stack have changed.

**Comment by amitsharma8891** [comment]
I am usng node 7 and npm 3.1, but whenever I try to run **"./ace make:controller Home"**  command it throws node: bad option: --harmony_proxies error.@thetutlage can you tell me some workaround as I am new to node and I really loved this framework architecture

**Comment by thetutlage** [comment]
@amitsharma8891 Simply remove `--harmony_proxies` from the `ace` file.
