### ISSUE TITLE
[Proposal] Expose additional global helpers for use in views: url() and assets()

### ISSUE THREAD

**Issue by nicklaw5** [adonisjs/adonis-framework#271]
It would be great if, [like Laravel](https://laravel.com/docs/5.3/helpers#urls), Adonis could expose two additional URL helpers inside views: `url()` and `assets()`.

As it stands, I have two middleware for providing these features in my application, but believe others can benefit from having these available out-of-the-box.

The below `ViewUrl.js` class
##### app/Http/MIddleware/ViewUrl.js
```javascript
'use strict'

const View = use('View')

class ViewUrl {

  * handle (request, response, next) {

    let baseUrl = request.secure()? 'https://' : 'http://'
    baseUrl += request.headers().host + '/'

    View.global('url', (path) => {
      if(typeof path != 'undefined') {
        path = (path.substring(0, 1) == '/')
          ? path.substring(1)
          : path
        return baseUrl + path
      }
      return baseUrl
    })

    yield next
  }

}

module.exports = ViewUrl
```
provides the ability to do the below in a view:
```html
<a href="{{ url('sign-in') }}">Sign In</a>
```
which renders:
```html
<a href="http://my-domain.com/sign-in">Sign In</a>
```

And the below `ViewAssets.js` class:
##### app/Http/MIddleware/ViewUrl.js
```javascript
'use strict'

const View = use('View')

class ViewAssets {

  * handle (request, response, next) {

    let baseUrl = request.secure()? 'https://' : 'http://'
    baseUrl += request.headers().host + '/assets/'

    View.global('assets', (assetPath) => {
      assetPath = (assetPath.substring(0, 1) == '/')
        ? assetPath.substring(1)
        : assetPath
      return baseUrl + assetPath
    })

    yield next
  }

}

module.exports = ViewAssets
```
provides the ability to do the below in a view:
```html
<link rel="stylesheet" type="text/css" href="{{ assets('css/styles.css') }}" />
```
which renders:
```html
<link rel="stylesheet" type="text/css" href="http://my-domain.com/assets/css/styles.css" />
```

**Comment by thetutlage** [comment]
Why do you want to use `absolute` URL's?

**Comment by nicklaw5** [comment]
To be honest I'm not sure :smile: I guess I'm just used to the syntax from working with my Laravel projects.

Happy to close this if you feel it is unnecessary.

**Comment by thetutlage** [comment]
@nicklaw5 Yes, I don't see any reason of adding absolute URL's.

**Comment by thetutlage** [comment]
Closing the issue, feel free to report any future issues

**Comment by nicklaw5** [comment]
@thetutlage I have just come across a situation where this proposal is somewhat relevant.

When generating URL's for use in emails. As it stands I need to hard code my URL in my email templates like so:

```html
<a href="https://my-domain.com/verify?token={{ verification_token }}">Click here to verify your account</a>
```
What do you think?

**Comment by navdeepsingh** [comment]
Question then : how we can add assets/js/* in template?

**Comment by wxs77577** [comment]
@thetutlage  I use `linkTo()` in mail template but it cannot generate a absolute url with hostname

**Comment by moraleslevi** [comment]
I am having a similar issue. I am using [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/) which requires absolute URLs to load external assets (images, css, js). I'm using APP_URL from env, but I would prefer it if this was available as a helper function so I don't have to specify baseUrl per environment.

**Comment by moraleslevi** [comment]
I solved for this in v4 using the following View global defined in hooks.js [**hooks.after.providersBooted**] (adapted from the solution @nicklaw5 posted above) which might be helpful for others:
`
  View.global('absoluteUrl', function (path) {
    const req = this.resolve('request')
    let baseUrl = req.secure() ? 'https://' : 'http://'
    baseUrl += req.headers().host + '/'
    if (typeof path !== 'undefined') {
      path = (path.substring(0, 1) === '/')
        ? path.substring(1)
        : path
      return baseUrl + path
    }
    return baseUrl
  })
`

**Comment by nickstock** [comment]
> I solved for this in v4 using the following View global defined in hooks.js [**hooks.after.providersBooted**] (adapted from the solution @nicklaw5 posted above) which might be helpful for others:
> 
> ```
> View.global('absoluteUrl', function (path) {
>   const req = this.resolve('request')
>   let baseUrl = req.secure() ? 'https://' : 'http://'
>   baseUrl += req.headers().host + '/'
>   if (typeof path !== 'undefined') {
>     path = (path.substring(0, 1) === '/')
>       ? path.substring(1)
>       : path
>     return baseUrl + path
>   }
>   return baseUrl
> })
> ```

This worked nicely for me, coming from Laravel I am used to sending out emails with activation and token verified links in so this feature was needed. The above code worked fine in normal views but to make it work for emails I had to pass the request object into the email view.
