### ISSUE TITLE
What about tests in the framework?

### ISSUE THREAD

**Issue by NetanelBasal** [adonisjs/adonis-framework#273]
I just discover this framework and its look Awesome, but what about testing?

**Comment by RomainLanz** [comment]
Hi @NetanelBasal !

@thetutlage [is currently working on this](https://trello.com/c/x8J0bqxN/19-out-of-the-box-testing).

If you don't want to wait for it, you can use [Zombie.js](http://zombie.js.org/) to do acceptance/integration testing and [Mocha](https://mochajs.org/) (or whatever you want) for unit testing.

[Here's an example application](https://github.com/adonisjs/adonis-rally) which is tested that you can take a look.

You may also want to take a look at this issue: [Best practice for writing tests](https://github.com/adonisjs/adonis-framework/issues/173)

**Comment by NetanelBasal** [comment]
Cool, Thanks!
