### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ScytaleTleilax** [adonisjs/adonis-framework#274]
Hi , 
I'm following [this](https://scotch.io/tutorials/meet-adonisjs-a-laravel-style-mvc-framework-for-node-js) walkthrough in order to get acquainted with AdonisJS but the build fails:

    installing dependencies... /npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program  Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v6.5.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE

    npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1`

Any guidance would really help me out.

[npm-debug.log.txt](https://github.com/adonisjs/adonis-framework/files/474590/npm-debug.log.txt)

**Comment by thetutlage** [comment]
@ScytaleTleilax Simply do `npm install --no-optional` inside the root of the project.

**Comment by ScytaleTleilax** [comment]
Oh, of course , silly me. Thanks !

**Comment by ScytaleTleilax** [comment]
Terribly sorry to reopen 

**ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz node-pre-gyp 
ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp)**

[verbose](https://gist.github.com/ScytaleTleilax/8b4b23154221ea8684e6c6682bea1120)

**Comment by thetutlage** [comment]
What is the command you are running to install modules

**Comment by ScytaleTleilax** [comment]
`E:\PROJES\hello-adonis>npm install --no-optional`

**Comment by thetutlage** [comment]
Trying it on my windows machine. Ideally `npm` should not try to install optionalDependencies

**Comment by ScytaleTleilax** [comment]
As reported 16 days ago the `--no-optional` flag [npm issue #8921](https://github.com/npm/npm/issues/8921) still has issues.

I tried with 
npm@3.1.0
npm@3.2.0
npm@3.5.0

Closing and booting my CentOS box since this is a npm issue

**Comment by ScytaleTleilax** [comment]
As reported 16 days ago the `--no-optional` flag [npm issue #8921](https://github.com/npm/npm/issues/8921) still has issues.

I tried with 
```
    npm@3.1.0
    npm@3.2.0
    npm@3.5.0
```

Closing and booting my CentOS box since this is a npm issue
