### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by obstschale** [adonisjs/adonis-framework#276]
A quick report. In your README you link to http://adonisjs.com/docs/2.0/contributing but this site does not exists. Maybe you want to fix that :)

PS: the same link appears in [CONTRIBUTING.md](https://github.com/adonisjs/adonis-framework/blob/develop/CONTRIBUTING.md) as well

**Comment by allanfreitas** [comment]
Hi @obstschale I've submitted a PR with the correct links.

**Comment by thetutlage** [comment]
Fixed in related PR
