### ISSUE TITLE
Adonis don't supported Linux operating system(Resolved)

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#285]
after upgrading nodejs and npm version from ```PPA``` i get this error:

```
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
installing dependencies... |
npm ERR! Please include the following file with any support request:
npm ERR!     /home/mahdi/Desktop/Home/www/adonisjs/awesome-project/npm-debug.log
undefined
```

as far as i know this means this framework doesn't supported linux yet. because after switching into directory and running ``` sudo npm i --no-optional ``` command couldn't resolve this problem and ```fsevents``` is required for this framework, Its very bad and unfortunately i cant use that on ```linux``` servers

**Comment by tux-world** [comment]
after ask this problem on StackOverFlow [@l0rin](http://stackoverflow.com/users/4202031/l0rin) said to me to downgrade npm version by this command 
```
sudo npm install -g npm@3.8.9
```

now i can run created project successful

**Comment by thetutlage** [comment]
@tux-world Before coming to the conclusion that the framework does not supports Linux, I would suggest you to dig into the error logs and understand the logged exceptions.

There are handful of projects running AdonisJs in production including the documentation website http://adonisjs.com which in hosted on Ubuntu itself.
