### ISSUE TITLE
Simple Quastion about relation

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#286]
in Laravel php framework we can make simple some relation between tables without any make relation on migration or between tables on ```phpMyadmin``` we can simply make relation by refer column names, such as 

```
class Tickets extends Model
{
    protected $table = 'tickets';

    public function user()
    {
        return $this->belongsTo('App\User','userId','id');
    }

}
```

is support this feature?

**Comment by RomainLanz** [comment]
Hey @tux-world !

Yes, it is! It's even documented.

adonisjs.com/docs/3.0/relationships

Please, search in the documentation before opening an issue.

**Comment by tux-world** [comment]
@RomainLanz its because of i'm was very excited, Thanks
