### ISSUE TITLE
Support Multi Language

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#287]
Hi. i cant find any document about this feature, how can i set some language and switch between them?

**Comment by allanfreitas** [comment]
I can't find any reference to Multi-language builtin support.

If you check the trello backlog, there's no mention to possibility develop it.
https://trello.com/b/yzpqCgdl/adonis-for-humans

I think if you realy need it, you can check the Website repo: https://github.com/adonisjs/adonis-documentation

You can use take the code used for the versions stuff,
like `/X.X/about-us`
and use like `/{en|es|br}/about-us`

**(_tip_: You can use a Middleware to work which version to use or load a default)**

I cannot checked if it works, but I think you can use the Config class to get your lang files, or implement with database using Lucid + Redis(to cache).

**Comment by thetutlage** [comment]
Working on same, will be published soon.

**Comment by tux-world** [comment]
Thanks. This framework very very useful. I switched from laravel. Thanks. I'm translating document to persian language. After finish i send it for you

**Comment by obstschale** [comment]
Great. A multi language feature would be very useful.

**Comment by thetutlage** [comment]
Please make use of https://npmjs.org/package/adonis-antl. Docs will be published with 3.1

**Comment by tux-world** [comment]
@thetutlage its not for multi language, for example change strings to other language such as English,India or Persion, your refer link is only for supporting multi language to format nomber or etc, Thanks :)

**Comment by thetutlage** [comment]
@tux-world What do you mean by "its not for multi language"?

**Comment by tux-world** [comment]
@thetutlage I'm so sorry sir, in this repository you wrote : 

> It ships Views Helpers to format dates, numbers, string messages and currency.

how can i use for example ```trans('your_welcome')``` to support  any language which user choose that?

**Comment by thetutlage** [comment]
Wait for the documentation to get released. For check docs here https://github.com/adonisjs/docs/blob/3.1/common-web-tools/13-internationalization.adoc

**Comment by tux-world** [comment]
@thetutlage I'm so sorry sir, after read again i can get your mean
