### ISSUE TITLE
Characters in the token id generated is not equal to the varchar character limit in token table

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#288]
Here's what I did:

1) ```ace auth:setup``` to setup authentication, it created migration as well which includes tokens table.
2) Changed authenticator from ```authenticator: 'session',``` to ```authenticator: 'api',```
3) Used following code to generate token:
```javascript
const user = yield User.find(1)
const token = yield request.auth.generate(user)
```
if I print this token it contains 121 characters while in ```tokens``` table, column ```token``` has only ```varchar(40)``` 40 characters.

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-auth #19](https://github.com/adonisjs/adonis-auth/issues/19) via [**ZenHub**](https://www.zenhub.com/)
