### ISSUE TITLE
[Proposal] Add table prefix option to config/database.js

### ISSUE THREAD

**Issue by nicklaw5** [adonisjs/adonis-framework#289]
As far as I can see there is no option to provide a table prefix for creating tables with migrations.

Would be great if we could add an option to `config/database.js` to include this:

#### ./config/database.js
```js
...
  mysql: {
    client: 'mysql',
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      user: Env.get('DB_USER', 'root'),
      password: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis'),
      tablePrefix: Env.get('DB_TABLE_PREFIX', 'ad_')
    }
  },
```
#### ./.env.example
```text
...
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_USER=root
DB_PASSWORD=
DB_DATABASE=adonis
DB_TABLE_PREFIX=ad_
```

**Comment by thetutlage** [comment]
Will add it in new release

**Comment by tux-world** [comment]
@thetutlage which date new version maybe released?

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-lucid #58](https://github.com/adonisjs/adonis-lucid/issues/58) via [**ZenHub**](https://www.zenhub.com/)
