### ISSUE TITLE
how to return a http get request result in the browser

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#29]
eg I want get a website's content and render it in my site 
I try some time method,but not work.

**Comment by thetutlage** [comment]
It has nothing to do with `Adonis` itself , in order to make http request to other websites you can make use of https://www.npmjs.com/package/request package

**Comment by wtser** [comment]
![](http://sfault-image.b0.upaiyun.com/425/909/4259092297-5666ac60b3a20_articlex)

**Comment by thetutlage** [comment]
```javascript,line-numbers
request(article.href, function (error, response, body) {
  if(!error){
   response.send(body)
}
})
```

and do not return article

**Comment by wtser** [comment]
i try it but it tell me 
TypeError (500) 
first argument must be a string or Buffer
![](http://sfault-image.b0.upaiyun.com/719/681/719681022-5666adc3600f0_articlex)

**Comment by wtser** [comment]
error: uncaughtException: Can't set headers after they are sent.

**Comment by thetutlage** [comment]
do not return article at the end of the function

**Comment by wtser** [comment]
code
```
*show(request, response) {
    const id = request.param("id");

    const Database = use('Database');
    const data     = yield Database.table('article').select('*').where({id: id});
    const article  = data[0]


    var request = require('request');
    request(article.href, function (error, res, body) {
      if (!error) {
        response.send(body)
      }
    })
  }
```

![image](https://cloud.githubusercontent.com/assets/2093743/11655559/c62da0d4-9de9-11e5-9caa-34b1dbfd6e1d.png)

**Comment by thetutlage** [comment]
can you show output of body

**Comment by wtser** [comment]
console.log 

![image](https://cloud.githubusercontent.com/assets/2093743/11655756/3b7f6452-9deb-11e5-88d5-3e2d441ecbbf.png)

then node throw a error

uncaughtException: Can't set headers after they are sent. 


![image](https://cloud.githubusercontent.com/assets/2093743/11655766/4ec772ca-9deb-11e5-8d06-1194bacf4e12.png)

**Comment by thetutlage** [comment]
weird will check

**Comment by wtser** [comment]
if i remove "return",then it trigger a 500 error,and it rendered in the browser,before my request.send run

**Comment by wtser** [comment]
finally I worked out

```
*show(request, response) {
    const id = request.param("id");

    const Database = use('Database');
    const data     = yield Database.table('article').select('*').where({id: id});
    const article  = data[0];


    var req  = require('request');
    var html = yield new Promise(function (resolve, reject) {
      req(article.href, function (error, res, body) {
        if (!error) {
          resolve(body)
        } else {
          reject(error)
        }
      })

    })
    
    response.send(html)
  }
```

using promise,not using response.send in callback

**Comment by thetutlage** [comment]
This is weird, i will check it soon
