### ISSUE TITLE
Error Creating a new adonis project

### ISSUE THREAD

**Issue by dguzman1012** [adonisjs/adonis-framework#292]
Hello community! I have readed a lot of thing about this frameworks, and i'd like to get involve into this framework. 

I have experience in Nodejs with Expressjs but since this framework is similar to standard laravel MVC... I was interested to try it!

My problem right now is when i try to install. It just doesn't work

I already execute this command: 'adonis check' and i get this output:

![check](https://cloud.githubusercontent.com/assets/5767551/18855584/fe2e20ca-8421-11e6-82e2-fb27104c0426.png)

Then when i execute the basic 'adonis new blog' i get these output:
![output_1](https://cloud.githubusercontent.com/assets/5767551/18855637/691fb02e-8422-11e6-9e57-9f97e1af40b7.png)

![output_2](https://cloud.githubusercontent.com/assets/5767551/18855643/6dcd539c-8422-11e6-8190-a50fab985fc7.png)

I don't understand what's happening.... Does anyone have the same issue??

**Comment by tux-world** [comment]
Hi you must upgrade node to 6 and npm to 3.8

**Comment by thetutlage** [comment]
This exception is thrown by npm when u are out of memory

**Comment by dguzman1012** [comment]
@thetutlage you are absolutely right!!! My bad... I was trying to deploy an Adonis Project into a low memory Virtual Machine... I just upgraded my VM to another with more resources and all went good!

Thanks guys!
