### ISSUE TITLE
How to Fork and add new features?

### ISSUE THREAD

**Issue by theobouwman** [adonisjs/adonis-framework#294]
Dear developers,

I'm new to open source projects and I'd like to add an Task Scheduler to the framework.

But when I fork this project and I add a new provider for my feature, how can I use my forked project as new Adonis Framework?

Thanks

**Comment by thetutlage** [comment]
@theobouwman I would suggest you to create a different repo and work on that for example:- `adonis-mail`, `adonis-redis` etc.

**Comment by thetutlage** [comment]
Closing since not a issue and more of a query. Feel free to discuss it in the Gitter chanel.
