### ISSUE TITLE
help in building relationship - Lucid

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#295]
DATABASE TABLES
```
sockets
---------------
id
user_id
socket_id

trackers
---------------
id
user_id
tracker_user_id
```
LUCID RELATIONSHIP
Tracker.js
```
socket() {
        return this.belongsTo('App/Model/Tracker', 'user_id', 'user_id')
}
```
Code
```
var tacker = yield Tracker.find(1);
console.log("response", tacker.socket());
```
Error:
```
TypeError: lower_case_and_underscored_word.replace is not a function at Object.camelize
```

**Comment by tux-world** [comment]
@webreinvent what was problem? could you reply on your post and explain about problem and how abput resolve this problem, i dont know whats problem, Thanks

**Comment by webreinvent** [comment]
@tux-world thanks but I resolved it :)

**Comment by webreinvent** [comment]
instead of this ```tacker.socket()```, i need to use ```yield tacker.socket().fetch()```, found it in documentation
