### ISSUE TITLE
adonis-mongorito request.auth.attempt returning model.query is not a function

### ISSUE THREAD

**Issue by mubbashar** [adonisjs/adonis-framework#297]
Trying to use mongo package https://github.com/thetutlage/adonis-mongorito with adonis framework. On 
`const login = yield request.auth.attempt(email, password);`
Getting 

`model.query is not a function`

Here is My User model file 

```
'use strict'

//const Lucid = use('Lucid')
const MongoritoModel = use('MongoritoModel')


class User extends MongoritoModel {

}

module.exports = User

```

**Comment by thetutlage** [comment]
It is not an official package supported by AdonisJs. Please contact the package author. https://github.com/allanfreitas/adonis-mongorito

**Comment by tux-world** [comment]
@mubbashar Hi, could you resolve your problem?

**Comment by allanfreitas** [comment]
I've answered here : https://github.com/allanfreitas/adonis-mongorito/issues/2
