### ISSUE TITLE
 Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build                                                                                           llback-to-build'

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#299]
Hello @thetutlage,

Firstly, I need to tell you, I am super excited to use your framework. Cheers for you.

Next, Today i started installing your Adonisjs. And stuck during many instances but that resolved.. but this following issue seems related to framework compatibility.

After running adonis new adonis-hello

`npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\                                                                                            Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fa                                                                                            llback-to-build'.
`

**Comment by thetutlage** [comment]
`fsevents` has some issues on Windows. Can you try installing packages with a noop flag.

```bash
npm i --no-optional
```

**Comment by navdeepsingh** [comment]
Thanks Bro!!
