### ISSUE TITLE
Response file download with a specified file name

### ISSUE THREAD

**Issue by vieks** [adonisjs/adonis-framework#3]
I am storing the file metadata on the database and the file content on the OS file system.
So I set a unique key from database as filename saved to the disk.

Actually the prototype of Response download method is
`response.attachment(path_to_file)`
and should be at least
`response.attachment(path_to_file[, name])`

So I would be able to restore the user original filename while he is downloading it
```javascript
*download(request,response){
      let file = /*fetch data from db*/
      response.attachment(file.path+file.id+file.format, file.name)
  }
```
Could you add the possibility to set a filename on the fly for a file to download ?

Because actually without this option the user receive the database file ID as filename
![image](http://puu.sh/kklPX/3317ce15aa.png)

Could you set an improvement like the code snippet below  ? Also could you add the possibility to set 'Content-Disposition' header to 'inline' or 'attachment' values according to the [underlying module](https://github.com/jshttp/content-disposition#contentdispositionfilename-options) ?

```javascript
  /**
   * Force Download file
   * @param     {String}   |     path                           |     path to file
   * @param     {String}   |     [name]                         |     name
   * @param     {String}   |     [disposition='attachment']     |     Force inline attachment
  */
  Response.prototype.attachment = function(path, name, disposition) {
    name = name || path
    disposition = disposition || 'attachment'
    this.header('Content-Disposition', contentDisposition(name, { type: disposition }))
    this.sendFile(path)
    return this
  };
```

to adonis-framework/node_modules/node-res/lib/index.js

result
![Image](http://puu.sh/kkmLI/d71fde0094.png)

NOTA: Laravel proposes a  [similar thing](http://laravel.com/docs/5.1/responses#file-downloads)

**Comment by thetutlage** [comment]
Sure

**Comment by thetutlage** [comment]
Fixed and latest version of `adonis-framework@1.0.8` will include updated `node-res` which supports filename and disposition.

**Comment by vieks** [comment]
Awesome !
Thanks.
