### ISSUE TITLE
Votes for official support by Adonis for MongoDB

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#300]
I am officially supporting this framework on https://www.patreon.com and would like to extend my support further but many of my clients demand NodeJS with MongoDB. So, either I have to choose other framework or keep stumbling to effectively use MongoDB with AdonisJS.

I would like to ask the community to Vote for official support by AdonisJS for MongoDB.

Do you agree with me?

**Comment by mwaa** [comment]
Yes adonis should support mongoDB. Ready to help out with this, @thetutlage if you need the help

**Comment by webreinvent** [comment]
@mwaa thanks, I was thinking, am I the only one who is expecting such support on the framework. 

@thetutlage how many votes you need to consider it? Although, I know that you're not the fan of MongoDB but we're in the service industry and we have to work according to the demand in the market.

You believe it or not but many people choose SailsJS over AdonisJS, just because it support MongoDB as well as MySql. I did the same but later switched to Adonis.

**Comment by tux-world** [comment]
@webreinvent Thanks, and i like to supported that by AdonisJs

**Comment by thetutlage** [comment]
@webreinvent If you think that you are a heavy user for MongoDB, why don't you write a provider for AdonisJs and make it available to everyone?

**Comment by webreinvent** [comment]
@thetutlage because I am busy enough serving my clients and don't have enough time nor expertise at the moment otherwise I would love to.

**Comment by thetutlage** [comment]
@webreinvent Does that mean I am sitting idle with no work?

As far as expertise are concerned I have never used Mongo in my life and don't think that I am the right candidate for that.

Also https://www.npmjs.com/package/adonis-mongorito seems to be good starting point since it is based upon http://mongorito.com. It is just a matter of taking out some time and making the API more user friendly.

**Comment by webreinvent** [comment]
@thetutlage no, I did not mean that but as you're are the author of the framework we expect more from you.

**Comment by thetutlage** [comment]
@webreinvent Yeah, but I would suggest you to look into the mentioned mongorito based provider, since I don't see any point in not using that.

**Comment by webreinvent** [comment]
@thetutlage I totally agree and we will definitely give it a try but trust me when we inform our clients that we'll use AdonisJS framework, they visit the website and look for the features. When they find no mention of MongoDB then they start questioning or recommend to go with other frameworks. This is the real life scenario. I really like the framework and would like to see it grow like Laravel in NodeJs community. We would love to be your sponsors, vendors, promoters or whatever the way we can support you.

I understand that you too have no experience of mongoDB then my question is how will you make it grow? Because community will be expecting much more features in future and maybe you might not have expertise on those too.

**Comment by mwaa** [comment]
Mongorito is a good package. Will look into https://github.com/allanfreitas/adonis-mongorito and see if it has any short comings.

However, what was thinking would it be hard to have this as part of the Adonisjs and not have to depend on external installs?

**Comment by mwaa** [comment]
@thetutlage if you receive a pull request for this would you be willing to merge into the framework?

**Comment by thetutlage** [comment]
@mwaa I don't understand why it has to be the part of the core. `adonis-auth`, `adonis-mail`, `adonis-lucid` they all are separate packages and the mongo one can be a separate package.

Also @webreinvent the framework is not there to make everyone happy. I know when to upgrade my skills and when not to.

Also if someone has already took an initiative why would I step in between until no one here has a valid point on not using the `mongorito` package and just saying it should be in the core.

**Comment by usamamashkoor** [comment]
Mongodb Support will be really helpful.

**Comment by Noitidart** [comment]
Yes also looking for officially maintained MongoDB support. Community projects always fizzle out. Capable of being a sponsor to support devs behind Adonis.
