### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#301]
![has many through_vux5jm jpg 900x220](https://cloud.githubusercontent.com/assets/2968787/19102531/8af321ea-8aee-11e6-8920-cf34816d54ab.png)

Ref: http://www.adonisjs.com/docs/3.0/relationships

**Comment by thetutlage** [comment]
Thanks, will fix it 😄

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/docs #70](https://github.com/adonisjs/docs/issues/70) via [**ZenHub**](https://www.zenhub.com/)
