### ISSUE TITLE
Handling input text as Array 

### ISSUE THREAD

**Issue by zainul-realtime** [adonisjs/adonis-framework#303]
Hello , i am trying to use adonis , but i have some problem when POST data from input with array (multiple). Actually when use multiple file is work , but in input type text it's doesn't work. how to handle it  ?

for example i have this input

```
<input type="text" name="file_name[]"  value="efg/>

<input type="text" name="file_name[]"  value="abc"/>
```

in server when i get from

```
console.log(request.input('file_name[]');
```

the output will be

```
{
  'file_name[]': abc
}
```

my expectations is get file_name as array , like in multiple file upload ..

Thank you ,
Hopefully there are people help me ..

**Comment by tux-world** [comment]
@zainul-realtime did you test ```console.log(request.input('file_name');``` ???

**Comment by zainul-realtime** [comment]
Yap i have try 
```
console.log(request.input('file_name');
```
But got undefined

**Comment by thetutlage** [comment]
It works fine for me

```html
    <input type="text" name="file_name[]"  value="efg" />
    <input type="text" name="file_name[]"  value="abc" />
```

```javascript
  console.log(request.input('file_name'))
```

**Comment by thetutlage** [comment]
Closing since no reply from the issue reporter and doesn't seems to be an issue. Please reopen if it still face problems

**Comment by andrasf** [comment]
```
<input type="text" name="datas[]" value="one" />
<input type="text" name="datas[]" value="two" />
```

With `{{ form.open({action: 'TestController.index', files: false}) }}`
`console.log(request.input('datas'))` outputs `[ 'one', 'two' ]`

With `{{ form.open({action: 'TestController.index', files: true}) }}`
`console.log(request.input('datas'))` outputs `null`

With `{{ form.open({action: 'TestController.index', files: true}) }}`
When uploading array of files `request.file('files')` returns `null` but `request.file('files[]')` works, returns array.
Handling text values the same way: `request.input('texts')` returns `null` and `request.input('texts[]')` only returns the last value.

It seems like you can have multiple text values with `files: false` OR you can upload multiple files with `files: true` but you cannot have both in one form.

So it has to do with `multipart/form-data` params.

Is this considered as a bug? Also looks inconsistent.
