### ISSUE TITLE
JSON object keys length not work in templating

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#304]
Hello @thetutlage  

{{ [1,2,3] | length }} : works
{{ "test" | length }} : works
{{ {key: value} | length }} : not works in framework

Please cross check. thks!!

**Comment by tux-world** [comment]
@navdeepsingh What happen? you resolved your problem?

**Comment by navdeepsingh** [comment]
Alright!

{{ {key: value} | length }} : not works in framework - sure its not working
rather
{{ JSONObject.length }} works for me

Thanks!

**Comment by tux-world** [comment]
@navdeepsingh then its work on variables only, that right?

**Comment by navdeepsingh** [comment]
Yeah seems!

**Comment by thetutlage** [comment]
@navdeepsingh Can you get length of objects in plain Javascript?

**Comment by navdeepsingh** [comment]
@thetutlage actually wat irks me https://mozilla.github.io/nunjucks/templating.html#length here they said, its working. But not for me. 

So just raised this issue, either {{ JSONObject.length }} already working for me

Thks!!

**Comment by thetutlage** [comment]
It works fine for me. `{{ {key: 'value'} | length }}`

**Comment by thetutlage** [comment]
Closing since no reply from the issue reporter and doesn't seems to be an issue. Please reopen if it still face problems
