### ISSUE TITLE
Adonis-cli installation problem

### ISSUE THREAD

**Issue by ald890** [adonisjs/adonis-framework#305]
During installation in the folder "Example App" adonis-cli throws an error

**Comment by thetutlage** [comment]
Can u please share the error?

**Comment by ald890** [comment]
![error](https://cloud.githubusercontent.com/assets/230560/19151102/26861f40-8bcb-11e6-858a-0c442f6e98a4.png)

**Comment by thetutlage** [comment]
Seems to be some with **space** within the directory name. Will reproduce the issue and fix it within `adonis-cli`.
