### ISSUE TITLE
How can i post JsonObject or JsonArray to Restfull Urls?

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#306]
when i want to test my restful with RestClient i get null for single request, My url which is work fine is
```
http://localhost:3333/user?username=2222
```

[SCREEN SHOT](http://rupload.ir/upload/7a3wqrajmhkfmkhi6k.png)

Route:

```
Route.resource('user', 'RegisterUserController');
```

Controller:

```
'use strict'

const User = use('App/Model/User');
class RegisterUserController {
    * index(request, response) {
        const username = request.input('username');
        response.json({name: username});
    }
}

module.exports = RegisterUserController;
```

**Comment by tux-world** [comment]
@thetutlage could you help me for this issue?

**Comment by thetutlage** [comment]
You are sending request body in a `GET` request whereas it needs to be query string

**Comment by tux-world** [comment]
So how can i use json object or json array from other application such as
android? Adonis couldnt support thay yet?

**Comment by thetutlage** [comment]
@tux-world The entire idea is against the HTTP. There is no point posting data on a GET request and also opens security holes.

I don't think any Platform will limit you to make GET requests only, so consider making a POST request.

**Comment by tux-world** [comment]
@thetutlage ```GET``` or ```POST``` http verbs must be get some format as QueryString or other format such jsonArray or jsonObject, in Android application we can create simple json format and send it to restful such as Laravel routes and parse it very simple, we dont need to create difficult QueryString like with ```?name=mahdi&family=pishguy`, using json is very simple and we can create that quickly, create QueryString string maybe that have some bug such as ```?name=mahdi&familypishguy`, all of my known frameworks support that without any problem such as Laravel or nodeJs express framework

**Comment by tux-world** [comment]
could you help me how can i post this format to controller for parse it:

```
{"widget": {
    "debug": "on",
    "window": {
        "title": "Sample Konfabulator Widget",
        "name": "main_window",
        "width": 500,
        "height": 500
    },
    "image": { 
        "src": "Images/Sun.png",
        "name": "sun1",
        "hOffset": 250,
        "vOffset": 250,
        "alignment": "center"
    },
    "text": {
        "data": "Click Here",
        "size": 36,
        "style": "bold",
        "name": "text1",
        "hOffset": 250,
        "vOffset": 100,
        "alignment": "center",
        "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;"
    }
}}    
```

**Comment by thetutlage** [comment]
I believe you are posting a `raw` body. What do you get after doing `request._raw`?

**Comment by tux-world** [comment]
@thetutlage i get ```null```

**Comment by thetutlage** [comment]
In that case it will be great if you can share the CURL request as I have no idea what data and how it is sent in the HTTP request

**Comment by thetutlage** [comment]
Closing since provided info is not enough

**Comment by tux-world** [comment]
@thetutlage this issue couldnt resolve and all provided information are enough

**Comment by thetutlage** [comment]
@tux-world Read the 1st answer here http://stackoverflow.com/questions/10298899/how-to-send-data-in-request-body-with-a-get-when-using-jquery-ajax.

I am not responsible for supporting for bad practices.
