### ISSUE TITLE
Cache Service Provider

### ISSUE THREAD

**Issue by helnokaly** [adonisjs/adonis-framework#309]
This is not an issue, I just want to share with AdonisJs developers a Cache service provider I published recently on npm. It heavily based on Laravel Cache so API will be familiar.

https://github.com/helnokaly/adonis-cache

Thanks

**Comment by thetutlage** [comment]
Looks great to me 😄. Mind sharing your twitter handle?

**Comment by helnokaly** [comment]
@thetutlage thanks :smiley:
No, it's okay @ Hany_ElNokaly . I'm not active though

**Comment by tux-world** [comment]
@helnokaly Thanks to share that

**Comment by thetutlage** [comment]
Closing since not an actionable issue. Thanks for contributing 😄
