### ISSUE TITLE
how to change session path 

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#31]
router

`Route.post('/admin/login', 'AdminController.login');`

code
```
  *login(request, response) {
    const method = request.request.method;
      const postData = request.post()
      if (postData.account == "wtser@qq.com" && postData.password == "123456") {
        yield request.session.put(postData)
      } else {
        return "用户名或密码错误"
      }
  }
```

![image](https://cloud.githubusercontent.com/assets/2093743/11717594/8097e454-9f8c-11e5-8638-bbabf17ac06f.png)

the path is /admin,so how can i change it to /?

**Comment by thetutlage** [comment]
I have updated docs and code to support options for cookies http://adonisjs.com/docs/1.0/request#session-management

**Comment by thetutlage** [comment]
Also make sure to update `adonis-framework` to version `1.2.0 `

**Comment by wtser** [comment]
thx
