### ISSUE TITLE
Https setup

### ISSUE THREAD

**Issue by Crecket** [adonisjs/adonis-framework#313]
I can't seem to find any documentation on how to implement https. Is this possible or am I simply missing something?

For now, I did some testing and created a basic setup for the framework here #312 

In my adonis-app I changed my .env file and added the following options. 
```
USE_HTTPS=true
HTTPS_KEY=certs/localhost.key
HTTPS_CERT=certs/localhost.crt
HTTPS_CA=certs/localhostCA.pem
``` 

I modified `bootstrap/http.js` to contain the following:
```
if(Env.get('USE_HTTPS')){
    const fs = require('fs');
    Server.listen(Env.get('HOST'), Env.get('PORT'), {
        key: fs.readFileSync(Env.get('HTTPS_KEY')),
        cert: fs.readFileSync(Env.get('HTTPS_CERT')),
        ca: [fs.readFileSync(Env.get('HTTPS_CA'))],
    })
}else{
    Server.listen(Env.get('HOST'), Env.get('PORT'))
}
```
Instead of just
```
Server.listen(Env.get('HOST'), Env.get('PORT'))
```

Like I said, this is just a test but it works perfectly right now. 

I might change the USE_HTTPS option and put it into the config. That way you can make sure a project uses https and only the certificate files are different per .env file

**Comment by thetutlage** [comment]
I would suggest using the `https` module instead. The changes will be in `bootstrap/http.js`.

Replace `Server.listen(Env.get('HOST'), Env.get('PORT'))` with the following code.

```javascript
const https = require('https')

https
   .createServer({key, cert}, Server.handle.bind(Server))
   .listen(Env.get('HOST'), Env.get('PORT'))
```

**Comment by RomainLanz** [comment]
I recommend you to use a proxy like Nginx to and configure your certificate in the Nginx configuration.

**Comment by thetutlage** [comment]
Closing since not a real issue and feel free to discuss more at the gitter channel.
