### ISSUE TITLE
shrinkwrap break new installation 

### ISSUE THREAD

**Issue by mastito03** [adonisjs/adonis-framework#317]
i think shrinkwrap file unneeded in new installation as dependency not need to locked anyway

fsevents dependency on shrinkwrap file break new installation on linux and windows as this library can't be installed on that system.

**Comment by thetutlage** [comment]
Agree! Also after reading this issue https://github.com/npm/npm/issues/2679 shrinkwrap has some potential issues

Would you mind creating a PR for same?

**Comment by mastito03** [comment]
adonisjs/adonis-app#36

**Comment by thetutlage** [comment]
Merged. Closing
