### ISSUE TITLE
Bug in EncryptionProvider 

### ISSUE THREAD

**Issue by slicklash** [adonisjs/adonis-framework#320]
It is possible to create new ciphertexts which decrypt properly by shifting some chiphertext into IV field.

```
original

{ iv: '5QvWn2kaNqXWQSxyV+QTtQ==',
  value: 'HdUgjzuah7ustqD7MvfUd1QfrorhhUI2eoX86amemME=',
  mac: '5405d05343fc98191a136a25575b34a4e818c14d154f8df24b38ed8e305f706b' }

tampered

 { iv: '5QvWn2kaNqXWQSxyV+QTtQ==HdUgjzuah7ustqD7MvfUd',
  value: '1QfrorhhUI2eoX86amemME=',
  mac: '5405d05343fc98191a136a25575b34a4e818c14d154f8df24b38ed8e305f706b' }

```

Either validate IV properly before continuing `(buf = Buffer.from(iv, 'base64')).length === 16 && buf.toString('base64') === iv` or better add IV as first block of value (`payload.value = IV || CT`) and handle decryption accordingly.

**Comment by RomainLanz** [comment]
Hey @slicklash !

Could you please write a payload that I can try on my own machine?
Thanks.

**Comment by slicklash** [comment]
```
const Encryption = require('./index.js')

const ConfigProvider = { get: (x) => x === 'app.appKey' ? 'mantasmantas1234' : 'aes-128-cbc' }

const oracle = new Encryption(ConfigProvider)

const encode = x => oracle.base64Encode(JSON.stringify(x))

const payloads = [
    {
        iv: '5QvWn2kaNqXWQSxyV+QTtQ==',
        value: 'HdUgjzuah7ustqD7MvfUd1QfrorhhUI2eoX86amemME=',
        mac: '5405d05343fc98191a136a25575b34a4e818c14d154f8df24b38ed8e305f706b'
    },
    {
        iv: '5QvWn2kaNqXWQSxyV+QTtQ==HdUgjzuah7ustqD7MvfUd',
        value: '1QfrorhhUI2eoX86amemME=',
        mac: '5405d05343fc98191a136a25575b34a4e818c14d154f8df24b38ed8e305f706b'
    }
]

payloads.forEach(x => { oracle.decrypt(encode(x)) })
```

**Comment by thetutlage** [comment]
@RomainLanz Are you able to produce a bug?

**Comment by RomainLanz** [comment]
The issue here is that we are concatenating `iv` and `value` to create the hash.

```javascript
hash (iv, value) {
  return this.hashHmac('sha256', iv + value, this.appKey)
}
```

So the two payloads provided by @slicklash will be the same after the concatenation.
The encoded `iv` should have a length of 24 (like every 16 char string compiled to base64).

To prevent a modification of the `iv` we could add a verification about the length of the encoded `iv` before the decoding.

```javascript
if (payload.iv.length !== 24) {
  throw CE.RuntimeException.invalidEncryptionPayload()
}
```

If you agree with this solution I'll create a PR @thetutlage, @slicklash

**Comment by slicklash** [comment]
@RomainLanz, @thetutlage. It should fail faster. No need to do 3 expensive HMAC operations (getJsonPayload calls validMac). Put the check inside invalidPayload.

```
invalidPayload (data) {
    return typeof data !== 'object' || typeof data.iv !== 'string' || data.iv.length !== 24 || !data.hasOwnProperty('value') || !data.hasOwnProperty('mac')
}
```

**Comment by RomainLanz** [comment]
@slicklash If we put the test in `invalidPayload` it will fail after mine.

It cannot be before getting the JSONified payload.

**Comment by RomainLanz** [comment]
Ok, let me create a PR and add a failing test.

**Comment by thetutlage** [comment]
@RomainLanz @slicklash Will check it soon.

**Comment by thetutlage** [comment]
Changed it a lot in 4.0, if one can share a failing tests for 4.0, I will be happy to consider it
