### ISSUE TITLE
Model and Migration Creation Naming

### ISSUE THREAD

**Issue by devmattrick** [adonisjs/adonis-framework#323]
Hi there,

When creating a model and migration using the command ```./ace make:model ExampleModel --migration``` causes the migration to be named something like "1476685414062_ExampleModel.js" as opposed to something more sensible like what is generated by ```./ace auth:setup```: "1476685414062_create_examplemodel_table.js" (for the record, either convention is fine, it just makes sense to stick to one).

Its obviously very minor, but it is something to consider.

Thanks for reading and I love your project!

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-lucid #62](https://github.com/adonisjs/adonis-lucid/issues/62) via [**ZenHub**](https://www.zenhub.com/)
