### ISSUE TITLE
Sending mails asynchronous.

### ISSUE THREAD

**Issue by mace015** [adonisjs/adonis-framework#325]
Hi,

I'm playing around with node (day job is PHP/Laravel dev), and I'm very intrigued by this framework.
I'm having a small issue/question and since I cant to find a better place to ask it, i'll just dump it here ;)

I want to send a mail asynchronous because.. well it can take some time with slow SMTP servers, and my gut tells this must be very easy with node, however, I cant seem to get it done with this framework.

I find a lot of 'tricks' to run code asynchronous with Node, but whatever I try, the mail wont be send unless I do it the 'procedural' way (yield the results of mail.send from the controller).

Perhaps i'm totally missing the point but could someone push me the right way in how to actually do this?

Thanks in advance!

**Comment by thetutlage** [comment]
The best way is to make use of events. Consider the following example of sending an email on user registeration

### bootstrap/events.js
```javascript
Event.when('user.registers', function * (user) {
  yield Mail.send('....')
})
```

Learn more about events here http://adonisjs.com/docs/3.1/events

**Comment by mace015** [comment]
Thanks a lot for answering! Implemented an event for sending the mail and it works amazing!

**Comment by thetutlage** [comment]
Great! Closing the issue
