### ISSUE TITLE
question: are there any real world examples that people have put on github?

### ISSUE THREAD

**Issue by illuminate3** [adonisjs/adonis-framework#326]
I've been using larval for a while but have been thinking to move to js. I am not very familiar with js/node/jquery so just jumping and see what works is rather difficult for me. So, I was wondering if anybody has a cms that is on github that they wouldn't mind sharing?

thanks!

**Comment by RomainLanz** [comment]
Dear @illuminate3 !

@thetutlage created [adonis-rally](https://github.com/adonisjs/adonis-rally) which is a forum application (API made with Adonis).

Yesterday Atinux push his [vue-adonis](https://github.com/Atinux/vue-adonis) boilerplate with with server-side rendering out of the box.

[This website](https://www.qualitas-helvetica.ch/) will be also open-sourced in a few weeks.

**Comment by thetutlage** [comment]
Also the documentation website is written in Adonis, here is the source code. https://github.com/adonisjs/adonis-documentation.

Closing since not an actionable issue
