### ISSUE TITLE
Error building project in adonis v5 in production

### ISSUE THREAD

**Issue by DiegoSouza7** [adonisjs/adonis-framework#3266]
I have the following error when building the project for production on linux. Everywhere I use the import from the app it gives this error:

import User from 'App/Models/User'
                   ~~~~~~~~~~~~~
app/Controllers/Http/Auth/ForgotPasswordAppController.ts:3:18 - error TS2307: Cannot find module 'App/Models/User' or its corresponding type declarations.

Version adonis
v5

Node.js version
v14.15.1

**Comment by SamerIstambouli** [comment]
Facing the same issue, did you manage to solve it @DiegoSouza7 ? 
Would appreciate it if you can shed some light on what the issue was.
Thank you

**Comment by SamerIstambouli** [comment]
Actually solved it by adding `"baseUrl": "./"` to tsconfig
