### ISSUE TITLE
Charset=utf-8 in the response header Content-Type

### ISSUE THREAD

**Issue by Atinux** [adonisjs/adonis-framework#329]
Hi!

Is there any way to set the charset by default in the response?
I now that express use the charset=utf-8 in their response header, example for json:

```
Content-Type: application/json; charset=utf-8
```

Actually I found a way of doing it by making:

``` js
response.header('Content-Type', 'application/json; charset=utf-8')
```

But if I render something different than a json, I have to change the header as well.

Do you think the node-res module can set the charset to utf-8 by default like express do?
https://github.com/poppinss/node-res/blob/develop/src/Response/index.js#L166

**Comment by thetutlage** [comment]
Yup makes sense! Will add it to `node-res`

**Comment by thetutlage** [comment]
Done in https://github.com/poppinss/node-res/commit/d68a9ce061f09aa1fda1c7b6afc5438af5e6477a

**Comment by Atinux** [comment]
👏 🎊
