### ISSUE TITLE
Nested route groups

### ISSUE THREAD

**Issue by keeross** [adonisjs/adonis-framework#33]
Route groups are very useful and help a lot. How about to make them nesting?
Some sort of Rails sugar.
```
Route.group('admin',function () {

  // Users
  Route.group('users',function () {

    Route.get('/','UsersController.index');

  }).prefix('/users').close()

}).prefix('/manage').close()
```

**Comment by keeross** [comment]
Hmm, sorry, didn't pay attention to .close() in users group, removed it and it worked out well.

**Comment by keeross** [comment]
Okay, strange situation. Removing .close() worked, but in case like this I have an error.
```
Route.group('manage',function () {

  // Dashboard
  Route.get('/','HomeController.manage');

  // Users
  Route.group('users',function () {

    Route.get('/','UsersController.index');

  }).prefix('/users')

}).prefix('/manage').close()
```
When I try to access dashboard "/manage" + "/", I get 404.

**Comment by thetutlage** [comment]
Nested groups are not supported yet, Newer version of adonis will eliminate the close method and groups will self close themselves and there will be support for nested groups as well.

**Comment by niallobrien** [comment]
Can we add this to the Roadmap?

**Comment by theobouwman** [comment]
Any updates here?

**Comment by lffg** [comment]
> Nested groups are not supported yet, Newer version of adonis will eliminate the close method and groups will self close themselves and there will be support for nested groups as well.

This is going to be available at version 5?
https://github.com/adonisjs/discussion/issues/62
