### ISSUE TITLE
How to enable softDeletes

### ISSUE THREAD

**Issue by PC-HUB** [adonisjs/adonis-framework#333]
Hey, this is the first time i am raising a query to github. I am new to AdonisJs and currently i am having troubles with softDeletes. I followed the documentation but still no luck with softDeletes. 
This is what i did in my Model :

```
'use strict'

const Lucid = use('Lucid')

class Note extends Lucid {

static get deleteTimestamp () {
    var note = new Note();
    return note.deleted_at;
  }

//And i event tried writing the above code like this:

static get deleteTimestamp () {
    return this.deleted_at;
  }

/*This is my Function to delete the row in the same Model Class*/

*deleteNote(id){

    var i;
    for(i=0;i<id.length;i++){

      var notes = yield Note.findBy('id',id[i]);
      yield notes.delete();

    }

    return "Notes Deleted Successfully"

  }
```

I've also added `table.softDeletes()` in my Migrations and after running the migrations it successfully created the column deleted_at in the table of my database

When i deletes a row by calling *deleteNote() from my Controller..it completely deletes the row instead of updating deleted_at column of the database.

Please help to this as i don't get how we can enable it... 😢

**Comment by helnokaly** [comment]
I believe it should be like that

static get deleteTimestamp () {
    return 'deleted_at'
}

**Comment by PC-HUB** [comment]
Wow...it worked like a charm....thanksss a lot man..you saved my time 👍 😆 

Jst Loved it!!!! 💯 😆

**Comment by PC-HUB** [comment]
close

**Comment by helnokaly** [comment]
@PC-HUB you are welcome bro... Happy coding :smile:
