### ISSUE TITLE
Help : how to register a new service provider

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#338]
Hello Helpers,
#### providers/MyName.js

``` javascript
const ServiceProvider = require('adonis-fold').ServiceProvider 
 class MyNameProvider extends ServiceProvider {
    * register() {
        this.app.bind('Adonis/Provider/MyName', function() {
            return 'Navdeep Singh'
        })
    }
}
```

calling like

``` javascript
const myName = use('Adonis/Provider/MyName')
```

Seems not correct way.. got 'Cannot find module 'Adonis/Provider/MyName' '

**Comment by navdeepsingh** [comment]
Well I register my test npm package. And used that in code. That works.
My Question : how to add and register provider in /providers

thks!

**Comment by thetutlage** [comment]
@navdeepsingh You have to register it inside the `bootstrap/app.js` file.

**Comment by navdeepsingh** [comment]
@thetutlage can give me overview by registering my above provider. Because I tried, it seems only node_modules providers can be added.

**Comment by thetutlage** [comment]
@navdeepsingh Can u please share the code on how you are trying to add it.

Let's take this example

### providers/MyName.js
```javascript
const ServiceProvider = require('adonis-fold').ServiceProvider 

class MyNameProvider extends ServiceProvider {
    * register() {
        this.app.bind('Adonis/Provider/MyName', function() {
            return 'Navdeep Singh'
        })
    }
}

module.exports = MyNameProvider
```

### bootstrap/app.js

```javascript
const providers = [
 path.join(__dirname, '../providers/MyName')
]
```

### Usage

```javascript
const MyName = use('Adonis/Provider/MyName')
```

**Comment by navdeepsingh** [comment]
@thetutlage  thks Paji!

Silly mistake! Was missed `module.exports = MyNameProvider`

Keep Rocking!!
