### ISSUE TITLE
Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by majidmushtaq91** [adonisjs/adonis-framework#341]
Hi,
I've deployed adonis project on mac osx then I have pushed my changes to my git repo now when I clone it to ubuntu machine once done I run `"npm install"` its end up on following error 

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
➜  zerobytes.io git:(master) ✗ npm install   
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Comment by RomainLanz** [comment]
Hey @majidmushtaq91,

Can you try to run `npm install` with `--no-optional` option?

```
npm install ---no-optional
```

**Comment by majidmushtaq91** [comment]
@RomainLanz thanks its work !

**Comment by jitendraF5buddy** [comment]
No it's not working i used npm install ---no-optional

**Comment by RomainLanz** [comment]
Hey @jitendraF5buddy 👋 

Please, create an new issue and be sure to use the latest version of the CLI `npm i -g @adonisjs/cli`.
