### ISSUE TITLE
Help : In callback function can't access request

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#343]
Hello @thetutlage 

Seems i can't use request to save requestToken in session.

this is my code
```javascript
* connect (request, response) {
      twitter.getRequestToken(function(error, requestToken, requestTokenSecret, results){
        if (error) {
            console.log("Error getting OAuth request token : " + JSON.stringify(error));
            response.internalServerError(JSON.stringify(error))
        } else {
            //store token and tokenSecret somewhere, you'll need them later; redirect user
            yield request.session.put('requestToken', 'Test') 
            response.send("https://twitter.com/oauth/authenticate?oauth_token=" + requestToken)
        }
      });
 }
```

Error

```javascript
ParseError: Unexpected token
 at             yield request.session.put('requestToken', requestToken) 
```

Any clue will be helpful!!
Thanks!!

**Comment by navdeepsingh** [comment]
ok explored more. And found I am trying to use yield inside a callback function, which seems wrong.
Do i need to convert my function to something other to use by yield
Found link : http://www.josefsima.com/convert-callback-function-to-support-generators-yield-in-nodejs/

Guide me next plz.

**Comment by RomainLanz** [comment]
Hey @navdeepsingh !

You should try to use [co](https://github.com/tj/co).

**Comment by thetutlage** [comment]
Closing since not actionable.
