### ISSUE TITLE
[question][preposal] Can i render a view file from addon ?

### ISSUE THREAD

**Issue by muxahuk** [adonisjs/adonis-framework#344]
Hey, 
I'm trying to split my app to different parts ( like addons ) to make them reusable.
And currently i have views related to my addon in that addon.
Is there a way to load these views and make use of them to {% extend '...' %} ?

If not, then how about making it like symfony ?
i.e.` {% extend '@M7/Addon/Admin:path.file' %}`
and `Route.on( '/admin' ).render( '@M7/Addon/Admin:file' );`

or maybe something else what comes in-to you'r mind, but it would be great feature, as we could write independent reusable addons for addonis :)

**Comment by thetutlage** [comment]
Yes that will be great, there should a way to register multiple paths for views next to a unique identifier. 

I will look into it but this feature may take a while, since I have to define some specs on creating/installing addons.

**Comment by muxahuk** [comment]
Thanks.
Can u provide any guess on estimetion time on specs/these feature ?

**Comment by thetutlage** [comment]
@muxahuk It's hard to share any timeline since I have started working on it yet.

**Comment by muxahuk** [comment]
@thetutlage I have started making it, but since u don't have addons specification/docummentation it's hard to make it really work.. https://github.com/muxahuk/adonis-framework/commit/04fe76b8eb0bb3328915e4f07f2da01550305995

**Comment by thetutlage** [comment]
@muxahuk Closing since actionable and will take care of it in the major release.
