### ISSUE TITLE
[preposal] Make redirect to check if it's route

### ISSUE THREAD

**Issue by muxahuk** [adonisjs/adonis-framework#345]
hey
I'v been doing some basic login and i would like to know, what's you'r thoughts on these:

```javascript
// routes.js
Route.on( '/' ).render( 'home').as( 'home' );

// any controller
const redirect = request.input( 'redirect' );

// currently:
if( redirect ) {
return response.redirect( redirect );
} else {
return response.route( 'home' );
}

// preposal:
return response.redirect( redirect || '@home' );
```

So it would be one method witch is used for both - route and url redirects.. if string starts with `@` it's a route else redirect to provided string...

**Comment by thetutlage** [comment]
That what it does right now. `response.route()` will try to find a route with given value, if not found it will consider the given value as the redirect url.

Also the existence is more of application specific thing, so I would suggest to keep it within the application and not move to the core.

**Comment by muxahuk** [comment]
U should mention that in docs, as these behavior is not obveouse.
Thanks.

**Comment by RomainLanz** [comment]
Will do :+1:

**Comment by muxahuk** [comment]
Also, i think related question:
Can i provide controller action to route to redirect it directly to controller ?
```javascript
return response.route( 'AppController.home2', {} );
```
If not, then consider making these feature, as if we will have addons and they will require some redirects i wouldn't want to define ( or later redefine by mistake the `alias` name for route ).

Here's what i think:
```javascript
return response.route( '@M7/Addon/Admin:LoginController.loginPage', {} );
```

These way, as i think, is more reusable in addons not to specify `.as()` for every route..
what do u think ?

**Comment by thetutlage** [comment]
Closing since added to docs.
