### ISSUE TITLE
[question] How to set variable from module relation in view ?

### ISSUE THREAD

**Issue by muxahuk** [adonisjs/adonis-framework#347]
Hey,

I'm making a profile ( like in you'r examples ) and i would like to extract/get it from `currentUser` in my views.
I'v tryed:
`{% set profile = currentUser.profile() %}`, `{% set profile = currentUser.profile().fetch() %}` and witch yield ( but twig doesn't recorgnizes it and throws an error ).

So, how do i get related table inside the view ? ( I know that i can do it in controller, but i don't want )
or there's no way of doing these ? if not - how can i change `currentUser` so that it has ['profile'] fetched to use it in views ?
May be i can somehow fetch it on every user select? like in you'r exaples `.with( 'profile' )`, but where should i put it ?

Maybe if i change model constructor to something like these:
```javascript
this.fetchedProfile = yield this.profile().fetch();
```
will solve the problem ?

**Comment by thetutlage** [comment]
You can do `{% yield profile = currentUser.profile().fetch() %}` and make sure to case the return value to json using `toJSON` method.

```twig
{% yield profile = currentUser.profile().fetch() %}
{% set profileJSON = profile.toJSON() %}
```

Above should work. Reference to docs http://adonisjs.com/docs/3.1/templating#_yield

**Comment by muxahuk** [comment]
Thanks.
