### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-framework#35]
Hey,

I read [there](https://github.com/adonisjs/adonis-framework/issues/18) that you have a Slack Channel? Can you make it public or maybe create a [Gitter](https://gitter.im/) chat room to discuss about the project? It would be better than create issues.

**Comment by keeross** [comment]
+1 
Gitter would be great for that kind of things.

**Comment by niallobrien** [comment]
@keeross https://gitter.im/adonisjs/adonis-framework
