### ISSUE TITLE
CSRF Secret Missing Issue

### ISSUE THREAD

**Issue by ghosh** [adonisjs/adonis-framework#352]
Hello,

I have a simple registration form setup. It works perfectly on my local machine. However, on the server it returns a `csrf secret missing` error. Running LAMP on Ubuntu 16.04.

- Form
```html
<form class="mb-2" method="POST" action="/register">
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" name="email" class="form-control" id="email" value="{{ old('email') }}" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
  </div>
  {{ csrfField }}
  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
```

- Controller
```js
* doSignup(request, response) {

  const userData = request.only('email', 'password')

  const rules = {
    email: 'required|email|unique:users',
    password: 'required|min:6|max:30',
  }

  const messages = {
    'email.required': 'Why you no give email?',
    'password.min': 'Password should be atleast 6 characters long.',
    'password.required': 'Give password maccha!'
  }

  const validation = yield Validator.validate(userData, rules, messages);

  if (validation.fails()) {
    yield request
      .withAll()
      .andWith({errors: validation.messages()})
      .flash()
    response.redirect('back')
  }

  // Validation passed, create the user.
  const user = new User();

  user.email = request.input('email');
  user.password = yield Hash.make(request.input('password'));

  yield user.save();
  yield request.auth.login(user);

  response.redirect('/');
}
```

- `.env`
```
HOST=localhost
PORT=3333
NODE_ENV=development
CACHE_VIEWS=false
SESSION_DRIVER=cookie
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_USER=root
DB_PASSWORD=
DB_DATABASE=database
```

- `shield.js`
```js
'use strict'

module.exports = {

  csp: {
    directives: {
    },
    reportOnly: false,
    setAllHeaders: false,
    disableAndroid: true
  },

  xss: {
    enabled: true,
    enableOnOldIE: false
  },

  xframe: 'DENY',

  nosniff: true,

  noopen: true,

  csrf: {
    enable: true,
    methods: ['POST', 'PUT', 'DELETE'],
    filterUris: [],
    compareHostAndOrigin: true
  }

}

```
Thanks

**Comment by ghosh** [comment]
I run the site via a reverse-proxy on apache. Seems like it could be because of that the `Host` and `Origin` don't match.

In `shield.js` I changed `csrf. compareHostAndOrigin ` to `false` and its working now. Not sure how safe this is though.

**Comment by thetutlage** [comment]
@ghosh Can u share the output of `request.header('origin')` and `request.header('referer')` on both the pages, the one that renders the form and the other one that gets the submitted values?

**Comment by ghosh** [comment]
So the page that shows the form has
```json
{"header":null,"referer":null}
```

The one that receives the form has
```
{"header":"http://signages.co","referer":"http://signages.co/register"}
```

**Comment by thetutlage** [comment]
Yes that seems to be the issue. Lemme dig more into it.. Thanks 😄

**Comment by thetutlage** [comment]
@ghosh It seems to be working fine. I would need more of your help like

1. The value of `request.hostname()` to the form submission action.
2. Which server are you using for reverse proxy. `nginx` or `apache2`
3. The config file for `nginx` or `apache2` (if possible).

Also make sure to set `trustProxy` to `true` in production when inside `config/app.js` file.

**Comment by smoof974** [comment]
I've got the same issue this morning with two differents projects.

I did not update nothing or modify my project for 5 last days.

Everything was working yesterday.

Did someone have an idea?

Thank you

**Comment by ghosh** [comment]
The page showing the form has

```js
{
    "hostname":"sitename.com"
    "header":null,
    "referer":null
}
```

The form submission route

```js
{
    "hostname":"sitename.com"
    "header":"http://sitename.co",
    "referer":"http://sitename.co/register"
}
```

I'm using apache2 with the following config
```
<VirtualHost *:80>
  DocumentRoot /var/www/sitename.com/

  ProxyPreserveHost On
  ProxyPass / http://localhost:3333/
  ProxyPassReverse / http://localhost:3333/

  ServerName sitename.com
</VirtualHost>
```

Funny thing is in order to check these details I reverted the value of `csrf. compareHostAndOrigin` back to `true`, and the site is still working. It most definitely was not the other day. Not made anychanges since. Not really sure whats going on here.

**Comment by thetutlage** [comment]
Tried with `nginx` and `apache2` both on a Ubuntu machine and cannot reproduce the issue. Closing the issue for now and feel free to re-open if something seems to be breaking
