### ISSUE TITLE
Session shared on all browser

### ISSUE THREAD

**Issue by smoof974** [adonisjs/adonis-framework#353]
Hello,

I've got a bug (or maybe not).

When I login on a browser, my session is detected and used on others browser.

Ex: Login with Firefox, then open Chrome and saw Im alredy connected, try with IE, the sams thing happen.

Can someone help me with this problem.

Thank you

**Comment by smoof974** [comment]
It seems to work when SESSION_DRIVER is set to file, but note when it set to cookie

**Comment by RomainLanz** [comment]
Hey @smoof974 !

This issue has been fixed with the version `3.0.4` of the framework.
Please upgrade the version and let us know if it's working.

**Comment by smoof974** [comment]
Hi @RomainLanz ,

Thank you for fast reply.

Actually Im running the  version 3.1.0 

Thank you

**Comment by RomainLanz** [comment]
The latest version of `adonis-framework` is `3.0.4`. It may be another package from `adonis` that has the version `3.1.0`.

**Comment by smoof974** [comment]
I did the update and seems to works now with SESSION_DRIVER=cookie.

Thank you very much for you help @RomainLanz

**Comment by RomainLanz** [comment]
Perfect! 🎉 

Enjoy coding with AdonisJs 🚀
