### ISSUE TITLE
make simple relation ship and get error

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#355]
I cant make simple relation ship between two table

![Screen Shot](http://rupload.ir/upload/jki0tn14w7cckgl8mabl.png)

my AlachiqChannel model

    channelsTypeId() {
        return this.belongsTo('App/Model/ChannelsType')
    }

and ChannelsType model

    alachigChannels() {
        return this.hasMany('App/Model/AlachiqChannel')
    }

    const channel = yield AlachiqChannel.find(1);
    const channelType = yield channel.channelsTypeId().fetch();

I get this error: 
```
Trying to fetch relationship with channels_type_id as primaryKey, whose value is falsy
```

**Comment by thetutlage** [comment]
Can u share the value of `channel.channels_type_id`

**Comment by tux-world** [comment]
@thetutlage yes sure, i get ```undefined``` unfortunately

**Comment by thetutlage** [comment]
What is the value of `channels_type` with in the database?

**Comment by tux-world** [comment]
in ```alachiqChannels``` table i have more row which all of them have ```1``` on ```channels_type_id``` and they are referenced on ```id``` on ```channelsType``` and on ```channelsType``` that have one row with ```1``` data

alachiqChannels:
![Screen Shot](http://rupload.ir/upload/k9h7tzerr6gd4vv6y6z8.png)

channelTypes:
![Screen Shot](http://rupload.ir/upload/lbk9j0pdam6gdb0s06z.png)

**Comment by tux-world** [comment]
@thetutlage could you found whats problem? i can't find

**Comment by thetutlage** [comment]
It's because the field name in the table is `channel_type_id`  whereas Adonis default foreign key is `channels_type_id`

Redefine your relation as

```javascript
channelsTypeId() {
    return this.belongsTo('App/Model/ChannelsType', 'id', 'channel_type_id')
}
```

**Comment by tux-world** [comment]
@thetutlage Thanks, but after that my relation array is empty and i dont have `channelsType` values on result:

```
AlachiqChannel {
  attributes: 
   { id: 1,
     channelName: 'خبر و خبرگزاریهای رسمی',
     channelLink: 'cafemaku/sajjadmajjad',
     channelDescription: 'کانالهای خبرگزاری رسمی کشور',
     channelImageFileName: 'boldt.jpg',
     channelAvatarFileName: '34.jpg',
     channelState: 0,
     channel_type_id: 1,
     channelOwnerUserId: 0,
     fileServerUrlId: 0,
     created_at: 2016-09-01T15:04:12.000Z,
     updated_at: 2016-09-01T15:04:12.000Z },
  original: 
   { id: 1,
     channelName: 'خبر و خبرگزاریهای رسمی',
     channelLink: 'cafemaku/sajjadmajjad',
     channelDescription: 'کانالهای خبرگزاری رسمی کشور',
     channelImageFileName: 'boldt.jpg',
     channelAvatarFileName: '34.jpg',
     channelState: 0,
     channel_type_id: 1,
     channelOwnerUserId: 0,
     fileServerUrlId: 0,
     created_at: 2016-09-01T15:04:12.000Z,
     updated_at: 2016-09-01T15:04:12.000Z },
  transaction: null,
  relations: {},
  frozen: false,
  eagerLoad: 
   EagerLoad {
     withRelations: [],
     withNestedRelations: {},
     relationsScope: {},
     nestedRelationsScope: {} } }
```

**Comment by muxahuk** [comment]
@tux-world You need to do: `const chanels = yield channel.channelsTypeId().fetch()`

**Comment by tux-world** [comment]
@muxahuk yes you are right, and i'm using that on my code sir,

```
const channel = yield AlachiqChannel.find(1);
const channelType = yield channel.channelsTypeId().fetch(); 
```

but i ```relation``` array is empty
