### ISSUE TITLE
Bug with toInt() sanitization function

### ISSUE THREAD

**Issue by Perfect7M** [adonisjs/adonis-framework#356]
Folowing code gnerate error `Cannot read property '0' of undefined`
```javascript
     const id = Validator.sanitizor.toInt(yield request.session.get('id'));
```

You must provide second argument:
```javascript
        const id = Validator.sanitizor.toInt(yield request.session.get('word'), 0);
```
And the problem gone. It's propably bug

**Comment by thetutlage** [comment]
Please file issue with https://github.com/poppinss/indicative
