### ISSUE TITLE
Problem with --harmony_proxies and node v7 

### ISSUE THREAD

**Issue by obstschale** [adonisjs/adonis-framework#357]
I upgrade to node 7.0.0 and I have now problems with `--harmony_proxies`. If I try to start a server with this flag the server will crash. Without it it's no problem.

That happens for the commands in `package.json` > `scripts` and even `./ace` is not running properly.

Node v6.9.1 is fine. 

Any idea ?

**Comment by RomainLanz** [comment]
Hey @obstschale !

Node 7 has removed the `harmony_proxies` flag in favor of `harmony`. You need to update commands in the `package.json` file and the hashbang in `ace`.

**Comment by obstschale** [comment]
:+1: Thx

**Comment by thetutlage** [comment]
Closing!
