### ISSUE TITLE
problem with create relation ship between tables

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#362]
i have three table on database and i'm trying to make simple relation ship between them, tables are ```channels```, ```channels_status``` and ```channels_type```,

content of ```channels``` is:

        {
            "id": 1,
            "channelName": "My Test Channel",
            "channelLink": "cafemaku/sajjadmajjad",
            "channelDescription": "Channel Description",
            "channelImageFileName": "boldt.jpg",
            "channelAvatarFileName": "34.jpg",
            "channels_status_id": 1,
            "channels_type_id": 2,
            "channelOwnerUser": 0,
            "fileServerUrlId": 0,
            "created_at": "2016-09-01 19:34:12",
            "updated_at": "2016-09-01 19:34:12"
        }
    
```channels_status``` :

        {
            "id": 1,
            "canShow": "userCreatedChannels",
            "deleted": "userCreatedChannels",
            "limited": "userCreatedChannels",
            "created_at": "2016-11-04 14:12:13",
            "updated_at": "2016-11-04 14:12:13"
        }

and ```channels_type```:

        {
            "id": 2,
            "channelTitle": "userCreatedChannels",
            "created_at": "2016-11-04 14:12:13",
            "updated_at": "2016-11-04 14:12:13"
        }

when i try to make relation ship between them i get ```null``` for ```channels_status```, for example:

```Channels``` model:

```
'use strict'

const Lucid = use('Lucid')

class Channels extends Lucid {
    static get table() {
        return 'channels'
    }

    channelType() {
        return this.belongsTo('App/Model/ChannelsType')
    }

    channelStatus() {
        return this.belongsTo('App/Model/ChannelsStatus')
    }

}

module.exports = Channels;
```

```ChannelsType``` model:

```
'use strict'

const Lucid = use('Lucid')

class ChannelsType extends Lucid {
    static get table() {
        return 'channels_type'
    }

    channels() {
        return this.hasMany('App/Model/Channel')
    }

}

module.exports = ChannelsType
```

```ChannelsStatus``` model:

```
'use strict'

const Lucid = use('Lucid')

class ChannelsStatus extends Lucid {
    static get table() {
        return 'channels_status'
    }

    status() {
        return this.hasMany('App/Model/Channel')
    }
}

module.exports = ChannelsStatus

```

using ```Eager Loading```  data channels content with relation ship:

    const channel = yield Channels.find(1);
    const users = yield Channels
        .query()
        .with('channelType', 'channelStatus')
        .fetch();
    response.send(users);

i get this Result of relation ship:

```
    [
        {
            "id": 1,
            "channelName": "My Test Channel",
            "channelLink": "cafemaku/sajjadmajjad",
            "channelDescription": "Channel Description",
            "channelImageFileName": "boldt.jpg",
            "channelAvatarFileName": "34.jpg",
            "channels_status_id": 1,
            "channels_type_id": 2,
            "channelOwnerUser": 0,
            "fileServerUrlId": 0,
            "created_at": "2016-09-01 19:34:12",
            "updated_at": "2016-09-01 19:34:12",
            "channelType":
            {
                "id": 2,
                "channelTitle": "userCreatedChannels",
                "created_at": "2016-11-04 14:12:13",
                "updated_at": "2016-11-04 14:12:13"
            },
            "channelStatus": null
        }
    ]
```

**Comment by thetutlage** [comment]
Can u share the query log by setting `debug:true` inside `config/database.js` file

**Comment by tux-world** [comment]
​I dont have any setting as ```debug``` to change on that file

**Comment by thetutlage** [comment]
http://adonisjs.com/docs/3.1/database-setup#_debugging

**Comment by tux-world** [comment]
@thetutlage Thanks, i enabled it and this is result:

```
{ method: 'select',
  options: {},
  bindings: [ 1, 1 ],
  sql: 'select * from `channels` where `id` = ? limit ?' }
{ method: 'select',
  options: {},
  bindings: [],
  sql: 'select * from `channels`' }
{ method: 'select',
  options: {},
  bindings: [ 2 ],
  sql: 'select * from `channels_type` where `id` in (?)' }
{ method: 'select',
  options: {},
  bindings: [ undefined ],
  sql: 'select * from `channels_status` where `id` in (?)' }
```

**Comment by tux-world** [comment]
@thetutlage in that ```bindings``` is ```undefined``` i check ```channel_status_id``` on ```channels``` and ```id``` on ```channels_status``` again. both of them are correct to make relation ship

**Comment by thetutlage** [comment]
Is it `channel_status_id` or `channels_status_id`

**Comment by tux-world** [comment]
its ```channels_status_id```

**Comment by thetutlage** [comment]
Okay lemme try to reproduce it

**Comment by tux-world** [comment]
do you want to i take some screen shot from them?

**Comment by thetutlage** [comment]
There is a bug in the related library called `inflect`. For now you can define `primary` and `foreign` keys manually.

```javascript
    channelStatus() {
        return this.belongsTo('App/Model/ChannelsStatus', 'id', 'channels_status_id')
    }
```

Related issue https://github.com/MSNexploder/inflect/issues/7

**Comment by tux-world** [comment]
@thetutlage problem resolved by redefine that, Thanks
