### ISSUE TITLE
Problem sending 204 status code with content-type header

### ISSUE THREAD

**Issue by Eusse** [adonisjs/adonis-framework#363]
Hi, i'm using adonis to create a JSON API for a ember js application. According to JSON API docs, [deleting resources](http://jsonapi.org/format/#crud-deleting-responses-204) needs to send a 204 status code with no content on success, and, as with the whole concept, needs to send the application/json [header](http://jsonapi.org/format/#content-negotiation-servers). The problem is that when i send the status 204, it deletes the content type header, no matter if i use the `.header()` or `.json()` method. This is my code: 
````
* destroy (request, response) {
    const contact = yield Contact.find(request.param('id'))
    let result = yield contact.delete()
    if(result){
      response.status(204)
      response.header('Content-type', 'application/json')
      response.send()
      //response.status(204).json() //this fails also
    }
  }
````
Just in case, this is my dependency list:
````
"dependencies": {
    "adonis-ace": "^3.0.4",
    "adonis-auth": "^1.0.4",
    "adonis-commands": "^2.1.2",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.3",
    "adonis-jsonapi": "^0.4.1",
    "adonis-lucid": "^3.0.8",
    "adonis-middleware": "^1.0.8",
    "mysql": "^2.11.1",
    "standard": "^8.4.0",
    "youch": "^1.0.1"
  }
````

**Comment by thetutlage** [comment]
Not sure why JSONAPI has that requirement with 204 status code since `Content-Type` is required when there is content in response.
https://tools.ietf.org/search/rfc2616#section-7.2.1

**Comment by thetutlage** [comment]
Closing since no reply from the issue creator.

**Comment by Eusse** [comment]
Sorry about the delay. If someone is having this same issue, what i did to solve it is using the 200 status code [response](http://jsonapi.org/format/#crud-deleting-responses-200) and returning the `meta` body like this
````json
{
  "meta": {
    "copyright": "Copyright 2015 Example Corp.",
    "authors": [
      "Yehuda Katz",
      "Steve Klabnik",
      "Dan Gebhardt",
      "Tyler Kellen"
    ]
  }
}
````
