### ISSUE TITLE
AJAX csrf token mismatch issue

### ISSUE THREAD

**Issue by banbanchs** [adonisjs/adonis-framework#370]
Hi!

I tried to use AJAX sending a request but AdonisJS keep throw `csrf token mismatch` error.

Then I found out cookie `XSRF-TOKEN` is encrypted, so csrf verify would always fail.

According to [Laravel document](https://laravel.com/docs/5.3/csrf#csrf-x-xsrf-token) and [its code](https://github.com/laravel/framework/blob/d03eddbdf0b77fc03b3f185d3171095a72018fd7/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L114), Laravel will decrypt the value of header `X-XSRF-TOKEN`, so that like the document says:

> Frontend Frameworks like AngularJs automatically reads this cookie and send it along with each Ajax request.

(Actually, It's not working on AdonisJS now....)

But AdonisJS treated `csrf-token`, `x-csrf-token` and `x-xsrf-token` [as same](https://github.com/adonisjs/adonis-middleware/blob/develop/src/Shield/index.js#L189-L191)

AJAX example code:

```html
<script>
  var csrfToken = /* read XSRF-token from cookie */;
  $.ajaxPrefilter(function (options, originalOptions, jqXHR) {
    jqXHR.setRequestHeader('csrf-token', csrfToken);
  });
  $.post('/test');
</script>
```

**Comment by RomainLanz** [comment]
You shouldn't read the CSRF Token from the cookie.

Use a global object or a metadata field to store your token.

```html
<meta name="csrf-token" value="{{ csrf_token() }}">
```

```html
<!-- Master Template -->
<script>
window.MY_SITE = {
  csrf_token: {{ csrf_token }}
}
</script>
```

**Comment by banbanchs** [comment]
@RomainLanz Thanks for replying :). I already used the first solution.

But the reason provided `XSRF-TOKEN` cookie is for frontend frameworks like [angular](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L1287) can automatically use it, I guess? `XSRF-TOKEN` cookie looks like useless at present.

Maybe we should follow the implement of Laravel decrypting `X-XSRF-TOKEN` header before verify it?

**Comment by thetutlage** [comment]
@banbanchs Agree with you. The purpose of `XSRF-TOKEN` is to keep it easier for Angular or similar frameworks to make the CSRF process simple.

Will fix it.

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-middleware #5](https://github.com/adonisjs/adonis-middleware/issues/5) via [**ZenHub**](https://www.zenhub.com/)
