### ISSUE TITLE
can i write simple Module or plugin with installable ability?

### ISSUE THREAD

**Issue by tux-world** [adonisjs/adonis-framework#372]
in some frameworks such as Laravel or some CMS like such as WordPress we can write simple plugin or modules and use that simply, for example on laravel we can write or splitting  some features as modules

**Comment by RomainLanz** [comment]
You can do whatever you want.

**Comment by tux-world** [comment]
@RomainLanz for example split admin features such as register module,send sms module, manage ticket module. write new module and install that from admin panel like with WordPress

**Comment by thetutlage** [comment]
@tux-world That is the domain logic and framework cannot support that. Frameworks are different from CMS's

**Comment by tux-world** [comment]
@thetutlage yes, but ```Laravel``` or ```Yii``` can support this feature, split features as modules

**Comment by thetutlage** [comment]
Examples?

**Comment by tux-world** [comment]
@thetutlage you can see this link: http://kamranahmed.info/blog/2015/12/03/creating-a-modular-application-in-laravel/

**Comment by RomainLanz** [comment]
@tux-world This is just code, you can also code that if you want.

**Comment by tux-world** [comment]
@RomainLanz You are right, how can i implementing this ability on AdonisJs ?

**Comment by thetutlage** [comment]
Closing since not actionable and not related to the core of the framework. @tux-world I would suggest to share/discuss ideas on Gitter.
