### ISSUE TITLE
Knex with official oracledb driver

### ISSUE THREAD

**Issue by tejzpr** [adonisjs/adonis-framework#373]
Hi, Seems the official oracledb driver support was there in knex from version 0.11.8 [https://github.com/tgriesser/knex/pull/990](https://github.com/tgriesser/knex/pull/990). I was able to connect to Oracle 12 by installing oracledb nodejs driver in my AdonisJS project using the following configuration:

```javascript
oracle: {
    client: 'oracledb',
    connection: {
      timeout: 10,
      host: 'localhost:1521',
      //port:'1521',                **//Declaring port here does not work**
      user: 'username',
      password: 'password',
      database: 'mydb'
    },
    debug: true
  }
```

But even after the connection got through, any queries made to OracleDB through the AdonisJS model resulted in an error. I am using a pre-defined table called 'USERS' (notice uppercase) with associated Model called Users. When the query is made to OracleDB it goes like this:
Error: select * from "users" - ORA-00942: table or view does not exist 
[Seems passing table names in quotes does not work with Oracle.](http://stackoverflow.com/questions/8628412/enclosing-column-names-within-double-quoatation-marks-with-create-command-in-ora). Is it possible to fix this issue from lucid so that we can add node/oracledb driver support to AdonisJS?

**Comment by thetutlage** [comment]
Is this the oracle db support issue? Or the table name needs to be fixed?

**Comment by tejzpr** [comment]
Table name passes inside double quotes to the DB like this: **`select * from "users"`**
Instead, it should pass like this : `**select * from users**`

**Comment by thetutlage** [comment]
Does it work fine with `knex`?

**Comment by tejzpr** [comment]
Just tested with latest Knex v0.12.6, and the issue exists in Knex library. Meanwhile knex.raw("select * from USER");  works fine with NodeJS/OracleDB driver. Meanwhile stong-oracle does not work at all.

**Comment by thetutlage** [comment]
@tejzpr Seems to be an issue with knex. Would you mind reporting this issue with them?

**Comment by tejzpr** [comment]
Done! :)

**Comment by thetutlage** [comment]
@tejzpr Does it only happens when table name case is mis-matched or everytime?

**Comment by tejzpr** [comment]
This issue occurs only if table name or field name case mismatch occurs. If table name & field name is of the same case in DB and Model then everything works fine. Verified this by overriding table name in model by using the following code.
`static get table () {
    return 'USER'
  }`

**Comment by tejzpr** [comment]
Another issue I just found is that **Omitting Fields From JSON** Output by using 
 ```
 static get visible () {
    return ['title', 'body']
  }
```
does not work with Oracle Database.

**Comment by tejzpr** [comment]
A possible solution to this issue could be that any Table name or Field name generated for Oracle data source be converted to uppercase before passing on to Knex query builder since Oracle internally saves table names & field names in upper case. i.e. even if a table is created in lower case like `user_list` in oracle it can still be accessed by running `select * from USER_LIST;`. But if a table is created in upper case like "USER_LIST" it cannot be accessed by passing `select * from user_list;`

**Comment by thetutlage** [comment]
Nope the end user should be responsible for setting up right database table name, instead of framework deciding it

**Comment by thetutlage** [comment]
Since it's not an issue with lucid, neither with knex, closing the issue

**Comment by tejzpr** [comment]
Hi according to [comment ](https://github.com/tgriesser/knex/issues/1785#issuecomment-261482022)from the knex issue that I raised some days back, the case sensitivity to Oracle table names should be handled while creating queries. Since AdonisJs had generators for creating models, shouldn't query compatibility be handled during that time?

**Comment by thetutlage** [comment]
Since Adonis does not know whether the `table name` is **lowercase** or **uppercase** it seems to be hard to transform names on the fly. The best way is to define the `tablename` on the model.
