### ISSUE TITLE
Omitting Fields From JSON does not work with Oracle Database

### ISSUE THREAD

**Issue by tejzpr** [adonisjs/adonis-framework#374]
I just found is that **Omitting Fields From JSON** Output by using 
 ```
 static get visible () {
    return ['title', 'body']
  }
```
does not work with Oracle Database. I get full results in JSON regardless of what I add in `get visible() `method.

**Comment by thetutlage** [comment]
how do you access the json output?

**Comment by tejzpr** [comment]
I am accessing the JSON output by accessing the URL `http://localhost:4000/users` which is generated by accessing `response.json(users)` which is defined in `UserController`

**Comment by thetutlage** [comment]
Can u share the entire code of the controller?

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-lucid #71](https://github.com/adonisjs/adonis-lucid/issues/71) via [**ZenHub**](https://www.zenhub.com/)
