### ISSUE TITLE
Differences between relationships.

### ISSUE THREAD

**Issue by theobouwman** [adonisjs/adonis-framework#375]
I know that M:M, 1:M and 1:1 relationships are.
But in the documentation there are a few more options to choose from.

- hasOne
- belongsTo                                           
- hasMany 
- belongsToMany
and 
- hasManyThough

EXAMPLE:
So you can say, a Category `hasMany` movies and you could say that a Category `belongsToMany` movies. But which one should you use. And what are the guidelines to choose one.

EXAMPLE:
A car `belongsTo` a user, or a car `hasOne` user.
A user `hasOne` car, and a user `belongsTo` a car.

I don't know the technical difference between these formulations, but I know there has to be a 1:M (one:many) side and a M:1 (many:one) side.

Thanks in advance.

Theo

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-lucid #70](https://github.com/adonisjs/adonis-lucid/issues/70) via [**ZenHub**](https://www.zenhub.com/)
