### ISSUE TITLE
HTTPS and HTTP2 support

### ISSUE THREAD

**Issue by ais-one** [adonisjs/adonis-framework#377]
Any possibility of including the options above? And also to run application to listen to multiple ports, so for eg 80 will serve http traffic but 443 can serve either https or http2.

I know it can be done just need to modify the adonis-framework/src/Server/index.js file...

Depending on config, require https or http2, (http is already available).

As for listening on multiple ports, that is another matter, worse case may need to create separate projects (unless someone can enlighten me toa better way).

Nginx and Apache can be used as reverse proxy and provide https & http2, however, it may nice to also be able to have https/http2  without using Nginx or Apache2

**Comment by RomainLanz** [comment]
Hey @ais-one!

Why do you want to get rid of a reverse proxy?

**Comment by thetutlage** [comment]
@ais-one Http2 is mainly helpful in pre serving content which is mainly assets. There's hardly any Node.js server exposed on port 80 and all of them lives behind `nginx` or `apache` or similar.

It will be overkill for the framework to do all this. I would suggest to nginx.

**Comment by ais-one** [comment]
Ok makes sense for now, I close this.
