### ISSUE TITLE
[Suggestion] replace route group with the method name

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-framework#379]
so instead of having
```js
Route.group('version1', function () {
  Route.get('/users', function * (request, response) {
  })
}).prefix('/api/v1')
```
it would be 
```js
Route.prefix('/api/v1', function () {
  Route.get('/users', function * (request, response) {
  })
})
```

writing the route like this makes it much easier for maintainability and improve code readability/quality specially when the nested group option gets added.

**Comment by thetutlage** [comment]
It is not only about prefixing the routes since you can also attach a middleware to a group of routes.

**Comment by ctf0** [comment]
in that case maybe we can then use it like
```js
Route.group([
  {prefix:'/api/v1'},
  {middleware: 'auth'}
], function () {
  Route.get('/users', function * (request, response) {
  })
})
```

**Comment by thetutlage** [comment]
This is even weird than the current syntax we have right now.

**Comment by ctf0** [comment]
its using the same syntax laravel is following, which is an array of options instead of using the chained methods, am totaly new to js world so forgive me

**Comment by thetutlage** [comment]
Laravel have it's own ways of doing things. Also I don't find any reason of changing the syntax and introducing a new breaking change.

**Comment by ctf0** [comment]
okay then, thanx for ur help 👍
