### ISSUE TITLE
Got "ParseError: Unexpected token" while using yield

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-framework#38]
Pretty sure i did not get the concept of generators, but why the heck I get a parse error in this method?

> `yield Database.from('admin').insert({access_token: tokens.access_token});` ^ ParseError: Unexpected token

`getToken(code)` is called from within a controller.
`oauth2Client.getToken` responds correctly, access_token is properly logged.

### Parse error
```js
const Database = use('Database');
const google = require('googleapis');
const googleAuth = require('google-auth-library');

class GoogleCalendarService {

  constructor() {
      let OAuth2 = google.auth.OAuth2;
      this.oauth2Client = new OAuth2(CLIENT_ID, CLIENT_SECRET, REDIRECT_URL);
  }

  * getToken(code) {
    let oauth2Client = this.oauth2Client;
    oauth2Client.getToken(code, function (err, tokens){
      if (!err) {
        oauth2Client.setCredentials(tokens);
        console.log(`Save ${tokens.access_token} to database`);
        //yield Database.from('admin').insert({'access_token': tokens.access_token});
      }
    });
  }
}
```

**Comment by gearsdigital** [comment]
Found a workaround using https://github.com/tj/co

**Comment by thetutlage** [comment]
how are you calling getToken in your controller ?

**Comment by gearsdigital** [comment]
This is the controller:

```js
'use strict';
const GoogleCalendarService = use('App/Services/GoogleCalendarService');

class CalendarController {

  constructor() {
    this.calendarService = new GoogleCalendarService();
  }
  
  * authorize(request, response) {
    let params = request.get();
    this.calendarService.getToken(params.code);

    const view = yield response.view('index.html');
    response.ok(view);
  }

  * index(request, response) {
    const view = yield response.view('index.html', {url: this.calendarService.generateAuthenticationUri()});
    response.ok(view);
  }

}

module.exports = CalendarController;
```

And here the appropriate route:

```js
Route.get('/auth', 'CalendarController.authorize');
```

**Comment by thetutlage** [comment]
You will have to use the `yield` while using `getToken` since it is a generator method

```javascript
yield this.calendarService.getToken(params.code);
```

**Comment by gearsdigital** [comment]
I tried it already, but it did not work out. In this case i got the parse error:

```
yield Database.from('admin').insert({'access_token': tokens.access_token}); ^ ParseError: Unexpected token
```

<img width="1296" alt="screen" src="https://cloud.githubusercontent.com/assets/965069/12030660/87a5ec94-ae02-11e5-8188-9ce1d937f338.png">

**Comment by thetutlage** [comment]
Ohh got it, coz you are trying to run it inside the callback of `oauth2Client.getToken` and generators needs to be at the first level of `* method`.

I am not a big fan of callbacks and if you are interested you can make use of https://github.com/tj/node-thunkify. It will convert your callbacks to generator friendly methods. Something like this

```javascript
const oauthToken = thunkify(oauth2Client.getToken)
try {
  const tokens = yield oauthToken(code)
  oauth2Client.setCredentials(tokens);
  console.log(`Save ${tokens.access_token} to database`);
  yield Database.from('admin').insert({'access_token': tokens.access_token});
}
catch (e) {
  console.log(e)
}
```

**Comment by gearsdigital** [comment]
I'll try that... :) Thank you for your fast and helpful support bro! :+1:
