### ISSUE TITLE
cannot paginate results for page less than 1

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-framework#380]
code
```js
Route.get('users', function*(req,res){
    const User = use('App/Model/User')
    const users = yield User.paginate(req.input('page'),2);
    yield res.sendView('users', { users: users.toJSON() });
})
```

view
```blade
{% for user in users %}
    <h2>{{ user.username }}</h2>
{% endfor %}
```

![demo](https://cloud.githubusercontent.com/assets/7388088/20544138/3fdfd5ba-b111-11e6-9ee7-12184ab4a723.jpg)

am still new into this but this is basicly based on the http://adonisjs.com/docs/3.1/lucid#_paginate_page_perpage_20 demo

if used `const users = yield User.paginate(2);` i get a diff error
```
(views/users.njk) TypeError: next is not a function
```

**Comment by thetutlage** [comment]
What's the value of `req.input('page')`. Also please post the entire view file.

**Comment by ctf0** [comment]
honestly i don't know how the paginate should work, i thought that i just need to give the items count i need per each page and the method will take care of the paging ex.laravel, however if i manually passed any number to the `req.input('page')` i get the second error as above

regarding the view that's all the code in it i believe am missing something but the docs doesnt instruct what exactly i should have to make this work.

**Comment by thetutlage** [comment]
@ctf0 Can u share the controller and the view code?

**Comment by ctf0** [comment]
sure
* route
```js
Route.get('users', function*(req,res){
    const User = use('App/Model/User')
    const users = yield User.all();
    yield res.sendView('master', { users: users.toJSON() });
})
```
* model
```js
'use strict'

const Lucid = use('Lucid')

class User extends Lucid {

}

module.exports = User
```
* view
```twig
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf_token" content="{{ csrfToken }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>AdonisJs - Node.Js MVC Framework</title>
    <link rel="icon" type="image/png" href="assets/favicon.png" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <section>
        <div class="container">
            <div class="row">
                {% for user in users %}
                <p>{{ user.username }}</p>
                {% endfor %}
            </div>
        </div>
    </section>
</body>
</html>
```

**Comment by ctf0** [comment]
### update

```js
const users = yield Database.from('users').forPage(1,2);
yield res.sendView('users', {users: users});
```
works but using `paginate(1,2)` gives error
```js
TypeError: next is not a function
```

still not sure how adonis handle the navigation through paginated results.

**Comment by ais-one** [comment]
You can do it this way, to check for page being a wrong number

let page = parseInt(req.input('page'))
if (isNaN(page)) page = 1
const rv = yield Student.paginate(page, 5);

**Comment by ctf0** [comment]
@ais-one can u make a gist with a simple demo ?

**Comment by thetutlage** [comment]
I tried the `paginate` method and all seems to be working fine. @ctf0 You can share a repo with required code to reproduce the issue?

**Comment by ctf0** [comment]
@thetutlage https://github.com/ctf0/ado-demo

**Comment by thetutlage** [comment]
@ctf0 

Here are the issues.

1. You should define a default value when page is not defined in the query string.

```js
request.input('page', 1)
```

2. If you look at the pagination response just by sending JSON to the browser, you will find that list of all the users is stored inside `data` key.

```twig
        {% for user in users.data %}
          <p>{{ user.username }}</p>
        {% endfor %}
```

**Comment by ctf0** [comment]
oooh okay, i added that part to the docs.

one last question, how adonis navigate through the paginated data, does it have something like https://laravel.com/docs/5.3/pagination#displaying-pagination-results 
or does the user have to make his own implmentation & if so can u give a small example and i will add i to the docs aswell ?

**Comment by ais-one** [comment]
Hi,

It should return pagination information. Use postman to test and you can
see what is being returned



*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by thetutlage** [comment]
@ctf0 There is no inbuilt paginator and it is simple as loop through the meta data and creating anchor tags.

**Comment by ctf0** [comment]
okay, thanx
