### ISSUE TITLE
Question: How to call API routes from within an Adonis app?

### ISSUE THREAD

**Issue by nicklaw5** [adonisjs/adonis-framework#384]
I would like to be able to call API routes from within non-API controller methods. My apps controllers are namespaced with `app/Http/Controllers/Web/` for regular website requests and `app/Http/Controllers/Api/` for external API access (with API tokens). The below `routes.js` file displays this:

```js
// app/Http/routes.js

const Route = use('Route')
const apiMethods = ['index', 'store', 'show', 'update', 'destroy']

Route.get('/books', 'Web/BooksController.index').as('get-books')
// ... other non-api routes

Route.group('api-v1', () => {
  Route.resource('books', 'Api/BooksController').only(apiMethods)
  // other api routes
}).prefix('/api/v1').middleware('apiAuth')
```

How can I call the `index` method on the `App/Http/Controllers/Api/BooksController.js` file from within the below `Web` controller?

```js
// app/Http/Controllers/Web/BooksController.js

'use strict'

class BooksController {

  * index (request, response) {
    // how can I call App/Http/Controllers/Api/BooksController.index ??
  }
}

module.exports = BooksController
```

**Comment by thetutlage** [comment]
Controllers are executed when your routes receive HTTP call. If you want to make an internal `http` request consider using https://npmjs.org/package/got.

**Comment by RomainLanz** [comment]
Hey @nicklaw5 !

If you use the `resource` helper it will create routes for you.

Take a look at the documentation http://adonisjs.com/docs/3.1/routing#_resourceful_routes

**Comment by nicklaw5** [comment]
Thanks @thetutlage, I thought that may be the case. I was hoping there was an alternative (perhaps hidden) Adonis feature that provided support for this.
