### ISSUE TITLE
[possible Bug] select query sort items on its own

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-framework#387]
* code
```js
Route.get('users', function*(req,res){
  const DB = use('Database');
  const users = yield DB
                  .on('sql', console.log)
                  .table('users')
                  .select('id');
  res.send(users)
})
```
* result
```js
[
  {"id": 1}, 
  {"id": 7}, // why this is here
  {"id": 2},
  {"id": 3},
  {"id": 4},
  {"id": 6},
  {"id": 9},
  {"id": 10}
]
```
* query
```bash
+ 5.78 ms : select `id` from `users`
```

----

> things even go crazier when selecting more than one row

* code
```js
Route.get('users', function*(req,res){
  const DB = use('Database');
  const users = yield DB
                  .on('sql', console.log)
                  .table('users')
                  .select('id','email');
  res.send(users)
})
```
* result
```js
[
  {
    "id": 10,
    "email": "andro@ex.com"
  },
  {
    "id": 3,
    "email": "karem@ex.com"
  },
  {
    "id": 4,
    "email": "koko@ex.com"
  },
  {
    "id": 6,
    "email": "mare@ex.com"
  },
  {
    "id": 9,
    "email": "nour@ex.com"
  },
  {
    "id": 2,
    "email": "ri@ex.com"
  },
  {
    "id": 1,
    "email": "sara@ex.com"
  },
  {
    "id": 7,
    "email": "ski@ex.com"
  }
]
```
* query
```bash
+ 15 ms : select `id`, `email` from `users`
```
as u can see, for some reason now the result is being sorted alphabetically according to email

**Comment by thetutlage** [comment]
If there was a sorting clause then it would be been shown within the **query**. What's the result when you run this query using mysql command line

**Comment by ctf0** [comment]
same result *this is weird*

**Comment by thetutlage** [comment]
Yup, something seems to be wrong with your DB itself.

**Comment by ctf0** [comment]
okay, i understand this is out of ur scope, but any idea what could be the issue ? or how to debug it ?

**Comment by thetutlage** [comment]
Is data saved in the right order? And which DB are you using?

**Comment by ctf0** [comment]
mysql

![dsfg](https://cloud.githubusercontent.com/assets/7388088/20607615/997ff25e-b282-11e6-89c9-5801361ab670.jpg)

**Comment by ctf0** [comment]
i think this answer it http://dba.stackexchange.com/questions/6051/what-is-the-default-order-of-records-for-a-select-statement-in-mysql

**Comment by ctf0** [comment]
so i think to avoid such issue in future , maybe we can add an `orderby` to the select query by default ?
