### ISSUE TITLE
Route.resource in Route.group problem

### ISSUE THREAD

**Issue by belozer** [adonisjs/adonis-framework#388]
```js
Route.group('public', () => {
  Route
  .resource('objects', 'api/public/ObjectsController')
  .only('store')
  .addMember('metrics', ['POST'])
  .addMember('actions', ['POST'])
  .as('public.objects')
})
.prefix('/api/v1/public')

Route.group('api', () => {
  Route
  .resource('objects', 'api/ObjectsController')
  .except('edit', 'create')
  .addMember('metrics')
  .addMember('users')
  .middleware('auth')
})
.prefix('/api/v1')
```

it generated two identical name

| Method  | URI                            | Action                                           | Middlewares  | Name 
|------------|------------------------------|----------------------------------------------|---------------------|------------------         
| POST   | /api/v1/public/objects | api/public/ObjectsController.store |                         | objects.store   
| POST   | /api/v1/objects           | api/ObjectsController.store            | auth                 | objects.store

**Comment by thetutlage** [comment]
Yup, it is a known issue. Will fix it by prefix the group name since that is unique.

**Comment by thetutlage** [comment]
@belozer Prefixing the `group name` will be a breaking change for others since their route names will be change. 

I will queue this up for the major release. For now I can suggest to make use of `as` method of resource as follows.

```javascript
      Route
      .resource('objects', 'api/public/ObjectsController')
      .only('store')
      .addMember('metrics', ['POST'])
      .addMember('actions', ['POST'])
      .as({
        store: 'public.objects.store',
        metrics: 'public.objects.metrics',
        actions: 'public.objects.actions'
      })
```

**Comment by naxmefy** [comment]
Route group could become an hidden extension to allow options like Route.group of Laravel

```PHP
        Route::group([
            'middleware' => ['web', 'admin'],
            'namespace' => 'App\Http\Controllers\Admin',
            'prefix' => 'admin',
            'as' => 'admin.',
        ], function ($router) {
            require base_path('routes/admin.php');
        });
```
the option property "as" set the prefix for names inside the group

**Comment by thetutlage** [comment]
Removed `addMember` and `addCollection`, they are super confusing and doesn't add much value either
