### ISSUE TITLE
Custom Helpers for Query Builder

### ISSUE THREAD

**Issue by theobouwman** [adonisjs/adonis-framework#389]
Is it possible to add a custom Helper to the Query Builder.
If so, where can I put this?

**Comment by belozer** [comment]
@theobouwman maybe you need use query scopes?
http://adonisjs.com/docs/3.1/lucid#_query_scopes

**Comment by theobouwman** [comment]
@belozer na, not really

**Comment by RomainLanz** [comment]
Hey @theobouwman!

What do you mean by `custom Helper` if it's not Query Scope?

**Comment by thetutlage** [comment]
Closing since no updates from the reporter
