### ISSUE TITLE
Support for multiple apps

### ISSUE THREAD

**Issue by lakshyaranganath** [adonisjs/adonis-framework#390]
Hey, first off great project team!

I was just fiddling around with a lot of nodejs frameworks out there, and stumbled upon adonis, and was wondering if there is support for multiple apps inside a single repo (something like django apps).

My use case is basically,
A single adonis project that handles authentication for other apps in the same project repo.
Each of these apps could basically be a simple webpage/api/dashboardapp etc...

**Comment by ais-one** [comment]
AdonisJS is very very similar to Laravel, you google about this. Currently it is not structured they way you have described.

You can attempt to modularize it yourself though, e.g. seperate folders under controller & under model, separate route files for each app

**Comment by lakshyaranganath** [comment]
Guess I'll have to dabble around AdonisJS to see if it fits 😄 

Thank you so much for clearing that up.
