### ISSUE TITLE
[Question] how to get the current instance of (request & response)

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-framework#392]
like in the controller , the methods have something like
```js
* index(request, response) {
   // ...
}
```

so how to do the same in somewhere else like
```js
* something(){
   const request = // the current instance of request
   const response = // the current instance of response
}
```

**Comment by thetutlage** [comment]
What do you mean by somewhere else?

**Comment by ctf0** [comment]
ex.
* PostController
```js
class PostController extends BaseController {

    * index(request, response) {
        yield response.sendView('form')
    }

    * store(request, response) {
        const rules = {...}

        // validate and redir on fail
        yield this.validate(rules);

        // all good, save data
        // response.send(request.all());
    }
}
```
* BaseController 
```js
validationFailed(validation) {
    return function*() {
       //  the current instance of request
       //  the current instance of response
        yield request.withAll().andWith({ errors: validation.messages() }).flash()
        response.redirect('back')
    }
}

* validate(rules, messages) {
    const data =  // the current instance of request.all();
    const validation = yield Validator.validateAll(data, rules, messages);

    if (validation.fails()) {
        yield this.validationFailed(validation)
    }
}
```

**Comment by thetutlage** [comment]
You need to pass, `request` and `response` to the method

**Comment by helnokaly** [comment]
There is no "current instance of request" becasue all requests in AdonisJS are all on the same application instance.

In Laravel every request instantiates a new application instance.

You have to pass the request and response as params to the function in the BaseController:
```javascript
yield this.validate(rules, request, response)
```

**Comment by ctf0** [comment]
is there away to register the req & res the same way its done in the route clouse or the controller methods ?

**Comment by thetutlage** [comment]
@ctf0 Still not clear

**Comment by ctf0** [comment]
i mean 
```js
route.get('/x', function*(req, res){
// ...
}
```
how do u bind `req & res` to the route closure without giving error of `req/res is undefined`

**Comment by thetutlage** [comment]
http://adonisjs.com/docs/3.1/routing#_basic_example

**Comment by ctf0** [comment]
i don't know how to explain it more than of what i already did, anyway thanx.

**Comment by aliturki2020** [comment]
How could I access request or the whole `context` from `trait`?
