### ISSUE TITLE
Unable to save and commit within a promise callback.

### ISSUE THREAD

**Issue by tiyindyfee** [adonisjs/adonis-framework#395]
We're trying to save within a promise callback, but while the model property updates, it does not persist to the database.

Here's a simplified example. I've tried numerous approaches, but nothing works so far. What am I missing? Thanks!

```javascript
* index(request, response) {
    let test = yield User.findBy('id', 4)

    fetch('http://localhost:3333/api')
    .then(response => response.json())
    .then(function() {
      function *testSave() {
        test.phone_number = Math.round(Math.random() * 10000)
        yield test.save()
      }

      let ts = testSave()
      ts.next()

      response.json(test)
    })
  }
```

**Comment by RomainLanz** [comment]
You cannot use `yield` inside a `callback`.

```javascript
const response = yield (yield fetch('http://localhost:3333/api')).json()

test.phone_number = Math.round(Math.random() * 10000)
yield test.save()
```

**Comment by tiyindyfee** [comment]
Do you know why not? It seems to modify the model in memory, just not save to the database. Yield seems to work in generally with callbacks, but it doesn't commit the database transaction.

**Comment by tiyindyfee** [comment]
Thanks for your help. Here's our working test case for anyone else looking at this in the future:

```javascript
* index(request, response) {
    let test = yield User.findBy('id', 4)

    let randomNumber = yield fetch('http://localhost:3333/api')
    .then(response => response.json())
    .then(function() {
      return Math.round(Math.random() * 10000)
    })

    test.phone_number = randomNumber
    yield test.save()

    response.json(test)
 }
```

**Comment by RomainLanz** [comment]
> Do you know why not?

`yield` is only working in generator function and a callback is not a generator function. Note that you can remove all of your callbacks by using `yield`. Your code will be cleaner.

**Comment by tiyindyfee** [comment]
Thanks for the reply, but actually the yield is working and is in a generator function. I'm wondering why the save method doesn't seem to actually save.

**Comment by RomainLanz** [comment]
You need to call `yield` when you call a generator.

So `let ts = testSave()` should be `let ts = yield testSave()` but you will use `yield` inside a non-generator function. 😬
