### ISSUE TITLE
Template render error

### ISSUE THREAD

**Issue by thanhps42** [adonisjs/adonis-framework#397]
I got this error when execute this controller:
`try {`
`      var result = request.input("result");`
`      var accounts = yield Account.query()`
`        .where({result: result})`
`        .select(["email", "password", "result", "info"])`
`        .fetch();`
`      yield response.sendView("account/export", {accounts: accounts});`
`    } catch (ex) {`
`      response.status(400).json({error: ex});`
`}`

In my view (resources/views/account/export.njk):
`{% for item in accounts %}`
`  <p>{{ item.email }}</p>`
`{% endfor %}`

And result:
> {"error":{"name":"Template render error"}}

**Comment by thetutlage** [comment]
Change following line of code 

### from
```javascript
yield response.sendView("account/export", {accounts: accounts});
```

### to

```javascript
yield response.sendView("account/export", {accounts: accounts.toJSON()});
```

**Comment by thanhps42** [comment]
Thanks.
