### ISSUE TITLE
how to use external node packages?

### ISSUE THREAD

**Issue by haabnaseem** [adonisjs/adonis-framework#399]

**Comment by thetutlage** [comment]
You would asked the same question on your existing issue https://github.com/adonisjs/adonis-framework/issues/398.

Using node packages is same as in any other node.js app. `require('package')`

Closing

**Comment by TrebatickyMatus101** [comment]
Unresolved method or function require() i think it is not the same

**Comment by RomainLanz** [comment]
What do you mean @TrebatickyMatus101?

Also, please create a new issue of you have any issue with Adonis or ask any questions in the forum/Discord server.
