### ISSUE TITLE
.env file add possibility to bind to an host

### ISSUE THREAD

**Issue by vieks** [adonisjs/adonis-framework#4]
Currently we can only bind to a port
`APP_PORT=80`

It would be convenient to define a host too
`APP_HOST=127.0.0.1`

That will be handled by `server.start(host, port)`

```javascript
/**
 * @function start
 * @description start http server on a given port
 * @param  {Number} port
 * @public
 */
Server.prototype.start = function (port) {
  this.Logger.info('serving app on port %s', port)
  this.serverInstance.listen(port)
}
```

**Comment by thetutlage** [comment]
What about a quick pull request with equivalent tests ,  i am into adding relationships support for ORM

**Comment by niallobrien** [comment]
Regarding the ORM? Why create a new one instead of using an existing ORM? Thanks.

**Comment by thetutlage** [comment]
which one will you recommend

**Comment by niallobrien** [comment]
I think Waterline, Sequelize or Bookshelf are all viable options. Thinky is a great ORM for RethinkDB if you're after realtime goodness with RethinkDB's changefeeds. The framework's looking great btw, keep up the great work.

**Comment by thetutlage** [comment]
i considered these options but they really didn't fit my requirements, i will write down post soon on why i planned to create the entire framework but in short i am in favor of expressive syntax.

Also lucid has endless possibilities it is very young so i have to cover lot of stuff

**Comment by niallobrien** [comment]
I agree with you, the fact that you care about the syntax and API is very obvious. Thank you for your hard work. I have yet to play with ES6 properly, so putting together an asset pipeline to use with Adonis might give me the perfect excuse to try it out. :)

**Comment by thetutlage** [comment]
what can be a good option for you in asset pipelining, I believe gulp is very much industry standard. But I am open to suggestions

**Comment by niallobrien** [comment]
For sure, check my repos - I've done a lot with Gulp and recently played with Webpack too.

**Comment by RomainLanz** [comment]
Can be close when https://github.com/adonisjs/adonis-app/pull/1 is merged.

cc @thetutlage
