### ISSUE TITLE
yield in Model

### ISSUE THREAD

**Issue by Perfect7M** [adonisjs/adonis-framework#400]
There is a way to yielding in model?

I create command which start bot in my app like this

```javascript
      this.info('Bot is starting...')
      Bot.init();
````
Then i have some nested function `init() -> watch() -> check()` in check i want to check for Redis cache to make better performance than checking evry time in database. So here my question:
There is a way to yield for example `Redis` to get value from cache? If not (I think isn't posible) how to make command to use some Controller (command insantly call Controller to use)?

**Comment by thetutlage** [comment]
Can u share some code and context on where you want to start the bot?

**Comment by Perfect7M** [comment]
Im using this package: https://docs.tmijs.org/
But the problem is that i have some standard code:
```javascript
    this.client = new tmi.client(this.config);
    // Connect the client to the server..
    this.client.connect();

    this.client.on("roomstate", function* (channel) {
      Bot.watch(channel);
    });
```
In watch function i have:
```javascript
    this.client.on("chat", function (channel, userstate, message, self) {
          [...]
          Redis.set(username, 'test');
          Redis.get(channel);
    }
```
But i can;t yield `Redis` fundtion in `function() {}` callback. But using promise fro me isnt working.

**Comment by thetutlage** [comment]
You can wrap your commands inside `co` https://npmjs.org/package/co

```
co(function * () {
  yield Redis.set()
}).then().catch()
```

**Comment by thetutlage** [comment]
Closing since actionable and no updates from the issue reporter too
