### ISSUE TITLE
Can i run raw queries?

### ISSUE THREAD

**Issue by seemsindie** [adonisjs/adonis-framework#401]
Hello guys, just a quick question: Can i run raw queries like here http://adonisjs.com/docs/3.1/migrations#_raw_statement but in controllers?
Thanks

**Comment by RomainLanz** [comment]
Hey @seemsindie !

What do you mean by running raw queries in controller?

**Comment by seemsindie** [comment]
@RomainLanz Can i use this http://knexjs.org/#Schema-raw ?

**Comment by thetutlage** [comment]
You can make use of it

```javascript
Database.schema.raw()
```

**Comment by seemsindie** [comment]
@thetutlage thanks man
