### ISSUE TITLE
Error when I trying to store a info

### ISSUE THREAD

**Issue by golinmarq** [adonisjs/adonis-framework#404]
I have a resourceful controller. Everything works fine when I use GET method, but when I want to store a new data I get an error that says: Error (403) host and origin mis-match. 

I use Postman to test my API so I think this is the problem. What is happening??

**Comment by thetutlage** [comment]
You need to send csrf token when making post request

**Comment by golinmarq** [comment]
@thetutlage thanks for your reply! how can I do this?

**Comment by thetutlage** [comment]
http://adonisjs.com/docs/3.1/csrf-protection

**Comment by golinmarq** [comment]
@thetutlage sure, I read this but I'm using a tool to test my API, I'm not using a form

**Comment by golinmarq** [comment]
Also, When I'm using React, how can I access to this token to send it to my API?

**Comment by thetutlage** [comment]
If it's an API endpoint, it's better to disable to the CSRF protection inside the config file

**Comment by thetutlage** [comment]
Closing, since not actionable and seems to be working fine
