### ISSUE TITLE
how can I use pagination?

### ISSUE THREAD

**Issue by merodiro** [adonisjs/adonis-framework#405]
how can I use pagination? 
the docs isn't clear about it, is there a simple way to include it in views?

**Comment by thanhps42** [comment]
Example: [http://s23.postimg.org/qw8fyil0b/screenshot_15.png](http://s23.postimg.org/qw8fyil0b/screenshot_15.png)

**Comment by alexsoftdev** [comment]
Is there way to render it not manually, but via some widget ?

**Comment by RomainLanz** [comment]
Hey @alexsoftdev! 👋 

Please, use the forum or the Discord Server for this kind of question.
