### ISSUE TITLE
How i can open adonis from other device in my network

### ISSUE THREAD

**Issue by ahmedawm2** [adonisjs/adonis-framework#408]
Hello, 
when i open my adonis server it work successfully from localhost with 'http://localhost:3333/'
but when i open it from other pc in my network by my local network ip address like 'http://192.168.1.12:8080/' not working 
i want any way to open it by my local network ip or any other way.

**Comment by navdeepsingh** [comment]
Hello,

Have you tried 'http://192.168.1.12:3333/' ? Currently my Virtual Host IP is 192.168.1.5 and I can access http://192.168.1.5:3333/ Plz cross check.

**Comment by thetutlage** [comment]
Make sure you change `localhost` to `0.0.0.0` inside .env file.

**Comment by Dougmarcolino** [comment]
> Make sure you change `localhost` to `0.0.0.0` inside .env file.

here it did not work, can anyone help me? 

![image](https://user-images.githubusercontent.com/7004832/46120774-63c10380-c1e7-11e8-89f7-4137f97ada96.png)

**Comment by tim3ks** [comment]
windows firewall :)

**Comment by DanleyCr7** [comment]
Dourgmarcolino voce bota o HOST= 0.0.0.0 e restarta o serve.
