### ISSUE TITLE
How can I remove attachment file after response it?

### ISSUE THREAD

**Issue by thanhps42** [adonisjs/adonis-framework#409]
My code: 

```javascript
*export(request, response) {
    let savePath = Helpers.storagePath("uploads") + "\\doc.txt";
    Database.raw(`COPY docs(id,name,value) TO '${savePath}' DELIMITER '|'`)
      .then(function (result) {
        response.attachment(savePath, "doc.txt");
      })
      .catch(function (ex) {
        response.status(400).json({error: ex});
      })
  }
```

I want to delete "doc.txt" after response is completed. How can I do that?

Thanks.

**Comment by thetutlage** [comment]
Make use of `fs` module to unlink the file.

**Comment by thanhps42** [comment]
I can't

Here is my code:

let savePath = Helpers.storagePath("uploads") + "\\ssh.txt";
    Database.raw(`COPY sshes(host,username,password) TO '${savePath}' DELIMITER '|'`)
      .then(function (result) {
        response.attachment(savePath, "ssh.txt");
        **fs.unlink(savePath, function (err) {
          if (err) response.status(400).json({error: err});
        });**
      })
      .catch(function (ex) {
        response.status(400).json({error: ex});
      })

And result: throw exception :((

**Comment by thetutlage** [comment]
What exception?

**Comment by thanhps42** [comment]
Error message: Not Found

**Comment by thetutlage** [comment]
Do you have file inside the storage directory?

**Comment by thanhps42** [comment]
When I remove "fs.unlink" I see "txt" file, if not I don't :(

**Comment by thanhps42** [comment]
Can you give me example how to do that?

Thanks.

**Comment by thanhps42** [comment]
@thetutlage Can you help me? :(

Thanks.

**Comment by thetutlage** [comment]
By looking at your code, I am not even sure how do you get the file at first place and also why you want to remove it.

Are you trying to delete uploaded file via HTTP. It will be great if you can share the entire code.

**Comment by thanhps42** [comment]
I export my table (postgresql) to "doc.txt" by using **COPY** command (postgres). Then I let user download it via **attachment** method. Then I want to delete "doc.txt" after user has been downloaded.

P/s: I think problem is "doc.txt" has been removed before user download it :(

**Comment by thetutlage** [comment]
Yup coz, `attachment` method streams the file to the user. I suggest you to wait until the response has been finished and then remove the file. You can make use of `onFinished` module https://github.com/jshttp/on-finished

### Example code

```javascript
let savePath = Helpers.storagePath("uploads") + "\\doc.txt";

Database
.raw(`COPY docs(id,name,value) TO '${savePath}' DELIMITER '|'`)
.then(function (result) {
     onFinished(response.response, function () {
          fs.unlink(savePath, function (err) {
              // you cannot write anymore to response now.
          })
     })
    response.attachment(savePath, "doc.txt");
})
.catch(function (ex) {
   response.status(400).json({error: ex});
})
```

**Comment by thanhps42** [comment]
@thetutlage Thanks <3

**Comment by thetutlage** [comment]
Closing since it seems to be working
