### ISSUE TITLE
proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag

### ISSUE THREAD

**Issue by cannap** [adonisjs/adonis-framework#41]
hi i try to run migration but i got 
proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag

package.json the original 
Win 10
Node: v5.3.0
NPM: 3.5.2

Command i use: 
node ace migration:run

but very good work and good docs :dancers:

**Comment by cannap** [comment]
i got it node --harmony_proxies ace migration:run

**Comment by thetutlage** [comment]
also you can run ace commands without using node like this `./ace migration:make` and it will work

**Comment by cannap** [comment]
this is not working for me on windows

**Comment by cannap** [comment]
i created a simple ace.bat with "node --harmony_proxies ace %*"

**Comment by thetutlage** [comment]
:+1:

**Comment by freehosting2016** [comment]
That is note work for me i also  created  ace.bat with "node --harmony_proxies ace %*" on project root directory

**Comment by JeyKeu** [comment]
Getting the same error on ubuntu 16.10 with
node: 4.2.6
npm: 3.5.2

**Comment by thetutlage** [comment]
You need to add `--harmony_proxies` flag when running the ace commands or the dev server.

```
node --harmony_proxies server.js
```

From Node6.0 this flag is not required

**Comment by JeyKeu** [comment]
I fixed it by removing `--harmony_proxies` from `ace`

**Comment by aitchkhan** [comment]
for Node v4, v5, the flag `--harmony_proxies` is required as adonis is using es2015 features.
for v6 and higher the flag is not required as Node has almost 99% coverage of es2015 features.

can we document it somewhere? or have I missed the documents?

**Comment by cannap** [comment]
@aitchkhan  http://dev.adonisjs.com/docs/4.0/installation :D soon

**Comment by aitchkhan** [comment]
@cannap  let me know if I can be of any help :D

**Comment by cannap** [comment]
@aitchkhan that problem is fixed since 1 year :D
