### ISSUE TITLE
Help for ES6 import feature

### ISSUE THREAD

**Issue by navdeepsingh** [adonisjs/adonis-framework#410]
Hello @thetutlage 

In my project, I am trying to import chart.js using like this
```
// ES6
import Chart from 'src/chart.js'
```

But i keep getting message
```
SyntaxError: import declarations may only appear at top level of a module
import Chart from 'src/chart.js'
```

Please help further, seems I am missing something or ?

**Comment by thetutlage** [comment]
Nodejs does not support ES next module loader yet, I am not sure why you using it

**Comment by navdeepsingh** [comment]
Trying to use chart.js in Adonisjs project using Vuejs.
Ref :  http://www.chartjs.org/docs/#getting-started-usage

**Comment by thetutlage** [comment]
It has nothing to do with Adonisjs, since it is a frontend library and needs to transpiled using babel or equivalent

**Comment by navdeepsingh** [comment]
Thanks for reply, virk sir :)
will check on that now.
