### ISSUE TITLE
Route Group prefix not working without leading slash

### ISSUE THREAD

**Issue by effectjared** [adonisjs/adonis-framework#415]
Installing a clean version of Adonis 3.2.0 and copy-pasting the route group example from the docs returns a 404.

```
Route.group('version1', function () {
  Route.get('users', function * (request, response) {
    response.send('test')
  })
}).prefix('api/v1')
```

It seems that when adding a prefix the leading slash is removed from the route, you are are able to fix this by instead defining the prefix as `/api/v1`.

Is this a bug or is it just the documentation which is wrong?

**Comment by RomainLanz** [comment]
Dear @effectjared !

Thanks for reporting this issue! ❤️

**Comment by manojchandrashekar** [comment]
Thank you. I faced the same issue while following the docs.
