### ISSUE TITLE
How to change Template Engine?

### ISSUE THREAD

**Issue by jaysg** [adonisjs/adonis-framework#418]
Is there any way to change the template engine would rather use something like pug.

**Comment by thanhps42** [comment]
I think nunjuckis better than pug :D

**Comment by thetutlage** [comment]
AdonisJs does not allow to configure template engines, since the idea of the framework is not have lot of boilerplate. `nunjucks` serve the purpose well and allowing too many template engines will be confusion for beginners coming into the eco-system.

**Comment by webdevian** [comment]
@jaysg Pug was a must-have for me too (lots of mixins I use across projects/platforms), so I've written a simple pug provider for adonis https://www.npmjs.com/package/adonis-pug
