### ISSUE TITLE
How to access to websocket clients from http controller?

### ISSUE THREAD

**Issue by ekifox** [adonisjs/adonis-framework#419]
Hello everyone,

I have a chat on websocket and i need to push some message entered from http api to everyone from websocket.

i.e. I need to call `socket.toEveryone().emit('message', 'From API')` (/app/**Ws**/Controllers/ChatController.js) from /app/**Http**/Controllers/ApiController.js

**Comment by thetutlage** [comment]
Simply grab the chat channel and call the emit message on it. Reference to docs http://adonisjs.com/docs/3.2/websocket#_emit_event_properties_2

#### Example

```javascript
const Ws = use('Ws')

// In your controller method
Ws.channel('chat'). emit('message', 'From API')
```

**Comment by ekifox** [comment]
@thetutlage wow, nice, thank you!

If not difficult, answer a few more questions for me :P

1) how best to create a static class to store some variables and create a couple of timers in this class

2) I need to implement Steam Bot in the same nodejs project which is a website and sockets, how to do it better (to have access to sockets and other classes, for example, static class in first question)?

**Comment by thetutlage** [comment]
Those are more of general programming questions. I would suggest to have a chat in the gitter room https://gitter.im/adonisjs/adonis-framework.
