### ISSUE TITLE
Using query strings to filter data

### ISSUE THREAD

**Issue by golinmarq** [adonisjs/adonis-framework#420]
In my db I have users with some types define by a number, e.g. `0` for **admins**, `-1` for **writers** and `1` for **viewers**. I need to query some users according its role, so in the * index function I coded

```javascript
index(request, response) {
    const userType = request.param('type', 'all')
    console.log(userType)
    switch(userType) {
      case 'writers':
        let users = yield User().where('type','<',1).fetch()
        break
      case 'viewers':
        let users = yield User.query().where('type','>=',0).fetch()
        break
      default:
        let users = yield User.query().where('type','<',2).fetch()
        break
    }
    response.json(users.toJSON())
  }
```

But I get Identifier 'users' has already been declared. 

What's the best approach to complete this?

**Comment by thetutlage** [comment]
You cannot redefine a variable multiple times and neither a switch statement is required either. Also I will suggest to ask these in the gitter room instead of creating issues. https://gitter.im/adonisjs/adonis-framework.

For now, you must define `users` at the top level and then re-assign it the query.

```
let users = null

switch (userType) {
  case 'writers':
        users = yield User().where('type','<',1).fetch()
        break
      case 'viewers':
        users = yield User.query().where('type','>=',0).fetch()
        break
      default:
        users = yield User.query().where('type','<',2).fetch()
        break
}
```
