### ISSUE TITLE
Babel issue with controllers

### ISSUE THREAD

**Issue by milosdakic** [adonisjs/adonis-framework#421]
Running Adonis through Babel, everything works fine apart from the controller mapping mechanism.

Works fine
```js
Route.get('version', function * (request, response) {
  response.send('okay')
})
```

Doesn't like the `export`
```js
Route.get('version', 'UtilsController.version')
```

```js
export default class UtilsController {
  * version (request, response) {
    response.send('okay')
  }
}
```

Is this an issue with the way `adonis-fold` does dependancy injection?

**Comment by RomainLanz** [comment]
Dear @milosdakic !

Adonis does not support any transpiler like Babel nor TypeScript.

Babel 6.0 transpile `export default` with `module.export.default = {}` this is probably why it is not working.

You may try to use the Babel plugin [babel-plugin-add-module-export](https://www.npmjs.com/package/babel-plugin-add-module-exports).

**Comment by thetutlage** [comment]
Yup that is the reason. Also I believe using babel is redudant ( in my view ). Node.js latest versions are almost compatible with ES6 specs
