### ISSUE TITLE
Integrate Raven js Sentry error logging

### ISSUE THREAD

**Issue by zeal29gdd** [adonisjs/adonis-framework#422]
Allow me to drop this here.
Is there a way to use sentry error logging to AdonisJs used as API(backend)?

**Comment by RomainLanz** [comment]
Hey @zeal29gdd

Yes! There's no reason that Adonis block you from using any third-party package! If you code works outside of Adonis it will works inside of it too!

If you encounter any issue please, fill free to ask a question.
