### ISSUE TITLE
JWT Authenticator

### ISSUE THREAD

**Issue by akusany2** [adonisjs/adonis-framework#424]
Not able to work with JSON Web Tokens Authenticator. Did everything written in docs:

```
authenticator: 'jwt'
jwt: {
    serializer: 'Lucid',
    model: 'App/Model/User',
    scheme: 'jwt',
    secret: Config.get('app.appKey'),
    options: {
      expiresIn: 999999
    }
  }
```

I am able to get the token through:
```
const user = yield User.findBy('username','test')
const token = yield request.auth.generate(user)
```

Sending it through Postman with Authorization header (along with Bearer)
<img width="1079" alt="screen shot 2017-01-14 at 1 00 54 am" src="https://cloud.githubusercontent.com/assets/3200031/21942920/04ecc2d0-d9f5-11e6-8cbf-a0b46b3be380.png">

Route:
```
Route.resource('/user', 'UserController')
  .middleware('auth:jwt')
```

It always gives 401 Unauthorized - Login Failure

Am I missing something? Do I need to write my own middleware?

**Comment by RomainLanz** [comment]
Hey @akusany2 !

The value should be `Bearer <token>`

**Comment by akusany2** [comment]
@RomainLanz Thank you for quick reply!! And yes my bad "Bearer" did the work! Thanks again, great framework.

**Comment by alanaasmaa** [comment]
Sorry for reopening old issue but i have the same problem.

Im using Bearer in front of token, my Header is sent to server.

I tried to use middleware and also yield `request.auth.check()`

I got the token by 

```
const currentUser = yield User.find(user.original.id)
const jwtToken = yield request.auth.generate(currentUser)
```

I have no idea what i'm doing wrong, i have spent on this about 5 or more hours.

**Comment by RomainLanz** [comment]
Hey @alanaasmaa !

Please, ask for help on the forum.

https://forum.adonisjs.com/
