### ISSUE TITLE
Why there is no MongoDB!????

### ISSUE THREAD

**Issue by dezashibi** [adonisjs/adonis-framework#426]
Hi ma friend
as you actually know most of Node.js developers including me like to use MongoDB as their database, the thing I'm really shocked up about is that why such a beautiful and lovely framework that stole my heart completely does not support mongoDB and mongoose

thank you, please keep this project alive, we are counting on you

**Comment by RomainLanz** [comment]
Hey @dezashibi !

Adonis will not support MongoDB.

You can still use the package [adonis-mongorito](https://github.com/allanfreitas/adonis-mongorito) written by @allanfreitas.

**Related Issue**

- [Votes for official support by Adonis for MongoDB](https://github.com/adonisjs/adonis-framework/issues/300)
- [support for mongodb](https://github.com/adonisjs/adonis-framework/issues/215)
- [How to Integrate With MongoDB?](https://github.com/adonisjs/adonis-framework/issues/213)
- [Can we have mongoDB support too?](https://github.com/adonisjs/adonis-framework/issues/103)
- [Support for document based databases?](https://github.com/adonisjs/adonis-lucid/issues/9)
- [support for nosql?](https://github.com/adonisjs/adonis-lucid/issues/11)

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by jay-jlm** [comment]
2018 update: a quick google/npm search revealed quite a few community projects related to this subject.
Here's a couple of them:
https://github.com/duyluonglc/lucid-mongo
https://medium.com/@juampi92/mongoose-models-with-the-mighty-adonis-js-715cd83b923f
