### ISSUE TITLE
Add the whereHas functionality to Lucid which exists in Laravel/Eloquent

### ISSUE THREAD

**Issue by KungWaz** [adonisjs/adonis-framework#427]
It would be nice to be able to filter the top level rows when querying models with relations.

If I have this structure:
`office: {
  orders: [{
    items: [{
      status: 'p'
    }, {
      status: 'c'
    }]
  },{
    items: [{
      status: 'd'
    }]
  }]
  },{
    items: [{
      status: 'd'
    }]
  }]
  }]]
}`

I want to get this result:
`office: {
  orders: [{
    items: [{
      status: 'p'
    }, {
      status: 'c'
    }]
  }]]
}`

But at the moment I can only accomplish this:
`office: {
  orders: [{
    items: [{
      status: 'p'
    }, {
      status: 'c'
    }]
  },{
    items: []
  }]
  },{
    items: []
  }]
  }]]
}`

I use the query builder with scoping:
`const office = yield Office
  .query()
  .with('orders.items')
  .where('id', officeId)
  .scope('orders.items', (builder) => {
    builder.whereNot('status','d')
  })
  .first()`

It would be nice to use a whereHas function here to be able to only get Orders that have OrderItems.

This request is related to this question on SO:
http://stackoverflow.com/questions/41679272/is-it-possible-to-do-a-nested-query-builder-in-adonisjs-with-lucid/41715041#41715041

**Comment by thetutlage** [comment]
Closed and moved to https://github.com/adonisjs/adonis-lucid/issues/92
