### ISSUE TITLE
502 (Bad Gateway)

### ISSUE THREAD

**Issue by lukaszflorczak** [adonisjs/adonis-framework#428]
First, I'm sorry if it's not good place for this issue, but I didn't find a working solution nowhere else. 

I have an app based on latest version of Adonis, and it works great on localhost. 
Yesterday I was tried to run it on Heroku. After many other problems it was working, but only home page. Any request to api returns 502 error (Bad Gateway). Because I was a lot problems with Heroku before, I uploaded it to DigitalOcean. But there is the same problem...

It is my routes.js file:

```
const Route = use('Route')

Route.group('api', function () {
    Route.get('/places/:ne_lat,:ne_lng::sw_lat,:sw_lng', 'PlaceController.index').formats(['json'])
}).prefix('/api/v1')

Route.get('*', function *(request, response) {
    yield response.sendView('app')
})
```

I'm now not sure there is something wrong with my Route (or other app configuration) or with server... Thank you for any help.

**Comment by RomainLanz** [comment]
Hey @lukaszflorczak !

Erreur 502 isan error created by the proxy that Heroku use (Nginx, Apache, ...).
You may verify logs of the system.

Note that you have an error in your code, it misses a comma into your api route.

```
/places/:ne_lat,:ne_lng::sw_lat,:sw_lng
```

should be

```
/places/:ne_lat,:ne_lng:,:sw_lat,:sw_lng
```

**Comment by lukaszflorczak** [comment]
OK... Next I has 503 errors, and finally it works on Heroku. .env was in .gitignore and then Heroku try to use sqlite3 instead of mysql.

I removed .env from .gitignore and removed PORT and HOST from .env. 

---

@RomainLanz I thnik my Route is ok. I call it like this:
```/api/v1/places/50.12,19.01:54.56,24.48```
First I have NE coordinates (lat,lng) and next, after colon char, SW coordinates (lat,lng).

**Comment by RomainLanz** [comment]
> I removed .env from .gitignore

You `.env` file should never be in any VCS becasue of security risk. You should create you own `.env` file for each environement. Now you may remove it an rewrite all the history of your repository to remove any trace of `.env`.

> I thnik my Route is ok. I call it like this:

Yeah, I missread :D

**Comment by lukaszflorczak** [comment]
I pushed all files to Heroku by git and .env file wasn't uploaded (it was in .gitignore probably by default in Adonis) before. So now, when it is on Heroku I want to modify .env and adapt it to my local enviroment and then add it again to .gitignore file. Do you think it is a correct way?

**Comment by RomainLanz** [comment]
No, you need to rewrite the history of your repository.

--> https://help.github.com/articles/removing-files-from-a-repository-s-history/
