### ISSUE TITLE
Any guidelines for authentication?

### ISSUE THREAD

**Issue by keeross** [adonisjs/adonis-framework#43]
Very exited about v2. amazing work and massive amount of cool ideas. 
Are there any guidelines for authentication? 
Or maybe some ways to integrate Passport based on connect?

**Comment by niallobrien** [comment]
The first place I'd look is using the Hashing service provider in a custom auth middleware.

**Comment by thetutlage** [comment]
creating a middleware for auth will be best approach. After redis, mail and events my next task is to have an authentication provider.
