### ISSUE TITLE
Editorconfig causes "issues"

### ISSUE THREAD

**Issue by levrik** [adonisjs/adonis-framework#431]
Hey there. The editorconfig forces LF as line-endings but on Windows Adonis generates the boilerplate app with CRLF as line-endings. I'm using Visual Studio Code and it changes the line-endings to LF on every file that I open. It's quite annoying.

**Comment by thetutlage** [comment]
Delete `.editorconfig` file

**Comment by thetutlage** [comment]
Closing since not actionable
