### ISSUE TITLE
Adonis Not allowing website contents as Frame from Another Website

### ISSUE THREAD

**Issue by yogeshwaranManoharan** [adonisjs/adonis-framework#432]
I'm having a domain and trying to forward it to IP where Adonisjs is running but its not showing the content

**Comment by yogeshwaranManoharan** [comment]
What is the procedure for Enabling Iframe for a certain domain

**Comment by thetutlage** [comment]
Issue title and description are so different. If it's only about the iframe then you need to change a setting inside the `config/shield.js` file

Set `X-FRAME=ALLOW`

**Comment by yogeshwaranManoharan** [comment]
Let me check please wait

**Comment by yogeshwaranManoharan** [comment]
Worked Perfectly. Instead if X-FRAME=ALLOW i used ALLOW-FROM http://mysite.com. 

Thank you !

**Comment by yogeshwaranManoharan** [comment]
But one thing is that the desktop content shows on the mobile instead of bootstrap responsive site, why is that?
