### ISSUE TITLE
Ace : TypeError Path must be a string. Received undefined

### ISSUE THREAD

**Issue by NicolasBouhours** [adonisjs/adonis-framework#433]
Hi
I've create new project on my computer, it works perfectly and i can do my migration ... with ace command.
Now try to start new project on my laptop and i can't run any ace command.

I have : TypeError Path must be a string. Received undefined

My two computers are using windows 10 and node -v 6.9.4.
I think that issue come from my ace file, but i don't know why, it's the same.

```
#!/usr/bin/env node
'use strict'
/*
|--------------------------------------------------------------------------
|   Running Console Commands
|--------------------------------------------------------------------------
|
|  Here we invoke console commands registered under Ace store.
|
*/
const kernel = require('./bootstrap/kernel')
kernel()
```

Any idea ? 
Thank's

**Comment by RomainLanz** [comment]
Hey @NicolasBouhours !

It's probably an error in the latest version of `adonis-command`. I have pointed out a portion of the code that may cause the error.

**Comment by NicolasBouhours** [comment]
Any idea how can i fix it :) ?

**Comment by thetutlage** [comment]
Downgrade adonis-commands to 2.1.3

**Comment by NicolasBouhours** [comment]
It works perfectly with the downgrade. Thank's !
