### ISSUE TITLE
Controller and timeouts

### ISSUE THREAD

**Issue by kyuz0** [adonisjs/adonis-framework#434]
Hi,

I have a controller for an AJAX request that takes a long time to process and return to the browser. What I am observing is that, before the controller has a chance to end, the ajax request fails with 'net::ERR_EMPTY_RESPONSE' on the client (jquery client-side).

Now, I originally thought this was an issue with timeouts client-side, but I have increased that and I still get this empty response.

Might it be that Adonis is imposing a server-side maximum limit on requests after which it simply fails and returns an empty answer (which would explain the error message as Jquery cannot parse that as JSON).

Cheers,
Donato

**Comment by thetutlage** [comment]
1. What's the url you are calling from Ajax?
2. Howz your routes.js file?
3. Are you making the response via the controller method for the given route?

**Comment by kyuz0** [comment]
Url: 
- http://localhost:3333/test

Route:
Route.get('/test', 'TasksController.test')

Controller:

* test (request, response) {
      setTimeout(function() {
        response.json({ok:'ok'})
      }, 120000)
  }

The setTimeout() simulates a longer call. if I go with 1 minute, everything works and I get the ok JSON response. I got with 2 minutes, and things break.

On a similar note, I'm confused on the usage of async functions with callbacks within a generator, not sure if that's the right way of doing it.

**Comment by thetutlage** [comment]
Why do you want to make the request wait for 2minutes?

**Comment by kyuz0** [comment]
Im using setTimeout() here just as an example. I'm performing a task that takes several minutes to return, the time it takes is not really under my control.

**Comment by thetutlage** [comment]
Http server in Node.js has a timeout, you can disable it or set it to higher value. https://nodejs.org/api/http.html#http_server_timeout

## How to do it in Node.js
You can do it get the access to the raw HTTP server inside `Listeners/Http.js` file.https://github.com/adonisjs/adonis-app/blob/develop/app/Listeners/Http.js#L40

```javascript
const Server = use('Adonis/Src/Server')

Server. getInstance().timeout = 0
```

**Comment by kyuz0** [comment]
That did the trick. Thanks a lot!

I'm really enjoying using AdonisJS and I'm new to Javascript really, so enjoying learning a new language as well. Still getting my head around the callback and asyc-based nature of the language, can certainly appreciate generators a lot!

A question: I understand in order to use generators you need a sort of generator runner, which is going to call next and so on... what do you use in AdonisJS? And how does that work when, from within a generator, you use a normal function with a callback?

**Comment by thetutlage** [comment]
@kyuz0 How async function works is a broad concept. I suggest you to join the gitter room and discuss about same.

Closing the issue since it works
