### ISSUE TITLE
Route questions

### ISSUE THREAD

**Issue by paulopmx** [adonisjs/adonis-framework#436]
Hey Guys,

I'm really excited about migrating my laravel project to adonisjs but I'm having some trouble finding documentations for the following issues:

1. Can I make multiple route files? Specially if I want to organize Route groups in their own files?

2. If I want a Route Group to redirect unauthenticated users, how do I go about it, middleware('auth') only seems to throw a 404 page.

**Comment by RomainLanz** [comment]
Hey @paulopmx !

Sorry for the delay of my answer.

> Can I make multiple route files? Specially if I want to organize Route groups in their own files?

Yes, you can split your routes between multiple route files. Then you need to require them into your main route files.

```javascript
'use strict'

const Route = use('Route')

require('./routes.frontend')
require('./routes.backend')
require('./routes.api')
```

> If I want a Route Group to redirect unauthenticated users, how do I go about it, middleware('auth') only seems to throw a 404 page.

You can create a `guest` middleware. I have created one in my [adonis-starter](https://github.com/RomainLanz/adonis-starter) kit.
https://github.com/RomainLanz/adonis-starter/blob/develop/app/Http/Middleware/RedirectIfAuthenticated.js
