### ISSUE TITLE
file upload issue. errno: -4037 code: "EXDEV"

### ISSUE THREAD

**Issue by eyeoftigers** [adonisjs/adonis-framework#438]
İ am trying to upload image but i always get the error.

`errno: -4037,
code: "EXDEV",
syscall: "rename",
path: "C:\Users\User~1.ISH\AppData\Local\Temp\upload_79c1e16bf2495246d9ba136ac6f19135",
dest: "D:\Projects\ppp\storage\WIN_20151011_17_45_53_Pro.jpg"`

i google and find that issue is with node js because moving files from different directory then project is not allowed by default. but i also i didn't find any configuration related to this.

**Comment by RomainLanz** [comment]
Hey @eyeoftigers !

Thanks for your report !

I will look into it soon.

**Comment by glevinzon** [comment]
how to apply the fix? @thetutlage

**Comment by thetutlage** [comment]
You have upgrade the version of `adonis-framework` to latest

**Comment by glevinzon** [comment]
@thetutlage 
![screenshot-apicapstone herokuapp com-2017-03-08-19-20-16](https://cloud.githubusercontent.com/assets/12289959/23702024/793db7ca-0434-11e7-9d52-98a612760825.png)
I can now successfully upload but accessing the file from the upload to the public directory doesnt seem working

**Comment by thetutlage** [comment]
Yes since, uploads directory is not publicly accessible. Checkout this example http://adonisjs.com/docs/3.2/security-introduction#_file_uploads

**Comment by glevinzon** [comment]
@thetutlage `uploads` directory is different from `public` folder/directory? or is that what you meant by uploads = public directory? anyway, how can I publicly access the file I uploaded? no way? can't be access absolutely? sorry for the noob question

**Comment by thetutlage** [comment]
The `public` directory is accessible by typing the url of the file, whereas any other directory is not. Also you should have share the actual link of uploaded files with the users.

The idea is to save the file to the `uploads` directory and save it's name inside a database column, then create a route where users can type the file id `/download/:id` and you look for the file name for that id and then download the file by using `response.download` method.

If you need even more help, I would suggest to talk about it in Gitter channel.
