### ISSUE TITLE
Array of inputs/files

### ISSUE THREAD

**Issue by andrasf** [adonisjs/adonis-framework#439]
Hi,

I also got issues like issue #303.

```
<input type="text" name="datas[]" value="one" />
<input type="text" name="datas[]" value="two" />
```

With `{{ form.open({action: 'TestController.index', files: false}) }}`
`console.log(request.input('datas'))` outputs `[ 'one', 'two' ]`

With `{{ form.open({action: 'TestController.index', files: true}) }}`
`console.log(request.input('datas'))` outputs `null`

With `{{ form.open({action: 'TestController.index', files: true}) }}`
When uploading array of files `request.file('files')` returns `null` but `request.file('files[]')` works, returns array.
Handling text values the same way: `request.input('texts')` returns `null` and `request.input('texts[]')` only returns the last value.

It seems like you can have multiple text values with `files: false` OR you can upload multiple files with `files: true` but you cannot have both in one form.

So it has to do with `multipart/form-data` params.

Is this considered as a bug? Also looks inconsistent.

**Comment by thetutlage** [comment]
Will try to re-produce this. If the behaviour is same, then it is a bug.

Ideally arrays should be accessed by referencing the normal field value. For example: `texts` should return the string or array, based upon what was sent by the client.

**Comment by m1ng-s** [comment]
Hi,
I got the same problem, I am trying to make a checkbox array
`{% for nutrition in nutritions %}`
`{% set checkbox = form.checkbox('nutritions[]', nutrition) %}`
`{{ form.label(nutrition, (checkbox + nutrition), {class: 'checkbox-inline'}) }}`						
`{% endfor %}`

with `files: true` in form open, result in form submit getting wrong:
'nutritions[]': 'nutritions4' which always return the last element with a key name having []

but if I remove `files: true` in form open, the result is fine:
 nutritions: [ 'nutritions1', 'nutritions2', 'nutritions3' ]

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-middleware#8

**Comment by thetutlage** [comment]
Try install `adonis-middleware` develop branch from Github. Feel free to report any issue regarding same

**Comment by harshdoshi999** [comment]
Hi, I am facing the same issue. If I use file type in form then email[] displays latest value only. How to solve this?

**Comment by harshdoshi999** [comment]
Neva mind, I installed adonis-middleware from dev branch and it worked.
