### ISSUE TITLE
Unexpected token when serving the app

### ISSUE THREAD

**Issue by dunkdunk** [adonisjs/adonis-framework#442]
After creating an app with the adonis-cli, I get the following error when running `npm run serve:dev`. The app creation process appeared successful. I'm running Node v4.3.1 and npm 3.10.9. Any ideas of what might be causing this?

```
> adonis-app@3.2.1 serve:dev /Users/mmmdunk/Web/yardstick
> nodemon --watch app --watch bootstrap --watch config --watch .env -x "node --harmony_proxies" server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/mmmdunk/Web/yardstick/app/**/* /Users/mmmdunk/Web/yardstick/bootstrap/**/* /Users/mmmdunk/Web/yardstick/config/**/* .env
[nodemon] starting `node --harmony_proxies server.js`
SyntaxError: Unexpected token [ 
 at /Users/mmmdunk/Web/yardstick/app/Listeners/Http.js (/Users/mmmdunk/Web/yardstick/app/Listeners/Http.js:1:1)
[nodemon] clean exit - waiting for changes before restart
```

**Comment by thetutlage** [comment]
Yup a known bug, would you mind commenting the usage of `youch` within this file. I will pushing the fix by tonight

**Comment by thetutlage** [comment]
Fixed everything with a proper test suite for windows too. You can upgrade youch to latest version

**Comment by dunkdunk** [comment]
It looks like you already fixed this, before I could get the `youch` output to you. Thanks!

**Comment by thetutlage** [comment]
👍 Closing
