### ISSUE TITLE
Can't use getter on timestamps() created_at and updated_at fields

### ISSUE THREAD

**Issue by andrewdelprete** [adonisjs/adonis-framework#444]
Creating a migration with `table.timestamps()` creates two fields `created_at` and `updated_at`. When I try to use a getter in my model to adjust the format of these two fields It doesn't work. It doesn't seem to support the underscore `_`.

```
  getCreatedAt (date) {
    return moment(date)
      .tz("America/Chicago")
      .format('ddd, MMM Do YYYY, h:mm:ss a');
  }
```

Should I use Computed Properties to format my timestamps or maybe rename my timestamp fields to something without an underscore like `createdAt` and `updatedAt` and use the getter? 

Thanks in advance!

**Comment by thetutlage** [comment]
The getters and setters on timestamps works a little different. Instead of using the field name, you make use of the identifier for that field.

Below one should work

```js
getCreateTimestamp (date) {
   return moment(date)
      .tz("America/Chicago")
      .format('ddd, MMM Do YYYY, h:mm:ss a');
}
```

Source code reference https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/Model/index.js#L514

**Comment by andrewdelprete** [comment]
Thank you @thetutlage !!
