### ISSUE TITLE
Event Listener Array

### ISSUE THREAD

**Issue by scsddeputy** [adonisjs/adonis-framework#446]
It would be benefitial if instead of having to define multiple closures for an event when we register a listener in the bootstrap/events file, we could just pass an array of listeners.

So instead of this:
`Event.when('event', 'listener')
Event.when('event', 'listener')
Event.when('event', 'listener')`

we can do something more like:
`Event.when('event', ['listener','listener','listener'])`

**Comment by thetutlage** [comment]
I will look into it in the upcoming releases, since it is a good to have feature

**Comment by thetutlage** [comment]
Added in 4.0 https://github.com/adonisjs/adonis-framework/blob/develop/src/Event/index.js#L157
