### ISSUE TITLE
Unable to run ace on Mac OSX 10.12.2

### ISSUE THREAD

**Issue by swethaphatke** [adonisjs/adonis-framework#447]
Hi,

I installed Adonis in my Mac, with node = v4.5.0, npm = 4.0.5, with yarn package. When I run ace for any operation, i am getting the following error. Running with flag --harmony_proxies also gives the same error. I am unable to run any commands. Please help.
`Error: proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag`
![error](https://cloud.githubusercontent.com/assets/13361927/22619043/943c57de-eb11-11e6-8e1f-9795b04e4ee3.png)

**Comment by RomainLanz** [comment]
Hey @swethaphatke !

Did you read the [documentation](http://adonisjs.com/docs/3.2/installation#_getting_proxies_error) ?

> Older versions of Node.js requires `--harmony_proxies` flag to add support for **ES2015 Proxies**. If you are using **Node.js < 6.0**, make sure to make following changes.
> ...

**Comment by thetutlage** [comment]
@swethaphatke You need to write `--harmony_proxies` on the first line of the `ace` file

**Comment by thetutlage** [comment]
Closing since not actionable
