### ISSUE TITLE
How to delete uploaded file?

### ISSUE THREAD

**Issue by bohdanz1997** [adonisjs/adonis-framework#450]
I send to controller file id, then i get from DB file name. Then i need to delete this file from the file system using 
`yield file.delete()`, where file - instance of Request.file class, how i can get this instance without request.file()?

**Comment by thetutlage** [comment]
`file.delete()` is used to delete the file from the `tmp` directory. If you want to remove files later from the saved directory. You should use the `fs` module for that

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by senocak** [comment]
I wonder how can i do that? I am facing the same problem.

**Comment by RomainLanz** [comment]
Use the native file system to do that aka `fs`.
