### ISSUE TITLE
create 2 or more directory for static file

### ISSUE THREAD

**Issue by mastito03** [adonisjs/adonis-framework#451]
is there any way to make additional directory beside public for static file?

use case is for compiled asset that need to be static file. but no need to uploaded as server can compile it.
public directory won't do as I often acidentaly mixed compiled file and normal one, and if I ignore it won't uploaded.

**Comment by thetutlage** [comment]
Create one inside `resources` directory called `resource/assets`

**Comment by mastito03** [comment]
ok thanks. I will try

**Comment by thetutlage** [comment]
Closing since not actionable
