### ISSUE TITLE
Events Not Properly Working | Silently discarding errors and Stops Execution

### ISSUE THREAD

**Issue by yogeshwaranManoharan** [adonisjs/adonis-framework#453]
I'm trying to fire events but after certain lines code doesn't work which is very peculiar. For Eg.

 `console.log("boool " + boolFirst); // this works`
 `let data = yield Post.all();`
 ` data = data.toJSON();`
 `console.log("Tasks Running" + data); // this works, after this nothing works`
 `let symbol = data[0]['id'];`
 `console.log("symbol" + symbol); // this doesn't work`

for the record im using https://www.npmjs.com/package/adonis-scheduler this library to fire events for every one minute, since there is no default task scheduler in adonis js. If there is please suggest.

**Comment by thetutlage** [comment]
How come events are not working, if you are able to log certain statements?

**Comment by yogeshwaranManoharan** [comment]
I've debugged the problem, it seems any error occurring on Events are discarded silently and execution stops in that instance. It's not reporting the errors.

**Comment by thetutlage** [comment]
@yogeshwaranManoharan In that case you need to create the issue with the author of the repo, since `adonis-scheduler` is not the official package
