### ISSUE TITLE
How to format field output for validator

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#454]
I've been searching through indicative and validator provider source for a while now, and I've come up with nothing. 

I'm looking to format the field name in a more user friendly fashion. 

For example;

first_name should display as "First Name" 

Whether I achieve this with some kind of mapping, or automatic parsing, I do not mind. Is there an easy way to achieve this today?

**Comment by thetutlage** [comment]
Indicative is validator and it does not format anything. You need to write your custom implementation to convert keys into human readable format.

**Comment by mikehhhhhhh** [comment]
For anyone else with the issue, I solved it like this;
`let messages = validation.messages();
messages.forEach((msg) => {
    let field = inflect.humanize(msg.field);
    msg.message = msg.message.replace(msg.field, field);
});`

It works, but it isn't very elegant. There should be a means to perform this sort of action on the {{field}} placeholder when building custom messages.

**Comment by thetutlage** [comment]
If it's just about the validation messages, you can better create getters for them and transform the field. Docs for getters here http://indicative.adonisjs.com/#indicative-basics-custom-messages

**Comment by thetutlage** [comment]
Closing since not actionable
