### ISSUE TITLE
Re-use hooks for different models

### ISSUE THREAD

**Issue by webdevian** [adonisjs/adonis-framework#457]
I have a slugify function, that I want to use as a beforeCreate hook on 4 different models.

I've tried lots of different ways to implement this without repeating myself but no matter how I try to define and then include the slug functionality (As a class, function or its own hook etc) but it is always undefined on the 2nd time I call it, as if the 1st hook is making it undefined

How should I do this so that my slugify function is available to more than one hook?

**Comment by webdevian** [comment]
I got it working by moving my slug.js file outside of the hooks directory. It would still be interesting to know what best practice for this is though?

**Comment by RomainLanz** [comment]
Hey @webdevian !

You may take a look at how @thetutlage is doing that in [adonis-rally](https://github.com/adonisjs/adonis-rally).

He registers a Service called [Slugify](https://github.com/adonisjs/adonis-rally/blob/develop/app/Services/Slugify.js) and then register it inside the model -> https://github.com/adonisjs/adonis-rally/blob/develop/app/Model/Question.js

**Comment by webdevian** [comment]
Thanks @RomainLanz, that makes a lot of sense, I didn't realise that hooks could be registered in services. I will have to study adonis-rally more!
