### ISSUE TITLE
Get user agent and Clientjs

### ISSUE THREAD

**Issue by dexmendonca** [adonisjs/adonis-framework#462]
How can i get the useragent header? And I can't use the module "clientjs" from [https://clientjs.org](https://clientjs.org)

this is my controller code:
```
class UaController {

  * index (request, response) {
	 
	  const ua = request.header('User-Agent')
	  console.log(ua);
   	  response.send('Look your log')
  }

}

module.exports = UaController
```

Thanks 😄

**Comment by thetutlage** [comment]
Does your request headers have `User-Agent` coz it works fine for me

**Comment by dexmendonca** [comment]
can you make one working example for me?
Do you have any configuration to do?

**Comment by dexmendonca** [comment]
Thanks
