### ISSUE TITLE
Error: "Top-level await is not available in the configured target environment"

### ISSUE THREAD

**Issue by patrickphat** [adonisjs/adonis-framework#4626]
### Package version

@adonisjs/core@6.12.1 

### Describe the bug

```
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/@adonisjs/core/build/services/hash.js:15:0:
      15 │ await app.booted(async () => {
         ╵ ~~~~~
```

### Reproduction repo
https://github.com/adonisjs/core/blob/ae657892c528bc10dc0149f4878135ca7053660b/services/hash.ts#L19-L21

**Comment by Julien-R44** [comment]
https://docs.adonisjs.com/guides/views-and-templates/inertia#top-level-await-is-not-available
