### ISSUE TITLE
E_UNDEFINED_METHOD: Method handle missing on App/Http/Middleware/RedirectLogin

### ISSUE THREAD

**Issue by harshdoshi999** [adonisjs/adonis-framework#463]
I am having this error when I am trying to access middleware:

'use strict'

class RedirectLogin {
  * handle (request, response, next) {
    const loggedIn = request.cookie('loggedIn');
		if(!loggedIn){
			response.route('login')
		}
  }
}

**Comment by RomainLanz** [comment]
What you are trying to do? It seems that you are doing the same thing that the Official `auth` middleware.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
