### ISSUE TITLE
Env with special characters

### ISSUE THREAD

**Issue by kevinmelo** [adonisjs/adonis-framework#4637]
### Package version

latest

### Describe the bug

Hello, i'm migrating my project to use Adonis6 + Typeorm, and i'm have a problema, don't know if is a bug or a 'normal' behavior.

My database password has a special characters, and i saw in a 2019 issue, that you need to escape (all good my sever is now up)
But if i try use the command `node ace migrate:show` that i create to use the Typeorm, i need to remove the scape, or it does not work. Both place use my `config/typeorm` file.

Thanks, and great project

**Comment by RomainLanz** [comment]
Hey @kevinmelo! 👋🏻 

We cannot help you with the amount of information you shared.
The best would be to share a repository with **the minimum amount of code** to reproduce your issue.

Also, you can still escape the `$` sign.

📚 https://docs.adonisjs.com/guides/getting-started/environment-variables#escaping-the--sign

**Comment by kevinmelo** [comment]
Thanks for the reply. I will close the issue and use like this. Maybe other will have the same problem in future.
