### ISSUE TITLE
 Error: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by riazXrazor** [adonisjs/adonis-framework#464]
i am getting this error when uploading a file, i googled a bit and found https://github.com/adonisjs/adonis-framework/issues/438 according to the thread its fixed and closed , apprently not isssue is still there.

**Comment by RomainLanz** [comment]
Hey @riazXrazor !

May you copy/paste the exact error you have?

**Comment by riazXrazor** [comment]
first of all thank you for the quick reply, 
i was fighting for an hour or two now having the same error, i update the File.js file from the repo too, but still got the same error, then i thought of creating an isssue, after that, saw your reply and re-run the code code to generate the error, but to my surprise it just uploaded no error nothing.

**Comment by RomainLanz** [comment]
Well, we will never know what was the problem! 😄 

Enjoy using Adonis.
