### ISSUE TITLE
Command don't closed after handling

### ISSUE THREAD

**Issue by enniel** [adonisjs/adonis-framework#465]
Screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/19760944/22866270/931d0492-f184-11e6-81ed-55776775fe60.png)

[Command code](https://gist.github.com/enniel/25264ea9b124697d72e95ef76aebad87)

**Comment by RomainLanz** [comment]
Hey @enniel !

I recommend you to take a look at this issue: https://github.com/adonisjs/adonis-framework/issues/227

Because you are fetching a Model with the database you need to manualy close the connection.

**Comment by enniel** [comment]
@RomainLanz Thanks!
