### ISSUE TITLE
Query Builder, Select Case Statement

### ISSUE THREAD

**Issue by rikad** [adonisjs/adonis-framework#466]
Hi, i have some project with adonis js, i love adonis cause it's very similar to laravel.

i wanted to write this query 

`SELECT id,name,form, CASE WHEN parent_id = 1 THEN id ELSE parent_id END AS sort FROM po_organizations ORDER BY sort`

is there ways to write raw query or is there any method to insert CASE statement on query builder ?

**Comment by thetutlage** [comment]
`Database.raw('YOUR QUERY')` should work

**Comment by rikad** [comment]
@thetutlage thank you verymuch :) ... it's worked
