### ISSUE TITLE
Remote websocket access

### ISSUE THREAD

**Issue by MaTiUs77** [adonisjs/adonis-framework#467]
Hello,

Im have adonis running with this env `HOST=localhost PORT=8081` on my server with the host 'ProductionServer'

The next client code is working good.
```
            const io = ws('http://localhost :8081', {});
            const client = io.channel('servermonitor')
            client.connect(function (error, connected) {
                if (error) {
                    console.log(error);
                    return
                }
                console.log('ServerMonitor Connected');
            });
```
The problem appears when i try to connect with a remote view, is the same code but changing the host..

`  const io = ws('http://ProductionServer:8081', {});`

The console.log returns this error

> /servermonitor,"Invalid namespace"

Can someone helpme with this please?

**Comment by thetutlage** [comment]
Can u reach your website as `http://ProductionServer:8081` by opening same in the browser?

**Comment by MaTiUs77** [comment]
In the server, where is running adonis, i attempting to access to the browser http://localhost:8081` and appears the adonis front view, then in the same machine i try to access to `http://ProductionServer:8081` and appears `ERR_CONNECTION_REFUSED` the same error trying to access from a remote view

:S

**Comment by thetutlage** [comment]
Yeah so it's not publicly available. I am not even sure how you got `ProductionServer` as the host

**Comment by MaTiUs77** [comment]
In my personal pc, with a fresh adonis install, i try to connect to `const io = ws('http://localhost :3333', {});` and works, then i try to connect with my public ip  `const io = ws('http://10.30.10.22:3333', {});`  and return xhr failed.

Do you know why?

**Comment by MaTiUs77** [comment]
i change the env configuration now is `HOST=ProductionServer PORT=8081`
The browser at ProducitonServer:8081 is working, 
the client to ` const io = ws('http://ProductionServer:8081', {});`

but still returning` /servermonitor,"Invalid namespace"`

**Comment by thetutlage** [comment]
Do you have the same `channel` on the server inside `socket.js` file?

**Comment by MaTiUs77** [comment]
This what i have, and works like a charm

**SERVER SIDE** 
ENV
```
HOST=localhost
PORT=8081
```

```
const Ws = use('Ws');
Ws.channel('/servermonitor', 'ServerMonitorController')
```
```

'use strict'
class ServerMonitorController {
	constructor (socket,request) {
		this.socket = socket;
		this.socket = request;		
		console.log("ServerMonitor client connected",socket.id);		
	}
		
	disconnected(socket) {
		console.log("ServerMonitor client disconnected",socket.id);
	}
}

module.exports = ServerMonitorController;
```

CLIENT SIDE
```
<script src="https://unpkg.com/adonis-websocket-client/dist/ws.min.js"></script>
<script>
const io = ws('localhost:8081', {});

const client = io.channel('servermonitor')
client.connect(function (error, connected) {
	if (error) {
		console.log(error);
		return
	}
	console.log('ServerMonitor Connected');
});

client.on('disconnect',function(){
	console.log('ServerMonitor Disconnected');
});
</script>
```
Running on browser the websockets returns `ServerMonitor Connected`
The server side is working good only when the browser url match with the HOST defined in .env.

**Browser test**
-  http://localhost:8081 Responding
-  http://ProductionServer:8081 Not Work
-  http://10.30.10.22:8081 Not Work

Now changing env HOST to `ProductionServer` and` const io = ws('ProductionServer:8081', {});`

**Browser test**
-  http://localhost:8081 Not Work
-  http://ProductionServer:8081 Responding 
-  http://10.30.10.22:8081 Works

Websockets is not connected, returns 

> /servermonitor,"Invalid namespace"

The same example is running on sailsjs and works, adonis is very good, i need only solve this issue

:(

**Comment by algha** [comment]
ws://localhost:3000 is working
but
ws://production.com:3000 is not working...
