### ISSUE TITLE
Failed to load url inertia/app/ssr.tsx (resolved id: inertia/app/ssr.tsx). Does the file exist?

### ISSUE THREAD

**Issue by elguarir** [adonisjs/adonis-framework#4670]
### Package version

@inertiajs/react@1.2.0

### Describe the bug

This is the default inertia template with react + ssr, i didn't change anything.

![image](https://github.com/user-attachments/assets/c12db4af-b364-4cf1-8647-802a72576c3b)

- ERROR (21520): Failed to load url inertia/app/ssr.tsx (resolved id: inertia/app/ssr.tsx). Does the file exist?
this is the error i get after building the application using `npm run build && cd build && npm i && node bin/server.js`

when running the development environment everything works fine.

any help please, this is the first time I'm trying Adonis!

**Comment by RomainLanz** [comment]
Hey @elguarir! 👋🏻 

You forgot to run your server in production mode.

```sh
NODE_ENV=production node bin/servers.js
```

📚 https://docs.adonisjs.com/guides/views-and-templates/inertia#why-my-production-build-is-not-working-

**Comment by elguarir** [comment]
@RomainLanz Thanks man it works now 🙌🙏
