### ISSUE TITLE
.env files for different node environments are not working

### ISSUE THREAD

**Issue by m-i-c-h-a-l** [adonisjs/adonis-framework#4671]
### Package version

6.12.1

### Describe the bug

I followed instructions in https://docs.adonisjs.com/guides/getting-started/environment-variables#environment-variables and created a .env.development file.  
My .env file:
```
TZ=UTC
PORT=3333
HOST=localhost
LOG_LEVEL=info
APP_KEY=xxxxxxxxxxxxxxxx
NODE_ENV=development
```

My .env.development file:
```
DB_HOST=postgres
DB_PORT=5432
DB_USER=root
DB_PASSWORD=password
DB_DATABASE=test
```

Result: server startup failed on this error:
Missing environment variable "DB_HOST"
...

Also .env.development.local is not working, but renaming to .env.local works. (not a workaround)

Expected result:
As written in docs .env.development and .env.development.local should be accepted and loaded.

P.S. 
Hot redeploy is not working for all alternatives - .env.local, .env.development and .env.development.local

**Comment by thetutlage** [comment]
Make sure to start your server by pre-defining the `NODE_ENV=development`, ie

```
NODE_ENV=development node ace serve --hmr
```

**Comment by m-i-c-h-a-l** [comment]
Thank you, you are right. This should be mentioned in the documentation.
