### ISSUE TITLE
Do not use TypeScript features that require transformation (features that doesn't exist in JavaScript) like experimentalDecorators

### ISSUE THREAD

**Issue by theoludwig** [adonisjs/adonis-framework#4687]
### Package version

6.12.1

### Describe the bug

Adonis uses TypeScript features that require transformations, notably Decorators and we must use in `tsconfig.json`:
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

It would be better if Adonis only use TypeScript for types annotations and only use JavaScript features otherwise.
IMO, but that's for another debate, Enums, namespace, decorators should have never existed in first place in TypeScript if it doesn't exist in JavaScript.

Notably, Node.js v22.6.0 added (as experimental, but still worth to already point out), a new CLI option, `--experimental-strip-types` to run natively TypeScript code without a build step or using `ts-node`/`tsx`.
But it only removes inline types (for a good reason, and is a good design choice IMO).
Ref: https://nodejs.org/docs/latest/api/typescript.html

Somewhat related, the default starter kits are using `ts-node`, but it has several bugs, is not well maintained, requires a complex setup (at least more complex than alternatives) for good perf, like the setup with SWC, it should be a lot better to use something like `tsx`: https://tsx.is/

**Comment by thetutlage** [comment]
> It would be better if Adonis only use TypeScript for types annotations and only use JavaScript features otherwise.
IMO, but that's for another debate, Enums, namespace, decorators should have never existed in first place in TypeScript if it doesn't exist in JavaScript.

Seems like a philosophical mis-match and we can hardly act upon it. We use decorators in many places and have plans to continue doing that.

> Somewhat related, the default starter kits are using ts-node, but it has several bugs, is not well maintained, requires a complex setup (at least more complex than alternatives) for good perf, like the setup with SWC, it should be a lot better to use something like tsx: https://tsx.is/

We do not use `tsx` because it does not 100% match the module resolution from Node.js. You need to specify the file extension with imports in Node and `tsx` allows for file imports without any extensions as-well.

Now this can be problematic in following scanerio.

- You have an import with any file extension and that just works fine in development.
- Now you create a production build and the same import stops working from the JavaScript output.

**Comment by RomainLanz** [comment]
And on top of that, decorators are part of the ECMAScript spec.

The only reason we keep using the one from TypeScript is that we need the metadata extracted for Dependency Injection.

**Comment by theoludwig** [comment]
Thank you for the fast answers on the issues I created. :smile:

> We do not use tsx because it does not 100% match the module resolution from Node.js. You need to specify the file extension with imports in Node and tsx allows for file imports without any extensions as-well.
>
> Now this can be problematic in following scanerio.
>
> You have an import with any file extension and that just works fine in development.
Now you create a production build and the same import stops working from the JavaScript output.

Yes that's why I don't like building my code, if it is not necessary as it can create weird behavior mismatch between development and production, and it's better if the 2 environements are as much as possible the same.
For client side, it's better to build, bundle, etc. for minification, but for server side in Node.js, not needed, I'm using `tsx` for both my developement and production.

About file extension, even if I'm using `tsx`, I'm still using the file extensions in the imports, and there are ESLint rules to enforce that.

So it is not on the roadmap to make Adonis work with the `--experimental-strip-types` CLI option of Node.js, one day, if it doesn't support experimental decorator?
