### ISSUE TITLE
Angular2 integration

### ISSUE THREAD

**Issue by Enethion** [adonisjs/adonis-framework#470]
When I found AdonisJS my first thought was "FINALLY!", but right after I tried creating SPA project with Angular2 my enthusiasm was crushed into pieces.

Since Ng2 is available only via NPM (or third-party script hosting services) it has to residue in `node_modules`. But making it accessible in rendered page seems kinda weird. I might be missing something, but the only way I found was creating route that would catch anything from domain.my/node_modules/* and respond with download of requested file, since `<script>` tag with path like `../node_modules` won't work (which is actually good), but then my console get's spammed with:
`(node:8764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 490): Error: Can't set headers after they are sent.`

Is there any better way of doing it? [ I might be awkwardly weak in searching ;) ]

**Comment by RomainLanz** [comment]
Hey @Enethion !

Why not creating your Angular2 inside the `resource/assets` folder and then compiling it with an assets bundler like Webpack/Laravel-Mix?

**Comment by Enethion** [comment]
Gosh, it's so obvious... Please don't kill me...
