### ISSUE TITLE
AdonisJs version

### ISSUE THREAD

**Issue by imranhou** [adonisjs/adonis-framework#471]
Thank you for all your work on Adonis - After comparing to other frameworks, I'm liking it more and wanted to give it a try but had a question on the AdonisJs version.
Documentation at http://adonisjs.com/docs/3.2/adonis-blog-part1 refers to version 3.2
But the versions here (at least the tags in github) only go as far as 3.0.9

How can I get version 3.2 of Adonis?

**Comment by RomainLanz** [comment]
Hey @imranhou !

The documentation version refer to the [adonis-app](https://github.com/adonisjs/adonis-app) package.

You can have the latest stable release by using the [adonis-cli](https://github.com/adonisjs/adonis-cli) tool.

**Comment by imranhou** [comment]
Hey !
That answers my question, thanks for a quick reply.
