### ISSUE TITLE
Dev server not reachable with ipv4

### ISSUE THREAD

**Issue by jeppester** [adonisjs/adonis-framework#4713]
### Package version

6.9.1

### Describe the bug

I spent more time than I'm willing to admit on debugging why the dev-server was not reachable with my firefox browsers. Eventually I discovered that I had disabled ipv6.

To replicate the issue:
```sh
➜ ~ npm init adonisjs@latest

> npx
> create-adonisjs


     _       _             _         _ ____  
    / \   __| | ___  _ __ (_)___    | / ___| 
   / _ \ / _` |/ _ \| '_ \| / __|_  | \___ \ 
  / ___ \ (_| | (_) | | | | \__ \ |_| |___) |
 /_/   \_\__,_|\___/|_| |_|_|___/\___/|____/ 
                                             

❯ Where should we create your new project · ./my-adonisjs-app
❯ Which starter kit would you like to use · Slim Starter Kit
❯ Download starter kit (1.14 s)
  Downloaded "github:adonisjs/slim-starter-kit"
❯ Install packages (1.4 min)
  Packages installed using "npm"
❯ Prepare application (856 ms)
  Application ready

╭──────────────────────────────────────────────────────────────────╮
│    Your AdonisJS project has been created successfully!          │
│──────────────────────────────────────────────────────────────────│
│                                                                  │
│    ❯ cd my-adonisjs-app                                          │
│    ❯ npm run dev                                                 │
│    ❯ Open http://localhost:3333                                  │
│    ❯                                                             │
│    ❯ Have any questions?                                         │
│    ❯ Join our Discord server - https://discord.gg/vDcEjq6        │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯
➜ ~ cd my-adonisjs-app
➜ ~ npm run dev
[ info ] starting HTTP server...
╭──────────────────────────────────────────────────╮
│                                                  │
│    Server address: http://localhost:3333        │
│    Watch Mode: HMR                               │
│    Ready in: 242 ms                              │
│                                                  │
╰──────────────────────────────────────────────────╯
[09:57:39.759] INFO (760386): started HTTP server on localhost:38769
```

Then in another terminal:
```sh
➜  ~ curl -6 http://localhost:3333
It works!%
➜  ~ curl -4 http://localhost:3333
curl: (7) Failed to connect to localhost port 3333 after 0 ms: Couldn't connect to server
```

Is this the intended behaviour?

**Comment by thetutlage** [comment]
Isn't this something to do with the network than the framework? Or what do you recommend to change to fix it?

**Comment by thetutlage** [comment]
Btw, the `http://localhost:38769` is the Vite address

**Comment by jeppester** [comment]
> Isn't this something to do with the network than the framework? Or what do you recommend to change to fix it?

I would have expected the same, but I build websites for a living and I haven't had issues with connecting to other dev servers also on localhost.

I've just checked two (nextjs and rails) projects, and they connect without issues.

I can however replicate the issue with the `https-server` npm package:
```sh
npx http-server -a localhost .
```

So the web server plays some sort of role.

> Btw, the `http://localhost:38769` is the Vite address

38769 was selected automatically because I already had a non-fresh adonis project running on 3333.
I've just confirmed that the problem is the same for 3333 - and so updated the issue description.

**Comment by RomainLanz** [comment]
Is your `HOST` environment variable configured as `localhost` or `127.0.0.1`?

Also, can you please run the following command and share the output? `nslookup localhost`

and finally, ensure the following is inside your `hosts` file:

```
127.0.0.1       localhost
::1             localhost
```

**Comment by jeppester** [comment]
`.env.development`:
```sh
HOST=localhost
```

`nslookup`:
```sh
➜ nslookup localhost
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	localhost.home
Address: 127.0.0.1
```

`/etc/hosts`:
```txt
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by jeppester** [comment]
Interestingly, if I comment out `::1` from my `/etc/hosts`, I'm able to connect with `curl -4 http://localhost:3333`, but obviously not with ipv6.

It would seem to me that adonis listens to ipv6 by default, then falls back to ipv4, whereas nextjs and rails listens to both, if available.

**Comment by jeppester** [comment]
After further digging I've come to the conclusion that calling `server.listen([port], 'localhost')` on an "http.Server" will only listen on ipv6, at least on my machine - unless I remove `::1` from my `/etc/hosts`

The reason that nextjs works is that it does not specify a host by default. So the nextjs server will listen on `::` and due to dual stack support (I think) also on `0.0.0.0`.  I think this is bad practice as it makes the dev-server available on the network. If I set the host to 'localhost', nextjs behaves just like adonisjs.

I still think it's odd that nodejs will not listen on both ipv4 and ipv6, and that it would be better to listen on both adresses, but it's really not an adonisjs issue.

I apologize for having you waste time on this

**Comment by thetutlage** [comment]
No worries. I will close the issue then :)
