### ISSUE TITLE
Websocket controller crash on client connection

### ISSUE THREAD

**Issue by NanoEdit** [adonisjs/adonis-framework#472]
I start making socket controller 
```
'use strict'

class SearchController {

    constructor (socket) {
        this.socket = socket
    }

    onSearch (message) {
        console.log(message);
    }

}
```

but it app crash on client connection

```
TypeError: this._closure is not a constructor
    at ExtendedChannel.LifeCycle._onConnection (D:\WebFindByPhone\node_modules\adonis-websocket\src\Channel\Mixins\LifeCycle.js:31:27)
    at Namespace.Channel.io.on (D:\WebFindByPhone\node_modules\adonis-websocket\src\Channel\index.js:123:47)
    at emitOne (events.js:96:13)
    at Namespace.emit (events.js:188:7)
    at Namespace.emit (D:\WebFindByPhone\node_modules\socket.io\lib\namespace.js:209:10)
    at D:\WebFindByPhone\node_modules\socket.io\lib\namespace.js:177:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Using adonis 3.2.1 and node v6.9.5

**Comment by thetutlage** [comment]
Do u export searchcontroller via module.exports?

**Comment by NanoEdit** [comment]
No, should I ?

**Comment by RomainLanz** [comment]
Yes, you need to export the module so it will be imported when you require the file.

I recommend you to read that: https://www.sitepoint.com/understanding-module-exports-exports-node-js/

**Comment by NanoEdit** [comment]
Thanks a lot.

**Comment by lmj0011** [comment]
I ran into this same issue. The full code example should be included in the docs. A lot of new devs will most likely follow the guide verbatim and forget about the `module.exports = SomeController` at the end of the file. 

http://adonisjs.com/docs/3.2/websocket

**Comment by thetutlage** [comment]
@lmj0011 Even if I will put the effort to update all examples have module.exports, something else will break.

It is more about getting familiar to Node.js in general. This looks to me like

> Why PHP examples does not have starting `<?php` tag.

**Comment by lmj0011** [comment]
`<?php` in PHP is more of generally knowledge than `module.exports = SomeController` I would say.

`<?php` is always need in a PHP script.

However, I get your point though

**Comment by thetutlage** [comment]
How can u use a module without `module.exports` even if you get out of AdonisJs app?

**Comment by lmj0011** [comment]
`node somescript.js` 

the `somescript.js` could be not export anything
