### ISSUE TITLE
Validating Arrays Bug

### ISSUE THREAD

**Issue by poorcoder** [adonisjs/adonis-framework#473]
Hi @thetutlage  

Thanks for your hard work. I am using Laravel and I like it soo much but I like your work too.

I am watching your video at youtube and learning the Adonis ( thnks for them too, pls keep them with better sound its hard to listen & and lower resolution )

I found a bug on Validation module  at this video you are telling about.
When we have form for multiple user form and if user gives us same info it passes the validation we get duplicate users at database...

 ( https://www.youtube.com/watch?v=4MB0_X1fm5k )

Thanks for all...

Mustafa

**Comment by thetutlage** [comment]
Cannot help much without any code to reproduce the issue

**Comment by thetutlage** [comment]
Closing since no response from issue reporter
