### ISSUE TITLE
Allow to set up global layout

### ISSUE THREAD

**Issue by howardEagle** [adonisjs/adonis-framework#474]
It would be great if in locals we'd have ability to setting up global layout instead of write every time 
`{%extends 'master' %}` in each view.

**Comment by thetutlage** [comment]
Not sure how much difference it will make. You will save 1 line but removes the transparency/clarity from your code, since anyone looking at the has no idea from where it is getting the base markup and have to look into the config file to find out the reason.

**Comment by howardEagle** [comment]
Maybe store layout in locals is not great idea. For example PHP framework Yii2 rendering flow:
![image](https://cloud.githubusercontent.com/assets/3662421/23066589/ff95f28a-f523-11e6-8533-320f55404856.png)

**Comment by thetutlage** [comment]
Yup it is better to be explicit. Closing the issue

**Comment by howardEagle** [comment]
Ok, suppose I have a view "login" and I want to use it in the modal popup and in a single page. 
It would be pretty simple if we can pass some param to view, that disable or include other layout:
`response.sendView(`login`, {layout: false})
response.sendView(`login`, {layout: 'empty'}) `

**Comment by RomainLanz** [comment]
Hey @howardEagle !

So it will be the same than defining your master layout inside your view.
This is how Nunjucks works.

**Comment by smezae** [comment]
Hi, i'm looking the docs and can't understand very good the layout system (I'm coming from RoR)

Just out of curiosity, there is a possibility that the layouts may be somehow similar to how rails do it; a default layout, and specify, if necessary ... another in particular within the controllers?
