### ISSUE TITLE
yield  Unexpected token

### ISSUE THREAD

**Issue by wuxiangwa** [adonisjs/adonis-framework#477]
static generateReward() {
        const rooms = yield Room  
            .query()
            .with('distributor')
            .with('rewards')
            .with('room_users')
            .fetch();
        return 1;
    }

err:
/Applications/XAMPP/xamppfiles/htdocs/n2_h5_wechat_20170209/server/app/Util/RewardUtil.js:10
        const rooms = yield Room
                            ^
ParseError: Unexpected token 
 at /Applications/XAMPP/xamppfiles/htdocs/n2_h5_wechat_20170209/server/app/Listeners/Http.js (/Applications/XAMPP/xamppfiles/htdocs/n2_h5_wechat_20170209/server/app/Listeners/Http.js:1:1)

**Comment by betaWeb** [comment]
Hi,

try with var keyword instead of const ?

**Comment by RomainLanz** [comment]
Hey @wuxiangwa !

You get this error because you are trying to use `yield` inside a normal function. `yield` can only be used inside a generator function.

You may change your code with something like

```js
static * generateReward() {
  const rooms = yield Room
    .query()
    .with('distributor')
    .with('rewards')
    .with('room_users')
    .fetch();
  return 1;
}
```

**Comment by wuxiangwa** [comment]
thank you,the problem solved!
