### ISSUE TITLE
Support for Node v22 and up

### ISSUE THREAD

**Issue by psalkowski** [adonisjs/adonis-framework#4771]
### Package version

6.14.1

### Describe the bug

After upgrade NodeJS to latest version (v23), AdonisJS throws error during startup 

```
   SyntaxError: Unexpected identifier 'assert'
 
   at (syntax error) SyntaxError: Unexpected identifier 'assert'
```

I don't have any imports with `assert` directive. NodeJS removed `assert` and replaced it with `with` directive after v22.

```
  "devDependencies": {
    "@adonisjs/assembler": "^7.8.2",
    "@adonisjs/eslint-config": "^1.3.0",
    "@adonisjs/prettier-config": "^1.4.0",
    "@adonisjs/tsconfig": "^1.4.0",
    "@japa/api-client": "^2.0.3",
    "@japa/assert": "^3.0.0",
    "@japa/plugin-adonisjs": "^3.0.1",
    "@japa/runner": "^3.1.4",
    "@swc/core": "1.7.26",
    "@types/lodash-es": "^4",
    "@types/luxon": "^3.4.2",
    "@types/node": "^20.14.9",
    "@types/uuid": "^10",
    "eslint": "^9.13.0",
    "hot-hook": "^0.3.1",
    "prettier": "^3.3.3",
    "ts-node": "^10.9.2",
    "typescript": "~5.6.3"
  },
  "dependencies": {
    "@adonisjs/auth": "^9.2.3",
    "@adonisjs/core": "^6.14.1",
    "@adonisjs/cors": "^2.2.1",
    "@adonisjs/lucid": "^21.3.0",
    "@adonisjs/transmit": "^2.0.2",
    "@vinejs/vine": "^2.1.0",
    "cheerio": "^1.0.0",
    "csv-parse": "^5.5.6",
    "lodash-es": "^4.17.21",
    "luxon": "^3.5.0",
    "mysql2": "^3.11.3",
    "pino-pretty": "^11.3.0",
    "reflect-metadata": "^0.2.2",
    "socket.io": "^4.8.0",
    "uuid": "^10.0.0"
  },
```

**Comment by RomainLanz** [comment]
Hey @psalkowski! 👋🏻 

We're already compatible with the latest version of Node.js.

Could you share the command you're running that's causing this error?

**Comment by psalkowski** [comment]
Regular `yarn dev`. I had earlier import json file with `assert`, but replaced it `with`. Does adonis have some build cache that I'm not aware of?

`yarn dev` is an alias for `node ace serve --hmr`

**Comment by RomainLanz** [comment]
Are you able to share a repository with the minimum amount of code to reproduce the issue?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by psalkowski** [comment]
It looks like that the differences that I had based on new starter app are:
- lib `ts-node` has been changed to `ts-node-maintained` (also ace.js has different reference to it)
- lib `@adonisjs/eslint-config` is using beta version on starter app: `^2.0.0-beta.6`, while I had `^1.3.0`.
- lib `pino-pretty` was missing on my application - not sure if needed

After these two changes, `yarn dev` works fine.
