### ISSUE TITLE
validate query also in validateUsing function

### ISSUE THREAD

**Issue by mohitxskull** [adonisjs/adonis-framework#4779]
### Package version

6.12.1

### Describe the bug

The `validateUsing` doesn't validate `query`

`modules/http/request_validator.ts`
 ```ts
     const data = validatorOptions.data || {
      ...this.#ctx.request.all(),
      ...this.#ctx.request.allFiles(),
      params: this.#ctx.request.params(),
      headers: this.#ctx.request.headers(),
      cookies: this.#ctx.request.cookiesList(),
    }
 ```
 
Is there any specific reason to not do this?

**Comment by RomainLanz** [comment]
Hey! 👋🏻 

Query strings are inside the `request.all()` object.

**Comment by mohitxskull** [comment]
Thank you @RomainLanz for the quick response

So if i wanna validate `querys` i can write my vine schema like i write for body?

```ts
vine.compile(
 vine.object({
  page: vine.number().optional(),
 })
)
```

**Comment by mohitxskull** [comment]
Thank you @RomainLanz  for the quick response. Sorry for unnecessarily opening the issue.

**Comment by RomainLanz** [comment]
> Thank you @RomainLanz for the quick response
> 
> So if i wanna validate `querys` i can write my vine schema like i write for body?
> 
> ```ts
> vine.compile(
>  vine.object({
>   page: vine.number().optional(),
>  })
> )
> ```

Yes!
