### ISSUE TITLE
Send data to view

### ISSUE THREAD

**Issue by betaWeb** [adonisjs/adonis-framework#478]
Hi there,

I would like to know if the way I send data to my view is correct ?

Controller :
`* show (req, res) {`
`  const id = req.param('id')`
`  const post = yield Post.findOrFail(id)`
`  yield res.sendView('posts.show', { post: post.toJSON() })`
`}`

View : 
`<h1>{{ post[0].name }}</h1>`
`<p>{{ post[0].content }}</p>`

Is there a way to avoid "[0]" and send directly the entity and not have to get post value with "[0]" ?

Thx a lot :)

**Comment by RomainLanz** [comment]
Hey @betaWeb !

If you want only to have one record you need to use the method `firstOrFail`.

**Comment by thetutlage** [comment]
It is always return a single record. Would you mind sharing the output of `yield Post.findOrFail(id)`

**Comment by betaWeb** [comment]
It returns an array of objects (`[{ .... }]`) and I'd like to have only an object ({ .... }`) in order to avoid having to get my resultset properties with `[0]`.
Is I fairly clear (my english is a lil bit rusty ^^) ?

**Comment by RomainLanz** [comment]
Hey !

`findOrFail` is calling `find` which is calling `findBy`. So it must returns an array.

I can send a PR to implement `firstOrFail`.

**Comment by betaWeb** [comment]
Hey @RomainLanz,

Indeed, it would be nice to have a `firstOrFail` method (which would directly returns an object instead of an array). So if you can send a PR .. ;)

Thx a lot :)

**Comment by thetutlage** [comment]
@RomainLanz @betaWeb `find` should return one row only, since primary key cannot have 2 rows for same value. I will fix the code.

**Comment by RomainLanz** [comment]
mmmh, `find` use `findBy` that return only one row.

```
return yield this.query().where(key, value).first()
```

which version of Adonis are you using @betaWeb ?

**Comment by betaWeb** [comment]
@thetutlage okay, thx :)
So, `find` (and `findOrFail`) will return an object instead of a collection of objects ?

**Comment by RomainLanz** [comment]
Hey @betaWeb !

Do you still have this issue?

**Comment by thetutlage** [comment]
@betaWeb and @RomainLanz This is kind of weird, I was looking into the tests and saw that `findOrFail` returns only a single instance and test passes fine. 

https://github.com/adonisjs/adonis-lucid/blob/develop/test/unit/lucid.spec.js#L1171

**Comment by thetutlage** [comment]
Closed since no reply for the issue reporter and I am not able to reproduce it

**Comment by betaWeb** [comment]
@thetutlage @RomainLanz Thx a lot for your help, problem sloved with use of `findOrFail`
