### ISSUE TITLE
TS doesn't recognize `auth` property inside `HttpContext`

### ISSUE THREAD

**Issue by vladchernenyi** [adonisjs/adonis-framework#4780]
### Package version

@adonisjs/http-server@7.2.5

### Describe the bug

`HttpContext` has `auth` property but TypeScript doesn't recognize it.

https://github.com/adonisjs/http-server/blob/7.x/src/http_context/main.ts#L25

<img width="471" alt="Screenshot 2024-10-27 at 23 46 24" src="https://github.com/user-attachments/assets/98e34e6e-9af9-4f6a-a15d-3bab180a86b8">
<img width="887" alt="Screenshot 2024-10-27 at 23 48 12" src="https://github.com/user-attachments/assets/e352cc17-ca98-4c2f-9a05-0350851fc8d5">

**Comment by RomainLanz** [comment]
Hey @vladchernenyi! 👋🏻 

Does the issue still occur after you reboot your IDE?
If it does, could you check that the `@adonisjs/auth/initialize_auth_middleware` middleware is registered?

**Comment by vladchernenyi** [comment]
Hey @RomainLanz!

Yes, I tried to reboot IDE, invalidate caches and restart TS server.

The problem is that `HttpContext` itself doesn't have `auth` property. You can go declaration here: https://github.com/adonisjs/http-server/blob/7.x/src/http_context/main.ts#L25 and you won't find it.

This means no TS autocompletion while development.

<img width="609" alt="Screenshot 2024-10-28 at 21 37 15" src="https://github.com/user-attachments/assets/99a2f433-cb88-444f-b795-e566087c8672">

p.s. Adonis will create/inject `auth` property at at a buildtime but i'd like to have it avalable as part of `HttpContext` for better type safety.

Thanks!

**Comment by RomainLanz** [comment]
> The problem is that HttpContext itself doesn't have auth property.

This is expected, the interface is augmented through the `auth` module. You wont find the reference in the base of the `HttpContext` interface.

See here: https://github.com/adonisjs/auth/blob/develop/src/middleware/initialize_auth_middleware.ts#L39

This is why I am asking if you have correctly imported the middleware.

**Comment by vladchernenyi** [comment]
> This is why I am asking if you have correctly imported the middleware.

Yes, it seems to be imported correctrly. I just created adonisjs app with tokens authentication using adonis cli.

Please see my test repo: https://github.com/vladchernenyi/adonis6-test/blob/main/adonis-postgres-auth/app/controllers/auth_controller.ts

**Comment by thetutlage** [comment]
![CleanShot 2024-10-31 at 06 56 57@2x](https://github.com/user-attachments/assets/bce5ed87-44e9-4962-9263-c6e6d7f5334e)

Just gave your repo a try and it seems to be working fine for me.

**Comment by vladchernenyi** [comment]
@thetutlage Thanks for verifying the issue!

Looks like issue does not exist in VS Code. I verified it on my side as well. Types also works fine in WebStorm.

And only Intellij Idea throw errors here and there. It doesn't recognoze types properly. I will investigate and drop a note here if i find the root cause.

Closing the issue.
