### ISSUE TITLE
xml 

### ISSUE THREAD

**Issue by wuxiangwa** [adonisjs/adonis-framework#480]
![image](https://cloud.githubusercontent.com/assets/18392247/23149748/1f6b8194-f829-11e6-962a-9e080c437bf6.png)
![image](https://cloud.githubusercontent.com/assets/18392247/23149849/db00bc4e-f829-11e6-8113-32d2948b582c.png)

How do I get this XML by  request ？

**Comment by thetutlage** [comment]
Need more info

1. Code you written to read XML
2. The output you have received.

**Comment by wuxiangwa** [comment]
The problem  is  already solved!


* message(request, response){
    // 获取原始body,并且解析
    let body = request.request.read().toString()
    console.log(body)
    let xml = new DOMParser().parseFromString(body)

    // 获取参数
    let event = StringUtil.getXMLValue(xml, 'Event')

    // 组装新的xml
    let templateXML = `
<xml>
<ToUserName><![CDATA[{0}]]></ToUserName>
<FromUserName><![CDATA[{1}]]></FromUserName>
<CreateTime>{2}</CreateTime>
<MsgType><![CDATA[transfer_customer_service]]></MsgType>
</xml>
`
    let returnXML = StringUtil.createXML(templateXML, event)

    response.send(returnXML)
  }
![image](https://cloud.githubusercontent.com/assets/18392247/23152286/0dfbc79e-f83c-11e6-8dc7-63b97a1a8533.png)
