### ISSUE TITLE
node --inspect ace serve is not working

### ISSUE THREAD

**Issue by atassis** [adonisjs/adonis-framework#4800]
### Package version

6.14.1

### Describe the bug

I cannot make a debugger via chrome inspect working. While running an app with `node --inspect ace serve --hmr` with or without `--hmr` flag, debugger is connected, but not triggered. I am using dynamic imports for controllers, but still, it shouldn't be an issue

**Comment by thetutlage** [comment]
It's hard to tell anything from the information you have shared. What do you mean by "debugger is connected, but not triggered"? Please share some screenshots and the steps you are following to test the debugger.

Also, it should not be reported as an issue until it is confirmed. So please open a discussion thread instead.

**Comment by pomarec** [comment]
@thetutlage 
I think the issue is quite explicit. I have the same issue.
Starting from a fresh api project :
```npm init adonisjs@latest hello-world -- --kit=api --auth-guard=access_tokens```
The debugger in VS Code (or chrome debugger) plugs in but breakpoints are not available in dynamic imports, only in files like `console.ts`.
Do you know how we can make it work ?

**Comment by pomarec** [comment]
After further investigation, it seems to be related to [Cluster](https://nodejs.org/api/cluster.html) feature of node. Adonis might be spawning multiple sub-processes, each (or part) of them spawning a debugger (based on ```NODE_OPTIONS="--inspect"```). VSCode sometimes plugs to the wrong process.

My understanding is that this problem does not happen when you VSCode launches adonis by its own because VSCode might know which process to attach to (the first it launched). But it happens when you remote debug (eg: a docker container) as VSCode does not know which process to attach to.


As I dont know the internals of Adonis, I went for a quick fix : spawning only one debugger no matter the number of adonis sub-processes. Here how I did this, I modified each of `app/bin/{console,server,test}.ts` and added into ```app.booting()``` :

```
   app.booting(async () => {

      if (process.env.NODE_ENV !== 'production')
        (await import('inspector')).open(9229, '0.0.0.0', false)

      await import('#start/env')
    })
```

I hope it will help @atassis

**Comment by thetutlage** [comment]
Can you try with `node ace --inspect serve --hmr`. Remember the `--inspect` flag is defined after `ace`. This is because we want to pass these flags to the child process (HTTP server) and not the parent process.

**Comment by reiguy77** [comment]
Thank you for figuring this out! This solved my problems of files not having source maps when trying to debug my dockerized adonis app

**Comment by pomarec** [comment]
Firsts tests are positives with `node ace --inspect serve --hmr`, thanks.
Might be useful to have a line in the doc ?

**Comment by atassis** [comment]
@thetutlage Hi there. Thanks for an advice, haven't tested it but will do it later.
Haven't seen any mention of adonisjs spawning child processes in documentation. Do you know about a documentation about the internal structure of the adonisjs, it might get some things clearer for understanding. Or if there is no such a doc- I'll try to read through the code later, but any help with links or anything else to speed it up might be useful
Thanks in any way!

**Comment by thetutlage** [comment]
@atassis Sure. The commands reference guide covers it to some extent https://docs.adonisjs.com/guides/references/commands#serve

Let me know if things are still unclear 👍

**Comment by atassis** [comment]
I see now. Though, I find it confusing the way docs are written.
1. It seems that flags for `ace` script are different that ones provided for a command, still there is no explanation of one. For example, it would be nice to write it like `node <node_flags> ace <ace_flags> *command* <command_flags> *arguments*`. So the developer would understand that there is a difference between base ace flags and commands' ones.
2. I have found no mention of `inspect` flag in `node ace --help` and `node ace serve --help` outputs. 
3. Also I find it useful to document whole list of flags for all commands in the docs, not partially in CLI and partially on website. Last thing makes it complicated to make a proper understanding of what's going on with the framework.

All this looks like another issue related to docs, though. If you agree with what's said above, I can make another docs related issue.
