### ISSUE TITLE
fresh install adonisv6 with template inertia : "flashes" when the page is first loaded (or when you do ctrl+R )

### ISSUE THREAD

**Issue by titoff002** [adonisjs/adonis-framework#4809]
### Package version

"@adonisjs/core": "^6.14.1", "@adonisjs/inertia": "^1.2.2",

### Package version

"@adonisjs/core": "^6.14.1", "@adonisjs/inertia": "^1.2.2",

### Describe the bug

![image](https://github.com/user-attachments/assets/427cd45c-abd5-4f34-877e-69a24667c190)

Hello,
Brand new installation of adonisjs v6 + inertia with the official adonis_inertia template (no other packages have been added and no modifications to the code have been made or added). 

Truly the original application/package. As you can see in the screenshot: a warning is mentioned to the effect that the css classes were not initially loaded and which creates "flashes" when the page is first loaded (or when you do ctrl+R ).

![image](https://github.com/user-attachments/assets/2e25b12f-0540-49c7-b19c-e99ea26dd68c)

Another problem : 
![image](https://github.com/user-attachments/assets/58d26bd0-a6ff-4fff-8c76-f13605114530)

 Do you have any idea how to solve this problem? Thank you and have a good day.

**Comment by Julien-R44** [comment]
Duplicate https://github.com/adonisjs/inertia/issues/47
