### ISSUE TITLE
Nunjucks configuration

### ISSUE THREAD

**Issue by picorelli** [adonisjs/adonis-framework#481]
I'd like to change nunjunck's configuration.. How can i do that? 

Example: 

`nunjucks.configure('/path/to/templates', {
  tags: {
    blockStart: '<%',
    blockEnd: '%>',
    variableStart: '<$',
    variableEnd: '$>',
    commentStart: '<#',
    commentEnd: '#>'
  }
});`

**Comment by betaWeb** [comment]
+1

It'd be great to have, for example, a `view.js` config file allows us to redifine Nunjucks default config :)

**Comment by betaWeb** [comment]
Otherwise, you can set the Nunjucks settings on app load (in bootstrap/app.js file if I'm not wrong)

**Comment by betaWeb** [comment]
Otherwise, you can set the Nunjucks settings on app load (in bootstrap/app.js file if I'm not wrong)

**Comment by thetutlage** [comment]
Not possible as of now, since AdonisJs does not expose `nunjucks`. I am also personally against the customizing too many things, since it only makes the eco-system confusing.

Anyways, the major release of Adonis(v4) will expose nunjucks.

**Comment by betaWeb** [comment]
@thetutlage Ok thanks a lot !
The V4 release is scheduled for when ? :)

**Comment by thetutlage** [comment]
@betaWeb There is no tentative date for that. Somewhere around July, August

**Comment by thetutlage** [comment]
Closing since not actionable and will be considered with the new release
