### ISSUE TITLE
Cannot lookup route "subdomain.login"

### ISSUE THREAD

**Issue by decoderid** [adonisjs/adonis-framework#4813]
### Package version

6.14.1

### Describe the bug

```log
METHOD ROUTE .................................................. HANDLER MIDDLEWARE
GET    /login (subdomain.login) ....................... #controllers/auth_…      guest
POST   /login ..................................... #controllers/auth_…      guest
```

![image](https://github.com/user-attachments/assets/9c953a94-f5ea-4ea3-a613-b21f4c647872)

**Comment by RomainLanz** [comment]
Hey @decoderid! 👋🏻 

It looks like the domain parameter is missing in your redirect call. As mentioned in the routing section, when using a domain modifier, you’ll need to include it to ensure proper route resolution.

Here's an example:

```ts
response.redirect().toRoute('subdomain.login', undefined, { domain: 'xxx' })
```

Hope this helps! 😊

**Comment by decoderid** [comment]
> Hey @decoderid! 👋🏻
> 
> It looks like the domain parameter is missing in your redirect call. As mentioned in the routing section, when using a domain modifier, you’ll need to include it to ensure proper route resolution.
> 
> Here's an example:
> 
> ```ts
> response.redirect().toRoute('subdomain.login', undefined, { domain: 'xxx' })
> ```
> 
> Hope this helps! 😊

thanks for replying, it works. but can it be done without domain name? because it is very strange to have to add domain name every time to do redirect

**Comment by RomainLanz** [comment]
You only have to specify the domain if the route you are looking for is under a domain.
