### ISSUE TITLE
Blank spaces in path

### ISSUE THREAD

**Issue by equeraltowenea** [adonisjs/adonis-framework#4822]
### Package version

@adonisjs/core@6.14.1

### Describe the bug

When I receive a parameter in path with blank space, when obtaining the HttpContext params, the blank spaces are like %20. Are you planning to parse that in the future?

**Comment by RomainLanz** [comment]
Hey @equeraltovivas! 👋🏻 

Currently, we can't parse this without introducing a breaking change. However, adding a flag to the configuration could make this possible. What do you think, @adonisjs/collaborators?

**Comment by thetutlage** [comment]
I have hardly seen URL's in wild with spaces between them. Yes, the query string for search can have spaces, but self defined URLs or generated slugs won't have them.

So I will not make router complicated to serve a niche use-case.

**Comment by equeraltowenea** [comment]
> I have hardly seen URL's in wild with spaces between them. Yes, the query string for search can have spaces, but self defined URLs or generated slugs won't have them.
> 
> So I will not make router complicated to serve a niche use-case.

In that case I close the issue.
