### ISSUE TITLE
Validator not populating flashSession

### ISSUE THREAD

**Issue by sn0rcha** [adonisjs/adonis-framework#4823]
### Package version

@adonisjs/core@6.15.2, @adonisjs/inertia@1.2.4

### Describe the bug

I'm having a bizarre issue with `request.validateAll` where if an element in the object exceeds a certain string length, the validator doesn't populate the `flashSession` with the errors:

My validation:

```
export const assignmentValidator = vine.compile(
  vine.object({
    name: vine.string().trim(),
    student_id: vine.number(),
    category: vine.string().trim(),
    status: vine.string().trim(),
    learning_level: vine.number(),
    due_date: vine.string().trim(),
    source_content: vine.string().trim().nullable().optional(),
    source_file: vine.string().trim().nullable().optional(),
    instructions: vine.string().trim(),
    instructions_notes: vine.string().trim().nullable(),
    score_pass: vine.number(),
  })
)
```

If I send `source_content` with a string length longer than 2403, it never populates the flashSession with any errors, anything less is fine.

Any ideas? - My `bodyParser` config is set to 60 MB on all types.

**PLEASE NOTE:** If I wrap the `request.validateUsing()` in a try / catch I get the following when clearing the name field and submitting - so the validation is working - it's just not populating the flashSession for some reason:
```
{
  status: 422,
  code: 'E_VALIDATION_ERROR',
  messages: [
    {
      message: 'The name field must be defined',
      rule: 'required',
      field: 'name'
    }
  ]
}
```

**Comment by thetutlage** [comment]
Can you update the session driver to use either `file` or `redis` and then give it a try?

**Comment by sn0rcha** [comment]
@thetutlage thanks for the reply! - it works on anything other than `cookie` - however I need `cookie` for socket authentication unless there's a better way to get the authenticated user with socket.io and Adonis?

**Comment by thetutlage** [comment]
Its more of a cookie size limitation than anything to do with AdonisJS. Also, why do you need the session data to be stored in cookie for the socket auth to work?

**Comment by sn0rcha** [comment]
when I'm working with socket.io listeners in the backend I use this function to grab the signed-in user:
```
 async getSocketUser(socket: Socket) {
    // @ts-ignore
    const SocketRequest = new Request(socket.request, null, encryption, {}, qs)
    const sessionId = SocketRequest.cookie('auth-cookie')

    if (!sessionId) {
      return null
    }
    const session = SocketRequest.encryptedCookie(sessionId)
    if (!session || !session.auth_web) {
      return null
    }
    return session.auth_web
  }
```

**Comment by sn0rcha** [comment]
hey @thetutlage 

I altered my socket user function to pull the session from redis:

```
  async getSocketUser(socket: Socket) {
    // @ts-ignore
    const SocketRequest = new Request(socket.request, null, encryption, {}, qs)
    const sessionId = SocketRequest.cookie('auth-cookie')
    const sessionData = await redis.get(sessionId)
    if (!sessionData) {
      return null
    }
    // parse session
    try {
      const sessionDataParsed = JSON.parse(sessionData)
      if (!sessionDataParsed || !sessionDataParsed.message) {
        return null
      }
      return sessionDataParsed.message.auth_web
    } catch (error) {
      return null
    }
  }
```

Can you see any issues using this method?

**Comment by thetutlage** [comment]
Nope. Not really. Also, feel free to further discuss it on Discord or the forum 👍
