### ISSUE TITLE
Flash message

### ISSUE THREAD

**Issue by picorelli** [adonisjs/adonis-framework#484]
Anybody knows how can I send a custom flash message after a success action? Thanks!

Ex: 

```
* show(request, response) {
     let user = checkCrendetials('user', '12345')

     if(!user) {
      response.redirect('back')
      return
     }

      //Flash message here
      response.redirect('panel')
  }
```

**Comment by betaWeb** [comment]
Try something like that :

`yield request.with({success: 'My wounderful success message'}).flash()`
`response.redirect('panel')`

:)
