### ISSUE TITLE
How to use generator functions when iterating a collection of models? 

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#485]
Please excuse me if this is a silly question, I'm still getting my head around using generators in this way. 

Let's take this simple example;

```javascript
let awards = yield UserAward.all()

awards.forEach(function(award) {
	let data = yield award.retrieve()
	console.log(data)
})
```

This obviously won't work, because I can't yield award.retrieve() in a non-generator function. 

In other occasions, I'd do something like;

```javascript
for(let i=0;i<awards.length;i++)
```

But being wrapped in lodash, awards does not have a length property. 

So is there an elegant way to use generator functions when looping through a collection of models?

**Comment by mikehhhhhhh** [comment]
It seems like I've some catching up to do in javascript. I feel slightly embarrassed now I've figured it out. 

The solution was to use for of

```javascript
for (let award of awards) {
    let data = yield award.retrieve()
}
```

**Comment by thetutlage** [comment]
Closing since you figured it out

**Comment by mikehhhhhhh** [comment]
@thetutlage Can I make a suggestion on the matter, however? 

Speaking strictly as someone that has a lot of Laravel experience, some Javascript/Node experience, but is new to building web apps with it;

The documentation lacks the kind of examples that would make migrating to JS/Adonis from say PHP/Laravel, Ruby/Rails easier for someone looking to make a step into building MVC apps with Javascript. 

I've been building Javascript apps for a few years, but this is my first time dealing with applications architected in this way with generators etc. and I'm hitting a few snags along the way with documentation that may be obvious to a veteran, but perhaps no so much to an newcomer. 

I was initially drawn in by the similarities to Laravel after deciding to attempt the switch to Javascript on the back end, but some things have been difficult. 

If addressing the documentation isn't what you want to/can do, What might help is A decent sized example or open sourced project built on Adonis, making good use of all the features but not too overwhelming.  Perhaps you know of something?

**Comment by betaWeb** [comment]
I agree with @mikehhhhhhh comment.

Maybe "decent sized" example or an example of every typical use cases the user can met would be great (like in Laravel doc for example) :)

**Comment by RomainLanz** [comment]
Hey @mikehhhhhhh & @betaWeb.

I understand your issue but you may know that [Generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) are part of the JavaScript spec and is not specific to Adonis.

It's like asking to understand how a `foreach` loop work in PHP. It's not the goal of Adonis to teach how JavaScript works. You have a lot of tutorials and a very good JavaScript Guide from the [MDN](https://developer.mozilla.org/en-US/).

I can say that Adonis will have a better documentation for the next release (4.0) with more examples and more "user oriented" but "basic" JavaScript will probably not be explained in it.

**Comment by betaWeb** [comment]
@RomainLanz I agree with you about the comprehension of Generators, but maybe it would be great to have an explanation of how they're used on AdonisJS ? :)

Ok, great for the 4.0 doc (for when ?) :)
