### ISSUE TITLE
Macros doesn't work inside if statement

### ISSUE THREAD

**Issue by howardEagle** [adonisjs/adonis-framework#487]
Example:
`{% if(recentPosts) %}`
`<div class="recent-post-list">`
`{% import './macros' as macros %}`
`{{ macros.recentData(recentPosts) }}`
`</div>`
`{% endif %}`

**Comment by RomainLanz** [comment]
Hey @howardEagle !

May you try with `ifAsync` ?

**Comment by howardEagle** [comment]
@RomainLanz, thanks - works like a charm :)

**Comment by howardEagle** [comment]
P.S. Add this into the docs, I have not found any reference about using ifAsync.
