### ISSUE TITLE
View.global is not bound to current request

### ISSUE THREAD

**Issue by andrasf** [adonisjs/adonis-framework#489]
Hi,

I was load testing my site with ab tool (https://httpd.apache.org/docs/2.4/programs/ab.html). I visited the site while testing and found that sometimes I seem to be logged in, sometimes not.

I started searching for the reason, and found the following:

* Create a middleware
* Add `View.global('input', request.input('input'))`
* Create a view that prints it: `{{ input }}`
* Visit your site with parameter `?input=right`
* Start `ab -n 1000 -c 50 http://127.0.0.1:3333/?input=wrong`
* Hit reload sometimes and you will see it prints `wrong` instead of `right`

This way I cannot put session variables in `View.global`.
Also, csrf tokens will be invalid, since they do not match in the View.
It also seems like `authProvider` uses this for user handling.

For now I overwrote my `sendView` method and added these variables for myself from the request object.

Not sure if nunjucks does this right, but one possible solution would be to use a method like `View.local` instead of `View.global` that would store data bound to the `Request` object and would be extended by options passed to the views.

I'm in the finish line of my project... do you have any instant suggestions for me? :)

**Comment by thetutlage** [comment]
Yup that is true. A `global` is a global and whenever you set a new value to it the old one overrides. I know people started using `globals` for request specific information, which is never a reliable way since 2 requests can come at the same time.

## What's the work around?
The best way is to pass the data you need to the view via `sendView` method, which makes sure that locals are isolated.

I cannot add any out of the box solution for it right now, since I am planning some good amount of changes for the views.

**Comment by andrasf** [comment]
I see. May I ask some?

I always need my session data for authentication / display stuff, so I created a middleware that yields and attaches `session.all()` to my `request`, thus I don't have to yield it all the time. And now I created a middleware that overrides `response.sendView` method, here I can add my session to view locals since I access my `request.session` from my controller scope. I can also override my csrfToken and csrfField values to the correct ones. Am I right?

My other two questions are:
* I guess situation is the same with flash messages but I feel a little insecure here. If I pass a local function called `old` to my views that returns `request.old(key, defaultValue)` - will it be in the right scope?
* Does a global middleware always precede those defined in routes.js? (`Route.group(...).middleware()`)

Thanks in advance.

**Comment by thetutlage** [comment]
Answers

1. I believe `old` global in the view will not point to the right request, so it is a bug.
2. All global middleware are executed before any middleware defined on the route.

I believe I have to jump in and fix the way you pass things onto views. There needs to be a way to have unique instance of views for each request.

**Comment by andrasf** [comment]
Thanks!
