### ISSUE TITLE
issue with handleCallback in twitter LoginController

### ISSUE THREAD

**Issue by basiclaser** [adonisjs/adonis-framework#490]
I've followed the text and video [here](http://adonisjs.com/docs/3.2/social-auth#_basic_example) twice in an attempt to set up twitter auth. On requesting authentication("log in with twitter"), i am returned to `http://localhost:3333/?oauth_token=kMhIIgAAAAA123AAABWoqySOU&oauth_verifier=Ji9AgBw7eyHxp8Lw123pg5c5ZDQjqOg`
and unfortunately the handleCallback generator function is ignored. It seems to me that authentication was successful, and im sure that just a small step is missing. I notice that the callback URL is '/' in the tutorial but then we specify 'twitter/authenticated' - should they be the same URL? Thank you.

```
'use strict'
const User = use('App/Model/User')

class LoginController {
    * redirect (request, response) {
        yield request.ally.driver('twitter').redirect()
    }
    * handleCallback (request, response) {
        const twUser = yield request.ally.driver('twitter').getUser()
        const searchAttr = {
            email: twUser.getEmail()
        }
        const newUser = {
            email: twUser.getEmail(),
            provider_id: twUser.getId(),
            provider_token: twUser.getAccessToken(),
            provider: 'twitter'
        }
        const user = yield User.findOrCreate(searchAttr, newUser)
        yield request.auth.loginViaId(user.id)
        response.redirect('/profile')
    }
}

module.exports = LoginController
```

**Comment by thetutlage** [comment]
Can u share your routes file + you have to register the same callback url with twitter aswell

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
