### ISSUE TITLE
How to eager load multiple items

### ISSUE THREAD

**Issue by andrewdelprete** [adonisjs/adonis-framework#491]
I'm trying to figure out how to retrieve multiple events `with` attached relationships. The below code only returns the first level of events but **does not** include the nested `eventType` or `bookings`. However, if I replace `fetch()` with `first()`, I get my first event with the proper nested relationships. Any ideas?

I'm using Adonis 3.0.11.

**Controller Method**
```
* checkEvents (request, response) {
    let sessions = yield this.Sessions
      .query()
      .whereIn('id', [3, 4])
      .with('event.eventType', 'bookings')
      .fetch()
...
}
```

**Output of sessions**

```
LodashWrapper {
  __wrapped__:
   [ { id: 3,
       event_id: 2,
       time: '08:00:00',
       status: 'active',
       created_at: 2017-02-26T05:26:46.000Z,
       updated_at: 2017-02-26T05:26:46.000Z },
     { id: 4,
       event_id: 2,
       time: '12:00:00',
       status: 'active',
       created_at: 2017-02-26T05:26:46.000Z,
       updated_at: 2017-02-26T05:26:46.000Z } ],
  __actions__:
   [ { func: [Function: transform],
       args: [Object],
       thisArg: [Object] } ],
  __chain__: false,
  __index__: 0,
  __values__: undefined }
```

**Debug**
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, 4 ],
  __knexQueryUid: '2eb5a8cb-56f6-4bd5-a65c-bfa92807329f',
  sql: 'select * from `sessions` where `id` in (?, ?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2, 2 ],
  __knexQueryUid: 'ffd17b0b-2ecb-4fef-99ad-ed157055e764',
  sql: 'select * from `events` where `id` in (?, ?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, 4 ],
  __knexQueryUid: '04e4ea8a-e0a3-4ff1-aa4f-08de2d533608',
  sql: 'select * from `bookings` where `session_id` in (?, ?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2 ],
  __knexQueryUid: 'b1372c5d-8a7a-4335-9c17-7f4e22c752aa',
  sql: 'select * from `event_types` where `id` in (?)' }
```

**Comment by thetutlage** [comment]
I would need couple of things to work with this

1. The output of the `sessions`
2. How relations are structured within models

Also it will be nice if you can enable debugging and see which all queries are ran, may be Lucid is not producing right queries.

http://adonisjs.com/docs/3.2/database-setup#_debugging

**Comment by andrewdelprete** [comment]
Hey @thetutlage, I updated the description. Thank for your the quick response!!

**Comment by thetutlage** [comment]
Queries seems fine to me. Did you try to do a `sessions.toJSON()` to see the output?

**Comment by andrewdelprete** [comment]
Hey @thetutlage, that did it. I'm not sure what I was doing wrong the first time. I could have sworn I had toJSON(). Must have been working too late. Thank you very much!!
