### ISSUE TITLE
Using instance variables inside a model 

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#493]
I have a few model hooks that duplicate a couple of models to another datastore via API on create/update. 

My problem is, I need to update a model at the end of the create hook, this leads to a never-ending loop. 

In other frameworks/languages, I've solved this kind of problem with something like this;

```javascript
this.addHook('afterUpdate', function * (next) {
  if (!this.disableHooks) {
    Kue.dispatch(UserToBapp.key, {type: 'update', id: this.id});
  }
})
```

and simply set ```model.disableHooks = true``` before calling ```model.save()```

My problem is that with Adonis, any instance variables seem to be caught by the setter and then I get errors about them trying to be interested into the SQL database. 

How can I avoid this?

**Comment by thetutlage** [comment]
Frankly saying, I didn't understood what you mean, Mind sharing some code on what exactly you are trying to do

**Comment by mikehhhhhhh** [comment]
Put simply, I need the ability to disable hooks for a model before I call save().

Normally I would just set an instance variable on the model to do that, like the ```this.disableHooks``` mentioned above.

But because setting this.disableHooks tries to insert data into a field 'disableHooks' in the database upon save(), I cannot use this method because I get a SQL exception.

**Comment by RomainLanz** [comment]
Hey @mikehhhhhhh !

> My problem is, I need to update a model at the end of the create hook, this leads to a never-ending loop.
Why do you need to update a model directly after creating it?

Also, this shouldn't create a never-ending loop since you are doing `create -> update -> afterUpdate`.

**Comment by thetutlage** [comment]
Closing since not actionable.
