### ISSUE TITLE
Possible to authenticate with token via middleware?

### ISSUE THREAD

**Issue by dunkdunk** [adonisjs/adonis-framework#495]
Not an issue, but an authorization question:

After reading through the docs on middleware, I'm curious if there is a way to read an authentication token from a cookie and pass it to the authentication middleware (using either the API scheme or JWT scheme).

My global middleware looks like this:

```
'use strict'

class TokenGetter {

  * handle (request, response, next) {
    // Read the token from cookie and decorate the request
    const token = request.cookie('token')
    request.token = token

    // Pass it along
    yield next
  }

}

module.exports = TokenGetter
```

Is it possible to authenticate users with the built-in authentication middleware with a method like this?

**Comment by thetutlage** [comment]
You can set the Authorization header via middleware

**Comment by dunkdunk** [comment]
Sorry if this is a silly question, but how would I set headers with Adonis? After reading the [docs](https://adonisjs.com/docs/3.2/request#_headers), I see that it is very easy to read header values, but am confused on how to set them.

**Comment by thetutlage** [comment]
You can say following inside a middleware

```
request.request.headers['authorization'] = 'your token'
```

Make sure to call the above middleware before the authentication middleware and define it here https://github.com/adonisjs/adonis-app/blob/develop/app/Http/kernel.js#L32

**Comment by dunkdunk** [comment]
Got it. Thanks so much for your help with this.
