### ISSUE TITLE
Override auth middleware exception page

### ISSUE THREAD

**Issue by betaWeb** [adonisjs/adonis-framework#496]
Hi there,

I have protected routes behind AdonisJS auth middleware, and I wanna know if it's possible to redirect in one of my routes with custom flash message if user is not allowed ?
For now, the user is redirected on a basic error page (InvalidLoginException).

Thank's.

**Comment by RomainLanz** [comment]
Hey @betaWeb !

You only need to listen for the exception in the exception handler.

**Comment by betaWeb** [comment]
@RomainLanz it seems logic, thx ;)

**Comment by lmj0011** [comment]
For those who will need more detail to go with:

You listen for the Exceptions here: https://github.com/adonisjs/adonis-app/blob/develop/app/Listeners/Http.js


If you're seeing a page with all of your ENV vars on it, that's expected in `development` mode
