### ISSUE TITLE
<Class> is not a constructor

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#497]
I'm experiencing annoying errors which never happened before, when trying to instantiate classes within another classes, to perform operations without code repetition. I'm really confused and I do not know what is happening, because when I manage to "fix" one, another of the same problem happens, for another class.

Just now, when I create a new `UserReporter` and I try to update is status to 'active', the function from `UserReporterOperation` executes a private method `_getLatestNews`, which instantiates `ReportersOperation` and executes its `parseReporter`.

```javascript
* _getLastestNews(userReporter) {
  const reportersOperation = new ReportersOperation()

  reportersOperation.googleAlertsUrlId = userReporter.url.split('/')[3]
  reportersOperation.reporterUrlId = userReporter.url.split('/')[4]

  return yield reportersOperation.parseReporter()
}
```

```javascript
* parseReporter() {
  const article = new Promise((resolve, reject) => {
    parser.parseURL(`https://www.google.com/alerts/feeds/${this.googleAlertsUrlId}/${this.reporterUrlId}`, (err, parsed) => {
      if (err) {
        return reject(new Error(err))
      }

      if (parsed.feed.entries.length === 0) {
        return reject(new Error('Nothing to parse'))
      }

      const link = parsed.feed.entries[0].link
      const betterLink = link.substring(42, link.indexOf('&ct='))
      
      mercury.parse(betterLink).then((data) => {
        resolve(data)
      }).catch((err) => {
        return reject(new Error(err))
      })
    })
  })
  
  return article
}
```

This is the method being executed when pressing the button to change the status:

```javascript
* updateStatusAndShare() {
  const userReporter = yield UserReporter.find(this.id)
  const reporterHistory = yield ReporterHistory.findBy('userReporterId', userReporter.id)

  userReporter.status = userReporter.status === 'inactive' ? 'active' : 'inactive'
  
  yield userReporter.save()

  if (!reporterHistory) {
    const parsed = yield this._getLastestNews(userReporter)

    if (parsed) {
      const shared = yield this._shareOnFacebook(userReporter)

      if (shared) {
        yield this._storeOnHistory(userReporter, parsed)
      }
    } else {
      this.addError(HTTPResponse.STATUS_INTERNAL_SERVER_ERROR, parsed)
    }
  }

  return { userReporter }
}
```

But then, boom: `ReportersOperation is not a constructor`.

This isn't the only occurrence. Before, for the third time, I manage to fix `FacebookOperation is not a constructor` when executing a creation method, that also needs to access another function from this operation class, to execute a method. I'm doing this because I feel it's better, since it separates the functions related to its models. The issue was solved by moving the instance of new class to outside the `try/catch`, but I do not doubt it will fail again.

Why is it happening? Is all wrong? Is all badly coded? What is?!

**Comment by RomainLanz** [comment]
Hey @mfgabriel92 !

How do you import `ReportersOperation` in your code?

**Comment by mfgabriel92** [comment]
`const Class = use('App/Operations/ClassOperation')`

You see all those 3 private methods being called within the method to
update the status? I've moved all those codes to there, instead of calling
a private method, and then everything seems to work fine. What do you think
it might be? Perhaps we could open a discussion?

**Comment by RomainLanz** [comment]
You can join the Gitter channel if you prefer to have a "live" discussion.

Do you export the module in your file `App/Operations/ClassOperation`?

**Comment by mfgabriel92** [comment]
Sure I do. It was all working before, many days ago, and suddenly started
it. But it's like this, that change apparently solved it, but I'm still not
100% secured.

**Comment by mfgabriel92** [comment]
And again it has happened. I really do not understand why this happens, makes me want to cry out of rage, for this totally non-sense error.

**Comment by mfgabriel92** [comment]
Hi,

Once again, the errors have happened. I swear to God, I do not know what to do.

**Comment by thetutlage** [comment]
@mfgabriel92 All this has nothing to do with AdonisJs, you have join the gitter channel. Closing the issue, since I cannot take any action on it
