### ISSUE TITLE
Create helper methods file

### ISSUE THREAD

**Issue by betaWeb** [adonisjs/adonis-framework#498]
Hi :)

I wan't to create an helper file, so I've created a folder `App/Helpers/index.js` that returns an object with helpful methods. So, I use this where I need to with `const Helpers = use('App/Helpers')`.

Is that the best way to do or is there a more convinient way ?

Thx.

**Comment by RomainLanz** [comment]
Hey @betaWeb !

This is perfectly fine!

**Comment by betaWeb** [comment]
@RomainLanz thx !
I've put into my file a helper method for flash messages, that I call into my controllers with `const flash = use('App/Helpers').flash`.

@thetutlage It should be great to have a global helper method `flash(message, type = 'error')` that returns a formated object `{flash: [{ type, message }]}` for example :)

**Comment by RomainLanz** [comment]
You can still write one yourself 😄

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by liseipi** [comment]
I want to use this.ctx in a helper file, if?
```
class AlertPrompt {
  static async handle (args) {
    console.log(args)
    const {title, type, message, responseURL} = args
    this.ctx.session.flash({
      notification: {
        title: title,
        type: type,
        message: message
      }
    })
    await this.ctx.session.commit()
    return this.ctx.response.redirect(responseURL || 'back')
  }
}
module.exports = AlertPrompt
```
