### ISSUE TITLE
auto-loader includes **every** file when using a directory path which causes parsing errors in specific cases

### ISSUE THREAD

**Issue by pstaender** [adonisjs/adonis-framework#50]
As example: when running migration tasks they break when having a non regular js-file in the migration directory.

In my specific case it was a `.DS_Store` file, with ace message:

```sh
$ ./ace migration:run
Unexpected token .
``` 

[The auto-loader includes the whole directory](https://github.com/adonisjs/adonis-lucid/blob/9092a4e37396fdf86bdfe91cc975ea1dad27a2f1/src/Commands/Run.js#L35) and has, as far as I could evaluate, no possibility to use globs pattern. This may cause a lot of problems when you want  to include other files in the directories as well - for instance markdown files for documentation.

Beside that, ace stops execution on error but the process isn't stopped. It should exit with status code 1 instead, right?

Regards
Philipp

**Comment by thetutlage** [comment]
@pstaender Migrations run will load all the files from migrations directory, i will add a check to load all files with `.js` extension.

Also a good point, ace should exit process on errors.

**Comment by thetutlage** [comment]
@pstaender Marked as bug, will fix in next release, you may have to remove the `.DS_STORE` file for now :(

**Comment by chewedon** [comment]
Hi, I'm also trying to use

    ./ace migration:run

I got a console message:

    Make sure you are exporting a class from .gitkeep

In my storage folder, there is a .gitkeep (has one by default) after generate the default yardstick project.

Can confirm that after removing .gitkeep file from project, the `migration:run` command works afterwards.

I am using version 2.0 of Adonis.

**Comment by vkeusebio** [comment]
encountered the same problem as @chewedon when issuing `ace migration:run` due to `.gitkeep`

**Comment by thetutlage** [comment]
you need to remove `.gitkeep` from migrations directory. This issues will be fixed in upcoming release

**Comment by thetutlage** [comment]
Created issue on `lucid` repo https://github.com/adonisjs/adonis-lucid/issues/12
