### ISSUE TITLE
Problem with auth.attemp password Password does not match error

### ISSUE THREAD

**Issue by eriasu** [adonisjs/adonis-framework#500]
Hi i have a problem when i want to verify the hash password the response is always false and i cant loging i send to the console the plaintext, the hash password and use the verify function in the Hash library when i create the user the verify send true when i want to login the verify send false
![screenshot from 2017-03-07 13-41-15](https://cloud.githubusercontent.com/assets/1227249/23667233/ef81918a-033b-11e7-9ee5-ca6b08cf758b.png)

**Comment by eriasu** [comment]
![screenshot from 2017-03-07 14-10-08](https://cloud.githubusercontent.com/assets/1227249/23668427/cec6a904-033f-11e7-9fd8-abe7098c5d92.png)

**Comment by RomainLanz** [comment]
Hey @eriasu !

May you copy/paste some code where you're using `auth.attempt()`?

**Comment by eriasu** [comment]
@RomainLanz  no problem

`* doRegister(request, response){
      const user = new User()
      user.username = request.input('name')
      user.email = request.input('email')
      user.password = yield Hash.make(request.input('password'))
      yield user.save()
      
      yield response.sendView('register')
  }`

`* login(request, response) {
        const email = request.input('email')
        const password = request.input('password')

        const login = yield request.auth.attempt(email,password)
        if(login){
          response.send('Logged In')
          return
        }
        response.unauthorized('Invalid Credentails')

    }`

**Comment by thetutlage** [comment]
Kind of weird. Mind creating a sample repo with the same code I can use to reproduce the issue?

**Comment by eriasu** [comment]
Sorry for the delay https://github.com/eriasu/AdonisTest

**Comment by eriasu** [comment]
i even test passing here the passwod for testing and making sure that the plaintext was compare with the hash but the same error =/ or maybe a made a huge mistake 
![screenshot from 2017-03-08 08-21-48](https://cloud.githubusercontent.com/assets/1227249/23702032/4e9abf74-03d8-11e7-8fb6-bae280fb3216.png)

**Comment by thetutlage** [comment]
You are hashing the password twice. Their is hook inside `User` model which hashes the password and you are doing it manually too inside the controller. Remove the controller one.

It needs to be 
```
user.password = request.input('password')
```

**Comment by eriasu** [comment]
yeah it was that stupid me srry for the trouble thanks for the help!

**Comment by thetutlage** [comment]
Closing the issue
