### ISSUE TITLE
Use uWebSocket for best performance

### ISSUE THREAD

**Issue by ansarizafar** [adonisjs/adonis-framework#501]
Consider using uWebSocket performance gain is huge https://github.com/uWebSockets/uWebSockets/wiki/(More-than)-one-million-requests-per-second-in-Node.js

**Comment by RomainLanz** [comment]
Hey @ansarizafar !

That's what Adonis already use!

--> https://github.com/adonisjs/adonis-websocket

**Comment by thetutlage** [comment]
Set this to true inside your config file to make use of uWebSocket https://github.com/adonisjs/adonis-websocket/blob/develop/examples/config.js#L14

**Comment by ansarizafar** [comment]
uWebsocket can also used for http server https://github.com/uWebSockets/uWebSockets/issues/379#issuecomment-269529743
