### ISSUE TITLE
Inconsistent date output between environments

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#502]
I've been developing on my Mac using sqlite and using a Linux environment with MySQL for staging.

My issue is with a field with the type of 'date' 

Both environments use the same seeds and both environments store the date as 'YYYY-MM-DD' in the database.

However, 

Simply echoing the date in the template ie. ```{{ item.start_date }}``` has two different outcomes depending on environment;

Mac/sqllite provides ```2006-10-01``` as expected
Linux/MySQL provides ```Sun Oct 01 2006 00:00:00 GMT+0000 (UTC)```

If I use MySQL locally on the mac environment, I get ```Sun Oct 01 2006 00:00:00 GMT+0000 (UTC)``` so it appears to be db driver dependent?

**Comment by thetutlage** [comment]
It is how `Sqlite` and `Mysql` save dates internally. That is why you have a dateFormat in your Lucid models to format the date to consistent output whenever you call `toJSON` on a model instance http://adonisjs.com/docs/3.2/lucid#_dateformat.

**Comment by thetutlage** [comment]
Closing since not actionable and can be handled with `dateformat`

**Comment by mikehhhhhhh** [comment]
Are you sure about that @thetutlage?

I looked at dateFormat() and the documentation suggested that was to set how datetime fields are stored? I'm specifically talking about a field with a type of ```date``` and dateFormat() doesn't appear to have any effect on my issue.

Here's the output from both MySQL and sqllite3;

MySQL;
```
mysql> select start_date from user_educations limit 1;
+------------+
| start_date |
+------------+
| 2006-10-01 |
+------------+
1 row in set (0.03 sec)
```

sqllite;
```
sqlite> select start_date from user_educations limit 1;
2006-10-01
```

Both seem to provide the same result but somewhere between adonis, the query builder and lucid, it seems to be transformed in some way depending on which database you're using. This sounds more like a bug to me and if it is not, behaviour like this almost defeats the purpose of an ORM and query builder. 

Test code: 
```javascript
var edu = yield Edu.find(1)
console.log(edu.start_date)
```

```
Mike-AB-MBP:app mike$ ./ace run:test (mysql)
2006-09-30T23:00:00.000Z

Mike-AB-MBP:app mike$ ./ace run:test (sqlite)
2006-10-01
```

**Comment by thetutlage** [comment]
@mikehhhhhhh As far as I know, Adonis does not do anything to your fields. Maybe the actual driver of `mysql` and `sqlite` does something. Check this thread of knex https://github.com/tgriesser/knex/issues/1461.

Also the mysql driver accepts a timezone option https://www.npmjs.com/package/mysql, Which means they do something internally with it.

To make sure Lucid spits out right dates, we need a way to define date fields on your models, so that Lucid can normalize them. I'll see what best can be in done in this direction, as it has lots of other use cases as well.
