### ISSUE TITLE
Dynamic domain name

### ISSUE THREAD

**Issue by ahmadibrahim-c** [adonisjs/adonis-framework#503]
Hi thanks for the great framework!

Is there a way to make the server listen to a dynamic domain name? I want to make my users able to forward their domains to my service and I know which domain is currently being used.

**Comment by thetutlage** [comment]
http://adonisjs.com/docs/3.2/routing#_domain_subdomain and for dynamic domain you can do

```
Route.group('my-group', function () {
  Route.get('posts', function * (request, response) {
      console.log()
  })
}).domain(':domain')
```

and then use the request method to fetch the subdomains http://adonisjs.com/docs/3.2/request#_subdomains

**Comment by ahmadibrahim-c** [comment]
Thanks! Its easier than what I imagined!
