### ISSUE TITLE
[Form builder] Manage errors

### ISSUE THREAD

**Issue by betaWeb** [adonisjs/adonis-framework#504]
Hi there !

I've a view with a form (to register an user) with data validation. If validation fails, I "flash" errors this way `yield request.withAll().andWith({ errors: parsed_errors }).flash()` (I parse errors to convert them to an object with field name as key).
So, I've created a global Nunjucks macro to get if a specific field has error(s) `hasError(old('errors'), 'email')`. And, to add an error class to a field (for example), I do this `form.email('email', old('email'), { class: 'form-control' + (' form-control-danger' if hasError(old('errors'), 'email')) })`, but I think it's not the cleaner way to do.

The problem is that is not very convinient to use that with the Form Builder.
Or is there a simple way to check errors with the form builder (and to add a specific class to an input for example) ?

Thx :)

**Comment by thetutlage** [comment]
@betaWeb There aren't helpers to pull errors from the flash messages. You can create your own View global and use that inside your views. 

Going forward I will adding more globals to the view layer by default, but for now you have to do the work

**Comment by betaWeb** [comment]
@thetutlage thx for your answer. I've create my own helpers, and Request folder for data validation (aka Laravel). It works, but it's not very "clean".

I'll share my code asap if someone want my integration.

**Comment by RomainLanz** [comment]
You can take example of my frontend code that manage Error. It should work with no problem in the backend also.

https://github.com/RomainLanz/adonis-starter/blob/develop/resources/assets/js/form/Errors.js

**Comment by thetutlage** [comment]
Closing since not actionable. @betaWeb Feel free to share your solution with everyone on this issue

**Comment by betaWeb** [comment]
@thetutlage Thx, I'll improve my solution et I'll share it soon :)
