### ISSUE TITLE
Emoji into database

### ISSUE THREAD

**Issue by aleks63** [adonisjs/adonis-framework#509]
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x94\xA5",...' for column 'account' at row 1

And collation in db is utf8mb4_general_ci

**Comment by thetutlage** [comment]
Seems to be related to database engine more than AdonisJs, and why do you even store emojis to database, store the shortcode or unicode instead

**Comment by thetutlage** [comment]
Closing since no updates from the issue reporter

**Comment by dguzman1012** [comment]
I know this is a closed issue, but since nobody gave a truly solution i offer mine for others who are in the same situation...

As @aleks63 said, we actually have to set collation db/table/field as _utf8mb4_general_ci_, but we need to make a little modification on config/database.js as well:

```
connection: Env.get('DB_CONNECTION', 'sqlite'),
..
mysql: {
    client: 'mysql',
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      user: Env.get('DB_USER', 'root'),
      password: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis'),
      charset: 'utf8mb4'
    }
  },
..
```
And that's it! adding _charset: 'utf8mb4'_ on DB connection settings solves this issue!

**Comment by kingeke** [comment]
@dguzman1012 Hello, thanks for this, adding the charset: 'utf8mb4' and collation: 'utf8mb4_unicode_ci', to the database config allows emojis to work, but now i'm getting an error when adding unique() to my columns,

```

**Comment by dguzman1012** [comment]
Hey @kingeke. Where do you set the collation `utf8mb4_unicode_ci `? to all database? 

> As @aleks63 said, we actually have to set collation db/table/field as _utf8mb4_general_ci_,

I strongly recommend to set the `utf8mb4_unicode_ci ` collation only to the field inside the database table. Not the entire database.

Please try with that.

King regards.
