### ISSUE TITLE
Sanitize user input

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-framework#51]
How do we handle user input? Writing a  custom service provider or is there an built in way to sanitize user input?

**Comment by thetutlage** [comment]
@gearsdigital There is no inbuilt method to sanitize input, you should probably check https://www.npmjs.com/package/sanitize-html. 

Soon sanitization methods will become part of the validator provider.

**Comment by gearsdigital** [comment]
Thanks! Looking forward to future development :)

Would you recommend to wrap sanitize-html in a service provider?

**Comment by thetutlage** [comment]
No, simply `require` it as you will do in any other node applications. Service providers are required when you want to share the functionality with everyone else

**Comment by gearsdigital** [comment]
Okay. Thanks again!
