### ISSUE TITLE
Https websockets

### ISSUE THREAD

**Issue by armenmargaryan** [adonisjs/adonis-framework#512]
Hi,

we are having trouble with adonis **websockets+https** configuration

we did websockets configuration according to this tutorial: http://adonisjs.com/docs/3.2/websocket
and https configuration via this article: https://github.com/adonisjs/adonis-framework/issues/313

as a result at client side js we have following error in browser console that this link: https://localhost:3004/socket.io/?EIO=3&transport=polling&t=LhCkSzv not found

if we open it: https://localhost:3004/socket.io/?EIO=3&transport=polling&t=LhCkSzv we see exception
> HttpException
> Route not found /socket.io/

but under http all works perfectly ...
http://localhost:3004/socket.io/?EIO=3&transport=polling&t=LhCkSzv is reachable

**is https websockets supported in adonis ?** 
or what we are missing ?

Thanks,
Armen

**Comment by thetutlage** [comment]
How are you running the https server?

**Comment by armenmargaryan** [comment]
We have modified in bootstrap/http.js

this
    const Server = use('Adonis/Src/Server')
    Server.listen(Env.get('HOST'), Env.get('PORT'))
    if (typeof (callback) === 'function') {
          callback()
   }

to
    const Server = use('Adonis/Src/Server');
    const https = require('https');
    const fs = require('fs');
      
    var certOptions = {
    	key: fs.readFileSync(Helpers.appPath()+'/../../crt/'+Env.get('HTTPS_CREDENTIALS_KEY'), 'utf8'),
        cert: fs.readFileSync(Helpers.appPath()+'/../../crt/'+Env.get('HTTPS_CREDENTIALS_CERT'), 'utf8'),  
    }
    https
	      .createServer(certOptions, Server.handle.bind(Server))
	      .listen(Env.get('PORT'), Env.get('HOST'));
      
    if (typeof (callback) === 'function') {
          callback()
   }

**Comment by thetutlage** [comment]
Till that time the Websocket server is already using the `http` option inside of https. What you need to do is move this line https://github.com/adonisjs/adonis-app/blob/develop/bootstrap/http.js#L81 after `https.createServer` statement.

**Comment by armenmargaryan** [comment]
I did as you sugested

      const Server = use('Adonis/Src/Server');
      const https = require('https');
      const fs = require('fs');
      
      var certOptions = {
    	key: fs.readFileSync(Helpers.appPath()+'/../../crt/'+Env.get('HTTPS_CREDENTIALS_KEY'), 'utf8'),
  		cert: fs.readFileSync(Helpers.appPath()+'/../../crt/'+Env.get('HTTPS_CREDENTIALS_CERT'), 'utf8'),  
	  }
      https
	      .createServer(certOptions, Server.handle.bind(Server))
	      .listen(Env.get('PORT'), Env.get('HOST'));
      
     // moved here
      use(Helpers.makeNameSpace('Ws', 'socket'));
      
      if (typeof (callback) === 'function') {
          callback()
      }

but this link: https://localhost:3004/socket.io/?EIO=3&transport=polling&t=LhCkSzv still gives

> Route not found /socket.io/

**Comment by thetutlage** [comment]
That seems to be weird, lemme try to reproduce the issue

**Comment by thetutlage** [comment]
Hey, really sorry for getting late on same. So there have been couple of things we need to take care off and my request suggestion was more of guess. 

I have tried following and worked fine for me.

#### bootstrap/http.js
```
const httpsServer = https.createServer(options, Server.handle.bind(Server))

// very important to update the internal http instance
Server.httpInstance = httpsServer

// make sure to move these 2 line to the bottom instead of top
use(Helpers.makeNameSpace('Ws', 'kernel'))
use(Helpers.makeNameSpace('Ws', 'socket'))

// Start the server
server.listen(Env.get('PORT'), Env.get('HOST'))
```

**Comment by armenmargaryan** [comment]
Yes i was missing **Server.httpInstance = httpsServer** part thanks
