### ISSUE TITLE
IDE with autocomplete?

### ISSUE THREAD

**Issue by eskrano** [adonisjs/adonis-framework#516]
Hey all . I install adonisjs but my VScode dont have autocomplete, what IDE can give me good autocomplete in adonisjs?

**Comment by thetutlage** [comment]
Sorry there is no official auto-complete plugin for VsCode as of now

**Comment by eskrano** [comment]
@thetutlage but for other IDE?

**Comment by shekohex** [comment]
Try WebStorm or Sublime Text

**Comment by thetutlage** [comment]
Duplicate of https://github.com/adonisjs/adonis-framework/issues/600
