### ISSUE TITLE
BelongToMany attach() doesn't create timestamps

### ISSUE THREAD

**Issue by yogeshwaranManoharan** [adonisjs/adonis-framework#517]
I tried attaching user with product table but it doesn't seem to create timestamp

yield user.products().attach([id]);

I've updated the model with ".withTimestamps()" but it's not working

**Comment by thetutlage** [comment]
From future please report the issue to the right now. Moving for now.

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-lucid#113
