### ISSUE TITLE
How do I get a parameter from a parent resource?

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-framework#518]
```javascript
Route.group('api', () => {
  Route.resource('users', 'UsersController').except('create', 'edit')
  Route.resource('users.pages', 'PagesController').except('create', 'edit')
})
```
And I want to get only those pages that are added by a certain user. By the url:
```
/api/users/1/pages
```
How to get the `user.id` inside the method `PagesController.index` ?

**Comment by thetutlage** [comment]
You can fetch the `users_id` parameter like this `Request.param('users_id')`. For future you can check the list of registered routes by running the following ace command.

```bash
node ace route:list
```

**Comment by cawa-93** [comment]
@thetutlage, wow. Thanks
