### ISSUE TITLE
Is it possible to implement the alias for the router?

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-framework#521]
In my application there is a route like this:
```javascript
//  /users/:id
Route.resource('users', 'UsersController')
// /users/:users_id/pages/:id
Route.resource('users.pages', 'PagesController')
```
Is there a way to create a alias route for `/users/:id`? I want to create such a route that will correspond to the current user, and reproduce the structure of the nested routes. Thus, routes
```
/users/current
/users/current/pages/:id
```
Will correspond
```
/users/111
/users/111/pages/:id
```
or
```
/users/222
/users/222/pages/:id
```
Depending on which user is authorized

**Comment by RomainLanz** [comment]
Hey @cawa-93 !

This feature is not implemented in the current version of Adonis.
Mind creating a PR to add it?

**Comment by thetutlage** [comment]
I don't think a PR for this is required, since adding user login logic to routes is not going to work. If you need `users/current`.

1. Create a route
2. Guard it with `auth` middleware
3. Return the user profile from the session user.

```js
Route.get('users/current', function * (request, response) {
  const user = yield request.auth.getUser()
  response.send(user)
}).middleware('auth')
```

User got pages? 

```js
Route.get('users/current/pages/:id', function * (request, response) {
  const user = yield request.auth.getUser()
  const pageId = request.param('id')

  const pages = yield user.pages().where('id', pageId).fetch()
  response.send(pages)
}).middleware('auth')
```

**Comment by thetutlage** [comment]
Closing since actionable
