### ISSUE TITLE
viewInstance not working with flash messages

### ISSUE THREAD

**Issue by Xoandbit** [adonisjs/adonis-framework#523]
Hi, thank you for implementing this feature.

https://github.com/adonisjs/adonis-framework/commit/08bdca3eac4e2c6804e74a84909a66b8f33c7949

But now flash messages are buggy, 

Got error when rendering view:
`Error: Unable to call `old`, which is undefined or falsey`

And flash messages do not show up, or shows up couple of page reloads later.

**Comment by thetutlage** [comment]
That commit has not been release yet. Are you using the code from Github?

**Comment by thetutlage** [comment]
Infact I tested that commit and all worked fine for me. So I released it as `3.0.12`

**Comment by Xoandbit** [comment]
It is working now. Thanks
