### ISSUE TITLE
I have a problem with authentication

### ISSUE THREAD

**Issue by wuxiangwa** [adonisjs/adonis-framework#525]
```js
authenticator: 'jwt',
 jwt: {
    serializer: 'Lucid',
    model: 'App/Model/User',
    scheme: 'jwt',
    uid: 'phone',
    password: 'password',
    secret: Config.get('app.appKey'),
    options: {
      expiresIn: 36000
    }
  }
```
if i want two or more authentication，what should i how to do?

and  i have another question?
when i use jwt.   yield request.auth.logout()

```
"error": {
    "message": "request.auth.logout is not a function",
    "name": "TypeError",
    "status": 500,
    "frames": [
```

**Comment by dguzman1012** [comment]
Hi!

What do you mean with "two or more authentication?"

>>> About the 2nd question: You don't need the logout method since JWT method validate every http request via Header, so if you have to logout your user just delete your localstorage/session on your app.

**Comment by thetutlage** [comment]
Please format your issues properly, since it will only take a minute and saves a lot of times for others.

To have multiple authentication schemes in place, you can make use of the auth middleware as following


```js
Route
.get()
.middleware('auth:jwt,session')
```

**Comment by thetutlage** [comment]
Closing since no updates from the issue reporter
