### ISSUE TITLE
Troubles when i get logged in

### ISSUE THREAD

**Issue by dguzman1012** [adonisjs/adonis-framework#526]
Hello everyone!

I come here with a strange issue...

To be clear, i have developed a complete API Endpoint with AdonisJS v3.1 and I had no problems. Now i wanted to begin a new development with this new version (V3.2) and i get troubles with the simple Authenticating method... 

This is what i have till now:
My **routes.js**: 
![image](https://cloud.githubusercontent.com/assets/5767551/24335033/d539d0f0-1243-11e7-934a-4a94836a2584.png)

**My AccountController** (this is where my login method is located):
![image](https://cloud.githubusercontent.com/assets/5767551/24335039/f7f0c0cc-1243-11e7-91cd-79a47f3d7797.png)

**HomeController.js** (For dashboard once i get logged in):
![image](https://cloud.githubusercontent.com/assets/5767551/24335054/219d73d4-1244-11e7-8285-c753d1478fa7.png)

This is my **config/auth.js** file:
![image](https://cloud.githubusercontent.com/assets/5767551/24335059/449b1026-1244-11e7-8686-aa9314e2f05a.png)

Now, i have made everything is supose to do: Make the migration with `./ace auth:setup`, run migration and seeders, and of course the simple login form. But, everytime i try to logged into the app, it just crash: 
![image](https://cloud.githubusercontent.com/assets/5767551/24335099/ff4d70bc-1244-11e7-88f3-847d4b1a7970.png)

I am pretty sure that the Authenticating method is working because i made a test and is working... but i don't know what happens with that error... 

I have no idea what could it be... Does anyone have a clue?

Thanks in advance...

**Comment by thetutlage** [comment]
Mind sharing the content inside the `dashboard` view?

**Comment by dguzman1012** [comment]
Hello man! Thanks for response!

Better, i can give you a fresh installation:

[](https://bitbucket.org/dguzman1012/adonisjs-example/overview)

Thanks for your help!

**Comment by dguzman1012** [comment]
@thetutlage i have updated the repo... Thanks!
