### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by apatche7** [adonisjs/adonis-framework#527]
I want to use socket with adonis without websocket and i'm using adonis last version, what's the best way to use socket with adonis? 

Thanks.

**Comment by thetutlage** [comment]
Here's the documentation on websockets http://adonisjs.com/docs/3.2/websocket

**Comment by apatche7** [comment]
Like I mentioned without websockets cause doesn't work with services, Just need to know the best way to use it like normal node js

**Comment by apatche7** [comment]
Like I mentioned without websockets cause doesn't work with services, Just need to know the best way to use it like normal node js

**Comment by RomainLanz** [comment]
What's the definition of `socket` and `websocket` for you?

**Comment by apatche7** [comment]
websocket mades for websites and using socket with it, Right?

**Comment by RomainLanz** [comment]
May I ask why do you want to use a raw socket instead of using the `websocket`?

* [http://stackoverflow.com/questions/4973622/difference-between-socket-and-websocket](Difference between socket and websocket?)

**Comment by apatche7** [comment]
Because I want to build web services for android for a chat.

**Comment by duyluonglc** [comment]
@apatche7 You can use adonis-websocket for your server & socket.io-client-java for your android app

**Comment by tronghiep92** [comment]
Hi @duyluonglc,
 Are you sure this is possible?
`socket.io-client-java` and `socket.io-client-swift` working well with `adonis-websocket`?
