### ISSUE TITLE
Wrong input from multipart/form-data

### ISSUE THREAD

**Issue by andrasf** [adonisjs/adonis-framework#529]
Hi,

If I send input with ampersand sign from a form with files: true, I only get the part before the & sign.
So as a simple test 1&2 becomes 1.
My problem is I need to submit encoded html values from an editor, which only get received until the first &amp; entity.

Thanks,
András

**Comment by thetutlage** [comment]
Mind sharing the code where you are reading these values?

**Comment by andrasf** [comment]
I read a list of related datas, but its simply
```
description = request.input(`description-${i}`, '')
console.log(description)
```
If my input was `1&2`, `1` is logged to the console.

In Chrome Dev Tools is see
```
------WebKitFormBoundarypbXmRTmeTjxIfZrM
Content-Disposition: form-data; name="description-0"

1&2
```

**Comment by andrasf** [comment]
I created a new empty project.

routes.js:
```
'use strict'

const Route = use('Route')

Route.get('/', 'TestController.index')
Route.post('/', 'TestController.print')
```

TestController:
```
'use strict'

class TestController {
  * index (request, response) {
    yield response.sendView('welcome')
  }

  * print (request,response) {
    response.send(request.input('stuff'))
  }
}

module.exports = TestController
```

welcome.njk:
```
{% extends 'master' %}

{% block content %}
  {{ form.open({ action: 'TestController.print', files: true }) }}
    {{ csrfField }}
    <input name="stuff" />
    <input type="submit" />
  {{ form.close() }}
{% endblock %}
```

It acts the same way. Works fine without `files: true`.

**Comment by thetutlage** [comment]
Identified bug, working on the fix

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-middleware#10
