### ISSUE TITLE
Middleware not working as expected

### ISSUE THREAD

**Issue by GreWull** [adonisjs/adonis-framework#530]
Hi!

I want to always have avaiable all the request parameters in my views, so I've created a middleware which look like this.

 
 

```
* handle (request, response, next) {

    const view = use('View')

    view.global('request', request.all())

    yield next
  }
```

In my view I have a simple GET form. It has 1 input with name "search" so the url will look like this

> url.com?search=foo

Now the problem is that if I try to print "{{ request.search }}" after I've pressed the submit button I don't get the "foo", but if I try again with "search=bar" it will print the previous search, in this case "foo". This only happens with the middleware whereas in the controller everything seems fine.

Even stranger is that I have this problem only with OSX and not with Win10. 
Tried with node 6.9.2 and 6.10.0

**Comment by thetutlage** [comment]
You should not add values to the view global but instead add to the instance of view on the response object.

```
 response.viewInstance.global('request', request.all())
```

**Comment by GreWull** [comment]
Thanks! 

That fixed the problem, I used this solution:

```
response.viewInstance = use('View')
response.viewInstance.global('request', request.all())
```

For me it wasn't really clear reading it from the docs, you might want update it in the future :)

Keep up the good work!
