### ISSUE TITLE
No line number 

### ISSUE THREAD

**Issue by jamesAtcodeninja** [adonisjs/adonis-framework#532]
Line numbers are not reported when there is an error in a migrations file, which makes it tricky to pinpoint exactly where in the code the error is coming from.

<img width="469" alt="screen shot 2017-04-06 at 1 02 33 pm" src="https://cloud.githubusercontent.com/assets/26530591/24738640/8c6e7e8c-1ac9-11e7-961c-1c27d1f403ce.png">

**Comment by thetutlage** [comment]
Yup will fix it

**Comment by jamesAtcodeninja** [comment]
Seems to me that this is a app wide issue - 

`(node:5792) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'indexOf' of undefined
`
As you can see, the error messages are practically useless since they don't indicate where the problem is coming from.

**Comment by thetutlage** [comment]
This is not an app wide issue, this exception is thrown by the Nodejs itself, when you don't have a catch block on your promises.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
