### ISSUE TITLE
I cant clone the git repo

### ISSUE THREAD

**Issue by Aribros** [adonisjs/adonis-framework#536]
When I run the command "adonis new myApp", I get the following errors during npm install:

1. fatal: Unable to look up github.com (port 9418) (The  requested name is valid, but no data of the requested type was found. ).

2. npm ERR! Cloning into bare repository

**Comment by RomainLanz** [comment]
Hey @Aribros !

Which version of `git` and `adonis-cli` (`adonis -V`) are you using?

Also are you behind a proxy?

May you try to clone the repository manually?

```bash
$ git clone https://github.com/adonisjs/adonis-framework.git
```

**Comment by Aribros** [comment]
Thanks for your prompt reply. Below is the versions of packages i am running.

- $ adonis -V
- 2.1.9
- node v6.10.0
- npm  v3.10.10

git clone worked, I think the problem was with the 'npm install'.

I tried again and got the following errors.

$ npm install
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by RomainLanz** [comment]
Are you using windows?

**Comment by Aribros** [comment]
Yes

**Comment by thetutlage** [comment]
Seems to be an issue with your network unable to reach github

**Comment by RomainLanz** [comment]
It can also be that you haven't installed `git` correctly. I may recommend you to re-install it.

--> https://git-scm.com/
