### ISSUE TITLE
Asynchronous loops with yield?!

### ISSUE THREAD

**Issue by aleks63** [adonisjs/adonis-framework#538]
I want to make asynchronous this.task()
How???

```
 * tasks() {
    let tasks = yield Task.all()

    for(let task of tasks) {
      yield this.task(task)
    }
  }
```

**Comment by RomainLanz** [comment]
Hey @aleks63 !

Your code is correct. Do you get any errors?

**Comment by aleks63** [comment]
Hello @RomainLanz

No errors. But yield this.task(task) blocks every loop.
I wanna make every loop async and parallel. How?

**Comment by duyluonglc** [comment]
@aleks63 you can yield a function or an array of functions to call parallel
```js
 * tasks() {
    let tasks = yield Task.all()
    let doTasks = []
    for(let task of tasks) {
      doTasks.push(this.task(task))
    }
    yield doTasks
  }
```

**Comment by thetutlage** [comment]
Better is to use co-functional, an npm package for generators iteration

**Comment by thetutlage** [comment]
Closing since not actionable
