### ISSUE TITLE
Unable to use `adonis new`

### ISSUE THREAD

**Issue by lghenk** [adonisjs/adonis-framework#539]
### Brief Description
I downloaded the adonis-cli yesterday. Followed the installation tab on the documentary. 
when i execute `adonis new gcp` i get back an error

```
√ Your current Node.js & npm version match the AdonisJs requirements!

× An error occured while trying to clone master version of adonisjs/adonis-app blueprint.
Command failed: git clone -b master --single-branch https://github.com/adonisjs/adonis-app.git D:\Project Files\RealMenOfGenius\NodeJS-Ports\gcp
fatal: Too many arguments.
```

### Sample Code
`adonis new gcp`

### Screenshots (if any)
http://prntscr.com/ewg1nj

**Comment by thetutlage** [comment]
What version of git you have?

**Comment by lghenk** [comment]
@thetutlage i have `version 2.11.1.windows.1`. 

After updating to the latest version 2.12.2 i still have the same problem. 

```
$ adonis new gcp-test
    _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

√ Your current Node.js & npm version match the AdonisJs requirements!

× An error occured while trying to clone master version of adonisjs/adonis-app b                                                                                                                                                                                               lueprint.
Command failed: git clone -b master --single-branch https://github.com/adonisjs/                                                                                                                                                                                               adonis-app.git D:\Project Files\RealMenOfGenius\NodeJS-Ports\gcp-test
fatal: Too many arguments.
```

**Comment by RomainLanz** [comment]
Hey @lghenk !

What happen if you run `git clone -b master --single-branch https://github.com/adonisjs/adonis-app.git gcp-test`?

**Comment by lghenk** [comment]
@RomainLanz That works.

**Comment by talski** [comment]
This error will still happen when your path has a space in it, it should be sanitized

**Comment by RomainLanz** [comment]
Hey @talski !

Are you using the new CLI with `npm i -g @adonisjs/cli`?

**Comment by talski** [comment]
I've installed with `npm i -g adonis-cli`

**Comment by RomainLanz** [comment]
May you try with the new CLI? (you can install it for the command I've wrote above)

**Comment by watzon** [comment]
So this still happens and I know the reason. If a path has spaces in it this error will occur because the path being passed to git isn't being wrapped in quotes. Git ends up seeing the spaces and thinks that you're using extra arguments.

**Comment by Shentia** [comment]
It solves after  download COMMAND LINE TOOLS FOR from https://developer.apple.com/download/more/
