### ISSUE TITLE
Integrate knex.js seed

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-framework#54]
It would be really nice to have a functionality to insert test or default data, after running database migrations. There is already an CLI as in `knex.js` [docs](http://knexjs.org/#Seeds-CLI) outlined.

> Seed files allow you to populate your database with test or seed data independent of your migration files.

Are there any plans to integrate that feature? What do you think about it?

**Comment by thetutlage** [comment]
check out trello its planned there
