### ISSUE TITLE
Handle commands

### ISSUE THREAD

**Issue by enniel** [adonisjs/adonis-framework#543]
How to run console commands from code like `Artisan:call(...)`?

**Comment by danilopolani** [comment]
@enniel do you ever solved it? Just including the command and running its `handle` method is limitating, 'cause you can't pass arguments. @thetutlage

**Comment by RomainLanz** [comment]
```js
const ace = require('@adonisjs/ace')

await ace.call('migration:run')
```

**Comment by danilopolani** [comment]
Does it work only with "default" ace commands? It tells me that my command "is not a registered command", but from terminal it works.

**Comment by MarkDylan49** [comment]
I'm having the same problem with @danilopolani "is not registered command"
