### ISSUE TITLE
Startup functions

### ISSUE THREAD

**Issue by douglasoliveira-sossego** [adonisjs/adonis-framework#544]
Hello,
Is there any place to insert startup functions?
That is, when I run "npm run serve" trigger this function.

**Comment by betaWeb** [comment]
Hi :),

I'm not pretty sure, but I think you can add your logic at the end of `then()` callback, in `bootstrap/http.js`, before or after server startup.
([https://github.com/adonisjs/adonis-app/blob/develop/bootstrap/http.js](url))

**Comment by thetutlage** [comment]
The best place is to listen for `Http.start` event, which is handled by `onStart` method inside `app/Listeners/Http.js` file.

**Comment by douglasoliveira-sossego** [comment]
Thanks @thetutlage

**Comment by camerlab** [comment]
Could you please tell me how to do it in Adonis 4?

**Comment by webdevian** [comment]
app/hooks.js

https://adonisjs.com/docs/4.0/ignitor#_hooks

**Comment by camerlab** [comment]
Thank you.
