### ISSUE TITLE
Auth with remember. How?

### ISSUE THREAD

**Issue by aleks63** [adonisjs/adonis-framework#545]
Auth with remember. How?

**Comment by wxs77577** [comment]
checkout the `authentication` in documents.

http://www.adonisjs.com/docs/3.2/authentication

```
'use strict'

class UsersController {

  * login (request, response) {
    const email = request.input('email')
    const password = request.input('password')
    const login = yield request.auth.attempt(email, password) 

    if (login) {
      response.send('Logged In Successfully')
      return
    }

    response.unauthorized('Invalid credentails')
  }

}
```

**Comment by aleks63** [comment]
No no. I used loginViaId.
And authorization is not permanent

**Comment by wxs77577** [comment]
You should use `cookie`

**Comment by aleks63** [comment]
But SESSION_DRIVER=cookie

**Comment by thetutlage** [comment]
@aleks63 you are doing it right, it's just the cookie gets expired a given point of time. I will add a an option to the `auth` module, which will create persistent cookie

**Comment by thetutlage** [comment]
Added in 4.0, docs will be out soon
