### ISSUE TITLE
Request::segment() in view

### ISSUE THREAD

**Issue by deathlover** [adonisjs/adonis-framework#549]
suppose URL is localhost/users/user
In view, in laravel to access URL in parts you have,
Request::segment(1) which returns "users"
Request::segment(2) which returns "user"
any helper in adonis?
don't want to be dependent on controller to pass the value to view by "sendView"

**Comment by thetutlage** [comment]
Why you want to do that? Sharing values from controller is fine

**Comment by thetutlage** [comment]
Closing since no response from issue reporter
