### ISSUE TITLE
CSRF Tokens work intermittently when using File as a session driver

### ISSUE THREAD

**Issue by sameffectdigital** [adonisjs/adonis-framework#551]
CSRF tokens throw a 'csrf token mismatch' exception intermittently and incorrectly when using File as a session driver. As soon as Cookie is re-instated as a session driver, the tokens work fine again. (You can get round the issue for one request by clearing your cookies, but then the issue re-appears).

Using version 3.0.13

**Comment by effectjared** [comment]
+1

**Comment by thetutlage** [comment]
@sameffectdigital Can u share some code or a sample repo showing the behavior. I just tested it and it works fine for all the requests

**Comment by thetutlage** [comment]
Closing it works fine and there is no update from the issue reporter. Feel free to re-open if you have more information
