### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kisese** [adonisjs/adonis-framework#552]
Hi, I have been unable to install Adonis for several days now, I am running windows 7. I keep getting stuck on the installing [dependencies](url) part. Attached is a screenshot. Kindly help.
![adonis_captur](https://cloud.githubusercontent.com/assets/6500360/25756916/3735549e-31d1-11e7-8167-f218cb365395.PNG)

**Comment by RomainLanz** [comment]
Hey @kisese !

Do you get any errors?

May you try to clone the repository and install dependencies by yourself to see if it's working?

**Comment by kisese** [comment]
Hi Romain,
I tried again and it worked thanks for your help
