### ISSUE TITLE
Using MySQL JSON functions

### ISSUE THREAD

**Issue by phonghpham** [adonisjs/adonis-framework#554]
How can I make use of MySQL JSON functions for modifying JSON data type ? 
https://dev.mysql.com/doc/refman/5.7/en/json-functions.html

Is there a way to use Query Builder to make update queries using JSON_SET for example ?

**Comment by thetutlage** [comment]
@phonghpham Knex team is already working on adding the JSON support https://github.com/tgriesser/knex/pull/1902.

If it takes time on their end, I'll consider adding it, but I'll wait to see where this thread heads

**Comment by thetutlage** [comment]
Knex suggests using http://knexjs.org/#Schema-specificType and it works great for MYSQL versions, that supports it

**Comment by rohitdalal67** [comment]
Sir any update regarding this feature?

**Comment by thetutlage** [comment]
You must `specificType` column when creating migrations and for methods specific to json features should be executed via raw query
