### ISSUE TITLE
Simple routing will not work, saying 'Method missing on controller'.

### ISSUE THREAD

**Issue by rw3iss** [adonisjs/adonis-framework#561]
## Brief
I set up a simple route to try to render a view, but it's saying the method doesn't exist on the controller. I created the controller with the ace command line tool as normal.

The route code:
`Route.get('testy', 'UsersController.testy'); // 'test' doesn't work??`

And the controller code
/app/Http/Controllers/UsersController.js:
```
class UsersController {
	* testy (request, response) {
		yield response.sendView('welcome');
                // have also tried just "return response.sendView('welcome')" and also 
"response.send('blah')"
	}
}
```

It works if put the method definition inline to the route, ie: Route.get('test', function * testy() { // blah });

Otherwise, here's the error:
```
RuntimeException
E_UNDEFINED_METHOD: Method testy missing on App/Http/Controllers/UsersController
```

Do I have to do something after I create the controller or route? 

Or is Adonis broken with routes that utilize strings/'Controller.method' references?

**Comment by rw3iss** [comment]
Somehow I removed the module.exports = UsersController at the bottom of the file. Woops. 
Sorry for the confusion.

**Comment by gabsrl** [comment]
I had the exactly same problem. I also created a controller trough the adonis CLI (with adonis make:controller MyAwesomeController) and what I've noted is that, sometimes  Adonis don't put the module.exports in the end of the file. So we end up with this E_UNDEFINED_METHOD erro.
Thanks for make me not having to spend a lot of time trying to solve this simple problem :)
