### ISSUE TITLE
show paginate

### ISSUE THREAD

**Issue by m-alinasab** [adonisjs/adonis-framework#562]
hello .

please help me to show paginate from view.njk file and render page number in collection .

into laravel blade is : {{ $users->render() }}

for adonisjs ?
thanks .

**Comment by thetutlage** [comment]
That is more of a helper to paginate over results, and Adonis does not have one. The paginate method from **Model** returns following output, which can be used to create paginated links

```js
{
  total: 80,
  currentPage: 2,
  perPage: 10,
  lastPage: 8,
  data: [{...}]
}
```

Simply loop till the `lastPage` and each link will pass it's own page.

**Comment by m-alinasab** [comment]
thank you .
I know manual code ... but I was looking for a better way.
