### ISSUE TITLE
Difference between the filters of ‘action‘ and ’route’?

### ISSUE THREAD

**Issue by JKChen** [adonisjs/adonis-framework#566]
route.js
`Route.put('posts/:id', 'PostsController.update').as('postUpdate')`

posts/update.njk
`<form method="POST" action="{{ 'postUpdate' | action({id: post.id}) }}">`
**or**
`<form method="POST" action="{{ 'postUpdate' | route({id: post.id}) }}">`

What is the difference between the two above? Which is recommended?

**Comment by thetutlage** [comment]
Action is a reference to the controller action and route is the reference to the route definition or name.

```twig
<form method="POST" action="{{ 'PostsController.update' | action({id: post.id}) }}">
```

and 

```twig
<form method="POST" action="{{ 'postUpdate' | route({id: post.id}) }}">
```

**Comment by JKChen** [comment]
Got it.Thanks for teaching.

**Comment by thetutlage** [comment]
Closing!
