### ISSUE TITLE
How can i extend the 'linkTo’ or ‘linkToAction’

### ISSUE THREAD

**Issue by JKChen** [adonisjs/adonis-framework#567]
Both predefined by AdonisJs as follow:
**`linkTo(route, text, data, target)`**
route.js:
Route.get('/', 'PostsController.index').as('index')
view.njk:
`{{ linkTo('index', 'Home') }}`
output like:
`<a href="/">Home</a>`

How can i extend the 'linkTo’ like:
**`linkTo(route, text, data, target, attributes, icon)`**
and view.njk:
`{{ linkTo('index', 'Home', {}, '', {'class': 'btn btn-default', 'title': 'Home'}, '<i class="fa fa-home"></i>') }}`
and then output like:
`<a href="/" class="btn btn-default" title="Home"><i class="fa fa-home"></i> Home</a>`

The same as 'linkToAction':
`linkToAction(controllerAction, text, data, target)`

**Comment by thetutlage** [comment]
Simply use `route` filter. `linkTo` is kind of helper for quickly creating an anchor tag, for custom stuff it's better to use the route filter.

```twig
<a href="{{ 'index' | route() }}"> Home </a>'
```

**Comment by JKChen** [comment]
Wow~Thank you for sharing.
