### ISSUE TITLE
route * don't normal

### ISSUE THREAD

**Issue by shmy** [adonisjs/adonis-framework#568]
Hello ！
First of all, I'm sorry my English is very bad ！
This is my code：
```javascript
Route.any('/admin/*', function* (request, response) {
  yield response.sendView('admin/index')
})
```
open `http://localhost:3000/admin` display  
`Route not found /admin`
but open `http://localhost:3000/admin/` It is normal

I want to go to `http://localhost:3000/admin`  the normal
thanks!

**Comment by thetutlage** [comment]
Routes are more like regular expressions, so saying `admin/*` means `admin/` is always required. If you want to catch admin too.

You can say

```
Route.any('/admin*', function* (request, response) {
  yield response.sendView('admin/index')
})
```

**Comment by shmy** [comment]
thinks

**Comment by thetutlage** [comment]
Closing!
