### ISSUE TITLE
Adonis ORM User.all() crashes

### ISSUE THREAD

**Issue by chewedon** [adonisjs/adonis-framework#57]
Seeing some strange things happening.

When I use the code:

    * index (request, response) {
      let users = yield User.all();
      response.json(users);
    }

I get an error:

    { [Error: select * from "users" where "users"."deleted_at" is null - SQLITE_ERROR: no such column: users.deleted_at] errno: 1, code: 'SQLITE_ERROR' }

when trying to access my server:

    http://localhost:3333/users

However, when I go:

    * index (request, response) {
      const users = yield Database.table('users').select('*');
      response.json(users);
    }

I get the expected JSON response back without any errors.

I've just discovered Adonis a few hours ago, and taking it for a quick spin.

Also, can we please get some documentation on defining Models in Adonis, I mean setting the properties like username, password, email, and what datatype they're suppose to be etc.

The documentation so far only show how to generate a model using ace command, and how to override special functions such as `visible()` and `hidden()`.

How do we define our model properties ? 

Is it:

    class User extends Lucid {
        username: { type: 'string', length: 6 },
        email: { type: 'email' },
        age: { type: 'integer' }
    }

Nice framework so far.

**Comment by gearsdigital** [comment]
Lucid seems to require the field `deleted_at`. To fix that issue you need to add the field `deleted_at` manually.

To define a model you simply need to create a class and extend from `Lucid`. 

```js
// Models/UserModel.js
'use strict';
const Lucid = use("Lucid");
class User extends Lucid { }
module.exports = User;
```

If I understand you correctly you're looking for migrations:

```js
```

**Comment by chewedon** [comment]
When you say you manually added the delete_at field, are you talking about inside your User model class javascript file or are you talking about directly in the SQL file ?

What you've shown there is defining a User model but how does one specify the properties of that User model ?

At the moment, the User model is blank, it hasn't specified that a User model should have a username, or password, or email, or age, or gender, etc.

I have tried:

'use strict'

    const Lucid = use("Lucid")

    class User extends Lucid {
      constructor() {
        this.username = '';
        this.password = '';
      }
    }

    module.exports = User

Like how is demonstrated here: https://babeljs.io/docs/learn-es2015/

but I get a console error: 

`this is not defined`.

**Comment by thetutlage** [comment]
@chewedon there seems to be confusion, let me address them.

1. Adonis orm has a concept of `soft deletes` which means whenever you delete it is not deleted in database, infact a field called `deleted_at` is updated to mark the row as deleted. You can turn it off by inside your model.
http://adonisjs.com/docs/2.0/lucid#soft-deletes

2. Lucid is only a sql orm and follows active record pattern, so there is no need to define schema inside your models as they only makes model dirty and harder to read. In order to setup database you can use migrations using `ace` commands.

**Comment by chewedon** [comment]
@thetutlage hello, thanks for replying :D

1) Yes, I've read briefly about the soft delete but problem is, I am not even deleting, all I'm doing is fetching.

As you can see from my example code I've shown above, all I did was generate a new Adonis project, created a few User model and then tried to do a fetch all Users using the `User.all()` method but that itself caused a crash and said `delete_at` field is missing which it is when looking at the generated SQLite table itself.

I am not even doing any `delete` operation in my code. I was expecting `User.all()` to give me the same result as `Database.table('user').select('*')`.

If Lucid requires that `delete_at` field, and soft delete is on by default, how come the database migration didn't generate the field `delete_at` when user run the ace command to migrate database ?


2) So let's say a new project has been underway by one man. Then months later, a new developer come on board the team, in order for the new developer to know what properties an entity such as `User` has, he needs to open the SQLite file and look at all the columns OR go through every migration file and see what operation was done on the table schema, i.e. new column inserted, deleted, updated etc

If this new developer does not have access to the SQL database file because he's working remotely, if becomes an even bigger problem.

I don't see how schema inside a model class makes it dirty and harder to read than any other regular Object Oriented Programming Class.

You're already going to have code like:

```javascript
class User extends Lucid {

  posts () {
    return this.hasMany('App/Model/Post')
  }

}
```

Now the programmer needs to look at the `User` class to see what relationship it has, as well as the SQL file, i.e. two separate places to visit to get the information he needs.

Do you see that as a problem ?

Maybe I just need to get used to it :D

**Comment by thetutlage** [comment]
Okay, first when you are fetching rows, it is ORM responsibility to make sure you are not getting deleted rows (soft deleted rows), so the fetch query will have to add a where clause. 

Next having schema inside the model is a pain not a relief, may be from smaller point it seems nice but it take the flexibility of versioning a database. 

Here is a nice article which simply talks about why versioning of database is required. http://enterprisecraftsmanship.com/2015/08/10/database-versioning-best-practices.

It is all about design practices which are followed by Adonis, and every design practice comes with goods and bads.

Finally, why migration file does not create a deleted_at column, this is something needs improvement and will fix it. From going onwards, every new migration file will have `timestamps` and `deleted_at` column by default.

**Comment by chewedon** [comment]
I see. I'll venture on and see how well Adonis synergizes with me :D

So far, I was able to do a simple image upload, place the image file inside the public folder and it was served immediately on my views, so it is a good start, liking it so far.

**Comment by thetutlage** [comment]
Great :+1:

**Comment by thetutlage** [comment]
Create issue on `lucid` repo https://github.com/adonisjs/adonis-lucid/issues/12
