### ISSUE TITLE
Render HTML

### ISSUE THREAD

**Issue by gideaoms** [adonisjs/adonis-framework#570]
Hi,

Is it possible to render html and not nunjucks?

**Comment by RomainLanz** [comment]
Hey @gideaoms !

`nunjucks` is basically `html` on steroids. Is there any reason you don't want to use it?

**Comment by thetutlage** [comment]
Other way is to simply send HTML files using the `response.download` method.

Store HTML files inside `resources/static`

```js
const Helpers = use('Helpers')

Route.get('/', function * (request, response) {
  response.download(Helpers.resourcesPath('static/index.html'))
})
```

**Comment by gideaoms** [comment]
The reason is that I'm using angularjs.

I know there is a raw function, but I wanted to know if I could render the html directly

thanks.

**Comment by thetutlage** [comment]
Cool, closing
