### ISSUE TITLE
using query builder count() return is a problem

### ISSUE THREAD

**Issue by ajoslin103** [adonisjs/adonis-framework#573]
the QueryBuilder .count() function returns  [ { 'count(*)': 0 } ]

the result is clumsy to handle and doesn't seem to follow the docs

Adonis 3.2.1

**Comment by thetutlage** [comment]
@ajoslin103 Can u point out where it doesn't follow the docs?

**Comment by ajoslin103** [comment]
I wonder if perhaps I am doing something wrong.  In trying to determine if a scriptName is already in use I query using count, but I have to define a helper to deal with that return.

```
pluckCount = (fromThis) => Object.values(fromThis[0])[0]
let scriptCount = yield Database.table('tbl_scripts').where('scriptName', allegedScriptName).count()
if (pluckCount(scriptCount)) { // iow: when scriptCount == [{'count(*)':1}]
    response.conflict(`the name: '${allegedName}' is already in use`)
    return
}
```

how do you handle the results of count?

It seems clumsy to get a return that I cannot immediately use.  I looked on the knex site and they do not actually say what comes back either...  They say that the result when used over postgres is a string - but they do not state any actual example outputs.

it's difficult because the docs do not directly say what should be the result of a .count() -- although an earlier version does 

from: http://adonisjs.com/docs/3.2/query-builder
const total = yield Database.from('users').count()

from: https://adonisjs.com/docs/3.0/query-builder
const total = yield Database.from('users').count()
// Output - select count(*) from `users`
// Returns - [ { 'count(*)': 1 } ]

**Comment by thetutlage** [comment]
Sure, I will write that the underlying library is knex
