### ISSUE TITLE
How to code ajax post request in adonisjs?

### ISSUE THREAD

**Issue by min-naing** [adonisjs/adonis-framework#575]
I am facing ajax post request problem:
Here is my ajax post request code:
````javascript
var csrf_token = "{{ csrfToken }}"
$.ajaxPrefilter(function (options, originalOptions, jqXHR) {
            jqXHR.setRequestHeader('csrf-token', csrf_token);
          });

          $.post('/unit/create', {
            buy_unit: $('#buy_unit').val(),
            sell_unit: $('#sell_unit').val(),
            conversion: $('#conversion').val()
          }, function (data, status) {

            if (status == 'success') {
              alert(data);
            }

          });
````
and in my controller:
````javascript
* createUnit (req, res) {

    const buy_unit = req.input('buy_unit');
    const sell_unit = req.input('sell_unit');
    const conversion = req.input('conversion');

    console.log(buy_unit);
    res.send(buy_unit);
}
````
the error I've got is:
POST http://localhost:3333/unit/create net::ERR_NETWORK_CHANGED
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
n.(anonymous function) @ jquery-2.2.4.min.js:4
(anonymous) @ dish-management:490
dispatch @ jquery-2.2.4.min.js:3
r.handle @ jquery-2.2.4.min.js:3
@marcbachmann

**Comment by marcbachmann** [comment]
I have no idea why you mentioned me in here.
I'm not working on that framewoek.

That error looks weird.
I guess that error occurs when your network card changes the ip/network during a request.
Can you reproduce the error?

**Comment by thetutlage** [comment]
Yes it seems to be an error on the network
