### ISSUE TITLE
How to select hidden Lucid fields?

### ISSUE THREAD

**Issue by samgranger** [adonisjs/adonis-framework#58]
I have a model, let's say it's a User model.

In most cases I don't want the password to be returned, so I add it to hidden fields. How can I include a hidden field where I do need it, for example when authenticating a user logging in?

```javascript
yield User.select('id', 'username', 'password').where('username', credentials.username).fetch()
```
seems to fail here.

**Comment by thetutlage** [comment]
where have you defined hidden fields? 

also you are manually selecting password inside your query, is there any specific reason for that ?

**Comment by samgranger** [comment]
I have defined the hidden field in app/Model/User.js

I want to hide it in most cases, I just need access to the password in 1 case.

```
'use strict'

const Lucid = use('Lucid')
const Hash = use('Hash')

class User extends Lucid {

  static get table () {
    return 'users'
  }

  static get hidden () {
    return ['password']
  }

  posts () {
    return this.hasMany('App/Model/Post')
  }


  static get softDeletes () {
    return false
  }

}

module.exports = User
```

**Comment by thetutlage** [comment]
Do not use the fetch method, it is the place where all the magic happens. Also make sure that without fetch you will loose lot of features but if you have a simple select query, than you can remove it.

```javascript
yield User.select('id', 'username', 'password').where('username', credentials.username)
```

**Comment by samgranger** [comment]
Cheers, thank you!

**Comment by brendaniel** [comment]
@thetutlage 
`static get hidden () {` method is gone on version 4

`this.$hidden = this.constructor.hidden`  Base.js:L203
I think this code is part of it.
how can i hide models field?

**Comment by tlgreg** [comment]
@brendaniel It should still works the same (_actually the line you highlighted makes it possible to use the static getter_), just not in the docs currently.
```js
class User extends Model {
  static get hidden () {
    return ['password']
  }
}
```

**Comment by brendaniel** [comment]
@tlgreg thanks.

`Model.query().where().fetch();` => it works!

**Comment by RomainLanz** [comment]
FYI, PR has been merged 🎉 
https://github.com/adonisjs/docs/pull/200
