### ISSUE TITLE
BelongsToMany with HasManyThrough 

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-framework#587]
I have the following database
![screenshot_20170620_163400](https://user-images.githubusercontent.com/1662812/27335773-55ac85ae-55d6-11e7-9a2b-0aa42c6a7368.png)
`User` and `Page` models are linked with `belongsToMany`
```js
// App/Model/Page
users () {
  return this.belongsToMany('App/Model/User', 'user_pages')
}
```
```js
// App/Model/User
pages () {
  return this.belongsToMany('App/Model/Page', 'user_pages')
}
```
`Page` and `Post` models are linked with `hasMany` and `belongsTo`
```js
// App/Model/Page
posts () {
  return this.hasMany('App/Model/Post')
}
```
```js
// App/Model/Post
page () {
  return this.belongsTo('App/Model/Page')
}
```
How use **HasManyThrough Relationship** in this case?
I try linked `User` and `Post` models with `hasManyThrough`
```js
// App/Model/User
posts () {
  return this.hasManyThrough('App/Model/Post', 'App/Model/Page')
}
```
But when you try to get all the `posts` of the `user`, an error occurs:
```js
* posts (request, response) {
  const userId = request.param('users_id')
  const user = yield User.find(userId)
  response.json(yield user.posts().fetch())
}
```
```
select `posts`.*, `pages`.`user_id` from `posts` inner join `pages` on `pages`.`id` = `posts`.`page_id` where `pages`.`user_id` = '1108519435909240' - ER_BAD_FIELD_ERROR: Unknown column 'pages.user_id' in 'field list'
```

**Comment by thetutlage** [comment]
Yeah this is an interesting and valid use case. 

Lucid thinks that `user_id` will exist in pages table, whereas `pages` and `users` doesn't have a direct relationship but instead makes use of the pivot table. 

I am not 100% sure if there is any work around as of now. But I would try to add this feature.

**Comment by rohitdalal67** [comment]
First of all great work on Adonisjs really thank you for making Nodejs really easy. I want to ask if there is any progress regarding this topic?
Because I am also facing similar issues and I have following table structures
Users, Events, Event_Comments
and i am not able to load event_comments with events.

I am new to MVC and its awesome but not able to completely use it in Adonisjs because of Lucid. To fetch the event_comments now I have to loop through which I want to avoid.
Getting following error when fetching event details - 
**Undefined binding(s) detected when compiling SELECT query: select `event_comments`.* from `event_comments` where `id` in (?)**

Please help if there is any better alternative.

**Comment by cawa-93** [comment]
@rohitdalal67 As a temporary solution in my case:
```js
const userId = request.param('users_id')

// Select all page ids from user
const pages = Database.from('user_pages').where('user_id', userId).select('page_id')
// Select all posts from selected pages (use subquery)
const posts = yield Database.from('posts').whereIn('page_id', pages)

response.json(posts)
```

**Comment by rohitdalal67** [comment]
Sorry @cawa-93  I don't want posts of a specific user. I need a api in which I loads all the posts with last 5 comments along with user info who commented. For this I don't want to use loop the data needs to be in following format - 

`{
        "id": 41,
        "title": "Test",
        "descriptions": "Ok",
        "type": "Post",
        "image": "1499927025309.jpg",
        "admin_verified": "1",
        "admin_id": 0,
        "user_id": 24,
        "image_url": "Api/V1/resize/23-06-2017_02-56-17-693.jpg",
        "comment_counts": 8,
        "like_count": 1,
        "is_liked": 0,
        "timeago": "11d ago",
        "user": {
            "id": 24,
            "first_name": "Rishi",
            "last_name": "paul",
            "profile_pic": "22-06-2017_02-54-15-962.jpg",
            "profile_pic_url": "Api/V1/resize/23-06-2017_02-56-17-693.jpg"
        },
        "blog_comments": [
            {
                "id": 32,
                "blog_id": 41,
                "user_id": 29,
                "comment": "Teet",
                "deleted": "0",
                "blocked": "0",
                "timeago": "11d ago",
                "up_voted": 1,
                "down_voted": 0,
                "is_voted": "0",
                "user": {
                    "id": 29,
                    "first_name": "Test1",
                    "last_name": "Test1",
                    "profile_pic": "23-06-2017_02-56-17-693.jpg",
                    "profile_pic_url": "Api/V1/resize/23-06-2017_02-56-17-693.jpg"
                }
            },
            {
                "id": 31,
                "blog_id": 41,
                "user_id": 29,
                "comment": "Yes",
                "deleted": "0",
                "blocked": "0",
                "timeago": "11d ago",
                "up_voted": 0,
                "down_voted": 0,
                "is_voted": "0",
                "user": {
                    "id": 29,
                    "first_name": "Test1",
                    "last_name": "Test1",
                    "profile_pic": "23-06-2017_02-56-17-693.jpg",
                    "profile_pic_url": "Api/V1/resize/23-06-2017_02-56-17-693.jpg"
                }
            }
        ]
    }`

**Comment by RomainLanz** [comment]
Issue moved to [adonisjs/adonis-lucid #197](https://github.com/adonisjs/adonis-lucid/issues/197) via [**ZenHub**](https://www.zenhub.com/)
