### ISSUE TITLE
adonis-app ENOENT error on local machine

### ISSUE THREAD

**Issue by pmesgari** [adonisjs/adonis-framework#588]
### Brief Description
I simply cloned the repo of adonis-app to my local machine and then run the following two commands.
- npm install
- npm run serve
Here I get error 'ENOENT' with code '-4058' and the description says 'no such file or directory, open C:\PyCharm\vue\vue-adonis\adonis-app\\.env' 
There is already a file with full name ".env.example" in the root directory

### Screenshots (if any)
![adonis](https://user-images.githubusercontent.com/14719521/27428835-807d8e0e-5743-11e7-9722-abae0907a12b.PNG)

**Comment by msyagli** [comment]
Environment file name must be ".env". Can't find the file.

**Comment by RomainLanz** [comment]
Hey :wave: !

Adonis require the `.env` files to works correctly.
You can copy paste the `.env.example`.

Also, you must use the official CLI to install new Adonis application :)

**Comment by pmesgari** [comment]
The problem is solved. I copied the file and then renamed it to .env
Thanks!
