### ISSUE TITLE
535 node_modules?

### ISSUE THREAD

**Issue by Extarys** [adonisjs/adonis-framework#591]
At first I though it installed my default modules, but a clean and prune install of adonis install 535 node modules?

Well, maybe 533 since I installed RethinkDBdash.

Why so many modules?
Why installing mustache if we use nunjack?
Some things I'm not familiar with probably..

**Comment by RomainLanz** [comment]
Hey @Extarys ! 👋 

Development's dependencies install a lot of package, if you remove it you'll have 365 directories inside your `node_modules`. In version 4, `nunjucks` will be dropped in favor of `edge.js`, this will also remove a lot of dependencies.

Note that having 500+ packages or 10+ doesn't meen that your application will be slower or bloated. 😄

**Comment by Extarys** [comment]
Thanks for the info haha! Never heard of edge, never coded asp.net. Would I be able to use nunjucks? :D Learning nodejs with all those promises and awaits stuff is already complicated enough

**Comment by RomainLanz** [comment]
I think you got the wrong link 😄 

`edge` is a new JS templating engine builded by @thetutlage.

Here's the doc + repo :

* http://edge.adonisjs.com/
* https://github.com/poppinss/edge
