### ISSUE TITLE
gzip support.

### ISSUE THREAD

**Issue by pikitgb** [adonisjs/adonis-framework#592]
Hi guys there is anyway to use gzip with adonis ?

Regards.

**Comment by thetutlage** [comment]
I believe you can use any gzip library to create the response

**Comment by pikitgb** [comment]
Hi Vik, i'm trying to create a Middleware to compress the responses but the brower is displaying 
Content Encoding Error

'use strict'

const zlib = require('zlib');

class GzipCompressor {

  * handle (request, response, next) {
    // here goes your middleware logic
    // yield next to pass the request to next middleware or controller

    response.header('Content-Encoding','gzip');
    const output = zlib.createGzip();
    output.pipe(response.response);

    yield next
  }

}

module.exports = GzipCompressor

**Comment by pikitgb** [comment]
I have been trying to send the response with Gzip so i installed an NGINX server for a reverse proxy with the 
    gzip              on;
    gzip_http_version 1.0;
    gzip_proxied      any;
    gzip_min_length   500;
    gzip_disable      "MSIE [1-6]\.";
    gzip_types        text/plain text/xml text/css
                      text/comma-separated-values
                      text/javascript
                      application/x-javascript
                      application/atom+xml;

and the site is responding with gzip but the assets (js, css, images) are not. 
When the page renders in the browser the scripts and links tags try to resolve the files and the adonis process is delivering those files to the browser not the NGINX process.

Do you know any ways this can work ? 

Thanks a lot in advance!

**Comment by RomainLanz** [comment]
Hey @pikitgb ! 👋 

You probably need to change your NGINX configuration by adding a new `location` to `~/public` that will overwrite your default `proxy_pass` location.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter.
