### ISSUE TITLE
Proxying request?

### ISSUE THREAD

**Issue by jamesAtcodeninja** [adonisjs/adonis-framework#593]
Is there a way to proxy a http request to another server?

**Comment by thetutlage** [comment]
I believe you should use a proxy server for that, or maybe you can explain the situation better to understand what exactly u are trying to achieve?

**Comment by jamesAtcodeninja** [comment]
Sorry about that. Let's say I have two servers, `A` and `B`. I want any requests that do not get caught by `A`'s routes to be sent to `B`, and ultimately returned back to the client. The biggest issue I'm having is proxying requests for the rendered html page because I can't find a method on the adonis `response` object for sending rendered html.

**Comment by thetutlage** [comment]
The `response.sendView` can be used to render HTML views

**Comment by thetutlage** [comment]
Regarding proxying requests, do you want the URL also to get changed for the client or should it internal handled and response is sent to the user?

**Comment by thetutlage** [comment]
Closing, since no response from the issue reporter
