### ISSUE TITLE
Better Logo

### ISSUE THREAD

**Issue by Extarys** [adonisjs/adonis-framework#594]
I love the Adonis framework, but the blue logo is so bad (sorry)

Would be nice to have something more modern ;)

**Comment by thetutlage** [comment]
This is what we are using right now https://camo.githubusercontent.com/3062f3bd75d4d01202dbb1b88a42103b913e8fba/687474703a2f2f7265732e636c6f7564696e6172792e636f6d2f61646f6e69736a732f696d6167652f75706c6f61642f715f3130302f76313439373131323637382f61646f6e69732d707572706c655f707a6b6d7a742e737667

**Comment by dobromir-hristov** [comment]
The websites favicon is the old one.

**Comment by Extarys** [comment]
@dobromir-hristov that would explain my feelings then
