### ISSUE TITLE
Resourceful Routes DELETE missing from Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by froamer** [adonisjs/adonis-framework#597]
Hi, I have the following routes:

```
Route.group('api version 1', () => {

	Route.any('/user/login', 'UserController.login')

	Route
		.resource('user', 'UserController')
		.except('create', 'edit')

})
	.prefix('/api/v1')
```

When calling the delete endpoint, the browser requests OPTIONS, e.g. ...

    http://localhost:3333/api/v1/user/4

But DELETE is not returned as an allowed method:

    Access-Control-Allow-Methods:GET, PUT, POST

Is this a bug or are my routes configured incorrectly?

Many thanks for any help - Adonis is Outstanding!

**Comment by RomainLanz** [comment]
Hey @froamer ! 👋 

Thanks for your feedback, I'll fix this soon.

**Comment by thetutlage** [comment]
@froamer All you need to do is update the config file. The `DELETE` is left out, so that you should enable it manually and know what CORS changes you have done

https://github.com/adonisjs/adonis-app/blob/develop/config/cors.js#L23

**Comment by froamer** [comment]
Many thanks @RomainLanz and @thetutlage, that solved the issue.
