### ISSUE TITLE
I want to get a long string as result! but i cant not!

### ISSUE THREAD

**Issue by wuxiangwa** [adonisjs/adonis-framework#599]
I want to get a long string as  result!

demo: response.send("123456789012345678901")

and the result is '123456789012345680000'

so i want to know why  and how i can get the right result!

**Comment by thetutlage** [comment]
Are u sure u are sending the value as a string? The javascript has limitation on big ints, so a number like `123456789012345678901 ` will be converted to `123456789012345680000`, that's you should cast it as a string.


I just tried sending `123456789012345678901`  and I get the right output, but if u send it as a number then yes, it will be changed and that is a Javascript limitation.

<img width="290" alt="screen shot 2017-07-05 at 5 08 49 pm" src="https://user-images.githubusercontent.com/1706381/27862774-a258d72a-61a4-11e7-9c1f-43176704cc55.png">


<img width="313" alt="screen shot 2017-07-05 at 5 08 26 pm" src="https://user-images.githubusercontent.com/1706381/27862783-a933c44c-61a4-11e7-8677-37ae967c0ab9.png">
