### ISSUE TITLE
error in create new project

### ISSUE THREAD

**Issue by amirkheirabadi** [adonisjs/adonis-framework#6]
when i try create new project ...
this error happen ..

SyntaxError: Use of const in strict mode.

**Comment by thetutlage** [comment]
what version of node are you using ? make sure it is >=4.0

**Comment by amirkheirabadi** [comment]
node 0.12.7
npm 2.3.0

**Comment by amirkheirabadi** [comment]
i use iojs without nodejs and that is work ...
