### ISSUE TITLE
Code completion and code hinting

### ISSUE THREAD

**Issue by 7ammer** [adonisjs/adonis-framework#600]
Does anyone have any hints on code hinting for adonisJs in their IDE's.

When I'm working in PHPStorm for example (Been using it for Laravel) if I add an import to my javascript files I'm able to get code hints in my current file for that imported file. 

However PHPStorm isn't able to pickup the namespaces used with the use() function.

I appreciate that use() greatly helps with location awareness for my files visually but code hinting helps me write faster ;)

Also another benefit of imports/exports is that My IDE is aware of them and can type hint those two. If I change a files location My IDE also knows where to refactor all my import paths and does it for me.

I'm not saying I'd prefer to use imports as I like the 'namespacing' concept however I just wish it worked better with my IDE and was wondering if anyone had any tips.

Cheers :)

**Comment by 7ammer** [comment]
Hmm, I guess this isn't seen as an issue then.

**Comment by thetutlage** [comment]
Okay, so the `use` method is not a Javascript standard, so we as a community will have to work towards adding integrations for it.

Frankly saying I don't use any IDE's, so I am not sure when the support for this will come, I am happy to help anyone who is interested in doing it

If let's say no one adds any support for it, then i'll do it but when I am doing with everything else in following order

1. Vscode
2. Atom
3. Webstorm

**Comment by 7ammer** [comment]
@thetutlage, Thanks for the reply :) I'm glad to hear this is something you've thought about.

I found this for the IntelliJ Platform: 

1. [custom_language_support/completion_contributor](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/completion_contributor.html)
2. [custom_language_support/reference_contributor](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/reference_contributor.html)
3. [indexing_and_psi_stubs](http://www.jetbrains.org/intellij/sdk/docs/basics/indexing_and_psi_stubs.html)

But unfortunately I'd need to know Java to write the plugin and thats a bit over my head :L

This link for atom looks a bit more achievable: [creating-an-autocomplete-plug-in-for-atom](http://codersblock.com/blog/creating-an-autocomplete-plug-in-for-atom/). I _think_ I could work out how to capture each namespace into an array. However, after that I'm not sure how (or I don't know the standard way) I could tell atom to read the file for exposed methods, objects, variables etc and bring type hinting for those into the current file. (see below example taken from WebStorm)

![test2](https://user-images.githubusercontent.com/3194029/27993622-abb59552-64a5-11e7-8158-adbfaaa047c3.gif)

**Comment by thetutlage** [comment]
Will be done as part of #56
