### ISSUE TITLE
socket emit

### ISSUE THREAD

**Issue by fingil** [adonisjs/adonis-framework#601]
I have encountered a case where inside a socket controller,
      this.socket.emit('event', data)
is not detected in my browser by a listener, but 
      this.socket.toMe().emit('event', data)
is detected. I am not sure why!

**Comment by thetutlage** [comment]
The concept is called reflection, adonis by default doesnt emit the messages to the same client, you can use `socket.toEveryone().emit`.

Stopping reflection is helpful in so many conditions, for example

A chat application appends the message to the DOM once user sends the message, now if the same client gets an event for the same message, the message will be duplicated

**Comment by fingil** [comment]
Thanks @thetutlage.
