### ISSUE TITLE
Add `--inspect` argument to `serve:dev` command?

### ISSUE THREAD

**Issue by 7ammer** [adonisjs/adonis-framework#602]
Hello :)
I just found out that I can debug node / an adonis project from Chrome's DevTools console which is really useful.
I added the `--inspect` argument to the `serve:dev` script, ran it, opened `chrome://inspect/` and everything works!

I was thinking perhaps it might be something worth adding / documenting?

```json
  "scripts": {
    "serve:dev": "nodemon --inspect --watch app --watch bootstrap --watch config --watch .env -x node server.js"
  },
```

**Comment by thetutlage** [comment]
Yup will add it the faq's section, i am already working on it

**Comment by thetutlage** [comment]
In 4.0 `adonis serve --debug` can be used instead
