### ISSUE TITLE
Addon package development and loading routes from external file?

### ISSUE THREAD

**Issue by 7ammer** [adonisjs/adonis-framework#603]
Two questions:
How can I create a provider that gets run on boot of the app?
I've added my provider location to `bootstrap/app.js` however I now get an error:
```node
/Users/jamesisbell/Documents/Projects/Test/node_modules/adonis-fold/src/Registrar/index.js:33
    return new Module()
           ^
TypeError: Module is not a constructor
```

Inside the boot method I'd like to load some routes (for graphql) but I'm not sure how to do this. Is there a `loadRoutesFrom('file.js')` method similar to [laravel's method found here](https://laravel.com/docs/5.4/packages#routing)?

**Comment by thetutlage** [comment]
Can u share the provider code?

**Comment by 7ammer** [comment]
There currently isn't much of anything in there atm, its a WIP atm.

```javascript

const ServiceProvider = require('adonis-fold').ServiceProvider

class MyProvider extends ServiceProvider {

  * register () {
    console.log("test1 - register");
  }

  * boot () {
    console.log("test2 - boot");
    // publish some resources
    // load my package specific route.js file here
  }
}

```

I'm guessing from the error that I need to perhaps return some class somewhere?

**Comment by thetutlage** [comment]
U need to export the class

```js
module.exports = MyProvider
```

**Comment by 7ammer** [comment]
Oh bother \*facepalm\* I guess I was in a php mindset there where there is no exporting concept.

Moving on from that, is there currently a way to boot up a route file? The below test gives me this error: `Error: Cannot find module 'Route'`

```javascript
  * boot () {
    console.log("test2 - boot");
    // publish some resources
    // load my package specific route.js file here, below is a test
    const Route = use('Route')
    Route.get('/test', function * (req, res) {
      res.send('hello world')
    })
  }
```

**Comment by thetutlage** [comment]
The `Route` is an alias, which is supposed to be used within the app, the core providers should be never rely on aliases and should use the complete namespace ( ofcourse needs to be documented well )

```js
const Route = use('Adonis/Src/Route')
```

**Comment by 7ammer** [comment]
@thetutlage, ah that would be why! Thanks for the clarification, all is in working order now.
Cheers 👍
