### ISSUE TITLE
View global 'currentUser' can return users from other sessions

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#605]
Edit: Please don't shoot me for not posting this in adonis-auth, this seems like more of an issue with View globals than the Auth module, I think?

It seems like the currentUser global is some way detached from the current session and is perhaps yielding the user from another simultaneous request?

It happens whether CACHE_VIEWS is true or false

My scenario: 

I have a page where the navigation bar displays the current user's name. It does this using the currentUser global: 
``` Nav name: {{ currentUser.first_name }} ```

One particular page (profile) also has the current user passed through from the controller
```javascript
* show(request, response) {
	let user = request.auth.getUser()

	yield response.sendView('profile', {user})
}
```

This particular view also shows the user's name at the top of their profile
```Profile name: {{ user.first_name }} {{ user.last_name }}```

The user passed from the controller is always that of the currently logged in user, so profile name is always correct. 

The user passed from the global "currentUser" sometimes loads other users, thus nav name is often incorrect. 

An easy way to replicate this for me is to do some load testing as user 1, then login as user 2 in the browser. Each refresh of the page the nav name changes between user 1, user 2 and the logged out state. 

Introducing currentUser global into other templates can often lead to different results, also. 

So you could have on one load;
Layout View: currentUser.id = 2
Nav View: currentUser.id = 1
request.auth.getUser() = 2

Then another;
Layout View: currentUser.id = 1
Nav View: currentUser.id = 1
request.auth.getUser() = 2

**Comment by mikehhhhhhh** [comment]
As a follow up, I did some testing with the Auth middleware to check whether that was it;

The expected user is logged to console each time, so it seems like globals are getting mixed up between sessions for View? 

```javascript
  * handle (request, response, next) {
    const AuthManager = this.AuthManager
    request.auth = new AuthManager(this.Config, request)
    request.currentUser = yield request.auth.getUser()
    this.view.global('currentUser', request.currentUser)

    if(request.input('test') == "1") {
      console.log(request.currentUser.first_name)
    }

    yield next
  }
```

**Comment by thetutlage** [comment]
Can u share the version of adonis-auth u r using?

**Comment by mikehhhhhhh** [comment]
Hi @thetutlage - I'm using 1.0.5

**Comment by RomainLanz** [comment]
May you update to `1.0.7`?

**Comment by mikehhhhhhh** [comment]
I updated to 1.0.7 to no avail. 

However, doing a full ```npm update``` seems to have cured it.

I should have tried that last night, but tiredness prevails!

These are the relevant updates for reference in case anyone else finds this looking for the same problem;
```
├── adonis-ace@3.0.6 -> 3.0.8
├── adonis-framework@3.0.9 -> 3.0.14
├── adonis-lucid@3.0.13 -> 3.0.16
├── adonis-middleware@1.0.10 -> 1.0.14
```

**Comment by thetutlage** [comment]
Cool, closing then
