### ISSUE TITLE
Different http instances for http and ws when create a manual http instance

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/adonis-framework#606]
## Brief

Problem is work only https.

When i need switch node from http to httpS, I add necessary code in `bootstrap/http.js` for reassign httpInstance

Sample code from node doc https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

But, Ws not working. I found problem: Ws used other (first new) http instance.
This is the sequence of calls:

[node start] 
-> 
[load Ws] -> [Server.getInstance()] -> [Server.httpInstance is empty] -> [create new http.createServer()] 
-> 
[next step load Server in boostrap/http.js] -> [... my new code for create http instance ...] -> [we have 2 http server]

New code for written `bootstrap/http.js`:

```javascript
     /*
      |--------------------------------------------------------------------------
      | Load Middleware And Routes
      |--------------------------------------------------------------------------
      |
      | Middleware and Routes are required to oil up your HTTP server. Here we
      | require defined files for same.
      |
      */
      use(Helpers.makeNameSpace('Http', 'kernel'))
      use(Helpers.makeNameSpace('Http', 'routes'))
      
      const fs = require('fs')
      const https = require('https')
      const Server = use('Adonis/Src/Server')
      const options = {
        key: fs.readFileSync(Env.get('HTTPS_SERVER_KEY')),
        cert: fs.readFileSync(Env.get('HTTPS_SERVER_CERT')),
      };
      Server.httpInstance = https.createServer(options, Server.handle.bind(Server))

      /*
      |--------------------------------------------------------------------------
      | Load Websocket Channels And Middleware
      |--------------------------------------------------------------------------
      |
      | Websocket channels defination should be loaded before firing the Http
      | server.
      |
      */
      use(Helpers.makeNameSpace('Ws', 'kernel'))
      use(Helpers.makeNameSpace('Ws', 'socket'))
```

I send PR with changes

**Comment by ntvsx193** [comment]
https://github.com/adonisjs/adonis-app/pull/63

**Comment by thetutlage** [comment]
Not an issue with 4.0, since you bind any HTTP server inside `start/app.js` file

**Comment by annymosse** [comment]
how to run both of http and https (for redirect the http requests to the https)? @thetutlage
