### ISSUE TITLE
Could we add Github Release notes?

### ISSUE THREAD

**Issue by dobromir-hristov** [adonisjs/adonis-framework#608]
First of all I really like where Adonis is going. I have been keeping a close eye on it for at least an year but never had the chance to do something sensible with it.

Wanting to see the recent changes I went to the Releases section and it was bland, empty 😞 Looking at projects like Vue (which I use constantly) it has some nice release notes on each release (minor or major) so people can see what has been going on recently. 

You use conventional commits so a simple conventional-github-releaser or just to copy from changelog.md would be a start I guess. Then you could note the most important things in the release your self and BOOM. One more step to being an even more awesome framework !

Keep it up 😄

**Comment by thetutlage** [comment]
I generate `CHANGELOG.md` file using https://github.com/conventional-changelog/conventional-changelog https://github.com/adonisjs/adonis-framework/blob/develop/CHANGELOG.md

**Comment by dobromir-hristov** [comment]
Ye, so do I. Its great. You can try and implement their [github-releaser](https://github.com/conventional-changelog/conventional-github-releaser). It gets the latest generated thingy and adds it to the Release notes on Github when you push your release. 
You could just as well do it manually as well with the latest release notes copied from the changelog.

**Comment by thetutlage** [comment]
I agree. I believe we can do better job in creating release notes. I will write them by hand for github releases when everything else is done

**Comment by dobromir-hristov** [comment]
Awesome! Closing.
