### ISSUE TITLE
How to check exist record before insert in Lucid

### ISSUE THREAD

**Issue by shinaBR2** [adonisjs/adonis-framework#609]
Hello everybody. I have confused something in Lucid. How can I check a user has already existed in database? Should I take a query before every insert/create action? And, could I use `hook` for check exist user `beforeCreate`? My goal is alert for user if an username or email has already exist, but I can't handle MySQL error if I don't check exist before. So, anybody can help me? Any help will be appreciate :)

**Comment by RomainLanz** [comment]
Hez @shinaBR2 👋 

In this situation it would be better to [use validation](http://adonisjs.com/docs/3.2/validator).
You have rules to check in your database if X or Y exists.

**Comment by shinaBR2** [comment]
@RomainLanz thanks a lots 😮 but I have found another question. How can I use [validation](http://adonisjs.com/docs/3.2/validator) on client side? For example, I'm going to build a RESTful API with VueJS on the client side. Anyway to do this? ❓

**Comment by RomainLanz** [comment]
That shouldn't change to much.
Your API will send back an error object with validation's errors and you'll handle that directly with VueJS.

**Comment by shinaBR2** [comment]
Oh, I see that way. But it send a request to API, though. Can I goal my validation without send an ajax request? ❔

**Comment by RomainLanz** [comment]
Well, you cannot know if a user already exists without checking your database, so you need to send an AJAX request.

**Comment by shinaBR2** [comment]
Okay 👍 thank you very much 😃
