### ISSUE TITLE
Creating a seed file with predefined data?

### ISSUE THREAD

**Issue by 7ammer** [adonisjs/adonis-framework#611]
I'd like to create a seed file with predefined data like below? If I try and add this to a seed file I get `RuntimeException: E_MISSING_MODEL_FACTORY: Cannot find model factory for App/Model/Users/User`

```javascript
var users = [
      {
        handle: 'joyo',
        name: 'jo blogs',
        description: 'does stuff'
      },
      {
        handle: 'sarahsmarts',
        name: 'Sarah Smart',
        description: 'is smart'
      },
      {
        handle: 'robo',
        name: 'Robert Miller',
        description: 'Likes machines'
      }
];

for(var i=0; i<4; i++) {
   yield User.create({
        handle: test[i].handle,
        name: test[i].name,
        description: test[i].description
  })
}
```

**Comment by digoribeiro** [comment]
You forgot to import your `User` template

**Comment by 7ammer** [comment]
Ah, right I didn't need: `yield Factory.model('App/Model/Communities/Community').create(5)`
in my `Database.js` file.

I wish there was an example in the docs for creating / using a seed files. Currently there is only an example for creating factories.
