### ISSUE TITLE
Websocket in cluster mode

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/adonis-framework#612]
I used AdonisJS in one instance PM2.
I want use PM2 in cluster mode, but WebSocket not working.

Is it planned support WebSocket via Redis or something else?

**Comment by hoangmy92** [comment]
Could you share more detail?

**Comment by RomainLanz** [comment]
Info: https://github.com/adonisjs/discussion/issues/51

**Comment by RomainLanz** [comment]
Closing since all information is inside https://github.com/adonisjs/discussion/issues/51
