### ISSUE TITLE
Model relationships do not follow softdeletes on intersect tables

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#613]
I was unsure whether this should go in lucid or here, so please forgive me if I got it wrong. 

I have a belongsToMany that has an intersect table.

It associates a User as an admin of an Organisation through an intersect table "organisation_admins"

That intersect table has softdeletes enabled, but the relationship returns all results regardless of whether they have been deleted

```javascript
return this.belongsToMany('App/Model/Organisation','organisation_admins','user_id','organisation_id')
```

It is easily fixed with the following, but I feel like this should be implicit in the behaviour of belongsToMany?

```javascript
    return this.belongsToMany('App/Model/Organisation','organisation_admins','user_id','organisation_id').where('deleted_at',null)
```

**Comment by thetutlage** [comment]
Should be good with 4.0

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by dusbuss** [comment]
HI @thetutlage  - you said that this should be good to go with 4.0, but i don't see soft deletes in the docs for 4.0. Has it been removed?

**Comment by shinobiwarrior** [comment]
Hi, are there news about soft deletes?
@dusbuss could you find anything?

**Comment by dusbuss** [comment]
@shinobiwarrior - haven't found anything about it yet

**Comment by webdevian** [comment]
Still waiting for it, there’s an open issue on the Adonis lucid repo that has been assigned so any updates will be there

**Comment by webdevian** [comment]
https://github.com/adonisjs/adonis-lucid/issues/257

**Comment by shinobiwarrior** [comment]
Thanks to both of you, I'll subscribe to that issue
