### ISSUE TITLE
How to set character encoding in response header?

### ISSUE THREAD

**Issue by amitsch666** [adonisjs/adonis-framework#614]
NextJS, by default, serves a page with the charset information in a meta tag like this:

`<meta charset="utf-8" class="next-head">`

However, I am looking to serve this data embedded with the page header as:

`Content-Type: text/html; charset=UTF-8`

Is there any way to accomplish this? I have configured a custom Express server. In this file (server.js), I have tried the following two methods, neither of which seem to work. The one below throws a **TypeError: Cannot create property 'statusCode' on string 'utf8'**:

```
server.get('*', (req, res) => {
      handle(req, res.charset = 'utf8')
});
```
The following runs without error but does not do anything to the header:

```
server.get('*', (req, res) => {
      res.charset = 'utf8'
      handle(req, res)
 });
```
Any expert opinion would be wonderful!

**Comment by thetutlage** [comment]
First of all I don't understand from where express came into the picture?

**Comment by thetutlage** [comment]
Closing, since there is no response from the issue reporter and the issue itself is not clear
