### ISSUE TITLE
Invalid input syntax for integer: “null”

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#616]
I am trying to use PostgreSQL with my AdonisJS framework and perform a simple creation of a new user, but somehow, a weird query is performed and the error is shown. This is the code that will be executed:

    * store() {
      let isValid = yield this.validate()
    
      if (!isValid) {
        return false
      }
    
      if (this.id === null) {
        return yield this.create()
      }
    
      return yield this.update()
    }

    // ...
  
    * create() {
      const user = new User()
      const userHash = new UserProperty()
      const userSalt = new UserProperty()
      const salt = Encryption.encrypt(randomString.generate(32))
  
      try {
        user.firstName = this.firstName
        user.middleName = this.middleName
        user.lastName = this.lastName
        user.email = this.email
        user.imageUrl = this.imageUrl
  
        yield user.save()
  
        userHash.userId = user.id
        userHash.key = 'hash'
        userHash.value = yield Hash.make(this.password + salt, 10)
  
        yield userHash.save()
  
        userSalt.userId = user.id
        userSalt.key = 'salt'
        userSalt.value = salt
  
        yield userSalt.save()
  
        return {user}
      } catch (e) {
        this.addError(HTTPResponse.STATUS_INTERNAL_SERVER_ERROR, e.message)
  
        return false
      }
    }

But then:

> HttpException: error: select "email" from "users" where "email" = $1 and not "id" = $2 - invalid input syntax for integer: "null"

In here, the controller:

    * store(request, response) {
      const userOperation = new UserOperation()
  
      userOperation.id = request.param('id')
      userOperation.firstName = request.input('firstName')
      userOperation.middleName = request.input('middleName')
      userOperation.lastName = request.input('lastName')
      userOperation.email = request.input('email')
      userOperation.imageUrl = request.input('imageUrl')
      userOperation.password = request.input('password')
      userOperation.confirmPassword = request.input('confirmPassword')
  
      const store = yield userOperation.store()
  
      if (store === false) {
        let error = userOperation.getFirstError()
  
        throw new HttpException(error.message, error.code)
      }
  
      const user = yield User.findBy('email', userOperation.email)
      const token = yield request.auth.generate(user)
  
      response.send({
        user,
        token: token.token
      })
    }

I tried altering that line where it `findBy` the email to id, and even removed the line, but the error continues.

**Comment by thetutlage** [comment]
There are so many hidden pieces to your code, so it's not clear to me what really is happening.  To the bare minimum, you can share the complete error stack trace

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter

**Comment by jcs224** [comment]
I'm running into this too. Seems to be related to Postgres.
