### ISSUE TITLE
Question - How to connect to multiple postgres ?

### ISSUE THREAD

**Issue by dlucidone** [adonisjs/adonis-framework#617]

**Comment by thetutlage** [comment]
Can u share more description and use case of what exactly u r trying to achieve?

**Comment by dlucidone** [comment]
@thetutlage I have a local pg DB and a remote pg connection how can I use both of them.

**Comment by thetutlage** [comment]
@dlucidone Define 2 connections in your `config/database.js` file and switch them at runtime when making database queries.

```js
Database.connection('connection_name').table('users')
```

**Comment by dlucidone** [comment]
@thetutlage thanks a lot!
