### ISSUE TITLE
Question: How to alias column name with lucid ORM?

### ISSUE THREAD

**Issue by dlucidone** [adonisjs/adonis-framework#618]
Example
`SELECT column_name AS alias_name
FROM table_name
WHERE [condition];`

**Comment by armorkram** [comment]
Specify a select in the query builder and add the column name with an alias - `'column_name AS alias_name'`

Example:
```
const users = (yield TableName.query()
  .where(...)
  .select('column_name AS alias_name')).value();

data.forEach(user => console.log(user.alias_name))
```

**Comment by dlucidone** [comment]
@armorkram  thanks!

**Comment by PurwadiPw** [comment]
What if there are no columns and want to make an alias ?

Example:
```
select('"-" AS AgentPhone')
```
I got an error

`ER_BAD_FIELD_ERROR: Unknown column '"-"' in 'field list'`
