### ISSUE TITLE
Using adonis Request object instead of express Request in `download` and `attachment` 

### ISSUE THREAD

**Issue by stas-sl** [adonisjs/adonis-framework#619]
Hi, I see that you are currently refactoring some code there, but in 3.x version of adonis was the following code:

```
jsonp (body) {
  const callback = this.request.input('callback') || configInstance.get('app.http.jsonpCallback')
  nodeRes.jsonp(this.request.request, this.response, body, callback)
}
download (filePath) {
  nodeRes.download(this.request, this.response, filePath)
}
attachment (filePath, name, disposition) {
  nodeRes.attachment(this.request, this.response, filePath, name, disposition)
}
```
As can be seen in the `jsonp` method you pass `this.request.request` (express Request) to `nodeRes`, while in `download` and `attachment`, you pass `this.request` (adonis Request) that afterwards is passed to the `send` method in `node-res`:
```
Response.download = function (req, res, filePath) {
  send(req, filePath).pipe(res)
}
```
I believe `send` expects regular express request and response objects. So currently there is an issue with detecting `not modified` case, when browser sends `if-none-match` or `if-modified-since` headers. So we should either change `node-res`:
```
Response.download = function (req, res, filePath) {
  send(req.request, filePath).pipe(res)
}
```
or adonis Request:
```
download (filePath) {
  nodeRes.download(this.request.request, this.response, filePath)
}
attachment (filePath, name, disposition) {
  nodeRes.attachment(this.request.request, this.response, filePath, name, disposition)
}
```

**Comment by thetutlage** [comment]
Not sure which version you are referring to, but in 4.0, Adonis `Response` passes the native `req` object to `nodeRes`.

Also there is no usage of express anywhere in the framework

**Comment by stas-sl** [comment]
I refer to 3.0.14 version, but I see that `download` and `attachment` implementation didn't change in 4.0. So the issue should be there as well. You pass Adonis `Response` to nodeRes and from there directly to `send` module which, I believe, doesn't know about Adonis and expects express `req` and `res` objects.

**Comment by RomainLanz** [comment]
Hey @stas-sl !

Actually, `nodeRes` is made by @thetutlage and doesn't expect to have any `express` object. It use the default HTTP Request & Response from Node.js...

**Comment by stas-sl** [comment]
Hmm, sorry for confusion. Everywhere I wrote "express request/response" should be read as "default Node.js request/response". Now I see that this part actually changed in 4.0, so this issue probably will not be applicable to it. 

So it is applicable only to 3.0.14 because Adonis Response has reference to Adonis Request:
```
// Server/index.js

handle (req, res) {
  const self = this
  const request = new this.Request(req, res)
  const response = new this.Response(request, res)
  ...
}
```
which is later passed to nodeRes:
```
// Response/index.js

download (filePath) {
  // here this.request is Adonis Request
  nodeRes.download(this.request, this.response, filePath) 
}
```

But I'm not sure if you plan to support 3.x version

**Comment by thetutlage** [comment]
@stas-sl Yes, 3.x will be supported for another 6months, so I will look into it and will fix it.

**Comment by thetutlage** [comment]
Closing
