### ISSUE TITLE
Question - How to perform Operations as Opening Modal Popups or Custom JS in Application?

### ISSUE THREAD

**Issue by dlucidone** [adonisjs/adonis-framework#620]
Whats the best way to include additional js in this framework to carry out operations such as opening models and performing operations on view layer only?

**Comment by RomainLanz** [comment]
Hey @dlucidone !

What do you mean by "view layer only"?

**Comment by dlucidone** [comment]
@RomainLanz thanks for the reply! by view layer I mean if I want to carry out any prompting task without passing control to the controller and then sending view.
eg- I have a button with some critical operation on it so I'll open a modal popup for confirmation to the user and then pass action to the controller or let say before that I want to do some calculation and then sending it to the controller.

**Comment by thetutlage** [comment]
@dlucidone I don't think it has anything to do with Server or AdonisJs. Interacting with the DOM is purely a frontend task

**Comment by dlucidone** [comment]
@thetutlage yes it is, so any best way to achieve that.

**Comment by RomainLanz** [comment]
AdonisJs is a server-side framework to help you create application.

This issue has nothing to do with AdonisJs. Please ask those type of question in forums/chat but don't create an issue.

**Comment by dlucidone** [comment]
@RomainLanz sure
