### ISSUE TITLE
Adonis New Project Deploy Issue

### ISSUE THREAD

**Issue by arobit** [adonisjs/adonis-framework#622]
Trying to deploy adonis on DigitalOcean

Versions:
root@Adonis:~/apps/test.domain.com# npm -v
3.10.10
root@Adonis:~/apps/test.domain.com# node -v
v6.11.2

I've run git clone --dissociate https://github.com/adonisjs/adonis-app test.demoamin.com

Error when i run the following command
npm run serve:dev

Error: Cannot find module 'adonis-fold'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/apps/test.domain.com-adonis/bootstrap/http.js:14:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[nodemon] app crashed - waiting for file changes before starting...

Please help me sort this.

**Comment by RomainLanz** [comment]
Hey @arobit !

I recommend you to use the AdonisCLI !
You can install it with `npm i -g @adonisjs/cli` and then run `adonis new`.

Since you are using `git` directly you need to not forget to install dependencies by running `npm i` inside your application folder.

**Comment by arobit** [comment]
Hey,
Thanks for the quick reply,

I tried both ways.

I tried using CLI also but keep getting error


> adonis-app@3.2.1 serve:dev /root/apps/test.domain.com/yardstick
> nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js

sh: 1: nodemon: not found

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve:dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! adonis-app@3.2.1 serve:dev: `nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the adonis-app@3.2.1 serve:dev script 'nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/apps/test.domain.com/yardstick/npm-debug.log



Am i doing something wrong?

**Comment by thetutlage** [comment]
Does this work for you locally?

Also make sure to remove `node_modules` directory and do a manual npm install.

```
rm -rf node_modules
npm i
```

**Comment by arobit** [comment]
Hi,
Same error :( 

Yes on local it works.

i am doing this on digitalocean,
I deployed a test node app and that works fine. I followed this tutorial
https://code.lengstorf.com/deploy-nodejs-ssl-digitalocean/


However when i replace the contents by adonis framework the nginx error log shows this that i've drafted below and the when i type npm run serve:dev the above error comes.

2017/08/14 10:05:46 [error] 10610#10610: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 116.193.x.x, server: domain.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "test.domain.com"

127.0.0.1 >> This is written as Database Host in EMV, Why is it considering this as HTTP host?
How do i change this?

**Comment by arobit** [comment]
Sorry for Bumping.
Should i change the port and host/other details from the emv itself?

My Nginx is listening to port 3333

**Comment by thetutlage** [comment]
Yes you can change the port to whatever you want

**Comment by arobit** [comment]
Alight. 

But what about these errors 

Error: Cannot find module 'adonis-fold'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/root/apps/test.domain.com-adonis/bootstrap/http.js:14:14)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)

**Comment by thetutlage** [comment]
Can u see `node_modules` being created in the project root?

**Comment by arobit** [comment]
I'm sorry. I am new to this, How do i check if node_modules are being created?

if not what should i do?


This is my nom debug log, just in case

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle adonis-app@3.2.1~prestart: adonis-app@3.2.1
6 silly lifecycle adonis-app@3.2.1~prestart: no script for prestart, continuing
7 info lifecycle adonis-app@3.2.1~start: adonis-app@3.2.1
8 verbose lifecycle adonis-app@3.2.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle adonis-app@3.2.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/apps/test.domain.com/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle adonis-app@3.2.1~start: CWD: /root/apps/test.domain.com
11 silly lifecycle adonis-app@3.2.1~start: Args: [ '-c',
11 silly lifecycle   'echo "\\033[31mWARN: \'start\' will be depreciated soon. Instead use \'npm run serve\'" && npm run serve' ]
12 silly lifecycle adonis-app@3.2.1~start: Returned: code: 1  signal: null
13 info lifecycle adonis-app@3.2.1~start: Failed to exec start script
14 verbose stack Error: adonis-app@3.2.1 start: `echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid adonis-app@3.2.1
16 verbose cwd /root/apps/test.domain.com
17 error Linux 4.4.0-87-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error adonis-app@3.2.1 start: `echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve`
22 error Exit status 1
23 error Failed at the adonis-app@3.2.1 start script 'echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the adonis-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs adonis-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls adonis-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by thetutlage** [comment]
You can check by doing

Make sure you are in the root of the project

```
[ -d "node_modules" ] && echo "Yes"
```

Does this command output `Yes`?

If no then, run

```
npm install
```

**Comment by arobit** [comment]
It said YES


root@Adonis:~/apps/test.domain.com# [ -d "node_modules" ] && echo "Yes"
Yes
root@Adonis:~/apps/test.domain.com# npm start

> adonis-app@3.2.1 start /root/apps/test.domain.com
> echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve

WARN: 'start' will be depreciated soon. Instead use 'npm run serve'

> adonis-app@3.2.1 serve /root/apps/test.domain.com
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'adonis-fold'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/apps/test.domain.com/bootstrap/http.js:14:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.2.1 serve: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-app@3.2.1 serve script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/apps/test.domain.com/npm-debug.log

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.2.1 start: `echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-app@3.2.1 start script 'echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo "\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'" && npm run serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/apps/test.domain.com/npm-debug.log
root@Adonis:~/apps/test.domain.com#

**Comment by thetutlage** [comment]
Updated your comment, since it is the same stack trace. 

I am not sure why is this happening. Can u see the `adonis-fold` directory inside `node_modules`?

```js
[ -d "node_modules/adonis-fold" ] && echo "Yes"
```

Also can u share

1. Npm version
2. The operating system you are on

**Comment by arobit** [comment]
root@Adonis:~/apps/test.domain.com# [ -d "node_modules/adonis-fold" ] && echo "Yes"
root@Adonis:~/apps/test.domain.com# npm -v
3.10.10
root@Adonis:~/apps/test.domain.com#  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by thetutlage** [comment]
Which means npm is not installing `adonis-fold` module at all. Now would you mind sharing the `package.json` file

**Comment by arobit** [comment]
{
  "name": "adonis-app",
  "version": "3.2.1",
  "main": "server.js",
  "scripts": {
    "start": "echo \"\\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'\" && npm run serve",
    "dev": "echo \"\\033[31mWARN: 'dev' will be depreciated soon. Instead use 'npm run serve:dev'\" && npm run serve:dev",
    "serve:dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js",
    "serve": "node server.js",
    "lint": "standard"
  },
  "author": "",
  "license": "MIT",
  "description": "",
  "private": true,
  "dependencies": {
    "adonis-ace": "^3.0.7",
    "adonis-auth": "^1.0.5",
    "adonis-commands": "^2.1.5",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.10",
    "adonis-lucid": "^3.0.14",
    "adonis-middleware": "^1.0.11",
    "adonis-websocket": "^1.0.3",
    "youch": "^2.0.4"
  },
  "standard": {
    "global": [
      "use",
      "make"
    ]
  },
  "autoload": {
    "App": "./app"
  },
  "devDependencies": {
    "nodemon": "^1.11.0",
    "standard": "^10.0.1"
  }
}

**Comment by thetutlage** [comment]
Also do u get any errors when trying to run `npm install`?

**Comment by thetutlage** [comment]
And how about running `npm install adonis-fold --save`?

**Comment by arobit** [comment]
```
root@Adonis:~/apps/test.domain.com# npm install
Killed         ....] / extract:youch: sill doParallel extract 663
root@Adonis:~/apps/test.domain.com# npm install adonis-fold --save
adonis-app@3.2.1 /root/apps/test.domain.com
└─┬ adonis-fold@3.0.3
  ├─┬ cat-log@1.0.2
  │ ├── ms@0.7.3
  │ └─┬ npmlog@2.0.4
  │   ├── ansi@0.3.1
  │   ├─┬ are-we-there-yet@1.1.4
  │   │ ├── delegates@1.0.0
  │   │ └─┬ readable-stream@2.3.3
  │   │   ├── core-util-is@1.0.2
  │   │   ├── inherits@2.0.3
  │   │   ├── isarray@1.0.0
  │   │   ├── process-nextick-args@1.0.7
  │   │   ├── safe-buffer@5.1.1
  │   │   ├── string_decoder@1.0.3
  │   │   └── util-deprecate@1.0.2
  │   └─┬ gauge@1.2.7
  │     ├── has-unicode@2.0.1
  │     ├── lodash.pad@4.5.1
  │     ├── lodash.padend@4.6.1
  │     └── lodash.padstart@4.6.1
  ├── co@4.6.0
  ├─┬ co-parallel@1.0.0
  │ └── co-thread@0.0.1
  ├─┬ coveralls@2.13.1
  │ ├─┬ js-yaml@3.6.1
  │ │ ├─┬ argparse@1.0.9
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@2.7.3
  │ ├── lcov-parse@0.0.10
  │ ├── log-driver@1.2.5
  │ ├── minimist@1.2.0
  │ └─┬ request@2.79.0
  │   ├── aws-sign2@0.6.0
  │   ├── aws4@1.6.0
  │   ├── caseless@0.11.0
  │   ├─┬ combined-stream@1.0.5
  │   │ └── delayed-stream@1.0.0
  │   ├── extend@3.0.1
  │   ├── forever-agent@0.6.1
  │   ├─┬ form-data@2.1.4
  │   │ └── asynckit@0.4.0
  │   ├─┬ har-validator@2.0.6
  │   │ ├─┬ chalk@1.1.3
  │   │ │ ├── ansi-styles@2.2.1
  │   │ │ ├── escape-string-regexp@1.0.5
  │   │ │ ├─┬ has-ansi@2.0.0
  │   │ │ │ └── ansi-regex@2.1.1
  │   │ │ ├── strip-ansi@3.0.1
  │   │ │ └── supports-color@2.0.0
  │   │ ├── commander@2.11.0
  │   │ ├─┬ is-my-json-valid@2.16.0
  │   │ │ ├── generate-function@2.0.0
  │   │ │ ├─┬ generate-object-property@1.2.0
  │   │ │ │ └── is-property@1.0.2
  │   │ │ ├── jsonpointer@4.0.1
  │   │ │ └── xtend@4.0.1
  │   │ └─┬ pinkie-promise@2.0.1
  │   │   └── pinkie@2.0.4
  │   ├─┬ hawk@3.1.3
  │   │ ├── boom@2.10.1
  │   │ ├── cryptiles@2.0.5
  │   │ ├── hoek@2.16.3
  │   │ └── sntp@1.0.9
  │   ├─┬ http-signature@1.1.1
  │   │ ├── assert-plus@0.2.0
  │   │ ├─┬ jsprim@1.4.1
  │   │ │ ├── assert-plus@1.0.0
  │   │ │ ├── extsprintf@1.3.0
  │   │ │ ├── json-schema@0.2.3
  │   │ │ └─┬ verror@1.10.0
  │   │ │   └── assert-plus@1.0.0
  │   │ └─┬ sshpk@1.13.1
  │   │   ├── asn1@0.2.3
  │   │   ├── assert-plus@1.0.0
  │   │   ├── bcrypt-pbkdf@1.0.1
  │   │   ├─┬ dashdash@1.14.1
  │   │   │ └── assert-plus@1.0.0
  │   │   ├── ecc-jsbn@0.1.1
  │   │   ├─┬ getpass@0.1.7
  │   │   │ └── assert-plus@1.0.0
  │   │   ├── jsbn@0.1.1
  │   │   └── tweetnacl@0.14.5
  │   ├── is-typedarray@1.0.0
  │   ├── isstream@0.1.2
  │   ├── json-stringify-safe@5.0.1
  │   ├─┬ mime-types@2.1.16
  │   │ └── mime-db@1.29.0
  │   ├── oauth-sign@0.8.2
  │   ├── qs@6.3.2
  │   ├── stringstream@0.0.5
  │   ├─┬ tough-cookie@2.3.2
  │   │ └── punycode@1.4.1
  │   ├── tunnel-agent@0.4.3
  │   └── uuid@3.1.0
  ├── dwell@1.0.0
  ├── eventemitter2@2.2.2
  ├── lodash@3.10.1
  ├── node-exceptions@1.0.3
  └─┬ require-stack@1.0.2
    └─┬ syntax-error@1.3.0
      └── acorn@4.0.13

root@Adonis:~/apps/test.domain.com#

```

**Comment by thetutlage** [comment]
Now if you run the server?

**Comment by arobit** [comment]
npm start gives same error as before

**Comment by thetutlage** [comment]
Ohhh man! Let's take this conversation private on gitter. 

Just sigin with Github here https://gitter.im/adonisjs/adonis-framework and send a `hi` in the channel.

**Comment by thetutlage** [comment]
Closing since it worked

**Comment by WNemencha** [comment]
@thetutlage would you mind sharing the solution for this issue please?
