### ISSUE TITLE
Custom routes in Provider

### ISSUE THREAD

**Issue by blendsoft** [adonisjs/adonis-framework#625]
Hi,
I want to make module with Service provider, and put route rules there
So I made:

'use strict'
const ServiceProvider = require('adonis-fold').ServiceProvider
const Route = use('Adonis/Src/Route')

class PageServiceProvider extends ServiceProvider {

    * register() {
        Route.get('/pages', '../../Modules/Page/Http/Controllers/PageController.index')
    }

    * boot() {
        // Everything is registered do some hard work
    }
    
}
module.exports = PageServiceProvider

But this not works, I think bacause aliases are initialized after registering Providers 
How can I set custom route rules in Provider/Module
Thanks

**Comment by thetutlage** [comment]
You should do this in `boot` method and not the `register` method. Also the path has to be a valid IoC container namespace.

```js
const ServiceProvider = require('adonis-fold').ServiceProvider

class PageServiceProvider extends ServiceProvider {
    * register() {
        this.app.bind('Modules/PageController', () => {
            const PageController = require('../../Modules/Page/Http/Controllers/PageController.index')
            return new PageController()
        })
    }

    * boot() {
        const Route = use('Adonis/Src/Route')
        Route.get('/pages', 'Modules/PageController')
    }
}
module.exports = PageServiceProvider
```

**Comment by blendsoft** [comment]
Wow, Its better than I thought, Thanks,
