### ISSUE TITLE
Adonisjs 4 And custom providers

### ISSUE THREAD

**Issue by blendsoft** [adonisjs/adonis-framework#626]
Hi,
I see that 4th version came with shortcuts like @adonisjs, but now I can't register my custom providers with path, i tried @app with no success, where can I check available shortucts, and how to define my own shortcuts ?

**Comment by thetutlage** [comment]
Can u share some code on what really u mean

**Comment by blendsoft** [comment]
Ok, I made this using path.join
But still it would be nice to define custom shortcuts
for example
@page for my Page module

const providers = [
    '@adonisjs/framework/providers/AppProvider',
    '@adonisjs/auth/providers/AuthProvider',
    path.join(__dirname, '../app/Modules/Page/Providers/PageServiceProvider'),
   '@page/Providers/PageServiceProvider'
]

**Comment by blendsoft** [comment]
closed
