### ISSUE TITLE
TDD approach encouraged by the framework or not?

### ISSUE THREAD

**Issue by aitchkhan** [adonisjs/adonis-framework#630]
Does the framework encourage developers to write unit tests, integration tests and e2e test for their web applications?
Does it provide any tools out of the box? Or the configurations, selection of tool is left to the developer?
Am i missing any docs? If yes, please share with me the docs related.

**Comment by thetutlage** [comment]
Yes there is an inbuilt service provider for writing and running tests.

```bash
adonis install @adonisjs/vow
```

The above command will setup tests for you and then just run `adonis test` to run the tests.

## What's pending?
The docs for all testing utilities are not out yet and I am working on it.

Also the browser client to write functional tests is not quite ready. As of today you can write Unit tests and API tests.

**Comment by aitchkhan** [comment]
okay, does it work for version >= `3.0`? 
I tried  `adonis install @adonisjs/vow`, but returns nothing.
I then ran `adonis test`, returns nothing.
**OS:** `Ubuntu 15.04`
**Engine:** `Node v6.10`
**adonis-cli**: `2.1.9`

**Comment by thetutlage** [comment]
Nope it is for 4.0 only
