### ISSUE TITLE
Error when create new project

### ISSUE THREAD

**Issue by muzichen** [adonisjs/adonis-framework#631]
![_20170901094232](https://user-images.githubusercontent.com/7547416/29952176-4cb66e6c-8efa-11e7-8ead-f2f25b603d26.png)

**Comment by thetutlage** [comment]
Git is not able to access the url to clone it from GitHub? Want to try by cloning it manually

**Comment by RomainLanz** [comment]
Seems like an error on your Cmder installation with certificate.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
