### ISSUE TITLE
Module Structure

### ISSUE THREAD

**Issue by sotnaspina** [adonisjs/adonis-framework#633]
Hello!

First of all congratulations for the project, I did not really use it, but it seems to be a great project.
So, I would like to know if it has some modularized structure, for example in Laravel I use (https://nwidart.com/laravel-modules/v2/introduction) as a module structure.

Grateful.

**Comment by thetutlage** [comment]
This question must be part of the official forum. Since someone may have some ideas around it https://forum.adonisjs.com/
