### ISSUE TITLE
What about storage folder and path in 4.0?

### ISSUE THREAD

**Issue by aleks63** [adonisjs/adonis-framework#634]
What about storage folder and path in 4.0? #

**Comment by iamraphson** [comment]
@aleks63 According to this http://dev.adonisjs.com/docs/4.0/file-uploads. A folder called `tmp` is created in your project root during upload

**Comment by thetutlage** [comment]
Also please go through the upgrade guide http://dev.adonisjs.com/docs/4.0/upgrade-guide#_storage_tmp

**Comment by lucascarpio3** [comment]
how to serve tmp path?
