### ISSUE TITLE
Oracle npm i oracle<<Deprecated has a new driver: oracledb

### ISSUE THREAD

**Issue by everaldoglima** [adonisjs/adonis-framework#635]
http://dev.adonisjs.com/docs/4.0/database#_supported_databases

This library is not maintained.
The node-oracle driver is obsolete. Oracle has a new driver: node-oracledb.

Please install the new driver with 'npm install oracledb'.

**Comment by thetutlage** [comment]
Can creating a PR for same  at https://github.com/adonisjs/docs under `4.0` branch?
