### ISSUE TITLE
Syntax Error from install

### ISSUE THREAD

**Issue by aleks63** [adonisjs/adonis-framework#637]
> adonis start --dev

const { Command } = require('../../../lib/ace')
SyntaxError: Unexpected token {

/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/New/index.js:13

**Comment by RomainLanz** [comment]
Hey @aleks63 👋 

Which version of Node.js are you using?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter

**Comment by jimfilippou** [comment]
I am still facing this issue...

**Comment by webdevian** [comment]
@jimfilippou This is probably due to an older version of node

**Comment by jimfilippou** [comment]
Thank you @webdevian !
Upgrading Node from v6.10.0 to v8.9.1 fixed this issue, i don't even know why i had that version 😆
