### ISSUE TITLE
Created_at and Updated_at is null when using repl

### ISSUE THREAD

**Issue by Shubham-Sinha** [adonisjs/adonis-framework#638]
### Brief Description
I ran default User migration and then tried to create a new User using ``adonis repl``. The user got created but the timestamps were null.
### Sample Code 
```
await use('Database').table('users').insert({username: 'John',email: 'john@doe.com', password: 'password'})
```

**Comment by thetutlage** [comment]
Timestamps are set when u use models.

**Comment by Shubham-Sinha** [comment]
Thanks for your prompt reply. Btw I tried this but failed
```
await use('Database').table('users').insert({username: 'John',email: 'john@doe.com', password: 'password', created_at: `${new Date()}`, updated_at: `${new Date()}`})
```
![Screenshot](https://i.imgur.com/SD2UmdE.png)

**Comment by thetutlage** [comment]
Yes, the value from `new Date()` is not valid as per Mysql, so u need to format it properly or use moment to that easily.

If u want to save the current timestamp, then make use of `Database.fn.now()` function.

Running following code in repl should work

```js
Db = use('Database')
Db.table('users').insert({ created_at: Db.fn.now(), updated_at: Db.fn.now() })
```
