### ISSUE TITLE
Etag option ignored

### ISSUE THREAD

**Issue by mhingston** [adonisjs/adonis-framework#641]
### Brief Description

ETag header is being set when explicitly set to false in config.

### Sample Code

Set `etag: false` in `config/app.js`

### Screenshots (if any)

![image](https://user-images.githubusercontent.com/9764437/30318406-f0511dbc-97a4-11e7-8cf1-6fc002106013.png)

![image](https://user-images.githubusercontent.com/9764437/30318434-fd85c2da-97a4-11e7-981e-31ccf907f4f4.png)

**Comment by thetutlage** [comment]
I believe this is for static assets only. Can u share the full config file

**Comment by mhingston** [comment]
Hi @thetutlage, it seems to be set on all routes? I have a repro [here](https://github.com/mhingston/adonis-fullstack-app/commit/586cd7fbc88de6637a97fded68aa3f1a7ffcf21d).

When I request /test which returns a JSON response the ETag is still present.

![image](https://user-images.githubusercontent.com/9764437/30320128-a154574c-97a9-11e7-8d22-d5d996e2aca9.png)

**Comment by thetutlage** [comment]
If u look at the config file, the `etag` setting is inside the `static` section. Which means this setting only applies to the static resources served from the public dir

https://github.com/mhingston/adonis-fullstack-app/blob/586cd7fbc88de6637a97fded68aa3f1a7ffcf21d/config/app.js#L84

**Comment by mhingston** [comment]
@thetutlage sure hear what you are saying that the setting is for static assets only, but as the ETag header is also being set on responses which aren't serving static assets, how do I switch the Etag header off?

![image](https://user-images.githubusercontent.com/9764437/30321264-61c4a146-97ad-11e7-9909-74ccb8679abb.png)

**Comment by thetutlage** [comment]
Yeah there is no way to ignore `Etag` when making response from routes. I will add an option for it too

**Comment by twigs67** [comment]
Is there any update on this?
