### ISSUE TITLE
How to set up angular-cli?

### ISSUE THREAD

**Issue by roberbnd** [adonisjs/adonis-framework#643]
Hello
I want to configure angular-cli  and doc say I can use wildcard:

```js
Route.any('*', ({ view }) => view.render('main'))
```

my index.html is in "./ng-app/dist/index.html"
I don't know if it is in the right structure and how I can return a file that  it is not  .edge,
 in laravel I used  "File" and "public_path()" for this option

```php
Route::get('/{any}', function ($any) {
    return File::get(public_path() . '/start.html');
})->where('any', '.*');
```

**Comment by thetutlage** [comment]
You can still return an `.edge` view coz it's valid HTML

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
