### ISSUE TITLE
adonis4 route validation

### ISSUE THREAD

**Issue by protzi** [adonisjs/adonis-framework#644]
I want to use validation method on resources
```
Route
  .post('users', 'UserController.store')
  .validator('StoreUser')
```

something like this
```
Route.resource('users', 'UserController')
.validator('StoreUser')
```
on store method, is it possible to add this feature in future ?

**Comment by thetutlage** [comment]
But how do u which method will be validated by adding validator on the resource?

**Comment by protzi** [comment]
only on post or put

**Comment by thetutlage** [comment]
But

1. What if your validation rules are different for `post` and `put`?
2. How to find which rules are for `post` and which are for `put`?

**Comment by protzi** [comment]
I think that its very common that for some resource you need validation rules, so if you have such cool validation method `validate` and you cant use it on resources then you must choose to use validation inside controller or not to use resource and describe every route separatly, is it possible to extend this method for something like this and to use it on `Route.resource()` ?
```
.validate({
 store: 'StoreUser',
 update: 'UpdateUser'
})
```

**Comment by thetutlage** [comment]
This syntax makes sense, will add support for it

**Comment by thetutlage** [comment]
Added in https://github.com/adonisjs/adonis-validation-provider/commit/d58e57c5e85c97491d2f3c4b4d2d696f4e603091

The syntax is as follows

```js
Route
  .resource('users', 'UserController')
  .validator(new Map([
    ['users.store', 'StoreUser'],
    ['users.update', 'UpdateUser']
  ]))
```
