### ISSUE TITLE
Cannot store ObjectID data type to session store 

### ISSUE THREAD

**Issue by kamatcho** [adonisjs/adonis-framework#647]
when i'am trying to logged in That Error Appear 
Cannot store ObjectID data type to session store

Here's my Controller Function :- 

```js
   async login ({ request, auth }) {
    const { email, password } = request.all()
    await auth.attempt(email, password)

    return 'Logged in successfully'
  }
```

**Comment by RomainLanz** [comment]
Hey @kamatcho! 👋 

May you share the content of your `config/auth.js`?

**Comment by kamatcho** [comment]
'use strict'

module.exports = {
  /*
  |--------------------------------------------------------------------------
  | Authenticator
  |--------------------------------------------------------------------------
  |
  | Authentication is a combination of serializer and scheme with extra
  | config to define on how to authenticate a user.
  |
  | Available Schemes - basic, session, jwt, api
  | Available Serializers - lucid, database
  |
  */
  authenticator: 'session',

  /*
  |--------------------------------------------------------------------------
  | Session
  |--------------------------------------------------------------------------
  |
  | Session authenticator makes use of sessions to authenticate a user.
  | Session authentication is always persistent.
  |
  */
  session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Basic Auth
  |--------------------------------------------------------------------------
  |
  | The basic auth authenticator uses basic auth header to authenticate a
  | user.
  |
  | NOTE:
  | This scheme is not persistent and users are supposed to pass
  | login credentials on each request.
  |
  */
  basic: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'basic',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Jwt
  |--------------------------------------------------------------------------
  |
  | The jwt authenticator works by passing a jwt token on each HTTP request
  | via HTTP `Authorization` header.
  |
  */
  jwt: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: 'self::app.appKey'
    }
  }
}



i 'm using package called lucid-mongo

**Comment by thetutlage** [comment]
Can u just format your code blocks?

**Comment by thetutlage** [comment]
Also what's the output of `emai, password` when u `console.log` them

**Comment by kamatcho** [comment]
'use strict'

module.exports = {
  /*
  |--------------------------------------------------------------------------
  | Authenticator
  |--------------------------------------------------------------------------
  |
  | Authentication is a combination of serializer and scheme with extra
  | config to define on how to authenticate a user.
  |
  | Available Schemes - basic, session, jwt, api
  | Available Serializers - lucid, database
  |
  */
  authenticator: 'session',

  /*
  |--------------------------------------------------------------------------
  | Session
  |--------------------------------------------------------------------------
  |
  | Session authenticator makes use of sessions to authenticate a user.
  | Session authentication is always persistent.
  |
  */
  session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Basic Auth
  |--------------------------------------------------------------------------
  |
  | The basic auth authenticator uses basic auth header to authenticate a
  | user.
  |
  | NOTE:
  | This scheme is not persistent and users are supposed to pass
  | login credentials on each request.
  |
  */
  basic: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'basic',
    uid: 'email',
    password: 'password'
  },

  /*
  |--------------------------------------------------------------------------
  | Jwt
  |--------------------------------------------------------------------------
  |
  | The jwt authenticator works by passing a jwt token on each HTTP request
  | via HTTP `Authorization` header.
  |
  */
  jwt: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: 'self::app.appKey'
    }
  }
}
i'm using lucid-mongo for database

**Comment by thetutlage** [comment]
I delete ur last comments, since we got the config. I am asking for the `email` and `password` you receive as part of the request?

**Comment by kamatcho** [comment]
i did that 
  async login ({ request,session, auth }) {
   const test = await auth.attempt(request.input('email'),request.input('password'));
   console.log(test)

   // return 'Logged in successfully'
  }
here is the result
![screenshot at sep 18 13-26-16](https://user-images.githubusercontent.com/11474418/30539909-fcc25cb2-9c74-11e7-97ce-d778a9af44bb.png)

**Comment by thetutlage** [comment]
Yup the return value of `lucid-mongo` is an Model instance, which cannot be saved as a string to the session. You should raise this issue with the package author to fix the `serializer`

**Comment by kamatcho** [comment]
Ok Thanks I will ask him for That ..... Thanks for ur time

**Comment by thetutlage** [comment]
Closing since not actionable
