### ISSUE TITLE
Resource route

### ISSUE THREAD

**Issue by EdisonLV** [adonisjs/adonis-framework#649]
## Brief

If you have defined resource route like this
~~~
Route.resource('user', 'UserController')
~~~

and try to access /user/create route, adonis will start infinite loading process of the page.
But if you have specified each route separately, it works as expected.
~~~
adonis-app@3.2.1
~~~

**Comment by thetutlage** [comment]
Not sure that routing will do that. Can u share the code of your `UserController.create` method?

**Comment by EdisonLV** [comment]
simple as this
~~~
  * create (request, response) {
    yield response.sendView('create')
  }
~~~

Thanks

**Comment by thetutlage** [comment]
Tried it and it works fine. Not sure if you have something else that causes this issue. Best will be to share a sample repo that reproduces the issue

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
