### ISSUE TITLE
CSFR-TOKEN not working Adonis 4 (dawn)

### ISSUE THREAD

**Issue by stecapra** [adonisjs/adonis-framework#653]
Using :
  -adonis 4 (dawn)
  -axios
  -vuejs

If i send an AJAX request like that:

```
axios.post('/API')
.then(function () {
  console.log('done')
})
```
it returns 403 error, while using the same code in adonis 3.2 it works. 
I'm using vuejs front-end.
Check also the headers in the request, and 'x-xsrf-token' is sent correctly.

**Comment by thetutlage** [comment]
Everything works fine for me. Checkout this repo https://github.com/thetutlage/framework-653

**Comment by thetutlage** [comment]
Already fixed on `@adonisjs/shield` repo
