### ISSUE TITLE
how to get file from multipart/form-data POST request

### ISSUE THREAD

**Issue by bolt12** [adonisjs/adonis-framework#657]
## Brief

Please check the following notes before creating any issue. Well formatted and concise descriptions will help us address your issues quickly

### Is this just a query?
If your question is just a query and not a bug or feature request. Consider asking it inside the [Gitter Channel](https://gitter.im/adonisjs/adonis-framework)

### Do you have multiple questions?
Please keep an issue focused on a single concern. Asking too many questions will confuse everyone.

## Choose the correct repo
Everyone has a tendency of creating issues inside `adonis-framework` repo. Please note adonis is a combination of several repos and creating issues in their dedicated repos will help everyone track existing issues and their fixes in a better way. For example:

1. ORM related issues should go to [adonis-lucid](https://github.com/adonisjs/adonis-lucid)
2. Auth related issues should go to [adonis-auth](https://github.com/adonisjs/adonis-auth)

Please check the [organization home page](https://github.com/adonisjs) to see the list of repos

## Structuring The Issue

I dont know if this is the right place to ask but i cant get this information anywhere. All i want is to be able to get a file through a post request to '/upload' endpoint in my adonis REST server.

All i get are answers to do it using the view in adonis but i want to be able to access files from other POST requests.

### Brief Description

Example: I have a React Web App and I Submit a file form that sends a POST request to my adonis RESTful server.

I dont know how to get this file... I already tried using request.file and all other methods while debugging.. 

Can someone help me with this?

**Comment by RomainLanz** [comment]
Hey @bolt12 !

Please format your issue correctly, this is simply unreadable.

If you have a question and you aren't reporting a bug of the framework, use the forum instead https://forum.adonisjs.com/.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter

**Comment by evaleirasclapps** [comment]
Same here, any idea?
