### ISSUE TITLE
[Feature Request] Allow variables in .env

### ISSUE THREAD

**Issue by mattcdavis1** [adonisjs/adonis-framework#658]
It would be nice to be able to use variables in the .env file similar to Laravel.

```
PROTOCOL=https://
HOST_NAME=dev.mysite.com
HTTP_PORT=443
APP_URL=${PROTOCOL}${HOST_NAME}:${HTTP_PORT}
```

I realize i can set variables in the application via Env.set() but i'm not aware of anywhere i can do this early enough to be available for stuff like config/services.  Plus, it's more convenient to just do this all in one place.

PHP DotEnv reference: https://github.com/vlucas/phpdotenv#nesting-variables

**Comment by thetutlage** [comment]
Yes, seems quite relevant, will add support for it

**Comment by thetutlage** [comment]
Added in https://github.com/adonisjs/adonis-framework/commit/66d18d744481f6776ae6362e857a90757d429680

**Comment by mattcdavis1** [comment]
great - thanks!
