### ISSUE TITLE
Adonis 4.0.18 Weried bug

### ISSUE THREAD

**Issue by mikield** [adonisjs/adonis-framework#659]
Lets asume that we have such route 
```js
Route.get('v1/test/:name', async ({params}) => {
  return params.name
})
```
In this case the `params.name` will be returned as expected.
But if I will set prefix on this route. 
And the route will become something like this:
```js
Route.get('test/:name', async ({params}) => {
  return params.name
}).prefix('v1')
```
The `name` param is now `null`.

Added additional param to route, like this:
```js
Route.get('test/:name/:surname', async ({params}) => {
  console.log(params)
  return "next"
}).prefix('v1')
```
And got `{ name: null, surname: null }` in console.
So every param is `null` after prefixing the route.

**Comment by thetutlage** [comment]
Mind using `4.0.20` and lemme know if the problem persists?

**Comment by mikield** [comment]
@thetutlage no, its working normal again. using `4.0.21`.
Thank you :smile:
