### ISSUE TITLE
view filter json render issue

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#66]
escaped 

![image](https://cloud.githubusercontent.com/assets/2093743/12319740/553c2f90-badf-11e5-898f-0128fcd8025f.png)

**Comment by RomainLanz** [comment]
Can you show us some code?

**Comment by wtser** [comment]
view

```
{{ increase|json }}

<script src="/components/Chart.js/Chart.min.js"></script>
```

dom

![image](https://cloud.githubusercontent.com/assets/2093743/12319889/430f7bbe-bae0-11e5-90ed-99e569b4c4db.png)

**Comment by wtser** [comment]
![image](https://cloud.githubusercontent.com/assets/2093743/12319959/b27dced8-bae0-11e5-8086-ab8d2c4f4a0e.png)

looks good ,but it escaped

**Comment by RomainLanz** [comment]
It's the correct behaviour.

http://adonisjs.com/docs/2.0/views#auto-escaping

**Comment by wtser** [comment]
resolved, thank u
