### ISSUE TITLE
Route parameters regexp validation

### ISSUE THREAD

**Issue by danilopolani** [adonisjs/adonis-framework#661]
Is there a way to bind the route parameter to satisfy a specific regexp? For example, in Laravel, we can write `Route::get('user/{id}')->where('id', '[0-9]+')` to allow only numeric values as `id`.

I tried, in Adonis v4, to use `.where('id', '[0-9]+')` after the route but obviously it doesn't work.

**Comment by thetutlage** [comment]
There is no `.where` method, but you can define the regex inline.

```js
```

**Comment by danilopolani** [comment]
Oh, thank you! I have another question about the integration of eslint with adonis. The goal is to throw an error in the app (localhost:3333, not only on the console) if the lint fails. Before I open another issue, is that possible? At this time, with some edits on the `package.json` and the module `npm-run-all` I can check real-time the lint, but the errors appear only in the terminal.

**Comment by thetutlage** [comment]
Maybe you can ask this question on the forum. https://forum.adonisjs.com/
