### ISSUE TITLE
Is there a plan to build a debugger, especially for database query optimization purpose?

### ISSUE THREAD

**Issue by chabib** [adonisjs/adonis-framework#666]

**Comment by thetutlage** [comment]
You can still debug database queries by setting `debug:true` inside config file

**Comment by chabib** [comment]
Ah, I see. What do you think if the debugging option is added to the boilerplate?

**Comment by thetutlage** [comment]
Yes will do so

**Comment by chabib** [comment]
I can help

**Comment by thetutlage** [comment]
Sure feel free to create the PR
