### ISSUE TITLE
Creating beginner issues

### ISSUE THREAD

**Issue by m1guelpf** [adonisjs/adonis-framework#668]
I think it'd be a good idea to create some beginner issues to make contributions easier for newcomers.

For example, I come from the PHP world (specifically Laravel), and would love to start contributing, but I don't know where to start. It'd be helpful to have something like a `beginners-only` label.

**Comment by RomainLanz** [comment]
Hey @m1guelpf ! 👋 

If I correctly understand, you want us to "labelize" issue that are easy to fix?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
