### ISSUE TITLE
Is there any "OR" condition in Lucid ?

### ISSUE THREAD

**Issue by lhmboyz** [adonisjs/adonis-framework#669]
`const users = yield User.query()
      .where('name','tony')
      .whereHas('userTokens', (builder) => {builder.where('jti','abc')})
      .fetch()`

Those statements below will produce SQL like this:

`select * from users where name = 'tony' and user_tokens.jti = 'abc'`

Which will result no data if user's name = 'tony' but he doesn't have any token with jti = 'abc'.

How do i select users which name = 'tony' OR have token with jti = 'abc' ?

**Comment by thetutlage** [comment]
Try `orWhereHas`?

**Comment by lhmboyz** [comment]
There is no `.orWhereHas` and `.orHas` syntax, here is the error:

`"message": "User.query(...).where(...).orWhere(...).orWhereHas is not a function"`

**Comment by thetutlage** [comment]
Ohh you seems to be using older version of AdonisJs, is there any specific reason to stick to `3.x` and not use `4.0`?

**Comment by lhmboyz** [comment]
hi, i just follow the installation manual from the official site using this command:

`adonis new yardstick` and then

`npm install`

those give me 3.x version, how do i upgrade to 4.x?

by the way, i tried to install adonis-lucid using this command:

`npm i —save adonis-lucid@4.0.20` and it said can’t find the adonis-lucid with those version.

thank you friend

**Comment by thetutlage** [comment]
How you installed `adonis-cli`. Here are the docs for 4.0 http://dev.adonisjs.com/

**Comment by lhmboyz** [comment]
Ah i i think maybe because i still use node version 6 and that adonis v4 requires version 8 or greater, so i can’t install the lates adonis version.

I will try it soon, thank you so much friend for the help.

**Comment by thetutlage** [comment]
Sure 👍
