### ISSUE TITLE
Is it possible to marge or intersect or union two relations?

### ISSUE THREAD

**Issue by parvezr** [adonisjs/adonis-framework#670]
I wonder if relation like this possible in current version of AdonisJs

    userRelations() {
         return this.hasMany('App/UserRelation');
     }

    relatedUserRelations() {
        return this.hasMany('App/UserRelation', 'related_user_id');
    }

    allUserRelations() {
        return this.userRelations.merge(this.relatedUserRelations);
    }

That would be great. Thanks.

**Comment by thetutlage** [comment]
I don't get how this thing will work practically?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
