### ISSUE TITLE
Session data not being stored when route hit too quickly

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/adonis-framework#671]
Version:

3.0.14

Reproduce:

- Setup a route.
- Have the route store a param from the client in the session.
- Have the route fetch the value from the session and return it via response.json.

Expected Result:

The session has the data and the data is returned to the client - either both fails or neither fails.

Actual Result:

The session ends up having a null value but returns the proper value to the client.

Code in the controller for the route:

```
var guesses = yield request.session.get('guesses');
guesses[id] = {'id': id, 'guess':guess};
yield request.session.put('guesses',guesses);
var guesses_verify = yield request.session.get('guesses');
var guess_verify = guesses_verify[id];	
response.json({guess: guess_verify});
```

If the route is hit slowly you'll get valid results but if hit too quickly you'll get:

```
[ null,
  { id: 1, guess: 'false' },
  { id: 2, guess: 'true' },
  null,
  null,
  null,
  null,
  { id: 7, guess: 'true' },
  { id: 8, guess: 'true' } ]
```

The strange thing being that the server responded with a valid message for every missing result i.e. Submit with id=0 got a response of:

```
guess 
    id: 0
    guess: true
```

We are using cookies as our SESSION_DRIVER.

**Comment by RomainLanz** [comment]
Hey @RaymondLC92 ! 👋 

May you create a repository so I can reproduce this issue?

**Comment by RaymondLC92** [comment]
@RomainLanz 

Can do.

**Comment by thetutlage** [comment]
@RaymondLC92 Any updates?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by RaymondLC92** [comment]
We've resolved it, and future projects will be based on 4.0 anyways.

Unfortunately we also don't have the time to devote to fixing this, we have pending deadlines.
