### ISSUE TITLE
Adonis 4.0 remember me token & edge views

### ISSUE THREAD

**Issue by WeyIin** [adonisjs/adonis-framework#673]
There are few things I want to point out (mind if I do it for Edge too?)

- Full stack 4.0 ships with user migration okay, however the type field is missing so when migrating and using remember to store token in the db, an exception will be thrown. To fix that manually all you have to do is add another field called 'type' in a token table. 

- when using remember token it stores user token in a table. Using log out it just updates "is_revoked" to true. Shouldn't token be deleted on log out anyway? Because having 1000 tokens of 1 user loging in and out is a bit too much :)

Edge: 
appending content to a master layout using `@!section('content')` works fine, however using `@!section('content') ` (notice the whitespace AFTER closing parenthesis?) throws an error:

`InvalidExpressionException

E_INVALID_EXPRESSION: Invalid expression <'content') > passed to (section) `block``

I was looking for hours as of why it didn't work, while following edge docs closely.

**Comment by RomainLanz** [comment]
Hey @WeyIin ! 👋 

> Full stack 4.0 ships with user migration okay, however the type field is missing so when migrating and using remember to store token in the db, an exception will be thrown. To fix that manually all you have to do is add another field called 'type' in a token table.

This has been fixed in this commit https://github.com/adonisjs/adonis-auth/commit/d0382052aa16d60ed921a61709ae43bf622aec81.

> when using remember token it stores user token in a table. Using log out it just updates "is_revoked" to true. Shouldn't token be deleted on log out anyway? Because having 1000 tokens of 1 user loging in and out is a bit too much :)

Yes, I'll take a look with @thetutlage about this one.

For the issue about `Edge.JS`, may you create an issue in the official repo (https://github.com/poppinss/edge) ?

**Comment by WeyIin** [comment]
Hey @RomainLanz 

Thanks for letting me know! Issue raised in the official repo!

**Comment by thetutlage** [comment]
@WeyIin Yes it makes sense to delete the token, instead of just revoking it

**Comment by thetutlage** [comment]
The edge issue has been fixed, and the token one is related to `adonis-auth`, so creating an issue there instead.

https://github.com/adonisjs/adonis-auth/issues/66
