### ISSUE TITLE
500 Template render error,  RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by opqclick** [adonisjs/adonis-framework#674]
Having issue on view coz its generating this issue 500
**Template render error
(/home/hasnat/nodeJs/yardstick/resources/views/orders.njk) RangeError: Maximum call stack size exceeded**
i am trying to show 2996 records to this view orders.njk and its giving me this error.
my local envs are...
node: 8.6.0
npm: 5.3.0
adonis: 3.0.10

**Comment by RomainLanz** [comment]
Hey @opqclick ! 👋 

You must have an issue within your template.
May you share its code?

**Comment by WeyIin** [comment]
It happened to me as well but because I was copying template from another view.

You are probably including a template with @include that has @layout('master') in it. Check the template :) 
I solved my issue with removing @layout as it makes sense when including a view to a template

**Comment by thetutlage** [comment]
@WeyIin He is using `3.2` so his template engine is nunjucks and your example shows the usage of Edge.

@opqclick Seems to be more of nunjucks issue, would you please report it with them too.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by opqclick** [comment]
Sorry guys i am wasn't regular here after creating this issue.

**Comment by opqclick** [comment]
Here is my project link
https://github.com/opqclick/adonis-yardstick.git

i am using mysql for testing purpose. i am a newbie so may be there will be some silly mistakes so please help to learn.

**Comment by thetutlage** [comment]
Since you are getting started. I recommend using 4.0. Docs here http://dev.adonisjs.com/

**Comment by opqclick** [comment]
Thank you very much for your suggestion. i am a laravel lover so thanks for this build like laravel. its very easy to learn.
