### ISSUE TITLE
make:controller --resource Tag Not Generating Methods

### ISSUE THREAD

**Issue by borie88** [adonisjs/adonis-framework#675]
The CLI shows that the --resource tag is available, but it isn't generating the appropriate methods. Is anyone else having this issue?

*edit - It would be awesome if we could do make:model Model --mcr to make a migration and restful controller at the same time like in Laravel!

**Comment by RomainLanz** [comment]
Hey @borie88 ! 👋 

> The CLI shows that the --resource tag is available, but it isn't generating the appropriate methods. Is anyone else having this issue?

This has been fixed and should be released soon.

> It would be awesome if we could do make:model Model --mcr to make a migration and restful controller at the same time like in Laravel!

Same for this one.

```bash
adonis make:model Model -mc
```

**Comment by borie88** [comment]
That's great, thanks!
