### ISSUE TITLE
Revoke current Api Token on Logout

### ISSUE THREAD

**Issue by GencBlakqori** [adonisjs/adonis-framework#677]
How can I revoke the current used Api Token while logging out? Is there any function with which I can get the current used Api Token or do I have to do something like this:

`
yield request.auth.revoke(request.authUser, [request.header('Authorization').replace('Bearer ', '')])
`

**Comment by RomainLanz** [comment]
Hey @GencBlakqori ! 👋 

For those kind of question may you please use the forum?

https://forum.adonisjs.com/

**Comment by GencBlakqori** [comment]
Alright thank you!

**Comment by thetutlage** [comment]
Closing since not actionable
