### ISSUE TITLE
Controllers in version 4 ??

### ISSUE THREAD

**Issue by juanpscotto** [adonisjs/adonis-framework#679]
Where are the controllers in dev 4.0??

Thanks

**Comment by iamraphson** [comment]
@juanpscotto There is no default controller  but you can use `make:controller` to create one nand they will be stored in "app/Controllers/Http" directory

**Comment by juanpscotto** [comment]
Yes I understand. But the docs are missing in the version 4.
Version 3:
https://adonisjs.com/docs/3.2/controllers
Version 4 ??

**Comment by thetutlage** [comment]
@juanpscotto Thanks for pointing, will add it to the docs

**Comment by juanpscotto** [comment]
You're welcome. You can close this if you want. Thanks.

**Comment by tobiasdalhof** [comment]
Bump

**Comment by RomainLanz** [comment]
Hey guys, check https://github.com/adonisjs/docs/issues/190
