### ISSUE TITLE
request.flashAll() does not work as expected

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-framework#68]
Taking this very basic example `yield request.flashAll()`does not work as expected.

```js
// EventController.js
*index(request, response) {
    let view = yield response.view('event');
    return response.send(view);
}

*add(request, response) {
    console.log(request.all());
    yield request.flashAll();
    let view = yield response.view('event');
    return response.send(view);
}
```

```js
// routes.js
Route.get('/calendar/event/add/:timestamp', 'EventController.index');
Route.post('/calendar/event/add/:timestamp', 'EventController.add');
```

```html
<!-- event.html -->
<form method="post">
  <fieldset>
    <div>
      <label for="phone" class="required">Your Phonenumber</label>
      <input type="tel" name="phone" id="phone" value="{{ old('phone') }}">
    </div>
    <div>
      <button class="btn-primary">Submit</button>
    </div>
  </fieldset>
</form>
```
Okay, whats going on:

1. User comes to visit `/calendar/event/add/:timestamp` and gets `EventController.index`
2. User fills the form field `phone` with some input (maybe: lorem)
3. User clicks `submit `

Now `request.all()` looks like that: `{ phone: 'lorem' }` but `{{ old('phone') }}` is empty.

If he now clicks `submit ` again `request.all()` looks like that: `{ phone: '' }` but `{{ old('phone') }}` is now populated with `lorem`.

### Demo
![demo](https://cloud.githubusercontent.com/assets/965069/12321894/fb2acc88-bab0-11e5-8595-921c24e99850.gif)

**Comment by thetutlage** [comment]
Checking

**Comment by thetutlage** [comment]
Ideally you should not be making view from your `*add` method, you should redirect back to the `*index` method. If your save action is failing you should send the user back to the form instead of re-rendering the form.

## Your Routes

```javascript
Route.get('/calendar/event/add/:timestamp', 'EventController.index').as('calendarView')
Route.post('/calendar/event/add/:timestamp', 'EventController.add').as('calendarAction')
```

## Your Controller methods

```javascript
* index (request, response) {
  const view = yield response.view('index')
  response.send(view)
}

* add (request, response) {
  console.log(request.all())
  yield request.flashAll()
  response.route('calendarView', {timestamp: 10})
}
```

**Comment by gearsdigital** [comment]
Did not know about `{{ 'calendarAction' | route({timestamp: '10'}) }}`! Thank you. I assume this is the "default" process to handle forms, isn't it?

**Comment by thetutlage** [comment]
Yes, `route` filter on view helps you in using route alias, instead of it's defination. Which is more flexbile as you change the route path anytime later

**Comment by gearsdigital** [comment]
Cool. Thanks again... Works now as expected.
