### ISSUE TITLE
response.json(string) return invalid json

### ISSUE THREAD

**Issue by ayaka209** [adonisjs/adonis-framework#680]
### Brief Description
response.json(string) returns invalid json

### Sample Code
in a controller:

```
* index(){
yield response.json("asdf")
}
```

got asdf, should be "asdf"

**Comment by thetutlage** [comment]
I didn't get what u mean by `asdf` and `"asdf"`, since both are strings

**Comment by ayaka209** [comment]
```
"xxx"
```
is a string and is a valid json string,
but without quote, it's not a valid json string.

response.json expect returns a valid json, that can be parsed directly, but now, if I use response.json("asdf"), it returns a invalid json

**Comment by RomainLanz** [comment]
Maybe because returning only `"asdf"` is not valid either?

**Comment by thetutlage** [comment]
`response.json()` expects an object and convert it to JSON string. Since `adsf` is a string already you can return it as it is using `response.send()`

**Comment by ayaka209** [comment]
@RomainLanz  
``
JSON.parse('"asdf"');  // valid
JSON.parse('asdf'); // invalid
```

@thetutlage maybe response.json(string) should throw an exception instead of send invalid json string?

**Comment by RomainLanz** [comment]
Getting back here.

So `"asdf"` may be a valid JSON syntax representing a JSON value but per the [RFC-4627](http://www.ietf.org/rfc/rfc4627.txt) (which defines `application/json` format) you cannot use it as the complete body of an HTTP response.

You must use `response.send()` if you only want to send this string.
