### ISSUE TITLE
adonis new missing .gitignore

### ISSUE THREAD

**Issue by oscarmorrison** [adonisjs/adonis-framework#681]
### Brief Description
- when creating a project with `adonis new [project name]` 
the new project seems to be missing a `.gitignore` file.

```
//.gitignore

.env
node_modules/
```

**Comment by RomainLanz** [comment]
Hey @oscarmorrison! 👋 

There's a `.gitignore` file.
Are you using 3.2 or 4.0?

**Comment by oscarmorrison** [comment]
hmm.. not sure what happened their, resetup and was there
