### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by sebasgarcep** [adonisjs/adonis-framework#682]
Suppose I have the following endpoints: `GET /public`, `GET /protected`, `GET /private`, where the first one is accesible by anyone, the second only only by logged in users, and the third only by logged in users who happen to be admins on the site. How do I implement this without writing the authorization code inside the request handler?

**Comment by thetutlage** [comment]
1. `GET /public`: Route without any auth middleware
2. `GET /proctected`: Add `auth` middleware. http://dev.adonisjs.com/docs/4.0/authentication#_auth_middleware
3. `GET /private`: Create a new middleware, which checks for the user type and add it after the `auth` middleware on the route.

**Comment by sebasgarcep** [comment]
Can I add the auth middleware to every route by default and then specify which routes don't use it? I'm sorry for bugging you but I'm assessing whether AdonisJS is a better fit four our projects than other frameworks.

**Comment by RomainLanz** [comment]
You can create a Route's group for that.
http://dev.adonisjs.com/docs/4.0/routing#_route_groups

**Comment by sebasgarcep** [comment]
Nice!
