### ISSUE TITLE
Automatic Validation

### ISSUE THREAD

**Issue by sebasgarcep** [adonisjs/adonis-framework#683]
How to perform Validation automatically whenever we are writing to the database? This is so I can reuse a Model across Routes without having to repeat the validation logic on every route.

**Comment by RomainLanz** [comment]
Hey @sebasgarcep! 👋 

You can use Lucid Hook to run validation before saving.

**Comment by sebasgarcep** [comment]
I just wanted to point out that in v4 you can do this:

http://dev.adonisjs.com/docs/4.0/validator#_route_validator

I ❤️ AdonisJS!

**Comment by vivex** [comment]
There should be option in models to describe fields and their type and if they are required or not.

This way there will not be  any need to create extra validators, simply model.save() will throw an informative error that following field is missing or invalid.
