### ISSUE TITLE
Unixtime in tmp file name

### ISSUE THREAD

**Issue by 1001v** [adonisjs/adonis-framework#685]
Hello. I've reproduced sample code from [File uploads guide](http://dev.adonisjs.com/docs/4.0/file-uploads), and it seems that **request.file** method uses unixtime integer to name the tmp file. So the case when two different file upload instances get the same tmp file name isn't rare, i tested. Sometimes two-three upload requests would be enough to fire the issue. I bet the tmp file name should be more unique. Thank you.

**Comment by RomainLanz** [comment]
Hey @1001v! 👋 

Let me look into this.
May you provide a repository so I can replicate this issue?

**Comment by thetutlage** [comment]
Yeah, this can cause issue, maybe we can use a better way to define the unique names. I will make the change.

**Comment by RomainLanz** [comment]
Why not use the `[uuid](https://www.npmjs.com/package/uuid)` package?

**Comment by 1001v** [comment]
I think you could use Math.random() + Date.now()

**Comment by RomainLanz** [comment]
`Math.random()` + `Date.now()` will be for sure faster but it can still create colision.
 
Also, a simple `uuid` generator got `74,355 ops/s` which isn't to slow to be used imo.

```
function b(a){return a?(a^Math.random()*16>>a/4).toString(16):([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,b)}
```

**Comment by thetutlage** [comment]
@RomainLanz Thanks will make the required changes

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-bodyparser#2
