### ISSUE TITLE
base URL

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/adonis-framework#686]
Is it possible to set the base URL for the app?

I'm using Adonis 4.0 but I haven't found any examples even with 3.0

The intention is to setup developer instances:

i.e.

https://www.ourdomain/node/developername/

We cannot use subdomains.

**Comment by RomainLanz** [comment]
Hey @RaymondLC92! 👋 

Can you elaborate on this request?

**Comment by RaymondLC92** [comment]
@RomainLanz 

Sure.

We have multiple developers, we'd like all developer instances to be running on their own route (i.e. Apache style "sites").

i.e. https://www.ourdomain.com/developerOne (we're using port 5000 + some unique digits from our system id)
i.e. https://www.ourdomain.com/developerTwo
i.e. https://www.ourdomain.com/developerThree
i.e. https://www.ourdomain.com/developerFour
i.e. https://www.ourdomain.com/developerFive

The /node/ segment of the url is not necessary and I've had our system administrator remove it from the Apache config. We do this using proxy style redirects to our port.

Developers like myself will have a procedure like so:

1. npm run dev (an alias to start the server)
2. Our .env tells it to listen on our respective port.
3. We attempt to visit https://www.ourdomain.com/developerOne
4. The site mostly is broken. i.e. static images no longer function as images are fetched at "https://www.ourdomain.com/imagename.png" rather than "https://www.ourdomain.com/developerOne/imagename.png".

There doesn't seem to be a way to address this. Express has the capacity to set a base URL:

https://stackoverflow.com/questions/4375554/is-it-possible-to-set-a-base-url-for-nodejs-app#5994334

Is this possible in adonis?

**Comment by RomainLanz** [comment]
I think you can use the env variable `APP_URL` to do that.
May you try?

**Comment by akaiSuicchi** [comment]
Hello @RaymondLC92 
About point 4
> The site mostly is broken. i.e. static images no longer function as images are fetched at "https://www.ourdomain.com/imagename.png" rather than "https://www.ourdomain.com/developerOne/imagename.png".

This can be fixed with ```html <base href="./YOUR_NODE/">```

**Comment by cmd-space** [comment]
I would love to know whether this is possible as well. I have Adonis installed on a subdirectory, and all links are defaulting to base url without the subdirectory. For example: example.com/blog is home for Adonis, and once I click the link to sign up or login it takes me to example.com/login

**Comment by RaymondLC92** [comment]
@RomainLanz 

Sure thing, I can try it when my Sysadmin wakes up, he's seemingly removed the routes from the apache config.

@akaiSuicchi If Romain's solution doesn't work I'll add that.

I'll post in the morning once he's had an opportunity to reconfigure things again.

**Comment by RaymondLC92** [comment]
@RomainLanz I've attempted to add:

`APP_URL=https://mydomain/mydevid/`

I've also tried it without the protocol, however it had no effect.

@akaiSuicchi 

Setting the base causes a default-src issue.

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src URL"). Source: (function (ERROR) {`

Snipped my URL for privacy's sake.

**Comment by akaiSuicchi** [comment]
@RaymondLC92 that base tag goes inside head in your html.
I am not sure but I believe I misunderstood your issue.

@cmd-space this is more like your solution I think.

**Comment by RaymondLC92** [comment]
We're still stumped as to why this is causing a CSP issue.

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by rosnaib11** [comment]
We need this
