### ISSUE TITLE
Package architecture?

### ISSUE THREAD

**Issue by benallfree** [adonisjs/adonis-framework#687]
I'm thinking about an architecture for extension packages, like Laravel has. Something that boots a service provider, can have its own migrations, config files, models, views, controllers, routes, knows how to eject everything, etc. Is this being worked on or in planning already?

**Comment by benallfree** [comment]
Found it in adonis/drive, nevermind :)

**Comment by osman-mohamad** [comment]
any news about this adonisjs packages ?
