### ISSUE TITLE
Unhandled promises exception handler

### ISSUE THREAD

**Issue by benallfree** [adonisjs/adonis-framework#688]
Right now we don't output stack traces for unhandled promises.

https://github.com/nodejs/node/issues/9523#issuecomment-259303079

`process.on('unhandledRejection', r => console.log(r))`

Fixes it.

Is this something that is worth adding to the framework when in dev mode?

**Comment by thetutlage** [comment]
Yes, we can add this. But with a **bold** warning saying that all `async/await` should be wrapped inside try/catch and Promises should have `.catch` on them

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-ignitor#1
