### ISSUE TITLE
Adonis 4 : Seed and Factory

### ISSUE THREAD

**Issue by WeyIin** [adonisjs/adonis-framework#689]
From the docs:
http://dev.adonisjs.com/docs/4.0/seeds-and-factories

I was trying to figure out why I am getting an errors such as 
> { Error: ER_NO_DEFAULT_FOR_FIELD: Field 'username' doesn't have a default value
if field is not nullable. 

I have the very same code as in docs

```js
Factory.blueprint('App/Models/User', async (faker) => {
  return {
    username: faker.username(),
    password: faker.password()
  }
})

and dummy seeder : 
const users = await Factory
  .model('App/Models/User')
  .createMany(1000)
```

Now, an error will occur for every field in the DB that has not null. If I set it to nullable, all fields will become NULL after runing the seeder.

Removing ASYNC from factory blue print seems to fix an issue

**Comment by thetutlage** [comment]
The issue has already been fixed in https://github.com/adonisjs/adonis-lucid/commit/045d587b7bf0e35d7994cd858dbef85f4674fe33

Will be published soon.
