### ISSUE TITLE
API with Social Auth

### ISSUE THREAD

**Issue by sebasgarcep** [adonisjs/adonis-framework#691]
I'm working on using AdonisJS as an API-only in a small project. My problem right now is that while I have Social Auth via Ally working for Adonis Views, I haven't found a way to get it to work when using Adonis as an API service, because I don't know how to wire stuff together for this purpose.

**Comment by RomainLanz** [comment]
Hey @sebasgarcep! 👋 

Are you using 3.2 or 4.0?

**Comment by sebasgarcep** [comment]
Thanks @RomainLanz for answering! I'm using 3.2 by now. Does it matter?

**Comment by RomainLanz** [comment]
Yes, 4.0 are way different.

Could you paste your `package.json` to see if you aren't merging 3.2 and 4.0 package?

**Comment by sebasgarcep** [comment]
```json
{
  "name": "adonis-app",
  "version": "3.2.1",
  "main": "server.js",
  "scripts": {
    "start": "echo \"\\033[31mWARN: 'start' will be depreciated soon. Instead use 'npm run serve'\" && npm run serve",
    "dev": "echo \"\\033[31mWARN: 'dev' will be depreciated soon. Instead use 'npm run serve:dev'\" && npm run serve:dev",
    "serve:dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js",
    "serve": "node server.js",
    "lint": "standard"
  },
  "author": "",
  "license": "MIT",
  "description": "",
  "private": true,
  "dependencies": {
    "adonis-ace": "^3.0.7",
    "adonis-ally": "^1.1.2",
    "adonis-auth": "^1.0.5",
    "adonis-commands": "^2.1.5",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.10",
    "adonis-lucid": "^3.0.14",
    "adonis-middleware": "^1.0.11",
    "adonis-validation-provider": "^3.0.5",
    "adonis-websocket": "^1.0.3",
    "pg": "^7.3.0",
    "youch": "^2.0.4"
  },
  "standard": {
    "global": [
      "use",
      "make"
    ]
  },
  "autoload": {
    "App": "./app"
  },
  "devDependencies": {
    "nodemon": "^1.11.0",
    "standard": "^10.0.1"
  }
}
```

**Comment by sebasgarcep** [comment]
Or maybe you can't use Adonis Ally as an API-only?

**Comment by thetutlage** [comment]
@sebasgarcep Why do you think that Ally cannot be used when building Rest API?

**Comment by duyluonglc** [comment]
I think the issue https://github.com/adonisjs/adonis-ally/issues/29 can help.
In case build api-only service I have ` access_token` from client and do not need using the `code` from redirect url

**Comment by sebasgarcep** [comment]
@thetutlage I haven't found anything in the Adonis Ally docs that would allow me to generate and validate google+ access tokens.

**Comment by thetutlage** [comment]
I believe it's here http://dev.adonisjs.com/docs/4.0/social-auth#_basic_example

**Comment by sebasgarcep** [comment]
I'm closing as this issue is similar to adonisjs/adonis-ally#29.

**Comment by renztoygwapo** [comment]
how we can use the ally as an api only ?
