### ISSUE TITLE
Function auth.attempt(email. password) doesn't work

### ISSUE THREAD

**Issue by mrtranquanghieu** [adonisjs/adonis-framework#697]
When I am trying to log in, but `auth.attempt(email. password)` doesn't work?
Here's my Controller Function
`async login ({ request, auth, response }) {`
        `const { email, password } = request.all()`
        `console.log(email)`
        `console.log(password)`
        `const authCheck = await auth.attempt(email, password)`
        `console.log(authCheck)`
        `return response.redirect('/profile')`
`}`

**Comment by thetutlage** [comment]
What’s not working here?

- you get any errors
- the user is getting logged in

**Comment by mrtranquanghieu** [comment]
Sorry. I just learned about the framework. I did not attent to the Hook User, so I  hashed the password twice. I resolved the problem. Tks :)
