### ISSUE TITLE
Syntax Highlighting for Edge

### ISSUE THREAD

**Issue by sebasgarcep** [adonisjs/adonis-framework#698]
Are there syntax highlighting tools for Edge in any editor? VSCode, Atom, Sublime? If so, then which editors do you wish to support (if any)?

**Comment by duyluonglc** [comment]
@sebasgarcep check the doc
http://dev.adonisjs.com/docs/4.0/views#_syntax_highlighting

**Comment by sebasgarcep** [comment]
Oops, missed that!
