### ISSUE TITLE
CamelCase Serializer

### ISSUE THREAD

**Issue by sebasgarcep** [adonisjs/adonis-framework#699]
I have an use case right now where I need to autoload certain relationships and transform all fields to camelcase before sending them to the API consumer. I'm already autoloading the relationships using `.addGlobalScope` and it works fine, but I don't understand how to serialize my data as camelcase.

For example, when making an API call I get:

```json
{
  "id": 1,
  "name": "John",
  "last_name": "Doe",
  "posts": [{
    "id": 3,
    "title": "Hey!",
    "created_at": "..."
  }]
}
```

When I want:

```json
{
  "id": 1,
  "name": "John",
  "lastName": "Doe",
  "posts": [{
    "id": 3,
    "title": "Hey!",
    "createdAt": "..."
  }]
}
```

What is the most general way to achieve this result?

**Comment by thetutlage** [comment]
Rolling out a serializer is the only way do it. Lemme share some code for that.

```js
'use strict'

const _ = use('lodash')
const VanillaSerializer = require('@adonisjs/lucid/src/Lucid/Serializers/Vanilla')

class JsonSerializer extends VanillaSerializer {
  _getRowJSON (modelInstance) {
    const json = _.transform(modelInstance.toObject(), (result, value, key) => {
      result[_.kebabCase(key)] = value
      return result
    }, {})
    this._attachRelations(modelInstance, json)
    this._attachMeta(modelInstance, json)
    return json
  }
}

module.exports = JsonSerializer
```

Save it inside `app/Models/Serializers/JsonSerializer.js`

And use this as the serializer for your models.

```js
class User extends Model {
  static get Serializer () {
    return use('App/Models/Serializers/JsonSerializer')
  }
}
```

**Comment by RomainLanz** [comment]
Closing since the answer was given and there's no answer from issue reporter.

**Comment by walbertoibarra** [comment]
@thetutlage your solution works when returning data to the client, but how do you do the same transformation on your model, for example:
``` js
const User = use('App/Models/User')
const user = await User.find(1)

// Would like to access fields like this:
user.userName

// Instead of:
user.user_name
```

Also, would be nice to do the inverse.
``` js
const user = new User()

user.userName = 'test' // Transform it to 'user_name'
await user.save()
```

**Comment by sebasgarcep** [comment]
We write everything with JS: mobile, desktop, web, server. Using snake case on properties is uncomfortable when everything else in our stack is camel case. So I believe what @walbertoibarra pointing out is a valid concern in many use cases.

**Comment by thetutlage** [comment]
How about naming fields as `camelCase` within SQL?

It is going to be much pain in transforming fields on fly before and after every SQL query for Lucid.

**Comment by sebasgarcep** [comment]
@thetutlage I think many things in Lucid kind of expect snake case structure to work out of the box. I don't know how much of a pain in the ass it would be to use everything in camel case inside SQL.

**Comment by thetutlage** [comment]
I don't think Lucid should enforce casing for SQL. If there are hardcoded strings like that, I am happy to fix them

**Comment by chabib** [comment]
@thetutlage the thing is there is a problem using camelcase in column due to some operating system case sensitivity, you can look it up on the net

**Comment by thetutlage** [comment]
Yes, then you should rely on `snake_case` itself. I don't see any point of adding layers of converting keys to different cases before and after saving them to the DB.

Every weird layer has it's own complexity and I want to stay away from it.

**Comment by gweizi** [comment]
@thetutlage I think my question is relevant to this thread:
It's not even about converting different cases, but different names - Is there equivalent to columnName of Sails.Js attributes in Adonis/Lucid?

I couldn't find a proper workaround for this issue:
I can use computed properties as an alias for the field (getter) + hook beforeCreate/beforeUpdate for a setter (I haven't tried it yet, so I'm not sure it will work)
As I wrote, this is not a proper workaround and make it too complicated for maintenance.

Thanks!

**Comment by sebasgarcep** [comment]
@gweizi I think @thetutlage's solution is the most appropiate. Just name your fields with camelCase. I haven't tried it but it should work. The only thing that may require some extra work may be relationships as they expect a particular structure for foreign key fields by default, but you can provide your own.

**Comment by gweizi** [comment]
@sebasgarcep Probably I didn't explain my issue that well.
I give an example to make it more clear. Assume I have an exist database with a table called foo, this table has a column called "bad_name_666". I would like to create a model with a field called good_name that refer to the db column "bad_name_666". Is there any option to do that? or I must change the db scheme (in this case the column name bad_name_666 to good_name)?

Thanks again!

**Comment by thetutlage** [comment]
No there is no way to do that, since it adds a complexity layer on top of your database schema and also I have no plans to introduce anything like this.

The attributes should be 100% same as the database schema, since it's easier to reason about them

**Comment by xxxwww** [comment]
Objection.js, which is built top on knex.js, [has a tranform fields function](http://vincit.github.io/objection.js/#snake-case-to-camel-case-conversion). Adonis Lucid is also built on knex.js, so you can use this feature from objection.js

1. Install objection
```js
npm i objection
```

2. Add in top of `config/database.js`
```js
const { knexSnakeCaseMappers } = require("objection");
```

3. Add mappers to your connection. For example, change this

```js
  pg: {
    client: 'pg',
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      port: Env.get('DB_PORT', ''),
      user: Env.get('DB_USER', 'root'),
      password: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis')
    },
    debug: Env.get('DB_DEBUG', false)
  }
```

To this
```js
  pg: ({
    ...{
      client: 'pg',
      connection: {
        host: Env.get('DB_HOST', 'localhost'),
        port: Env.get('DB_PORT', ''),
        user: Env.get('DB_USER', 'root'),
        password: Env.get('DB_PASSWORD', ''),
        database: Env.get('DB_DATABASE', 'adonis')
      },
      debug: Env.get('DB_DEBUG', false)
    },
    ...knexSnakeCaseMappers()
  })
```

That's all, now you can use `.where('createdAt', ...)` instead of `.where('created_at', ...)` and `SomeModel.createdAt` instead of `SomeModel.created_at`. This conversion also works for `SomeModel.toJSON()`

**Comment by ngloom** [comment]
Thanks @xxxwww , great solution ~

**Comment by skrenek** [comment]
I was originally using this @xxxwww's solution, but found it causes Lucid's child population to fail silently.  I haven't delved into it, but my guess is it is not assigning the ids correctly due to the property name mismatch to do the load.

`let user = await User.query().where('email', email).with('role').fetch()`
and

    let user = await User.find(1)
    user.load('role')
both fail silently, leaving `role` null.  I've had to revert back to a custom serializer.

**Comment by xxxwww** [comment]
@skrenek looks like the conversion works for the foreign key in relationships too. Therefore, you need to explicitly specify the key if it is stored in a database in a format other than camelCase

**Comment by skrenek** [comment]
Can you elaborate on what you mean by specifying the key?  I thought the point of the workaround was to allow db columns to be specified in snake case and properties in code in camel case.

**Comment by prakashbharti786** [comment]
Any update on this guys? Since my whole table's name are in camelCase.
Please help with answer how can i change the default behavior of table.timestamps() which create table name in snack_case. I want it to be in camelCase.

**Comment by Secular12** [comment]
@xxxwww per @skrenek could you elaborate on what you meant by specifying the key?

**Comment by pirey** [comment]
there is a library for knex.js that does exactly this conversion of snake_case to camelCase.
https://github.com/Kequc/knex-stringcase

is there a way in adonis to use setup knex connection?

**Comment by henrikgundersen** [comment]
@xxxwww's fix works lika a charm except when you return a newly created record. Adonis saves a DB query by just appending `created_at` and `updated_at` in snake_case to the record when created which means it will not go through the `knexSnakeCaseMapper`.

This will then give you this when returning a created record:
```js
// Creating record and returning
const user = new User()
user.firstName = 'Foo'
await user.save()

return response.json({ user })
```
```js
// Returned response
{
  "id": 1,
  "firstName": "Foo",
  "created_at": "<timestamp>", // <-- snake_case
  "updated_at": "<timestamp>", // <-- snake_case
}
```
and this when retrieving existing record:
```js
// Finding existing record and returning
const user = await User.find(1)
return response.json({ user })
```

```js
// Returned response
{
  "id": 1,
  "firstName": "Foo",
  "createdAt": "<timestamp>", // <-- camelCase
  "updatedAt": "<timestamp>", // <-- camelCase
}
```

**Comment by e200** [comment]
> ```js
> knexSnakeCaseMappers
> ```

This solution makes Adonis unable to load relations.

**Comment by johnmcguin** [comment]
@e200 I am going to have to look into that. I have been unable to load relations (probably since adding this) and couldn't figure out why for the life of me. Also, I have been looking for a solution to accomplish this outside of models / serializers. Even with `knexSnakeCaseMappers`, it doesn't seem to convert snake_case to camelCase in the instance of running raw sql statements via Database.raw(). Is there any way to intercept responses in AdonisJS and run that logic there?

**Comment by johnmcguin** [comment]
@e200 have you figured a workaround for this? I am having a hard time finding a cleaner solution than knexSnakeCaseMappers, but it's a bummer that the Lucid relations don't work with it.

**Comment by amakarenko-sumy** [comment]
@xxxwww I have a problem with knexSnakCaseMappers and relations in adonis.

**Comment by amakarenko-sumy** [comment]
@xxxwww I have a problem with knexSnakCaseMappers with ralations in adonis.

**Comment by amakarenko-sumy** [comment]
@xxxwww I have a problem with **knexSnakCaseMappers** with ralations in adonis.
For exaple:
We have 3 models: users, roles and user_role;
in **user** model we have method:
```
 roles(){
    return this.belongsToMany(
      'App/Models/Role',
      'userId',
      'roleId',
    ).pivotTable('user_role');
}
```

Two way to get data:
1) Works
```
const user = await User.find(1)
user.load('roles')
```
2) Not works. Resuls is empty array of roles
`conts user = await User.query().with('roles').fetch()
`

**Comment by johnmcguin** [comment]
@amakarenko-sumy I am not positive, but try to camelCase your pivotTable 'userRole' instead of 'user_role'
