### ISSUE TITLE
Adonis 4.0.27: Factories with custom data like Laravel

### ISSUE THREAD

**Issue by pixelpeter** [adonisjs/adonis-framework#702]
In Laravel I can overwrite the default values of a factory simple by specifying an array of new values on runtime.

Related to the documentation at http://adonisjs.com/docs/4.0/seeds-and-factories#_custom_data I need to specify the factory in a specific way to enable this functionality. But then I will loose the default values.

That's why my current solution uses lodash as a workaround to have both functionalities:

```
const _       = require('lodash');
const Factory = use('Factory');

Factory.blueprint('App/Models/MyModel', (faker, i, data) => {
    return {
        user_id       : _.defaultTo(data.user_id, faker.pickone([123456, 456789, 123789, 987654, 654321, 111111, 222222, 333333])),
        group_id      : _.defaultTo(data.id_notation, 11111),
    };
});
```
Now I can use this factory in two ways.
With default values
```
    await Factory
        .model('App/Models/MySql/Usecase')
        .create();
```

With new/overwritten values
```
    await Factory
        .model('App/Models/MySql/Usecase')
        .create({ user_id: 98765 });
```

Is the current functionality the wanted/final behavior or do you plan to add a functionality to directly overwrite the default values in the future?

**Comment by RomainLanz** [comment]
This is already implemented.

Please see https://github.com/adonisjs/adonis-blog-demo/blob/master/database/factory.js#L23
