### ISSUE TITLE
Cannot find module 'Factory'

### ISSUE THREAD

**Issue by oliveiradouglas** [adonisjs/adonis-framework#703]
I am getting the following error on controller.

```Cannot find module 'Factory'```

![image](https://user-images.githubusercontent.com/11797503/32622697-dc68e93a-c56a-11e7-8d78-dcfe0dcc226b.png)

Someone know why?

**Comment by RomainLanz** [comment]
Hey @oliveiradouglas! 👋 

Which blueprint have you used?
Also, what are you trying to achieve? You shouldn't have tests on your controller.

**Comment by oliveiradouglas** [comment]
Hello @RomainLanz, I was testing the user registry this was a temporary method, I have already solved my question. Thank you.
