### ISSUE TITLE
return this missed in Route.Group.middleware

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-framework#706]
https://github.com/adonisjs/adonis-framework/blob/94b46b216b0f309dce9ee274679ef4e5f2f889df/src/Route/Group.js#L58

 **return this** missed in Route.Group.middleware
It has to be
```
  middleware (...middleware) {
    this._routes.forEach((route) => route.prependMiddleware(...middleware))
    return this
  }

```

**Comment by RomainLanz** [comment]
Hey @yariksav! 👋🏻

May you create a PR to fix this?

**Comment by yariksav** [comment]
done
