### ISSUE TITLE
Adonis make command file indentation

### ISSUE THREAD

**Issue by oscarmorrison** [adonisjs/adonis-framework#708]
## Choose the correct repo
Not sure if its in this repo or the `cli` or the `ace` one. (Sorry in advance)

# Issue

I have set up editorconfig
```
# editorconfig.org

[*]
indent_size = 4
```

However whenever I use any of the `make:migration` `make:controller` etc. etc. commands, the file generated, does not respect the indentation_size (defaults to 2)

**Comment by RomainLanz** [comment]
Hey @oscarmorrison!

`editorconfig` is an editor's plugin that set your **editor configuration** to respect what you set up.
It has nothing to do with Adonis and will not change how the generator generates our file

**Comment by thetutlage** [comment]
Yes as @RomainLanz said it’s a plugin to instruct the editor. But lemme see if we can do anything about it or not

**Comment by thetutlage** [comment]
I am closing this, since there is no simple way for AdonisJs to read the `.editorconfig` even before the project doesn't exists.
