### ISSUE TITLE
Question: init provider async and then start app

### ISSUE THREAD

**Issue by protzi** [adonisjs/adonis-framework#709]
I try to implement basic Service Provider for rabbitMQ, and can't figure out, how to lunch app after rabbit connected, callback in hooks isn't async, so what is proper way to do this and where the best place to subscribe handlers ?

![selection_001](https://user-images.githubusercontent.com/17887536/32697420-a5f11cd0-c798-11e7-89ca-248866f84596.png)

_**providers/Rabbit/Provider.js**_
```
const { ServiceProvider } = require('@adonisjs/fold')

class RabbitProvider extends ServiceProvider {
  register () {
    this.app.singleton('@/Rabbit', () => {
      const Config = this.app.use('Adonis/Src/Config')
      return new (require('.'))(Config.get('rabbit'))
    })
  }
}

module.exports = RabbitProvider

```

_**providers/Rabbit/index.js**_
```
const rabbit = require('rabbot')

class Rabbit {
  constructor(config) {
    this._config = config
  }

  configure(callback) {
    rabbit.configure(this._config)
      .done(callback.bind(this))
  }

  get() {
    return rabbit;
  }

  init() {
    // register handlers ...
  }
}

module.exports = Rabbit
```

_**app/hooks.js**_
```
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
  console.log('providers booted')
  
  const Config = use('Adonis/Src/Config')
  const Rabbit = use('@/Rabbit')

  Rabbit.configure(() => {
    console.log('Rabbit connected')
  })
})

hooks.before.httpServer(() => {
  console.log('before server started')
})

hooks.after.httpServer(() => {
  console.log('server started')
})
```

![selection_002](https://user-images.githubusercontent.com/17887536/32697607-efb007b0-c79c-11e7-98af-c1fe639cf7fc.png)

**Comment by thetutlage** [comment]
Do it inside the `boot` of the provider. That is `async`

**Comment by protzi** [comment]
@thetutlage same result

**Comment by thetutlage** [comment]
Can u share the actual code

1. How you registered the provider
2. What's the code inside the `boot` method

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
