### ISSUE TITLE
DB Transactions Support

### ISSUE THREAD

**Issue by oliveiradouglas** [adonisjs/adonis-framework#711]
Hello, Lucid Models has transactions support? I not found in docs.

**Comment by RomainLanz** [comment]
Hey @oliveiradouglas! 👋 

Please, ask those kinds of questions in the forum instead of creating an issue.
Here's the doc for it http://adonisjs.com/docs/4.0/query-builder#_database_transactions.

**Comment by oliveiradouglas** [comment]
Hello @RomainLanz, thanks for repply i will go for the forum.
