### ISSUE TITLE
Testing API returns error about "done()" function

### ISSUE THREAD

**Issue by pawel-miczka** [adonisjs/adonis-framework#712]
Hi,

Today I decided to make some simple REST API and make functional test with Adonis. 
My test looks like this:

```js
'use strict'

const { test, trait } = use('Test/Suite')('Template')
const Template = use('App/Models/Template')

trait('Test/ApiClient')

test('get list of templates', async ({ client, done }) => {
  const response = await client
    .get('/template')
    .end()

  response.assertStatus(200)
})
```

but after **adonis test** i get error:

```
  1. get list of templates
  Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at Test._parseError (G:\Projekty\Akcelerator\adonis\szablony_dokumentow\node_modules\japa\src\Test.js:109:16)
    at Callable.args.run.then.then.catch (G:\Projekty\Akcelerator\adonis\szablony_dokumentow\node_modules\japa\src\Test.js:195:21)
```

Can anyone explain what I'm doing wrong?

**Comment by watzon** [comment]
Basically what it says, you're supposed to call done when the function completes and you're not calling it.

```js
test('get list of templates', async ({ client, done }) => {
  const response = await client
    .get('/template')
    .end()

  response.assertStatus(200)
  return done()
})
```

**Comment by thetutlage** [comment]
Basically what is says is something else

```
Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

The test has been timed-out, which means you need to increase the test time. The safest way is to set it to `0`, which means disable timeouts.

```js
test('get list of templates', async ({ client, done }) => {
  const response = await client
    .get('/template')
    .end()

  response.assertStatus(200)
}).timeout(0)
```

The default timeout is `2000ms`.

**Comment by watzon** [comment]
@thetutlage that's a confusing error then. Shouldn't `done()` get called?

**Comment by pawel-miczka** [comment]
return done() doesn't work.

.timeout(0) works fine.

You should update docs then. Your example api test doesn't say anything about .timeout(0) (or im blind): http://adonisjs.com/docs/4.0/api-tests.

**Comment by RomainLanz** [comment]
Hey @pawel-miczka! 👋 

May you sent a PR to https://github.com/adonisjs/docs/ to improve the documentation about testing? 😄

**Comment by pawel-miczka** [comment]
Sure, no problem ;)
