### ISSUE TITLE
Edge route global doesn't work for named routes in a group

### ISSUE THREAD

**Issue by watzon** [adonisjs/adonis-framework#713]
With the following code in my routes file

```js
Route.group(() => {
  Route.get('/', async ({ view }) => {
    return view.render('blog.coming-soon')
  }).as('blog.index')
}).domain('blog.localhost.com')
```

the `route` global method should create a link to `blog.localhost.com` even when the link is being displayed on another domain (like `localhost.com`). What is happening instead is that I just get a link to the site's index page.

The link is being displayed like this `<li><a href="{{ route('blog.index') }}">Blog</a></li>`

**Comment by thetutlage** [comment]
Sorry for getting late on it, but one thing that struck my mind, how to know the `protocol`?

**Comment by watzon** [comment]
@thetutlage hmm I didn't think about that one. It could default to http unless a tls or protocol option is specified?

**Comment by thetutlage** [comment]
Yeah but where that option will be specified?

**Comment by watzon** [comment]
It could either go in the route definition or the `route` global. Or possibly both?
