### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Labelsuisse** [adonisjs/adonis-framework#714]
With adonisjs 4, 

what is the difference between 
> adonis serve --dev and adonis serve?

here is what is displayed:
┌──────────────────────┐
│                      │
│    Started server    │
│    Watcher: On       │
│    Debugger: Off     │
│                      │
└──────────────────────┘

The files Watcher is enabled, but it does not work.

thanks

**Comment by thetutlage** [comment]
How you found that file watcher is not working? Which files did u edited?

**Comment by Labelsuisse** [comment]
I create HomeController with cmd "adonis make:controller Home" and i edit this file.
After modifie, never modifications change appears in my browser (i refresh browser before)

**Comment by RomainLanz** [comment]
Hey @Labelsuisse! 👋 

What was the output of the CLI when you changed the file?

**Comment by Labelsuisse** [comment]
Hi @RomainLanz ,

i run server with adonis serve --dev and show display CLI :
┌──────────────────────┐
│                      │
│    Started server    │
│    Watcher: On       │
│    Debugger: Off     │
│                      │
└──────────────────────┘
2017-11-15T10:31:30.009Z - info: serving app on http://127.0.0.1:3333

never output of CLI when changed the file!

**Comment by thetutlage** [comment]
Are u running it inside Docker or some virtual machine and also which Operating system

**Comment by Labelsuisse** [comment]
No, i working on Mac OS Sierra.
nodejs version: v8.4.0
npm version: 5.4.2
adonis-cli version: 4.0.0

**Comment by thetutlage** [comment]
Wow I am on Mac OS Sierra too and it works fine

----

![ezgif-3-b33bd89bc6](https://user-images.githubusercontent.com/1706381/32832319-164cd0ca-ca21-11e7-9de9-f2ff1082a72f.gif)

**Comment by Labelsuisse** [comment]
I am sincerely sorry, nothing happens to me!

**Comment by thetutlage** [comment]
Can u please a share GIF on how you doing it?

**Comment by Labelsuisse** [comment]
Yes, I will send you a GIF as soon as possible. 
Thank you for your support

**Comment by Labelsuisse** [comment]
@thetutlage here is:
![adonis](https://user-images.githubusercontent.com/3238600/32844220-1e7764da-ca22-11e7-8737-faaae1cc6dcc.gif)

**Comment by 18601673727** [comment]
Very interesting conversation 😆

**Comment by thetutlage** [comment]
This is amazing, I have never seen this happening. Lemme go through the chokidar ( internal tool Adonis uses for watching file ) issues and see what I find

**Comment by Labelsuisse** [comment]
I solved my problem.
If my application is in a tmp or public directory, nodemon ignore all file changes.

expl:
~/tmp
    |__ adonis-blog

OR
~/public
    |__ adonis-blog

I create a pull request.

**Comment by RomainLanz** [comment]
Closing since the PR has been merged 😄
