### ISSUE TITLE
Develop under Docker environment, how to live reload deamon?

### ISSUE THREAD

**Issue by 18601673727** [adonisjs/adonis-framework#715]
Currently my command to start container is
```
npm start
```
if I go with
```
adonis serve --dev
```
this error comes out:
```
Cannot start service node: oci runtime error: container_linux.go:265: starting container process caused "exec: \"adonis\": executable file not found in $PATH"
```
Now I have to manually restart whole docker stack for each modifications. 😞

**Comment by RomainLanz** [comment]
Hey @18601673727! 👋 

You need to install the Adonis CLI into your docker container, since `adonis serve` came from it.

```
npm i -g @adonisjs/cli
```

**Comment by 18601673727** [comment]
Hi @RomainLanz!

I've tried this way, but it will cause permission issues due to using `-g`, so I've tried bootstrapping stack with command `npm i @adonisjs/cli` then log into that container do things like this:
```
docker exec -it xxx /bin/bash
node ./node_modules/@adonisjs/cli/bin/index.js server --dev
```
then nothing happened, tried changed code and save, server not reloading.

**Comment by RomainLanz** [comment]
It seems to be an issue with `npm` itself.
May you try this https://github.com/npm/npm/issues/17851#issuecomment-343666114

**Comment by 18601673727** [comment]
Sure, maybe later I'm OK with manually restart for now.

**Comment by RomainLanz** [comment]
Also the other way would be to install locally the CLI and run it via `npx`.

**Comment by radmen** [comment]
@18601673727 you're using docker native, or docker machine? On docker machine, it's possible that file watchers will not react to file changes. This problem is related to FS drivers of a virtual machine.

**Comment by 18601673727** [comment]
This issue also influence commands like: `adonis migration:run`, I have to change `.env` for using the external DB host to satisfy it, then change back to let the app connect to DB internally.

**Comment by 18601673727** [comment]
@radmen, Docker Machine on a Mac.

**Comment by radmen** [comment]
> Docker Machine on a Mac.

If possible switch to Docker Native. OSX file drivers for Virtualbox are incomplete - they can't sync file events so file watchers are unable to restart Adonis. On Docker Native it works without any problems.

> This issue also influence commands like: adonis migration:run, I have to change .env for using the external DB host to satisfy it, then change back to let the app connect to DB internally.

I assume that you run Adonis locally and run migrations through Docker? Well that's what happens when you're using inconsistent env :)
If you have to stick to Docker Machine you can try to add host aliases for the services and Docker Machine hosts and adjust configuration to match those hosts.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by 18601673727** [comment]
Hi @radmen, Sorry for the long time delay, but I've just installed VMware Fusion(10.1.1 7520154) and running docker native on a ubuntu vm inside, then I've made some changes of the code on OSX, ended up the results are exactly same, so I suggest maybe implementing something like 
```
npm start --dev
``` 
to giving the people like me who can't use `adonis serve --dev` as an alternative?
