### ISSUE TITLE
Allow the edge route global to work with url query params

### ISSUE THREAD

**Issue by watzon** [adonisjs/adonis-framework#716]
### Brief Description

The `route` global for edge is very handy, but currently the second parameter, where you pass in parameters that get added on to the route, only work if the parameters have been defined on the route. I propose that we modify this behaviour so that the route get's checked first, and if no matches are found for the parameter it get's turned into a query string and appended to the URL.

### Sample Code

```blade
<!-- view.edge -->
<a href="{{ route('AuthController.login', { ref: 'footer' }) }}">Login</a>
```

```js
// routes.js

Route.get('/auth/log-in', 'AuthController.login')
```

The url should end up as `http://mysite.com/auth/log-in?ref=footer

**Comment by thetutlage** [comment]
That's too much magic, for query string you can simply pass `qs` key and an object next to it.

```js
route('AuthController.login', { qs: { ref: 'footer'  } })
```

**Comment by watzon** [comment]
@thetutlage that needs to be documented then. I couldn't figure it out for the life of me.

**Comment by thetutlage** [comment]
Nope, I didn't said that it's implemented, I said the implementation should follow the given pattern

**Comment by watzon** [comment]
Ahhh ok. Well I can update the PR to reflect that then.

**Comment by RomainLanz** [comment]
Closing since a PR is open.
