### ISSUE TITLE
Suggestion: Name of session flash view helper old is confusing

### ISSUE THREAD

**Issue by ellogwen** [adonisjs/adonis-framework#719]
I was reading a tutorial from someone that used this line of template code in his example
```
@if(old('notification'))
    <div class="notification is-success">
        {{ old('notification') }}
    </div>
@endif
```

I was curious what the old function does because he did not explain it and the name is not intentionally obvious (at least for me). But googling for **adonis and old** or **edge and old** was harder than it should be. I found it eventually in the documentation as a sub section of sessions -> flash messages -> view helpers and learned that this functions returns the value of flash message variable or a default value like so
`
<input type="text" name="username" value="{{ old('username', '') }}" />
`
Now the functionally is clear to me (the tutorial writer omitted the last parameter tho) but after that it is still not clear to me why this function is called `old`. Is it a shortcut? Did this name come from a Laravel/Other Framework background? Or does the name `old` in this context mean something different that I as a non-native-english speaker does not get?

As a suggestion there could be an alias name for this function?

Sorry for this first world problem ticket :)

**Comment by RomainLanz** [comment]
Hey @ellogwen! 👋 

Actually, there's already an alias called `flashMessage`.
http://adonisjs.com/docs/4.0/sessions#_flashmessage_key_defaultvalue

**Comment by ellogwen** [comment]
Oh, you are right. Didn't know that this is the alias. But

> Returns the value for a given key from the flash store.

and

> Returns the flash message for a given key 

is basically the same. My bad -_-
