### ISSUE TITLE
How  to turn off the details for 404, 401, 403, ... errors?

### ISSUE THREAD

**Issue by mrtranquanghieu** [adonisjs/adonis-framework#720]
I want to turn off the details for 404, 401, 403, ... errors. 
For example: [http://adonisjs.com/404](url)

**Comment by RomainLanz** [comment]
Hey @mrtranquanghieu!

Please, check http://adonisjs.com/docs/4.0/exceptions

**Comment by mrtranquanghieu** [comment]
Thanks. I have resolved this problem!
