### ISSUE TITLE
Mysql / Migration

### ISSUE THREAD

**Issue by kamalkech** [adonisjs/adonis-framework#725]
node --version    = v8.9.1
npm --version     = 5.5.1
adonis --version = 4.0.0

i run this command : adonis migration:run

i get this error : 
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true

**Comment by thetutlage** [comment]
MySQL server is not running

**Comment by radmen** [comment]
..or you're providing incorrect DB creds.

**Comment by kamalkech** [comment]
I fin a solution, must to enable / allow network access to mysql.
