### ISSUE TITLE
cygwin git not work probably. It cannot clone repo

### ISSUE THREAD

**Issue by adrianmak** [adonisjs/adonis-framework#726]
adnois new blog

D:\adonis-tutorial>adonis new blog
    _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

√ Your current Node.js & npm version match the AdonisJs requirements!
× Unable to clone repo

=============================================
Installation failed due to following error
=============================================
Command failed: git clone --depth=1 https://github.com/adonisjs/adonis-fullstack-app.git "D:\adonis-tutorial\blog"
Cloning into 'D:\adonis-tutorial\blog'...
fatal: Invalid path '/d/adonis-tutorial/D:\adonis-tutorial\blog': No such file or directory

**Comment by RomainLanz** [comment]
Seems similar of https://github.com/adonisjs/adonis-cli/issues/72

**Comment by RomainLanz** [comment]
Closing in favor of the other issue.
