### ISSUE TITLE
Inject parameters

### ISSUE THREAD

**Issue by Theremsoe** [adonisjs/adonis-framework#727]
Hi guys, congratulations for this job. 

My question is: how can i do for inject/add aditional parameters in controller methods?

For example: 

```javascript
async single ({ request, response, myCustomParameter }) {}
```
or
```javascript
async single ({ request, response }, myCustomParameter) {}
```

Can i do it in a middleware?

Thanks

**Comment by thetutlage** [comment]
Yes create a middleware and add values to the context

```js
class FooMiddleware {
  handle (ctx, next) {
      ctx.myCustomParameter = 'foo'
      await next()
   }
}
```
