### ISSUE TITLE
New features in adonis js.

### ISSUE THREAD

**Issue by hkmsadek** [adonisjs/adonis-framework#729]
This is not a bug report. Can we expect the bellow features in version 4 when it's officially released or may be they are already added I am not sure but would like to see them for sure :)

1. Most popular framework like koa has upgraded to HTTP/2, is adonis js 4 uses it or it will he added in future ?

2. Like to see Vue js configured just like laravel.

3. Laravel recently added react js too so do you plan anything like that ? It would be really awesome lol.

4. Seems socket implementation still in work. Can we expect an abstract layer in socket like how sails do such a nice way? Or adonis has already better that this? Like to see socket implementation much easier because many php developers migrating to nodes mostly because of real time app. 

Thank you and keep the good work :)
God bless you :)

**Comment by G3z** [comment]
1. 4.0 is released https://adonisjs.svbtle.com/here-you-go-adonis-4-0

2. (&3) I believe it's stated in the docs that no frontend framework is provided nor any will be (you can add laravel-mix pretty easily)

4. Websockets are still WIP for adonis 4.x

**Comment by hkmsadek** [comment]
Thank you. So you are not sure of HTTP/2 ?

**Comment by thetutlage** [comment]
@hkmsadek Http2 is still experimental in Nodejs and also it’s not as simple as changing the switch, the entire way of writing the apps will change

Also why u think HTT

**Comment by hkmsadek** [comment]
Thanks, I read a details post about HTTP/2 it is has few disadvantage too so it's not something supper needed yet. 

Thanks again and hope to see a nice easy integration of socket in adonis 4.

**Comment by thetutlage** [comment]
👍

**Comment by julianobailao** [comment]
Have a documentation about socket controller?
