### ISSUE TITLE
Router feature question

### ISSUE THREAD

**Issue by phucblog** [adonisjs/adonis-framework#732]
Hi, guys.
Not a bug, i would ask some info.
Example i want to log a Route status after response like this:

`GET /api/pages status:200 500.000 ms`

by using middleware, it run before the controller, and need something like `after:route` to log it to console.
With expressjs, it's simple to do it with expressjs/morgan, but i dont know how to integrate in    AdonisJS.

Thank.

**Comment by twilroad** [comment]
using hooks.

**Comment by thetutlage** [comment]
You can create a middleware for that too and simply use `finish` event. Simple example

```js
class LogMiddleware {
  async handle ({ request, response }, next) {
    const requestStart = process.hrtime()
    response.response.on('finish', () => {
      const [sec, nanosec] = process.hrtime(requestStart)
      const responseTime = (sec * 1e9 + nanosec) / 1000000

      Logger.info('%s(%s) request on %s url -> %s',
        request.method(),
        response.response.statusCode,
        request.url(),
        `${responseTime} ms`
      )
    })
    await next()
  }
}

module.exports = LogMiddleware
```

**Comment by phucblog** [comment]
oh, many thank guys, i did it.
