### ISSUE TITLE
Switch locale doesn't work

### ISSUE THREAD

**Issue by danilopolani** [adonisjs/adonis-framework#733]
### Brief Description
Using the query parameters `?lang=` doesn't work if the current locale of the user is in the "available language". If I have "Accept-Language" set to "IT" and I navigate a page with `?lang=en`, the language is still "it".

The problem I guess is on line 20 of [Antl/ContextBidings](https://github.com/adonisjs/adonis-antl/blob/develop/src/ContextBindings/index.js#L20):

`const language = this.request.language(availableLocales) || this.request.input('lang')`

It should be the inverse, giving priority to the input (note: I didn't tested it):

`const language = this.request.input('lang') || this.request.language(availableLocales)`

And, by the way, there's no way to change the locale from a middleware. I tried both these but they don't work, the locale is still "it" in my controllers.

```
'use strict'

const Antl = use('Antl')

class Language {
  async handle ({ request, response, locale, params, session }, next) {
    // Otherwise, set current locale
    Antl.switchLocale('en')

    // Call next to advance the request
    await next()
  }
}

module.exports = Language
```

---

```
'use strict'

const Antl = use('Antl')

class Language {
  async handle ({ request, response, locale, params, session }, next) {

    // asynchronous
    await Antl.bootLoader()

    // Otherwise, set current locale
    Antl.switchLocale('en')

    // Call next to advance the request
    await next()
  }
}

module.exports = Language
```

The ways to achieve this are:

1. To change the "Accept-Language" header from the web browser, but it's an awful solution
2. Retrieve the lang parameter in a Controller (to extend), check if the language is in the available ones, if not set the fallback and then call Antl.switchLocale.

While finding a way to retrieve the current locale in my views (I figured out only `antl._locale`), because of this the found locale is wrong (taken from headers) and from `View.extend` we can't use variable such as `request` or `params` to replicate the code to find the correct locale.

**Comment by danilopolani** [comment]
PS: Middlewares don't work when a page is not found

**Comment by thetutlage** [comment]
Okay, so there are couple of things here.

1. When using `Antl.switchLocale('en')`  you are simply changing the locale of a global instance, which is not passed to your controllers or routes.
2. Yes the preference is given to the header over query string, which can be changed, but I am not sure what everyone would need in this case.

Now regarding your middleware, this is what you can do to manually override it.

```js
class Language {
  async handle ({ request, response, locale, params, session, antl }, next) {
    antl.switchLocale('en')
    await next()
  }
}

module.exports = Language
```

**Note**: Each request can have a different language, so you should never `switchLocale` on a global instance and instead set it for `antl` passed as the request context.

**Comment by danilopolani** [comment]
Also if I use `antl.switchLocale('en')` in the middleware, when I retrieve the locale from destructured object, it is the Header-given one. Anyway I found a (dirty) solution and I'm good with it. About the middleware not working on 404s have you got any idea?

**Comment by thetutlage** [comment]
That is by design. There are 3 layers of middleware

1. Server
2. Global
3. Named

The `Global` and `Named` only works when there is a registered route and `Server` one works everytime.

The example of Server middleware are `Static` and `Cors`.

**Comment by danilopolani** [comment]
Understood, thank you!
