### ISSUE TITLE
>npm i -g @adonisjs/cli          error      看不懂哪里错了

### ISSUE THREAD

**Issue by DazhuangChen** [adonisjs/adonis-framework#734]
npm WARN gentlyRm not removing C:\Users\Administrator\AppData\Roaming\npm\adonis.cmd as it wasn't installed by C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli
npm WARN gentlyRm not removing C:\Users\Administrator\AppData\Roaming\npm\adonis as it wasn't installed by C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli
C:\Users\Administrator\AppData\Roaming\npm\adonis -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli\index.js
npm ERR! path C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@adonisjs\cli\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@adonisjs\\cli\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@adonisjs\\cli\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-26T12_00_31_780Z-debug.log

**Comment by DazhuangChen** [comment]
怎么那么多错误

**Comment by twilroad** [comment]
operation not permitted，没有用管理员是身份运行这个命令吧

**Comment by RomainLanz** [comment]
Hey @DazhuangChen! 👋 

You seem to have a permission issue on your system.
Which version of `npm` are you using?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by DazhuangChen** [comment]
Thank you. After asking others, it is found that the framework needs to be configured and can not be used directly.
Now this problem has been solved.
