### ISSUE TITLE
adonis new yardstick           Unable to clone repo       

### ISSUE THREAD

**Issue by DazhuangChen** [adonisjs/adonis-framework#735]
_       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

√ Your current Node.js & npm version match the AdonisJs requirements!
× Unable to clone repo

=============================================
Installation failed due to following error
=============================================
Command failed: git clone --depth=1 https://github.com/adonisjs/adonis-fullstack-app.git "C:\Users\Administrator\yardstick"
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by jrishabh55** [comment]
Hi, 
are you sure git is installed on your system, Please check by running the following command,

`git --version`
It should give you an output like this. 
`git version 2.15.0.windows.1`

If it is not installed you might need to do it first.

**Comment by twilroad** [comment]
maybe network error, can not access to github.com

**Comment by thetutlage** [comment]
You have posted the same issue for multiple times, closing this one in favor of https://github.com/adonisjs/adonis-framework/issues/734

**Comment by DazhuangChen** [comment]
I just started to contact this thing. I don't know that you need to install GIT. Thank you.

**Comment by RomainLanz** [comment]
Maybe we should check that GIT is installed within the CLI? @thetutlage

**Comment by thetutlage** [comment]
Yeah we can do that, happy to accept the PR
