### ISSUE TITLE
redis pub/sub

### ISSUE THREAD

**Issue by colynb** [adonisjs/adonis-framework#739]
I noticed that in the documentation you provided for doing pub/sub with redis, you provide the following example:

```
Redis.publish('music', {
  id: 1,
  title: 'Love me like you do',
  artist: 'Ellie goulding'
})
```

I couldn't get this to work as expected in my subscribe function, trying to just console.log the payload. It was just returning `[object Object]`. Digging into your code, you don't have any such method called `publish` so I went looking for it int the `ioredis` library instead. I noticed that they too do not have that method, which brings me to the native redis command bindings, publish being one of them. It only takes a string as the payload. So, I think your documentation needs to be updated to show that the object needs to be stringified first.

**Comment by thetutlage** [comment]
Closing as merged https://github.com/adonisjs/docs/pull/218
