### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by tinkone** [adonisjs/adonis-framework#74]
Is there a way to reload the application changes without restart via `npm start` ?

**Comment by thetutlage** [comment]
Yes, install nodemon

```
nodemon --watch app --harmony_proxies server.js
```

**Comment by azulkipli** [comment]
I use this sample app https://github.com/adonisjs/adonis-blog-demo
then try 
```
nodemon --watch app --harmony_proxies server.js
```
it seem not work
