### ISSUE TITLE
How to add global Customs Headers?

### ISSUE THREAD

**Issue by blacktrue** [adonisjs/adonis-framework#741]
Hi, i need add global custom headers, in specific: 'Strict-Transport-Security'.

My API AdonisJS is upload with pm2

**Comment by webdevian** [comment]
Best to do this in your server software (nginx, apache) IMO

**Comment by blacktrue** [comment]
Thanks, How do you receive the response from the controller to add the header from the middleware?

**Comment by webdevian** [comment]
@blacktrue Middleware is hit before the controller, it receives a request and a response object which then get passed onto the next middleware, then eventually the controller

**Comment by blacktrue** [comment]
Thanks, I understood if I add a header in the middleware it remains globally. Now it works
