### ISSUE TITLE
Overwrites previous Route in group() method

### ISSUE THREAD

**Issue by brendaniel** [adonisjs/adonis-framework#742]
## Structuring The Issue
The order of routes does not work in the `Route.group()` method.

### Sample Code
_ProductController.js_
``` js ProductController
async category({ response }) {
  console.log('category');
}

async show({ response }) {
  console.log('show');
}
```
**case 1**
_routes.js_
``` js routes.js
Route.group(() => {
  Route.get('/product/category', 'ProductController.category');
  Route.get('/product/:id', 'ProductController.show');
})
.prefix('api');
```
You can see 'show' in console.

**case 2**
_routes.js_
``` js routes.js
Route.get('/product/category', 'ProductController.category');

Route.group(() => {
  Route.get('/product/:id', 'ProductController.show');
})
.prefix('api');
```
Now 'category', 'show' in console.

### Error Stack (if any)
I wonder if the order in  `Route.group()` method is irrelevant to the route, or is it a bug?

**Comment by thetutlage** [comment]
Can you share the URL you hit from the browser?

**Comment by thetutlage** [comment]
![screen shot 2017-12-11 at 11 10 38 am](https://user-images.githubusercontent.com/1706381/33817149-f05fc8e8-de63-11e7-9cd2-bed1b86aeb7b.png)

Using your routes, this is output I get, which is the same order as routes get matched, which seems fine to me

**Comment by brendaniel** [comment]
## sample code
``` js
// ProductController.js
async categories() {
  console.log('categories')
}

async detail() {
  console.log('show')
}
```
**case 1**
``` js
// routes.js
Route.group(() => {
  Route.get('/product/category/:id?', 'ProductController.categories');
  Route.get('/product/:id', 'ProductController.detail');
})
.prefix('api/v1')
.formats(['json']);
```

**case 2**
``` js
// routes.js
Route.get('/api/v1/product/category/:id?', 'ProductController.categories');
Route.group(() => {
  Route.get('/product/:id', 'ProductController.detail');
})
.prefix('api/v1')
.formats(['json']);
```

## screenshots
![image](https://user-images.githubusercontent.com/11773683/33817741-7086e7de-de84-11e7-8326-86de90c4482b.png)

API calls in postman
**case 1** 
> GET /api/v1/product/category
![image](https://user-images.githubusercontent.com/11773683/33817819-e26efaa8-de84-11e7-891a-8ed850cdfae9.png)

**case 2**
> GET /api/v1/product/category
![image](https://user-images.githubusercontent.com/11773683/33817835-051b8d32-de85-11e7-8cac-e6732a7b042c.png)

**Comment by thetutlage** [comment]
As per your routes definition in `case1` you have registered 2 routes, but screenshot of `case1` shows 3 on the terminal.

Can u create a sample app which reproduces the issue

**Comment by brendaniel** [comment]
sample app

**case 1**
![image](https://user-images.githubusercontent.com/11773683/33820942-39d33920-de95-11e7-87f5-1bcdcc7e285f.png)

**case 2**
![image](https://user-images.githubusercontent.com/11773683/33820925-1d3bf0ea-de95-11e7-8449-b6489fa6b21b.png)

**Comment by thetutlage** [comment]
I mean share the repo of this app, screenshots are not something I can use to debug

**Comment by brendaniel** [comment]
@thetutlage 
👍 
https://github.com/brendaniel/adonis-route-test/

**Comment by tlgreg** [comment]
Looks to me the root of the issue is actually `.formats()` and the normally optional trailing slash.
If you request `/api/product/category/` or `/api/product/category/.json` it does resolve `categories` while without the slash it resolves `show`. Same thing with *case2* if you add `.formats(['json'])` to the outside route it will behave the same.

**Comment by thetutlage** [comment]
Going to look into it in a while

**Comment by thetutlage** [comment]
Created an issue on the internal library Adonis uses, let's see what best can be done here https://github.com/pillarjs/path-to-regexp/issues/131

**Comment by thetutlage** [comment]
I am afraid, I don't think I can fix it anyway unless the internal library `path-to-regexp` fixes it. The only option is to re-write the functionality of `path-to-regexp`, which I have no plans to do it right now.

**Comment by brendaniel** [comment]
@thetutlage appreciate your time
