### ISSUE TITLE
Adonis api mail  not working  (adonis install @adonisjs/mail)

### ISSUE THREAD

**Issue by Jayaramvenkatanarayanan** [adonisjs/adonis-framework#745]
## Problem 
Hi all, I am developing Adonis restful API services  ( version 4.0). I am using adonis mail in my code. I have followed doc but I got an error like  this  :   Cannot find module 'Adonis/Src/View'

## Tools 
Webstorm & insomina ( rest client ) 

## My folder structure 
![structure](https://user-images.githubusercontent.com/14818202/34012111-84b67b82-e138-11e7-9e5d-a2c4a5b1ac71.png)

### Sample Code

     config/Mail.js  - I am using mailtrap

     'use strict'

     const Env = use('Env')

     module.exports = {
  
     connection: Env.get('MAIL_CONNECTION', 'smtp'),
     smtp: {
     driver: 'smtp',
     pool: true,
     port: 2525,
     host: 'smtp.mailtrap.io',
     secure: false,
     auth: {
      user: "########",
      pass: "########"
    },
    maxConnections: 5,
    maxMessages: 100,
    rateLimit: 10
      },

 
    sparkpost: {
      driver: 'sparkpost',
       apiKey: Env.get('SPARKPOST_API_KEY'),
       extras: {}
      }
       }

----------------------------

    my Code : in user controller
     // Store the information

    async store({request, response}) {

    let validation = await  validate(request.all(), rules)
    if (validation.fails()) {
      return response.status(400).json({data: 'error', message: validation._errorMessages[0].message, status: false})
    }
    const userInfo = request.all();
    const users = new User();
    users.username = userInfo.username;
    users.email = userInfo.email;
    users.password = userInfo.password;
    let checkUser = await dataBase.table('users').where('email', '=', users.email)
    if (checkUser.length > 0) {
      return response.status(400).json({data: 'insert fail', message: 'email already register', status: false})
    }
    await users.save();
    // sending mail after registration
    const data =request.only(['username','email', 'password']);
    await Mail.send('emails.welcome', {}, (message) => {
      message.from('#####.com')
      message.to('####.com')
    })
    return response.status(201).json({message: 'user created successfull', status: true});
  }
### Screenshots - Rest client 
![error](https://user-images.githubusercontent.com/14818202/34012301-4356934c-e139-11e7-9665-7f5643fe28a5.png)

**Comment by thetutlage** [comment]
Yes emails are stored in view templates, so you need to register the view provider inside the providers array

```
 '@adonisjs/framework/providers/ViewProvider'
```

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks thetutlage Its working fine.

**Comment by outluch** [comment]
Should be added to docs, imo. Mail requires ViewProvider added or smth. (in mail section)

**Comment by RomainLanz** [comment]
@outluch PRs are welcomed 🤗
