### ISSUE TITLE
 JWT - token middelware Routes not working In Adonis API 

### ISSUE THREAD

**Issue by Jayaramvenkatanarayanan** [adonisjs/adonis-framework#746]
I am using JWT token based auth in Adonis API. Login API working fine. I cant use the jwt auth check for other routes.
for example, Admin login success full, but that same admin auth check not working other activities. 

       My Routes:
       
       Route.group(() => {
       Route.get('user', 'UserController.index');
       Route.post('addUser', 'UserController.store');
       Route.get('getUser/:id', 'UserController.showId').middleware(['auth:jwt']);
       Route.put('updateUser/:id', 'UserController.userUpdate');
       Route.delete('deleteUser/:id', 'UserController.remove');
       Route.post('login', 'UserController.login');
       Route.get('check', 'UserController.check').middleware(['auth:jwt']);
       }).prefix('api/v2');

      My auth.js
         jwt: {
                serializer: 'lucid',
                model: 'App/Models/User',
                scheme: 'jwt',
                uid: 'email',
                password: 'password',
                options: {
                 secret: 'self::app.appKey'
                 }
                 }
             }

 User controller:

       async login({request, auth, response}) {
              const {email, password} = request.all();
              let token = await auth.attempt(email, password);
               return response.status(200).json({data: token, message: 'Login successfull', status: true});
              }
 Its working fine.

But i want to check get users from DB using id passing in url with auth check it's not working.

          //get by id

            async showId({params, response, auth}) {
             try {
               let play = await auth.generate(user);
                console.log(play);
               let userInfo = await User.find(params.id)
                 if (userInfo != null) {
                 return response.json({data: userInfo, auth: auth, message: 'get the record', status: true})
               }
                return response.status(404).json(notFound)
              } catch (error) {
                       response.send('Missing or invalid jwt token')
                 }

                }
       URL : oute.get('getUser/:id', 'UserController.showId').middleware(['auth:jwt']);

Response 
![jwt](https://user-images.githubusercontent.com/14818202/34077745-491d35e8-e331-11e7-8126-77a64aa227e4.png)

I passed header also.give me the solution.

**Comment by thetutlage** [comment]
The token passed in the `Authorization` header must start with `Bearer` keyword. http://adonisjs.com/docs/4.0/authentication#_jwt

```js
Authorization = Bearer <token>
```

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks now it's resolved, but I can't  revoke my jwt token check my code below and suggest me 

Logout code:

         const user = await auth.getUser()  -- (in example use current.user but its not working for me ) 
         console.log(user);
         const token = auth.getAuthHeader()
         await user
                  .tokens()
                  .where('type', 'api_token')
                   .where('is_revoked', false)
                   .where('token', Encryption.decrypt(token))
                   .update({ is_revoked: true })
          return response.send({ message: 'Logout successfully' })

if i use const user = await auth.current.user i got the error below 

![jwt](https://user-images.githubusercontent.com/14818202/34097741-1df0a420-e400-11e7-9490-3092e19b25cd.png)

**Comment by thetutlage** [comment]
Is the route to revoke the token using the `auth` middleware?

**Comment by Jayaramvenkatanarayanan** [comment]
yes

**Comment by thetutlage** [comment]
Can u share the route definition for `logout`

**Comment by Jayaramvenkatanarayanan** [comment]
ya sure

     Route.group(() => {
      Route.post('login', 'UserController.login')  ;
     Route.get('user', 'UserController.index').middleware('auth');
      Route.get('logout', 'UserController.logout')
    }).prefix('api/v2');

**Comment by thetutlage** [comment]
As per the routes file you shared, the logout is not using the auth middleware

**Comment by Jayaramvenkatanarayanan** [comment]
Yes bro  i cant get the current user while i use this code 

   const user =  await auth.current.user 

if i use this 

      const user =  await auth.getUser()

revoke jwt successful but still i can use that.

**Comment by thetutlage** [comment]
Do u even understand what I am saying.

When a request reaches the `logout` route, how does Adonis knows which user token should be returned?

**Comment by Jayaramvenkatanarayanan** [comment]
Ok, I will give the particular token and revoke that. may I correct?  pl give the sample how to do it

**Comment by thetutlage** [comment]
Can u please change your route to use the `auth` middleware?

```js
Route.get('logout', 'UserController.logout').middleware('auth')
```

**Comment by Jayaramvenkatanarayanan** [comment]
ok i will check it and update you

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks bro

**Comment by ireolaniyan** [comment]
> The token passed in the `Authorization` header must start with `Bearer` keyword. http://adonisjs.com/docs/4.0/authentication#_jwt
> 
> ```js
> Authorization = Bearer <token>
> ```

Where should this be set?

**Comment by RomainLanz** [comment]
It should be set by your frontend @ireolaniyan

**Comment by ireolaniyan** [comment]
Yes. I found out how to set it in Postman. Thanks @RomainLanz
