### ISSUE TITLE
CORS problem ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH

### ISSUE THREAD

**Issue by JeremyGreaux** [adonisjs/adonis-framework#747]
Hi, 
I use graphql-apolo-adonis extension to create my own graphQL api.
Query request works fine, but when I use Mutation query, I have got this request error: 

`
POST http://localhost:3333/graphql net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH
ApolloError.js:34 Uncaught (in promise) Error: Network error: Failed to fetch
    at new ApolloError (ApolloError.js:34)
    at Object.error (QueryManager.js:122)
    at SubscriptionObserver.error (zen-observable.js:174)
    at httpLink.js:147
    at <anonymous>
`  

I tryed to change cors configs, but no changes.
With another graphQL API (express), I have not this error.

Thx for helping

**Comment by RomainLanz** [comment]
Hey @JeremyGreaux! 👋 

This is an issue directly with the package.
Please, create an issue there https://github.com/ammezie/adonis-apollo-server,

Thanks
