### ISSUE TITLE
AdonisJS migration Error on PostgreSQL : withSchema is not a function

### ISSUE THREAD

**Issue by bendo01** [adonisjs/adonis-framework#749]
I want to create a DB under non-public Schema in PostgreSQL. In knexjs document :
```
knex.schema.withSchema('public').createTable('users', function (table){
  table.increments();
})
```
My migration code is:
```
this.withSchema('myschema').create('users', table => {
  table.increments()
})
```
But migration:run returns this error:
```
TypeError: this.withSchema is not a function
```
How can I create DB under custom schema?
[same question is asking here](https://stackoverflow.com/questions/47862332/adonisjs-migration-error-on-postgresql-withschema-is-not-a-function)

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-lucid#269
