### ISSUE TITLE
Preprocessor support

### ISSUE THREAD

**Issue by tinkone** [adonisjs/adonis-framework#75]
Hypothetically speaking, where would one add in preprocessor support in the application? Having gotten the UI/UX team invested in `sass`, it's going to be one hell of a struggle to rip it away from them. In previous applications, we used `gulp` to run tasks which produces artifacts in the static route, not sure how to go about in adonis.

**Comment by thetutlage** [comment]
how a backend framework can decide what do to with sass.
1. install gulp as you usually do.
2. Create a gulpfile.
3. Keep sass under resources/sass and compile css to public directory

**Comment by tinkone** [comment]
Thanks now that you put in steps, it seems intuitively obvious.
