### ISSUE TITLE
Default Exception message change ( jwt ) adonis 4.0

### ISSUE THREAD

**Issue by Jayaramvenkatanarayanan** [adonisjs/adonis-framework#750]
I want to change the default exception message in my project, I am using JWT auth with default middleware functionality.
 my auth middleware working fine but I need to change the default message I tried custom exception handler but it's not working.

My custom exception code:

                class TokenException extends LogicalException {
                /**
                 * Handle this exception by itself
                 */
                 handle (error, { response }) {
                 if (error.name === 'InvalidJwtToken') {
                   response.status(500).send('Some message')
                  }
                }

In user controller : 

         const tokenMessage = use('App/Exceptions/TokenException');

          async Showall({auth,response}) {
           try {
              await auth.check();
             } catch (e) {
            return await tokenMessage.handel();
            }
             }

Route 

         Route.get('findall', 'UserController.Showall').middlerware('auth');

 Default error message:

       
![jwt](https://user-images.githubusercontent.com/14818202/34295909-d8ce9f4e-e735-11e7-85ab-ce696d08a889.png)

Default error message change to like below in JSON format

       {
       "message":"InvalidJwtToken",
       "status" :false
       }

**Comment by thetutlage** [comment]
Are you sure the code inside controller is being called?

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks, 
In My route, i use again auth check middleware. that's only its send default message.
