### ISSUE TITLE
Question: How to use Adonis Packages inside Vue Files?

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [adonisjs/adonis-framework#752]
Hello,
im using [AdoNuxt ](https://github.com/nuxt-community/adonuxt-template)= [AdonisJs](https://adonisjs.com) + [NuxtJs](https://nuxtjs.org):
so i want to use Adonis Packages such as: `session` or `Antl`,... inside `vue` files?

like: this 
`<span>{{ Antl.formatMessage('footer.greeting') }}</span>`

it shows error:
`Cannot read property 'formatMessage' of undefined`

and the session like this inside `vuex store file index.js`:
```
     async increment ({ commit }, { session }, payload) {
        try {
          session.put('counter', payload)
        } catch (e) {
          console.log(e)
        }
      }
```
but this also won't work, (im now using axios to interact)!
is there anyone have tried to use this combination?

**Comment by thetutlage** [comment]
Vuejs is used on frontend and AdonisJs is a backend framework. The question is similar to, `How would I use Php in vuejs`

**Comment by NadhirBoukhenifra** [comment]
@thetutlage yes, i know that (frontend: VueJs) and (Backend: AdonisJs),
but they are in same language? (JS), is there any way to connect them (without `axios`), or using another plugin?
and thank you,

**Comment by thetutlage** [comment]
Axios makes Http request using Ajax, I don't get the question how backend code can be integrated within frontend.

The backend code runs before the response is sent to the browser and frontend runs after the browser renders the response. The philosophy of joining them is flawed in itself.
