### ISSUE TITLE
Adonis js hasone relationship not working 

### ISSUE THREAD

**Issue by Jayaramvenkatanarayanan** [adonisjs/adonis-framework#753]
I am trying has one relationship: One-to-one relationship between employees and salaries. 
one employee has one relationship with salaries.

My Database :

employee
   
      class EmpSchema extends Schema {
        up () {
          this.create('employees', table => {
          table.integer('emp_no').primary().notNullable().unique();
          table.string('firstname', 20).notNullable();
          table.string('lastname', 20);
          table.enu ('gender', ['m','f']).notNullable();
          table.date('hiredate').notNullable();
          table.timestamps();
         })
       }

      down () {
        this.drop('employees')
      }
       }

Salaries

             class SalariesSchema extends Schema {
           up () {
               this.create('salaries', (table) => {
                table.integer('emp_no').index().references('emp_no').inTable('employees').onDelete('CASCADE');
                table.integer('salary').notNullable();
                table.date('from_date').notNullable();
                table.date('to_date').notNullable();
                table.primary(['from_date']);
             })
              }

             down () {
               this.drop('salaries')
           }
           }

Models

 salaries

        salaries(){
         return this.hasOne('App/Models/Salaries','emp_no','emp_no');
         }

route

        Route.get('find', 'EmpsalaryController.Showid');

Showid

       var getUser = await Employee.query().where('emp_no', '=', emp_no);
             console.log(getUser);
          var empSalary = await getUser.salaries().fetch();
          return response.status(200).json({
            data: empSalary,
            message: 'get the record',
            status: true
          });

              i got this error: getUser.salaries is not a function

**Comment by hoangmy92** [comment]
Without [fetch()](http://adonisjs.com/docs/4.0/lucid#_query_builder), your result is just an object, instead of *Employee instance*. So you can't execute *salaries* :)

**Comment by Jayaramvenkatanarayanan** [comment]
So how I get this record

**Comment by Jayaramvenkatanarayanan** [comment]
I have tried but i got the same error, check the doc relationship its showing that only

**Comment by Jayaramvenkatanarayanan** [comment]
In debug mode, I got this error   

   { method: 'select',
        options: {},
          timeout: false,
           cancelOnTimeout: false,
          bindings: [ 1 ],
         __knexQueryUid: 'e2ff40e4-7b75-4d34-b82f-2473a5c21fd0',
              toNative: [Function: toNative],
            sql: 'select * from `employees` where `emp_no` = ?' }
       getUser.salaries is not a function

**Comment by thetutlage** [comment]
@Jayaramvenkatanarayanan I do recommend you to debug your code when in doubt.

As per your code, if I log `getUser`, it is an array of rows, so for sure it cannot have `salaries` method on it.

```js
var getUser = await Employee.query().where('emp_no', '=', emp_no)
```

What you need is the instance of the model 

```js
var user = await Employee.query().where('emp_no', '=', emp_no).first()
await user.salaries().fetch()
```

The short form of above can be

```js
var user = await Employee.findBy('emp_no', emp_no)
await user.salaries().fetch()
```

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks, @thetutlage, it's working fine.
