### ISSUE TITLE
Resourceful controller routing

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-framework#76]
After creating a resourceful controller, it seems that the routing is not setup correctly.
When I hit `resource/create` it seems that it is not automatically finding the view in `resources/views/users/create.html`. It is instead hitting the `show` method in the controller.

For example, add this to your resourceful controller and then hit `<resource>/create`. You'll see it return `show method`.

```
    * show (request, response) {
      response.send('Show method')
    }
```

**Comment by RomainLanz** [comment]
The latest release of `adonis-framework` (2.0.7) doesn't create a `create` route.

You should use the dev release to have a correct `Route.resource()` function.

Update your `package.json` file to replace `^2.0.0` to `adonisjs/adonis-framework#develop`.

**Comment by niallobrien** [comment]
Thanks @RomainLanz
