### ISSUE TITLE
Setting Logger.level at runtime doesn't work

### ISSUE THREAD

**Issue by CherryDT** [adonisjs/adonis-framework#760]
When I set `Logger.level`, it appears to have no effect.

Further looking into the issue and stepping into a broken `Logger.debug` call (after setting `Logger.level = 'debug'`) shows the following:

* `use('Logger').level` (which belongs to the facade, I believe...?) **does** reflect the new level. (See **(1)**)
* The `Logger` (`@adonisjs/framework/src/Logger/index.js`) class instance's `level` **does NOT** reflect the new level. (See **(2)**)
* The `Logger` (`@adonisjs/framework/src/Logger/index.js`) class instance's `driver.level` **does NOT** reflect the new level. (See **(3)**)
* A breakpoint on the `Logger` (`@adonisjs/framework/src/Logger/index.js`) class's `set level` setter is **NOT** hit when the new level is set.

![image](https://user-images.githubusercontent.com/6010463/34943729-28c95046-f9fd-11e7-9af5-2e729d71218d.png)

I'm using `@adonisjs/framework@4.0.30`.

**Comment by thetutlage** [comment]
Seems like an issue at first glance, lemme look into it

**Comment by thetutlage** [comment]
Release as 4.0.31
