### ISSUE TITLE
Unable to stream public image via response.download() or response.attachment()

### ISSUE THREAD

**Issue by sliktrik** [adonisjs/adonis-framework#763]
Using adonis 4.0 I'm trying to load an image from a remote url and return an image as a response

```
const Http = use('request')

class FileController {

    async image({request, params, response}){

        const url = 'https://news.nationalgeographic.com/content/dam/news/photos/000/755/75552.ngsversion.1422285553360.adapt.1900.1.jpg'

        Http
            .get(url)
            .pipe(response.response) //<- does not work as per 3.0

    }

}
```
also using `response.download(url)` and `response.attachment(url,'cat.jpg')` return a 404 error

**Comment by thetutlage** [comment]
You have turn of the `implicitEnd` mode on response.

```js
response.implicitEnd = false
Http.get(url).pipe(response.response)
```
More on same here http://adonisjs.com/docs/4.0/response

**Comment by sliktrik** [comment]
Thank you!

**Comment by ghosh** [comment]
I know this is closed, but using `implicitEnd` with `response.download` still does not work.

```
response.implicitEnd = false
response.download(url)
```

Is the only option here using an external `Http` package?
