### ISSUE TITLE
Response is empty

### ISSUE THREAD

**Issue by LeMalandrin** [adonisjs/adonis-framework#764]
Hi,
I just installed my adonis project (version 4.0.0). I have NodeJS (version 8.9.4)  installed on a mint linux distrib. I can run the server, but when I'm calling a simple method in routes.js which is : 

```js
Route.get('users/:id', function * (request, response) {
    const id = request.param('id')
    response.send('Profile for user with id ${id}')
  })
```

I just get this for response in my browser : -->  {}

I tried to implement my code in a controller's method, but this is the same. I tried to send a json response to try, but I get the same response. 

Maybe I made a mistake somewhere ?

Thanks

**Comment by thetutlage** [comment]
Route handlers are not `generator method (*)`, it has to be following

```js
Route.get('users/:id', async function (request, response) {
    const id = request.param('id')
    response.send('Profile for user with id ${id}')
})
```

**Comment by LeMalandrin** [comment]
I just your code, and I get : 

> request.param is not a function

So I try to do : 

`Route.get('users/:id', async function (request, response) {
    response.send('Profile for user')
})`

I get : 

> response is undefined (and I can get an undefined when I console.log(response) )

Sorry...maybe I miss something...
I took the first code I posted from the documentation

Very thank you for the very fast answer ^^

**Comment by LeMalandrin** [comment]
Okay I got it, I wasn't on the right documentation --" what a noob
Thank you thetutlage and really sorry
