### ISSUE TITLE
Adonisjs can t save value of user id in new table

### ISSUE THREAD

**Issue by NikolaBarisic** [adonisjs/adonis-framework#765]
I can't enrol value of user.id in table cards. 

my user model:
'use strict'

const Model = use('Model')
class User extends Model {
  static boot () {
    super.boot()

    /**
     * A hook to bash the user password before saving
     * it to the database.
     *
     * Look at `app/Models/Hooks/User.js` file to
     * check the hashPassword method
     */
    this.addHook('beforeCreate', 'User.hashPassword')
  }
  card () {
   return this.hasMany('App/Models/Card', 'id', 'user_id')
 }
 static get table () {
    return 'users'
  }
  static get primaryKey () {
    return 'id'
  }
  static get hidden () {
   return ['password']
 }
}
module.exports = User

my card model 

'use strict'

const Model = use('Model')

class Card extends Model {
  static get table() {
    return 'cards'
  }
  static get primaryKey () {
    return 'id'
  }

  user(){
    return this.belongsTo('App/Models/User')
  }
}

module.exports = Card

my user database/migrations

'use strict'

const Schema = use('Schema')

class UserSchema extends Schema {
    up () {
        this.create('users', table => {
            table.increments('id')
            table.string('firstname', 16).nullable()
            table.string('lastname', 16).nullable()
            table.string('username', 80).nullable()
            table.string('email', 255).nullable()
            table.string('password', 60).nullable()
            table.timestamps()
        })
    }

    down () {
        this.drop('users')
    }
}

module.exports = UserSchema

my cards database/migration 

'use strict'

const Schema = use('Schema')

class CardSchema extends Schema {
  up () {
    this.create('cards', table => {
      table.increments()
      table.integer('user_id').unsigned()
      table.string('namecard').nullable()
      table.string('barcod').nullable()
      table.string('idcard').nullable()
      table.timestamps()
      table.foreign('user_id').references('users.id')
    })
  }

  down () {
    this.drop('cards')
  }
}

module.exports = CardSchema

When I make new card in card table I get user_id value of NULL 

And my card controller

  async postCard({response, request, session,params,auth}){

      const value = {
         namecard: 'required|min:3|max:20',

       }
    const validation = await validateAll(request.all(), value)

    if (validation.fails()) {
      session.withErrors(validation.messages())
              .flashAll()

      return response.redirect('card')
    }

    const card = new Card()
    const user = await auth.getUser()

    card.namecard = request.input('namecard')
    card.barcod = request.input('barcod')
    card.idcard = request.input('idcard')

    await Database.table('cards').insert({
      user_id: user.id,
    })

**Comment by thetutlage** [comment]
Can you please spend 5mins to format the code properly? I cannot understand a line and it is hard to give you the right answer.

Here are the github docs on markdown https://guides.github.com/features/mastering-markdown/

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
