### ISSUE TITLE
Can I run a sql script using the database module or something similar?

### ISSUE THREAD

**Issue by moar55** [adonisjs/adonis-framework#766]

**Comment by thetutlage** [comment]
Need code samples on what exactly you want

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by moar55** [comment]
I am sorry for late reply. I just wanted to be able to run a .sql script using an ace command, I am not sure how to do that.

**Comment by thetutlage** [comment]
I believe you can read the `.sql` file manually and make use of the `raw` method to execute commands.

Example code for an ace command

```js
const Database = use('Database')

const sqlCommand = await this.readFile('<file-path>')
await Database.raw(sqlCommand)
```

Now if you have multiple commands in a single file, then you need to identify on how to split them. May be with a new line or whatever is appropriate in your case

**Comment by moar55** [comment]
That's exactly what I need.
Thanks!
