### ISSUE TITLE
Anonymous function in template

### ISSUE THREAD

**Issue by touskar** [adonisjs/adonis-framework#770]
I used the filter function on an object collection, but when I pass it an anonymous function in parameter I get an error during the rendering process of the page.
`{{ items.filter((item) => return item.value > 5) }}`
 I am obliged to declare the anonymous function in the controller, then  pass it in the parameters of the view.

```
async ({view}) => {
  return view.render('template', {
    filterFn: (item) => {
      return item.lengh > 0
    }
  })
}
```

And then : 
`{{ items.filter(filterFn) }}`

**Comment by thetutlage** [comment]
Ues templates are not Javascript files, and hence an anonymous function is not allowed.

**Comment by touskar** [comment]
Okey so I can't pass general javascript expression to edge template. Thanks

**Comment by RomainLanz** [comment]
You can always use view presenters to achieve this kind of thing.

**Comment by touskar** [comment]
Okey. Thanks
