### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY

### ISSUE THREAD

**Issue by jitendraF5buddy** [adonisjs/adonis-framework#772]
## Brief

npm install forever -g i am run this command

**getting this error** : 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/fo                                            rever/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                            1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                            )
npm ERR! Linux 3.10.0-693.5.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "forever" "-g"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! path /home/mysitename/.npm/_locks/staging-a072192f34a17023.lock
npm ERR! code Unknown system error -122
npm ERR! errno -122
npm ERR! syscall open

npm ERR! Unknown system error -122: Unknown system error -122, open '/home/mysitename/.npm/_locks/staging-a072192f34a17023.lock'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.10.0-693.5.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "forever" "-g"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.609541676
npm ERR! code Unknown system error -122
npm ERR! errno -122
npm ERR! syscall open

npm ERR! Unknown system error -122: Unknown system error -122, open 'npm-debug.l                                            og.609541676'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mysitename/npm-debug.log

**Comment by RomainLanz** [comment]
Hey @jitendraF5buddy ! 👋 

Have you updated and installed the new CLI as requested?

**Comment by jitendraF5buddy** [comment]
Yes but getting error

**Comment by RomainLanz** [comment]
Wait.

The command you are running is `npm install forever -g`?

**Comment by jitendraF5buddy** [comment]
Yes i l ready installed npm and node js

**Comment by jitendraF5buddy** [comment]
then i am installing npm install forever -g

**Comment by RomainLanz** [comment]
Please, fill an issue on `forever` repository https://github.com/foreverjs/forever.

I don't know why you are opening an issue on adonis-framework since it's not related.

**Comment by jitendraF5buddy** [comment]
Sorry for that

**Comment by RomainLanz** [comment]
No worries 😄
