### ISSUE TITLE
Invalid CSRF token using Axios

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [adonisjs/adonis-framework#776]
### Brief Description
Hello,
i have this sample `API`
```
Route.group(() => {
  Route.get('/hello', () => ({
    greeting: 'This is the real hello world '
  }))
  Route.post('/hello', async ({request}) => {
    console.log(request)
    return { greeting: 'Hello from POST!!' }
  })
}).prefix('test');
```
and when i call it from `Axios` or `Postman` 
the `GET` works fine.
the `POST` show:
```
HttpException
EBADCSRFTOKEN: Invalid CSRF token
```
![01](https://user-images.githubusercontent.com/13006236/35474082-6fbd6c22-0389-11e8-901f-4af2822b0705.PNG)

its the same problem when using `axios` from another `frontend` `app`.
its about CSRF token !!  how can i handle this?
thank you.

**Comment by RomainLanz** [comment]
Hey @NadhirBoukhenifra! 👋 

It seems that you are building an API Only backend. I recommend you to disable the CSRF protection if it's the case.

You can do that by changing the value in the `config/shield.js` file.
https://github.com/adonisjs/adonis-shield/blob/develop/example/config.js#L135

**Comment by RomainLanz** [comment]
Closing since talk about that in Gitter and resolved.

**Comment by lucasctd** [comment]
For those with the same problem you can get the value of the csrfField and set in your request header like below:

`xhr.setRequestHeader('x-csrf-token', document.querySelector('[name="_csrf"]').value);`

If you use the Key X-XSRF-TOKEN to set the cookie value of XSRF-TOKEN it will not work, even though it's in the [docs](https://adonisjs.com/docs/4.1/csrf#_how_it_works)...

**Comment by s-appdeveloper** [comment]
Yeah, it doesn't work. Seems like the XSRF-TOKEN cookie token is much longer than the value from '{{ csrfToken }}'. 
I would really like this to work as documented, since the frontend could be hosted separately.

**Comment by belal-mazlom** [comment]
You could add API routes to filtered urls, like this.

in `config/shield.js`

Modify: 
```javascript
csrf: {
    cookieOptions: {
      httpOnly: false,
      maxAge: 7200,
      path: '/',
      sameSite: true,
    },
    enable: true,
    filterUris: ['/api/(.*)'],
    methods: ['POST', 'PUT', 'DELETE'],
  }
```

**Comment by YvesBoah** [comment]
> Hey @NadhirBoukhenifra! 👋
> 
> It seems that you are building an API Only backend. I recommend you to disable the CSRF protection if it's the case.
> 
> You can do that by changing the value in the [`config/shield.js` file](https://github.com/adonisjs/adonis-shield/blob/develop/example/config.js#L135).
> 
> [More information](https://security.stackexchange.com/questions/166724/should-i-use-csrf-protection-on-rest-api-endpoints) about disabling CSRF protection on a REST API.

Thank you
