### ISSUE TITLE
access a relationship

### ISSUE THREAD

**Issue by pdipasqua** [adonisjs/adonis-framework#777]
Hi guys,
I have two model: User and Tenant

In User I define this relation with Tenant:

```
  tenants () {
    return this.belongsToMany('App/Models/Tenant')
    .pivotTable('tenant_users')
    .withPivot(['roles','users','office_id'])
  } 

```
Now, in punch in function 

```
	async punchIn ({request, auth }) {
		const user = await auth.getUser()   
		const actual_tenant = await user
			.tenants()
			.wherePivot('tenant_id', user.last_tenant_id)
			.fetch()
	        return actual_tenant
```

Ok, result 200 with this response 

`[{"id":1,"name":"Test Tenant","employees":10,"pivot":{"tenant_id":1,"user_id":2,"roles":[1,2,3],"users":[2],"office_id":1}}]`

but if I access to actual_tenant[0] I receive nothing into repsonse
and if i try to accesso to actual_tenant[0].pivot I got an error because actual_tenant[0] is undefined

So, what am I doing wrong?

Regards, Paolo

**Comment by pdipasqua** [comment]
Hi guys,
I have two model: User and Tenant

In User I define this relation with Tenant:

```
  tenants () {
    return this.belongsToMany('App/Models/Tenant')
    .pivotTable('tenant_users')
    .withPivot(['roles','users','office_id'])
  } 

```
Now, in punch in function 

```
	async punchIn ({request, auth }) {
		const user = await auth.getUser()   
		const actual_tenant = await user
			.tenants()
			.wherePivot('tenant_id', user.last_tenant_id)
			.fetch()
	        return actual_tenant
```

Ok, result 200 with this response 

`[{"id":1,"name":"Test Tenant","employees":10,"pivot":{"tenant_id":1,"user_id":2,"roles":[1,2,3],"users":[2],"office_id":1}}]`

but if I access to actual_tenant[0] I receive nothing into repsonse
and if i try to accesso to actual_tenant[0].pivot I got an error because actual_tenant[0] is undefined

So, what am I doing wrong?

Regards, Paolo

**Comment by thetutlage** [comment]
The output of the `fetch` method is not a plain array, instead it is an instance of a [serializer](http://adonisjs.com/docs/4.0/serializers).

If you want an array of model instances you can access them as `actual_tenant.rows`.

The JSON representation array is access by calling `toJSON` method. `actual_tenant.toJSON()`

**Comment by pdipasqua** [comment]
Ok, I understand. Thanks.
