### ISSUE TITLE
API Resources

### ISSUE THREAD

**Issue by douglaszaltron** [adonisjs/adonis-framework#778]
When building an API, you may need a transformation layer that sits between your models and the json responses that are actually returned to your application's users.  Has any feature known in adonisjs that can easily work with this method? [One sample here](https://murze.be/a-fractal-service-provider-for-laravel) or [in laravel5.5](https://laravel.com/docs/5.5/eloquent-resources)

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
