### ISSUE TITLE
session.flash

### ISSUE THREAD

**Issue by obeza** [adonisjs/adonis-framework#780]
Hello.

I just trying to use : session.flash
In my controller :

```js
class InvitationController {
  async index({ view, session }) {
     
    let invitations = await Invitation.all()

    return view.render('pages.backoffice.invitation.index', {
      invitations : invitations.toJSON()
    })
  }

  async store({ request, session, response }) {
    ...
     session.flash({ notification: 'You have been redirected back' })
     // redirect to InvitationController.index
     response.redirect('/backoffice/invitation') 
  }
}
```

In my view : 'pages.backoffice.invitation.index'
```
@if(flashMessage('notification'))
  <span> {{ flashMessage('notification') }} </span>
@endif
```

Nothing happened

**Comment by thetutlage** [comment]
Can u please format the code properly, it's hard to read it

**Comment by thetutlage** [comment]
Just tried it with a sample project and all seems to be working fine.

Can u share a repo with the minimum code to reproduce the issue?

**Comment by obeza** [comment]
Hello @thetutlage my repo :
https://github.com/obeza/adonis-blog

I create a component with flashMessage ( in the folder views/components/flashMessage ). I call this inside my "layouts/back.edge"

**Comment by thetutlage** [comment]
So that’s the missing piece from your first comment. 

Components have isolated state, means they don’t share the state of the parent template and hence you need to pass it the values manually 

```
@component(‘name’, flashMessages = flashMessages)
```

**Comment by obeza** [comment]
Perfect.
It's working.
Thank you @thetutlage
