### ISSUE TITLE
allow factories to use methods defined in traits

### ISSUE THREAD

**Issue by alidcastano** [adonisjs/adonis-framework#782]
I like to create a factory method for each model so that it's easy to create it with all its data and associations.

```
class Post extends Model {
   static async init ({ title, user }) {
      cost post = new Post()
       post.fill({ title })
       await post.owner().associate(user)
       await post.save()
   }
   ....
}
```

However, it is not possible to then call: `Factory.model('App/Models/Post').init({ user })` since factories do not seem to expose the model's methods.

Would this be possible? Thanks.

**Comment by thetutlage** [comment]
Why would you use a factory in this case? Simply use the model and call the method.

```
use('App/Models/Post').init({ user })
```

**Comment by alidcastano** [comment]
I figured that that way I could make uses of the faker object, but I can also import that chancejs library myself otherwise

**Comment by thetutlage** [comment]
Okay, so what you want is a model instance pre-filled with faker data.

Then you should use `.make` method.

```
const postInstance = Factory.model('App/Models/Post').make()
postInstance.init({ user })
```

**Comment by alidcastano** [comment]
Ah, that makes sense. Thanks!
