### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by bryannbarbosa** [adonisjs/adonis-framework#783]
I need to upload an image through a request, but when I upload, I find the following message:

**'request entity too large'**

Although I have configured the file size that will be received, what can I do to solve the problem?

**Comment by thetutlage** [comment]
Can u share the settings that you have changed and what's the file size?

**Comment by bryannbarbosa** [comment]
First of all, thank you.

This is the function I'm using:
```
async store({request, response}) {
  const profilePic = request.file('profile_pic', {
    types: ['images'],
    size: '60mb'
  })

  await profilePic.move(Helpers.tmpPath('uploads'), {
    name: `${new Date().getTime()}.${file.subtype}`
  })

  if(!profilePic.moved()) {
    return profilePic.error()
  }
  return 'File moved'
}
```

The size of image is 62,9 KB

**Comment by bryannbarbosa** [comment]
@thetutlage I need to develop an important project using AdonisJS and I have a deadline, if you can help me in the shortest possible time, I would be immensely grateful

**Comment by thetutlage** [comment]
I tried your code and everything worked fine. Also the `60mb` you have set is the current file max size. However you need to set the max payload size of request inside `config/bodyParser.js` file.

https://github.com/adonisjs/adonis-fullstack-app/blob/develop/config/bodyParser.js#L110

Also there was a typo that `file.subtype` has to be `profilePic.subtype`

**Comment by bryannbarbosa** [comment]
The real problem is that the content-type defined in the request was like **"application / x-www-form-urlencoded"**, by **disabling this in Postman**, it ran perfectly, thanks!

**Comment by thetutlage** [comment]
Ohhh yeah, it has to be `multipart/form-data`

**Comment by emjea** [comment]
hi, i have issue like this.
i tried upload pdf file (size 1-2Mb). the response always entity too large.
what can I do to solve the problem?

this is my code
  const profilePic = request.file("profPic", {
        types: ["image", "pdf"],
        size: "5mb"
      });

**Comment by RomainLanz** [comment]
Hey @emjea! 👋 

You need to increase the size limit in `config/bodyParser.js`.
Also, make sure that your proxy configuration let you upload a big file.

**Comment by emjea** [comment]
Hi @RomainLanz !

it's worked now.
Thanks so much :)

**Comment by jbrhinalyn** [comment]
I have an issue but this time its from canvass dataURL. I already increase the limit to 100MB the error still display. I check the image size and its around 9KB only. Im using AJAX POST in submitting the data.
