### ISSUE TITLE
Default Exception Handler not found in 5.0.2

### ISSUE THREAD

**Issue by webdevian** [adonisjs/adonis-framework#784]
My handler in app/Exceptions/Handler.js is not being picked up by adonis server and ignitor since upgrading today

**Comment by webdevian** [comment]
@thetutlage  It looks like this is fixed in 5.0.3?

**Comment by thetutlage** [comment]
Yes, I was preparing for 4.1 release of the framework, which had some intermediate bugs. So it should be good now.
