### ISSUE TITLE
Is it possible to change the view engine?

### ISSUE THREAD

**Issue by dan-gamble** [adonisjs/adonis-framework#786]
I personally come from a Django background so personally prefer template syntax like Jinja2 / Nunjucks as opposed to blade / edge.

Is there any way to do this at the moment or any plans to add it in the future?

**Comment by webdevian** [comment]
It won't ever be added into adonis-framework but you could have a go at making your own. I have made a Pug templating provider, that mirrors the api of the build in edge engine and it wasn't too difficult - https://github.com/webdevian/adonis-pug

**Comment by dan-gamble** [comment]
Awesome, thanks @webdevian

**Comment by thetutlage** [comment]
Closing since not actionable
