### ISSUE TITLE
Is it possible using function selectRaw in Adonis?

### ISSUE THREAD

**Issue by umaams** [adonisjs/adonis-framework#788]
I have query:
`select user_id, sum(total) as total from transaction group by user_id`
Currently, in adonis i will write code like this
`await Database.raw('select user_id, sum(total) as total from transaction group by user_id')`

Hopefully next time you can add function selectRaw, so my code will be simpler like this:
`await Database.table('transaction').selectRaw('user_id, sum(total) as total').groupBy('user_id')`

**Comment by thetutlage** [comment]
How about 

```js
Database.table('transaction').select('user_id').sum('total as total').groupBy('user_id')
```

**Comment by umaams** [comment]
Thanks @thetutlage.
