### ISSUE TITLE
For loop in edge tamplate

### ISSUE THREAD

**Issue by shpontex** [adonisjs/adonis-framework#789]
##
Can someone tell me how to do a for loop in edge, i couldn't find anything in the documentation

thank you

**Comment by thetutlage** [comment]
http://edge.adonisjs.com/docs/iteration

**Comment by shpontex** [comment]
thank you but i already checked, 
im looking to do something like for(i=0;i<6;i++) , to do pagination

**Comment by thetutlage** [comment]
You can do something like this

```
@each(number in range(totalNumberOfPages))
  {{ number }}
@endeach
```

And `range` is a global function given by Edge itself http://edge.adonisjs.com/docs/globals#_range_start_0_end

**Comment by shpontex** [comment]
ok that's what i was looking for 
thank you for your fast reply

**Comment by thetutlage** [comment]
👍 . Closing the issue
