### ISSUE TITLE
adonis --help gives error after fresh npm installation

### ISSUE THREAD

**Issue by laravellously** [adonisjs/adonis-framework#790]
![capture](https://user-images.githubusercontent.com/13837652/36206097-fac51b52-1145-11e8-9174-9530bd3ce4e4.PNG)
Hi,

I am new to AdonisJs, though I have a solid Laravel background, and I think I'm gonna love this framework too. I just did a fresh install, according to the [Docs](http://adonisjs.com/docs/4.1/installation). Above is the error that I am getting.

I am using Node 9.4.0, Win 10, so please, what is the issue?

**Comment by thetutlage** [comment]
Yeah this is weird. Cannot replicate on my machine either. Lemme try it on a windows machine

**Comment by laravellously** [comment]
Yeah @RomainLanz @thetutlage . It is really weird. I just updated Node to 9.5.0. Below is the error again
![captureii](https://user-images.githubusercontent.com/13837652/36207811-fc356dd8-114b-11e8-8c7a-3f686d508ec0.PNG)

Any ideas?

**Comment by thetutlage** [comment]
The issues seems to be related to the debug module https://github.com/visionmedia/debug.

Which terminal are you using?

**Comment by laravellously** [comment]
@thetutlage I am using Git Bash on Windows.

**Comment by thetutlage** [comment]
Are you able to run any other Node.js programs on Git bash.

Also what happens if you try it on windows command line

**Comment by laravellously** [comment]
Yes, I run all node programs from bash. Same error occurs on Windows Command line.

**Comment by thetutlage** [comment]
Weird, give me sometime. I will try it myself on a windows machine and will post an update

**Comment by laravellously** [comment]
Okay. But from the error log, I think the error comes from the package `enquirer`

**Comment by laravellously** [comment]
A little progress here... I re-installed it and it is working ONLY in Windows Command Prompt, but still not in Bash.

**Comment by thetutlage** [comment]
@laravellously Did it worked for you?

**Comment by laravellously** [comment]
@thetutlage Yes it did. I have started developing with it. It's super cool. Thanks.

**Comment by thetutlage** [comment]
Nice 👍 Did you find the issue behind it?

**Comment by laravellously** [comment]
Nope, not really. Seem to be a problem with npm cache. I did `npm cache verify` and then restarted my system. Oh, I also deleted all the folders in {Drive}/Users/{User}/AppData/Roaming/npm-cache directory. Hope this helps someone too.
