### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by amitguptagwl** [adonisjs/adonis-framework#791]
This is really a helpful framework. But when I compared the benchmark report against other frameworks, I found that adonis is not performing well.

https://github.com/PlainSight/NodeRestPerfTest3

Result
```
express
Requests per second:    10526.97 [#/sec] (mean)
raw_node
Requests per second:    17931.46 [#/sec] (mean)
restify
Requests per second:    11835.28 [#/sec] (mean)
koa2
Requests per second:    13180.16 [#/sec] (mean)
fastify
Requests per second:    15888.34 [#/sec] (mean)
total.js
Requests per second:    14446.93 [#/sec] (mean)
sails.js
Requests per second:    2016.40 [#/sec] (mean)
adonis.js
Requests per second:    4063.64 [#/sec] (mean)
```

I'm running tests on Ubuntu 17.10, 16gb RAM, node 9.5

**Comment by thetutlage** [comment]
U r benchmarking a way older version of AdonisJs

**Comment by webdevian** [comment]
See more discussion here - https://github.com/adonisjs/adonis-framework/issues/586

**Comment by amitguptagwl** [comment]
I have reinstalled adonis and it's cli to latest. But unfortunately got `Requests per second:    1302.72 [#/sec] (mean)` for the same tests.

**Comment by thetutlage** [comment]
How did you installed the `cli`?

**Comment by amitguptagwl** [comment]
I installed https://www.npmjs.com/package/@adonisjs/cli
```
sudo npm i --global @adonisjs/cli
```

**Comment by thetutlage** [comment]
Then please create a slim app using the cli and share a repo with benchmarks

**Comment by amitguptagwl** [comment]
Here is the forked and updated repo

https://github.com/amitguptagwl/NodeRestPerfTest3

**Comment by thetutlage** [comment]
The repo still has the old code

**Comment by thetutlage** [comment]
This is a old file https://github.com/amitguptagwl/NodeRestPerfTest3/blob/master/yardstick-changes/app/Http/routes.js

**Comment by amitguptagwl** [comment]
Thanks.  This time I have `--api-only` flag to create the repo. And used new route. New score is;

`Requests per second:    6475.26 [#/sec] (mean)`

**Comment by RomainLanz** [comment]
You must use the `--slim` flag if you want to have a realistic comparison between other frameworks. You are still currently comparing orange to apple. 😉

**Comment by amitguptagwl** [comment]
I completely agree that if you providing some feature it'll impact the speed somewhere. and `performance doesn't mean speed only`.
