### ISSUE TITLE
DB.raw queries and pagination

### ISSUE THREAD

**Issue by hxdef2517** [adonisjs/adonis-framework#793]
I have a query like `Database.raw(` .. `) `
But when I try to paginate `Database.raw(` .. `).paginate(params.currentPage, params.perPage)`
It says 

> Database.raw(...).paginate is not a function

I need to use raw queries for my task, only raw, so how can I paginate actually ?

**Comment by thetutlage** [comment]
If it's a raw query, then offset and limit should be in raw form right?

**Comment by hxdef2517** [comment]
Yes, thats how I implemented, so means there are no other way like in laravel in raw query still use paginator ?

**Comment by thetutlage** [comment]
I believe it's not possible from knex itself ( the underlying query builder ). Can you share the exact query you are trying to run?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
