### ISSUE TITLE
parse error while filtering data by created_at

### ISSUE THREAD

**Issue by kunaldodiya** [adonisjs/adonis-framework#794]
const User = use("App/Models/User");

// this is not working.. and no any example of filtering data by dates.. please help
const records = User.query().where("created_at", "<", Moment().substract(1, "day"));

// i am trying to fetch all users who were registered atleast 24 hours/ 1 day ago or before .. not today. 
but it gives parse error

**Comment by webdevian** [comment]
You need to format the moment date object as a mysql friendly string:

```js
const yesterday = Moment().substract(1, 'day').format('YYYY-MM-DD HH:mm:ss')
const records = User.query().where('created_at', '<', yesterday)
```

**Comment by thetutlage** [comment]
Closing since @webdevian answered the question.
