### ISSUE TITLE
No matching version found for @adonisjs/lucid@^5.0.2

### ISSUE THREAD

**Issue by lizhongyi** [adonisjs/adonis-framework#798]
No matching version found for @adonisjs/lucid@^5.0.2

**Comment by thetutlage** [comment]
<img width="391" alt="screen shot 2018-02-23 at 2 24 03 pm" src="https://user-images.githubusercontent.com/1706381/36585775-3d72643a-18a5-11e8-9f70-3323affae0a1.png">

**Comment by thetutlage** [comment]
Closing since not actionable
