### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by kazzkiq** [adonisjs/adonis-framework#80]
When running `npm start` after successfully running the [instalation steps](http://adonisjs.com/docs/2.0/installation) I'm getting this message if I try to access Adonis in a browser:

```bash
var/www/weevy/node_modules/adonis-framework/src/Request/index.js:123
    return nodeReq.post(this.request) || {}
                   ^

TypeError: nodeReq.post is not a function
    at Request.post (/var/www/weevy/node_modules/adonis-framework/src/Request/index.js:123:20)
    at Request.all (/var/www/weevy/node_modules/adonis-framework/src/Request/index.js:78:37)
    at Request.input (/var/www/weevy/node_modules/adonis-framework/src/Request/index.js:66:24)
    at Server.handle (/var/www/weevy/node_modules/adonis-framework/src/Server/index.js:77:28)
    at emitTwo (events.js:100:13)
    at Server.emit (events.js:185:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@2.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 1
```

I tried re-installing dependencies, re-installing `node-req` and even deleting the project and starting over. It still doesn't work. Any ideas?

**Comment by gearsdigital** [comment]
Are you using the latest version of adonis? Your error log points to `adonis-app@2.0.0`. Have you tried to run `npm update --save`?

**Comment by gearsdigital** [comment]
Seems to be related to https://github.com/adonisjs/adonis-framework/pull/79

**Comment by kazzkiq** [comment]
What exactly can I do in order to run Adonis without this issue?

I've tried runnin `npm update --save` without effects.

**Comment by kazzkiq** [comment]
Issue solved using this approach:

- Open `your-adonis-app/node_modules/adonis-framework/src/Request/index.js`
- Change `nodeReq.post(this.request)` by `nodeReq.hasBody(this.request)`
- Run `npm start` and try to access in browser.

It seems the issue was with the package `node-req` which changed its API from `.post()` to `.hasBody()` while Adonis still used the old one.

**Comment by thetutlage** [comment]
The scheduled change was for a new release and it's my bad i put the package on npm. Removed the latest version. So just do a quick `rm -rf node_modules && npm install --sav`

**Comment by thetutlage** [comment]
Verified and you are good to go
