### ISSUE TITLE
JSON error response is not match in development and production mode

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-framework#801]
**JSON  error response is not match in development and production mode**
### Sample Code
In BaseHandler when process.env.NODE_ENV === 'development' it generates error by Youch module
https://github.com/adonisjs/adonis-framework/blob/b2082d27bda81ac9c224612a474ddaa4aaa414a2/src/Exception/BaseHandler.js#L78-L82

Youch module generates such structure (in **error** porperty and without **code**)
```
{
  error: {
    message: "...",
    name: "...",
    status: 404,
    frames: [...]
  }
}
```

When NODE_ENV switch to production error message will generate by internal function and will be like
```
{
  message: "...",
  name: "...",
  code: "...",
  status: 404,
}

```
I suppose we need strict structure to get currect error message!
PS: I know that I can use own Handler, but...

**Comment by yariksav** [comment]
```
 if (process.env.NODE_ENV === 'development') { 
   const formattedError = await this._getYouchError(error, request.request, isJSON)
   response.status(error.status).send(Object.assign({code: error.code}, formattedError.error))
   return 
 }   
```
something like this

**Comment by thetutlage** [comment]
Why the error structure has to match in development n production?

Infact why you want to show the file paths from where the exception is thrown in production?

**Comment by thetutlage** [comment]
Also the structure you are mentioning is for unexpected errors and I believe your app should not have unhandled exceptions

**Comment by yariksav** [comment]
> Infact why you want to show the file paths from where the exception is thrown in production?
I don't want to show paths, I write REST API and every Exception such as ValidationException,  Forbidden, NotFount, TokenExpired - retranslate to client-side application and it has to do correct reaction. I just need message and code of exception, for example E_JWT_TOKEN_EXPIRED, etc. 
(ValidationException has own response structure)

> Also the structure you are mentioning is for unexpected errors and I believe your app should not have unhandled exceptions

I suppose ValidationException, Forbidden, NotFount, TokenExpired, InvalidParameter, etc - this is not unexpected error, this is normal error for REST API exchange

**Comment by thetutlage** [comment]
`ValidationException` seems to be returning the consistent output. 

![validation-exception](https://user-images.githubusercontent.com/1706381/36711822-7ddd11ba-1bab-11e8-99e7-13ef1dc8bdcc.gif)

**Comment by yariksav** [comment]
Yes, I wrote "(ValidationException has own response structure)" and works good. I mentoin about ValidationException for example to you question about unhandled errors. Such ua Validation has output description, other exceptions must have correct outputs to process it in client-side application

**Comment by thetutlage** [comment]
Every exception cannot define a consumable output, and that's why you have a custom exception handler to define your own standard response the way you want

**Comment by thetutlage** [comment]
Closing since not actionable
