### ISSUE TITLE
how can load my custom provider in any model

### ISSUE THREAD

**Issue by vrwebdesign** [adonisjs/adonis-framework#805]
I want to create new provider called Listoption and use it in any model.
so I create new folder with name providers and inside it create new file as Listoption.js

```'use strict'

const { ServiceProvider } = require('@adonisjs/fold')
class Listoption extends ServiceProvider {
  register () {
    // register bindings
    console.log('register');
  }

  boot () {
    console.log('boot');

    // optionally do some initial setup
  }
  test(){
    console.log('it is a test from provider');
  }
}

module.exports = Listoption
```
now I want to use Listoption in my Model and I don't now how to call it
`const Listoption = use('Adonis/providers/Listoption')`
I try to load but I have an Error.

**Comment by RomainLanz** [comment]
Hey @vrwebdesign! 👋 

It seems that you misunderstood the usage of Service Provider.
What are you trying to do?

**Comment by vrwebdesign** [comment]
I want to make listoption of any table that front end can filter or sort or search in any table of database.
in admin panel I have many table and I want to CRUD in all of them and in list i have a data grid and i want to sort and search and filter data from server side and I want to write a method that can do this for all Model

**Comment by RomainLanz** [comment]
I believe a Trait is what you're looking for http://adonisjs.com/docs/4.0/traits

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
