### ISSUE TITLE
how can use my custom model extend Model

### ISSUE THREAD

**Issue by vrwebdesign** [adonisjs/adonis-framework#806]
I want to create MyModel extends Model and use it inside of every model like this

`class User extend MyModel{}`

how can I do it?

**Comment by RomainLanz** [comment]
Hey @vrwebdesign!

What have you tried so far?
Note that this is a JavaScript question and it's not related to Adonis at all.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
