### ISSUE TITLE
Error in the documantaion

### ISSUE THREAD

**Issue by RandallFlagg** [adonisjs/adonis-framework#809]
Hi,

In the documentation on the adonisjs.com site at version 4.1 it is not clear where to put the global code.

At the [Extending Views](https://adonisjs.com/docs/4.1/views#_extending_views) section the following is written:

> Since the code to extend the View needs to be executed once, you can make use of providers or ignitor hooks. Make sure to read how to extend guide before continuing. 

but the link is pointing to the [Views](https://adonisjs.com/docs/4.1/views) page when expected to point to the extend guide.

Thanks.

**Comment by thetutlage** [comment]
Hello @RandallFlagg, thanks for pointing that out. Can you please create a PR for same in https://github.com/adonisjs/docs repo?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
