### ISSUE TITLE
Timezone out-of-the-box

### ISSUE THREAD

**Issue by rafaelfesi** [adonisjs/adonis-framework#810]
I was looking for something like Laravel has, on the file `config/app.php`, a variable that sets the default timezone used by the application like this: `'timezone' => 'UTC'`

But I didn't found it on AdonisJS.

So, I tested in a server with UTC timezone set on Linux and it just works fine, but I was wondering while developing with Adonis if on my mac could the application still save date as UTC on the database.

Also found this issue on Knex [#1461](https://github.com/tgriesser/knex/issues/1461) about the timezones. On my opinion is more interesting setting this on `config/app.js` to follows the framework philosophy.

I would like to know your thoughts about that and if would be interesting to has it out-of-the-box.

**Comment by moltar** [comment]
There is no good way to set the TZ in node from inside the node process.

See for more details: https://github.com/nodejs/node-v0.x-archive/issues/3286

Possible solutions:

* Set TZ in the `.env` file
* Set TZ env in your `.bashrc` file for your machine
* If you are using PostgreSQL, then simply use columns `with time zone` and the timezone becomes irrelevant.
