### ISSUE TITLE
TypeError Cannot assign to read only property 'name' of function '(file) => { return { name: `${new Date().getTime()}.${file.subtype}` } }'

### ISSUE THREAD

**Issue by hkmsadek** [adonisjs/adonis-framework#813]
await profilePic.move(Helpers.publicPath('uploads'), (file) => {
        return {
          name: `${new Date().getTime()}.${file.subtype}`
        }
     })

I am not being able to rename it. Why it's happening?

**Comment by hkmsadek** [comment]
I was able to change the file name this way 

       const type=request.file('file').subtype;
       const name= `avater_${new Date().getTime()}.${type}`
        await profilePic.move(Helpers.publicPath('uploads'), {
             name: name
        })

**Comment by thetutlage** [comment]
The first example is incorrect. I am not sure from where you got this code

**Comment by tlgreg** [comment]
Confused with `moveAll` most likely.
