### ISSUE TITLE
Question: How to add a custom logger driver?

### ISSUE THREAD

**Issue by Theremsoe** [adonisjs/adonis-framework#816]
I have the next code for register a custom driver in "Logger":

```javascript
class Provider extends ServiceProvider {
  register() {
    ioc.extend('Adonis/Src/Logger', 'my-driver', function (app) {
      return new Driver()
    })
  }
}
```

But when i try use this driver Adonis launch a exception:

```text
RuntimeException: E_INVALID_LOGGER_DRIVER: Logger driver my-driver does not exists.
> More details: https://err.sh/adonisjs/errors/E_INVALID_LOGGER_DRIVER
```

What it is wrong?

Thanks

**Comment by thetutlage** [comment]
Have you registered your provider inside the providers array

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by keeross** [comment]
Btw that's the problem I faced with, described it on forum here: https://forum.adonisjs.com/t/cant-extend-logger/1004
