### ISSUE TITLE
How would you implements "apollo-upload-server" with Adonis?

### ISSUE THREAD

**Issue by rafaelfesi** [adonisjs/adonis-framework#819]
I was trying to figure out how to implements the "**apollo-upload-server**" with AdonisJS Framework but without success. 

How would you implements it with AdonisJS, @thetutlage ? Have you any example how to integrate? I searched all over the internet for this solution, before open this issue. I only found example how to integrate with other frameworks.

Ref. URL: https://github.com/jaydenseric/apollo-upload-server/blob/master/readme.md

**Comment by thetutlage** [comment]
Why not use the existing file upload options?

**Comment by rafaelfesi** [comment]
I'm using GraphQL Server in both API and Client side. It is an implementation of file upload for graphql. So, the API responses is only in one route for all requests.

Then, after graphql processes the requisition I can use the `Drive` to upload it to AWS S3, for example.

**Comment by rafaelfesi** [comment]
Here's how the `route.js`looks like using GraphQL Server:

```javascript
const Route = use('Route')
const GraphqlAdonis = use('ApolloServer')
const schema = use('App/data/schema')

Route.route('/', ({ request, auth, response }) => {
    return GraphqlAdonis.graphql({
        schema,
        context: { auth }
    }, request, response)
}, ['GET', 'POST'])

Route.get('/graphiql', ({ request, response }) => {
    return GraphqlAdonis.graphiql(
        { endpointURL: '/' }, 
        request, 
        response
    )
})
```

**Comment by thetutlage** [comment]
@rafaelfesi Afraid, I am not much familiar with the package. Also just by the looks, you will have to use their `bodyparser` to allow file uploads. https://github.com/jaydenseric/apollo-upload-server/blob/master/readme.md

They ship for express and koa out of the box and not for Adonis. So the only option is use the custom middleware option they have in their docs

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by adrianyg7** [comment]
Hi guys, after a little research I came up with the following. Please notice some tricky things like `request.request` and `response.response` these are the NodeJS raw req/res. Don't forget to set `autoProcess` to false on bodyParser files.

Middleware
```
const { processRequest } = require('graphql-upload');

class GraphQlUpload {
  async handle ({ request, response }, next) {
    if (!request.is('multipart/form-data')) return await next();
    const finished = new Promise(resolve => request.request.on('end', resolve));

    try {
      request.body = await processRequest(
        request.request, response.response,
        { maxFileSize: 10000000, maxFiles: 10 }
      );
      await next();
    } finally {
      await finished;
    }
  }
}
```

config/bodyParser.js
```
{
  files: {
    autoProcess: false,
  }
}
```

**Comment by valmirphp** [comment]
@adrianyg7  This information was very useful. The days was breaking his head with this.

Thanks for the tip.
