### ISSUE TITLE
migration command error

### ISSUE THREAD

**Issue by pyaesone17** [adonisjs/adonis-framework#82]
when i try to run like this.
<code>
node ace migration:run. 
</code>
It shows
proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag

**Comment by thetutlage** [comment]
say `./ace migration:run`

**Comment by pyaesone17** [comment]
It shows like this. Sorry I m coming from php world :(
/usr/bin/env: node --harmony_proxies: No such file or directory

**Comment by thetutlage** [comment]
What command you are running? The Operating System you are on?

**Comment by pyaesone17** [comment]
ubuntu OS . I m running ./ace migration:run this commnad

**Comment by pyaesone17** [comment]
Although I m using Ubuntu  only 
windows command effect on me.
<code>
 node --harmony_proxies ace migration:run
</code>
I dont know why ?

**Comment by thetutlage** [comment]
No this command will work for everyone. `./ace` gives problem on windows

**Comment by pyaesone17** [comment]
<code>
./ace migration:run 
</code>
It doesn't still work .

**Comment by thetutlage** [comment]
Node binary is not inside your $PATH, that is the reason. http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory
