### ISSUE TITLE
Shouldn't the auth middleware redirect the user?

### ISSUE THREAD

**Issue by codingphasedotcom** [adonisjs/adonis-framework#821]
I'm working on a course with Adonis JS and I'm realizing one thing about the auth middleware that it does not redirect the user to anywhere. I'm looking for more information on the documentation and can't find anything on it either. I don't think this message should be the default when using the middleware.  
![screen shot 2018-04-03 at 11 14 06 pm](https://user-images.githubusercontent.com/26421899/38286750-f1c0bc30-3794-11e8-8960-91728a992fe3.png)

Loving the framework just a suggestion. 
Currently working on my own Auth Middleware to give the option to redirect the user to a specific route. Let me know if this has been already created or in the works

**Comment by RomainLanz** [comment]
Hey @codingphasedotcom! 👋 

You simply need to handle this exception in your exception handler and redirect from there.

**Comment by codingphasedotcom** [comment]
Ok got it thanks.
