### ISSUE TITLE
How do you return the old exception handler?

### ISSUE THREAD

**Issue by codingphasedotcom** [adonisjs/adonis-framework#823]
Ok so I followed the instructions in https://adonisjs.com/docs/4.1/exceptions#_handling_exceptions
```
adonis make:ehandler
```
now it gave me control to handle the exceptions but what if you want to return the old view that came with adonis
![screen shot 2018-04-03 at 11 14 06 pm](https://user-images.githubusercontent.com/26421899/38318409-411a66b0-37fd-11e8-87a2-828fa2d183f3.png)

instead of showing this
![screen shot 2018-04-04 at 11 41 05 am](https://user-images.githubusercontent.com/26421899/38318444-54ddb06c-37fd-11e8-8ba1-619f9f45f76c.png)

also is there a way to show the original view for all other exceptions except ```E_INVALID_SESSION: Invalid session```

**Comment by thetutlage** [comment]
You can call `super.handle`

```
class ExceptionHandler extends BaseExceptionHandler {
  async handle (error, ctx) {
      return super.handle(...arguments)
  }
}
```

Then `return` statement is very important

**Comment by codingphasedotcom** [comment]
thanks worked like a charm
