### ISSUE TITLE
zsh: command not found: adonis

### ISSUE THREAD

**Issue by NayeemUrRehman** [adonisjs/adonis-framework#824]
## Brief

Please check the following notes before creating any issue. Well formatted and concise descriptions will help us address your issues quickly

### Is this just a query?
If your question is just a query and not a bug or feature request. Consider asking it inside the [Gitter Channel](https://gitter.im/adonisjs/adonis-framework)

### Do you have multiple questions?
Please keep an issue focused on a single concern. Asking too many questions will confuse everyone.

## Choose the correct repo
Everyone has a tendency of creating issues inside `adonis-framework` repo. Please note adonis is a combination of several repos and creating issues in their dedicated repos will help everyone track existing issues and their fixes in a better way. For example:

1. ORM related issues should go to [adonis-lucid](https://github.com/adonisjs/adonis-lucid)
2. Auth related issues should go to [adonis-auth](https://github.com/adonisjs/adonis-auth)

Please check the [organization home page](https://github.com/adonisjs) to see the list of repos

**Comment by NayeemUrRehman** [comment]
By running `adonis --help` in terminal shows **zsh: command not found: adonis**

**Comment by RomainLanz** [comment]
Hey @NayeemUrRehman! 👋 

How did you install the adonis CLI?

**Comment by pedzed** [comment]
This issue should be closed in my opinion. 

This is a problem related to your own NPM installation. Not an AdonisJS problem.

---

Either way, you didn't mention your OS. So we cannot help. You can simply google for "[NPM change global directory](https://www.google.com/search?q=NPM+change+global+directory)" or "[NPM add global directory to path variable](https://www.google.com/search?q=NPM+add+global+directory+to+path+variable)".

**Comment by RomainLanz** [comment]
We keep the issue open for few days to let the issue reporter answer. 😄 

Closing this since it's not the case.
