### ISSUE TITLE
same password different hash result 

### ISSUE THREAD

**Issue by vrwebdesign** [adonisjs/adonis-framework#825]
I signup 2 user with same password in database and the password fields be different .
is this Okay?
and when i want to to auth the user with jwt method this error occurred 
the password in incorrect.

**Comment by thetutlage** [comment]
Yes hashes are always different, even for the same value.

Regarding where it says `password is incorrect`. Please share some code on how to authenticate the user and how you hash their password

**Comment by vrwebdesign** [comment]
Model/User.js
```
class User extends Model {
  static boot() {
    super.boot();
    this.addHook("beforeCreate", "User.hashPassword");
  }
}
```
Hook/User.js
```
UserHook.hashPassword = async (userInstance) => {
  if (userInstance.password) {
    userInstance.password = await Hash.make(userInstance.password)
  }
}
```
route
```
Route.post("login", "UserController.login");
```
controller
```
async login({ request, auth }) {
    const { email, password } = request.all();
    let token = await auth.attempt(email, password);

    return response
      .status(200)
      .json({ data: token, message: "Login successfull", status: true });
  }
```
result
```
[{"field":"password","message":"Invalid user password"}]
```

**Comment by vrwebdesign** [comment]
the problem was in migration.
I define the password field in varchar(50) but must define varchar(60)
