### ISSUE TITLE
Inconsistency between embedding assets ("css" and "script")

### ISSUE THREAD

**Issue by pedzed** [adonisjs/adonis-framework#826]
For embedding a stylesheet, you have the `css()` function, but for embedding a script, you have `script()`. This is an inconsistency which confuses people.

### Proposal  1
Keep `script()` and change `css()` to `style()`.

### Proposal 2
Keep `css()` and change `script()` to `js()`.

Either change should have a temporary deprecation time. In the mean time, aliasing can be used for a transition: if proposal 1 gets chosen, `css()` can call `style()` until `css()` gets removed entirely.

Related documentation: https://adonisjs.com/docs/4.1/views#_globals

![image](https://user-images.githubusercontent.com/8146593/38524259-4d86ed56-3c4e-11e8-9d34-7a148e7f0e8e.png)

**Comment by thetutlage** [comment]
Yes we can have `script` and `style` and let `css` be their with a deprecation warning

**Comment by RomainLanz** [comment]
Would you mind creating a PR for this @pedzed?

**Comment by webdevian** [comment]
I can do it. I've already implemented similar in adonis-pug
