### ISSUE TITLE
Route validator can not work

### ISSUE THREAD

**Issue by spenggithub** [adonisjs/adonis-framework#829]
According to the guide, I put the route validator in the route.js file and generated the validator file for StoreUser.js, but it doesn't work
`Route.post('login', 'LoginController.login').validator('StoreUser')`
`get rules () {
    return {
      email: 'required|email|unique:users',
      password: 'required'
    }
  }`

**Comment by thetutlage** [comment]
What’s not working?

**Comment by juhguu** [comment]
I have the same problem.
The validation only works if I call him directly in my controller action using the "traditional form". If I use the Router Validator, nothing happens.

My router - common.js:
```javascript
'use strict'

const Route = use ('Route')

Route.group(() => {
  Route.resource('/colors', 'ColorController')
    .validator(new Map([
      [['colors.store'], ['StoreColor']]
    ]))
    .apiOnly()
})
  .prefix('api/v1')
  .namespace('Api/v1')
```

My test controller - ColorController.js:
```javascript
  async store ({ request, response }) {
    const color = new Color()
    await color.save()

    response.status(201).json({
      message: 'Successfully created a new color.',
      data: color
    })
  }
```

My validator - StoreColor.js

```javascript
'use strict'

class StoreColor {
  get validateAll () {
    return true
  }

  get rules () {
    return {
      'name': 'required'
    }
  }

  async fails (errorMessages) {
    return this.ctx.response.send(errorMessages)
  }
}

module.exports = StoreColor
```
