### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by tavsta** [adonisjs/adonis-framework#832]
Knex:warning - Connection Error: Error: Connection lost: The server closed the connection.

I have issue and it just show this message.
It make my app crash.

**Comment by thetutlage** [comment]
The error is pretty descriptive that your MYSQL server closed the connection

**Comment by tavsta** [comment]
This error only happen when using transaction.

**Comment by alexhenriquepv** [comment]
So .. how to prevent "app crash" when lost connection? Currently my app is crashing many times in day.

![image](https://user-images.githubusercontent.com/12400276/70823055-bb806600-1dbd-11ea-95ff-61513af3940b.png)
