### ISSUE TITLE
Request option to have semi-colons inserted after statements

### ISSUE THREAD

**Issue by FrenchMajesty** [adonisjs/adonis-framework#833]
Coming from a PHP background working with Laravel I could not have dreamed of a better Node.js framework I could find. I frankly thank you for this genius piece of software engineering. 

Now, what I just noticed is that when using the command line (or not) every file that the framework generates is created without the semi-colons and by preference some programmers like to write JavaScript code **with** semicolons and having to go back and add them at the end of every statement on every single model, migration, controller, etc... that I create can become ridiculously tedious.

For example my company's JavaScript coding style guidelines requires the semicolons after every statement.

I think it would be nice to have an option to initialize a project with semicolons so that programmers don't have to go back behind what's been created and add them manually.

Having an option that work along the lines of `adonis new coolApp --semicolons` would be really great.

**Comment by webdevian** [comment]
Couldn't you do this with your linter of choice? I think Prettier might be able to it as part of your build process

**Comment by RomainLanz** [comment]
Hey @FrenchMajesty! 👋 

This was already discussed [here](https://github.com/adonisjs/discussion/issues/28) and the answer will still be the same: _No, we will not add that_.

As @webdevian state, you can use a linter that fix that for you automatically.

**Comment by thetutlage** [comment]
@FrenchMajesty Frankly saying Javascript has too many paths in terms of formatting. If I will add support for semi-colons, then one will ask for `4 spaces indentation` and so on.

I will try to keep Adonis away from all this and have only one template. You can always use `prettier` to fix all the files for you, right after installation.

```bash
adonis new your-app && prettier --write **/*.js
```
