### ISSUE TITLE
Adonis serve --dev dont work even after new fresh install

### ISSUE THREAD

**Issue by Naenaesean** [adonisjs/adonis-framework#834]
## Brief

Hi.
Today, when im trying to open my server with adonis serve --dev, no errors displayed and I can still use the control terminal, as if nothing had happened, my server does not open.... I can not debug it if I do not know the error.
I tried to delete the node_modules folder, but still nothing, even after emptying the npm cache. 
i tried to adonis serve --debug too but nothing happened too.
there are no issues on the internet like this to resolve it, i do not know how to fix this bug ..
It all started bugging when I added the validatator provider, and since then, even removing it, I still have this error. What should I do?
   
      
 ### Screenshots (if any)
https://image.noelshack.com/fichiers/2018/16/6/1524309395-adonis.png

**Comment by Naenaesean** [comment]
Hello. first of all, thanks for you quick answer.

after several attempts since this morning, i finnaly resolve my problem!

I uninstalled all npm/node folders. and when i re install all the components, finally, it worked!
Sorry for the inconvenience.
And thank you for your great framework, im loving it!

**Comment by thetutlage** [comment]
Cool :)
