### ISSUE TITLE
How to run multiple instances?

### ISSUE THREAD

**Issue by tavsta** [adonisjs/adonis-framework#835]
I want to use load balancing, but don't know how to run multiple instance per source.

**Comment by thetutlage** [comment]
1. You can use inbuilt node.js cluster module and it will load balance for you.
2. Or simply run 2 instances of codebase on different ports.

```js
PORT=4444 node server.js
PORT=5555 node server.js
```

**Comment by webdevian** [comment]
PM2 also works well for this:

`pm2 start server.js -i <number-of-workers>`
