### ISSUE TITLE
Sending status code and message with response.send in AdonisJS version 4.1 shows always 200

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#836]
I am writing RESTful APIs with AdonisJS version 4.1, and I am trying to send from the server error messages, whatever they are.

First, I have created an `Operation` class which has common operations for storing errors and validating the rules.

    "use strict";
    
    const Validator = use('Validator');
    const HTTP = use("App/HTTPResponse");
    
    /**
     * Class model for basic operations
     *
     * @author gabriel
     * @class
     */
    class Operation {
      constructor() {
        this.errors = [];
        this.validator = Validator
      }
    
      /**
       * Common rules
       *
       * @returns {{}}
       */
      get rules() {
        return {}
      }
    
      async validate() {
        this.errors = [];
    
        const validation = await this.validator.validate(this, this.rules);
    
        if (validation.fails()) {
          validation.messages().map((err) => {
            this.addError(HTTP.STATUS_INTERNAL_SERVER_ERROR, err.message);
          });
    
          return false
        }
    
        return true;
      }
    
      /**
       * Function for adding an error message to the array of errors
       *
       * @param code
       * @param message
       * @returns {Promise<void>}
       */
      async addError(code, message) {
        await this.errors.push({ code, message })
      }
    
      /**
       * Gets the first error on the errors list
       *
       * @returns {Promise<*>}
       */
      getFirstError() {
        return this.errors[0]
      }
    }
    
    
    module.exports = Operation;

Then, my `InvoiceInfoOperation`, which extends `Operation` class, will attempt to validate these fields before proceeding with the operation:

    class InvoiceInfoOperation extends Operation {
    ...
    async store() {
      if (!this.validate()) {
        return false;
      }
      ...
    ...

Then, the `InvoiceInfoController`:

    async store({ request, response }) {
      const op = new InvoiceInfoOperation();
      op.invoiceId = request.input("invoiceId");
      op.invoiceAmount = request.input("invoiceAmount");
      op.paymentTarget = request.input("paymentTarget");
  
      const store = await op.store();
  
      if (!store) {
        const error = op.getFirstError();
        return await response.send(error.code);
        // return await response.send(error.code, error.message);
        // return response.status(error.status).send(error.message);
      }
  
      return response.send(200);
    }

The commented codes are my previous attempts. Also tried without `await`. The thing is that using Insomnia software, I can see the status code is always shown 200. Take an example where I forgot to specify a mandatory field, which will then execute the `addError` method from `Operation`, since the validation fails:

[![enter image description here][1]][1]

The number "500" that is shown here what is passed to `send()` to the controller. Obviously, since there is a 200 at the top of the window of Insomnia, it means it is not sending anything.

  [1]: https://i.stack.imgur.com/rTAT6.png

**Comment by thetutlage** [comment]
It has to be

```js
response.status(statusCode).send(body)
```

**Comment by thetutlage** [comment]
Going to close
