### ISSUE TITLE
Adonis 4 error on Ignitor file on production which i did not touch that file

### ISSUE THREAD

**Issue by jbrhinalyn** [adonisjs/adonis-framework#840]
Hi,

I got this error on my server which totally i did not open/edit that file.

at Object.<anonymous> (/var/www/jblhosting.xyz/node_modules/@adonisjs/ignitor/index.js:13:17)
6|server   | /var/www/jblhosting.xyz/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:285
6|server   |   async _bootProviders () {
6|server   |         ^^^^^^^^^^^^^^
6|server   | SyntaxError: Unexpected identifier
6|server   |     at createScript (vm.js:56:10)
6|server   |     at Object.runInThisContext (vm.js:97:10)
6|server   |     at Module._compile (module.js:542:28)
6|server   |     at Object.Module._extensions..js (module.js:579:10)
6|server   |     at Module.load (module.js:487:32)
6|server   |     at tryModuleLoad (module.js:446:12)
6|server   |     at Function.Module._load (module.js:438:3)
6|server   |     at Module.require (module.js:497:17)
6|server   |     at require (internal/module.js:20:19)
6|server   |     at Object.<anonymous> (/var/www/jblhosting.xyz/node_modules/@adonisjs/ignitor/index.js:13:17)

No issue in my local. I just really don't know how the cause of it. 
Version on my server
nodejs version is v9.11.1
npm version is 5.6.0

Adonis 3.2, no problem at all. Only this latest version which i have that problem.

**Comment by webdevian** [comment]
What version of Node are you using? I get the error if I use a version that doesn't support Async/Await

**Comment by jbrhinalyn** [comment]
i'm using nodejs v9.11.1

**Comment by jbrhinalyn** [comment]
nodejs version in my laptop is v8.9.1 which is working. maybe i have to downgrade to that version.

**Comment by webdevian** [comment]
It should work on 9.x too.

How are you detecting the version on your server? Try adding `console.log(process.version)` into server.js just to check the version the script is actually being run under

**Comment by jbrhinalyn** [comment]
the app die right away after pm2 restart server.js
![screenshot_7](https://user-images.githubusercontent.com/14085295/39131985-5be0e3b6-4743-11e8-9723-4ed5594e30be.png)

**Comment by jbrhinalyn** [comment]
i downgrade my nodejs version to v8.9.1 same with my local node version and the problem are still the same. :(

**Comment by webdevian** [comment]
It could be a problem with PM2. What happens if you run server.js directly in the command line?

**Comment by webdevian** [comment]
Yes that looks right. Then the app starts serving ok?

**Comment by jbrhinalyn** [comment]
No. The solution was to upgrade to latest version of NPM. Its working now with latest version of NPM. Thanks @webdevian . Really appreciate it. 😄

**Comment by jbrhinalyn** [comment]
Closing now this ticket since issue is been resolve and not related to AdonisJS.
