### ISSUE TITLE
can't get middleware props

### ISSUE THREAD

**Issue by sekseason** [adonisjs/adonis-framework#843]
I've create role middleware:

_class Role {
  async handle({ request, auth, response }, next, roles) { 
    console.log(roles) --> output: []
    ......
  }
}
module.exports = Role_

register at `app/kernel.js` as

_const globalMiddleware = [_
 ...
  _'App/Middleware/Role'_
_]_

_const namedMiddleware = {_
  ...
  _role: 'App/Middleware/Role'_
_}_

and call at `routes.js' as 

_.middleware(['auth:jwt', 'role:admin'])_

can't get the 'admin' value in middleware, am i missing something?
and this middleware gets called every time, even not attached to the route.

**Comment by thetutlage** [comment]
Can you please format the codeblocks?
