### ISSUE TITLE
Error: Cannot find module after delete Model How to resolve?

### ISSUE THREAD

**Issue by 7elven** [adonisjs/adonis-framework#849]
in laravel use: composer dump-autoload
how adonis ?

**Comment by 7elven** [comment]
@RomainLanz 
I create new project with adonis
I try to crate User Model by adonis cli but I want to change model name
I delete User model file and create new model by cli again

when I try start app by "adonis serve --dev" it's error
Error: Cannot find module 

I sorry about error log because I remove all directory and create new adonis project
-*-  I want to know how to fix this error when I try to delete model file again

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
