### ISSUE TITLE
route not found (404 error)

### ISSUE THREAD

**Issue by sekseason** [adonisjs/adonis-framework#850]
i've SPA in `/public` folder and in routes.js

_Route.any('*', async ({ response }) => {
  return response.download(Helpers.tmpPath('public/index.html'))
})_

go to http://localhost:3333 everything works fine,
but got 404 when go to http://localhost:3333/home

it is correct to use '*' as wildcard route?

**Comment by thetutlage** [comment]
Do you have this file inside `tmp/public/index.html`?

**Comment by sekseason** [comment]
got it, update the path as below every thing works now.

_return response.download(Helpers.tmpPath('../public/index.html'))_

thanks.
