### ISSUE TITLE
Use objects for where clauses in query builder 

### ISSUE THREAD

**Issue by FrenchMajesty** [adonisjs/adonis-framework#854]
Hello,

In the doc it specifies two ways of creating where clauses in a query:

```
const users = await Database.from('users').where('id', 1)
// Or
const users = await Database.from('users').where({ id: 1 })

```
So I tried to run a query like the following:

![carbon 3](https://user-images.githubusercontent.com/24761660/39784543-5c50f858-52de-11e8-9c9e-30bb1d3f011c.png)

But it would be nice if that functionality could be implemented for the cases where there might be more than one query filters applied. Consider the following use case:

![carbon 1](https://user-images.githubusercontent.com/24761660/39784420-f59e759a-52dd-11e8-8795-bf6c336d32cb.png)

**Comment by thetutlage** [comment]
Can you be more specific with your issue. When you say it didn't work, what do you mean by that?

Also please enable query debugging and share the SQL queries output too

**Comment by thetutlage** [comment]
Your first comment shows queries related to `User` and `Cars` and the sql output shows query on `verifications_codes`.

Now I am not sure if the SQL output is correct, since I cannot see the code that you wrote, which output this SQL query.

In short, I want to know

1. What code you write in Javascript?
2. What's the SQL output of the query?
3. What is the expected output?

**Comment by FrenchMajesty** [comment]
@thetutlage If you noticed the 1st example in the original post is not the same as the second as well, they were examples to show what I was trying to do. Sorry for the confusion.

1. My actual code is:
![carbon](https://user-images.githubusercontent.com/24761660/39797936-10d551b2-5324-11e8-9b4c-3da241665309.png)

2.The SQL output is:
![carbon 1](https://user-images.githubusercontent.com/24761660/39797949-1d8a952a-5324-11e8-9f58-66264ead2c5f.png)
