### ISSUE TITLE
Question: Manipulate data before return in Route controller

### ISSUE THREAD

**Issue by FrenchMajesty** [adonisjs/adonis-framework#855]
Hello,

I want to pull in data from my database, do some manipulations with it and then return a response to the API request however I'm unable to do that.

So in my controller this is what I'm doing:
![carbon 4](https://user-images.githubusercontent.com/24761660/39788304-759635a6-52ef-11e8-81c9-5c5d8957e22d.png)

I thought it may be due to the async/await nature of the query so I tried to use a promise with no avail.

![carbon 5](https://user-images.githubusercontent.com/24761660/39788401-f6e02ed2-52ef-11e8-9d77-7aecc4fdfbba.png)

I've been trying to look for answers online but I cannot find any. Why is this happening and how can I get around that? It doesn't make sense for me to return raw data to then manipulate it on the front-end.

**Comment by thetutlage** [comment]
Can you share the output of `console.log(datas)`

**Comment by FrenchMajesty** [comment]
@thetutlage 
![screen shot 2018-05-08 at 11 12 33 pm](https://user-images.githubusercontent.com/24761660/39795383-5f37a328-5315-11e8-8c4b-0fbf659fa15e.png)

**Comment by thetutlage** [comment]
Yup, the output is not an array. It's an instance of `VanillaSerializer` with `rows` property (array) on it.

```js
console.log(datas.rows[0])
```

**Comment by FrenchMajesty** [comment]
I'm blind, thank you.
