### ISSUE TITLE
Ioc in app/services instead providers/

### ISSUE THREAD

**Issue by romulo1984** [adonisjs/adonis-framework#859]
The `app/services` folder is autoloaded by default. But is it possible to bind my services within this folder using IoC, so I do not need to use 'new' to instantiate my class and not use ServiceProvider?

Example:
```javascript
// app/services/HelloService.js
class HelloService {
    constructor (Config) {
        this.Config = Config
    }

    foo () {
        return 'foo'
    }
}

module.exports = HelloService

// app/controllers/HelloController.js
const HelloService = use('app/services/HelloService')

class HelloController {
    bar () {
        const foo = HelloService.foo()
    }
}
```

**Comment by thetutlage** [comment]
Simply export `new HelloService()`?

**Comment by thetutlage** [comment]
Once your code is inside your own Adonis app, there is no need to complex things. The real benefit of IoC bindings is, when you want to distribute the code.

Keep it as simple as

```js
const Config = use('Config')

class HelloService {
}

module.exports = new HelloService()
```

**Comment by thetutlage** [comment]
Thanks 😄
