### ISSUE TITLE
how to includenode_modules css and js

### ISSUE THREAD

**Issue by sergiopeluzzi** [adonisjs/adonis-framework#860]
Hello... I'm new on adonijs. I need some help including some files on my main page.

I'm using template tags to add my custom css and js files
`{{ css('main.css') }}`
and
`{{ script('main.js') }}`

These files in public folder, and it's OK
But i need add other css and js files in node_modules folder.
I've tried
`{{ css('../node_modules/bootstrap/bootstrap.css') }}`
`{{ css('/node_modules/bootstrap/bootstrap.css') }}`
`{{ css('node_modules/bootstrap/bootstrap.css') }}`
and nothing works

There is one soluction for this or am I totally wrong?

**Comment by thetutlage** [comment]
Let’s say you are not using Adonis or Edge, how will you serve files on HTTP from `node_modules`

**Comment by sergiopeluzzi** [comment]
link tag?

**Comment by webdevian** [comment]
You can only serve static files from your public folder.

You don't want to expose node_modules to the outside world, you'll risk exposing source code and vulnerabilities.

**Comment by RomainLanz** [comment]
No need to keep this open.
This isn't an issue with Adonis itself.

You need to move your file over the `public` folder or use some assets bundling tool to compile them and generate a bundle inside your `public` folder.
