### ISSUE TITLE
Hook event beforeDelete not working

### ISSUE THREAD

**Issue by cookievu** [adonisjs/adonis-framework#865]
I using hook event **beforeDelete** in my model.
I use `await post.attachments().delete()` but it not working for me.
**beforeCreate** working.

**Comment by RomainLanz** [comment]
Hey @cookievu ! 👋 

Could you please create a repository with the minimum code to reproduce the issue?

**Comment by cookievu** [comment]
@RomainLanz 
Thanks for reply :))
My repo
[https://github.com/cookievu/awesome-adonis.git](awesome-adonis repo)

Wish you a good day

**Comment by thetutlage** [comment]
Because `post.comments().delete()` is bulk delete operation and hooks are always called when you perform actions on a single instance.

**Comment by cookievu** [comment]
@thetutlage Thank you for your comment. From that you have found my solution.

**Comment by sorxrob** [comment]
May I know your solution to this problem @cookievu ? Thank you.
