### ISSUE TITLE
executing adonis --help command give error

### ISSUE THREAD

**Issue by simonmawole** [adonisjs/adonis-framework#866]
I try run the command "adonis --help" and throw error message see below. But if i delete node_module the command execute with no problem 
I am running windows 10 64-bit with node v8.11.2

SyntaxError: Unexpected identifier

1 _preLoadFiles.forEach
  C:\Users\Simon\NodeJsProjects\jevvie-backend\node_modules\@adonisjs\ignitor\src\Ignitor\index.js:375

2 Ignitor._loadPreLoadFiles
  C:\Users\Simon\NodeJsProjects\jevvie-backend\node_modules\@adonisjs\ignitor\src\Ignitor\index.js:367

3 Ignitor.fire
  C:\Users\Simon\NodeJsProjects\jevvie-backend\node_modules\@adonisjs\ignitor\src\Ignitor\index.js:760

**Comment by RomainLanz** [comment]
Hey @simonmawole! 👋 

This is a weird issue.
Could you please try to reinstall the CLI with `npm i -g @adonisjs/cli`?

**Comment by thetutlage** [comment]
One of your project files inside the `start` folder has a syntax error

**Comment by simonmawole** [comment]
Hello @thetutlage here are files inside start folder.  I cant find where the syntax error located, so i just initialize another project directory and copy code there and it works fine now
[app.txt](https://github.com/adonisjs/adonis-framework/files/2045907/app.txt)
[kernel.txt](https://github.com/adonisjs/adonis-framework/files/2045908/kernel.txt)
[routes.txt](https://github.com/adonisjs/adonis-framework/files/2045909/routes.txt)

**Comment by thetutlage** [comment]
@simonmawole I was expecting you to simply paste the code. Anyways, nice that it works fine in a new project.
