### ISSUE TITLE
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

### ISSUE THREAD

**Issue by mendrinos** [adonisjs/adonis-framework#868]
# Environment

AdonisJS version: 4.1
Knex version: 0.14.5
Database + version: MySQL 5.7.21
OS: MacOS 10.13.4 (17E202)

# Deprication logs

Using the AdonisJS framework and when I run:

`await Database.raw('use ' + subdomainDbName).get()`

I am getting this deprication logs:

`(node:8013) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.`

Not a bit issue; but my log files are getting bloated with this Warning, and wondering if it is related to Knex.js?

**Comment by tlgreg** [comment]
Neither knex or lucid seems to directly use `unenroll`, most likely the database driver is the issue.
mysqljs/mysql#2003 has the issue about it, `mysql2` or `pg` doesn't use `unenroll`, not sure about others.

**Comment by anurbol** [comment]
I also have this when running migration. Not near computer right now, can someone find which package uses unenroll.

**Comment by thetutlage** [comment]
Closing since not actionable
