### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by ivanguimam** [adonisjs/adonis-framework#869]
I have the following services:

**User**

    module.exports = class UserService {
        static get inject () {
            return ['App/Services/Solicitation']
        }
        constructor (SolicitationService) {
            this.solicitationService = SolicitationService
        }
    }

**Solicitation**

    module.exports = class SolicitationService {
        static get inject () {
            return ['App/Services/User']
        }
        constructor (UserService) {
            this.userService = UserService
        }
    }

As one service ends up injecting the other when I call my endpoints I get the following error: `Maximum call stack size exceeded`

**Comment by RomainLanz** [comment]
Hey @ivanguimam ! 👋 

Could you please create a repository with the minimum code to help us reproduce the issue?

**Comment by thetutlage** [comment]
Since Node.js doesn't allow circular dependencies, it will be hard to avoid them. IoC container can try to detect bindings and do not `require` them if already required, but I believe I don't want to go that path as of now.
