### ISSUE TITLE
How to use 'in' rule for non-string values?

### ISSUE THREAD

**Issue by BatuhanK** [adonisjs/adonis-framework#872]
## Brief

I have a custom validator like this: 

```js
class PlanCalculate {
  get rules () {
    return {
      like_count: 'required|in:1000,2000,3000'
    }
  }
  get sanitizationRules () {
    return {
      like_count: 'to_int'
    }
  }
}
```
If I send post body like below it fails
```json
{
  "like_count": 3000
}
```
But if I send like this it passes
```json
{
  "like_count": "3000"
}
```

How can I use in validator for numbers?

**Comment by thetutlage** [comment]
If you are sanitizing the value to an int, then you must validate integers only. Also make use of `rule` method to define the values as an array. https://indicative.adonisjs.com/docs/in

```js
like_count: [
  rule('required'),
  rule('in', [1000, 2000, 3000])
]
```
