### ISSUE TITLE
Server Timeout

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/adonis-framework#877]
We just ingested more than 3 Million additional data points into our database (creating countless records) this had caused our queries to skyrocket past the default nodejs server timeout of 120,000ms.

I've tried disabling the Http timeout inside of app/Listeners/Http.js:

-------------------------------------------------------------------------

```
const Server = use('Adonis/Src/Server')

Http.onStart = function () {
    Server.getInstance().timeout = 0;
};
```

> A value of 0 will disable the timeout behavior on incoming connections.

https://nodejs.org/api/http.html#http_server_timeout

-------------------------------------------------------------------------

However this doesn't seem to work as timeouts still occur after 120,000ms and nginx indicates that the server is still prematurely closing the connection.

**Comment by thetutlage** [comment]
Are you using adonis 3.2?

**Comment by RaymondLC92** [comment]
@thetutlage No I'm on AdonisJS 4.1

**Comment by thetutlage** [comment]
https://adonisjs.com/docs/4.1/ignitor#_hooks

**Comment by RaymondLC92** [comment]
Thanks, that was enough to get it working.

Solution included for those those who may also be searching:

> start/hooks.js

```
const { hooks } = require('@adonisjs/ignitor')
const Server = use('Adonis/Src/Server')

hooks.after.httpServer(() => {
    Server.getInstance().timeout = 0;
})
```

**Comment by RaymondLC92** [comment]
@thetutlage This appears to still not be working, previous tests completed successfully because the query came back slightly faster.

**Comment by thetutlage** [comment]
How do you verify?

**Comment by RaymondLC92** [comment]
We have a route that returns a compilation of stats within our database, it takes about 3 minutes in the production database.

I hit the route, and see if the node server 502s at the 120,000ms mark, however on the dev database there's less records so when I tested it it happened to come back just below 120,000ms causing it to avoid being killed off.

**Comment by thetutlage** [comment]
I believe then you are testing Node.js HTTP server functionality. Whereas in this case, you need to confirm that calling `Server.getInstance().timeout = 0` does set the timeout or not.

**Comment by RaymondLC92** [comment]
How else would you recommend testing the timeout was set if not by checking to see if it did in fact override the default 120,000ms timeout?

If the timeout is disabled, the Node HTTP server shouldn't timeout.

**Comment by thetutlage** [comment]
Then that should be an issue with the HTTP server itself and not the logic on how to setup the timeout. Both are different issues

**Comment by RaymondLC92** [comment]
How would you suggest making sure that the timeout has actually been changed?

**Comment by RaymondLC92** [comment]
@thetutlage I moved my code from the hook into the server.js file by adding a .then.

```
    .then(() => {
        use('Adonis/Src/Server').getInstance().timeout = 0;
        use('Logger').info(`Server timeout: ${use('Adonis/Src/Server').getInstance().timeout}`);
    })
```

Now my server waits for the query correctly (With it taking upwards of 170,000ms) and the route returns 0.

Was my hook wrong in some way?

**Comment by thetutlage** [comment]
The call to `const Server = use('Adonis/Src/Server')` should be inside the `hook` callback. 

Note: when hooks file is loaded the IoC container bindings are not available.

**Comment by thetutlage** [comment]
Anyways, I am closing the issue, since this is not something I can take action on. If you want to talk more about it, use the discord server
