### ISSUE TITLE
Adonisjs test pipeline

### ISSUE THREAD

**Issue by hakerkiler** [adonisjs/adonis-framework#878]
Hi,
I whant to browser unit test automatical show page with pipelines from bitbuket
But when runing test http server is not runing.
Help me please

**Comment by RomainLanz** [comment]
Hey @hakerkiler ! 👋 

I'm sorry, but I didn't understand what's your issue about.

**Comment by hakerkiler** [comment]
how i can test web browser without run nump start?

**Comment by RomainLanz** [comment]
Have you read the documentation about testing?

🔗 https://adonisjs.com/docs/4.1/browser-tests

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
