### ISSUE TITLE
auth.attempt issue returns error "select * where username = 'blahblah'"

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#879]
### Brief Description
     I am trying to create a login on my application, I utilized the auth.attemp() method from your docs. but it returns an error, sql error, as you can see based from the screenshot it doesn't define the table where to select
### Sample Code
`   async login({request, auth}){
        const {username, password} = request.all();
        await auth.attempt(username, password);

        return 'Logged in successfully'
    }`

### Screenshots (if any)
![image](https://user-images.githubusercontent.com/34019246/41018560-f2c24d2c-698c-11e8-9ded-5c85787a063c.png)

**Comment by thetutlage** [comment]
Please share the `config/auth.js` and User model file

**Comment by RomainLanz** [comment]
Closing since no issue from issue reporter.
