### ISSUE TITLE
Error finding module on a live server

### ISSUE THREAD

**Issue by dongido001** [adonisjs/adonis-framework#880]
I have a route for an API which I created in api.js and then import it to routes.js.

For an endpoint, I have a code like below:

```
  Route.post('/user/register', 'api/v1/AuthController.register')
```

The `AuthController.js` file is located in `/app/Controllers/Http/API/v1/AuthController.js`.

Now my confusion. On my local `localhost:3333/user/register'` works pretty well without error but on a live server, I get this error:
```
Error: Cannot find module '/app/Controllers/Http/Api/v1/AuthController'
```

But when I change the route on the live server to:
```
Route.post('/user/register', 'API/v1/AuthController.register')
```

It works.

I'm just curious what might be going on here.

**Comment by thetutlage** [comment]
Directories in Mac are not case sensitive, however in Linux they are.

**Comment by thetutlage** [comment]
Also I recommend using the forum for questions, which are not confirmed bugs
