### ISSUE TITLE
Provide seed value to Factory provider

### ISSUE THREAD

**Issue by adrian-gallardo-wizeline** [adonisjs/adonis-framework#884]
## Brief
I would like to be able to provide a seed value to faker (chancejs) instance

The idea behind this is to generate (sequentially) always the same data when running a seeder 

In the project I'm working on I could manage to do the following:

```
const seededModels = {}

function seedModelIfNeeded(modelName, faker, seed) {
  if (seededModels[modelName]) {
    return
  }
  faker.mt.init_genrand(seed)
  seededModels[modelName] = true
}

Factory.blueprint('App/Models/Schema', (faker) => {
  
  seedModelIfNeeded('App/Models/Schema', faker, 12345)

  return {
    name: faker.sentence({ words: 3 }),
    ...
  }
})

```

This workaround is working as expected, so every time I run the seed command I get the same generated models with the expected data

What do you think about adding support to this feature? or it is already possible to address this somehow? I could't find anything about this in the doc

**Comment by RomainLanz** [comment]
Hey @adrian-gallardo-wizeline! 👋 

I don't get what your code is doing since calling `seedModelIfNeeded('App/Models/Schema', faker)` do nothing.

**Comment by adrian-gallardo-wizeline** [comment]
Hey @RomainLanz thanks for your interest, I've updated the snippet just in case

So, before adding those lines to the `factory` script, everytime I run `adonis migration seed` I get different values for my seeded models.. ie:
 lets say I'm creating two models and the name property that is generated on each is `one two three` and `four five six` (random 3 words).. but next time I run the `seed` command I get another words for each model, like `seven eight nine` and `some other words`..

The idea behind providing a seed value is that everytime I run the `migration seed` command I get the same values for the models I'm creating, so following the example I would get always  `one two three` and `four five six` for the first two models I create with this factory

I think this could be nice if supported internally by the `Factory.blueprint`, so you can just provide the seed value through some configuration object, ie:

```
Factory.blueprint('App/Models/Schema', (faker) => {
    return {
    name: faker.sentence({ words: 3 }),
        ...
     }
}, {fakerSeed: 1234})

```

**Comment by RomainLanz** [comment]
This already exists, you need to use the third parameters of the `Factory` function.

Exemples:
**Factory** - https://github.com/adonisjs/adonis-blog-demo/blob/master/database/factory.js
**Usage** - https://github.com/adonisjs/adonis-blog-demo/blob/master/test/functional/authentication.spec.js#L34

**Comment by RomainLanz** [comment]
Oops, wrong button 😄

**Comment by adrian-gallardo-wizeline** [comment]
Hey @RomainLanz, thanks for the examples, but I think that is not what I was trying to achieve.
Please take a look at this documentation about the faker `seed`: https://chancejs.com/usage/seed.html

What I wanted to get from the `factory` are models which data is more predictable. By using a seed you are ensured to get the same results

But maybe what you shared before is the right way to go, provinding values for the properties that I want to be present in the output object. Thanks for the suggestion!

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
