### ISSUE TITLE
Add copyright in generated files

### ISSUE THREAD

**Issue by Melchyore** [adonisjs/adonis-framework#887]
Hello,

I was wondering if you can add the ability to use copyright in files created via `adonis make:*`

The concept is very simple : create a copyright file in the app root, then adonis will check if it exists. If true, it will write the content in the top of generated file.

**Comment by RomainLanz** [comment]
Hey @Melchyore! 👋 

I don't believe we will add that to the framework.

**Comment by thetutlage** [comment]
Adding copyright or licenses in your code is not job of the framework. Simply create a personal `ace` command to do that
