### ISSUE TITLE
Question: what is the best way to know if app is running from command line?

### ISSUE THREAD

**Issue by anurbol** [adonisjs/adonis-framework#888]
What's the best approach?

I tried `process.title`: it's `node` when running from CLI, and `browser` when running from browser. But should I use this approach, or there is better/official way of doing this?

**Comment by RomainLanz** [comment]
Hey @anurbol! 👋 

It's in the doc ! https://adonisjs.com/docs/4.1/helpers#_isacecommand

**Comment by anurbol** [comment]
Wow! I missed that. Thank you :D
