### ISSUE TITLE
adonis does not install

### ISSUE THREAD

**Issue by arausly** [adonisjs/adonis-framework#892]
after installing adonis as specified in the docs 
npm install @adonisjs/cli

it installs successfully, but then i try running adonis --help it , and then it shows adonis command not found

I have tried this over and over again,

I have npm 4.6.1
node 8.10.0

**Comment by RomainLanz** [comment]
Hey @arausly! 👋 

1. You need to install the CLI globally or make use of `npx` to run the CLI.
2. If you aren't using `npx`, be sure to add the global `node_modules/.bin` directory to your PATH.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
