### ISSUE TITLE
JSX or VUEJS template engine

### ISSUE THREAD

**Issue by LucaGabi** [adonisjs/adonis-framework#896]
## Why this feature is required (specific use-cases will be appreciated)?
It is a clean way to write templates

## Have you tried any other work arounds?
there is a pug provider and while pug is great it uses weak delimiters for blocks and it is verry easy to break even by adding or deleting a space  

## Are you willing to work on it with little guidance?
Yes

**Comment by RomainLanz** [comment]
Hey @LucaGabi ! 👋 

I believe you completely missed the point of Adonis.
AdonisJS is a backend framework and it doesn't care about which technologies you use for your frontend. Internally we use the template engine `edge.js` to generate the view in the server side.

Nothing keeps you from using VueJS (or whatever frontend framework you like) with or without JSX in your frontend.

**Comment by LucaGabi** [comment]
Hi,

   Maybe I was not clear enough my goal is to use markojs to render my vews. It supports server side rendering.

Thanks.

**Comment by RomainLanz** [comment]
Still has nothing to do with Adonis.
You are talking about a frontend templating engine.

Closing since not actionable.
