### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by protzi** [adonisjs/adonis-framework#897]
## Prerequisites
Run adonijs app and redis with docker and can't connect
Can't connect to redis `[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379`

I have a question, why `@adonisjs/redis` receives such config with host `127.0.0.1` instead of `redis`
if i manualy hardcode host to `redis`, everything works as expected

## Package version
`  "version": "4.1.0"`
## Node.js and npm version
`9.4.0`

## Sample Code (to reproduce the issue)
// .env
`SESSION_DRIVER=redis`

![redis_config](https://user-images.githubusercontent.com/17887536/41816643-023cb7ba-7793-11e8-9a04-de54e6538c8d.png)
![docker_config](https://user-images.githubusercontent.com/17887536/41816644-0715d7c6-7793-11e8-9c2a-586a8a70950d.png)

**Comment by thetutlage** [comment]
Can you share `config/session.js` file?

**Comment by thetutlage** [comment]
The redis property here must be an object. `self::redis.local` is depreciated.

I have ideally removed it from all places, not sure if your project was created earlier

**Comment by protzi** [comment]
how it possible ? version 4.1.0, just created new app with adonis-cli and its the same config for session.

**Comment by thetutlage** [comment]
Closing since not actionable
