### ISSUE TITLE
Middleware error handling

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#898]
I have created a middleware, it is stated in your docs that it can throw error. 
Can you give me an example usage how to catch and  throw error inside middleware.

Thanks!

**Comment by thetutlage** [comment]
The way you throw error in an other part of your app.

```
throw new Error('')
```

**Comment by kingleuther** [comment]
@thetutlage, followup question, do you still support the sendView function? I cannot find any from the docs, are there any substitute for this? 

in my middleware i placed this 
`response.status(403).sendView('errors.403');`

**Comment by kingleuther** [comment]
done with this.
