### ISSUE TITLE
request.ajax() returns false even if it comes from ajax

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#899]
Here's my axios code

`        axios.post('/paktay', {
            headers: {
                'X-Requested-With': true
            }
        }).then((res)=>{
            console.log(res.data);
        });
    }`

**Comment by RomainLanz** [comment]
Hey @kingleuther! 👋 

Remove the header `X-Requested-With`, this is automatically set by `axios` and sound't be `true`.

Code https://github.com/poppinss/node-req/blob/develop/index.js#L366

**Comment by thetutlage** [comment]
You won't have to set `X-Requested-With`. If the request is from browser using `axios`, then it will set it for you.

Also I recommend using forum or the discord channel for confusions.

**Comment by kingleuther** [comment]
@thetutlage noted I will retry that.

**Comment by thetutlage** [comment]
Closing since not actionable
