### ISSUE TITLE
use socket on adonis

### ISSUE THREAD

**Issue by amirkheirabadi** [adonisjs/adonis-framework#9]
hi ...
how i can integrate socket.io with adonis...
can show me a very simple demo ...

**Comment by thetutlage** [comment]
Check out http://amanvirk.me/using-socket-io-with-adonis/

**Comment by amirkheirabadi** [comment]
perfecttttttttttttttttttttt

**Comment by amirkheirabadi** [comment]
thank you ... but i have problem with this ...
when i try to use my method provider in socket file give me error for use yield... while i put 'use strict'
```
Unexpected strict mode reserved word
```
plz help

**Comment by thetutlage** [comment]
check out how to use generators

**Comment by amirkheirabadi** [comment]
my socket.js

```
const server = use('http').createServer()
const io = use('socket.io')(server)
const ch = use('Challenge/Challenge')
console.log(yield ch.test())
io.on('connection', function(socket) {
	console.log('connection created >>>')
	socket.on('signup', function(data) {
		console.log(JSON.parse(data));
	})

})
io.listen(3000)
```

**Comment by thetutlage** [comment]
You cannot use `yield` without a generator method, make sure to wrap inside co

```
npm install co --save
```

```javascript

co (function * () {
  const values = yield ch.test()
  console.log(values)
})

```

**Comment by amirkheirabadi** [comment]
sorry i also put use strict on top of the socket.js but show me error Again
```
Unexpected strict mode reserved word
```

**Comment by thetutlage** [comment]
Are you wrapping your yield inside `co` generator method ?

**Comment by tinkone** [comment]
Based on the write-up for the socket io implementation, how would you then get a handle on the io in say a controller? I would like to do `io.emit('msg', 'test')` for example.

**Comment by tinkone** [comment]
Not sure if it's the best way to do it but what I figured doing is expose some methods for the socket server in `socket.js` and inject it into the controller to get a handle. Seems to work for me.

**Comment by AbdelilahLbardi** [comment]
The blog post shows that's easy to implement Socket with Adonis !
But i think that it will be better and awesome to make it as a service provider, so the usage will be simple like:

````javascript

class UserController {

    * login (request, response) {
        const email = request.input('email')
        const password = request.input('password')
        const login = yield request.auth.attempt(email, password)

        if (login) {
            response.send('Logged In Successfully')
            Socket.emit('new_user_connected', {message: 'new user is connected'})
            return
        }

        response.unauthorized('Invalid credentails')
    }

}
````

**Comment by thetutlage** [comment]
@AbdelilahLbardi It has to be more than wrapping socket.io inside a service provider. The official provider will have a friendly API to make use of websockets around the real world scenarios.

You will have to wait for that for a while 😄

**Comment by AbdelilahLbardi** [comment]
@thetutlage alright! Go ahead boss :+1:

**Comment by zainul-realtime** [comment]
@AbdelilahLbardi nice info mate , it will be nice again if @AbdelilahLbardi  write the full example or tutorial about socket wrapping inside a service provider ..

Thanks

**Comment by RomainLanz** [comment]
You may have a look of https://github.com/adonisjs/adonis-websocket

**Comment by zainul-realtime** [comment]
@RomainLanz Thank you brother

**Comment by kunaldodiya** [comment]
adonis 4 with socket.io implemented successfully and socket.js also console.log() new messages from client but than I have to handle everything from this socket.js file, how can i pass this socket instance into any controller say UserController so that i can emit message from controller ???
