### ISSUE TITLE
Override or disregard Handler.js

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#901]
Hi @thetutlage,

I would like to ask do we have any way how to disregard the global exceptionhandler ? 

Example:
I am currently working locally I want to see the errors sent by adonisjs, I want to disregard the  ExceptionHandler (ehandler).

Can we do this?

**Comment by thetutlage** [comment]
You want to disregard in development or disregard it completely?

**Comment by kingleuther** [comment]
@thetutlage I want to disregard in development.

**Comment by thetutlage** [comment]
Simply call `super.handle` inside your `handle` method.

```js
async handle (error, { response }) {
  if (process.env.NODE_ENV === 'development') {
    return super.handle(...arguments)
  }

  // handle in production
}
```

**Comment by kingleuther** [comment]
@thetutlage  thanks you!
