### ISSUE TITLE
error running "adonis serve -dev"

### ISSUE THREAD

**Issue by agung96tm** [adonisjs/adonis-framework#902]
when i run "adonis serve -dev" in mac, the error. How to fix it?

![screen shot 2018-06-27 at 11 45 00](https://user-images.githubusercontent.com/1901484/41953750-ddeac5ba-79c6-11e8-8b62-f8bda7a43b48.png)

## Package version
4.1.0

## Node.js and npm version
Node Version : v8.11.1
NPM Version : 6.0.0

## Sample Code (to reproduce the issue)
none

## BONUS (a sample repo to reproduce the issue)
none

**Comment by thetutlage** [comment]
Request you to share complete information. All of the following info is missing.

<img width="638" alt="screen shot 2018-06-27 at 10 46 43 am" src="https://user-images.githubusercontent.com/1706381/41954156-6c62047c-79f7-11e8-9b59-4b2574db5252.png">

**Comment by agung96tm** [comment]
the problem is solved after I re-install the adonis via npm, thanks: D
