### ISSUE TITLE
Lucid Model table name issue

### ISSUE THREAD

**Issue by rhnkyr** [adonisjs/adonis-framework#904]
I would lite to use my custom table name in Route Model but I wont get any data even though my table has data over 1K rows. I use mongo db. If I change the model name to KmlData, I get the data.

## Package version
"@adonisjs/framework": "^5.0.7",
    "@adonisjs/ignitor": "^2.0.6",
    "@adonisjs/lucid": "^5.0.4",
    "lucid-mongo": "^3.1.0",

## Node.js and npm version
Node : v9.4.0  NPM : 5.6.0

## Sample Code (to reproduce the issue)
```
'use strict'

const Model = use('Model')

class Route extends Model {

    static get table() {
        return 'kml_data'
    }

}

module.exports = Route
```

**Comment by thetutlage** [comment]
Hello @rhnkyr 👋 

`lucid-mongo` is not an official package and you must create an issue with the package author.
