### ISSUE TITLE
Adonis commands doesn't terminate if I use socket.io-redis library

### ISSUE THREAD

**Issue by rvashchenko** [adonisjs/adonis-framework#905]
When I use this construction in start/socket.js,

```
const redis = require('socket.io-redis');
const io = use('socket.io')(Server.getInstance(), options);
io.adapter(redis({ host: redisData.host, port: redisData.port }));
```

part of adonis commands (e.g. adonis migration:run) doesn't terminate after execution, but if I start tests with migrations this problem doesn't occur.

**Comment by thetutlage** [comment]
Because connection to redis is persistent and hence you will have to it.

**Comment by rvashchenko** [comment]
@thetutlage I tried to do it, but I could not. Could You help me with this?

**Comment by thetutlage** [comment]
Can you share the code for the command?

**Comment by rvashchenko** [comment]
@thetutlage Yes, I tried to do something like this in start/hooks.js

```
const { hooks } = require('@adonisjs/ignitor');

hooks.before.aceCommand(async () => {
    const Redis = use('Redis');

    await Redis.quit();
});
```

**Comment by thetutlage** [comment]
You are using socket.io redis library and hence you have to terminate connection using that and not the redis library shipped by Adonis.

**Comment by rvashchenko** [comment]
I agree, but that library does not have methods for closing the connection, I asked the developers of the library, but I still have not received a response.

**Comment by thetutlage** [comment]
Why you are connecting to socketio when running ace command?

**Comment by rvashchenko** [comment]
I added socket.io-redis to start/socket.js, because I use multiple node.js, how to do it I looked [here](https://socket.io/docs/using-multiple-nodes/#passing-events-between-nodes)

**Comment by thetutlage** [comment]
Can you share the contents of `start/socket.js` file?

**Comment by rvashchenko** [comment]
Yes

```
const AuthController = make('App/Controllers/Ws/AuthController');
const SmsController = make('App/Controllers/Ws/SmsController');
const Event = use('Event');
const Server = use('Server');
const Config = use('Config');
const redis = require('socket.io-redis');

const options = {
    pingTimeout: 2000,
    pingInterval: 2000
};

const io = use('socket.io')(Server.getInstance(), options);

let redisData = Config.get('redis');
redisData = redisData[redisData.connection];

io.adapter(redis({ host: redisData.host, port: redisData.port }));

io.sockets.setMaxListeners(0);
Event.setMaxListeners(0);

io.on('connection', (socket) => {
    socket.setMaxListeners(0);

    socket.on('login', (data) => {
        AuthController.login(socket, data);
    });

    socket.on('smsConfirm', (data, callback) => {
        SmsController.smsConfirm(socket, data, callback);
    });
});
```

**Comment by thetutlage** [comment]
I suggest moving all this inside the `aceCommand` check to make sure it doesn't get executed when running the ace command.


```js
const Helpers = use('Helpers')

if (!Helpers.isAceCommand()) {
  // your code
}
```

Docs on same https://adonisjs.com/docs/4.1/helpers#_isacecommand

**Comment by rvashchenko** [comment]
Great, thanks it works
