### ISSUE TITLE
Connect to external database

### ISSUE THREAD

**Issue by jbrhinalyn** [adonisjs/adonis-framework#908]
I have my database on another server (209.97.163.71).
When I access my application which is on another server, it give a Access denied and the IP is not on the database server IP. It pointing on the application IP Address (159.65.15.220).

See attachment for reference.
_(From **RomainLanz**, removed your picture seems we could saw part of your password, I recommend you to change it ASAP)_

**Comment by jbrhinalyn** [comment]
On version 3.2, its working. but on version 4.1, that's the error.

**Comment by thetutlage** [comment]
Because you are passing the domain, which resolves to the public ip and not the private ip. Mind changing the domain with `209.97.163.71`.

**Comment by jbrhinalyn** [comment]
Hi @thetutlage 

I change the it both on the .env and config/database.js file.
Its still the same.
![screenshot_2](https://user-images.githubusercontent.com/14085295/42084226-aa434002-7bbf-11e8-85b8-5fb787a620d2.png)

**Comment by jbrhinalyn** [comment]
Hi @thetutlage 

It's now working. The main cause of the error is the special characters i had in the password.
Similar issue to this one - https://forum.adonisjs.com/t/connect-to-a-external-db-rds-amazon/1279

**Comment by jbrhinalyn** [comment]
Closing now the issue.

**Comment by thetutlage** [comment]
Ahhh! Thanks for sharing the resolution
