### ISSUE TITLE
How to load Adonis from an external app?

### ISSUE THREAD

**Issue by spazer5** [adonisjs/adonis-framework#909]
I'm trying to use [Bull](https://github.com/OptimalBits/bull) but there doesn't seem to be any active adonis plugin for it. (Kue doesn't have all features i want).

How can I access the adonis app and `use()` from within a bull script?

**Comment by BatuhanK** [comment]
You can create custom provider: https://adonisjs.com/docs/4.1/extending-adonisjs#_extending_providers

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
