### ISSUE TITLE
cant install adonijs on mac

### ISSUE THREAD

**Issue by Imammalik234** [adonisjs/adonis-framework#911]
## Note

You choose to create an issue, which is not a bug and neither a feature request. We recommend using [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs) for same.

Continue, if you think that your issue needs to be on Github.

*Delete the above section before submitting*

**Comment by RomainLanz** [comment]
Closing since there's no information at all.
Feel free to create a new one if needed.
