### ISSUE TITLE
SET foreign_key_checks not supported? 

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#912]
`class AlterOrganizationRolePermissionSchema extends Schema {
    up () {
        Database.raw('SET foreign_key_checks = 1;')
        this.table('organization_role_permissions', (table) => {
        table.dropUnique('organization_role_id')
        table.dropUnique('permission_code')
        table.unique(['organization_role_id', 'permission_code'], 'unique_org_role_permission_col')
        })

    }`

Do you support this ? or how to set foreign key checks?

**Comment by thetutlage** [comment]
Please read https://knexjs.org/#Schema-raw

Also please format your code properly to make it readable :). Do consider using forums and discord server for questions
