### ISSUE TITLE
Using static method while querying relationships breaks the relationship constraint

### ISSUE THREAD

**Issue by mathieuh** [adonisjs/adonis-framework#914]
Hi,  about  https://adonisjs.com/docs/4.1/relationships#_querying_data, it seems that using the static method (https://adonisjs.com/docs/4.1/lucid#_static_methods) instead of ``fetch()`` breaks the constraint, for example:
```const posts = await user.posts().fetch()```
 would return user's posts while: 
```const posts = await user.posts().ids()```
 would return an array of all posts ids, not only the ones belonging to ``user``.

## Package version
"adonis-version": "4.1.0",
"@adonisjs/lucid": "^5.0.3",

## Node.js and npm version
v8.0.0
6.1.0

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-lucid#358
