### ISSUE TITLE
can i use neo4j with adonis framework?

### ISSUE THREAD

**Issue by AhsanAbrar** [adonisjs/adonis-framework#917]
i just saw your framework for node.js

i'm new to adonisjs

can i use neo4j with adonisjs, any guideline for it?

**Comment by thetutlage** [comment]
@AhsanAbrar Are you struggling to use it?

AdonisJs does have some first party modules for certain features. However, you are free to make use of any node module, just like you will do with any other Node.js application.

Neo4j does have a dedicated driver for Node.js https://neo4j.com/developer/javascript/, you can make use of it.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
