### ISSUE TITLE
Invalid Month error on table.timestamps() - Reposting 

### ISSUE THREAD

**Issue by malepatip** [adonisjs/adonis-framework#918]
Hello, I am [reposting ](https://forum.adonisjs.com/t/invalid-month-error-on-table-timestamps/1486)this question as i dont see much views on my question on forum.adonisjs.com
I am using Oracle database for posting data from HTML Page.
All my models, migrations, views, are defaults to Adonis 4.1 documentation, not customized anything.

Migration:

```js
up () {
    this.create('ois', (table) => {
      table.increments()
      table.string('proj_name').notNullable()  
      table.timestamps()
    })
  }
```

Model:

```js
'use strict'
const Model = use('Model')

class Oi extends Model {
}

module.exports = Oi
```

Controller:

```js
async store({ request, response, session }){
     //persist to database
    const oi = new Oi()
    oi.proj_name = request.input('Projname')
    await oi.save()
    return response.redirect('/oi')
```

I get this error, after filling the form:

Error

```
insert into “ois” (“created_at”, “proj_name”, “updated_at”) values (:1, :2, :3) returning “id” into :4 - ORA-01843: not a valid month
```

Database Table Structure:
![capture3](https://user-images.githubusercontent.com/3514731/43086722-a7d58a3a-8e63-11e8-84d8-21edfb44a3d3.PNG)

**Comment by thetutlage** [comment]
What happens if you change the precision of timestamps to `4`. `table.timestamps(4)`?

**Comment by malepatip** [comment]
I treid that, throwing same error, but I was able get through .insert function, here is the code:

```
async store({request, response}) {
    await Database
    .insert({
        created_at: Database.raw("CURRENT_TIMESTAMP"),
        proj_name: request.input('proj_name'), 
        updated_at: Database.raw("CURRENT_TIMESTAMP")
    })
    .into ('ois')
    return response.redirect('/oi')    
}
```

**Comment by thetutlage** [comment]
So you are using the Database query builder directly and not Lucid models?

Also can you share the version of `@adonisjs/lucid` in your package.json file

**Comment by thetutlage** [comment]
Can you upgrade to the most recent version of Lucid, which is `6.0.x` and lemme if problem persists. 

I don't deal with oracle everyday, but if problem still persists, I will try it manually on Oracle and see what's causing this

**Comment by malepatip** [comment]
Ok, Not sure if it did the update on lucid to 6.0.x to correctly, this is what I see in my package.json:

 "@adonisjs/lucid": "git+https://github.com/adonisjs/adonis-lucid.git",

After installing the latest lucid (which I am thinking), I still get the same error "Invalid Month"

**Comment by thetutlage** [comment]
Okay, gonna try it myself with the actual oracle server

**Comment by ujjwal-kr** [comment]
someone look at #1058
