### ISSUE TITLE
How to prevent default html reponse on api only project errors?

### ISSUE THREAD

**Issue by marceloHashzen** [adonisjs/adonis-framework#919]
I'm starting an api only project with adonis, but every error returns as html content instead of json. For example, when a route is protected with the auth middleware and the token isn't passed, it returns the `InvalidJwtToken` error html page.

How can I prevent this behavior and return just json or avoid the default validation and check on my own to return json?

**Comment by thetutlage** [comment]
AdonisJs in built error handling respects the `content negotiation` headers like `Accept`.

If you will set the `Accept: application/json` header, then all error output will be in JSON over HTML.

Another thing you can do is create a global middleware, which set this header for you, this way your clients won't have to set the header explicitly.

Sample code for the middleware


```js
class SpoofAccept {
  async handle ({ request }, next) {
    request.request.headers['accept'] = 'application/json'
    await next()
  }
}

module.exports = SpoofAccept
```

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by rsorage** [comment]
It did not solve the issue for me.
