### ISSUE TITLE
I have an issue with .belongsTo relationship

### ISSUE THREAD

**Issue by dguzman1012** [adonisjs/adonis-framework#920]
## Package version
4.1

## Node.js and npm version
- Nodejs: v8.11.3
- npm: 5.6.0

## Description
Hello There, this is really weird!!

I have two(2) models Message and User.

In Message model I have created a basic .belongsTo relationship with the User model. 

![captura de pantalla de 2018-07-27 18-06-15](https://user-images.githubusercontent.com/5767551/43347265-0adaa0c4-91cb-11e8-94b6-27dd13165649.png)

However, I am unable to get the sender(User) from any message.

![captura de pantalla de 2018-07-27 18-07-45](https://user-images.githubusercontent.com/5767551/43347272-12021aee-91cb-11e8-8459-52aae9f556c1.png)

And this is the output:

![captura de pantalla de 2018-07-27 18-08-45](https://user-images.githubusercontent.com/5767551/43347279-1919cd90-91cb-11e8-83a1-e30e1d2dc75c.png)

Does anyone have any idea???? It is really frustrating since, I have been working from a while with Adonis and it never happened before.

I have even enabled the database debug and effectively it calls the query to user:
![captura de pantalla de 2018-07-27 18-11-40](https://user-images.githubusercontent.com/5767551/43347292-21337620-91cb-11e8-9f3b-4af659ca87df.png)

(I run this query into the DB and of course, it show me the user).

Any thought will be appreciated!

**Comment by thetutlage** [comment]
The `user_id` on the `message` row is a string. Make sure the `foreign_key` and `primary_key` data type is same

**Comment by dguzman1012** [comment]
Hi @thetutlage, thanks for take a minute to look into this case.

Actually the user_id filed is numeric type (bigint).

![captura de pantalla de 2018-07-29 03-39-11](https://user-images.githubusercontent.com/5767551/43363705-210e793a-92e1-11e8-84f4-19914c782cec.png)

However ,I don't know why the ORM is handle the user_id field like a string.

**Comment by thetutlage** [comment]
Is `id` in the `users` table also `bigint`.

Since Javascript natively doesn't have support for `bigints` all drivers will wrap them into a string. Adonis or Lucid doesn't have control over it.

Also can you share the database you are using?

**Comment by dguzman1012** [comment]
No, you are right! the `id` field of user tabla is a "serial" integer type.

So, changing the `user_id` from "bigint" to "integer" works:

![captura de pantalla de 2018-07-29 04-33-09](https://user-images.githubusercontent.com/5767551/43364045-c6e16fb4-92e8-11e8-955f-6da9d50dd0f6.png)

Thank you very much for clarify this @thetutlage. Actually I didn't know that "bigint" type wasn't recognized as integers by Javascript.
