### ISSUE TITLE
Add checking is .env file exists

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-framework#921]
Can you add checking is file '.env' exists before calling fs.readFileSync  in

https://github.com/adonisjs/adonis-framework/blob/2de3833fd082cfe6f464914f3dd2bea2fe5014b1/src/Env/index.js#L101

This because when i do **npm run test** in repository (with bitbucket pipeline) it crashes with error
 
Error: ENOENT: no such file or directory, open '...../.env'

1 Env.load
  .../node_modules/@adonisjs/framework/src/Env/index.js:101

.env file is not recommended to commit, and perhaps is not necessary, if you have environment variables in your cloud.

Now I must set variable **ENV_SILENT=true** for this

Thank you!

**Comment by thetutlage** [comment]
Without environment variables you will be running an unstable codebase. So it is mandatory to have `.env` file.

However many servers allows them to be configured via some admin interface, in that case u must tell Adonis to ignore the file using `ENV_SILENT`.

In short no change is required and this is the correct behaviour

**Comment by yariksav** [comment]
Thank you, @thetutlage
