### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by viniciusvelasco** [adonisjs/adonis-framework#922]
Sorry if I'm asking for help in the wrong place. Would anyone have a way to make deploy work? I've tried it on Azure, Heroku, Google Cloud, and none works. In Heroku the start occurs but at the first request the request drops for a R10 error of 60 seconds at the port. Bad Gateway 502 error occurs in Google Azure does not start Thanks if anyone can help me. The documentation does not contemplate deploy.

**Comment by thetutlage** [comment]
I suggest join the discord server http://discord.me/adonisframework. You may get some help regarding deployments there

**Comment by viniciusvelasco** [comment]
Thanks for the answer, I got it in Azure, the problem was that the version of the node installed in the Azure environment is 6.3 and need to send to the application folder the version that is being used in localhost
