### ISSUE TITLE
adonis make:migration users is not generate file.

### ISSUE THREAD

**Issue by Erchoc** [adonisjs/adonis-framework#924]
![image](https://user-images.githubusercontent.com/19908809/43810153-c4c248e0-9ae8-11e8-89c2-2f388a2443aa.png)

**Comment by RomainLanz** [comment]
Hey @Erchoc! 👋 

Could you run `which adonis` and also give us information about your system?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
