### ISSUE TITLE
QUESTION: make:migration

### ISSUE THREAD

**Issue by kingleuther** [adonisjs/adonis-framework#925]
Hi!,

I would like to ask where to find the file that contains the command make:migration.

My scenario is, im going to extend this, to support migration to certain path. Thanks!

**Comment by thetutlage** [comment]
Here it is https://github.com/adonisjs/adonis-cli/blob/develop/src/Commands/Make/Migration.js

Suggest to use Forums or discord channel for quick questions. Will help you in getting quick replies and helps us in focusing on main issues 😄

**Comment by kingleuther** [comment]
Ah.. i was looking at the node_modules of the framework haha
Anyway, is it located in the framework? what folder?

**Comment by rdunk** [comment]
The `adonis make:migration` command is executed using adonis-cli, the code it executes is part of that package rather than the adonis-framework package.
