### ISSUE TITLE
.wsServer is not a function

### ISSUE THREAD

**Issue by woodgates** [adonisjs/adonis-framework#928]
Hi.
I'm using adonis_nuxt frameork and I want to use websockes. I followed the instructions and I get this error message:

```
/home/jorge/Dropbox/www/adonis_nuxt/server.js:24
  .wsServer()  
   ^

TypeError: (intermediate value).appRoot(...).wsServer is not a function
    at Object.<anonymous> (/home/jorge/Dropbox/www/adonis_nuxt/server.js:24:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
Installed versions:

nodejs v8.11.3
npm 6.4.0

adonis_nuxt@1.0.0 /home/jorge/Dropbox/www/adonis_nuxt
├── @adonisjs/ace@4.0.8
├── @adonisjs/auth@2.0.11
├── @adonisjs/bodyparser@1.0.8
├── @adonisjs/cors@1.0.6
├── @adonisjs/fold@4.0.9
├── @adonisjs/framework@4.0.31
├── @adonisjs/ignitor@1.0.14
├── @adonisjs/lucid@4.1.3
├── @adonisjs/session@1.0.26
├── @adonisjs/shield@1.0.7
├── @adonisjs/validator@5.0.3
├── @adonisjs/websocket@1.0.11
├── @nuxtjs/axios@5.3.1
├── babel-eslint@8.2.6
├── cross-env@5.2.0
├── UNMET PEER DEPENDENCY eslint@5.4.0
├── eslint-loader@2.1.0
├── eslint-plugin-vue@4.7.1
├── mysql@2.16.0
├── mysql2@1.6.1
├── nodemon@1.18.3
├── nuxt@1.4.2
├── portal-vue@1.3.0
├── stylus@0.54.5
├── stylus-loader@3.0.2
├── vee-validate@2.1.0-beta.8
├── vue-gallery@1.4.0
└── vuetify@1.1.13

**Comment by thetutlage** [comment]
Can you share the actual code for the `server.js` file and also have u registered the provider?

**Comment by woodgates** [comment]
@thetutlage 
Hi.

I attached the server.js

Here are my providers in app.js

const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/framework/providers/ViewProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/shield/providers/ShieldProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/auth/providers/AuthProvider',
  '@adonisjs/validator/providers/ValidatorProvider',
  '@adonisjs/websocket/providers/WsProvider'
]

[server.js.txt](https://github.com/adonisjs/adonis-framework/files/2302619/server.js.txt)

**Comment by thetutlage** [comment]
Hey, your dependencies seems to be quite old. The support for `wsServer` was added in `@adonisjs/ignitor@2.x.x`. Mind updating to the latest version?

**Comment by woodgates** [comment]
@thetutlage 
Hi.

I updated all the adonis packages and I got no error messages. Thanks!

I attached the server.js

Here are my providers in app.js

const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/framework/providers/ViewProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/shield/providers/ShieldProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/auth/providers/AuthProvider',
  '@adonisjs/validator/providers/ValidatorProvider',
  '@adonisjs/websocket/providers/WsProvider'
]

[server.js.txt](https://github.com/adonisjs/adonis-framework/files/2302619/server.js.txt)
