### ISSUE TITLE
Create Model name that contains 'Model' . Ex: CarModel

### ISSUE THREAD

**Issue by FilippiSilva** [adonisjs/adonis-framework#931]
## Package version
4.1.0

## Node.js and npm version
v8.9.0 and 6.0.0

## Sample Code (to reproduce the issue)
adonis make:model CarMake -m -c
adonis make:model CarModel -m -c

queries to the faulted database, querying another table. Queries to the model CarModel, are made in the table 'car_makes'

**Comment by RomainLanz** [comment]
Hey @FilippiSilva! 👋 

The command `adonis make:model CarModel` will automatically shrink the suffix `Model`, if you need it I recommend you to add it again to your filename and class name.

Adonis will then use your class name to define the name of your table, this is probably why it's not querying the correct table.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
