### ISSUE TITLE
where can I find complete documentation of socket io with Adonis ?

### ISSUE THREAD

**Issue by antojsh** [adonisjs/adonis-framework#936]
## Socket io with Adonis

I am developing an API and I have the need to implement socket.io services but I can not find a clear documentation of how to do it

*I appreciate your collaboration*

**Comment by thetutlage** [comment]
AdonisJs has it's own Websocket implementation, so very first question is, why not use that?

Also you have to read `socket.io` docs, if you plan to use it.

**Comment by thetutlage** [comment]
Closing since not actionable
