### ISSUE TITLE
events.js throw error after new install on Windows

### ISSUE THREAD

**Issue by garciamarco33** [adonisjs/adonis-framework#938]
## Package version
4.1.0

## Node.js and npm version
Node.js =>8.11.4
npm => 6.4.1

## Issue
Hello,
I just made a new install of my project on Windows and when I start :
`adonis serve --dev`

I get an error after a few second :
```
events.js:183
     throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'C:\Users\my\repository\tmp\adonis.log'
```
"'C:\Users\my\repository\tmp\adonis.log" doesn't exist.
I tried to remove node_modules and reinstall it doesn't work.
I tried to change port and it doesn't work.

Do you know what the problem is please ?

**Comment by thetutlage** [comment]
I believe you are using the `file` driver of the logger. Simply create the `tmp` directory inside your project root and it should be good

**Comment by garciamarco33** [comment]
It doesn't work even with this folder :/
