### ISSUE TITLE
configurable migrations, seeds, views directories paths

### ISSUE THREAD

**Issue by osman-mohamad** [adonisjs/adonis-framework#941]
## Why this feature is required (specific use-cases will be appreciated)?
easily plug-able application modules
## Have you tried any other work arounds?
I tried to setup modules seeds in sub directories . but it didn't work
## Are you willing to work on it with little guidance?
yes

**Comment by thetutlage** [comment]
I don't see where this addition will help. Can you please share some use cases where changing the directory path to something else if really helpful?

**Comment by thetutlage** [comment]
Yeah but that removes the transparency in which order the migrations will be executed? Also what if I want to change their order?

**Comment by thetutlage** [comment]
I am not sure what all issues are faced by the users of these packages and what work-around Laravel community has found around that.

To make it more accessible, I would better have a file, where you can require migrations from anywhere and decide the order.

```js
module.exports = [
  './migrations/something.js',
  'some_module/migrations/migration.js'
]
```

> That would be awesome if we could also create sub-app in the Adonis ecosystem
Yeah I have plans for something like this

**Comment by PazzaVlad** [comment]
Views directories paths will useful feature, especially for large projects imho.

**Comment by thetutlage** [comment]
Large products is subjective, having a way to club multiple sub-apps to make a larger app is helpful but that is way beyond just views or migrations.

As I said earlier, I have plans to add support for sub-apps. So closing this for now :)

**Comment by osman-mohamad** [comment]
> I don't see where this addition will help. Can you please share some use cases where changing the directory path to something else if really helpful?
sub applications , packages for example users permissions package, ... etc
---
any chance we can help to speed up this `sub-apps plan` ?
---
>Yeah but that removes the transparency in which order the migrations will be executed? Also what if I want to change their order?
migrations for the first time can be run based on the directory order in the config file . then it is based on  migrations table information .
---
> Large products is subjective, having a way to club multiple sub-apps to make a larger app is helpful but that is way beyond just views or migrations.
controllers can be called from any where if they used from the routes file . which can be imported from the packages if needed .
