### ISSUE TITLE
CastDates and FormatDates not Working

### ISSUE THREAD

**Issue by agusm** [adonisjs/adonis-framework#943]
```
static formatDates(field, value) {
    console.log('field')
    if (field === 'dob') {
      return value.format('YYYY-MM-DD')
    }
    return super.formatDates(field, value)
  }

  static castDates(field, value) {
    console.log('display field')
    if (field === 'dob') {
      return value.format('YYYY-MM-DD')
    }
    return super.castDates(field, value)
  }
```
code above not working to format date.
I get result with TImezone format, but my data type is date, not datetime.
so how to display date with format YYYY-MM-DD

**Comment by thetutlage** [comment]
Please format the issue properly. You can learn more about markdown [here](https://guides.github.com/features/mastering-markdown/)

**Comment by agusm** [comment]
ok, i have edited that.

please return only date without time and timezone, because I just need date, not datetime + timezone format.

**Comment by RomainLanz** [comment]
You need to use a `moment` (or any others date library) in the method `formatDates()`.

Also be sure to setup the `dates` getter.

```js
static get dates () {
  return super.dates.concat(['dob'])
}
```

**Comment by agusm** [comment]
ok thank you
