### ISSUE TITLE
Upload the .PSD file, after subtype processing: .vnd.adobe.photoshop

### ISSUE THREAD

**Issue by liseipi** [adonisjs/adonis-framework#946]
Upload the .PSD file, after subtype processing: .vnd.adobe.photoshop

**Comment by thetutlage** [comment]
You can get the extension using `file.extname`

**Comment by liseipi** [comment]
Yes, I am like this: ${file.clientName.replace(/^.+\./,'')
but, when types: ['image'], when upload .psd, there is no error.
