### ISSUE TITLE
The app doesn't listen to IOS socket.

### ISSUE THREAD

**Issue by apatche7** [adonisjs/adonis-framework#947]
noticed the project is working fine with Android and Web not IOS.

I tried to solve the problem but nothing work.

I tried the IOS app with a node.js code and it's working fine but not with Adonis

I'm using Adonis version 3.2.1

This is my codes.

Ws.channel('/chat', 'ChatController').middleware('auth:jwt')

* onTest (data) { console.log('test socket', data); }

IOS code: sample test app

var socket = SocketIOClient(socketURL: URL(string: "http://45.76.159.126:8080/chat?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVpZCI6MjYxfSwiaWF0IjoxNTM2NTgwNDQ3fQ.9eLKoX7eEd9OkHTpiyE0pOZPF-mRBr5MNQuF8mdWVW8")!, config: [.log(false), .forcePolling(true)])

override init() { super.init() socket.on("test") { dataArray, ack in print("dataArray 1") print(dataArray) print("dataArray 2") }

**Comment by RomainLanz** [comment]
Duplicates : https://github.com/adonisjs/adonis-websocket/issues/66

**Comment by apatche7** [comment]
You did close it and no one response :(
