### ISSUE TITLE
Sanitize parameters of GET requests

### ISSUE THREAD

**Issue by Ali-Azmoud** [adonisjs/adonis-framework#948]
Hey
I am going to validate and sanitize parameters of the `GET` requests and Im using below script to do it,

```
class GetProduct {

    get rules () {
        return {
            id: 'required|existsInShop:products,id',
        }
    }

    get sanitizationRules () {
        return {
            id: `to_int`,
        }
    }

    get data () {
        const requestBody = this.ctx.request.params
        // const requestBody = { ...this.ctx.request.params, ...this.ctx.request.all() }
        // const sessionId = this.ctx.request.header('X-Session-Id')

        return Object.assign({}, requestBody, {})
    }

    async fails (errorMessages) {
        return this.ctx.response.send(errorMessages)
    }

}
```
however, by using this script, `sanitization` does not work.
Inside my controller when I log `typeof request.params.id`  or `typeof params.id` , it returns `string` which should be `number`

I have to mention that this only happens in `get` requests. ( parameters in route url )

any help

**Comment by Ali-Azmoud** [comment]
So how can I have access to params ?
I'm a bit confused. [In the documentations](https://adonisjs.com/docs/4.1/validator#_custom_data_object) at line 9, it gets all inputs from a post method ( I think ) but as I said I want to have access to params of the `GET URL` and those params are not inside `this.ctx.request.all()`. therefor I decided to use params as the request body.

Actually... I don't know what I am doing ! I just want to validate and sanitize `GET` params.
What's the best way to do that?

**Comment by thetutlage** [comment]
Do u know what are `params`? How do define them in the URL?

**Comment by Ali-Azmoud** [comment]
Yeah , route params.

    /product/:id

You know, I've already done sanitizing inside my controllers but I don't want to do these kind of actions inside controllers

**Comment by thetutlage** [comment]
I believe the only sanitization you need to do is `Number(params.id)`. I don't why that is a big deal?

**Comment by Ali-Azmoud** [comment]
No, I only expected to get the sanitized data. I don't know why `GET` params can not be sanitized inside `App\Validators` but maybe there's a reason behind it ...

**Comment by thetutlage** [comment]
The params are already sanitised. You are talking about route params.

`Query params != Route params`
