### ISSUE TITLE
Make HTTP request with Adonis

### ISSUE THREAD

**Issue by kazzkiq** [adonisjs/adonis-framework#95]
I have a project where one of its Controller's must make a HTTP request before returning the view with some data.

I could probably use a module such as [Request](https://www.npmjs.com/package/request), but I just wanted to know if Adonis have a specific API for this kind of requests.

Hypothetical sample code:

```js
const Request = use('Request'); // Adonis request method

class MyController {
    
    * index (request, response) {
        Request.get('http://some-url-here/jsonp').then((result) => {
          
            // do something with the value
            response.send(view, JSON.parse(result));
        });
    }

}
```

Is there something like that already baked into Adonis or I just should use an external package?

**Comment by thetutlage** [comment]
No there is official module for that, so you are free to use anything. And since controller methods are generators you can yield promises.

```javascript
const result = yield Request.get('http://some-url-here/jsonp')
response.send(JSON.parse(result))
```

**Comment by nwashangai** [comment]
#95 
`const result = yield Request.get('http://some-url-here/jsonp')
response.send(JSON.parse(result))`

please this didn't help me, maybe i didn't understand
am using the latest version, do i need to use any already preinstalled module to be able to use the above?
sometthing like this

`const Request = use('Request')`

hope you understand thanks

**Comment by webdevian** [comment]
Are you using adonis v3 or v4? This won't work in 4

**Comment by nwashangai** [comment]
@webdevian am using v4, please how do I solve this problem if this doesn't work

**Comment by webdevian** [comment]
```js
const Request = use('Request')

const response = await Request.get('http://some-url-here/jsonp')

console.log(response)

```

**Comment by nwashangai** [comment]
@webdevian thanks but i tried that earlier and i got error showing missing stack frame at this line 

`const Request = use('Request')`

**Comment by nwashangai** [comment]
@webdevian this is my controller 

`'use strict'
const PayDirect = use('App/Models/PayDirect')
const Branch = use('App/Models/Branch')
const Request = use('Request')

class PayDirectController {
    async getPayment({ request, response }) {
        const param = request.get()
        const query = await PayDirect.getPayment(param)
        let i = 0, data = []
        for (let value of query.data[0]) {
            i = i + 1
            const fetch = await Branch.query().where('id', value.branch).first()
            data.push({
                id: i,
                pid: value.id,
                amount: value.amount,
                sender: value.sender,
                staff: value.staff,
                branch: {
                    bid: value.branch,
                    branch: fetch.branchName
                },
                phone: value.phone,
                date: value.created_at,
                update_at: value.update_at
            })
        }
        response.json({ items: data, total: query.total[0][0].counts })
    }

    async setPayment({ request, response }) {
        const post = request.post()
        try {
            const deposit = PayDirect.create({
                sender: post.sender,
                amount: post.amount,
                branch: post.branch,
                staff: post.staff,
                token: this.makeToken(),
                phone: post.phone
            })
        } catch (e) {
            response.json({ err: e })
        }
        /*response.json({
            deposit: 'success'
        })*/
    }

    async test({ request, response }) {
        const res = await Request.get('http://localhost/api/get.php')
        response.json(res)
    }

    makeToken() {
      let text = "";
      let possible = "0123456789";

      for (let i = 0; i <= 5; i++)
        text += possible.charAt(Math.floor(Math.random() * possible.length));

      return text;
    }

}

module.exports = PayDirectController
`

**Comment by RomainLanz** [comment]
@nwashangai Please, create another issue instead of jumping into this one (even if it's closed).

Also, there's no official module for that. You must install a dependency to do HTTP, like `request`, `axios` or `got`.
