### ISSUE TITLE
Add support for DigitalOcean Spaces s3

### ISSUE THREAD

**Issue by clayderson** [adonisjs/adonis-framework#950]
DigitalOcean offers a service called "spaces" that is nothing more than a resale of the famous AWS S3. AdonisJS would probably support DigitalOcean spaces if it were not for a preconfigured URL

Example of s3 endpoint provided by DigitalOcean

```
Endpoint: nyc3.digitaloceanspaces.com
Bucket: ms2
Access key: ---
Secret access key: ---
```

When I try to use the service, I have this return

```
https://s3.nyc3.digitaloceanspaces.com.amazonaws.com/ms2/official/css/store.css
```

Is it possible to leave this generic configuration entry so that it can accept this service?

**Comment by clayderson** [comment]
Done.

https://github.com/adonisjs/docs/pull/294
https://github.com/adonisjs/adonis-drive/pull/14

**Comment by jbrhinalyn** [comment]
@clayderson do you have sample for ACL? it seems DO spaces default is private and need to setup it as public. thanks.
