### ISSUE TITLE
Edge in conflict with JS backticks

### ISSUE THREAD

**Issue by clayderson** [adonisjs/adonis-framework#951]
If I try to use the backticks, an error message appears when I try to access the page

Example

```
player.attr('src', `https://example.com/renders/body/${data.uuid}?scale=4`)
```

![captura de tela 2018-09-18 23 08 39](https://user-images.githubusercontent.com/15388584/45726903-cb4bd300-bb97-11e8-869d-7a1ede9cbb2e.png)

**Comment by thetutlage** [comment]
This issue was moved to poppinss/edge#56
