### ISSUE TITLE
The SQL injection?

### ISSUE THREAD

**Issue by vinnie0921** [adonisjs/adonis-framework#952]
## Package version
adonis 4.1.0

## Node.js and npm version
Node.js version: 10.8.0
npm version: 6.4.0

## Sample Code (to reproduce the issue)

```
const User = use('App/Models/User')

class UserSeeder {
  async run () {
    let text = '{"upgrade_order": ["bios", "ec", "mcu"]}';
    let info = JSON.parse(text);
    console.log(info.upgrade_order);
    const user = new User();
    user.username = 'test';
    user.password = 'password';
    user.email = info.upgrade_order;
    await user.save();
  }
}
module.exports = UserSeeder
```

output:

```
code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlMessage: 'Column count doesn\'t match value count at row 1',
  sqlState: '21S01',
  index: 0,
  sql:
   'insert into `users` (`created_at`, `email`, `password`, `updated_at`, `username`) values (\'2018-09-19 10:11:21\', \'bios\', \'ec\', \'mcu\', \'$2a$10$27GvPqcOqyyZhDD.JNArxu5tqnnjvdzumD6uxTzPUHHxqF75GlzWe\', \'2018-09-19 10:11:21\', \'test\')' }

```

**Comment by RomainLanz** [comment]
Hey @vinnie0921! 👋 

This isn't SQL Injection, you are simply trying to save an `Array` in a `String` field. Therefore, coercion is used and your `Array` is joined using `,`.

It's a normal behaviour. If you want to avoid this simply run validation over your field.

Please, if you believe this could be used to inject SQL queries provide a proper example.

**Comment by thetutlage** [comment]
This is not SQL injection at all. You are converting the user data string to a Javascript data type, which is the dangerous thing to do in it’s own.

Database are not meant to accept language specific arrays and objects
