### ISSUE TITLE
Websocket scalability

### ISSUE THREAD

**Issue by ed-fruty** [adonisjs/adonis-framework#955]
From the docs I read this:

> The websocket server scales naturally on Node.js cluster without any 3rd party dependencies like Redis. Also there is no need of sticky sessions.

It's pretty cool (I can suggest it handles by master process) but, it's only scalability on the **one machine**.

How it can be scale for **several servers** ?
If one connection will serve by one node, and the second connection in another node. So we can't send message from first node socket to another node sockets, isn't it?

Can we resolve this with adonis ?

I mean schema something like [this](https://cdn-images-1.medium.com/max/800/1*ryiL00dESNJTL_jRnUyAyA.png)

With socket.io it's just makes through **redis adapter**.

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-websocket#67
