### ISSUE TITLE
Recovering a video file stored on mongo gridfs and downloading by stream

### ISSUE THREAD

**Issue by mittaus** [adonisjs/adonis-framework#956]
Using adonis 4.1 I'm trying recovering a video file stored on mongo gridfs and downloading by stream on demand of the user

the video is stored in mongo gridfs in multiple documents as seen below:

chunks._id      | chunks.n | size chunk.data (in KB)
`- - - - - - - - - - - - - - - - - - - - - -`
ObjectId("5ba3086c8cdf9e168256b8bd")  |    0     |     255
ObjectId("5ba3086c8cdf9e168256b8be")  |    1     |     255
ObjectId("5ba3086c8cdf9e168256b8bf")   |    2     |     255
ObjectId("5ba3086c8cdf9e168256b8c0")  |    3     |     255
ObjectId("5ba3086c8cdf9e168256b8c1")  |    4     |     255
ObjectId("5ba3086c8cdf9e168256b8c2")  |    5     |     255
ObjectId("5ba3086c8cdf9e168256b8c3")  |    6     |     255
ObjectId("5ba3086c8cdf9e168256b8c4")  |    7     |     255
ObjectId("5ba3086c8cdf9e168256b8c5")  |    8     |     255
ObjectId("5ba3086c8cdf9e168256b8c6")  |    9     |     255
ObjectId("5ba3086c8cdf9e168256b8c7")  |    10    |     255
ObjectId("5ba3086c8cdf9e168256b8c8")  |    11    |     255
ObjectId("5ba3086c8cdf9e168256b8c9")  |    12    |     255
ObjectId("5ba3086c8cdf9e168256b8ca")  |    13    |     255
ObjectId("5ba3086c8cdf9e168256b8cb")  |    14    |     255
ObjectId("5ba3086c8cdf9e168256b8cc")  |    15    |     255
ObjectId("5ba3086c8cdf9e168256b8cd")  |    16    |     255
ObjectId("5ba3086c8cdf9e168256b8ce")  |    17    |     255
ObjectId("5ba3086c8cdf9e168256b8cf")   |     18    |     255
ObjectId("5ba3086c8cdf9e168256b8d0")  |    19    |     205.041

My code is:

`async dbDownloadVideo({ request, response, params }) {

    response.implicitEnd = false
    const mongoClient = await Database.connect()

    let bucket = new mongodb.GridFSBucket(mongoClient, {
      bucketName: "videos"
    })

    const videoFile = await bucket.find({ _id: params.fileId }).toArray()
    let fileMetadata = null
    if (videoFile.length > 0) {
      fileMetadata = videoFile[0]
    }

    response.header("accept-ranges", "bytes");
    response.header("content-type", fileMetadata.contentType)

    let downloadStream = bucket.openDownloadStream(fileId)

     downloadStream.on("data", chunk => {
      //Error here only response first 255KB
       response.send(chunk)
     })

     downloadStream.on("error", () => {
       response.sendStatus(404)
     })

     downloadStream.on("end", () => {
       response.end()
    })
  
  }`

In Express framework event on.data response.write(chunk) work:

`downloadStream.on('data', (chunk) => {
    response.write(chunk)
  })`

In adonis what would be the equivalent to response.write ("data") of the Express framework. Since I understand that it only transfers the first 255KB because the HTTP connection ends

**Comment by RomainLanz** [comment]
Hey @mittaus! 👋 

Please read the documentation about how to make a response with callbacks.
https://adonisjs.com/docs/4.1/response#_i_need_callbacks

**Comment by mittaus** [comment]
Thankz @RomainLanz 

I found 2 solutions

```
// versión 1:
downloadStream.pipe(response.response)

downloadStream.on("error", () => {
  response.sendStatus(404)
})

downloadStream.on("end", () => {
  response.end()
})
```



```
//versión 2
let data = []
downloadStream.on("data", chunk => {
  data[data.length].push(chunk)
})

downloadStream.on("error", () => {
  response.sendStatus(404)
})

downloadStream.on("end", () => {
  let final = Buffer.concat(data)
  response.send(final)
})
```

**Comment by thetutlage** [comment]
Closing since not actionable
