### ISSUE TITLE
Can't use adonis commands

### ISSUE THREAD

**Issue by Amisoz** [adonisjs/adonis-framework#958]
Hi, i've deployed Adonis on Ubuntu 18.04, and when i try to use adonis command it do nothing 
![image](https://user-images.githubusercontent.com/23367423/45976376-e199d900-c046-11e8-8c73-3f1671ee2271.png)

And, when i only write Adonis, i can see the usage.
![image](https://user-images.githubusercontent.com/23367423/45976395-ea8aaa80-c046-11e8-8e73-defa0ccad7d4.png)

Thanks.

**Comment by thetutlage** [comment]
How did you installed the cli? And what's the output of `adonis --version`

**Comment by Amisoz** [comment]
Hi,

I installed cli by using ``npm i adonis-cli`` and my version is 2.1.9.

**Comment by thetutlage** [comment]
Suggest you to read the official documentation https://adonisjs.com/docs/4.1/installation#_cli_tool. Since the package you have installed is incorrect

**Comment by Amisoz** [comment]
Yeah, it's work.

Sorry and thanks :)
