### ISSUE TITLE
Implement Socket.io in Adonis 4.1 

### ISSUE THREAD

**Issue by nnil4cl** [adonisjs/adonis-framework#959]
How implement Socket.io in Adonis 4.1 ?

I could not find any sample that work correctly.

Thanks for your help.

**Comment by thetutlage** [comment]
Please make sure to read the guidelines before posting an issue.

The gh issues are not for general questions and same must be asked on the [forum](https://forum.adonisjs.com)

**Comment by nnil4cl** [comment]
https://forum.adonisjs.com/t/socket-io-in-adonis-4-1/1961
