### ISSUE TITLE
problems when access a model twice exactly the same time

### ISSUE THREAD

**Issue by rbartholomay** [adonisjs/adonis-framework#96]
Hi,

i use the node-scheduler inside an adonis app. I define my ServiceProvider like this:

```
const ServiceProvider = require('adonis-fold').ServiceProvider;

class ScheduleProvider extends ServiceProvider {

  * register () {

    this.app.bind('App/Schedule', function (app) {
      return require('node-schedule');
    })
  }
}

module.exports = ScheduleProvider;
```

All my jobs using co and starts with the same code block like this:

```
Schedule.scheduleJob('0 */5 7-21 * * 1-6', function () {

  // because yield must be at top-level we need co for wrapping
  co(function* () {

    // fetch the Credentials
    let sysLoginOptions = yield SysLogins.where('name', '=', 'MySystem').first().fetch();
    if (!sysLoginOptions.size()) {
      throw new Error('System credentials not available');
    }


    sysLoginOptions = sysLoginOptions.toJSON();
```

When two or more jobs start exactly the same time  i get the following error:

`
[Error: System credentials not available] 'Error: System credentials not available\n    at C:\\Users\\rb\\Sourcen\\ad\\app\\CronJobs\\IDR.js:55:13\n    at next (native)\n    at onFulfilled (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\co\\index.js:65:19)\n    at tryCatcher (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\util.js:26:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\promise.js:507:31)\n    at Promise._settlePromiseAt (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\promise.js:581:18)\n    at Promise._settlePromises (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\promise.js:697:14)\n    at Async._drainQueue (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\async.js:123:16)\n    at Async._drainQueues (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (C:\\Users\\rb\\Sourcen\\ad\\node_modules\\bluebird\\js\\main\\async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)'
`

if i let start the jobs with one second difference all runs fine:

```
Schedule.scheduleJob('0 */5 7-21 * * 1-6', function () {
 [...]

Schedule.scheduleJob('1 */5 7-21 * * 1-6', function () {
 [...]

Schedule.scheduleJob('2 */5 7-21 * * 1-6', function () {
 [...]

Schedule.scheduleJob('3 */5 7-21 * * 1-6', function () {
 [...]
```

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-lucid#20
