### ISSUE TITLE
List of file types for upload

### ISSUE THREAD

**Issue by jbrhinalyn** [adonisjs/adonis-framework#961]
Where can I find list of allowed types for file upload?

For video, i try this one but it says invalid parameter
var filename = request.file('filename', {
			types: ['video'],
			subtype: ['mp4'],
			size: '80mb'
		})

https://adonisjs.com/docs/4.1/file-uploads#_file_properties

**Comment by thetutlage** [comment]
Adding to docs here https://adonisjs.com/docs/4.1/file-uploads#_validation_options
