### ISSUE TITLE
node serve  problem

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/adonis-framework#962]
@mokhakifa commented on [Thu Sep 27 2018](https://github.com/adonisjs/adonis-lucid/issues/389)

hello every one why when start serve my project … it served 4 times
like the image below
i need to run hook that do some function when http server started
the function run but it run 4 times …

the version i use is 4.1
![image](https://user-images.githubusercontent.com/37499088/46146130-4a10d200-c262-11e8-87a0-b0e78cc41730.png)

**Comment by RomainLanz** [comment]
Hey @mokhakifa! 👋 

What's the content of this function?

**Comment by thetutlage** [comment]
Also can you share the content of `server.js` file?

**Comment by RomainLanz** [comment]
Seems solved. https://forum.adonisjs.com/t/adonis-serve-problem/1979/5
