### ISSUE TITLE
Parse env variables

### ISSUE THREAD

**Issue by vincentducorps** [adonisjs/adonis-framework#963]
## Package version
>  "version": "4.1.0",
>   "adonis-version": "4.1.0",

## Node.js and npm version

> NodeJS  v10.9.0
> npm 6.2.0

## Sample Code (to reproduce the issue)
Set `DB_DEBUG=false` will still continue to display queries in the console.
This is because env variables are not parsed.

This package seems to be created for: https://github.com/niftylettuce/dotenv-parse-variables

See also: https://github.com/adonisjs/adonis-framework/commit/00ff73f13d7a0a9179e6a61ff06a94d26f819f36#diff-e2625b4032ee326641919c5b7ae6f807

**Comment by thetutlage** [comment]
Closing since not actionable
