### ISSUE TITLE
How do I sort the migrations that need to be performed before others?

### ISSUE THREAD

**Issue by un-versed** [adonisjs/adonis-framework#964]
I have a migration (A) that depends on another migration (B), which is running right after. 
How can I sort so that, migration B runs before A?

**Comment by RomainLanz** [comment]
Hey @un-versed! 👋 

This is more a question than a bug, please, use the forum or our Discord server next time.

To give you an answer, Adonis sort those files by alphabetical order, this is why you have a timestamp before the name of the file.

You can then changes the timestamp to make it run before the other.

Take notice that you should never change the order if those migration has already been run in production. It would be preferable to create a new migration that change something or add something to your database.
