### ISSUE TITLE
Does Adonis support cluster mode?

### ISSUE THREAD

**Issue by spazer5** [adonisjs/adonis-framework#965]
I'm not using websockets, just want to enable cluster mode. I've tried changing server.js to something like this:

```
var cluster = require('cluster');
var http = require('http');
var numCPUs = 3;

if (cluster.isMaster) {
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on('exit', (worker) => {
        console.log('mayday! mayday! worker', worker.process.pid, ' is no more!')
        cluster.fork()
    })
} else {

  const { Ignitor } = require('@adonisjs/ignitor')

  new Ignitor(require('@adonisjs/fold'))
    .appRoot(__dirname)
    .fireHttpServer()
    .catch(console.error)

}
```

This indeed looks like it starts 3 servers on the console, but i tried printing `response.json({ pid: process.pid })` and it never changes when i refresh as if it's still just a single server

**Comment by thetutlage** [comment]
The cluster module of Node.js decides which node will receive the request. Ideally it is based upon [round robin](https://nodejs.org/api/cluster.html#cluster_cluster_schedulingpolicy) (unless you are on Windows). 

Try opening multiple tabs or windows and you will occasionally see the process.pid changing. 

Even a plain Node.js HTTP server behaves the same way.


```js
const http = require('http')
var cluster = require('cluster')
var numCPUs = 3

if (cluster.isMaster) {
  for (var i = 0; i < numCPUs; i++) {
    cluster.fork()
  }
  cluster.on('exit', (worker) => {
    console.log('mayday! mayday! worker', worker.process.pid, ' is no more!')
  })
} else {
	http.createServer((req, res) => {
		res.end(String(process.pid))
	}).listen(3000)
}
```
