### ISSUE TITLE
AdoNuxt: is possible using auth in nuxtServerInit

### ISSUE THREAD

**Issue by DJafari** [adonisjs/adonis-framework#966]
how can possible inject `auth` variable in `nuxtServerInit` ?
i test `use('Auth')` but return module not found

thanks

**Comment by RomainLanz** [comment]
Hey @DJafari! 👋 

You need to understand that everything inside nuxt will run on the client or on Nuxt server. Therefore, you cannot use Adonis eco-system inside.

Please, take a look at this forum post: https://forum.adonisjs.com/t/use-session-in-nuxt-store-nuxtserverinit/1965/2

**Comment by DJafari** [comment]
@RomainLanz thanks for your quick reply
i know that, but I wanted to avoid using ajax requests as much as possible

for example for Lucid Models, this trick works in `nuxtServerInit`

```
const User = use('App/Models/User');
```

not possible connect adonis with nuxt ? for example in `req.auth` or something like `use('Auth')` ?

i know that something usable only in server ( not client )

**Comment by DJafari** [comment]
i found a solution

**NuxtController** :
```
async render ({ request: { request: req }, response, session, auth }) {
    response.implicitEnd = false
    await session.commit()
    req.auth = auth
    await new Promise((resolve, reject) => {
      this.nuxt.render(req, response.response, promise => {
        promise.then(resolve).catch(reject)
      })
    })
  }
```

what's your idea ?

**Comment by RomainLanz** [comment]
You may want to check this code https://github.com/RomainLanz/adonuxt/blob/master/src/Nuxt.js

**Comment by RomainLanz** [comment]
The best would be none of them and create two separate apps.
If you really want to mix those context I recommend to open an issue in the Nuxt repository where you'll have more help.
