### ISSUE TITLE
Copy of file using Drive

### ISSUE THREAD

**Issue by jbrhinalyn** [adonisjs/adonis-framework#967]
Is it possible to use the Drive (File System) in a copying a file outside of the app directory?
The scenario is I uploaded a file then put it in the public folder.
I want to create a copy of that file and put it outside the app directory.
Is that possible?
Thanks.

**Comment by thetutlage** [comment]
Something to be discussed on the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)
