### ISSUE TITLE
Main domain routes available in subdomain

### ISSUE THREAD

**Issue by garciamarco33** [adonisjs/adonis-framework#971]
## Package version
4.1

## Node.js and npm version
8.9.1 and 6.4.1

## Problem
Hello,
I want to create a subdomain but my previous routes are available in this new subdomain.
Do I have to precise the domain of every routes from my main domain to avoid them to get available in the subdomain ?
Is this normal too ?
Thanks in advance,
Marco Garcia

**Comment by thetutlage** [comment]
Share some code please 🙏

**Comment by garciamarco33** [comment]
Ok sorry didn't think it was usefull.
I have all of my routes from my main domain like

` Route.get('/', ({ view }) => view.render('index'))`

And I'm adding a subdomain that we will call test with routes like

```
Route.group(() => {
  Route.get('/', ({ view }) => view.render('test/index'))
}).domain('test.maindomain.com')
```

And if i'm going on test.maindomain.com it will call the first route.

So my question is:
Is this normal and do I have to add to every routes => `.domain('maindomain.com')` ?

**Comment by garciamarco33** [comment]
Yes it work for the routes I have on both domain thanks
but my other routes that I only have in my maindomain are still available in the subdomain

**Comment by iedmrc** [comment]
please refer:
https://forum.adonisjs.com/t/routing-domains-doesnt-care-for-domain-while-routes-are-same/2178/4
