### ISSUE TITLE
Unable to set cookie when the response is returning json

### ISSUE THREAD

**Issue by hinng0302** [adonisjs/adonis-framework#972]
## Package version
adonis-fullstack-app: 4.1.0

## Node.js and npm version
Nodejs 8.9.0
Npm 6.4.1

## Sample Code (to reproduce the issue)
var ret = {
"profile": 123,
"breakpoint": [234.34, 234,52]
}
response.cookie('Set-Cookie', '12,24,36').json(ret)

![screen shot 2018-10-04 at 3 14 44 pm](https://user-images.githubusercontent.com/32009170/46458418-4d6b0700-c7e8-11e8-95c5-483f4d825f94.png)

**Comment by hinng0302** [comment]
if i using the code below:
response.header('Set-Cookie', 'cookie=testing;').json(ret)

![screen shot 2018-10-04 at 3 19 08 pm](https://user-images.githubusercontent.com/32009170/46458584-df730f80-c7e8-11e8-9a5e-207d4f8516a2.png)

**Comment by thetutlage** [comment]
Asking the same question everywhere will not help. Closing in favour of discord question
