### ISSUE TITLE
How to configure eslint and prettier?

### ISSUE THREAD

**Issue by hansiemithun** [adonisjs/adonis-framework#973]
Trying to configure the eslint and prettier, but there are many global variables defined. Can you please guide how to set up the same to support for vscode as a default editor

**Comment by RomainLanz** [comment]
Hey @hansiemithun! 👋 

Please, use the forum or our Discord server for this kind of question.
This is not an issue with Adonis nor in the scope of Adonis.

If you want to use `eslint` and `prettier` you must learn those tool and check their documentation first.
