### ISSUE TITLE
wantsJson function

### ISSUE THREAD

**Issue by Ali-Azmoud** [adonisjs/adonis-framework#974]
Hi

`Laravel` has a function called `wantsJson` which uses the `Accept` header sent by the client to know if client wants json response or not

I couldn't find this function in adonisjs, I know it's easy to implement it but I think it would be a good feature in the next version of adonis js.

**Comment by thetutlage** [comment]
Get into the habit of reading the docs https://adonisjs.com/docs/4.1/request#_content_negotiation and **ADONIS JS IS NOT A CLONE OF LARAVEL**, so please don't expect all of the methods to have same name **PLEASE**
