### ISSUE TITLE
Using {{route()}} not return to localhost

### ISSUE THREAD

**Issue by mlazuardy** [adonisjs/adonis-framework#975]
## Package version
Latest adonis

## Node.js and npm version
LTS 

## Sample Code (to reproduce the issue)
using
```
{{route('as')}}
```
on mailtrap.io to verified user email not return to http://localhost:port , but return to mailtrap domain itself
```

**Comment by thetutlage** [comment]
Something to be discussed on the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)
