### ISSUE TITLE
MySQL lock in share mode

### ISSUE THREAD

**Issue by clayderson** [adonisjs/adonis-framework#976]
Hello!

How could I perform a SELECT with the MySQL LOCK IN SHARE MODE parameter to ensure that the returned data will always be the latest if an UPDATE is in progress at the time the SELECT was issued?

**Comment by thetutlage** [comment]
Please make sure to refer the knex docs, since this is what AdonisJs uses internally https://knexjs.org/#Builder-forShare

Also please try to use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?) for generic questions (which are not confirmed bugs)
