### ISSUE TITLE
How to load two data in Mail.send

### ISSUE THREAD

**Issue by mlazuardy** [adonisjs/adonis-framework#977]
## Package version
Latest

## Node.js and npm version
LTS

## Sample Code (to reproduce the issue)
how to use Mail.send and send two data in view
```
Event.on('new::blog', async (blog,user) => {
  await Mail.send('emails.blog', (one,two),(message) => {
    message
    .to(user.email)
    .from('from@email')
    .subject(`${blog.title} has been created`)
  })
```
i mean the one , two can be injected as variable in edge template. the code above didnt return anything

**Comment by thetutlage** [comment]
This is not a question related to AdonisJs, it's a general programming question. So please do not create issues for same on Github and instead use [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


Just to answer, you pass multiple arguments as an object

```js
await Mail.send('emails.blog', { one,two },(message) => {
 
})
```

And access it inside the views as follows

```edge
{{ one }}

{{ two }}
```
