### ISSUE TITLE
uploading image in Lucid Hooks

### ISSUE THREAD

**Issue by DJafari** [adonisjs/adonis-framework#978]
in laravel we can upload image in model hooks by something like :

```php
Category::create($request->only(['name', 'image']);
```

```php
.
.
.
self::saving(function($model) {
    if($model->image instanceof UploadedFile) {
        // UPLOADING IMAGE AND SET TO MODEL PROPERTY
        $model->image = $fullPath;
    }
});
.
.
.
```

is possible having something like in adonis ? it's useful for avoid duplicate code

currently in adonis `request.only(['name', 'image'])` not detect file field

**Comment by thetutlage** [comment]
Something to be discussed on the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)

**Comment by DJafari** [comment]
@thetutlage i searched before create feature request, can you give me link ?

thanks

**Comment by thetutlage** [comment]
@DJafari I closed the issue, coz it's not a bug and neither a feature request. I suggest asking questions on the Forum or discord, since it helps me and the team focus on real issues on Github
