### ISSUE TITLE
wsServer is not a function

### ISSUE THREAD

**Issue by webkostya** [adonisjs/adonis-framework#979]
**TypeError:** (intermediate value).appRoot(...).fireHttpServer(...).wsServer is not a function

![2018-10-17 14 26 40](https://user-images.githubusercontent.com/5229018/47083388-126dc800-d219-11e8-93c9-ccb6741236ae.png)

**Comment by thetutlage** [comment]
Have u installed and registered the Websocket provider? https://adonisjs.com/docs/4.1/websocket#_setup

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
