### ISSUE TITLE
Versioning past 4.1

### ISSUE THREAD

**Issue by jakesyl** [adonisjs/adonis-framework#981]
I noticed that when adonis was upgraded from `4.0` to `4.1`the package was bumped to [5.0.0](https://github.com/adonisjs/adonis-framework/commit/86e22829627bf2c06dd7336da11dff4088a130c4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L4). I was wondering why this was done and if the plan is to continue.

**Comment by RomainLanz** [comment]
Hey @jakesyl! 👋 

Each module of Adonis follows semver and its own.
You are using Adonis Lucid 6.0 while using Adonis 4.1 for example.

Here's an RFC on same https://github.com/adonisjs/rfcs/issues/12

**Comment by thetutlage** [comment]
@jakesyl Yes, it’s bit confusing. I suggest going through the RFC shared by @romainLanz and especially this comment https://github.com/adonisjs/rfcs/issues/12#issuecomment-427882012

**Comment by jakesyl** [comment]
Got it!
