### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by nicopenaredondo** [adonisjs/adonis-framework#982]
How do i process a file upload in adonisJS ? I've tried to follow the steps in the documentation but i get an empty field upon submitting the form

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server (https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
