### ISSUE TITLE
Data is lost between Middleware and request.post()

### ISSUE THREAD

**Issue by pawelsas** [adonisjs/adonis-framework#986]
I have a route /job/:id
I use middleware **FindJob** to fetch the job and to append it to the request body.
The **JobController** extracts the job of the request body and does further processing.

In the FindJob middleware everything is fine. The log show the job.
When I do console log in my JobController, the job is undefined.

## Package version
5.0.12

## Node.js and npm version
8.11 and 6.4

### routes.js
```
'use strict'

const Route = use('Route')
const Next = use('Adonis/Addons/Next')
const handler = Next.getRequestHandler()

// ==============================================
// API Routes:

Route.group(() => {
  // Jobs:
  Route.get('jobs', 'JobController.index')
  Route.get('jobs/:id', 'JobController.show').middleware(['findJob'])
  Route.post('jobs', 'JobController.store')
  Route.patch('jobs/:id', 'JobController.update').middleware(['findJob'])
  Route.delete('jobs/:id', 'JobController.destroy').middleware(['findJob'])

// ==============================================
// Default:

Route.get(
  '*',
  ({ request, response }) =>
    new Promise((resolve, reject) => {
      handler(request.request, response.response, promise => {
        promise.then(resolve).catch(reject)
      })
    })
)

```

### FindJob.js
```
const Job = use('App/Models/Job')

// ================================================================================================

class FindJob {
  async handle(
    {
      request,
      response,
      params: { id }
    },
    next
  ) {
    const job = await Job.find(id)

    if (!job) {
      return response.status(404).json({
        message: 'Job not found.',
        id
      })
    }

    request.body.job = job

    await next()
  }
}

// ================================================================================================

module.exports = FindJob
```

### JobController.js (excerpt)
```
  async show({ request, response }) {
    try {
      const { job } = request.post()

      // job log is undefined
```

### kernel.js (excerpt)
```
const namedMiddleware = {
  findJob: 'App/Middleware/FindJob',
```

Any help is highly appreciated.
Thanks!

**Comment by thetutlage** [comment]
When you are finding the `job`, don't attach it to the request body, since it is not something sent by the user. Try to keep it clear for yourself or for others working on the code. Simply attach it to `ctx`

```js
async handle(ctx, next) {
  ctx.job = job
  await next()
}
```

**Comment by pawelsas** [comment]
Wow, that simple.
Thanks!

**Comment by MaxBernard** [comment]
How do you access the 'job' in the controller?  Simply doing 
const { job } = request.post()
returns 'Undefined'.

**Comment by pawelsas** [comment]
@MaxBernard did you setup the FindJob middleware? The job is passed to the body over there.

**Comment by MaxBernard** [comment]
Yes, I did.  Can you share some code showing how you access the job in the controller?

**Comment by pawelsas** [comment]
Sorry, I was wrong. The job is passed to the context NOT to the body. You can destructure it like the request.

```
async someFunc({ job, request }) {
    // do so something with job...
  }
```

**Comment by MaxBernard** [comment]
Thanks Pawel.
