### ISSUE TITLE
use socket instead websocket

### ISSUE THREAD

**Issue by annymosse** [adonisjs/adonis-framework#988]
how can i use simple secket coz the websocket provider doesnt work with my `golang` code even in `python` and when i tried to use `socket.io` i had lots of troubles and issues,when i work with the `websocket client` and `websocket server` its work well ,the problem is i couldnt make a `websocket client` alternative for other languages like `golang,lua,java...`
(sorry for my bad language)

**Comment by thetutlage** [comment]
Do not use the inbuilt AdonisJs websocket server then and use https://github.com/websockets/ws. It is the bare bones implementation of the Websocket server in Node.

Ofcourse, you don't get things like `Channels`, `Topics` with it, since Websocket as a protocol has no support for them too
