### ISSUE TITLE
can not work dynamic subdomain

### ISSUE THREAD

**Issue by msadeghifard1989** [adonisjs/adonis-framework#989]
## Note

You choose to create an issue, which is not a bug and neither a feature request. We recommend using [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs) for same.

Continue, if you think that your issue needs to be on Github.

*Delete the above section before submitting*

**Comment by msadeghifard1989** [comment]
hi 
thanks for the great framework
{
Is there a way to make the server listen to a dynamic domain name? I want to make my users able to forward their domains to my service and I know which domain is currently being used.
}
this link
https://github.com/adonisjs/adonis-framework/issues/503#issue-212676983

this route : 
Can not recognize:
http://ms.192.168.43.63:3333

Route.group('my-group', async () =>{
  Route.get('posts',  async (request, response) =>{

    return "hi";
  })
}).domain(':domain')

please help me

**Comment by RomainLanz** [comment]
Hey @msadeghifard1989! 👋 

You cannot use dynamic domain if you are using an IP address to bind your app.
Edit your `host` file and add the binding yourself.

Also, for this kind of question, you should use our [Forum](https://forum.adonisjs.com/) or [Discord Server](https://discord.gg/vDcEjq6).
