### ISSUE TITLE
Bug in request.multipart.field

### ISSUE THREAD

**Issue by un-versed** [adonisjs/adonis-framework#992]
I'm trying to use the example i found in #851 , but seems broken.

The ```body``` var is still empty, and i have a lot of multipart fields in my request.

Anyone knows how to solve it?

```
/**
   * Create/save a new invoice.
   * POST invoices
   */
  async store ({ params, request, response, auth }) {
    var body = {}
    request.multipart.field((name, value) => {
      console.log(name)
      console.log(value)
      body[name] = value
    })

    console.log(request.body)
    console.log(body)
}
```

**Comment by thetutlage** [comment]
This is what you are missing

<img width="646" alt="screenshot 2018-10-30 at 10 33 22 am" src="https://user-images.githubusercontent.com/1706381/47708838-42609680-dc2f-11e8-8631-ca9ca6bd665c.png">

**Comment by begueradj** [comment]
How did you find about `request.multipart.field()` by yourself? it is not mentioned in the documentation @un-versed

**Comment by begueradj** [comment]
I wonder why `request.multipart.process()` works only POST but not in PATCH ?

**Comment by Tequelequeteque** [comment]
You can use `request.post()` for only fields
