### ISSUE TITLE
How to check a column existence in controller

### ISSUE THREAD

**Issue by behnamazimi** [adonisjs/adonis-framework#994]
I want to check a column existence in my code. 
This functionality works truly in migrations but not in controllers.  

### What I tried
As mentioned in the **knex** docs, the `hasColumn` method belongs to the `schema`. I added const `Schema = use('Schema')` to the controller but I faced this error,
> Cannot find module 'Schema'

What should I do?

**Comment by thetutlage** [comment]
You can use `Database.schema.hasColumn`.

Also you can use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?) in future to get quick replies on generic questions, which are not yet classified as bugs

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
