### ISSUE TITLE
Adda direct link to Github from Adonis Homepage

### ISSUE THREAD

**Issue by SNaushadS** [adonisjs/adonis-framework#995]
Not a bug neither a Feature. This is just a feedback about adonis homepage.

I saw the design request on opensourcedesign jobs > checked adonis site > found that the Github repo link is hidden 3 layers.

I understand developers would benefit if the github link is available quicker. User has to click on Get Started and at the lower end section there is a small text link.

As compared to other framework sites, where github star button and repo link are readily available without any interaction.

Example : React Js
Look at the explicit Github Link in top right.

![image](https://user-images.githubusercontent.com/1532907/47950690-baa2c100-df7b-11e8-81e5-b1285b3a9de6.png)

**Comment by ShadowPaz** [comment]
this proposal must to be comment on discord channel or the adonis forum, since this is not a bug

**Comment by tlgreg** [comment]
Its okay as an issue I think, but should be on [adonisjs/adonisjs.com](https://github.com/adonisjs/adonisjs.com)

**Comment by ShadowPaz** [comment]
an issue is problem about the normal function of a piece of software and this ins't it @tlgreg

**Comment by SNaushadS** [comment]
@tlgreg that make . but i'm not sure if i can move this to that repo. I'm not so familiar with Github, so when i visited the Adonisjs Github page, i saw only these repos, so added the feedback in the closest repo.
![image](https://user-images.githubusercontent.com/1532907/47961944-58f55c00-e03a-11e8-8869-bb1e0c043226.png)

Later i realised that these are Pinned ones and there are multiple repos below the scroll.

Your call on where to have it. Thanks

**Comment by SNaushadS** [comment]
Created new issue in AdonisJS.com repo. Closing.
