### ISSUE TITLE
Error: Request failed with status code 504

### ISSUE THREAD

**Issue by enxoco** [adonisjs/adonis-framework#996]
I have an api that I am using in production.  I created it using adonis new api --api-only.  It has been running great in production for over 6 months now but today after adding a couple more lines of code.  I started noticing some errors.  Now whenever I make a request to it I am getting the following error in my browser.

Error: Request failed with status code 504

I get the same thing if I try to hit this route via curl or Postman.  From what I can figure it seems to be a timeout issue with Node but I am not sure where to adjust this.  On my development machine I am just running
 ```
nodemon server.js
```

The purpose of the api is to parse over some proxy log files that are stored on a server.  Basically I am converting a csv file to JSON and then performing some sanitation and analysis of the data.  The code that I added this morning is a simple if statement that tries to identify certain patterns in a url.  I know that it is not the code that is causing a problem but more likely an issue with the request taking a long time to run. 

# Node.js and npm version
nodejs - v8.12.0
npm - 6.4.1

**Comment by thetutlage** [comment]
I don't think, that there is any magical way for us to know what lines of code you added and why it's giving `504`. 

You have to debug the app yourself and report specific issues, if found any

**Comment by thetutlage** [comment]
@enxoco Okay, then it's a different issue all together and still there are some unknowns here.

1. Do you have any proxy `(maybe nginx)` in front of your node app? If yes, then maybe that proxy is timing out.
2. If you are sure that proxy server is not timing out, then you can increase the request timeout as mentioned here. https://nodejs.org/docs/latest-v8.x/api/http.html#http_message_settimeout_msecs_callback.

```js
request.request.setTimeout(0) // disabled
```
